/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Agra Taj Heritage Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const AGRA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 27.1767,
  longitude: 78.0081,
};

export const AGRA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-agr-1-1',
    name: 'Fatehabad Road Sector 1 High Street',
    zone: 'Fatehabad Road',
    location: { latitude: 27.114700, longitude: 77.956100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fatehabad Road.',
  },
  {
    id: 'node-agr-1-2',
    name: 'Fatehabad Road Sector 2 High Street',
    zone: 'Fatehabad Road',
    location: { latitude: 27.117700, longitude: 77.959100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fatehabad Road.',
  },
  {
    id: 'node-agr-1-3',
    name: 'Fatehabad Road Sector 3 High Street',
    zone: 'Fatehabad Road',
    location: { latitude: 27.120700, longitude: 77.962100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fatehabad Road.',
  },
  {
    id: 'node-agr-2-1',
    name: 'Sanjay Place Sector 1 High Street',
    zone: 'Sanjay Place',
    location: { latitude: 27.126700, longitude: 77.966100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sanjay Place.',
  },
  {
    id: 'node-agr-2-2',
    name: 'Sanjay Place Sector 2 High Street',
    zone: 'Sanjay Place',
    location: { latitude: 27.129700, longitude: 77.969100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sanjay Place.',
  },
  {
    id: 'node-agr-2-3',
    name: 'Sanjay Place Sector 3 High Street',
    zone: 'Sanjay Place',
    location: { latitude: 27.132700, longitude: 77.972100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sanjay Place.',
  },
  {
    id: 'node-agr-3-1',
    name: 'Civil Lines Sector 1 High Street',
    zone: 'Civil Lines',
    location: { latitude: 27.138700, longitude: 77.976100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-agr-3-2',
    name: 'Civil Lines Sector 2 High Street',
    zone: 'Civil Lines',
    location: { latitude: 27.141700, longitude: 77.979100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-agr-3-3',
    name: 'Civil Lines Sector 3 High Street',
    zone: 'Civil Lines',
    location: { latitude: 27.144700, longitude: 77.982100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-agr-4-1',
    name: 'Tajganj Sector 1 High Street',
    zone: 'Tajganj',
    location: { latitude: 27.150700, longitude: 77.986100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tajganj.',
  },
  {
    id: 'node-agr-4-2',
    name: 'Tajganj Sector 2 High Street',
    zone: 'Tajganj',
    location: { latitude: 27.153700, longitude: 77.989100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tajganj.',
  },
  {
    id: 'node-agr-4-3',
    name: 'Tajganj Sector 3 High Street',
    zone: 'Tajganj',
    location: { latitude: 27.156700, longitude: 77.992100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tajganj.',
  },
  {
    id: 'node-agr-5-1',
    name: 'Kamla Nagar Sector 1 High Street',
    zone: 'Kamla Nagar',
    location: { latitude: 27.162700, longitude: 77.996100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kamla Nagar.',
  },
  {
    id: 'node-agr-5-2',
    name: 'Kamla Nagar Sector 2 High Street',
    zone: 'Kamla Nagar',
    location: { latitude: 27.165700, longitude: 77.999100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kamla Nagar.',
  },
  {
    id: 'node-agr-5-3',
    name: 'Kamla Nagar Sector 3 High Street',
    zone: 'Kamla Nagar',
    location: { latitude: 27.168700, longitude: 78.002100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kamla Nagar.',
  },
  {
    id: 'node-agr-6-1',
    name: 'Dayalbagh Sector 1 High Street',
    zone: 'Dayalbagh',
    location: { latitude: 27.174700, longitude: 78.006100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dayalbagh.',
  },
  {
    id: 'node-agr-6-2',
    name: 'Dayalbagh Sector 2 High Street',
    zone: 'Dayalbagh',
    location: { latitude: 27.177700, longitude: 78.009100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dayalbagh.',
  },
  {
    id: 'node-agr-6-3',
    name: 'Dayalbagh Sector 3 High Street',
    zone: 'Dayalbagh',
    location: { latitude: 27.180700, longitude: 78.012100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dayalbagh.',
  },
  {
    id: 'node-agr-7-1',
    name: 'Khandari Sector 1 High Street',
    zone: 'Khandari',
    location: { latitude: 27.186700, longitude: 78.016100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Khandari.',
  },
  {
    id: 'node-agr-7-2',
    name: 'Khandari Sector 2 High Street',
    zone: 'Khandari',
    location: { latitude: 27.189700, longitude: 78.019100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Khandari.',
  },
  {
    id: 'node-agr-7-3',
    name: 'Khandari Sector 3 High Street',
    zone: 'Khandari',
    location: { latitude: 27.192700, longitude: 78.022100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Khandari.',
  },
  {
    id: 'node-agr-8-1',
    name: 'Sikandra Sector 1 High Street',
    zone: 'Sikandra',
    location: { latitude: 27.198700, longitude: 78.026100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sikandra.',
  },
  {
    id: 'node-agr-8-2',
    name: 'Sikandra Sector 2 High Street',
    zone: 'Sikandra',
    location: { latitude: 27.201700, longitude: 78.029100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sikandra.',
  },
  {
    id: 'node-agr-8-3',
    name: 'Sikandra Sector 3 High Street',
    zone: 'Sikandra',
    location: { latitude: 27.204700, longitude: 78.032100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sikandra.',
  },
  {
    id: 'node-agr-9-1',
    name: 'Shahganj Sector 1 High Street',
    zone: 'Shahganj',
    location: { latitude: 27.210700, longitude: 78.036100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shahganj.',
  },
  {
    id: 'node-agr-9-2',
    name: 'Shahganj Sector 2 High Street',
    zone: 'Shahganj',
    location: { latitude: 27.213700, longitude: 78.039100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shahganj.',
  },
  {
    id: 'node-agr-9-3',
    name: 'Shahganj Sector 3 High Street',
    zone: 'Shahganj',
    location: { latitude: 27.216700, longitude: 78.042100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shahganj.',
  },
  {
    id: 'node-agr-10-1',
    name: 'Belanganj Sector 1 High Street',
    zone: 'Belanganj',
    location: { latitude: 27.222700, longitude: 78.046100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Belanganj.',
  },
  {
    id: 'node-agr-10-2',
    name: 'Belanganj Sector 2 High Street',
    zone: 'Belanganj',
    location: { latitude: 27.225700, longitude: 78.049100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Belanganj.',
  },
  {
    id: 'node-agr-10-3',
    name: 'Belanganj Sector 3 High Street',
    zone: 'Belanganj',
    location: { latitude: 27.228700, longitude: 78.052100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Belanganj.',
  },
];

export const AGRA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-agr-1',
    fromNodeId: 'node-agr-1-1',
    toNodeId: 'node-agr-1-2',
    roadName: 'Fatehabad Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-2',
    fromNodeId: 'node-agr-1-2',
    toNodeId: 'node-agr-1-3',
    roadName: 'Fatehabad Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-3',
    fromNodeId: 'node-agr-2-1',
    toNodeId: 'node-agr-2-2',
    roadName: 'Sanjay Place Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-4',
    fromNodeId: 'node-agr-2-2',
    toNodeId: 'node-agr-2-3',
    roadName: 'Sanjay Place Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-5',
    fromNodeId: 'node-agr-3-1',
    toNodeId: 'node-agr-3-2',
    roadName: 'Civil Lines Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-6',
    fromNodeId: 'node-agr-3-2',
    toNodeId: 'node-agr-3-3',
    roadName: 'Civil Lines Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-7',
    fromNodeId: 'node-agr-4-1',
    toNodeId: 'node-agr-4-2',
    roadName: 'Tajganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-8',
    fromNodeId: 'node-agr-4-2',
    toNodeId: 'node-agr-4-3',
    roadName: 'Tajganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-9',
    fromNodeId: 'node-agr-5-1',
    toNodeId: 'node-agr-5-2',
    roadName: 'Kamla Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-10',
    fromNodeId: 'node-agr-5-2',
    toNodeId: 'node-agr-5-3',
    roadName: 'Kamla Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-11',
    fromNodeId: 'node-agr-6-1',
    toNodeId: 'node-agr-6-2',
    roadName: 'Dayalbagh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-12',
    fromNodeId: 'node-agr-6-2',
    toNodeId: 'node-agr-6-3',
    roadName: 'Dayalbagh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-13',
    fromNodeId: 'node-agr-7-1',
    toNodeId: 'node-agr-7-2',
    roadName: 'Khandari Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-14',
    fromNodeId: 'node-agr-7-2',
    toNodeId: 'node-agr-7-3',
    roadName: 'Khandari Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-15',
    fromNodeId: 'node-agr-8-1',
    toNodeId: 'node-agr-8-2',
    roadName: 'Sikandra Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-16',
    fromNodeId: 'node-agr-8-2',
    toNodeId: 'node-agr-8-3',
    roadName: 'Sikandra Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-17',
    fromNodeId: 'node-agr-9-1',
    toNodeId: 'node-agr-9-2',
    roadName: 'Shahganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-18',
    fromNodeId: 'node-agr-9-2',
    toNodeId: 'node-agr-9-3',
    roadName: 'Shahganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-19',
    fromNodeId: 'node-agr-10-1',
    toNodeId: 'node-agr-10-2',
    roadName: 'Belanganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-agr-20',
    fromNodeId: 'node-agr-10-2',
    toNodeId: 'node-agr-10-3',
    roadName: 'Belanganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
