/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Ahmedabad Urban Area
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const AHMEDABAD_BASE_COORDINATE: GeoCoordinate = {
  latitude: 23.0225,
  longitude: 72.5714,
};

export const AHMEDABAD_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ahm-1-1',
    name: 'Navrangpura Sector 1 High Street',
    zone: 'Navrangpura',
    location: { latitude: 22.960500, longitude: 72.519400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Navrangpura.',
  },
  {
    id: 'node-ahm-1-2',
    name: 'Navrangpura Sector 2 High Street',
    zone: 'Navrangpura',
    location: { latitude: 22.963500, longitude: 72.522400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Navrangpura.',
  },
  {
    id: 'node-ahm-1-3',
    name: 'Navrangpura Sector 3 High Street',
    zone: 'Navrangpura',
    location: { latitude: 22.966500, longitude: 72.525400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Navrangpura.',
  },
  {
    id: 'node-ahm-2-1',
    name: 'Satellite Sector 1 High Street',
    zone: 'Satellite',
    location: { latitude: 22.972500, longitude: 72.529400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Satellite.',
  },
  {
    id: 'node-ahm-2-2',
    name: 'Satellite Sector 2 High Street',
    zone: 'Satellite',
    location: { latitude: 22.975500, longitude: 72.532400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Satellite.',
  },
  {
    id: 'node-ahm-2-3',
    name: 'Satellite Sector 3 High Street',
    zone: 'Satellite',
    location: { latitude: 22.978500, longitude: 72.535400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Satellite.',
  },
  {
    id: 'node-ahm-3-1',
    name: 'Bodakdev Sector 1 High Street',
    zone: 'Bodakdev',
    location: { latitude: 22.984500, longitude: 72.539400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bodakdev.',
  },
  {
    id: 'node-ahm-3-2',
    name: 'Bodakdev Sector 2 High Street',
    zone: 'Bodakdev',
    location: { latitude: 22.987500, longitude: 72.542400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bodakdev.',
  },
  {
    id: 'node-ahm-3-3',
    name: 'Bodakdev Sector 3 High Street',
    zone: 'Bodakdev',
    location: { latitude: 22.990500, longitude: 72.545400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bodakdev.',
  },
  {
    id: 'node-ahm-4-1',
    name: 'Vastrapur Sector 1 High Street',
    zone: 'Vastrapur',
    location: { latitude: 22.996500, longitude: 72.549400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vastrapur.',
  },
  {
    id: 'node-ahm-4-2',
    name: 'Vastrapur Sector 2 High Street',
    zone: 'Vastrapur',
    location: { latitude: 22.999500, longitude: 72.552400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vastrapur.',
  },
  {
    id: 'node-ahm-4-3',
    name: 'Vastrapur Sector 3 High Street',
    zone: 'Vastrapur',
    location: { latitude: 23.002500, longitude: 72.555400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vastrapur.',
  },
  {
    id: 'node-ahm-5-1',
    name: 'Prahlad Nagar Sector 1 High Street',
    zone: 'Prahlad Nagar',
    location: { latitude: 23.008500, longitude: 72.559400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Prahlad Nagar.',
  },
  {
    id: 'node-ahm-5-2',
    name: 'Prahlad Nagar Sector 2 High Street',
    zone: 'Prahlad Nagar',
    location: { latitude: 23.011500, longitude: 72.562400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Prahlad Nagar.',
  },
  {
    id: 'node-ahm-5-3',
    name: 'Prahlad Nagar Sector 3 High Street',
    zone: 'Prahlad Nagar',
    location: { latitude: 23.014500, longitude: 72.565400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Prahlad Nagar.',
  },
  {
    id: 'node-ahm-6-1',
    name: 'Maninagar Sector 1 High Street',
    zone: 'Maninagar',
    location: { latitude: 23.020500, longitude: 72.569400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Maninagar.',
  },
  {
    id: 'node-ahm-6-2',
    name: 'Maninagar Sector 2 High Street',
    zone: 'Maninagar',
    location: { latitude: 23.023500, longitude: 72.572400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Maninagar.',
  },
  {
    id: 'node-ahm-6-3',
    name: 'Maninagar Sector 3 High Street',
    zone: 'Maninagar',
    location: { latitude: 23.026500, longitude: 72.575400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Maninagar.',
  },
  {
    id: 'node-ahm-7-1',
    name: 'Paldi Sector 1 High Street',
    zone: 'Paldi',
    location: { latitude: 23.032500, longitude: 72.579400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Paldi.',
  },
  {
    id: 'node-ahm-7-2',
    name: 'Paldi Sector 2 High Street',
    zone: 'Paldi',
    location: { latitude: 23.035500, longitude: 72.582400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Paldi.',
  },
  {
    id: 'node-ahm-7-3',
    name: 'Paldi Sector 3 High Street',
    zone: 'Paldi',
    location: { latitude: 23.038500, longitude: 72.585400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Paldi.',
  },
  {
    id: 'node-ahm-8-1',
    name: 'Ghatlodia Sector 1 High Street',
    zone: 'Ghatlodia',
    location: { latitude: 23.044500, longitude: 72.589400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ghatlodia.',
  },
  {
    id: 'node-ahm-8-2',
    name: 'Ghatlodia Sector 2 High Street',
    zone: 'Ghatlodia',
    location: { latitude: 23.047500, longitude: 72.592400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ghatlodia.',
  },
  {
    id: 'node-ahm-8-3',
    name: 'Ghatlodia Sector 3 High Street',
    zone: 'Ghatlodia',
    location: { latitude: 23.050500, longitude: 72.595400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ghatlodia.',
  },
  {
    id: 'node-ahm-9-1',
    name: 'SG Highway Sector 1 High Street',
    zone: 'SG Highway',
    location: { latitude: 23.056500, longitude: 72.599400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in SG Highway.',
  },
  {
    id: 'node-ahm-9-2',
    name: 'SG Highway Sector 2 High Street',
    zone: 'SG Highway',
    location: { latitude: 23.059500, longitude: 72.602400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in SG Highway.',
  },
  {
    id: 'node-ahm-9-3',
    name: 'SG Highway Sector 3 High Street',
    zone: 'SG Highway',
    location: { latitude: 23.062500, longitude: 72.605400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in SG Highway.',
  },
  {
    id: 'node-ahm-10-1',
    name: 'Thaltej Sector 1 High Street',
    zone: 'Thaltej',
    location: { latitude: 23.068500, longitude: 72.609400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Thaltej.',
  },
  {
    id: 'node-ahm-10-2',
    name: 'Thaltej Sector 2 High Street',
    zone: 'Thaltej',
    location: { latitude: 23.071500, longitude: 72.612400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Thaltej.',
  },
  {
    id: 'node-ahm-10-3',
    name: 'Thaltej Sector 3 High Street',
    zone: 'Thaltej',
    location: { latitude: 23.074500, longitude: 72.615400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Thaltej.',
  },
];

export const AHMEDABAD_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ahm-1',
    fromNodeId: 'node-ahm-1-1',
    toNodeId: 'node-ahm-1-2',
    roadName: 'Navrangpura Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-2',
    fromNodeId: 'node-ahm-1-2',
    toNodeId: 'node-ahm-1-3',
    roadName: 'Navrangpura Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-3',
    fromNodeId: 'node-ahm-2-1',
    toNodeId: 'node-ahm-2-2',
    roadName: 'Satellite Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-4',
    fromNodeId: 'node-ahm-2-2',
    toNodeId: 'node-ahm-2-3',
    roadName: 'Satellite Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-5',
    fromNodeId: 'node-ahm-3-1',
    toNodeId: 'node-ahm-3-2',
    roadName: 'Bodakdev Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-6',
    fromNodeId: 'node-ahm-3-2',
    toNodeId: 'node-ahm-3-3',
    roadName: 'Bodakdev Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-7',
    fromNodeId: 'node-ahm-4-1',
    toNodeId: 'node-ahm-4-2',
    roadName: 'Vastrapur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-8',
    fromNodeId: 'node-ahm-4-2',
    toNodeId: 'node-ahm-4-3',
    roadName: 'Vastrapur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-9',
    fromNodeId: 'node-ahm-5-1',
    toNodeId: 'node-ahm-5-2',
    roadName: 'Prahlad Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-10',
    fromNodeId: 'node-ahm-5-2',
    toNodeId: 'node-ahm-5-3',
    roadName: 'Prahlad Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-11',
    fromNodeId: 'node-ahm-6-1',
    toNodeId: 'node-ahm-6-2',
    roadName: 'Maninagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-12',
    fromNodeId: 'node-ahm-6-2',
    toNodeId: 'node-ahm-6-3',
    roadName: 'Maninagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-13',
    fromNodeId: 'node-ahm-7-1',
    toNodeId: 'node-ahm-7-2',
    roadName: 'Paldi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-14',
    fromNodeId: 'node-ahm-7-2',
    toNodeId: 'node-ahm-7-3',
    roadName: 'Paldi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-15',
    fromNodeId: 'node-ahm-8-1',
    toNodeId: 'node-ahm-8-2',
    roadName: 'Ghatlodia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-16',
    fromNodeId: 'node-ahm-8-2',
    toNodeId: 'node-ahm-8-3',
    roadName: 'Ghatlodia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-17',
    fromNodeId: 'node-ahm-9-1',
    toNodeId: 'node-ahm-9-2',
    roadName: 'SG Highway Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-18',
    fromNodeId: 'node-ahm-9-2',
    toNodeId: 'node-ahm-9-3',
    roadName: 'SG Highway Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-19',
    fromNodeId: 'node-ahm-10-1',
    toNodeId: 'node-ahm-10-2',
    roadName: 'Thaltej Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ahm-20',
    fromNodeId: 'node-ahm-10-2',
    toNodeId: 'node-ahm-10-3',
    roadName: 'Thaltej Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
