/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Prayagraj Sangam Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const ALLAHABAD_BASE_COORDINATE: GeoCoordinate = {
  latitude: 25.4358,
  longitude: 81.8463,
};

export const ALLAHABAD_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-all-1-1',
    name: 'Civil Lines Sector 1 High Street',
    zone: 'Civil Lines',
    location: { latitude: 25.373800, longitude: 81.794300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-all-1-2',
    name: 'Civil Lines Sector 2 High Street',
    zone: 'Civil Lines',
    location: { latitude: 25.376800, longitude: 81.797300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-all-1-3',
    name: 'Civil Lines Sector 3 High Street',
    zone: 'Civil Lines',
    location: { latitude: 25.379800, longitude: 81.800300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-all-2-1',
    name: 'George Town Sector 1 High Street',
    zone: 'George Town',
    location: { latitude: 25.385800, longitude: 81.804300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in George Town.',
  },
  {
    id: 'node-all-2-2',
    name: 'George Town Sector 2 High Street',
    zone: 'George Town',
    location: { latitude: 25.388800, longitude: 81.807300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in George Town.',
  },
  {
    id: 'node-all-2-3',
    name: 'George Town Sector 3 High Street',
    zone: 'George Town',
    location: { latitude: 25.391800, longitude: 81.810300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in George Town.',
  },
  {
    id: 'node-all-3-1',
    name: 'Katra Sector 1 High Street',
    zone: 'Katra',
    location: { latitude: 25.397800, longitude: 81.814300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Katra.',
  },
  {
    id: 'node-all-3-2',
    name: 'Katra Sector 2 High Street',
    zone: 'Katra',
    location: { latitude: 25.400800, longitude: 81.817300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Katra.',
  },
  {
    id: 'node-all-3-3',
    name: 'Katra Sector 3 High Street',
    zone: 'Katra',
    location: { latitude: 25.403800, longitude: 81.820300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Katra.',
  },
  {
    id: 'node-all-4-1',
    name: 'Tagore Town Sector 1 High Street',
    zone: 'Tagore Town',
    location: { latitude: 25.409800, longitude: 81.824300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tagore Town.',
  },
  {
    id: 'node-all-4-2',
    name: 'Tagore Town Sector 2 High Street',
    zone: 'Tagore Town',
    location: { latitude: 25.412800, longitude: 81.827300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tagore Town.',
  },
  {
    id: 'node-all-4-3',
    name: 'Tagore Town Sector 3 High Street',
    zone: 'Tagore Town',
    location: { latitude: 25.415800, longitude: 81.830300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tagore Town.',
  },
  {
    id: 'node-all-5-1',
    name: 'Allahpur Sector 1 High Street',
    zone: 'Allahpur',
    location: { latitude: 25.421800, longitude: 81.834300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Allahpur.',
  },
  {
    id: 'node-all-5-2',
    name: 'Allahpur Sector 2 High Street',
    zone: 'Allahpur',
    location: { latitude: 25.424800, longitude: 81.837300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Allahpur.',
  },
  {
    id: 'node-all-5-3',
    name: 'Allahpur Sector 3 High Street',
    zone: 'Allahpur',
    location: { latitude: 25.427800, longitude: 81.840300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Allahpur.',
  },
  {
    id: 'node-all-6-1',
    name: 'Mumfordganj Sector 1 High Street',
    zone: 'Mumfordganj',
    location: { latitude: 25.433800, longitude: 81.844300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mumfordganj.',
  },
  {
    id: 'node-all-6-2',
    name: 'Mumfordganj Sector 2 High Street',
    zone: 'Mumfordganj',
    location: { latitude: 25.436800, longitude: 81.847300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mumfordganj.',
  },
  {
    id: 'node-all-6-3',
    name: 'Mumfordganj Sector 3 High Street',
    zone: 'Mumfordganj',
    location: { latitude: 25.439800, longitude: 81.850300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mumfordganj.',
  },
  {
    id: 'node-all-7-1',
    name: 'Naini Hub Sector 1 High Street',
    zone: 'Naini Hub',
    location: { latitude: 25.445800, longitude: 81.854300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Naini Hub.',
  },
  {
    id: 'node-all-7-2',
    name: 'Naini Hub Sector 2 High Street',
    zone: 'Naini Hub',
    location: { latitude: 25.448800, longitude: 81.857300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Naini Hub.',
  },
  {
    id: 'node-all-7-3',
    name: 'Naini Hub Sector 3 High Street',
    zone: 'Naini Hub',
    location: { latitude: 25.451800, longitude: 81.860300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Naini Hub.',
  },
  {
    id: 'node-all-8-1',
    name: 'Teliyarganj Sector 1 High Street',
    zone: 'Teliyarganj',
    location: { latitude: 25.457800, longitude: 81.864300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Teliyarganj.',
  },
  {
    id: 'node-all-8-2',
    name: 'Teliyarganj Sector 2 High Street',
    zone: 'Teliyarganj',
    location: { latitude: 25.460800, longitude: 81.867300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Teliyarganj.',
  },
  {
    id: 'node-all-8-3',
    name: 'Teliyarganj Sector 3 High Street',
    zone: 'Teliyarganj',
    location: { latitude: 25.463800, longitude: 81.870300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Teliyarganj.',
  },
  {
    id: 'node-all-9-1',
    name: 'Dhumanganj Sector 1 High Street',
    zone: 'Dhumanganj',
    location: { latitude: 25.469800, longitude: 81.874300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dhumanganj.',
  },
  {
    id: 'node-all-9-2',
    name: 'Dhumanganj Sector 2 High Street',
    zone: 'Dhumanganj',
    location: { latitude: 25.472800, longitude: 81.877300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dhumanganj.',
  },
  {
    id: 'node-all-9-3',
    name: 'Dhumanganj Sector 3 High Street',
    zone: 'Dhumanganj',
    location: { latitude: 25.475800, longitude: 81.880300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dhumanganj.',
  },
  {
    id: 'node-all-10-1',
    name: 'Lukarganj Sector 1 High Street',
    zone: 'Lukarganj',
    location: { latitude: 25.481800, longitude: 81.884300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lukarganj.',
  },
  {
    id: 'node-all-10-2',
    name: 'Lukarganj Sector 2 High Street',
    zone: 'Lukarganj',
    location: { latitude: 25.484800, longitude: 81.887300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lukarganj.',
  },
  {
    id: 'node-all-10-3',
    name: 'Lukarganj Sector 3 High Street',
    zone: 'Lukarganj',
    location: { latitude: 25.487800, longitude: 81.890300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lukarganj.',
  },
];

export const ALLAHABAD_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-all-1',
    fromNodeId: 'node-all-1-1',
    toNodeId: 'node-all-1-2',
    roadName: 'Civil Lines Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-2',
    fromNodeId: 'node-all-1-2',
    toNodeId: 'node-all-1-3',
    roadName: 'Civil Lines Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-3',
    fromNodeId: 'node-all-2-1',
    toNodeId: 'node-all-2-2',
    roadName: 'George Town Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-4',
    fromNodeId: 'node-all-2-2',
    toNodeId: 'node-all-2-3',
    roadName: 'George Town Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-5',
    fromNodeId: 'node-all-3-1',
    toNodeId: 'node-all-3-2',
    roadName: 'Katra Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-6',
    fromNodeId: 'node-all-3-2',
    toNodeId: 'node-all-3-3',
    roadName: 'Katra Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-7',
    fromNodeId: 'node-all-4-1',
    toNodeId: 'node-all-4-2',
    roadName: 'Tagore Town Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-8',
    fromNodeId: 'node-all-4-2',
    toNodeId: 'node-all-4-3',
    roadName: 'Tagore Town Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-9',
    fromNodeId: 'node-all-5-1',
    toNodeId: 'node-all-5-2',
    roadName: 'Allahpur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-10',
    fromNodeId: 'node-all-5-2',
    toNodeId: 'node-all-5-3',
    roadName: 'Allahpur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-11',
    fromNodeId: 'node-all-6-1',
    toNodeId: 'node-all-6-2',
    roadName: 'Mumfordganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-12',
    fromNodeId: 'node-all-6-2',
    toNodeId: 'node-all-6-3',
    roadName: 'Mumfordganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-13',
    fromNodeId: 'node-all-7-1',
    toNodeId: 'node-all-7-2',
    roadName: 'Naini Hub Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-14',
    fromNodeId: 'node-all-7-2',
    toNodeId: 'node-all-7-3',
    roadName: 'Naini Hub Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-15',
    fromNodeId: 'node-all-8-1',
    toNodeId: 'node-all-8-2',
    roadName: 'Teliyarganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-16',
    fromNodeId: 'node-all-8-2',
    toNodeId: 'node-all-8-3',
    roadName: 'Teliyarganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-17',
    fromNodeId: 'node-all-9-1',
    toNodeId: 'node-all-9-2',
    roadName: 'Dhumanganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-18',
    fromNodeId: 'node-all-9-2',
    toNodeId: 'node-all-9-3',
    roadName: 'Dhumanganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-19',
    fromNodeId: 'node-all-10-1',
    toNodeId: 'node-all-10-2',
    roadName: 'Lukarganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-all-20',
    fromNodeId: 'node-all-10-2',
    toNodeId: 'node-all-10-3',
    roadName: 'Lukarganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
