/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Amman Seven Hills Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const AMMAN_BASE_COORDINATE: GeoCoordinate = {
  latitude: 31.9454,
  longitude: 35.9284,
};

export const AMMAN_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-amm-1-1',
    name: 'Abdoun Sector 1 High Street',
    zone: 'Abdoun',
    location: { latitude: 31.883400, longitude: 35.876400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Abdoun.',
  },
  {
    id: 'node-amm-1-2',
    name: 'Abdoun Sector 2 High Street',
    zone: 'Abdoun',
    location: { latitude: 31.886400, longitude: 35.879400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Abdoun.',
  },
  {
    id: 'node-amm-1-3',
    name: 'Abdoun Sector 3 High Street',
    zone: 'Abdoun',
    location: { latitude: 31.889400, longitude: 35.882400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Abdoun.',
  },
  {
    id: 'node-amm-2-1',
    name: 'Jabal Amman Sector 1 High Street',
    zone: 'Jabal Amman',
    location: { latitude: 31.895400, longitude: 35.886400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jabal Amman.',
  },
  {
    id: 'node-amm-2-2',
    name: 'Jabal Amman Sector 2 High Street',
    zone: 'Jabal Amman',
    location: { latitude: 31.898400, longitude: 35.889400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jabal Amman.',
  },
  {
    id: 'node-amm-2-3',
    name: 'Jabal Amman Sector 3 High Street',
    zone: 'Jabal Amman',
    location: { latitude: 31.901400, longitude: 35.892400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jabal Amman.',
  },
  {
    id: 'node-amm-3-1',
    name: 'Jabal Al-Weibdeh Sector 1 High Street',
    zone: 'Jabal Al-Weibdeh',
    location: { latitude: 31.907400, longitude: 35.896400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jabal Al-Weibdeh.',
  },
  {
    id: 'node-amm-3-2',
    name: 'Jabal Al-Weibdeh Sector 2 High Street',
    zone: 'Jabal Al-Weibdeh',
    location: { latitude: 31.910400, longitude: 35.899400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jabal Al-Weibdeh.',
  },
  {
    id: 'node-amm-3-3',
    name: 'Jabal Al-Weibdeh Sector 3 High Street',
    zone: 'Jabal Al-Weibdeh',
    location: { latitude: 31.913400, longitude: 35.902400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jabal Al-Weibdeh.',
  },
  {
    id: 'node-amm-4-1',
    name: 'Sweifieh Sector 1 High Street',
    zone: 'Sweifieh',
    location: { latitude: 31.919400, longitude: 35.906400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sweifieh.',
  },
  {
    id: 'node-amm-4-2',
    name: 'Sweifieh Sector 2 High Street',
    zone: 'Sweifieh',
    location: { latitude: 31.922400, longitude: 35.909400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sweifieh.',
  },
  {
    id: 'node-amm-4-3',
    name: 'Sweifieh Sector 3 High Street',
    zone: 'Sweifieh',
    location: { latitude: 31.925400, longitude: 35.912400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sweifieh.',
  },
  {
    id: 'node-amm-5-1',
    name: 'Shmeisani Sector 1 High Street',
    zone: 'Shmeisani',
    location: { latitude: 31.931400, longitude: 35.916400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shmeisani.',
  },
  {
    id: 'node-amm-5-2',
    name: 'Shmeisani Sector 2 High Street',
    zone: 'Shmeisani',
    location: { latitude: 31.934400, longitude: 35.919400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shmeisani.',
  },
  {
    id: 'node-amm-5-3',
    name: 'Shmeisani Sector 3 High Street',
    zone: 'Shmeisani',
    location: { latitude: 31.937400, longitude: 35.922400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shmeisani.',
  },
  {
    id: 'node-amm-6-1',
    name: 'Al-Rabieh Sector 1 High Street',
    zone: 'Al-Rabieh',
    location: { latitude: 31.943400, longitude: 35.926400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al-Rabieh.',
  },
  {
    id: 'node-amm-6-2',
    name: 'Al-Rabieh Sector 2 High Street',
    zone: 'Al-Rabieh',
    location: { latitude: 31.946400, longitude: 35.929400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al-Rabieh.',
  },
  {
    id: 'node-amm-6-3',
    name: 'Al-Rabieh Sector 3 High Street',
    zone: 'Al-Rabieh',
    location: { latitude: 31.949400, longitude: 35.932400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al-Rabieh.',
  },
  {
    id: 'node-amm-7-1',
    name: 'Dabouq Sector 1 High Street',
    zone: 'Dabouq',
    location: { latitude: 31.955400, longitude: 35.936400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dabouq.',
  },
  {
    id: 'node-amm-7-2',
    name: 'Dabouq Sector 2 High Street',
    zone: 'Dabouq',
    location: { latitude: 31.958400, longitude: 35.939400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dabouq.',
  },
  {
    id: 'node-amm-7-3',
    name: 'Dabouq Sector 3 High Street',
    zone: 'Dabouq',
    location: { latitude: 31.961400, longitude: 35.942400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dabouq.',
  },
  {
    id: 'node-amm-8-1',
    name: 'Khalda Sector 1 High Street',
    zone: 'Khalda',
    location: { latitude: 31.967400, longitude: 35.946400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Khalda.',
  },
  {
    id: 'node-amm-8-2',
    name: 'Khalda Sector 2 High Street',
    zone: 'Khalda',
    location: { latitude: 31.970400, longitude: 35.949400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Khalda.',
  },
  {
    id: 'node-amm-8-3',
    name: 'Khalda Sector 3 High Street',
    zone: 'Khalda',
    location: { latitude: 31.973400, longitude: 35.952400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Khalda.',
  },
  {
    id: 'node-amm-9-1',
    name: 'Downtown Amman Sector 1 High Street',
    zone: 'Downtown Amman',
    location: { latitude: 31.979400, longitude: 35.956400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Amman.',
  },
  {
    id: 'node-amm-9-2',
    name: 'Downtown Amman Sector 2 High Street',
    zone: 'Downtown Amman',
    location: { latitude: 31.982400, longitude: 35.959400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Amman.',
  },
  {
    id: 'node-amm-9-3',
    name: 'Downtown Amman Sector 3 High Street',
    zone: 'Downtown Amman',
    location: { latitude: 31.985400, longitude: 35.962400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Amman.',
  },
  {
    id: 'node-amm-10-1',
    name: 'Abdali Sector 1 High Street',
    zone: 'Abdali',
    location: { latitude: 31.991400, longitude: 35.966400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Abdali.',
  },
  {
    id: 'node-amm-10-2',
    name: 'Abdali Sector 2 High Street',
    zone: 'Abdali',
    location: { latitude: 31.994400, longitude: 35.969400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Abdali.',
  },
  {
    id: 'node-amm-10-3',
    name: 'Abdali Sector 3 High Street',
    zone: 'Abdali',
    location: { latitude: 31.997400, longitude: 35.972400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Abdali.',
  },
];

export const AMMAN_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-amm-1',
    fromNodeId: 'node-amm-1-1',
    toNodeId: 'node-amm-1-2',
    roadName: 'Abdoun Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-2',
    fromNodeId: 'node-amm-1-2',
    toNodeId: 'node-amm-1-3',
    roadName: 'Abdoun Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-3',
    fromNodeId: 'node-amm-2-1',
    toNodeId: 'node-amm-2-2',
    roadName: 'Jabal Amman Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-4',
    fromNodeId: 'node-amm-2-2',
    toNodeId: 'node-amm-2-3',
    roadName: 'Jabal Amman Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-5',
    fromNodeId: 'node-amm-3-1',
    toNodeId: 'node-amm-3-2',
    roadName: 'Jabal Al-Weibdeh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-6',
    fromNodeId: 'node-amm-3-2',
    toNodeId: 'node-amm-3-3',
    roadName: 'Jabal Al-Weibdeh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-7',
    fromNodeId: 'node-amm-4-1',
    toNodeId: 'node-amm-4-2',
    roadName: 'Sweifieh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-8',
    fromNodeId: 'node-amm-4-2',
    toNodeId: 'node-amm-4-3',
    roadName: 'Sweifieh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-9',
    fromNodeId: 'node-amm-5-1',
    toNodeId: 'node-amm-5-2',
    roadName: 'Shmeisani Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-10',
    fromNodeId: 'node-amm-5-2',
    toNodeId: 'node-amm-5-3',
    roadName: 'Shmeisani Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-11',
    fromNodeId: 'node-amm-6-1',
    toNodeId: 'node-amm-6-2',
    roadName: 'Al-Rabieh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-12',
    fromNodeId: 'node-amm-6-2',
    toNodeId: 'node-amm-6-3',
    roadName: 'Al-Rabieh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-13',
    fromNodeId: 'node-amm-7-1',
    toNodeId: 'node-amm-7-2',
    roadName: 'Dabouq Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-14',
    fromNodeId: 'node-amm-7-2',
    toNodeId: 'node-amm-7-3',
    roadName: 'Dabouq Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-15',
    fromNodeId: 'node-amm-8-1',
    toNodeId: 'node-amm-8-2',
    roadName: 'Khalda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-16',
    fromNodeId: 'node-amm-8-2',
    toNodeId: 'node-amm-8-3',
    roadName: 'Khalda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-17',
    fromNodeId: 'node-amm-9-1',
    toNodeId: 'node-amm-9-2',
    roadName: 'Downtown Amman Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-18',
    fromNodeId: 'node-amm-9-2',
    toNodeId: 'node-amm-9-3',
    roadName: 'Downtown Amman Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-19',
    fromNodeId: 'node-amm-10-1',
    toNodeId: 'node-amm-10-2',
    roadName: 'Abdali Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amm-20',
    fromNodeId: 'node-amm-10-2',
    toNodeId: 'node-amm-10-3',
    roadName: 'Abdali Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
