/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Amritsar Majha Heritage Zone
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const AMRITSAR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 31.634,
  longitude: 74.8723,
};

export const AMRITSAR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-amr-1-1',
    name: 'Ranjit Avenue Sector 1 High Street',
    zone: 'Ranjit Avenue',
    location: { latitude: 31.572000, longitude: 74.820300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ranjit Avenue.',
  },
  {
    id: 'node-amr-1-2',
    name: 'Ranjit Avenue Sector 2 High Street',
    zone: 'Ranjit Avenue',
    location: { latitude: 31.575000, longitude: 74.823300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ranjit Avenue.',
  },
  {
    id: 'node-amr-1-3',
    name: 'Ranjit Avenue Sector 3 High Street',
    zone: 'Ranjit Avenue',
    location: { latitude: 31.578000, longitude: 74.826300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ranjit Avenue.',
  },
  {
    id: 'node-amr-2-1',
    name: 'Lawrence Road Sector 1 High Street',
    zone: 'Lawrence Road',
    location: { latitude: 31.584000, longitude: 74.830300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lawrence Road.',
  },
  {
    id: 'node-amr-2-2',
    name: 'Lawrence Road Sector 2 High Street',
    zone: 'Lawrence Road',
    location: { latitude: 31.587000, longitude: 74.833300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lawrence Road.',
  },
  {
    id: 'node-amr-2-3',
    name: 'Lawrence Road Sector 3 High Street',
    zone: 'Lawrence Road',
    location: { latitude: 31.590000, longitude: 74.836300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lawrence Road.',
  },
  {
    id: 'node-amr-3-1',
    name: 'Mall Road Sector 1 High Street',
    zone: 'Mall Road',
    location: { latitude: 31.596000, longitude: 74.840300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mall Road.',
  },
  {
    id: 'node-amr-3-2',
    name: 'Mall Road Sector 2 High Street',
    zone: 'Mall Road',
    location: { latitude: 31.599000, longitude: 74.843300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mall Road.',
  },
  {
    id: 'node-amr-3-3',
    name: 'Mall Road Sector 3 High Street',
    zone: 'Mall Road',
    location: { latitude: 31.602000, longitude: 74.846300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mall Road.',
  },
  {
    id: 'node-amr-4-1',
    name: 'Heritage Street Sector 1 High Street',
    zone: 'Heritage Street',
    location: { latitude: 31.608000, longitude: 74.850300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Heritage Street.',
  },
  {
    id: 'node-amr-4-2',
    name: 'Heritage Street Sector 2 High Street',
    zone: 'Heritage Street',
    location: { latitude: 31.611000, longitude: 74.853300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Heritage Street.',
  },
  {
    id: 'node-amr-4-3',
    name: 'Heritage Street Sector 3 High Street',
    zone: 'Heritage Street',
    location: { latitude: 31.614000, longitude: 74.856300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Heritage Street.',
  },
  {
    id: 'node-amr-5-1',
    name: 'Model Town Sector 1 High Street',
    zone: 'Model Town',
    location: { latitude: 31.620000, longitude: 74.860300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Model Town.',
  },
  {
    id: 'node-amr-5-2',
    name: 'Model Town Sector 2 High Street',
    zone: 'Model Town',
    location: { latitude: 31.623000, longitude: 74.863300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Model Town.',
  },
  {
    id: 'node-amr-5-3',
    name: 'Model Town Sector 3 High Street',
    zone: 'Model Town',
    location: { latitude: 31.626000, longitude: 74.866300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Model Town.',
  },
  {
    id: 'node-amr-6-1',
    name: 'Majitha Road Sector 1 High Street',
    zone: 'Majitha Road',
    location: { latitude: 31.632000, longitude: 74.870300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Majitha Road.',
  },
  {
    id: 'node-amr-6-2',
    name: 'Majitha Road Sector 2 High Street',
    zone: 'Majitha Road',
    location: { latitude: 31.635000, longitude: 74.873300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Majitha Road.',
  },
  {
    id: 'node-amr-6-3',
    name: 'Majitha Road Sector 3 High Street',
    zone: 'Majitha Road',
    location: { latitude: 31.638000, longitude: 74.876300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Majitha Road.',
  },
  {
    id: 'node-amr-7-1',
    name: 'Batala Road Sector 1 High Street',
    zone: 'Batala Road',
    location: { latitude: 31.644000, longitude: 74.880300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Batala Road.',
  },
  {
    id: 'node-amr-7-2',
    name: 'Batala Road Sector 2 High Street',
    zone: 'Batala Road',
    location: { latitude: 31.647000, longitude: 74.883300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Batala Road.',
  },
  {
    id: 'node-amr-7-3',
    name: 'Batala Road Sector 3 High Street',
    zone: 'Batala Road',
    location: { latitude: 31.650000, longitude: 74.886300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Batala Road.',
  },
  {
    id: 'node-amr-8-1',
    name: 'Civil Lines Sector 1 High Street',
    zone: 'Civil Lines',
    location: { latitude: 31.656000, longitude: 74.890300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-amr-8-2',
    name: 'Civil Lines Sector 2 High Street',
    zone: 'Civil Lines',
    location: { latitude: 31.659000, longitude: 74.893300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-amr-8-3',
    name: 'Civil Lines Sector 3 High Street',
    zone: 'Civil Lines',
    location: { latitude: 31.662000, longitude: 74.896300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-amr-9-1',
    name: 'Green Avenue Sector 1 High Street',
    zone: 'Green Avenue',
    location: { latitude: 31.668000, longitude: 74.900300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Green Avenue.',
  },
  {
    id: 'node-amr-9-2',
    name: 'Green Avenue Sector 2 High Street',
    zone: 'Green Avenue',
    location: { latitude: 31.671000, longitude: 74.903300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Green Avenue.',
  },
  {
    id: 'node-amr-9-3',
    name: 'Green Avenue Sector 3 High Street',
    zone: 'Green Avenue',
    location: { latitude: 31.674000, longitude: 74.906300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Green Avenue.',
  },
  {
    id: 'node-amr-10-1',
    name: 'GT Road Sector 1 High Street',
    zone: 'GT Road',
    location: { latitude: 31.680000, longitude: 74.910300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in GT Road.',
  },
  {
    id: 'node-amr-10-2',
    name: 'GT Road Sector 2 High Street',
    zone: 'GT Road',
    location: { latitude: 31.683000, longitude: 74.913300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in GT Road.',
  },
  {
    id: 'node-amr-10-3',
    name: 'GT Road Sector 3 High Street',
    zone: 'GT Road',
    location: { latitude: 31.686000, longitude: 74.916300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in GT Road.',
  },
];

export const AMRITSAR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-amr-1',
    fromNodeId: 'node-amr-1-1',
    toNodeId: 'node-amr-1-2',
    roadName: 'Ranjit Avenue Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-2',
    fromNodeId: 'node-amr-1-2',
    toNodeId: 'node-amr-1-3',
    roadName: 'Ranjit Avenue Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-3',
    fromNodeId: 'node-amr-2-1',
    toNodeId: 'node-amr-2-2',
    roadName: 'Lawrence Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-4',
    fromNodeId: 'node-amr-2-2',
    toNodeId: 'node-amr-2-3',
    roadName: 'Lawrence Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-5',
    fromNodeId: 'node-amr-3-1',
    toNodeId: 'node-amr-3-2',
    roadName: 'Mall Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-6',
    fromNodeId: 'node-amr-3-2',
    toNodeId: 'node-amr-3-3',
    roadName: 'Mall Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-7',
    fromNodeId: 'node-amr-4-1',
    toNodeId: 'node-amr-4-2',
    roadName: 'Heritage Street Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-8',
    fromNodeId: 'node-amr-4-2',
    toNodeId: 'node-amr-4-3',
    roadName: 'Heritage Street Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-9',
    fromNodeId: 'node-amr-5-1',
    toNodeId: 'node-amr-5-2',
    roadName: 'Model Town Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-10',
    fromNodeId: 'node-amr-5-2',
    toNodeId: 'node-amr-5-3',
    roadName: 'Model Town Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-11',
    fromNodeId: 'node-amr-6-1',
    toNodeId: 'node-amr-6-2',
    roadName: 'Majitha Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-12',
    fromNodeId: 'node-amr-6-2',
    toNodeId: 'node-amr-6-3',
    roadName: 'Majitha Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-13',
    fromNodeId: 'node-amr-7-1',
    toNodeId: 'node-amr-7-2',
    roadName: 'Batala Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-14',
    fromNodeId: 'node-amr-7-2',
    toNodeId: 'node-amr-7-3',
    roadName: 'Batala Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-15',
    fromNodeId: 'node-amr-8-1',
    toNodeId: 'node-amr-8-2',
    roadName: 'Civil Lines Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-16',
    fromNodeId: 'node-amr-8-2',
    toNodeId: 'node-amr-8-3',
    roadName: 'Civil Lines Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-17',
    fromNodeId: 'node-amr-9-1',
    toNodeId: 'node-amr-9-2',
    roadName: 'Green Avenue Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-18',
    fromNodeId: 'node-amr-9-2',
    toNodeId: 'node-amr-9-3',
    roadName: 'Green Avenue Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-19',
    fromNodeId: 'node-amr-10-1',
    toNodeId: 'node-amr-10-2',
    roadName: 'GT Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-amr-20',
    fromNodeId: 'node-amr-10-2',
    toNodeId: 'node-amr-10-3',
    roadName: 'GT Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
