/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Amsterdam Canal Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const AMSTERDAM_BASE_COORDINATE: GeoCoordinate = {
  latitude: 52.3676,
  longitude: 4.9041,
};

export const AMSTERDAM_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ams-1-1',
    name: 'Centrum Sector 1 High Street',
    zone: 'Centrum',
    location: { latitude: 52.305600, longitude: 4.852100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Centrum.',
  },
  {
    id: 'node-ams-1-2',
    name: 'Centrum Sector 2 High Street',
    zone: 'Centrum',
    location: { latitude: 52.308600, longitude: 4.855100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Centrum.',
  },
  {
    id: 'node-ams-1-3',
    name: 'Centrum Sector 3 High Street',
    zone: 'Centrum',
    location: { latitude: 52.311600, longitude: 4.858100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Centrum.',
  },
  {
    id: 'node-ams-2-1',
    name: 'De Pijp Sector 1 High Street',
    zone: 'De Pijp',
    location: { latitude: 52.317600, longitude: 4.862100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in De Pijp.',
  },
  {
    id: 'node-ams-2-2',
    name: 'De Pijp Sector 2 High Street',
    zone: 'De Pijp',
    location: { latitude: 52.320600, longitude: 4.865100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in De Pijp.',
  },
  {
    id: 'node-ams-2-3',
    name: 'De Pijp Sector 3 High Street',
    zone: 'De Pijp',
    location: { latitude: 52.323600, longitude: 4.868100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in De Pijp.',
  },
  {
    id: 'node-ams-3-1',
    name: 'Jordaan Sector 1 High Street',
    zone: 'Jordaan',
    location: { latitude: 52.329600, longitude: 4.872100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jordaan.',
  },
  {
    id: 'node-ams-3-2',
    name: 'Jordaan Sector 2 High Street',
    zone: 'Jordaan',
    location: { latitude: 52.332600, longitude: 4.875100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jordaan.',
  },
  {
    id: 'node-ams-3-3',
    name: 'Jordaan Sector 3 High Street',
    zone: 'Jordaan',
    location: { latitude: 52.335600, longitude: 4.878100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jordaan.',
  },
  {
    id: 'node-ams-4-1',
    name: 'Oud-West Sector 1 High Street',
    zone: 'Oud-West',
    location: { latitude: 52.341600, longitude: 4.882100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Oud-West.',
  },
  {
    id: 'node-ams-4-2',
    name: 'Oud-West Sector 2 High Street',
    zone: 'Oud-West',
    location: { latitude: 52.344600, longitude: 4.885100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Oud-West.',
  },
  {
    id: 'node-ams-4-3',
    name: 'Oud-West Sector 3 High Street',
    zone: 'Oud-West',
    location: { latitude: 52.347600, longitude: 4.888100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Oud-West.',
  },
  {
    id: 'node-ams-5-1',
    name: 'Oud-Zuid Sector 1 High Street',
    zone: 'Oud-Zuid',
    location: { latitude: 52.353600, longitude: 4.892100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Oud-Zuid.',
  },
  {
    id: 'node-ams-5-2',
    name: 'Oud-Zuid Sector 2 High Street',
    zone: 'Oud-Zuid',
    location: { latitude: 52.356600, longitude: 4.895100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Oud-Zuid.',
  },
  {
    id: 'node-ams-5-3',
    name: 'Oud-Zuid Sector 3 High Street',
    zone: 'Oud-Zuid',
    location: { latitude: 52.359600, longitude: 4.898100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Oud-Zuid.',
  },
  {
    id: 'node-ams-6-1',
    name: 'Westerpark Sector 1 High Street',
    zone: 'Westerpark',
    location: { latitude: 52.365600, longitude: 4.902100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Westerpark.',
  },
  {
    id: 'node-ams-6-2',
    name: 'Westerpark Sector 2 High Street',
    zone: 'Westerpark',
    location: { latitude: 52.368600, longitude: 4.905100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Westerpark.',
  },
  {
    id: 'node-ams-6-3',
    name: 'Westerpark Sector 3 High Street',
    zone: 'Westerpark',
    location: { latitude: 52.371600, longitude: 4.908100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Westerpark.',
  },
  {
    id: 'node-ams-7-1',
    name: 'Oost Sector 1 High Street',
    zone: 'Oost',
    location: { latitude: 52.377600, longitude: 4.912100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Oost.',
  },
  {
    id: 'node-ams-7-2',
    name: 'Oost Sector 2 High Street',
    zone: 'Oost',
    location: { latitude: 52.380600, longitude: 4.915100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Oost.',
  },
  {
    id: 'node-ams-7-3',
    name: 'Oost Sector 3 High Street',
    zone: 'Oost',
    location: { latitude: 52.383600, longitude: 4.918100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Oost.',
  },
  {
    id: 'node-ams-8-1',
    name: 'Noord Sector 1 High Street',
    zone: 'Noord',
    location: { latitude: 52.389600, longitude: 4.922100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Noord.',
  },
  {
    id: 'node-ams-8-2',
    name: 'Noord Sector 2 High Street',
    zone: 'Noord',
    location: { latitude: 52.392600, longitude: 4.925100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Noord.',
  },
  {
    id: 'node-ams-8-3',
    name: 'Noord Sector 3 High Street',
    zone: 'Noord',
    location: { latitude: 52.395600, longitude: 4.928100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Noord.',
  },
  {
    id: 'node-ams-9-1',
    name: 'Zuidas Sector 1 High Street',
    zone: 'Zuidas',
    location: { latitude: 52.401600, longitude: 4.932100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zuidas.',
  },
  {
    id: 'node-ams-9-2',
    name: 'Zuidas Sector 2 High Street',
    zone: 'Zuidas',
    location: { latitude: 52.404600, longitude: 4.935100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zuidas.',
  },
  {
    id: 'node-ams-9-3',
    name: 'Zuidas Sector 3 High Street',
    zone: 'Zuidas',
    location: { latitude: 52.407600, longitude: 4.938100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zuidas.',
  },
  {
    id: 'node-ams-10-1',
    name: 'Bos en Lommer Sector 1 High Street',
    zone: 'Bos en Lommer',
    location: { latitude: 52.413600, longitude: 4.942100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bos en Lommer.',
  },
  {
    id: 'node-ams-10-2',
    name: 'Bos en Lommer Sector 2 High Street',
    zone: 'Bos en Lommer',
    location: { latitude: 52.416600, longitude: 4.945100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bos en Lommer.',
  },
  {
    id: 'node-ams-10-3',
    name: 'Bos en Lommer Sector 3 High Street',
    zone: 'Bos en Lommer',
    location: { latitude: 52.419600, longitude: 4.948100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bos en Lommer.',
  },
];

export const AMSTERDAM_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ams-1',
    fromNodeId: 'node-ams-1-1',
    toNodeId: 'node-ams-1-2',
    roadName: 'Centrum Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-2',
    fromNodeId: 'node-ams-1-2',
    toNodeId: 'node-ams-1-3',
    roadName: 'Centrum Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-3',
    fromNodeId: 'node-ams-2-1',
    toNodeId: 'node-ams-2-2',
    roadName: 'De Pijp Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-4',
    fromNodeId: 'node-ams-2-2',
    toNodeId: 'node-ams-2-3',
    roadName: 'De Pijp Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-5',
    fromNodeId: 'node-ams-3-1',
    toNodeId: 'node-ams-3-2',
    roadName: 'Jordaan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-6',
    fromNodeId: 'node-ams-3-2',
    toNodeId: 'node-ams-3-3',
    roadName: 'Jordaan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-7',
    fromNodeId: 'node-ams-4-1',
    toNodeId: 'node-ams-4-2',
    roadName: 'Oud-West Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-8',
    fromNodeId: 'node-ams-4-2',
    toNodeId: 'node-ams-4-3',
    roadName: 'Oud-West Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-9',
    fromNodeId: 'node-ams-5-1',
    toNodeId: 'node-ams-5-2',
    roadName: 'Oud-Zuid Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-10',
    fromNodeId: 'node-ams-5-2',
    toNodeId: 'node-ams-5-3',
    roadName: 'Oud-Zuid Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-11',
    fromNodeId: 'node-ams-6-1',
    toNodeId: 'node-ams-6-2',
    roadName: 'Westerpark Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-12',
    fromNodeId: 'node-ams-6-2',
    toNodeId: 'node-ams-6-3',
    roadName: 'Westerpark Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-13',
    fromNodeId: 'node-ams-7-1',
    toNodeId: 'node-ams-7-2',
    roadName: 'Oost Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-14',
    fromNodeId: 'node-ams-7-2',
    toNodeId: 'node-ams-7-3',
    roadName: 'Oost Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-15',
    fromNodeId: 'node-ams-8-1',
    toNodeId: 'node-ams-8-2',
    roadName: 'Noord Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-16',
    fromNodeId: 'node-ams-8-2',
    toNodeId: 'node-ams-8-3',
    roadName: 'Noord Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-17',
    fromNodeId: 'node-ams-9-1',
    toNodeId: 'node-ams-9-2',
    roadName: 'Zuidas Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-18',
    fromNodeId: 'node-ams-9-2',
    toNodeId: 'node-ams-9-3',
    roadName: 'Zuidas Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-19',
    fromNodeId: 'node-ams-10-1',
    toNodeId: 'node-ams-10-2',
    roadName: 'Bos en Lommer Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ams-20',
    fromNodeId: 'node-ams-10-2',
    toNodeId: 'node-ams-10-3',
    roadName: 'Bos en Lommer Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
