/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Ankara Capital Çankaya Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const ANKARA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 39.9334,
  longitude: 32.8597,
};

export const ANKARA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ank-1-1',
    name: 'Çankaya Sector 1 High Street',
    zone: 'Çankaya',
    location: { latitude: 39.871400, longitude: 32.807700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Çankaya.',
  },
  {
    id: 'node-ank-1-2',
    name: 'Çankaya Sector 2 High Street',
    zone: 'Çankaya',
    location: { latitude: 39.874400, longitude: 32.810700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Çankaya.',
  },
  {
    id: 'node-ank-1-3',
    name: 'Çankaya Sector 3 High Street',
    zone: 'Çankaya',
    location: { latitude: 39.877400, longitude: 32.813700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Çankaya.',
  },
  {
    id: 'node-ank-2-1',
    name: 'Kızılay Sector 1 High Street',
    zone: 'Kızılay',
    location: { latitude: 39.883400, longitude: 32.817700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kızılay.',
  },
  {
    id: 'node-ank-2-2',
    name: 'Kızılay Sector 2 High Street',
    zone: 'Kızılay',
    location: { latitude: 39.886400, longitude: 32.820700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kızılay.',
  },
  {
    id: 'node-ank-2-3',
    name: 'Kızılay Sector 3 High Street',
    zone: 'Kızılay',
    location: { latitude: 39.889400, longitude: 32.823700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kızılay.',
  },
  {
    id: 'node-ank-3-1',
    name: 'Tunalı Hilmi Sector 1 High Street',
    zone: 'Tunalı Hilmi',
    location: { latitude: 39.895400, longitude: 32.827700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tunalı Hilmi.',
  },
  {
    id: 'node-ank-3-2',
    name: 'Tunalı Hilmi Sector 2 High Street',
    zone: 'Tunalı Hilmi',
    location: { latitude: 39.898400, longitude: 32.830700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tunalı Hilmi.',
  },
  {
    id: 'node-ank-3-3',
    name: 'Tunalı Hilmi Sector 3 High Street',
    zone: 'Tunalı Hilmi',
    location: { latitude: 39.901400, longitude: 32.833700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tunalı Hilmi.',
  },
  {
    id: 'node-ank-4-1',
    name: 'Gazi Osman Paşa Sector 1 High Street',
    zone: 'Gazi Osman Paşa',
    location: { latitude: 39.907400, longitude: 32.837700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gazi Osman Paşa.',
  },
  {
    id: 'node-ank-4-2',
    name: 'Gazi Osman Paşa Sector 2 High Street',
    zone: 'Gazi Osman Paşa',
    location: { latitude: 39.910400, longitude: 32.840700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gazi Osman Paşa.',
  },
  {
    id: 'node-ank-4-3',
    name: 'Gazi Osman Paşa Sector 3 High Street',
    zone: 'Gazi Osman Paşa',
    location: { latitude: 39.913400, longitude: 32.843700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gazi Osman Paşa.',
  },
  {
    id: 'node-ank-5-1',
    name: 'Bahçelievler Ankara Sector 1 High Street',
    zone: 'Bahçelievler Ankara',
    location: { latitude: 39.919400, longitude: 32.847700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bahçelievler Ankara.',
  },
  {
    id: 'node-ank-5-2',
    name: 'Bahçelievler Ankara Sector 2 High Street',
    zone: 'Bahçelievler Ankara',
    location: { latitude: 39.922400, longitude: 32.850700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bahçelievler Ankara.',
  },
  {
    id: 'node-ank-5-3',
    name: 'Bahçelievler Ankara Sector 3 High Street',
    zone: 'Bahçelievler Ankara',
    location: { latitude: 39.925400, longitude: 32.853700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bahçelievler Ankara.',
  },
  {
    id: 'node-ank-6-1',
    name: 'Bilkent Sector 1 High Street',
    zone: 'Bilkent',
    location: { latitude: 39.931400, longitude: 32.857700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bilkent.',
  },
  {
    id: 'node-ank-6-2',
    name: 'Bilkent Sector 2 High Street',
    zone: 'Bilkent',
    location: { latitude: 39.934400, longitude: 32.860700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bilkent.',
  },
  {
    id: 'node-ank-6-3',
    name: 'Bilkent Sector 3 High Street',
    zone: 'Bilkent',
    location: { latitude: 39.937400, longitude: 32.863700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bilkent.',
  },
  {
    id: 'node-ank-7-1',
    name: 'Çayyolu Sector 1 High Street',
    zone: 'Çayyolu',
    location: { latitude: 39.943400, longitude: 32.867700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Çayyolu.',
  },
  {
    id: 'node-ank-7-2',
    name: 'Çayyolu Sector 2 High Street',
    zone: 'Çayyolu',
    location: { latitude: 39.946400, longitude: 32.870700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Çayyolu.',
  },
  {
    id: 'node-ank-7-3',
    name: 'Çayyolu Sector 3 High Street',
    zone: 'Çayyolu',
    location: { latitude: 39.949400, longitude: 32.873700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Çayyolu.',
  },
  {
    id: 'node-ank-8-1',
    name: 'Ulus Sector 1 High Street',
    zone: 'Ulus',
    location: { latitude: 39.955400, longitude: 32.877700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ulus.',
  },
  {
    id: 'node-ank-8-2',
    name: 'Ulus Sector 2 High Street',
    zone: 'Ulus',
    location: { latitude: 39.958400, longitude: 32.880700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ulus.',
  },
  {
    id: 'node-ank-8-3',
    name: 'Ulus Sector 3 High Street',
    zone: 'Ulus',
    location: { latitude: 39.961400, longitude: 32.883700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ulus.',
  },
  {
    id: 'node-ank-9-1',
    name: 'Kavaklıdere Sector 1 High Street',
    zone: 'Kavaklıdere',
    location: { latitude: 39.967400, longitude: 32.887700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kavaklıdere.',
  },
  {
    id: 'node-ank-9-2',
    name: 'Kavaklıdere Sector 2 High Street',
    zone: 'Kavaklıdere',
    location: { latitude: 39.970400, longitude: 32.890700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kavaklıdere.',
  },
  {
    id: 'node-ank-9-3',
    name: 'Kavaklıdere Sector 3 High Street',
    zone: 'Kavaklıdere',
    location: { latitude: 39.973400, longitude: 32.893700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kavaklıdere.',
  },
  {
    id: 'node-ank-10-1',
    name: 'Batıkent Sector 1 High Street',
    zone: 'Batıkent',
    location: { latitude: 39.979400, longitude: 32.897700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Batıkent.',
  },
  {
    id: 'node-ank-10-2',
    name: 'Batıkent Sector 2 High Street',
    zone: 'Batıkent',
    location: { latitude: 39.982400, longitude: 32.900700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Batıkent.',
  },
  {
    id: 'node-ank-10-3',
    name: 'Batıkent Sector 3 High Street',
    zone: 'Batıkent',
    location: { latitude: 39.985400, longitude: 32.903700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Batıkent.',
  },
];

export const ANKARA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ank-1',
    fromNodeId: 'node-ank-1-1',
    toNodeId: 'node-ank-1-2',
    roadName: 'Çankaya Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-2',
    fromNodeId: 'node-ank-1-2',
    toNodeId: 'node-ank-1-3',
    roadName: 'Çankaya Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-3',
    fromNodeId: 'node-ank-2-1',
    toNodeId: 'node-ank-2-2',
    roadName: 'Kızılay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-4',
    fromNodeId: 'node-ank-2-2',
    toNodeId: 'node-ank-2-3',
    roadName: 'Kızılay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-5',
    fromNodeId: 'node-ank-3-1',
    toNodeId: 'node-ank-3-2',
    roadName: 'Tunalı Hilmi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-6',
    fromNodeId: 'node-ank-3-2',
    toNodeId: 'node-ank-3-3',
    roadName: 'Tunalı Hilmi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-7',
    fromNodeId: 'node-ank-4-1',
    toNodeId: 'node-ank-4-2',
    roadName: 'Gazi Osman Paşa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-8',
    fromNodeId: 'node-ank-4-2',
    toNodeId: 'node-ank-4-3',
    roadName: 'Gazi Osman Paşa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-9',
    fromNodeId: 'node-ank-5-1',
    toNodeId: 'node-ank-5-2',
    roadName: 'Bahçelievler Ankara Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-10',
    fromNodeId: 'node-ank-5-2',
    toNodeId: 'node-ank-5-3',
    roadName: 'Bahçelievler Ankara Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-11',
    fromNodeId: 'node-ank-6-1',
    toNodeId: 'node-ank-6-2',
    roadName: 'Bilkent Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-12',
    fromNodeId: 'node-ank-6-2',
    toNodeId: 'node-ank-6-3',
    roadName: 'Bilkent Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-13',
    fromNodeId: 'node-ank-7-1',
    toNodeId: 'node-ank-7-2',
    roadName: 'Çayyolu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-14',
    fromNodeId: 'node-ank-7-2',
    toNodeId: 'node-ank-7-3',
    roadName: 'Çayyolu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-15',
    fromNodeId: 'node-ank-8-1',
    toNodeId: 'node-ank-8-2',
    roadName: 'Ulus Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-16',
    fromNodeId: 'node-ank-8-2',
    toNodeId: 'node-ank-8-3',
    roadName: 'Ulus Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-17',
    fromNodeId: 'node-ank-9-1',
    toNodeId: 'node-ank-9-2',
    roadName: 'Kavaklıdere Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-18',
    fromNodeId: 'node-ank-9-2',
    toNodeId: 'node-ank-9-3',
    roadName: 'Kavaklıdere Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-19',
    fromNodeId: 'node-ank-10-1',
    toNodeId: 'node-ank-10-2',
    roadName: 'Batıkent Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ank-20',
    fromNodeId: 'node-ank-10-2',
    toNodeId: 'node-ank-10-3',
    roadName: 'Batıkent Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
