/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Antalya Turquoise Coast
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const ANTALYA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 36.8969,
  longitude: 30.7133,
};

export const ANTALYA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ant-1-1',
    name: 'Kaleiçi Old Town Sector 1 High Street',
    zone: 'Kaleiçi Old Town',
    location: { latitude: 36.834900, longitude: 30.661300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kaleiçi Old Town.',
  },
  {
    id: 'node-ant-1-2',
    name: 'Kaleiçi Old Town Sector 2 High Street',
    zone: 'Kaleiçi Old Town',
    location: { latitude: 36.837900, longitude: 30.664300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kaleiçi Old Town.',
  },
  {
    id: 'node-ant-1-3',
    name: 'Kaleiçi Old Town Sector 3 High Street',
    zone: 'Kaleiçi Old Town',
    location: { latitude: 36.840900, longitude: 30.667300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kaleiçi Old Town.',
  },
  {
    id: 'node-ant-2-1',
    name: 'Lara Beach Sector 1 High Street',
    zone: 'Lara Beach',
    location: { latitude: 36.846900, longitude: 30.671300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lara Beach.',
  },
  {
    id: 'node-ant-2-2',
    name: 'Lara Beach Sector 2 High Street',
    zone: 'Lara Beach',
    location: { latitude: 36.849900, longitude: 30.674300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lara Beach.',
  },
  {
    id: 'node-ant-2-3',
    name: 'Lara Beach Sector 3 High Street',
    zone: 'Lara Beach',
    location: { latitude: 36.852900, longitude: 30.677300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lara Beach.',
  },
  {
    id: 'node-ant-3-1',
    name: 'Konyaaltı Sector 1 High Street',
    zone: 'Konyaaltı',
    location: { latitude: 36.858900, longitude: 30.681300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Konyaaltı.',
  },
  {
    id: 'node-ant-3-2',
    name: 'Konyaaltı Sector 2 High Street',
    zone: 'Konyaaltı',
    location: { latitude: 36.861900, longitude: 30.684300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Konyaaltı.',
  },
  {
    id: 'node-ant-3-3',
    name: 'Konyaaltı Sector 3 High Street',
    zone: 'Konyaaltı',
    location: { latitude: 36.864900, longitude: 30.687300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Konyaaltı.',
  },
  {
    id: 'node-ant-4-1',
    name: 'Muratpaşa Sector 1 High Street',
    zone: 'Muratpaşa',
    location: { latitude: 36.870900, longitude: 30.691300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Muratpaşa.',
  },
  {
    id: 'node-ant-4-2',
    name: 'Muratpaşa Sector 2 High Street',
    zone: 'Muratpaşa',
    location: { latitude: 36.873900, longitude: 30.694300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Muratpaşa.',
  },
  {
    id: 'node-ant-4-3',
    name: 'Muratpaşa Sector 3 High Street',
    zone: 'Muratpaşa',
    location: { latitude: 36.876900, longitude: 30.697300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Muratpaşa.',
  },
  {
    id: 'node-ant-5-1',
    name: 'Kepez Sector 1 High Street',
    zone: 'Kepez',
    location: { latitude: 36.882900, longitude: 30.701300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kepez.',
  },
  {
    id: 'node-ant-5-2',
    name: 'Kepez Sector 2 High Street',
    zone: 'Kepez',
    location: { latitude: 36.885900, longitude: 30.704300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kepez.',
  },
  {
    id: 'node-ant-5-3',
    name: 'Kepez Sector 3 High Street',
    zone: 'Kepez',
    location: { latitude: 36.888900, longitude: 30.707300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kepez.',
  },
  {
    id: 'node-ant-6-1',
    name: 'Döşemealtı Sector 1 High Street',
    zone: 'Döşemealtı',
    location: { latitude: 36.894900, longitude: 30.711300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Döşemealtı.',
  },
  {
    id: 'node-ant-6-2',
    name: 'Döşemealtı Sector 2 High Street',
    zone: 'Döşemealtı',
    location: { latitude: 36.897900, longitude: 30.714300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Döşemealtı.',
  },
  {
    id: 'node-ant-6-3',
    name: 'Döşemealtı Sector 3 High Street',
    zone: 'Döşemealtı',
    location: { latitude: 36.900900, longitude: 30.717300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Döşemealtı.',
  },
  {
    id: 'node-ant-7-1',
    name: 'Işıklar Sector 1 High Street',
    zone: 'Işıklar',
    location: { latitude: 36.906900, longitude: 30.721300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Işıklar.',
  },
  {
    id: 'node-ant-7-2',
    name: 'Işıklar Sector 2 High Street',
    zone: 'Işıklar',
    location: { latitude: 36.909900, longitude: 30.724300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Işıklar.',
  },
  {
    id: 'node-ant-7-3',
    name: 'Işıklar Sector 3 High Street',
    zone: 'Işıklar',
    location: { latitude: 36.912900, longitude: 30.727300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Işıklar.',
  },
  {
    id: 'node-ant-8-1',
    name: 'Şirinyalı Sector 1 High Street',
    zone: 'Şirinyalı',
    location: { latitude: 36.918900, longitude: 30.731300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Şirinyalı.',
  },
  {
    id: 'node-ant-8-2',
    name: 'Şirinyalı Sector 2 High Street',
    zone: 'Şirinyalı',
    location: { latitude: 36.921900, longitude: 30.734300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Şirinyalı.',
  },
  {
    id: 'node-ant-8-3',
    name: 'Şirinyalı Sector 3 High Street',
    zone: 'Şirinyalı',
    location: { latitude: 36.924900, longitude: 30.737300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Şirinyalı.',
  },
  {
    id: 'node-ant-9-1',
    name: 'Fener Sector 1 High Street',
    zone: 'Fener',
    location: { latitude: 36.930900, longitude: 30.741300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fener.',
  },
  {
    id: 'node-ant-9-2',
    name: 'Fener Sector 2 High Street',
    zone: 'Fener',
    location: { latitude: 36.933900, longitude: 30.744300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fener.',
  },
  {
    id: 'node-ant-9-3',
    name: 'Fener Sector 3 High Street',
    zone: 'Fener',
    location: { latitude: 36.936900, longitude: 30.747300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fener.',
  },
  {
    id: 'node-ant-10-1',
    name: 'Meltem Sector 1 High Street',
    zone: 'Meltem',
    location: { latitude: 36.942900, longitude: 30.751300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Meltem.',
  },
  {
    id: 'node-ant-10-2',
    name: 'Meltem Sector 2 High Street',
    zone: 'Meltem',
    location: { latitude: 36.945900, longitude: 30.754300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Meltem.',
  },
  {
    id: 'node-ant-10-3',
    name: 'Meltem Sector 3 High Street',
    zone: 'Meltem',
    location: { latitude: 36.948900, longitude: 30.757300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Meltem.',
  },
];

export const ANTALYA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ant-1',
    fromNodeId: 'node-ant-1-1',
    toNodeId: 'node-ant-1-2',
    roadName: 'Kaleiçi Old Town Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-2',
    fromNodeId: 'node-ant-1-2',
    toNodeId: 'node-ant-1-3',
    roadName: 'Kaleiçi Old Town Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-3',
    fromNodeId: 'node-ant-2-1',
    toNodeId: 'node-ant-2-2',
    roadName: 'Lara Beach Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-4',
    fromNodeId: 'node-ant-2-2',
    toNodeId: 'node-ant-2-3',
    roadName: 'Lara Beach Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-5',
    fromNodeId: 'node-ant-3-1',
    toNodeId: 'node-ant-3-2',
    roadName: 'Konyaaltı Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-6',
    fromNodeId: 'node-ant-3-2',
    toNodeId: 'node-ant-3-3',
    roadName: 'Konyaaltı Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-7',
    fromNodeId: 'node-ant-4-1',
    toNodeId: 'node-ant-4-2',
    roadName: 'Muratpaşa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-8',
    fromNodeId: 'node-ant-4-2',
    toNodeId: 'node-ant-4-3',
    roadName: 'Muratpaşa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-9',
    fromNodeId: 'node-ant-5-1',
    toNodeId: 'node-ant-5-2',
    roadName: 'Kepez Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-10',
    fromNodeId: 'node-ant-5-2',
    toNodeId: 'node-ant-5-3',
    roadName: 'Kepez Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-11',
    fromNodeId: 'node-ant-6-1',
    toNodeId: 'node-ant-6-2',
    roadName: 'Döşemealtı Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-12',
    fromNodeId: 'node-ant-6-2',
    toNodeId: 'node-ant-6-3',
    roadName: 'Döşemealtı Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-13',
    fromNodeId: 'node-ant-7-1',
    toNodeId: 'node-ant-7-2',
    roadName: 'Işıklar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-14',
    fromNodeId: 'node-ant-7-2',
    toNodeId: 'node-ant-7-3',
    roadName: 'Işıklar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-15',
    fromNodeId: 'node-ant-8-1',
    toNodeId: 'node-ant-8-2',
    roadName: 'Şirinyalı Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-16',
    fromNodeId: 'node-ant-8-2',
    toNodeId: 'node-ant-8-3',
    roadName: 'Şirinyalı Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-17',
    fromNodeId: 'node-ant-9-1',
    toNodeId: 'node-ant-9-2',
    roadName: 'Fener Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-18',
    fromNodeId: 'node-ant-9-2',
    toNodeId: 'node-ant-9-3',
    roadName: 'Fener Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-19',
    fromNodeId: 'node-ant-10-1',
    toNodeId: 'node-ant-10-2',
    roadName: 'Meltem Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ant-20',
    fromNodeId: 'node-ant-10-2',
    toNodeId: 'node-ant-10-3',
    roadName: 'Meltem Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
