/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Athens Acropolis Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const ATHENS_BASE_COORDINATE: GeoCoordinate = {
  latitude: 37.9838,
  longitude: 23.7275,
};

export const ATHENS_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ath-1-1',
    name: 'Plaka Sector 1 High Street',
    zone: 'Plaka',
    location: { latitude: 37.921800, longitude: 23.675500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Plaka.',
  },
  {
    id: 'node-ath-1-2',
    name: 'Plaka Sector 2 High Street',
    zone: 'Plaka',
    location: { latitude: 37.924800, longitude: 23.678500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Plaka.',
  },
  {
    id: 'node-ath-1-3',
    name: 'Plaka Sector 3 High Street',
    zone: 'Plaka',
    location: { latitude: 37.927800, longitude: 23.681500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Plaka.',
  },
  {
    id: 'node-ath-2-1',
    name: 'Monastiraki Sector 1 High Street',
    zone: 'Monastiraki',
    location: { latitude: 37.933800, longitude: 23.685500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Monastiraki.',
  },
  {
    id: 'node-ath-2-2',
    name: 'Monastiraki Sector 2 High Street',
    zone: 'Monastiraki',
    location: { latitude: 37.936800, longitude: 23.688500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Monastiraki.',
  },
  {
    id: 'node-ath-2-3',
    name: 'Monastiraki Sector 3 High Street',
    zone: 'Monastiraki',
    location: { latitude: 37.939800, longitude: 23.691500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Monastiraki.',
  },
  {
    id: 'node-ath-3-1',
    name: 'Kolonaki Sector 1 High Street',
    zone: 'Kolonaki',
    location: { latitude: 37.945800, longitude: 23.695500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kolonaki.',
  },
  {
    id: 'node-ath-3-2',
    name: 'Kolonaki Sector 2 High Street',
    zone: 'Kolonaki',
    location: { latitude: 37.948800, longitude: 23.698500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kolonaki.',
  },
  {
    id: 'node-ath-3-3',
    name: 'Kolonaki Sector 3 High Street',
    zone: 'Kolonaki',
    location: { latitude: 37.951800, longitude: 23.701500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kolonaki.',
  },
  {
    id: 'node-ath-4-1',
    name: 'Syntagma Sector 1 High Street',
    zone: 'Syntagma',
    location: { latitude: 37.957800, longitude: 23.705500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Syntagma.',
  },
  {
    id: 'node-ath-4-2',
    name: 'Syntagma Sector 2 High Street',
    zone: 'Syntagma',
    location: { latitude: 37.960800, longitude: 23.708500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Syntagma.',
  },
  {
    id: 'node-ath-4-3',
    name: 'Syntagma Sector 3 High Street',
    zone: 'Syntagma',
    location: { latitude: 37.963800, longitude: 23.711500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Syntagma.',
  },
  {
    id: 'node-ath-5-1',
    name: 'Koukaki Sector 1 High Street',
    zone: 'Koukaki',
    location: { latitude: 37.969800, longitude: 23.715500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Koukaki.',
  },
  {
    id: 'node-ath-5-2',
    name: 'Koukaki Sector 2 High Street',
    zone: 'Koukaki',
    location: { latitude: 37.972800, longitude: 23.718500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Koukaki.',
  },
  {
    id: 'node-ath-5-3',
    name: 'Koukaki Sector 3 High Street',
    zone: 'Koukaki',
    location: { latitude: 37.975800, longitude: 23.721500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Koukaki.',
  },
  {
    id: 'node-ath-6-1',
    name: 'Exarcheia Sector 1 High Street',
    zone: 'Exarcheia',
    location: { latitude: 37.981800, longitude: 23.725500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Exarcheia.',
  },
  {
    id: 'node-ath-6-2',
    name: 'Exarcheia Sector 2 High Street',
    zone: 'Exarcheia',
    location: { latitude: 37.984800, longitude: 23.728500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Exarcheia.',
  },
  {
    id: 'node-ath-6-3',
    name: 'Exarcheia Sector 3 High Street',
    zone: 'Exarcheia',
    location: { latitude: 37.987800, longitude: 23.731500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Exarcheia.',
  },
  {
    id: 'node-ath-7-1',
    name: 'Psyrri Sector 1 High Street',
    zone: 'Psyrri',
    location: { latitude: 37.993800, longitude: 23.735500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Psyrri.',
  },
  {
    id: 'node-ath-7-2',
    name: 'Psyrri Sector 2 High Street',
    zone: 'Psyrri',
    location: { latitude: 37.996800, longitude: 23.738500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Psyrri.',
  },
  {
    id: 'node-ath-7-3',
    name: 'Psyrri Sector 3 High Street',
    zone: 'Psyrri',
    location: { latitude: 37.999800, longitude: 23.741500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Psyrri.',
  },
  {
    id: 'node-ath-8-1',
    name: 'Kifisia Sector 1 High Street',
    zone: 'Kifisia',
    location: { latitude: 38.005800, longitude: 23.745500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kifisia.',
  },
  {
    id: 'node-ath-8-2',
    name: 'Kifisia Sector 2 High Street',
    zone: 'Kifisia',
    location: { latitude: 38.008800, longitude: 23.748500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kifisia.',
  },
  {
    id: 'node-ath-8-3',
    name: 'Kifisia Sector 3 High Street',
    zone: 'Kifisia',
    location: { latitude: 38.011800, longitude: 23.751500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kifisia.',
  },
  {
    id: 'node-ath-9-1',
    name: 'Glyfada Sector 1 High Street',
    zone: 'Glyfada',
    location: { latitude: 38.017800, longitude: 23.755500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Glyfada.',
  },
  {
    id: 'node-ath-9-2',
    name: 'Glyfada Sector 2 High Street',
    zone: 'Glyfada',
    location: { latitude: 38.020800, longitude: 23.758500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Glyfada.',
  },
  {
    id: 'node-ath-9-3',
    name: 'Glyfada Sector 3 High Street',
    zone: 'Glyfada',
    location: { latitude: 38.023800, longitude: 23.761500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Glyfada.',
  },
  {
    id: 'node-ath-10-1',
    name: 'Piraeus Sector 1 High Street',
    zone: 'Piraeus',
    location: { latitude: 38.029800, longitude: 23.765500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Piraeus.',
  },
  {
    id: 'node-ath-10-2',
    name: 'Piraeus Sector 2 High Street',
    zone: 'Piraeus',
    location: { latitude: 38.032800, longitude: 23.768500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Piraeus.',
  },
  {
    id: 'node-ath-10-3',
    name: 'Piraeus Sector 3 High Street',
    zone: 'Piraeus',
    location: { latitude: 38.035800, longitude: 23.771500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Piraeus.',
  },
];

export const ATHENS_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ath-1',
    fromNodeId: 'node-ath-1-1',
    toNodeId: 'node-ath-1-2',
    roadName: 'Plaka Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-2',
    fromNodeId: 'node-ath-1-2',
    toNodeId: 'node-ath-1-3',
    roadName: 'Plaka Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-3',
    fromNodeId: 'node-ath-2-1',
    toNodeId: 'node-ath-2-2',
    roadName: 'Monastiraki Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-4',
    fromNodeId: 'node-ath-2-2',
    toNodeId: 'node-ath-2-3',
    roadName: 'Monastiraki Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-5',
    fromNodeId: 'node-ath-3-1',
    toNodeId: 'node-ath-3-2',
    roadName: 'Kolonaki Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-6',
    fromNodeId: 'node-ath-3-2',
    toNodeId: 'node-ath-3-3',
    roadName: 'Kolonaki Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-7',
    fromNodeId: 'node-ath-4-1',
    toNodeId: 'node-ath-4-2',
    roadName: 'Syntagma Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-8',
    fromNodeId: 'node-ath-4-2',
    toNodeId: 'node-ath-4-3',
    roadName: 'Syntagma Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-9',
    fromNodeId: 'node-ath-5-1',
    toNodeId: 'node-ath-5-2',
    roadName: 'Koukaki Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-10',
    fromNodeId: 'node-ath-5-2',
    toNodeId: 'node-ath-5-3',
    roadName: 'Koukaki Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-11',
    fromNodeId: 'node-ath-6-1',
    toNodeId: 'node-ath-6-2',
    roadName: 'Exarcheia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-12',
    fromNodeId: 'node-ath-6-2',
    toNodeId: 'node-ath-6-3',
    roadName: 'Exarcheia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-13',
    fromNodeId: 'node-ath-7-1',
    toNodeId: 'node-ath-7-2',
    roadName: 'Psyrri Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-14',
    fromNodeId: 'node-ath-7-2',
    toNodeId: 'node-ath-7-3',
    roadName: 'Psyrri Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-15',
    fromNodeId: 'node-ath-8-1',
    toNodeId: 'node-ath-8-2',
    roadName: 'Kifisia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-16',
    fromNodeId: 'node-ath-8-2',
    toNodeId: 'node-ath-8-3',
    roadName: 'Kifisia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-17',
    fromNodeId: 'node-ath-9-1',
    toNodeId: 'node-ath-9-2',
    roadName: 'Glyfada Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-18',
    fromNodeId: 'node-ath-9-2',
    toNodeId: 'node-ath-9-3',
    roadName: 'Glyfada Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-19',
    fromNodeId: 'node-ath-10-1',
    toNodeId: 'node-ath-10-2',
    roadName: 'Piraeus Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ath-20',
    fromNodeId: 'node-ath-10-2',
    toNodeId: 'node-ath-10-3',
    roadName: 'Piraeus Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
