/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Atlanta Peachtree Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const ATLANTA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 33.749,
  longitude: -84.388,
};

export const ATLANTA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-atl-1-1',
    name: 'Midtown Atlanta Sector 1 High Street',
    zone: 'Midtown Atlanta',
    location: { latitude: 33.687000, longitude: -84.440000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Midtown Atlanta.',
  },
  {
    id: 'node-atl-1-2',
    name: 'Midtown Atlanta Sector 2 High Street',
    zone: 'Midtown Atlanta',
    location: { latitude: 33.690000, longitude: -84.437000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Midtown Atlanta.',
  },
  {
    id: 'node-atl-1-3',
    name: 'Midtown Atlanta Sector 3 High Street',
    zone: 'Midtown Atlanta',
    location: { latitude: 33.693000, longitude: -84.434000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Midtown Atlanta.',
  },
  {
    id: 'node-atl-2-1',
    name: 'Buckhead Sector 1 High Street',
    zone: 'Buckhead',
    location: { latitude: 33.699000, longitude: -84.430000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Buckhead.',
  },
  {
    id: 'node-atl-2-2',
    name: 'Buckhead Sector 2 High Street',
    zone: 'Buckhead',
    location: { latitude: 33.702000, longitude: -84.427000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Buckhead.',
  },
  {
    id: 'node-atl-2-3',
    name: 'Buckhead Sector 3 High Street',
    zone: 'Buckhead',
    location: { latitude: 33.705000, longitude: -84.424000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Buckhead.',
  },
  {
    id: 'node-atl-3-1',
    name: 'Downtown Atlanta Sector 1 High Street',
    zone: 'Downtown Atlanta',
    location: { latitude: 33.711000, longitude: -84.420000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Atlanta.',
  },
  {
    id: 'node-atl-3-2',
    name: 'Downtown Atlanta Sector 2 High Street',
    zone: 'Downtown Atlanta',
    location: { latitude: 33.714000, longitude: -84.417000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Atlanta.',
  },
  {
    id: 'node-atl-3-3',
    name: 'Downtown Atlanta Sector 3 High Street',
    zone: 'Downtown Atlanta',
    location: { latitude: 33.717000, longitude: -84.414000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Atlanta.',
  },
  {
    id: 'node-atl-4-1',
    name: 'Inman Park Sector 1 High Street',
    zone: 'Inman Park',
    location: { latitude: 33.723000, longitude: -84.410000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Inman Park.',
  },
  {
    id: 'node-atl-4-2',
    name: 'Inman Park Sector 2 High Street',
    zone: 'Inman Park',
    location: { latitude: 33.726000, longitude: -84.407000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Inman Park.',
  },
  {
    id: 'node-atl-4-3',
    name: 'Inman Park Sector 3 High Street',
    zone: 'Inman Park',
    location: { latitude: 33.729000, longitude: -84.404000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Inman Park.',
  },
  {
    id: 'node-atl-5-1',
    name: 'Old Fourth Ward Sector 1 High Street',
    zone: 'Old Fourth Ward',
    location: { latitude: 33.735000, longitude: -84.400000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old Fourth Ward.',
  },
  {
    id: 'node-atl-5-2',
    name: 'Old Fourth Ward Sector 2 High Street',
    zone: 'Old Fourth Ward',
    location: { latitude: 33.738000, longitude: -84.397000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old Fourth Ward.',
  },
  {
    id: 'node-atl-5-3',
    name: 'Old Fourth Ward Sector 3 High Street',
    zone: 'Old Fourth Ward',
    location: { latitude: 33.741000, longitude: -84.394000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old Fourth Ward.',
  },
  {
    id: 'node-atl-6-1',
    name: 'Virginia-Highland Sector 1 High Street',
    zone: 'Virginia-Highland',
    location: { latitude: 33.747000, longitude: -84.390000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Virginia-Highland.',
  },
  {
    id: 'node-atl-6-2',
    name: 'Virginia-Highland Sector 2 High Street',
    zone: 'Virginia-Highland',
    location: { latitude: 33.750000, longitude: -84.387000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Virginia-Highland.',
  },
  {
    id: 'node-atl-6-3',
    name: 'Virginia-Highland Sector 3 High Street',
    zone: 'Virginia-Highland',
    location: { latitude: 33.753000, longitude: -84.384000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Virginia-Highland.',
  },
  {
    id: 'node-atl-7-1',
    name: 'West Midtown Sector 1 High Street',
    zone: 'West Midtown',
    location: { latitude: 33.759000, longitude: -84.380000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in West Midtown.',
  },
  {
    id: 'node-atl-7-2',
    name: 'West Midtown Sector 2 High Street',
    zone: 'West Midtown',
    location: { latitude: 33.762000, longitude: -84.377000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in West Midtown.',
  },
  {
    id: 'node-atl-7-3',
    name: 'West Midtown Sector 3 High Street',
    zone: 'West Midtown',
    location: { latitude: 33.765000, longitude: -84.374000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in West Midtown.',
  },
  {
    id: 'node-atl-8-1',
    name: 'Poncey-Highland Sector 1 High Street',
    zone: 'Poncey-Highland',
    location: { latitude: 33.771000, longitude: -84.370000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Poncey-Highland.',
  },
  {
    id: 'node-atl-8-2',
    name: 'Poncey-Highland Sector 2 High Street',
    zone: 'Poncey-Highland',
    location: { latitude: 33.774000, longitude: -84.367000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Poncey-Highland.',
  },
  {
    id: 'node-atl-8-3',
    name: 'Poncey-Highland Sector 3 High Street',
    zone: 'Poncey-Highland',
    location: { latitude: 33.777000, longitude: -84.364000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Poncey-Highland.',
  },
  {
    id: 'node-atl-9-1',
    name: 'Decatur Sector 1 High Street',
    zone: 'Decatur',
    location: { latitude: 33.783000, longitude: -84.360000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Decatur.',
  },
  {
    id: 'node-atl-9-2',
    name: 'Decatur Sector 2 High Street',
    zone: 'Decatur',
    location: { latitude: 33.786000, longitude: -84.357000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Decatur.',
  },
  {
    id: 'node-atl-9-3',
    name: 'Decatur Sector 3 High Street',
    zone: 'Decatur',
    location: { latitude: 33.789000, longitude: -84.354000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Decatur.',
  },
  {
    id: 'node-atl-10-1',
    name: 'Atlantic Station Sector 1 High Street',
    zone: 'Atlantic Station',
    location: { latitude: 33.795000, longitude: -84.350000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Atlantic Station.',
  },
  {
    id: 'node-atl-10-2',
    name: 'Atlantic Station Sector 2 High Street',
    zone: 'Atlantic Station',
    location: { latitude: 33.798000, longitude: -84.347000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Atlantic Station.',
  },
  {
    id: 'node-atl-10-3',
    name: 'Atlantic Station Sector 3 High Street',
    zone: 'Atlantic Station',
    location: { latitude: 33.801000, longitude: -84.344000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Atlantic Station.',
  },
];

export const ATLANTA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-atl-1',
    fromNodeId: 'node-atl-1-1',
    toNodeId: 'node-atl-1-2',
    roadName: 'Midtown Atlanta Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-2',
    fromNodeId: 'node-atl-1-2',
    toNodeId: 'node-atl-1-3',
    roadName: 'Midtown Atlanta Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-3',
    fromNodeId: 'node-atl-2-1',
    toNodeId: 'node-atl-2-2',
    roadName: 'Buckhead Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-4',
    fromNodeId: 'node-atl-2-2',
    toNodeId: 'node-atl-2-3',
    roadName: 'Buckhead Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-5',
    fromNodeId: 'node-atl-3-1',
    toNodeId: 'node-atl-3-2',
    roadName: 'Downtown Atlanta Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-6',
    fromNodeId: 'node-atl-3-2',
    toNodeId: 'node-atl-3-3',
    roadName: 'Downtown Atlanta Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-7',
    fromNodeId: 'node-atl-4-1',
    toNodeId: 'node-atl-4-2',
    roadName: 'Inman Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-8',
    fromNodeId: 'node-atl-4-2',
    toNodeId: 'node-atl-4-3',
    roadName: 'Inman Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-9',
    fromNodeId: 'node-atl-5-1',
    toNodeId: 'node-atl-5-2',
    roadName: 'Old Fourth Ward Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-10',
    fromNodeId: 'node-atl-5-2',
    toNodeId: 'node-atl-5-3',
    roadName: 'Old Fourth Ward Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-11',
    fromNodeId: 'node-atl-6-1',
    toNodeId: 'node-atl-6-2',
    roadName: 'Virginia-Highland Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-12',
    fromNodeId: 'node-atl-6-2',
    toNodeId: 'node-atl-6-3',
    roadName: 'Virginia-Highland Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-13',
    fromNodeId: 'node-atl-7-1',
    toNodeId: 'node-atl-7-2',
    roadName: 'West Midtown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-14',
    fromNodeId: 'node-atl-7-2',
    toNodeId: 'node-atl-7-3',
    roadName: 'West Midtown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-15',
    fromNodeId: 'node-atl-8-1',
    toNodeId: 'node-atl-8-2',
    roadName: 'Poncey-Highland Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-16',
    fromNodeId: 'node-atl-8-2',
    toNodeId: 'node-atl-8-3',
    roadName: 'Poncey-Highland Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-17',
    fromNodeId: 'node-atl-9-1',
    toNodeId: 'node-atl-9-2',
    roadName: 'Decatur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-18',
    fromNodeId: 'node-atl-9-2',
    toNodeId: 'node-atl-9-3',
    roadName: 'Decatur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-19',
    fromNodeId: 'node-atl-10-1',
    toNodeId: 'node-atl-10-2',
    roadName: 'Atlantic Station Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-atl-20',
    fromNodeId: 'node-atl-10-2',
    toNodeId: 'node-atl-10-3',
    roadName: 'Atlantic Station Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
