/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Auckland Waitematā Harbour
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const AUCKLAND_BASE_COORDINATE: GeoCoordinate = {
  latitude: -36.8485,
  longitude: 174.7633,
};

export const AUCKLAND_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-auc-1-1',
    name: 'Auckland CBD Sector 1 High Street',
    zone: 'Auckland CBD',
    location: { latitude: -36.910500, longitude: 174.711300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Auckland CBD.',
  },
  {
    id: 'node-auc-1-2',
    name: 'Auckland CBD Sector 2 High Street',
    zone: 'Auckland CBD',
    location: { latitude: -36.907500, longitude: 174.714300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Auckland CBD.',
  },
  {
    id: 'node-auc-1-3',
    name: 'Auckland CBD Sector 3 High Street',
    zone: 'Auckland CBD',
    location: { latitude: -36.904500, longitude: 174.717300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Auckland CBD.',
  },
  {
    id: 'node-auc-2-1',
    name: 'Ponsonby Sector 1 High Street',
    zone: 'Ponsonby',
    location: { latitude: -36.898500, longitude: 174.721300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ponsonby.',
  },
  {
    id: 'node-auc-2-2',
    name: 'Ponsonby Sector 2 High Street',
    zone: 'Ponsonby',
    location: { latitude: -36.895500, longitude: 174.724300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ponsonby.',
  },
  {
    id: 'node-auc-2-3',
    name: 'Ponsonby Sector 3 High Street',
    zone: 'Ponsonby',
    location: { latitude: -36.892500, longitude: 174.727300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ponsonby.',
  },
  {
    id: 'node-auc-3-1',
    name: 'Parnell Sector 1 High Street',
    zone: 'Parnell',
    location: { latitude: -36.886500, longitude: 174.731300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Parnell.',
  },
  {
    id: 'node-auc-3-2',
    name: 'Parnell Sector 2 High Street',
    zone: 'Parnell',
    location: { latitude: -36.883500, longitude: 174.734300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Parnell.',
  },
  {
    id: 'node-auc-3-3',
    name: 'Parnell Sector 3 High Street',
    zone: 'Parnell',
    location: { latitude: -36.880500, longitude: 174.737300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Parnell.',
  },
  {
    id: 'node-auc-4-1',
    name: 'Newmarket Sector 1 High Street',
    zone: 'Newmarket',
    location: { latitude: -36.874500, longitude: 174.741300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Newmarket.',
  },
  {
    id: 'node-auc-4-2',
    name: 'Newmarket Sector 2 High Street',
    zone: 'Newmarket',
    location: { latitude: -36.871500, longitude: 174.744300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Newmarket.',
  },
  {
    id: 'node-auc-4-3',
    name: 'Newmarket Sector 3 High Street',
    zone: 'Newmarket',
    location: { latitude: -36.868500, longitude: 174.747300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Newmarket.',
  },
  {
    id: 'node-auc-5-1',
    name: 'Mount Eden Sector 1 High Street',
    zone: 'Mount Eden',
    location: { latitude: -36.862500, longitude: 174.751300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mount Eden.',
  },
  {
    id: 'node-auc-5-2',
    name: 'Mount Eden Sector 2 High Street',
    zone: 'Mount Eden',
    location: { latitude: -36.859500, longitude: 174.754300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mount Eden.',
  },
  {
    id: 'node-auc-5-3',
    name: 'Mount Eden Sector 3 High Street',
    zone: 'Mount Eden',
    location: { latitude: -36.856500, longitude: 174.757300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mount Eden.',
  },
  {
    id: 'node-auc-6-1',
    name: 'Takapuna Sector 1 High Street',
    zone: 'Takapuna',
    location: { latitude: -36.850500, longitude: 174.761300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Takapuna.',
  },
  {
    id: 'node-auc-6-2',
    name: 'Takapuna Sector 2 High Street',
    zone: 'Takapuna',
    location: { latitude: -36.847500, longitude: 174.764300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Takapuna.',
  },
  {
    id: 'node-auc-6-3',
    name: 'Takapuna Sector 3 High Street',
    zone: 'Takapuna',
    location: { latitude: -36.844500, longitude: 174.767300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Takapuna.',
  },
  {
    id: 'node-auc-7-1',
    name: 'Grey Lynn Sector 1 High Street',
    zone: 'Grey Lynn',
    location: { latitude: -36.838500, longitude: 174.771300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Grey Lynn.',
  },
  {
    id: 'node-auc-7-2',
    name: 'Grey Lynn Sector 2 High Street',
    zone: 'Grey Lynn',
    location: { latitude: -36.835500, longitude: 174.774300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Grey Lynn.',
  },
  {
    id: 'node-auc-7-3',
    name: 'Grey Lynn Sector 3 High Street',
    zone: 'Grey Lynn',
    location: { latitude: -36.832500, longitude: 174.777300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Grey Lynn.',
  },
  {
    id: 'node-auc-8-1',
    name: 'Britomart Sector 1 High Street',
    zone: 'Britomart',
    location: { latitude: -36.826500, longitude: 174.781300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Britomart.',
  },
  {
    id: 'node-auc-8-2',
    name: 'Britomart Sector 2 High Street',
    zone: 'Britomart',
    location: { latitude: -36.823500, longitude: 174.784300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Britomart.',
  },
  {
    id: 'node-auc-8-3',
    name: 'Britomart Sector 3 High Street',
    zone: 'Britomart',
    location: { latitude: -36.820500, longitude: 174.787300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Britomart.',
  },
  {
    id: 'node-auc-9-1',
    name: 'Devonport Sector 1 High Street',
    zone: 'Devonport',
    location: { latitude: -36.814500, longitude: 174.791300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Devonport.',
  },
  {
    id: 'node-auc-9-2',
    name: 'Devonport Sector 2 High Street',
    zone: 'Devonport',
    location: { latitude: -36.811500, longitude: 174.794300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Devonport.',
  },
  {
    id: 'node-auc-9-3',
    name: 'Devonport Sector 3 High Street',
    zone: 'Devonport',
    location: { latitude: -36.808500, longitude: 174.797300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Devonport.',
  },
  {
    id: 'node-auc-10-1',
    name: 'K Road Sector 1 High Street',
    zone: 'K Road',
    location: { latitude: -36.802500, longitude: 174.801300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in K Road.',
  },
  {
    id: 'node-auc-10-2',
    name: 'K Road Sector 2 High Street',
    zone: 'K Road',
    location: { latitude: -36.799500, longitude: 174.804300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in K Road.',
  },
  {
    id: 'node-auc-10-3',
    name: 'K Road Sector 3 High Street',
    zone: 'K Road',
    location: { latitude: -36.796500, longitude: 174.807300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in K Road.',
  },
];

export const AUCKLAND_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-auc-1',
    fromNodeId: 'node-auc-1-1',
    toNodeId: 'node-auc-1-2',
    roadName: 'Auckland CBD Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-2',
    fromNodeId: 'node-auc-1-2',
    toNodeId: 'node-auc-1-3',
    roadName: 'Auckland CBD Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-3',
    fromNodeId: 'node-auc-2-1',
    toNodeId: 'node-auc-2-2',
    roadName: 'Ponsonby Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-4',
    fromNodeId: 'node-auc-2-2',
    toNodeId: 'node-auc-2-3',
    roadName: 'Ponsonby Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-5',
    fromNodeId: 'node-auc-3-1',
    toNodeId: 'node-auc-3-2',
    roadName: 'Parnell Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-6',
    fromNodeId: 'node-auc-3-2',
    toNodeId: 'node-auc-3-3',
    roadName: 'Parnell Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-7',
    fromNodeId: 'node-auc-4-1',
    toNodeId: 'node-auc-4-2',
    roadName: 'Newmarket Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-8',
    fromNodeId: 'node-auc-4-2',
    toNodeId: 'node-auc-4-3',
    roadName: 'Newmarket Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-9',
    fromNodeId: 'node-auc-5-1',
    toNodeId: 'node-auc-5-2',
    roadName: 'Mount Eden Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-10',
    fromNodeId: 'node-auc-5-2',
    toNodeId: 'node-auc-5-3',
    roadName: 'Mount Eden Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-11',
    fromNodeId: 'node-auc-6-1',
    toNodeId: 'node-auc-6-2',
    roadName: 'Takapuna Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-12',
    fromNodeId: 'node-auc-6-2',
    toNodeId: 'node-auc-6-3',
    roadName: 'Takapuna Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-13',
    fromNodeId: 'node-auc-7-1',
    toNodeId: 'node-auc-7-2',
    roadName: 'Grey Lynn Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-14',
    fromNodeId: 'node-auc-7-2',
    toNodeId: 'node-auc-7-3',
    roadName: 'Grey Lynn Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-15',
    fromNodeId: 'node-auc-8-1',
    toNodeId: 'node-auc-8-2',
    roadName: 'Britomart Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-16',
    fromNodeId: 'node-auc-8-2',
    toNodeId: 'node-auc-8-3',
    roadName: 'Britomart Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-17',
    fromNodeId: 'node-auc-9-1',
    toNodeId: 'node-auc-9-2',
    roadName: 'Devonport Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-18',
    fromNodeId: 'node-auc-9-2',
    toNodeId: 'node-auc-9-3',
    roadName: 'Devonport Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-19',
    fromNodeId: 'node-auc-10-1',
    toNodeId: 'node-auc-10-2',
    roadName: 'K Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-auc-20',
    fromNodeId: 'node-auc-10-2',
    toNodeId: 'node-auc-10-3',
    roadName: 'K Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
