/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Chhatrapati Sambhajinagar Heritage Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const AURANGABAD_BASE_COORDINATE: GeoCoordinate = {
  latitude: 19.8762,
  longitude: 75.3433,
};

export const AURANGABAD_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-aur-1-1',
    name: 'Cannaught Place Sector 1 High Street',
    zone: 'Cannaught Place',
    location: { latitude: 19.814200, longitude: 75.291300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cannaught Place.',
  },
  {
    id: 'node-aur-1-2',
    name: 'Cannaught Place Sector 2 High Street',
    zone: 'Cannaught Place',
    location: { latitude: 19.817200, longitude: 75.294300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cannaught Place.',
  },
  {
    id: 'node-aur-1-3',
    name: 'Cannaught Place Sector 3 High Street',
    zone: 'Cannaught Place',
    location: { latitude: 19.820200, longitude: 75.297300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cannaught Place.',
  },
  {
    id: 'node-aur-2-1',
    name: 'Samarth Nagar Sector 1 High Street',
    zone: 'Samarth Nagar',
    location: { latitude: 19.826200, longitude: 75.301300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Samarth Nagar.',
  },
  {
    id: 'node-aur-2-2',
    name: 'Samarth Nagar Sector 2 High Street',
    zone: 'Samarth Nagar',
    location: { latitude: 19.829200, longitude: 75.304300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Samarth Nagar.',
  },
  {
    id: 'node-aur-2-3',
    name: 'Samarth Nagar Sector 3 High Street',
    zone: 'Samarth Nagar',
    location: { latitude: 19.832200, longitude: 75.307300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Samarth Nagar.',
  },
  {
    id: 'node-aur-3-1',
    name: 'CIDCO N-1 to N-6 Sector 1 High Street',
    zone: 'CIDCO N-1 to N-6',
    location: { latitude: 19.838200, longitude: 75.311300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in CIDCO N-1 to N-6.',
  },
  {
    id: 'node-aur-3-2',
    name: 'CIDCO N-1 to N-6 Sector 2 High Street',
    zone: 'CIDCO N-1 to N-6',
    location: { latitude: 19.841200, longitude: 75.314300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in CIDCO N-1 to N-6.',
  },
  {
    id: 'node-aur-3-3',
    name: 'CIDCO N-1 to N-6 Sector 3 High Street',
    zone: 'CIDCO N-1 to N-6',
    location: { latitude: 19.844200, longitude: 75.317300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in CIDCO N-1 to N-6.',
  },
  {
    id: 'node-aur-4-1',
    name: 'Osmanpura Sector 1 High Street',
    zone: 'Osmanpura',
    location: { latitude: 19.850200, longitude: 75.321300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Osmanpura.',
  },
  {
    id: 'node-aur-4-2',
    name: 'Osmanpura Sector 2 High Street',
    zone: 'Osmanpura',
    location: { latitude: 19.853200, longitude: 75.324300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Osmanpura.',
  },
  {
    id: 'node-aur-4-3',
    name: 'Osmanpura Sector 3 High Street',
    zone: 'Osmanpura',
    location: { latitude: 19.856200, longitude: 75.327300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Osmanpura.',
  },
  {
    id: 'node-aur-5-1',
    name: 'Garkheda Sector 1 High Street',
    zone: 'Garkheda',
    location: { latitude: 19.862200, longitude: 75.331300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Garkheda.',
  },
  {
    id: 'node-aur-5-2',
    name: 'Garkheda Sector 2 High Street',
    zone: 'Garkheda',
    location: { latitude: 19.865200, longitude: 75.334300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Garkheda.',
  },
  {
    id: 'node-aur-5-3',
    name: 'Garkheda Sector 3 High Street',
    zone: 'Garkheda',
    location: { latitude: 19.868200, longitude: 75.337300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Garkheda.',
  },
  {
    id: 'node-aur-6-1',
    name: 'Jalna Road Sector 1 High Street',
    zone: 'Jalna Road',
    location: { latitude: 19.874200, longitude: 75.341300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jalna Road.',
  },
  {
    id: 'node-aur-6-2',
    name: 'Jalna Road Sector 2 High Street',
    zone: 'Jalna Road',
    location: { latitude: 19.877200, longitude: 75.344300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jalna Road.',
  },
  {
    id: 'node-aur-6-3',
    name: 'Jalna Road Sector 3 High Street',
    zone: 'Jalna Road',
    location: { latitude: 19.880200, longitude: 75.347300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jalna Road.',
  },
  {
    id: 'node-aur-7-1',
    name: 'Seven Hills Sector 1 High Street',
    zone: 'Seven Hills',
    location: { latitude: 19.886200, longitude: 75.351300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Seven Hills.',
  },
  {
    id: 'node-aur-7-2',
    name: 'Seven Hills Sector 2 High Street',
    zone: 'Seven Hills',
    location: { latitude: 19.889200, longitude: 75.354300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Seven Hills.',
  },
  {
    id: 'node-aur-7-3',
    name: 'Seven Hills Sector 3 High Street',
    zone: 'Seven Hills',
    location: { latitude: 19.892200, longitude: 75.357300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Seven Hills.',
  },
  {
    id: 'node-aur-8-1',
    name: 'Kranti Chowk Sector 1 High Street',
    zone: 'Kranti Chowk',
    location: { latitude: 19.898200, longitude: 75.361300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kranti Chowk.',
  },
  {
    id: 'node-aur-8-2',
    name: 'Kranti Chowk Sector 2 High Street',
    zone: 'Kranti Chowk',
    location: { latitude: 19.901200, longitude: 75.364300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kranti Chowk.',
  },
  {
    id: 'node-aur-8-3',
    name: 'Kranti Chowk Sector 3 High Street',
    zone: 'Kranti Chowk',
    location: { latitude: 19.904200, longitude: 75.367300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kranti Chowk.',
  },
  {
    id: 'node-aur-9-1',
    name: 'Beed Bypass Sector 1 High Street',
    zone: 'Beed Bypass',
    location: { latitude: 19.910200, longitude: 75.371300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Beed Bypass.',
  },
  {
    id: 'node-aur-9-2',
    name: 'Beed Bypass Sector 2 High Street',
    zone: 'Beed Bypass',
    location: { latitude: 19.913200, longitude: 75.374300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Beed Bypass.',
  },
  {
    id: 'node-aur-9-3',
    name: 'Beed Bypass Sector 3 High Street',
    zone: 'Beed Bypass',
    location: { latitude: 19.916200, longitude: 75.377300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Beed Bypass.',
  },
  {
    id: 'node-aur-10-1',
    name: 'Waluj Sector 1 High Street',
    zone: 'Waluj',
    location: { latitude: 19.922200, longitude: 75.381300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Waluj.',
  },
  {
    id: 'node-aur-10-2',
    name: 'Waluj Sector 2 High Street',
    zone: 'Waluj',
    location: { latitude: 19.925200, longitude: 75.384300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Waluj.',
  },
  {
    id: 'node-aur-10-3',
    name: 'Waluj Sector 3 High Street',
    zone: 'Waluj',
    location: { latitude: 19.928200, longitude: 75.387300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Waluj.',
  },
];

export const AURANGABAD_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-aur-1',
    fromNodeId: 'node-aur-1-1',
    toNodeId: 'node-aur-1-2',
    roadName: 'Cannaught Place Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-2',
    fromNodeId: 'node-aur-1-2',
    toNodeId: 'node-aur-1-3',
    roadName: 'Cannaught Place Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-3',
    fromNodeId: 'node-aur-2-1',
    toNodeId: 'node-aur-2-2',
    roadName: 'Samarth Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-4',
    fromNodeId: 'node-aur-2-2',
    toNodeId: 'node-aur-2-3',
    roadName: 'Samarth Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-5',
    fromNodeId: 'node-aur-3-1',
    toNodeId: 'node-aur-3-2',
    roadName: 'CIDCO N-1 to N-6 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-6',
    fromNodeId: 'node-aur-3-2',
    toNodeId: 'node-aur-3-3',
    roadName: 'CIDCO N-1 to N-6 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-7',
    fromNodeId: 'node-aur-4-1',
    toNodeId: 'node-aur-4-2',
    roadName: 'Osmanpura Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-8',
    fromNodeId: 'node-aur-4-2',
    toNodeId: 'node-aur-4-3',
    roadName: 'Osmanpura Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-9',
    fromNodeId: 'node-aur-5-1',
    toNodeId: 'node-aur-5-2',
    roadName: 'Garkheda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-10',
    fromNodeId: 'node-aur-5-2',
    toNodeId: 'node-aur-5-3',
    roadName: 'Garkheda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-11',
    fromNodeId: 'node-aur-6-1',
    toNodeId: 'node-aur-6-2',
    roadName: 'Jalna Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-12',
    fromNodeId: 'node-aur-6-2',
    toNodeId: 'node-aur-6-3',
    roadName: 'Jalna Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-13',
    fromNodeId: 'node-aur-7-1',
    toNodeId: 'node-aur-7-2',
    roadName: 'Seven Hills Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-14',
    fromNodeId: 'node-aur-7-2',
    toNodeId: 'node-aur-7-3',
    roadName: 'Seven Hills Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-15',
    fromNodeId: 'node-aur-8-1',
    toNodeId: 'node-aur-8-2',
    roadName: 'Kranti Chowk Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-16',
    fromNodeId: 'node-aur-8-2',
    toNodeId: 'node-aur-8-3',
    roadName: 'Kranti Chowk Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-17',
    fromNodeId: 'node-aur-9-1',
    toNodeId: 'node-aur-9-2',
    roadName: 'Beed Bypass Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-18',
    fromNodeId: 'node-aur-9-2',
    toNodeId: 'node-aur-9-3',
    roadName: 'Beed Bypass Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-19',
    fromNodeId: 'node-aur-10-1',
    toNodeId: 'node-aur-10-2',
    roadName: 'Waluj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aur-20',
    fromNodeId: 'node-aur-10-2',
    toNodeId: 'node-aur-10-3',
    roadName: 'Waluj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
