/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Austin Silicon Hills
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const AUSTIN_BASE_COORDINATE: GeoCoordinate = {
  latitude: 30.2672,
  longitude: -97.7431,
};

export const AUSTIN_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-aus-1-1',
    name: 'Downtown Austin Sector 1 High Street',
    zone: 'Downtown Austin',
    location: { latitude: 30.205200, longitude: -97.795100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Austin.',
  },
  {
    id: 'node-aus-1-2',
    name: 'Downtown Austin Sector 2 High Street',
    zone: 'Downtown Austin',
    location: { latitude: 30.208200, longitude: -97.792100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Austin.',
  },
  {
    id: 'node-aus-1-3',
    name: 'Downtown Austin Sector 3 High Street',
    zone: 'Downtown Austin',
    location: { latitude: 30.211200, longitude: -97.789100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Austin.',
  },
  {
    id: 'node-aus-2-1',
    name: 'South Congress Sector 1 High Street',
    zone: 'South Congress',
    location: { latitude: 30.217200, longitude: -97.785100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in South Congress.',
  },
  {
    id: 'node-aus-2-2',
    name: 'South Congress Sector 2 High Street',
    zone: 'South Congress',
    location: { latitude: 30.220200, longitude: -97.782100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in South Congress.',
  },
  {
    id: 'node-aus-2-3',
    name: 'South Congress Sector 3 High Street',
    zone: 'South Congress',
    location: { latitude: 30.223200, longitude: -97.779100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in South Congress.',
  },
  {
    id: 'node-aus-3-1',
    name: 'East Austin Sector 1 High Street',
    zone: 'East Austin',
    location: { latitude: 30.229200, longitude: -97.775100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in East Austin.',
  },
  {
    id: 'node-aus-3-2',
    name: 'East Austin Sector 2 High Street',
    zone: 'East Austin',
    location: { latitude: 30.232200, longitude: -97.772100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in East Austin.',
  },
  {
    id: 'node-aus-3-3',
    name: 'East Austin Sector 3 High Street',
    zone: 'East Austin',
    location: { latitude: 30.235200, longitude: -97.769100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in East Austin.',
  },
  {
    id: 'node-aus-4-1',
    name: 'Rainey Street Sector 1 High Street',
    zone: 'Rainey Street',
    location: { latitude: 30.241200, longitude: -97.765100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rainey Street.',
  },
  {
    id: 'node-aus-4-2',
    name: 'Rainey Street Sector 2 High Street',
    zone: 'Rainey Street',
    location: { latitude: 30.244200, longitude: -97.762100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rainey Street.',
  },
  {
    id: 'node-aus-4-3',
    name: 'Rainey Street Sector 3 High Street',
    zone: 'Rainey Street',
    location: { latitude: 30.247200, longitude: -97.759100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rainey Street.',
  },
  {
    id: 'node-aus-5-1',
    name: 'Zilker Sector 1 High Street',
    zone: 'Zilker',
    location: { latitude: 30.253200, longitude: -97.755100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zilker.',
  },
  {
    id: 'node-aus-5-2',
    name: 'Zilker Sector 2 High Street',
    zone: 'Zilker',
    location: { latitude: 30.256200, longitude: -97.752100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zilker.',
  },
  {
    id: 'node-aus-5-3',
    name: 'Zilker Sector 3 High Street',
    zone: 'Zilker',
    location: { latitude: 30.259200, longitude: -97.749100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zilker.',
  },
  {
    id: 'node-aus-6-1',
    name: 'Domain Northside Sector 1 High Street',
    zone: 'Domain Northside',
    location: { latitude: 30.265200, longitude: -97.745100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Domain Northside.',
  },
  {
    id: 'node-aus-6-2',
    name: 'Domain Northside Sector 2 High Street',
    zone: 'Domain Northside',
    location: { latitude: 30.268200, longitude: -97.742100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Domain Northside.',
  },
  {
    id: 'node-aus-6-3',
    name: 'Domain Northside Sector 3 High Street',
    zone: 'Domain Northside',
    location: { latitude: 30.271200, longitude: -97.739100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Domain Northside.',
  },
  {
    id: 'node-aus-7-1',
    name: 'Barton Hills Sector 1 High Street',
    zone: 'Barton Hills',
    location: { latitude: 30.277200, longitude: -97.735100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Barton Hills.',
  },
  {
    id: 'node-aus-7-2',
    name: 'Barton Hills Sector 2 High Street',
    zone: 'Barton Hills',
    location: { latitude: 30.280200, longitude: -97.732100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Barton Hills.',
  },
  {
    id: 'node-aus-7-3',
    name: 'Barton Hills Sector 3 High Street',
    zone: 'Barton Hills',
    location: { latitude: 30.283200, longitude: -97.729100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Barton Hills.',
  },
  {
    id: 'node-aus-8-1',
    name: 'Hyde Park Austin Sector 1 High Street',
    zone: 'Hyde Park Austin',
    location: { latitude: 30.289200, longitude: -97.725100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park Austin.',
  },
  {
    id: 'node-aus-8-2',
    name: 'Hyde Park Austin Sector 2 High Street',
    zone: 'Hyde Park Austin',
    location: { latitude: 30.292200, longitude: -97.722100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park Austin.',
  },
  {
    id: 'node-aus-8-3',
    name: 'Hyde Park Austin Sector 3 High Street',
    zone: 'Hyde Park Austin',
    location: { latitude: 30.295200, longitude: -97.719100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park Austin.',
  },
  {
    id: 'node-aus-9-1',
    name: 'Mueller Sector 1 High Street',
    zone: 'Mueller',
    location: { latitude: 30.301200, longitude: -97.715100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mueller.',
  },
  {
    id: 'node-aus-9-2',
    name: 'Mueller Sector 2 High Street',
    zone: 'Mueller',
    location: { latitude: 30.304200, longitude: -97.712100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mueller.',
  },
  {
    id: 'node-aus-9-3',
    name: 'Mueller Sector 3 High Street',
    zone: 'Mueller',
    location: { latitude: 30.307200, longitude: -97.709100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mueller.',
  },
  {
    id: 'node-aus-10-1',
    name: 'Travis Heights Sector 1 High Street',
    zone: 'Travis Heights',
    location: { latitude: 30.313200, longitude: -97.705100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Travis Heights.',
  },
  {
    id: 'node-aus-10-2',
    name: 'Travis Heights Sector 2 High Street',
    zone: 'Travis Heights',
    location: { latitude: 30.316200, longitude: -97.702100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Travis Heights.',
  },
  {
    id: 'node-aus-10-3',
    name: 'Travis Heights Sector 3 High Street',
    zone: 'Travis Heights',
    location: { latitude: 30.319200, longitude: -97.699100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Travis Heights.',
  },
];

export const AUSTIN_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-aus-1',
    fromNodeId: 'node-aus-1-1',
    toNodeId: 'node-aus-1-2',
    roadName: 'Downtown Austin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-2',
    fromNodeId: 'node-aus-1-2',
    toNodeId: 'node-aus-1-3',
    roadName: 'Downtown Austin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-3',
    fromNodeId: 'node-aus-2-1',
    toNodeId: 'node-aus-2-2',
    roadName: 'South Congress Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-4',
    fromNodeId: 'node-aus-2-2',
    toNodeId: 'node-aus-2-3',
    roadName: 'South Congress Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-5',
    fromNodeId: 'node-aus-3-1',
    toNodeId: 'node-aus-3-2',
    roadName: 'East Austin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-6',
    fromNodeId: 'node-aus-3-2',
    toNodeId: 'node-aus-3-3',
    roadName: 'East Austin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-7',
    fromNodeId: 'node-aus-4-1',
    toNodeId: 'node-aus-4-2',
    roadName: 'Rainey Street Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-8',
    fromNodeId: 'node-aus-4-2',
    toNodeId: 'node-aus-4-3',
    roadName: 'Rainey Street Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-9',
    fromNodeId: 'node-aus-5-1',
    toNodeId: 'node-aus-5-2',
    roadName: 'Zilker Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-10',
    fromNodeId: 'node-aus-5-2',
    toNodeId: 'node-aus-5-3',
    roadName: 'Zilker Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-11',
    fromNodeId: 'node-aus-6-1',
    toNodeId: 'node-aus-6-2',
    roadName: 'Domain Northside Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-12',
    fromNodeId: 'node-aus-6-2',
    toNodeId: 'node-aus-6-3',
    roadName: 'Domain Northside Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-13',
    fromNodeId: 'node-aus-7-1',
    toNodeId: 'node-aus-7-2',
    roadName: 'Barton Hills Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-14',
    fromNodeId: 'node-aus-7-2',
    toNodeId: 'node-aus-7-3',
    roadName: 'Barton Hills Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-15',
    fromNodeId: 'node-aus-8-1',
    toNodeId: 'node-aus-8-2',
    roadName: 'Hyde Park Austin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-16',
    fromNodeId: 'node-aus-8-2',
    toNodeId: 'node-aus-8-3',
    roadName: 'Hyde Park Austin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-17',
    fromNodeId: 'node-aus-9-1',
    toNodeId: 'node-aus-9-2',
    roadName: 'Mueller Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-18',
    fromNodeId: 'node-aus-9-2',
    toNodeId: 'node-aus-9-3',
    roadName: 'Mueller Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-19',
    fromNodeId: 'node-aus-10-1',
    toNodeId: 'node-aus-10-2',
    roadName: 'Travis Heights Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-aus-20',
    fromNodeId: 'node-aus-10-2',
    toNodeId: 'node-aus-10-3',
    roadName: 'Travis Heights Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
