/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Bangkok Chao Phraya Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BANGKOK_BASE_COORDINATE: GeoCoordinate = {
  latitude: 13.7563,
  longitude: 100.5018,
};

export const BANGKOK_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ban-1-1',
    name: 'Sukhumvit Sector 1 High Street',
    zone: 'Sukhumvit',
    location: { latitude: 13.694300, longitude: 100.449800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sukhumvit.',
  },
  {
    id: 'node-ban-1-2',
    name: 'Sukhumvit Sector 2 High Street',
    zone: 'Sukhumvit',
    location: { latitude: 13.697300, longitude: 100.452800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sukhumvit.',
  },
  {
    id: 'node-ban-1-3',
    name: 'Sukhumvit Sector 3 High Street',
    zone: 'Sukhumvit',
    location: { latitude: 13.700300, longitude: 100.455800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sukhumvit.',
  },
  {
    id: 'node-ban-2-1',
    name: 'Siam Sector 1 High Street',
    zone: 'Siam',
    location: { latitude: 13.706300, longitude: 100.459800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Siam.',
  },
  {
    id: 'node-ban-2-2',
    name: 'Siam Sector 2 High Street',
    zone: 'Siam',
    location: { latitude: 13.709300, longitude: 100.462800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Siam.',
  },
  {
    id: 'node-ban-2-3',
    name: 'Siam Sector 3 High Street',
    zone: 'Siam',
    location: { latitude: 13.712300, longitude: 100.465800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Siam.',
  },
  {
    id: 'node-ban-3-1',
    name: 'Silom Sector 1 High Street',
    zone: 'Silom',
    location: { latitude: 13.718300, longitude: 100.469800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Silom.',
  },
  {
    id: 'node-ban-3-2',
    name: 'Silom Sector 2 High Street',
    zone: 'Silom',
    location: { latitude: 13.721300, longitude: 100.472800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Silom.',
  },
  {
    id: 'node-ban-3-3',
    name: 'Silom Sector 3 High Street',
    zone: 'Silom',
    location: { latitude: 13.724300, longitude: 100.475800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Silom.',
  },
  {
    id: 'node-ban-4-1',
    name: 'Thonglor Sector 1 High Street',
    zone: 'Thonglor',
    location: { latitude: 13.730300, longitude: 100.479800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Thonglor.',
  },
  {
    id: 'node-ban-4-2',
    name: 'Thonglor Sector 2 High Street',
    zone: 'Thonglor',
    location: { latitude: 13.733300, longitude: 100.482800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Thonglor.',
  },
  {
    id: 'node-ban-4-3',
    name: 'Thonglor Sector 3 High Street',
    zone: 'Thonglor',
    location: { latitude: 13.736300, longitude: 100.485800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Thonglor.',
  },
  {
    id: 'node-ban-5-1',
    name: 'Ekkamai Sector 1 High Street',
    zone: 'Ekkamai',
    location: { latitude: 13.742300, longitude: 100.489800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ekkamai.',
  },
  {
    id: 'node-ban-5-2',
    name: 'Ekkamai Sector 2 High Street',
    zone: 'Ekkamai',
    location: { latitude: 13.745300, longitude: 100.492800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ekkamai.',
  },
  {
    id: 'node-ban-5-3',
    name: 'Ekkamai Sector 3 High Street',
    zone: 'Ekkamai',
    location: { latitude: 13.748300, longitude: 100.495800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ekkamai.',
  },
  {
    id: 'node-ban-6-1',
    name: 'Ari Sector 1 High Street',
    zone: 'Ari',
    location: { latitude: 13.754300, longitude: 100.499800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ari.',
  },
  {
    id: 'node-ban-6-2',
    name: 'Ari Sector 2 High Street',
    zone: 'Ari',
    location: { latitude: 13.757300, longitude: 100.502800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ari.',
  },
  {
    id: 'node-ban-6-3',
    name: 'Ari Sector 3 High Street',
    zone: 'Ari',
    location: { latitude: 13.760300, longitude: 100.505800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ari.',
  },
  {
    id: 'node-ban-7-1',
    name: 'Sathorn Sector 1 High Street',
    zone: 'Sathorn',
    location: { latitude: 13.766300, longitude: 100.509800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sathorn.',
  },
  {
    id: 'node-ban-7-2',
    name: 'Sathorn Sector 2 High Street',
    zone: 'Sathorn',
    location: { latitude: 13.769300, longitude: 100.512800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sathorn.',
  },
  {
    id: 'node-ban-7-3',
    name: 'Sathorn Sector 3 High Street',
    zone: 'Sathorn',
    location: { latitude: 13.772300, longitude: 100.515800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sathorn.',
  },
  {
    id: 'node-ban-8-1',
    name: 'Chinatown Yaowarat Sector 1 High Street',
    zone: 'Chinatown Yaowarat',
    location: { latitude: 13.778300, longitude: 100.519800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chinatown Yaowarat.',
  },
  {
    id: 'node-ban-8-2',
    name: 'Chinatown Yaowarat Sector 2 High Street',
    zone: 'Chinatown Yaowarat',
    location: { latitude: 13.781300, longitude: 100.522800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chinatown Yaowarat.',
  },
  {
    id: 'node-ban-8-3',
    name: 'Chinatown Yaowarat Sector 3 High Street',
    zone: 'Chinatown Yaowarat',
    location: { latitude: 13.784300, longitude: 100.525800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chinatown Yaowarat.',
  },
  {
    id: 'node-ban-9-1',
    name: 'Rattanakosin Sector 1 High Street',
    zone: 'Rattanakosin',
    location: { latitude: 13.790300, longitude: 100.529800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rattanakosin.',
  },
  {
    id: 'node-ban-9-2',
    name: 'Rattanakosin Sector 2 High Street',
    zone: 'Rattanakosin',
    location: { latitude: 13.793300, longitude: 100.532800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rattanakosin.',
  },
  {
    id: 'node-ban-9-3',
    name: 'Rattanakosin Sector 3 High Street',
    zone: 'Rattanakosin',
    location: { latitude: 13.796300, longitude: 100.535800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rattanakosin.',
  },
  {
    id: 'node-ban-10-1',
    name: 'Phra Khanong Sector 1 High Street',
    zone: 'Phra Khanong',
    location: { latitude: 13.802300, longitude: 100.539800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Phra Khanong.',
  },
  {
    id: 'node-ban-10-2',
    name: 'Phra Khanong Sector 2 High Street',
    zone: 'Phra Khanong',
    location: { latitude: 13.805300, longitude: 100.542800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Phra Khanong.',
  },
  {
    id: 'node-ban-10-3',
    name: 'Phra Khanong Sector 3 High Street',
    zone: 'Phra Khanong',
    location: { latitude: 13.808300, longitude: 100.545800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Phra Khanong.',
  },
];

export const BANGKOK_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ban-1',
    fromNodeId: 'node-ban-1-1',
    toNodeId: 'node-ban-1-2',
    roadName: 'Sukhumvit Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-2',
    fromNodeId: 'node-ban-1-2',
    toNodeId: 'node-ban-1-3',
    roadName: 'Sukhumvit Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-3',
    fromNodeId: 'node-ban-2-1',
    toNodeId: 'node-ban-2-2',
    roadName: 'Siam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-4',
    fromNodeId: 'node-ban-2-2',
    toNodeId: 'node-ban-2-3',
    roadName: 'Siam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-5',
    fromNodeId: 'node-ban-3-1',
    toNodeId: 'node-ban-3-2',
    roadName: 'Silom Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-6',
    fromNodeId: 'node-ban-3-2',
    toNodeId: 'node-ban-3-3',
    roadName: 'Silom Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-7',
    fromNodeId: 'node-ban-4-1',
    toNodeId: 'node-ban-4-2',
    roadName: 'Thonglor Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-8',
    fromNodeId: 'node-ban-4-2',
    toNodeId: 'node-ban-4-3',
    roadName: 'Thonglor Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-9',
    fromNodeId: 'node-ban-5-1',
    toNodeId: 'node-ban-5-2',
    roadName: 'Ekkamai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-10',
    fromNodeId: 'node-ban-5-2',
    toNodeId: 'node-ban-5-3',
    roadName: 'Ekkamai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-11',
    fromNodeId: 'node-ban-6-1',
    toNodeId: 'node-ban-6-2',
    roadName: 'Ari Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-12',
    fromNodeId: 'node-ban-6-2',
    toNodeId: 'node-ban-6-3',
    roadName: 'Ari Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-13',
    fromNodeId: 'node-ban-7-1',
    toNodeId: 'node-ban-7-2',
    roadName: 'Sathorn Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-14',
    fromNodeId: 'node-ban-7-2',
    toNodeId: 'node-ban-7-3',
    roadName: 'Sathorn Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-15',
    fromNodeId: 'node-ban-8-1',
    toNodeId: 'node-ban-8-2',
    roadName: 'Chinatown Yaowarat Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-16',
    fromNodeId: 'node-ban-8-2',
    toNodeId: 'node-ban-8-3',
    roadName: 'Chinatown Yaowarat Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-17',
    fromNodeId: 'node-ban-9-1',
    toNodeId: 'node-ban-9-2',
    roadName: 'Rattanakosin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-18',
    fromNodeId: 'node-ban-9-2',
    toNodeId: 'node-ban-9-3',
    roadName: 'Rattanakosin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-19',
    fromNodeId: 'node-ban-10-1',
    toNodeId: 'node-ban-10-2',
    roadName: 'Phra Khanong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ban-20',
    fromNodeId: 'node-ban-10-2',
    toNodeId: 'node-ban-10-3',
    roadName: 'Phra Khanong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
