/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Barcelona Catalonia Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BARCELONA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 41.3879,
  longitude: 2.1699,
};

export const BARCELONA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bar-1-1',
    name: 'Eixample Sector 1 High Street',
    zone: 'Eixample',
    location: { latitude: 41.325900, longitude: 2.117900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Eixample.',
  },
  {
    id: 'node-bar-1-2',
    name: 'Eixample Sector 2 High Street',
    zone: 'Eixample',
    location: { latitude: 41.328900, longitude: 2.120900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Eixample.',
  },
  {
    id: 'node-bar-1-3',
    name: 'Eixample Sector 3 High Street',
    zone: 'Eixample',
    location: { latitude: 41.331900, longitude: 2.123900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Eixample.',
  },
  {
    id: 'node-bar-2-1',
    name: 'Gothic Quarter Sector 1 High Street',
    zone: 'Gothic Quarter',
    location: { latitude: 41.337900, longitude: 2.127900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gothic Quarter.',
  },
  {
    id: 'node-bar-2-2',
    name: 'Gothic Quarter Sector 2 High Street',
    zone: 'Gothic Quarter',
    location: { latitude: 41.340900, longitude: 2.130900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gothic Quarter.',
  },
  {
    id: 'node-bar-2-3',
    name: 'Gothic Quarter Sector 3 High Street',
    zone: 'Gothic Quarter',
    location: { latitude: 41.343900, longitude: 2.133900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gothic Quarter.',
  },
  {
    id: 'node-bar-3-1',
    name: 'Gràcia Sector 1 High Street',
    zone: 'Gràcia',
    location: { latitude: 41.349900, longitude: 2.137900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gràcia.',
  },
  {
    id: 'node-bar-3-2',
    name: 'Gràcia Sector 2 High Street',
    zone: 'Gràcia',
    location: { latitude: 41.352900, longitude: 2.140900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gràcia.',
  },
  {
    id: 'node-bar-3-3',
    name: 'Gràcia Sector 3 High Street',
    zone: 'Gràcia',
    location: { latitude: 41.355900, longitude: 2.143900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gràcia.',
  },
  {
    id: 'node-bar-4-1',
    name: 'El Born Sector 1 High Street',
    zone: 'El Born',
    location: { latitude: 41.361900, longitude: 2.147900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in El Born.',
  },
  {
    id: 'node-bar-4-2',
    name: 'El Born Sector 2 High Street',
    zone: 'El Born',
    location: { latitude: 41.364900, longitude: 2.150900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in El Born.',
  },
  {
    id: 'node-bar-4-3',
    name: 'El Born Sector 3 High Street',
    zone: 'El Born',
    location: { latitude: 41.367900, longitude: 2.153900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in El Born.',
  },
  {
    id: 'node-bar-5-1',
    name: 'Poblenou Sector 1 High Street',
    zone: 'Poblenou',
    location: { latitude: 41.373900, longitude: 2.157900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Poblenou.',
  },
  {
    id: 'node-bar-5-2',
    name: 'Poblenou Sector 2 High Street',
    zone: 'Poblenou',
    location: { latitude: 41.376900, longitude: 2.160900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Poblenou.',
  },
  {
    id: 'node-bar-5-3',
    name: 'Poblenou Sector 3 High Street',
    zone: 'Poblenou',
    location: { latitude: 41.379900, longitude: 2.163900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Poblenou.',
  },
  {
    id: 'node-bar-6-1',
    name: 'Barceloneta Sector 1 High Street',
    zone: 'Barceloneta',
    location: { latitude: 41.385900, longitude: 2.167900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Barceloneta.',
  },
  {
    id: 'node-bar-6-2',
    name: 'Barceloneta Sector 2 High Street',
    zone: 'Barceloneta',
    location: { latitude: 41.388900, longitude: 2.170900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Barceloneta.',
  },
  {
    id: 'node-bar-6-3',
    name: 'Barceloneta Sector 3 High Street',
    zone: 'Barceloneta',
    location: { latitude: 41.391900, longitude: 2.173900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Barceloneta.',
  },
  {
    id: 'node-bar-7-1',
    name: 'Sarrià Sector 1 High Street',
    zone: 'Sarrià',
    location: { latitude: 41.397900, longitude: 2.177900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sarrià.',
  },
  {
    id: 'node-bar-7-2',
    name: 'Sarrià Sector 2 High Street',
    zone: 'Sarrià',
    location: { latitude: 41.400900, longitude: 2.180900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sarrià.',
  },
  {
    id: 'node-bar-7-3',
    name: 'Sarrià Sector 3 High Street',
    zone: 'Sarrià',
    location: { latitude: 41.403900, longitude: 2.183900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sarrià.',
  },
  {
    id: 'node-bar-8-1',
    name: 'Sant Antoni Sector 1 High Street',
    zone: 'Sant Antoni',
    location: { latitude: 41.409900, longitude: 2.187900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sant Antoni.',
  },
  {
    id: 'node-bar-8-2',
    name: 'Sant Antoni Sector 2 High Street',
    zone: 'Sant Antoni',
    location: { latitude: 41.412900, longitude: 2.190900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sant Antoni.',
  },
  {
    id: 'node-bar-8-3',
    name: 'Sant Antoni Sector 3 High Street',
    zone: 'Sant Antoni',
    location: { latitude: 41.415900, longitude: 2.193900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sant Antoni.',
  },
  {
    id: 'node-bar-9-1',
    name: 'Les Corts Sector 1 High Street',
    zone: 'Les Corts',
    location: { latitude: 41.421900, longitude: 2.197900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Les Corts.',
  },
  {
    id: 'node-bar-9-2',
    name: 'Les Corts Sector 2 High Street',
    zone: 'Les Corts',
    location: { latitude: 41.424900, longitude: 2.200900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Les Corts.',
  },
  {
    id: 'node-bar-9-3',
    name: 'Les Corts Sector 3 High Street',
    zone: 'Les Corts',
    location: { latitude: 41.427900, longitude: 2.203900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Les Corts.',
  },
  {
    id: 'node-bar-10-1',
    name: 'Poble Sec Sector 1 High Street',
    zone: 'Poble Sec',
    location: { latitude: 41.433900, longitude: 2.207900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Poble Sec.',
  },
  {
    id: 'node-bar-10-2',
    name: 'Poble Sec Sector 2 High Street',
    zone: 'Poble Sec',
    location: { latitude: 41.436900, longitude: 2.210900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Poble Sec.',
  },
  {
    id: 'node-bar-10-3',
    name: 'Poble Sec Sector 3 High Street',
    zone: 'Poble Sec',
    location: { latitude: 41.439900, longitude: 2.213900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Poble Sec.',
  },
];

export const BARCELONA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bar-1',
    fromNodeId: 'node-bar-1-1',
    toNodeId: 'node-bar-1-2',
    roadName: 'Eixample Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-2',
    fromNodeId: 'node-bar-1-2',
    toNodeId: 'node-bar-1-3',
    roadName: 'Eixample Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-3',
    fromNodeId: 'node-bar-2-1',
    toNodeId: 'node-bar-2-2',
    roadName: 'Gothic Quarter Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-4',
    fromNodeId: 'node-bar-2-2',
    toNodeId: 'node-bar-2-3',
    roadName: 'Gothic Quarter Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-5',
    fromNodeId: 'node-bar-3-1',
    toNodeId: 'node-bar-3-2',
    roadName: 'Gràcia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-6',
    fromNodeId: 'node-bar-3-2',
    toNodeId: 'node-bar-3-3',
    roadName: 'Gràcia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-7',
    fromNodeId: 'node-bar-4-1',
    toNodeId: 'node-bar-4-2',
    roadName: 'El Born Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-8',
    fromNodeId: 'node-bar-4-2',
    toNodeId: 'node-bar-4-3',
    roadName: 'El Born Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-9',
    fromNodeId: 'node-bar-5-1',
    toNodeId: 'node-bar-5-2',
    roadName: 'Poblenou Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-10',
    fromNodeId: 'node-bar-5-2',
    toNodeId: 'node-bar-5-3',
    roadName: 'Poblenou Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-11',
    fromNodeId: 'node-bar-6-1',
    toNodeId: 'node-bar-6-2',
    roadName: 'Barceloneta Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-12',
    fromNodeId: 'node-bar-6-2',
    toNodeId: 'node-bar-6-3',
    roadName: 'Barceloneta Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-13',
    fromNodeId: 'node-bar-7-1',
    toNodeId: 'node-bar-7-2',
    roadName: 'Sarrià Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-14',
    fromNodeId: 'node-bar-7-2',
    toNodeId: 'node-bar-7-3',
    roadName: 'Sarrià Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-15',
    fromNodeId: 'node-bar-8-1',
    toNodeId: 'node-bar-8-2',
    roadName: 'Sant Antoni Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-16',
    fromNodeId: 'node-bar-8-2',
    toNodeId: 'node-bar-8-3',
    roadName: 'Sant Antoni Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-17',
    fromNodeId: 'node-bar-9-1',
    toNodeId: 'node-bar-9-2',
    roadName: 'Les Corts Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-18',
    fromNodeId: 'node-bar-9-2',
    toNodeId: 'node-bar-9-3',
    roadName: 'Les Corts Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-19',
    fromNodeId: 'node-bar-10-1',
    toNodeId: 'node-bar-10-2',
    roadName: 'Poble Sec Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bar-20',
    fromNodeId: 'node-bar-10-2',
    toNodeId: 'node-bar-10-3',
    roadName: 'Poble Sec Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
