/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Beirut Mediterranean Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BEIRUT_BASE_COORDINATE: GeoCoordinate = {
  latitude: 33.8938,
  longitude: 35.5018,
};

export const BEIRUT_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bei-1-1',
    name: 'Hamra Sector 1 High Street',
    zone: 'Hamra',
    location: { latitude: 33.831800, longitude: 35.449800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hamra.',
  },
  {
    id: 'node-bei-1-2',
    name: 'Hamra Sector 2 High Street',
    zone: 'Hamra',
    location: { latitude: 33.834800, longitude: 35.452800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hamra.',
  },
  {
    id: 'node-bei-1-3',
    name: 'Hamra Sector 3 High Street',
    zone: 'Hamra',
    location: { latitude: 33.837800, longitude: 35.455800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hamra.',
  },
  {
    id: 'node-bei-2-1',
    name: 'Achrafieh Sector 1 High Street',
    zone: 'Achrafieh',
    location: { latitude: 33.843800, longitude: 35.459800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Achrafieh.',
  },
  {
    id: 'node-bei-2-2',
    name: 'Achrafieh Sector 2 High Street',
    zone: 'Achrafieh',
    location: { latitude: 33.846800, longitude: 35.462800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Achrafieh.',
  },
  {
    id: 'node-bei-2-3',
    name: 'Achrafieh Sector 3 High Street',
    zone: 'Achrafieh',
    location: { latitude: 33.849800, longitude: 35.465800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Achrafieh.',
  },
  {
    id: 'node-bei-3-1',
    name: 'Mar Mikhaël Sector 1 High Street',
    zone: 'Mar Mikhaël',
    location: { latitude: 33.855800, longitude: 35.469800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mar Mikhaël.',
  },
  {
    id: 'node-bei-3-2',
    name: 'Mar Mikhaël Sector 2 High Street',
    zone: 'Mar Mikhaël',
    location: { latitude: 33.858800, longitude: 35.472800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mar Mikhaël.',
  },
  {
    id: 'node-bei-3-3',
    name: 'Mar Mikhaël Sector 3 High Street',
    zone: 'Mar Mikhaël',
    location: { latitude: 33.861800, longitude: 35.475800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mar Mikhaël.',
  },
  {
    id: 'node-bei-4-1',
    name: 'Gemmayzeh Sector 1 High Street',
    zone: 'Gemmayzeh',
    location: { latitude: 33.867800, longitude: 35.479800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gemmayzeh.',
  },
  {
    id: 'node-bei-4-2',
    name: 'Gemmayzeh Sector 2 High Street',
    zone: 'Gemmayzeh',
    location: { latitude: 33.870800, longitude: 35.482800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gemmayzeh.',
  },
  {
    id: 'node-bei-4-3',
    name: 'Gemmayzeh Sector 3 High Street',
    zone: 'Gemmayzeh',
    location: { latitude: 33.873800, longitude: 35.485800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gemmayzeh.',
  },
  {
    id: 'node-bei-5-1',
    name: 'Downtown Beirut Sector 1 High Street',
    zone: 'Downtown Beirut',
    location: { latitude: 33.879800, longitude: 35.489800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Beirut.',
  },
  {
    id: 'node-bei-5-2',
    name: 'Downtown Beirut Sector 2 High Street',
    zone: 'Downtown Beirut',
    location: { latitude: 33.882800, longitude: 35.492800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Beirut.',
  },
  {
    id: 'node-bei-5-3',
    name: 'Downtown Beirut Sector 3 High Street',
    zone: 'Downtown Beirut',
    location: { latitude: 33.885800, longitude: 35.495800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Beirut.',
  },
  {
    id: 'node-bei-6-1',
    name: 'Verdun Sector 1 High Street',
    zone: 'Verdun',
    location: { latitude: 33.891800, longitude: 35.499800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Verdun.',
  },
  {
    id: 'node-bei-6-2',
    name: 'Verdun Sector 2 High Street',
    zone: 'Verdun',
    location: { latitude: 33.894800, longitude: 35.502800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Verdun.',
  },
  {
    id: 'node-bei-6-3',
    name: 'Verdun Sector 3 High Street',
    zone: 'Verdun',
    location: { latitude: 33.897800, longitude: 35.505800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Verdun.',
  },
  {
    id: 'node-bei-7-1',
    name: 'Badaro Sector 1 High Street',
    zone: 'Badaro',
    location: { latitude: 33.903800, longitude: 35.509800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Badaro.',
  },
  {
    id: 'node-bei-7-2',
    name: 'Badaro Sector 2 High Street',
    zone: 'Badaro',
    location: { latitude: 33.906800, longitude: 35.512800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Badaro.',
  },
  {
    id: 'node-bei-7-3',
    name: 'Badaro Sector 3 High Street',
    zone: 'Badaro',
    location: { latitude: 33.909800, longitude: 35.515800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Badaro.',
  },
  {
    id: 'node-bei-8-1',
    name: 'Raouché Sector 1 High Street',
    zone: 'Raouché',
    location: { latitude: 33.915800, longitude: 35.519800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Raouché.',
  },
  {
    id: 'node-bei-8-2',
    name: 'Raouché Sector 2 High Street',
    zone: 'Raouché',
    location: { latitude: 33.918800, longitude: 35.522800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Raouché.',
  },
  {
    id: 'node-bei-8-3',
    name: 'Raouché Sector 3 High Street',
    zone: 'Raouché',
    location: { latitude: 33.921800, longitude: 35.525800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Raouché.',
  },
  {
    id: 'node-bei-9-1',
    name: 'Zaitunay Bay Sector 1 High Street',
    zone: 'Zaitunay Bay',
    location: { latitude: 33.927800, longitude: 35.529800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zaitunay Bay.',
  },
  {
    id: 'node-bei-9-2',
    name: 'Zaitunay Bay Sector 2 High Street',
    zone: 'Zaitunay Bay',
    location: { latitude: 33.930800, longitude: 35.532800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zaitunay Bay.',
  },
  {
    id: 'node-bei-9-3',
    name: 'Zaitunay Bay Sector 3 High Street',
    zone: 'Zaitunay Bay',
    location: { latitude: 33.933800, longitude: 35.535800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zaitunay Bay.',
  },
  {
    id: 'node-bei-10-1',
    name: 'Monot Sector 1 High Street',
    zone: 'Monot',
    location: { latitude: 33.939800, longitude: 35.539800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Monot.',
  },
  {
    id: 'node-bei-10-2',
    name: 'Monot Sector 2 High Street',
    zone: 'Monot',
    location: { latitude: 33.942800, longitude: 35.542800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Monot.',
  },
  {
    id: 'node-bei-10-3',
    name: 'Monot Sector 3 High Street',
    zone: 'Monot',
    location: { latitude: 33.945800, longitude: 35.545800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Monot.',
  },
];

export const BEIRUT_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bei-1',
    fromNodeId: 'node-bei-1-1',
    toNodeId: 'node-bei-1-2',
    roadName: 'Hamra Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-2',
    fromNodeId: 'node-bei-1-2',
    toNodeId: 'node-bei-1-3',
    roadName: 'Hamra Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-3',
    fromNodeId: 'node-bei-2-1',
    toNodeId: 'node-bei-2-2',
    roadName: 'Achrafieh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-4',
    fromNodeId: 'node-bei-2-2',
    toNodeId: 'node-bei-2-3',
    roadName: 'Achrafieh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-5',
    fromNodeId: 'node-bei-3-1',
    toNodeId: 'node-bei-3-2',
    roadName: 'Mar Mikhaël Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-6',
    fromNodeId: 'node-bei-3-2',
    toNodeId: 'node-bei-3-3',
    roadName: 'Mar Mikhaël Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-7',
    fromNodeId: 'node-bei-4-1',
    toNodeId: 'node-bei-4-2',
    roadName: 'Gemmayzeh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-8',
    fromNodeId: 'node-bei-4-2',
    toNodeId: 'node-bei-4-3',
    roadName: 'Gemmayzeh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-9',
    fromNodeId: 'node-bei-5-1',
    toNodeId: 'node-bei-5-2',
    roadName: 'Downtown Beirut Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-10',
    fromNodeId: 'node-bei-5-2',
    toNodeId: 'node-bei-5-3',
    roadName: 'Downtown Beirut Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-11',
    fromNodeId: 'node-bei-6-1',
    toNodeId: 'node-bei-6-2',
    roadName: 'Verdun Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-12',
    fromNodeId: 'node-bei-6-2',
    toNodeId: 'node-bei-6-3',
    roadName: 'Verdun Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-13',
    fromNodeId: 'node-bei-7-1',
    toNodeId: 'node-bei-7-2',
    roadName: 'Badaro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-14',
    fromNodeId: 'node-bei-7-2',
    toNodeId: 'node-bei-7-3',
    roadName: 'Badaro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-15',
    fromNodeId: 'node-bei-8-1',
    toNodeId: 'node-bei-8-2',
    roadName: 'Raouché Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-16',
    fromNodeId: 'node-bei-8-2',
    toNodeId: 'node-bei-8-3',
    roadName: 'Raouché Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-17',
    fromNodeId: 'node-bei-9-1',
    toNodeId: 'node-bei-9-2',
    roadName: 'Zaitunay Bay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-18',
    fromNodeId: 'node-bei-9-2',
    toNodeId: 'node-bei-9-3',
    roadName: 'Zaitunay Bay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-19',
    fromNodeId: 'node-bei-10-1',
    toNodeId: 'node-bei-10-2',
    roadName: 'Monot Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bei-20',
    fromNodeId: 'node-bei-10-2',
    toNodeId: 'node-bei-10-3',
    roadName: 'Monot Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
