/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Belgrade Danube & Sava
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BELGRADE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 44.7866,
  longitude: 20.4489,
};

export const BELGRADE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bel-1-1',
    name: 'Stari Grad Sector 1 High Street',
    zone: 'Stari Grad',
    location: { latitude: 44.724600, longitude: 20.396900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Stari Grad.',
  },
  {
    id: 'node-bel-1-2',
    name: 'Stari Grad Sector 2 High Street',
    zone: 'Stari Grad',
    location: { latitude: 44.727600, longitude: 20.399900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Stari Grad.',
  },
  {
    id: 'node-bel-1-3',
    name: 'Stari Grad Sector 3 High Street',
    zone: 'Stari Grad',
    location: { latitude: 44.730600, longitude: 20.402900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Stari Grad.',
  },
  {
    id: 'node-bel-2-1',
    name: 'Vračar Sector 1 High Street',
    zone: 'Vračar',
    location: { latitude: 44.736600, longitude: 20.406900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vračar.',
  },
  {
    id: 'node-bel-2-2',
    name: 'Vračar Sector 2 High Street',
    zone: 'Vračar',
    location: { latitude: 44.739600, longitude: 20.409900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vračar.',
  },
  {
    id: 'node-bel-2-3',
    name: 'Vračar Sector 3 High Street',
    zone: 'Vračar',
    location: { latitude: 44.742600, longitude: 20.412900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vračar.',
  },
  {
    id: 'node-bel-3-1',
    name: 'Dorćol Sector 1 High Street',
    zone: 'Dorćol',
    location: { latitude: 44.748600, longitude: 20.416900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dorćol.',
  },
  {
    id: 'node-bel-3-2',
    name: 'Dorćol Sector 2 High Street',
    zone: 'Dorćol',
    location: { latitude: 44.751600, longitude: 20.419900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dorćol.',
  },
  {
    id: 'node-bel-3-3',
    name: 'Dorćol Sector 3 High Street',
    zone: 'Dorćol',
    location: { latitude: 44.754600, longitude: 20.422900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dorćol.',
  },
  {
    id: 'node-bel-4-1',
    name: 'Novi Beograd Sector 1 High Street',
    zone: 'Novi Beograd',
    location: { latitude: 44.760600, longitude: 20.426900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Novi Beograd.',
  },
  {
    id: 'node-bel-4-2',
    name: 'Novi Beograd Sector 2 High Street',
    zone: 'Novi Beograd',
    location: { latitude: 44.763600, longitude: 20.429900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Novi Beograd.',
  },
  {
    id: 'node-bel-4-3',
    name: 'Novi Beograd Sector 3 High Street',
    zone: 'Novi Beograd',
    location: { latitude: 44.766600, longitude: 20.432900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Novi Beograd.',
  },
  {
    id: 'node-bel-5-1',
    name: 'Zemun Sector 1 High Street',
    zone: 'Zemun',
    location: { latitude: 44.772600, longitude: 20.436900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zemun.',
  },
  {
    id: 'node-bel-5-2',
    name: 'Zemun Sector 2 High Street',
    zone: 'Zemun',
    location: { latitude: 44.775600, longitude: 20.439900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zemun.',
  },
  {
    id: 'node-bel-5-3',
    name: 'Zemun Sector 3 High Street',
    zone: 'Zemun',
    location: { latitude: 44.778600, longitude: 20.442900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zemun.',
  },
  {
    id: 'node-bel-6-1',
    name: 'Savski Venac Sector 1 High Street',
    zone: 'Savski Venac',
    location: { latitude: 44.784600, longitude: 20.446900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Savski Venac.',
  },
  {
    id: 'node-bel-6-2',
    name: 'Savski Venac Sector 2 High Street',
    zone: 'Savski Venac',
    location: { latitude: 44.787600, longitude: 20.449900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Savski Venac.',
  },
  {
    id: 'node-bel-6-3',
    name: 'Savski Venac Sector 3 High Street',
    zone: 'Savski Venac',
    location: { latitude: 44.790600, longitude: 20.452900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Savski Venac.',
  },
  {
    id: 'node-bel-7-1',
    name: 'Palilula Belgrade Sector 1 High Street',
    zone: 'Palilula Belgrade',
    location: { latitude: 44.796600, longitude: 20.456900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Palilula Belgrade.',
  },
  {
    id: 'node-bel-7-2',
    name: 'Palilula Belgrade Sector 2 High Street',
    zone: 'Palilula Belgrade',
    location: { latitude: 44.799600, longitude: 20.459900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Palilula Belgrade.',
  },
  {
    id: 'node-bel-7-3',
    name: 'Palilula Belgrade Sector 3 High Street',
    zone: 'Palilula Belgrade',
    location: { latitude: 44.802600, longitude: 20.462900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Palilula Belgrade.',
  },
  {
    id: 'node-bel-8-1',
    name: 'Zvezdara Sector 1 High Street',
    zone: 'Zvezdara',
    location: { latitude: 44.808600, longitude: 20.466900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zvezdara.',
  },
  {
    id: 'node-bel-8-2',
    name: 'Zvezdara Sector 2 High Street',
    zone: 'Zvezdara',
    location: { latitude: 44.811600, longitude: 20.469900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zvezdara.',
  },
  {
    id: 'node-bel-8-3',
    name: 'Zvezdara Sector 3 High Street',
    zone: 'Zvezdara',
    location: { latitude: 44.814600, longitude: 20.472900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zvezdara.',
  },
  {
    id: 'node-bel-9-1',
    name: 'Voždovac Sector 1 High Street',
    zone: 'Voždovac',
    location: { latitude: 44.820600, longitude: 20.476900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Voždovac.',
  },
  {
    id: 'node-bel-9-2',
    name: 'Voždovac Sector 2 High Street',
    zone: 'Voždovac',
    location: { latitude: 44.823600, longitude: 20.479900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Voždovac.',
  },
  {
    id: 'node-bel-9-3',
    name: 'Voždovac Sector 3 High Street',
    zone: 'Voždovac',
    location: { latitude: 44.826600, longitude: 20.482900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Voždovac.',
  },
  {
    id: 'node-bel-10-1',
    name: 'Senjak Sector 1 High Street',
    zone: 'Senjak',
    location: { latitude: 44.832600, longitude: 20.486900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Senjak.',
  },
  {
    id: 'node-bel-10-2',
    name: 'Senjak Sector 2 High Street',
    zone: 'Senjak',
    location: { latitude: 44.835600, longitude: 20.489900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Senjak.',
  },
  {
    id: 'node-bel-10-3',
    name: 'Senjak Sector 3 High Street',
    zone: 'Senjak',
    location: { latitude: 44.838600, longitude: 20.492900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Senjak.',
  },
];

export const BELGRADE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bel-1',
    fromNodeId: 'node-bel-1-1',
    toNodeId: 'node-bel-1-2',
    roadName: 'Stari Grad Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-2',
    fromNodeId: 'node-bel-1-2',
    toNodeId: 'node-bel-1-3',
    roadName: 'Stari Grad Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-3',
    fromNodeId: 'node-bel-2-1',
    toNodeId: 'node-bel-2-2',
    roadName: 'Vračar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-4',
    fromNodeId: 'node-bel-2-2',
    toNodeId: 'node-bel-2-3',
    roadName: 'Vračar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-5',
    fromNodeId: 'node-bel-3-1',
    toNodeId: 'node-bel-3-2',
    roadName: 'Dorćol Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-6',
    fromNodeId: 'node-bel-3-2',
    toNodeId: 'node-bel-3-3',
    roadName: 'Dorćol Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-7',
    fromNodeId: 'node-bel-4-1',
    toNodeId: 'node-bel-4-2',
    roadName: 'Novi Beograd Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-8',
    fromNodeId: 'node-bel-4-2',
    toNodeId: 'node-bel-4-3',
    roadName: 'Novi Beograd Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-9',
    fromNodeId: 'node-bel-5-1',
    toNodeId: 'node-bel-5-2',
    roadName: 'Zemun Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-10',
    fromNodeId: 'node-bel-5-2',
    toNodeId: 'node-bel-5-3',
    roadName: 'Zemun Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-11',
    fromNodeId: 'node-bel-6-1',
    toNodeId: 'node-bel-6-2',
    roadName: 'Savski Venac Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-12',
    fromNodeId: 'node-bel-6-2',
    toNodeId: 'node-bel-6-3',
    roadName: 'Savski Venac Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-13',
    fromNodeId: 'node-bel-7-1',
    toNodeId: 'node-bel-7-2',
    roadName: 'Palilula Belgrade Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-14',
    fromNodeId: 'node-bel-7-2',
    toNodeId: 'node-bel-7-3',
    roadName: 'Palilula Belgrade Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-15',
    fromNodeId: 'node-bel-8-1',
    toNodeId: 'node-bel-8-2',
    roadName: 'Zvezdara Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-16',
    fromNodeId: 'node-bel-8-2',
    toNodeId: 'node-bel-8-3',
    roadName: 'Zvezdara Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-17',
    fromNodeId: 'node-bel-9-1',
    toNodeId: 'node-bel-9-2',
    roadName: 'Voždovac Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-18',
    fromNodeId: 'node-bel-9-2',
    toNodeId: 'node-bel-9-3',
    roadName: 'Voždovac Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-19',
    fromNodeId: 'node-bel-10-1',
    toNodeId: 'node-bel-10-2',
    roadName: 'Senjak Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bel-20',
    fromNodeId: 'node-bel-10-2',
    toNodeId: 'node-bel-10-3',
    roadName: 'Senjak Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
