/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Berlin Central Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BERLIN_BASE_COORDINATE: GeoCoordinate = {
  latitude: 52.52,
  longitude: 13.405,
};

export const BERLIN_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ber-1-1',
    name: 'Mitte Sector 1 High Street',
    zone: 'Mitte',
    location: { latitude: 52.458000, longitude: 13.353000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mitte.',
  },
  {
    id: 'node-ber-1-2',
    name: 'Mitte Sector 2 High Street',
    zone: 'Mitte',
    location: { latitude: 52.461000, longitude: 13.356000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mitte.',
  },
  {
    id: 'node-ber-1-3',
    name: 'Mitte Sector 3 High Street',
    zone: 'Mitte',
    location: { latitude: 52.464000, longitude: 13.359000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mitte.',
  },
  {
    id: 'node-ber-2-1',
    name: 'Kreuzberg Sector 1 High Street',
    zone: 'Kreuzberg',
    location: { latitude: 52.470000, longitude: 13.363000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kreuzberg.',
  },
  {
    id: 'node-ber-2-2',
    name: 'Kreuzberg Sector 2 High Street',
    zone: 'Kreuzberg',
    location: { latitude: 52.473000, longitude: 13.366000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kreuzberg.',
  },
  {
    id: 'node-ber-2-3',
    name: 'Kreuzberg Sector 3 High Street',
    zone: 'Kreuzberg',
    location: { latitude: 52.476000, longitude: 13.369000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kreuzberg.',
  },
  {
    id: 'node-ber-3-1',
    name: 'Prenzlauer Berg Sector 1 High Street',
    zone: 'Prenzlauer Berg',
    location: { latitude: 52.482000, longitude: 13.373000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Prenzlauer Berg.',
  },
  {
    id: 'node-ber-3-2',
    name: 'Prenzlauer Berg Sector 2 High Street',
    zone: 'Prenzlauer Berg',
    location: { latitude: 52.485000, longitude: 13.376000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Prenzlauer Berg.',
  },
  {
    id: 'node-ber-3-3',
    name: 'Prenzlauer Berg Sector 3 High Street',
    zone: 'Prenzlauer Berg',
    location: { latitude: 52.488000, longitude: 13.379000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Prenzlauer Berg.',
  },
  {
    id: 'node-ber-4-1',
    name: 'Friedrichshain Sector 1 High Street',
    zone: 'Friedrichshain',
    location: { latitude: 52.494000, longitude: 13.383000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Friedrichshain.',
  },
  {
    id: 'node-ber-4-2',
    name: 'Friedrichshain Sector 2 High Street',
    zone: 'Friedrichshain',
    location: { latitude: 52.497000, longitude: 13.386000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Friedrichshain.',
  },
  {
    id: 'node-ber-4-3',
    name: 'Friedrichshain Sector 3 High Street',
    zone: 'Friedrichshain',
    location: { latitude: 52.500000, longitude: 13.389000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Friedrichshain.',
  },
  {
    id: 'node-ber-5-1',
    name: 'Neukölln Sector 1 High Street',
    zone: 'Neukölln',
    location: { latitude: 52.506000, longitude: 13.393000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Neukölln.',
  },
  {
    id: 'node-ber-5-2',
    name: 'Neukölln Sector 2 High Street',
    zone: 'Neukölln',
    location: { latitude: 52.509000, longitude: 13.396000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Neukölln.',
  },
  {
    id: 'node-ber-5-3',
    name: 'Neukölln Sector 3 High Street',
    zone: 'Neukölln',
    location: { latitude: 52.512000, longitude: 13.399000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Neukölln.',
  },
  {
    id: 'node-ber-6-1',
    name: 'Charlottenburg Sector 1 High Street',
    zone: 'Charlottenburg',
    location: { latitude: 52.518000, longitude: 13.403000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Charlottenburg.',
  },
  {
    id: 'node-ber-6-2',
    name: 'Charlottenburg Sector 2 High Street',
    zone: 'Charlottenburg',
    location: { latitude: 52.521000, longitude: 13.406000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Charlottenburg.',
  },
  {
    id: 'node-ber-6-3',
    name: 'Charlottenburg Sector 3 High Street',
    zone: 'Charlottenburg',
    location: { latitude: 52.524000, longitude: 13.409000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Charlottenburg.',
  },
  {
    id: 'node-ber-7-1',
    name: 'Schöneberg Sector 1 High Street',
    zone: 'Schöneberg',
    location: { latitude: 52.530000, longitude: 13.413000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Schöneberg.',
  },
  {
    id: 'node-ber-7-2',
    name: 'Schöneberg Sector 2 High Street',
    zone: 'Schöneberg',
    location: { latitude: 52.533000, longitude: 13.416000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Schöneberg.',
  },
  {
    id: 'node-ber-7-3',
    name: 'Schöneberg Sector 3 High Street',
    zone: 'Schöneberg',
    location: { latitude: 52.536000, longitude: 13.419000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Schöneberg.',
  },
  {
    id: 'node-ber-8-1',
    name: 'Moabit Sector 1 High Street',
    zone: 'Moabit',
    location: { latitude: 52.542000, longitude: 13.423000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Moabit.',
  },
  {
    id: 'node-ber-8-2',
    name: 'Moabit Sector 2 High Street',
    zone: 'Moabit',
    location: { latitude: 52.545000, longitude: 13.426000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Moabit.',
  },
  {
    id: 'node-ber-8-3',
    name: 'Moabit Sector 3 High Street',
    zone: 'Moabit',
    location: { latitude: 52.548000, longitude: 13.429000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Moabit.',
  },
  {
    id: 'node-ber-9-1',
    name: 'Wedding Sector 1 High Street',
    zone: 'Wedding',
    location: { latitude: 52.554000, longitude: 13.433000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wedding.',
  },
  {
    id: 'node-ber-9-2',
    name: 'Wedding Sector 2 High Street',
    zone: 'Wedding',
    location: { latitude: 52.557000, longitude: 13.436000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wedding.',
  },
  {
    id: 'node-ber-9-3',
    name: 'Wedding Sector 3 High Street',
    zone: 'Wedding',
    location: { latitude: 52.560000, longitude: 13.439000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wedding.',
  },
  {
    id: 'node-ber-10-1',
    name: 'Tempelhof Sector 1 High Street',
    zone: 'Tempelhof',
    location: { latitude: 52.566000, longitude: 13.443000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tempelhof.',
  },
  {
    id: 'node-ber-10-2',
    name: 'Tempelhof Sector 2 High Street',
    zone: 'Tempelhof',
    location: { latitude: 52.569000, longitude: 13.446000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tempelhof.',
  },
  {
    id: 'node-ber-10-3',
    name: 'Tempelhof Sector 3 High Street',
    zone: 'Tempelhof',
    location: { latitude: 52.572000, longitude: 13.449000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tempelhof.',
  },
];

export const BERLIN_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ber-1',
    fromNodeId: 'node-ber-1-1',
    toNodeId: 'node-ber-1-2',
    roadName: 'Mitte Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-2',
    fromNodeId: 'node-ber-1-2',
    toNodeId: 'node-ber-1-3',
    roadName: 'Mitte Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-3',
    fromNodeId: 'node-ber-2-1',
    toNodeId: 'node-ber-2-2',
    roadName: 'Kreuzberg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-4',
    fromNodeId: 'node-ber-2-2',
    toNodeId: 'node-ber-2-3',
    roadName: 'Kreuzberg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-5',
    fromNodeId: 'node-ber-3-1',
    toNodeId: 'node-ber-3-2',
    roadName: 'Prenzlauer Berg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-6',
    fromNodeId: 'node-ber-3-2',
    toNodeId: 'node-ber-3-3',
    roadName: 'Prenzlauer Berg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-7',
    fromNodeId: 'node-ber-4-1',
    toNodeId: 'node-ber-4-2',
    roadName: 'Friedrichshain Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-8',
    fromNodeId: 'node-ber-4-2',
    toNodeId: 'node-ber-4-3',
    roadName: 'Friedrichshain Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-9',
    fromNodeId: 'node-ber-5-1',
    toNodeId: 'node-ber-5-2',
    roadName: 'Neukölln Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-10',
    fromNodeId: 'node-ber-5-2',
    toNodeId: 'node-ber-5-3',
    roadName: 'Neukölln Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-11',
    fromNodeId: 'node-ber-6-1',
    toNodeId: 'node-ber-6-2',
    roadName: 'Charlottenburg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-12',
    fromNodeId: 'node-ber-6-2',
    toNodeId: 'node-ber-6-3',
    roadName: 'Charlottenburg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-13',
    fromNodeId: 'node-ber-7-1',
    toNodeId: 'node-ber-7-2',
    roadName: 'Schöneberg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-14',
    fromNodeId: 'node-ber-7-2',
    toNodeId: 'node-ber-7-3',
    roadName: 'Schöneberg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-15',
    fromNodeId: 'node-ber-8-1',
    toNodeId: 'node-ber-8-2',
    roadName: 'Moabit Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-16',
    fromNodeId: 'node-ber-8-2',
    toNodeId: 'node-ber-8-3',
    roadName: 'Moabit Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-17',
    fromNodeId: 'node-ber-9-1',
    toNodeId: 'node-ber-9-2',
    roadName: 'Wedding Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-18',
    fromNodeId: 'node-ber-9-2',
    toNodeId: 'node-ber-9-3',
    roadName: 'Wedding Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-19',
    fromNodeId: 'node-ber-10-1',
    toNodeId: 'node-ber-10-2',
    roadName: 'Tempelhof Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ber-20',
    fromNodeId: 'node-ber-10-2',
    toNodeId: 'node-ber-10-3',
    roadName: 'Tempelhof Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
