/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Bhopal Lake City Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BHOPAL_BASE_COORDINATE: GeoCoordinate = {
  latitude: 23.2599,
  longitude: 77.4126,
};

export const BHOPAL_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bho-1-1',
    name: 'MP Nagar Sector 1 High Street',
    zone: 'MP Nagar',
    location: { latitude: 23.197900, longitude: 77.360600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in MP Nagar.',
  },
  {
    id: 'node-bho-1-2',
    name: 'MP Nagar Sector 2 High Street',
    zone: 'MP Nagar',
    location: { latitude: 23.200900, longitude: 77.363600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in MP Nagar.',
  },
  {
    id: 'node-bho-1-3',
    name: 'MP Nagar Sector 3 High Street',
    zone: 'MP Nagar',
    location: { latitude: 23.203900, longitude: 77.366600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in MP Nagar.',
  },
  {
    id: 'node-bho-2-1',
    name: 'Arera Colony Sector 1 High Street',
    zone: 'Arera Colony',
    location: { latitude: 23.209900, longitude: 77.370600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Arera Colony.',
  },
  {
    id: 'node-bho-2-2',
    name: 'Arera Colony Sector 2 High Street',
    zone: 'Arera Colony',
    location: { latitude: 23.212900, longitude: 77.373600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Arera Colony.',
  },
  {
    id: 'node-bho-2-3',
    name: 'Arera Colony Sector 3 High Street',
    zone: 'Arera Colony',
    location: { latitude: 23.215900, longitude: 77.376600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Arera Colony.',
  },
  {
    id: 'node-bho-3-1',
    name: 'Shahpura Sector 1 High Street',
    zone: 'Shahpura',
    location: { latitude: 23.221900, longitude: 77.380600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shahpura.',
  },
  {
    id: 'node-bho-3-2',
    name: 'Shahpura Sector 2 High Street',
    zone: 'Shahpura',
    location: { latitude: 23.224900, longitude: 77.383600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shahpura.',
  },
  {
    id: 'node-bho-3-3',
    name: 'Shahpura Sector 3 High Street',
    zone: 'Shahpura',
    location: { latitude: 23.227900, longitude: 77.386600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shahpura.',
  },
  {
    id: 'node-bho-4-1',
    name: 'Kolar Road Sector 1 High Street',
    zone: 'Kolar Road',
    location: { latitude: 23.233900, longitude: 77.390600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kolar Road.',
  },
  {
    id: 'node-bho-4-2',
    name: 'Kolar Road Sector 2 High Street',
    zone: 'Kolar Road',
    location: { latitude: 23.236900, longitude: 77.393600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kolar Road.',
  },
  {
    id: 'node-bho-4-3',
    name: 'Kolar Road Sector 3 High Street',
    zone: 'Kolar Road',
    location: { latitude: 23.239900, longitude: 77.396600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kolar Road.',
  },
  {
    id: 'node-bho-5-1',
    name: 'New Market Sector 1 High Street',
    zone: 'New Market',
    location: { latitude: 23.245900, longitude: 77.400600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in New Market.',
  },
  {
    id: 'node-bho-5-2',
    name: 'New Market Sector 2 High Street',
    zone: 'New Market',
    location: { latitude: 23.248900, longitude: 77.403600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in New Market.',
  },
  {
    id: 'node-bho-5-3',
    name: 'New Market Sector 3 High Street',
    zone: 'New Market',
    location: { latitude: 23.251900, longitude: 77.406600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in New Market.',
  },
  {
    id: 'node-bho-6-1',
    name: 'Gulmohar Sector 1 High Street',
    zone: 'Gulmohar',
    location: { latitude: 23.257900, longitude: 77.410600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gulmohar.',
  },
  {
    id: 'node-bho-6-2',
    name: 'Gulmohar Sector 2 High Street',
    zone: 'Gulmohar',
    location: { latitude: 23.260900, longitude: 77.413600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gulmohar.',
  },
  {
    id: 'node-bho-6-3',
    name: 'Gulmohar Sector 3 High Street',
    zone: 'Gulmohar',
    location: { latitude: 23.263900, longitude: 77.416600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gulmohar.',
  },
  {
    id: 'node-bho-7-1',
    name: 'Hoshangabad Road Sector 1 High Street',
    zone: 'Hoshangabad Road',
    location: { latitude: 23.269900, longitude: 77.420600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hoshangabad Road.',
  },
  {
    id: 'node-bho-7-2',
    name: 'Hoshangabad Road Sector 2 High Street',
    zone: 'Hoshangabad Road',
    location: { latitude: 23.272900, longitude: 77.423600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hoshangabad Road.',
  },
  {
    id: 'node-bho-7-3',
    name: 'Hoshangabad Road Sector 3 High Street',
    zone: 'Hoshangabad Road',
    location: { latitude: 23.275900, longitude: 77.426600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hoshangabad Road.',
  },
  {
    id: 'node-bho-8-1',
    name: 'Bittan Market Sector 1 High Street',
    zone: 'Bittan Market',
    location: { latitude: 23.281900, longitude: 77.430600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bittan Market.',
  },
  {
    id: 'node-bho-8-2',
    name: 'Bittan Market Sector 2 High Street',
    zone: 'Bittan Market',
    location: { latitude: 23.284900, longitude: 77.433600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bittan Market.',
  },
  {
    id: 'node-bho-8-3',
    name: 'Bittan Market Sector 3 High Street',
    zone: 'Bittan Market',
    location: { latitude: 23.287900, longitude: 77.436600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bittan Market.',
  },
  {
    id: 'node-bho-9-1',
    name: 'Bairagarh Sector 1 High Street',
    zone: 'Bairagarh',
    location: { latitude: 23.293900, longitude: 77.440600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bairagarh.',
  },
  {
    id: 'node-bho-9-2',
    name: 'Bairagarh Sector 2 High Street',
    zone: 'Bairagarh',
    location: { latitude: 23.296900, longitude: 77.443600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bairagarh.',
  },
  {
    id: 'node-bho-9-3',
    name: 'Bairagarh Sector 3 High Street',
    zone: 'Bairagarh',
    location: { latitude: 23.299900, longitude: 77.446600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bairagarh.',
  },
  {
    id: 'node-bho-10-1',
    name: 'Ayodhya Bypass Sector 1 High Street',
    zone: 'Ayodhya Bypass',
    location: { latitude: 23.305900, longitude: 77.450600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ayodhya Bypass.',
  },
  {
    id: 'node-bho-10-2',
    name: 'Ayodhya Bypass Sector 2 High Street',
    zone: 'Ayodhya Bypass',
    location: { latitude: 23.308900, longitude: 77.453600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ayodhya Bypass.',
  },
  {
    id: 'node-bho-10-3',
    name: 'Ayodhya Bypass Sector 3 High Street',
    zone: 'Ayodhya Bypass',
    location: { latitude: 23.311900, longitude: 77.456600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ayodhya Bypass.',
  },
];

export const BHOPAL_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bho-1',
    fromNodeId: 'node-bho-1-1',
    toNodeId: 'node-bho-1-2',
    roadName: 'MP Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-2',
    fromNodeId: 'node-bho-1-2',
    toNodeId: 'node-bho-1-3',
    roadName: 'MP Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-3',
    fromNodeId: 'node-bho-2-1',
    toNodeId: 'node-bho-2-2',
    roadName: 'Arera Colony Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-4',
    fromNodeId: 'node-bho-2-2',
    toNodeId: 'node-bho-2-3',
    roadName: 'Arera Colony Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-5',
    fromNodeId: 'node-bho-3-1',
    toNodeId: 'node-bho-3-2',
    roadName: 'Shahpura Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-6',
    fromNodeId: 'node-bho-3-2',
    toNodeId: 'node-bho-3-3',
    roadName: 'Shahpura Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-7',
    fromNodeId: 'node-bho-4-1',
    toNodeId: 'node-bho-4-2',
    roadName: 'Kolar Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-8',
    fromNodeId: 'node-bho-4-2',
    toNodeId: 'node-bho-4-3',
    roadName: 'Kolar Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-9',
    fromNodeId: 'node-bho-5-1',
    toNodeId: 'node-bho-5-2',
    roadName: 'New Market Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-10',
    fromNodeId: 'node-bho-5-2',
    toNodeId: 'node-bho-5-3',
    roadName: 'New Market Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-11',
    fromNodeId: 'node-bho-6-1',
    toNodeId: 'node-bho-6-2',
    roadName: 'Gulmohar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-12',
    fromNodeId: 'node-bho-6-2',
    toNodeId: 'node-bho-6-3',
    roadName: 'Gulmohar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-13',
    fromNodeId: 'node-bho-7-1',
    toNodeId: 'node-bho-7-2',
    roadName: 'Hoshangabad Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-14',
    fromNodeId: 'node-bho-7-2',
    toNodeId: 'node-bho-7-3',
    roadName: 'Hoshangabad Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-15',
    fromNodeId: 'node-bho-8-1',
    toNodeId: 'node-bho-8-2',
    roadName: 'Bittan Market Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-16',
    fromNodeId: 'node-bho-8-2',
    toNodeId: 'node-bho-8-3',
    roadName: 'Bittan Market Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-17',
    fromNodeId: 'node-bho-9-1',
    toNodeId: 'node-bho-9-2',
    roadName: 'Bairagarh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-18',
    fromNodeId: 'node-bho-9-2',
    toNodeId: 'node-bho-9-3',
    roadName: 'Bairagarh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-19',
    fromNodeId: 'node-bho-10-1',
    toNodeId: 'node-bho-10-2',
    roadName: 'Ayodhya Bypass Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bho-20',
    fromNodeId: 'node-bho-10-2',
    toNodeId: 'node-bho-10-3',
    roadName: 'Ayodhya Bypass Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
