/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Bhubaneswar Smart Capital Zone
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BHUBANESWAR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 20.2961,
  longitude: 85.8245,
};

export const BHUBANESWAR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bhu-1-1',
    name: 'Saheed Nagar Sector 1 High Street',
    zone: 'Saheed Nagar',
    location: { latitude: 20.234100, longitude: 85.772500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Saheed Nagar.',
  },
  {
    id: 'node-bhu-1-2',
    name: 'Saheed Nagar Sector 2 High Street',
    zone: 'Saheed Nagar',
    location: { latitude: 20.237100, longitude: 85.775500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Saheed Nagar.',
  },
  {
    id: 'node-bhu-1-3',
    name: 'Saheed Nagar Sector 3 High Street',
    zone: 'Saheed Nagar',
    location: { latitude: 20.240100, longitude: 85.778500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Saheed Nagar.',
  },
  {
    id: 'node-bhu-2-1',
    name: 'Jayadev Vihar Sector 1 High Street',
    zone: 'Jayadev Vihar',
    location: { latitude: 20.246100, longitude: 85.782500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jayadev Vihar.',
  },
  {
    id: 'node-bhu-2-2',
    name: 'Jayadev Vihar Sector 2 High Street',
    zone: 'Jayadev Vihar',
    location: { latitude: 20.249100, longitude: 85.785500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jayadev Vihar.',
  },
  {
    id: 'node-bhu-2-3',
    name: 'Jayadev Vihar Sector 3 High Street',
    zone: 'Jayadev Vihar',
    location: { latitude: 20.252100, longitude: 85.788500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jayadev Vihar.',
  },
  {
    id: 'node-bhu-3-1',
    name: 'Patia Tech Zone Sector 1 High Street',
    zone: 'Patia Tech Zone',
    location: { latitude: 20.258100, longitude: 85.792500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Patia Tech Zone.',
  },
  {
    id: 'node-bhu-3-2',
    name: 'Patia Tech Zone Sector 2 High Street',
    zone: 'Patia Tech Zone',
    location: { latitude: 20.261100, longitude: 85.795500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Patia Tech Zone.',
  },
  {
    id: 'node-bhu-3-3',
    name: 'Patia Tech Zone Sector 3 High Street',
    zone: 'Patia Tech Zone',
    location: { latitude: 20.264100, longitude: 85.798500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Patia Tech Zone.',
  },
  {
    id: 'node-bhu-4-1',
    name: 'Nayapalli Sector 1 High Street',
    zone: 'Nayapalli',
    location: { latitude: 20.270100, longitude: 85.802500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nayapalli.',
  },
  {
    id: 'node-bhu-4-2',
    name: 'Nayapalli Sector 2 High Street',
    zone: 'Nayapalli',
    location: { latitude: 20.273100, longitude: 85.805500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nayapalli.',
  },
  {
    id: 'node-bhu-4-3',
    name: 'Nayapalli Sector 3 High Street',
    zone: 'Nayapalli',
    location: { latitude: 20.276100, longitude: 85.808500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nayapalli.',
  },
  {
    id: 'node-bhu-5-1',
    name: 'Khandagiri Sector 1 High Street',
    zone: 'Khandagiri',
    location: { latitude: 20.282100, longitude: 85.812500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Khandagiri.',
  },
  {
    id: 'node-bhu-5-2',
    name: 'Khandagiri Sector 2 High Street',
    zone: 'Khandagiri',
    location: { latitude: 20.285100, longitude: 85.815500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Khandagiri.',
  },
  {
    id: 'node-bhu-5-3',
    name: 'Khandagiri Sector 3 High Street',
    zone: 'Khandagiri',
    location: { latitude: 20.288100, longitude: 85.818500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Khandagiri.',
  },
  {
    id: 'node-bhu-6-1',
    name: 'Chandrasekharpur Sector 1 High Street',
    zone: 'Chandrasekharpur',
    location: { latitude: 20.294100, longitude: 85.822500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chandrasekharpur.',
  },
  {
    id: 'node-bhu-6-2',
    name: 'Chandrasekharpur Sector 2 High Street',
    zone: 'Chandrasekharpur',
    location: { latitude: 20.297100, longitude: 85.825500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chandrasekharpur.',
  },
  {
    id: 'node-bhu-6-3',
    name: 'Chandrasekharpur Sector 3 High Street',
    zone: 'Chandrasekharpur',
    location: { latitude: 20.300100, longitude: 85.828500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chandrasekharpur.',
  },
  {
    id: 'node-bhu-7-1',
    name: 'Master Canteen Sector 1 High Street',
    zone: 'Master Canteen',
    location: { latitude: 20.306100, longitude: 85.832500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Master Canteen.',
  },
  {
    id: 'node-bhu-7-2',
    name: 'Master Canteen Sector 2 High Street',
    zone: 'Master Canteen',
    location: { latitude: 20.309100, longitude: 85.835500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Master Canteen.',
  },
  {
    id: 'node-bhu-7-3',
    name: 'Master Canteen Sector 3 High Street',
    zone: 'Master Canteen',
    location: { latitude: 20.312100, longitude: 85.838500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Master Canteen.',
  },
  {
    id: 'node-bhu-8-1',
    name: 'KIIT Square Sector 1 High Street',
    zone: 'KIIT Square',
    location: { latitude: 20.318100, longitude: 85.842500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in KIIT Square.',
  },
  {
    id: 'node-bhu-8-2',
    name: 'KIIT Square Sector 2 High Street',
    zone: 'KIIT Square',
    location: { latitude: 20.321100, longitude: 85.845500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in KIIT Square.',
  },
  {
    id: 'node-bhu-8-3',
    name: 'KIIT Square Sector 3 High Street',
    zone: 'KIIT Square',
    location: { latitude: 20.324100, longitude: 85.848500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in KIIT Square.',
  },
  {
    id: 'node-bhu-9-1',
    name: 'Old Town Sector 1 High Street',
    zone: 'Old Town',
    location: { latitude: 20.330100, longitude: 85.852500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old Town.',
  },
  {
    id: 'node-bhu-9-2',
    name: 'Old Town Sector 2 High Street',
    zone: 'Old Town',
    location: { latitude: 20.333100, longitude: 85.855500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old Town.',
  },
  {
    id: 'node-bhu-9-3',
    name: 'Old Town Sector 3 High Street',
    zone: 'Old Town',
    location: { latitude: 20.336100, longitude: 85.858500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old Town.',
  },
  {
    id: 'node-bhu-10-1',
    name: 'Infocity Sector 1 High Street',
    zone: 'Infocity',
    location: { latitude: 20.342100, longitude: 85.862500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Infocity.',
  },
  {
    id: 'node-bhu-10-2',
    name: 'Infocity Sector 2 High Street',
    zone: 'Infocity',
    location: { latitude: 20.345100, longitude: 85.865500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Infocity.',
  },
  {
    id: 'node-bhu-10-3',
    name: 'Infocity Sector 3 High Street',
    zone: 'Infocity',
    location: { latitude: 20.348100, longitude: 85.868500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Infocity.',
  },
];

export const BHUBANESWAR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bhu-1',
    fromNodeId: 'node-bhu-1-1',
    toNodeId: 'node-bhu-1-2',
    roadName: 'Saheed Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-2',
    fromNodeId: 'node-bhu-1-2',
    toNodeId: 'node-bhu-1-3',
    roadName: 'Saheed Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-3',
    fromNodeId: 'node-bhu-2-1',
    toNodeId: 'node-bhu-2-2',
    roadName: 'Jayadev Vihar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-4',
    fromNodeId: 'node-bhu-2-2',
    toNodeId: 'node-bhu-2-3',
    roadName: 'Jayadev Vihar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-5',
    fromNodeId: 'node-bhu-3-1',
    toNodeId: 'node-bhu-3-2',
    roadName: 'Patia Tech Zone Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-6',
    fromNodeId: 'node-bhu-3-2',
    toNodeId: 'node-bhu-3-3',
    roadName: 'Patia Tech Zone Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-7',
    fromNodeId: 'node-bhu-4-1',
    toNodeId: 'node-bhu-4-2',
    roadName: 'Nayapalli Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-8',
    fromNodeId: 'node-bhu-4-2',
    toNodeId: 'node-bhu-4-3',
    roadName: 'Nayapalli Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-9',
    fromNodeId: 'node-bhu-5-1',
    toNodeId: 'node-bhu-5-2',
    roadName: 'Khandagiri Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-10',
    fromNodeId: 'node-bhu-5-2',
    toNodeId: 'node-bhu-5-3',
    roadName: 'Khandagiri Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-11',
    fromNodeId: 'node-bhu-6-1',
    toNodeId: 'node-bhu-6-2',
    roadName: 'Chandrasekharpur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-12',
    fromNodeId: 'node-bhu-6-2',
    toNodeId: 'node-bhu-6-3',
    roadName: 'Chandrasekharpur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-13',
    fromNodeId: 'node-bhu-7-1',
    toNodeId: 'node-bhu-7-2',
    roadName: 'Master Canteen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-14',
    fromNodeId: 'node-bhu-7-2',
    toNodeId: 'node-bhu-7-3',
    roadName: 'Master Canteen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-15',
    fromNodeId: 'node-bhu-8-1',
    toNodeId: 'node-bhu-8-2',
    roadName: 'KIIT Square Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-16',
    fromNodeId: 'node-bhu-8-2',
    toNodeId: 'node-bhu-8-3',
    roadName: 'KIIT Square Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-17',
    fromNodeId: 'node-bhu-9-1',
    toNodeId: 'node-bhu-9-2',
    roadName: 'Old Town Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-18',
    fromNodeId: 'node-bhu-9-2',
    toNodeId: 'node-bhu-9-3',
    roadName: 'Old Town Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-19',
    fromNodeId: 'node-bhu-10-1',
    toNodeId: 'node-bhu-10-2',
    roadName: 'Infocity Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bhu-20',
    fromNodeId: 'node-bhu-10-2',
    toNodeId: 'node-bhu-10-3',
    roadName: 'Infocity Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
