/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Birmingham West Midlands
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BIRMINGHAM_BASE_COORDINATE: GeoCoordinate = {
  latitude: 52.4862,
  longitude: -1.8904,
};

export const BIRMINGHAM_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bir-1-1',
    name: 'City Centre Birmingham Sector 1 High Street',
    zone: 'City Centre Birmingham',
    location: { latitude: 52.424200, longitude: -1.942400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in City Centre Birmingham.',
  },
  {
    id: 'node-bir-1-2',
    name: 'City Centre Birmingham Sector 2 High Street',
    zone: 'City Centre Birmingham',
    location: { latitude: 52.427200, longitude: -1.939400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in City Centre Birmingham.',
  },
  {
    id: 'node-bir-1-3',
    name: 'City Centre Birmingham Sector 3 High Street',
    zone: 'City Centre Birmingham',
    location: { latitude: 52.430200, longitude: -1.936400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in City Centre Birmingham.',
  },
  {
    id: 'node-bir-2-1',
    name: 'Jewellery Quarter Sector 1 High Street',
    zone: 'Jewellery Quarter',
    location: { latitude: 52.436200, longitude: -1.932400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jewellery Quarter.',
  },
  {
    id: 'node-bir-2-2',
    name: 'Jewellery Quarter Sector 2 High Street',
    zone: 'Jewellery Quarter',
    location: { latitude: 52.439200, longitude: -1.929400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jewellery Quarter.',
  },
  {
    id: 'node-bir-2-3',
    name: 'Jewellery Quarter Sector 3 High Street',
    zone: 'Jewellery Quarter',
    location: { latitude: 52.442200, longitude: -1.926400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jewellery Quarter.',
  },
  {
    id: 'node-bir-3-1',
    name: 'Digbeth Sector 1 High Street',
    zone: 'Digbeth',
    location: { latitude: 52.448200, longitude: -1.922400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Digbeth.',
  },
  {
    id: 'node-bir-3-2',
    name: 'Digbeth Sector 2 High Street',
    zone: 'Digbeth',
    location: { latitude: 52.451200, longitude: -1.919400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Digbeth.',
  },
  {
    id: 'node-bir-3-3',
    name: 'Digbeth Sector 3 High Street',
    zone: 'Digbeth',
    location: { latitude: 52.454200, longitude: -1.916400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Digbeth.',
  },
  {
    id: 'node-bir-4-1',
    name: 'Edgbaston Sector 1 High Street',
    zone: 'Edgbaston',
    location: { latitude: 52.460200, longitude: -1.912400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Edgbaston.',
  },
  {
    id: 'node-bir-4-2',
    name: 'Edgbaston Sector 2 High Street',
    zone: 'Edgbaston',
    location: { latitude: 52.463200, longitude: -1.909400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Edgbaston.',
  },
  {
    id: 'node-bir-4-3',
    name: 'Edgbaston Sector 3 High Street',
    zone: 'Edgbaston',
    location: { latitude: 52.466200, longitude: -1.906400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Edgbaston.',
  },
  {
    id: 'node-bir-5-1',
    name: 'Moseley Sector 1 High Street',
    zone: 'Moseley',
    location: { latitude: 52.472200, longitude: -1.902400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Moseley.',
  },
  {
    id: 'node-bir-5-2',
    name: 'Moseley Sector 2 High Street',
    zone: 'Moseley',
    location: { latitude: 52.475200, longitude: -1.899400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Moseley.',
  },
  {
    id: 'node-bir-5-3',
    name: 'Moseley Sector 3 High Street',
    zone: 'Moseley',
    location: { latitude: 52.478200, longitude: -1.896400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Moseley.',
  },
  {
    id: 'node-bir-6-1',
    name: 'Harborne Sector 1 High Street',
    zone: 'Harborne',
    location: { latitude: 52.484200, longitude: -1.892400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Harborne.',
  },
  {
    id: 'node-bir-6-2',
    name: 'Harborne Sector 2 High Street',
    zone: 'Harborne',
    location: { latitude: 52.487200, longitude: -1.889400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Harborne.',
  },
  {
    id: 'node-bir-6-3',
    name: 'Harborne Sector 3 High Street',
    zone: 'Harborne',
    location: { latitude: 52.490200, longitude: -1.886400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Harborne.',
  },
  {
    id: 'node-bir-7-1',
    name: 'Colmore Row Sector 1 High Street',
    zone: 'Colmore Row',
    location: { latitude: 52.496200, longitude: -1.882400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Colmore Row.',
  },
  {
    id: 'node-bir-7-2',
    name: 'Colmore Row Sector 2 High Street',
    zone: 'Colmore Row',
    location: { latitude: 52.499200, longitude: -1.879400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Colmore Row.',
  },
  {
    id: 'node-bir-7-3',
    name: 'Colmore Row Sector 3 High Street',
    zone: 'Colmore Row',
    location: { latitude: 52.502200, longitude: -1.876400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Colmore Row.',
  },
  {
    id: 'node-bir-8-1',
    name: 'Mailbox Sector 1 High Street',
    zone: 'Mailbox',
    location: { latitude: 52.508200, longitude: -1.872400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mailbox.',
  },
  {
    id: 'node-bir-8-2',
    name: 'Mailbox Sector 2 High Street',
    zone: 'Mailbox',
    location: { latitude: 52.511200, longitude: -1.869400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mailbox.',
  },
  {
    id: 'node-bir-8-3',
    name: 'Mailbox Sector 3 High Street',
    zone: 'Mailbox',
    location: { latitude: 52.514200, longitude: -1.866400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mailbox.',
  },
  {
    id: 'node-bir-9-1',
    name: 'Selly Oak Sector 1 High Street',
    zone: 'Selly Oak',
    location: { latitude: 52.520200, longitude: -1.862400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Selly Oak.',
  },
  {
    id: 'node-bir-9-2',
    name: 'Selly Oak Sector 2 High Street',
    zone: 'Selly Oak',
    location: { latitude: 52.523200, longitude: -1.859400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Selly Oak.',
  },
  {
    id: 'node-bir-9-3',
    name: 'Selly Oak Sector 3 High Street',
    zone: 'Selly Oak',
    location: { latitude: 52.526200, longitude: -1.856400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Selly Oak.',
  },
  {
    id: 'node-bir-10-1',
    name: 'Kings Heath Sector 1 High Street',
    zone: 'Kings Heath',
    location: { latitude: 52.532200, longitude: -1.852400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kings Heath.',
  },
  {
    id: 'node-bir-10-2',
    name: 'Kings Heath Sector 2 High Street',
    zone: 'Kings Heath',
    location: { latitude: 52.535200, longitude: -1.849400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kings Heath.',
  },
  {
    id: 'node-bir-10-3',
    name: 'Kings Heath Sector 3 High Street',
    zone: 'Kings Heath',
    location: { latitude: 52.538200, longitude: -1.846400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kings Heath.',
  },
];

export const BIRMINGHAM_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bir-1',
    fromNodeId: 'node-bir-1-1',
    toNodeId: 'node-bir-1-2',
    roadName: 'City Centre Birmingham Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-2',
    fromNodeId: 'node-bir-1-2',
    toNodeId: 'node-bir-1-3',
    roadName: 'City Centre Birmingham Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-3',
    fromNodeId: 'node-bir-2-1',
    toNodeId: 'node-bir-2-2',
    roadName: 'Jewellery Quarter Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-4',
    fromNodeId: 'node-bir-2-2',
    toNodeId: 'node-bir-2-3',
    roadName: 'Jewellery Quarter Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-5',
    fromNodeId: 'node-bir-3-1',
    toNodeId: 'node-bir-3-2',
    roadName: 'Digbeth Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-6',
    fromNodeId: 'node-bir-3-2',
    toNodeId: 'node-bir-3-3',
    roadName: 'Digbeth Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-7',
    fromNodeId: 'node-bir-4-1',
    toNodeId: 'node-bir-4-2',
    roadName: 'Edgbaston Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-8',
    fromNodeId: 'node-bir-4-2',
    toNodeId: 'node-bir-4-3',
    roadName: 'Edgbaston Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-9',
    fromNodeId: 'node-bir-5-1',
    toNodeId: 'node-bir-5-2',
    roadName: 'Moseley Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-10',
    fromNodeId: 'node-bir-5-2',
    toNodeId: 'node-bir-5-3',
    roadName: 'Moseley Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-11',
    fromNodeId: 'node-bir-6-1',
    toNodeId: 'node-bir-6-2',
    roadName: 'Harborne Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-12',
    fromNodeId: 'node-bir-6-2',
    toNodeId: 'node-bir-6-3',
    roadName: 'Harborne Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-13',
    fromNodeId: 'node-bir-7-1',
    toNodeId: 'node-bir-7-2',
    roadName: 'Colmore Row Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-14',
    fromNodeId: 'node-bir-7-2',
    toNodeId: 'node-bir-7-3',
    roadName: 'Colmore Row Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-15',
    fromNodeId: 'node-bir-8-1',
    toNodeId: 'node-bir-8-2',
    roadName: 'Mailbox Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-16',
    fromNodeId: 'node-bir-8-2',
    toNodeId: 'node-bir-8-3',
    roadName: 'Mailbox Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-17',
    fromNodeId: 'node-bir-9-1',
    toNodeId: 'node-bir-9-2',
    roadName: 'Selly Oak Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-18',
    fromNodeId: 'node-bir-9-2',
    toNodeId: 'node-bir-9-3',
    roadName: 'Selly Oak Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-19',
    fromNodeId: 'node-bir-10-1',
    toNodeId: 'node-bir-10-2',
    roadName: 'Kings Heath Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bir-20',
    fromNodeId: 'node-bir-10-2',
    toNodeId: 'node-bir-10-3',
    roadName: 'Kings Heath Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
