/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Boston Back Bay & Seaport
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BOSTON_BASE_COORDINATE: GeoCoordinate = {
  latitude: 42.3601,
  longitude: -71.0589,
};

export const BOSTON_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bos-1-1',
    name: 'Back Bay Sector 1 High Street',
    zone: 'Back Bay',
    location: { latitude: 42.298100, longitude: -71.110900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Back Bay.',
  },
  {
    id: 'node-bos-1-2',
    name: 'Back Bay Sector 2 High Street',
    zone: 'Back Bay',
    location: { latitude: 42.301100, longitude: -71.107900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Back Bay.',
  },
  {
    id: 'node-bos-1-3',
    name: 'Back Bay Sector 3 High Street',
    zone: 'Back Bay',
    location: { latitude: 42.304100, longitude: -71.104900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Back Bay.',
  },
  {
    id: 'node-bos-2-1',
    name: 'Seaport District Sector 1 High Street',
    zone: 'Seaport District',
    location: { latitude: 42.310100, longitude: -71.100900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Seaport District.',
  },
  {
    id: 'node-bos-2-2',
    name: 'Seaport District Sector 2 High Street',
    zone: 'Seaport District',
    location: { latitude: 42.313100, longitude: -71.097900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Seaport District.',
  },
  {
    id: 'node-bos-2-3',
    name: 'Seaport District Sector 3 High Street',
    zone: 'Seaport District',
    location: { latitude: 42.316100, longitude: -71.094900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Seaport District.',
  },
  {
    id: 'node-bos-3-1',
    name: 'Beacon Hill Sector 1 High Street',
    zone: 'Beacon Hill',
    location: { latitude: 42.322100, longitude: -71.090900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Beacon Hill.',
  },
  {
    id: 'node-bos-3-2',
    name: 'Beacon Hill Sector 2 High Street',
    zone: 'Beacon Hill',
    location: { latitude: 42.325100, longitude: -71.087900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Beacon Hill.',
  },
  {
    id: 'node-bos-3-3',
    name: 'Beacon Hill Sector 3 High Street',
    zone: 'Beacon Hill',
    location: { latitude: 42.328100, longitude: -71.084900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Beacon Hill.',
  },
  {
    id: 'node-bos-4-1',
    name: 'North End Sector 1 High Street',
    zone: 'North End',
    location: { latitude: 42.334100, longitude: -71.080900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in North End.',
  },
  {
    id: 'node-bos-4-2',
    name: 'North End Sector 2 High Street',
    zone: 'North End',
    location: { latitude: 42.337100, longitude: -71.077900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in North End.',
  },
  {
    id: 'node-bos-4-3',
    name: 'North End Sector 3 High Street',
    zone: 'North End',
    location: { latitude: 42.340100, longitude: -71.074900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in North End.',
  },
  {
    id: 'node-bos-5-1',
    name: 'South End Boston Sector 1 High Street',
    zone: 'South End Boston',
    location: { latitude: 42.346100, longitude: -71.070900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in South End Boston.',
  },
  {
    id: 'node-bos-5-2',
    name: 'South End Boston Sector 2 High Street',
    zone: 'South End Boston',
    location: { latitude: 42.349100, longitude: -71.067900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in South End Boston.',
  },
  {
    id: 'node-bos-5-3',
    name: 'South End Boston Sector 3 High Street',
    zone: 'South End Boston',
    location: { latitude: 42.352100, longitude: -71.064900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in South End Boston.',
  },
  {
    id: 'node-bos-6-1',
    name: 'Cambridge Harvard Sector 1 High Street',
    zone: 'Cambridge Harvard',
    location: { latitude: 42.358100, longitude: -71.060900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cambridge Harvard.',
  },
  {
    id: 'node-bos-6-2',
    name: 'Cambridge Harvard Sector 2 High Street',
    zone: 'Cambridge Harvard',
    location: { latitude: 42.361100, longitude: -71.057900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cambridge Harvard.',
  },
  {
    id: 'node-bos-6-3',
    name: 'Cambridge Harvard Sector 3 High Street',
    zone: 'Cambridge Harvard',
    location: { latitude: 42.364100, longitude: -71.054900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cambridge Harvard.',
  },
  {
    id: 'node-bos-7-1',
    name: 'Fenway Sector 1 High Street',
    zone: 'Fenway',
    location: { latitude: 42.370100, longitude: -71.050900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fenway.',
  },
  {
    id: 'node-bos-7-2',
    name: 'Fenway Sector 2 High Street',
    zone: 'Fenway',
    location: { latitude: 42.373100, longitude: -71.047900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fenway.',
  },
  {
    id: 'node-bos-7-3',
    name: 'Fenway Sector 3 High Street',
    zone: 'Fenway',
    location: { latitude: 42.376100, longitude: -71.044900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fenway.',
  },
  {
    id: 'node-bos-8-1',
    name: 'Brookline Sector 1 High Street',
    zone: 'Brookline',
    location: { latitude: 42.382100, longitude: -71.040900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Brookline.',
  },
  {
    id: 'node-bos-8-2',
    name: 'Brookline Sector 2 High Street',
    zone: 'Brookline',
    location: { latitude: 42.385100, longitude: -71.037900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Brookline.',
  },
  {
    id: 'node-bos-8-3',
    name: 'Brookline Sector 3 High Street',
    zone: 'Brookline',
    location: { latitude: 42.388100, longitude: -71.034900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Brookline.',
  },
  {
    id: 'node-bos-9-1',
    name: 'Somerville Sector 1 High Street',
    zone: 'Somerville',
    location: { latitude: 42.394100, longitude: -71.030900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Somerville.',
  },
  {
    id: 'node-bos-9-2',
    name: 'Somerville Sector 2 High Street',
    zone: 'Somerville',
    location: { latitude: 42.397100, longitude: -71.027900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Somerville.',
  },
  {
    id: 'node-bos-9-3',
    name: 'Somerville Sector 3 High Street',
    zone: 'Somerville',
    location: { latitude: 42.400100, longitude: -71.024900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Somerville.',
  },
  {
    id: 'node-bos-10-1',
    name: 'Charlestown Sector 1 High Street',
    zone: 'Charlestown',
    location: { latitude: 42.406100, longitude: -71.020900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Charlestown.',
  },
  {
    id: 'node-bos-10-2',
    name: 'Charlestown Sector 2 High Street',
    zone: 'Charlestown',
    location: { latitude: 42.409100, longitude: -71.017900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Charlestown.',
  },
  {
    id: 'node-bos-10-3',
    name: 'Charlestown Sector 3 High Street',
    zone: 'Charlestown',
    location: { latitude: 42.412100, longitude: -71.014900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Charlestown.',
  },
];

export const BOSTON_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bos-1',
    fromNodeId: 'node-bos-1-1',
    toNodeId: 'node-bos-1-2',
    roadName: 'Back Bay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-2',
    fromNodeId: 'node-bos-1-2',
    toNodeId: 'node-bos-1-3',
    roadName: 'Back Bay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-3',
    fromNodeId: 'node-bos-2-1',
    toNodeId: 'node-bos-2-2',
    roadName: 'Seaport District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-4',
    fromNodeId: 'node-bos-2-2',
    toNodeId: 'node-bos-2-3',
    roadName: 'Seaport District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-5',
    fromNodeId: 'node-bos-3-1',
    toNodeId: 'node-bos-3-2',
    roadName: 'Beacon Hill Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-6',
    fromNodeId: 'node-bos-3-2',
    toNodeId: 'node-bos-3-3',
    roadName: 'Beacon Hill Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-7',
    fromNodeId: 'node-bos-4-1',
    toNodeId: 'node-bos-4-2',
    roadName: 'North End Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-8',
    fromNodeId: 'node-bos-4-2',
    toNodeId: 'node-bos-4-3',
    roadName: 'North End Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-9',
    fromNodeId: 'node-bos-5-1',
    toNodeId: 'node-bos-5-2',
    roadName: 'South End Boston Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-10',
    fromNodeId: 'node-bos-5-2',
    toNodeId: 'node-bos-5-3',
    roadName: 'South End Boston Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-11',
    fromNodeId: 'node-bos-6-1',
    toNodeId: 'node-bos-6-2',
    roadName: 'Cambridge Harvard Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-12',
    fromNodeId: 'node-bos-6-2',
    toNodeId: 'node-bos-6-3',
    roadName: 'Cambridge Harvard Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-13',
    fromNodeId: 'node-bos-7-1',
    toNodeId: 'node-bos-7-2',
    roadName: 'Fenway Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-14',
    fromNodeId: 'node-bos-7-2',
    toNodeId: 'node-bos-7-3',
    roadName: 'Fenway Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-15',
    fromNodeId: 'node-bos-8-1',
    toNodeId: 'node-bos-8-2',
    roadName: 'Brookline Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-16',
    fromNodeId: 'node-bos-8-2',
    toNodeId: 'node-bos-8-3',
    roadName: 'Brookline Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-17',
    fromNodeId: 'node-bos-9-1',
    toNodeId: 'node-bos-9-2',
    roadName: 'Somerville Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-18',
    fromNodeId: 'node-bos-9-2',
    toNodeId: 'node-bos-9-3',
    roadName: 'Somerville Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-19',
    fromNodeId: 'node-bos-10-1',
    toNodeId: 'node-bos-10-2',
    roadName: 'Charlestown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bos-20',
    fromNodeId: 'node-bos-10-2',
    toNodeId: 'node-bos-10-3',
    roadName: 'Charlestown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
