/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Brussels European Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BRUSSELS_BASE_COORDINATE: GeoCoordinate = {
  latitude: 50.8503,
  longitude: 4.3517,
};

export const BRUSSELS_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bru-1-1',
    name: 'Grand Place Sector 1 High Street',
    zone: 'Grand Place',
    location: { latitude: 50.788300, longitude: 4.299700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Grand Place.',
  },
  {
    id: 'node-bru-1-2',
    name: 'Grand Place Sector 2 High Street',
    zone: 'Grand Place',
    location: { latitude: 50.791300, longitude: 4.302700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Grand Place.',
  },
  {
    id: 'node-bru-1-3',
    name: 'Grand Place Sector 3 High Street',
    zone: 'Grand Place',
    location: { latitude: 50.794300, longitude: 4.305700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Grand Place.',
  },
  {
    id: 'node-bru-2-1',
    name: 'Ixelles Sector 1 High Street',
    zone: 'Ixelles',
    location: { latitude: 50.800300, longitude: 4.309700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ixelles.',
  },
  {
    id: 'node-bru-2-2',
    name: 'Ixelles Sector 2 High Street',
    zone: 'Ixelles',
    location: { latitude: 50.803300, longitude: 4.312700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ixelles.',
  },
  {
    id: 'node-bru-2-3',
    name: 'Ixelles Sector 3 High Street',
    zone: 'Ixelles',
    location: { latitude: 50.806300, longitude: 4.315700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ixelles.',
  },
  {
    id: 'node-bru-3-1',
    name: 'Saint-Gilles Sector 1 High Street',
    zone: 'Saint-Gilles',
    location: { latitude: 50.812300, longitude: 4.319700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Saint-Gilles.',
  },
  {
    id: 'node-bru-3-2',
    name: 'Saint-Gilles Sector 2 High Street',
    zone: 'Saint-Gilles',
    location: { latitude: 50.815300, longitude: 4.322700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Saint-Gilles.',
  },
  {
    id: 'node-bru-3-3',
    name: 'Saint-Gilles Sector 3 High Street',
    zone: 'Saint-Gilles',
    location: { latitude: 50.818300, longitude: 4.325700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Saint-Gilles.',
  },
  {
    id: 'node-bru-4-1',
    name: 'European Quarter Sector 1 High Street',
    zone: 'European Quarter',
    location: { latitude: 50.824300, longitude: 4.329700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in European Quarter.',
  },
  {
    id: 'node-bru-4-2',
    name: 'European Quarter Sector 2 High Street',
    zone: 'European Quarter',
    location: { latitude: 50.827300, longitude: 4.332700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in European Quarter.',
  },
  {
    id: 'node-bru-4-3',
    name: 'European Quarter Sector 3 High Street',
    zone: 'European Quarter',
    location: { latitude: 50.830300, longitude: 4.335700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in European Quarter.',
  },
  {
    id: 'node-bru-5-1',
    name: 'Uccle Sector 1 High Street',
    zone: 'Uccle',
    location: { latitude: 50.836300, longitude: 4.339700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Uccle.',
  },
  {
    id: 'node-bru-5-2',
    name: 'Uccle Sector 2 High Street',
    zone: 'Uccle',
    location: { latitude: 50.839300, longitude: 4.342700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Uccle.',
  },
  {
    id: 'node-bru-5-3',
    name: 'Uccle Sector 3 High Street',
    zone: 'Uccle',
    location: { latitude: 50.842300, longitude: 4.345700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Uccle.',
  },
  {
    id: 'node-bru-6-1',
    name: 'Schaerbeek Sector 1 High Street',
    zone: 'Schaerbeek',
    location: { latitude: 50.848300, longitude: 4.349700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Schaerbeek.',
  },
  {
    id: 'node-bru-6-2',
    name: 'Schaerbeek Sector 2 High Street',
    zone: 'Schaerbeek',
    location: { latitude: 50.851300, longitude: 4.352700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Schaerbeek.',
  },
  {
    id: 'node-bru-6-3',
    name: 'Schaerbeek Sector 3 High Street',
    zone: 'Schaerbeek',
    location: { latitude: 50.854300, longitude: 4.355700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Schaerbeek.',
  },
  {
    id: 'node-bru-7-1',
    name: 'Etterbeek Sector 1 High Street',
    zone: 'Etterbeek',
    location: { latitude: 50.860300, longitude: 4.359700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Etterbeek.',
  },
  {
    id: 'node-bru-7-2',
    name: 'Etterbeek Sector 2 High Street',
    zone: 'Etterbeek',
    location: { latitude: 50.863300, longitude: 4.362700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Etterbeek.',
  },
  {
    id: 'node-bru-7-3',
    name: 'Etterbeek Sector 3 High Street',
    zone: 'Etterbeek',
    location: { latitude: 50.866300, longitude: 4.365700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Etterbeek.',
  },
  {
    id: 'node-bru-8-1',
    name: 'Forest Sector 1 High Street',
    zone: 'Forest',
    location: { latitude: 50.872300, longitude: 4.369700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Forest.',
  },
  {
    id: 'node-bru-8-2',
    name: 'Forest Sector 2 High Street',
    zone: 'Forest',
    location: { latitude: 50.875300, longitude: 4.372700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Forest.',
  },
  {
    id: 'node-bru-8-3',
    name: 'Forest Sector 3 High Street',
    zone: 'Forest',
    location: { latitude: 50.878300, longitude: 4.375700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Forest.',
  },
  {
    id: 'node-bru-9-1',
    name: 'Woluwe Sector 1 High Street',
    zone: 'Woluwe',
    location: { latitude: 50.884300, longitude: 4.379700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Woluwe.',
  },
  {
    id: 'node-bru-9-2',
    name: 'Woluwe Sector 2 High Street',
    zone: 'Woluwe',
    location: { latitude: 50.887300, longitude: 4.382700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Woluwe.',
  },
  {
    id: 'node-bru-9-3',
    name: 'Woluwe Sector 3 High Street',
    zone: 'Woluwe',
    location: { latitude: 50.890300, longitude: 4.385700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Woluwe.',
  },
  {
    id: 'node-bru-10-1',
    name: 'Molenbeek Sector 1 High Street',
    zone: 'Molenbeek',
    location: { latitude: 50.896300, longitude: 4.389700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Molenbeek.',
  },
  {
    id: 'node-bru-10-2',
    name: 'Molenbeek Sector 2 High Street',
    zone: 'Molenbeek',
    location: { latitude: 50.899300, longitude: 4.392700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Molenbeek.',
  },
  {
    id: 'node-bru-10-3',
    name: 'Molenbeek Sector 3 High Street',
    zone: 'Molenbeek',
    location: { latitude: 50.902300, longitude: 4.395700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Molenbeek.',
  },
];

export const BRUSSELS_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bru-1',
    fromNodeId: 'node-bru-1-1',
    toNodeId: 'node-bru-1-2',
    roadName: 'Grand Place Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-2',
    fromNodeId: 'node-bru-1-2',
    toNodeId: 'node-bru-1-3',
    roadName: 'Grand Place Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-3',
    fromNodeId: 'node-bru-2-1',
    toNodeId: 'node-bru-2-2',
    roadName: 'Ixelles Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-4',
    fromNodeId: 'node-bru-2-2',
    toNodeId: 'node-bru-2-3',
    roadName: 'Ixelles Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-5',
    fromNodeId: 'node-bru-3-1',
    toNodeId: 'node-bru-3-2',
    roadName: 'Saint-Gilles Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-6',
    fromNodeId: 'node-bru-3-2',
    toNodeId: 'node-bru-3-3',
    roadName: 'Saint-Gilles Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-7',
    fromNodeId: 'node-bru-4-1',
    toNodeId: 'node-bru-4-2',
    roadName: 'European Quarter Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-8',
    fromNodeId: 'node-bru-4-2',
    toNodeId: 'node-bru-4-3',
    roadName: 'European Quarter Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-9',
    fromNodeId: 'node-bru-5-1',
    toNodeId: 'node-bru-5-2',
    roadName: 'Uccle Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-10',
    fromNodeId: 'node-bru-5-2',
    toNodeId: 'node-bru-5-3',
    roadName: 'Uccle Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-11',
    fromNodeId: 'node-bru-6-1',
    toNodeId: 'node-bru-6-2',
    roadName: 'Schaerbeek Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-12',
    fromNodeId: 'node-bru-6-2',
    toNodeId: 'node-bru-6-3',
    roadName: 'Schaerbeek Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-13',
    fromNodeId: 'node-bru-7-1',
    toNodeId: 'node-bru-7-2',
    roadName: 'Etterbeek Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-14',
    fromNodeId: 'node-bru-7-2',
    toNodeId: 'node-bru-7-3',
    roadName: 'Etterbeek Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-15',
    fromNodeId: 'node-bru-8-1',
    toNodeId: 'node-bru-8-2',
    roadName: 'Forest Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-16',
    fromNodeId: 'node-bru-8-2',
    toNodeId: 'node-bru-8-3',
    roadName: 'Forest Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-17',
    fromNodeId: 'node-bru-9-1',
    toNodeId: 'node-bru-9-2',
    roadName: 'Woluwe Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-18',
    fromNodeId: 'node-bru-9-2',
    toNodeId: 'node-bru-9-3',
    roadName: 'Woluwe Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-19',
    fromNodeId: 'node-bru-10-1',
    toNodeId: 'node-bru-10-2',
    roadName: 'Molenbeek Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bru-20',
    fromNodeId: 'node-bru-10-2',
    toNodeId: 'node-bru-10-3',
    roadName: 'Molenbeek Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
