/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Bucharest Little Paris
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BUCHAREST_BASE_COORDINATE: GeoCoordinate = {
  latitude: 44.4268,
  longitude: 26.1025,
};

export const BUCHAREST_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-buc-1-1',
    name: 'Old Town Bucharest Sector 1 High Street',
    zone: 'Old Town Bucharest',
    location: { latitude: 44.364800, longitude: 26.050500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old Town Bucharest.',
  },
  {
    id: 'node-buc-1-2',
    name: 'Old Town Bucharest Sector 2 High Street',
    zone: 'Old Town Bucharest',
    location: { latitude: 44.367800, longitude: 26.053500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old Town Bucharest.',
  },
  {
    id: 'node-buc-1-3',
    name: 'Old Town Bucharest Sector 3 High Street',
    zone: 'Old Town Bucharest',
    location: { latitude: 44.370800, longitude: 26.056500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old Town Bucharest.',
  },
  {
    id: 'node-buc-2-1',
    name: 'Dorobanți Sector 1 High Street',
    zone: 'Dorobanți',
    location: { latitude: 44.376800, longitude: 26.060500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dorobanți.',
  },
  {
    id: 'node-buc-2-2',
    name: 'Dorobanți Sector 2 High Street',
    zone: 'Dorobanți',
    location: { latitude: 44.379800, longitude: 26.063500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dorobanți.',
  },
  {
    id: 'node-buc-2-3',
    name: 'Dorobanți Sector 3 High Street',
    zone: 'Dorobanți',
    location: { latitude: 44.382800, longitude: 26.066500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dorobanți.',
  },
  {
    id: 'node-buc-3-1',
    name: 'Floreasca Sector 1 High Street',
    zone: 'Floreasca',
    location: { latitude: 44.388800, longitude: 26.070500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Floreasca.',
  },
  {
    id: 'node-buc-3-2',
    name: 'Floreasca Sector 2 High Street',
    zone: 'Floreasca',
    location: { latitude: 44.391800, longitude: 26.073500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Floreasca.',
  },
  {
    id: 'node-buc-3-3',
    name: 'Floreasca Sector 3 High Street',
    zone: 'Floreasca',
    location: { latitude: 44.394800, longitude: 26.076500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Floreasca.',
  },
  {
    id: 'node-buc-4-1',
    name: 'Primăverii Sector 1 High Street',
    zone: 'Primăverii',
    location: { latitude: 44.400800, longitude: 26.080500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Primăverii.',
  },
  {
    id: 'node-buc-4-2',
    name: 'Primăverii Sector 2 High Street',
    zone: 'Primăverii',
    location: { latitude: 44.403800, longitude: 26.083500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Primăverii.',
  },
  {
    id: 'node-buc-4-3',
    name: 'Primăverii Sector 3 High Street',
    zone: 'Primăverii',
    location: { latitude: 44.406800, longitude: 26.086500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Primăverii.',
  },
  {
    id: 'node-buc-5-1',
    name: 'Cotroceni Sector 1 High Street',
    zone: 'Cotroceni',
    location: { latitude: 44.412800, longitude: 26.090500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cotroceni.',
  },
  {
    id: 'node-buc-5-2',
    name: 'Cotroceni Sector 2 High Street',
    zone: 'Cotroceni',
    location: { latitude: 44.415800, longitude: 26.093500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cotroceni.',
  },
  {
    id: 'node-buc-5-3',
    name: 'Cotroceni Sector 3 High Street',
    zone: 'Cotroceni',
    location: { latitude: 44.418800, longitude: 26.096500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cotroceni.',
  },
  {
    id: 'node-buc-6-1',
    name: 'Pipera Sector 1 High Street',
    zone: 'Pipera',
    location: { latitude: 44.424800, longitude: 26.100500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pipera.',
  },
  {
    id: 'node-buc-6-2',
    name: 'Pipera Sector 2 High Street',
    zone: 'Pipera',
    location: { latitude: 44.427800, longitude: 26.103500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pipera.',
  },
  {
    id: 'node-buc-6-3',
    name: 'Pipera Sector 3 High Street',
    zone: 'Pipera',
    location: { latitude: 44.430800, longitude: 26.106500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pipera.',
  },
  {
    id: 'node-buc-7-1',
    name: 'Aviatorilor Sector 1 High Street',
    zone: 'Aviatorilor',
    location: { latitude: 44.436800, longitude: 26.110500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Aviatorilor.',
  },
  {
    id: 'node-buc-7-2',
    name: 'Aviatorilor Sector 2 High Street',
    zone: 'Aviatorilor',
    location: { latitude: 44.439800, longitude: 26.113500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Aviatorilor.',
  },
  {
    id: 'node-buc-7-3',
    name: 'Aviatorilor Sector 3 High Street',
    zone: 'Aviatorilor',
    location: { latitude: 44.442800, longitude: 26.116500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Aviatorilor.',
  },
  {
    id: 'node-buc-8-1',
    name: 'Tineretului Sector 1 High Street',
    zone: 'Tineretului',
    location: { latitude: 44.448800, longitude: 26.120500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tineretului.',
  },
  {
    id: 'node-buc-8-2',
    name: 'Tineretului Sector 2 High Street',
    zone: 'Tineretului',
    location: { latitude: 44.451800, longitude: 26.123500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tineretului.',
  },
  {
    id: 'node-buc-8-3',
    name: 'Tineretului Sector 3 High Street',
    zone: 'Tineretului',
    location: { latitude: 44.454800, longitude: 26.126500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tineretului.',
  },
  {
    id: 'node-buc-9-1',
    name: 'Titan Bucharest Sector 1 High Street',
    zone: 'Titan Bucharest',
    location: { latitude: 44.460800, longitude: 26.130500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Titan Bucharest.',
  },
  {
    id: 'node-buc-9-2',
    name: 'Titan Bucharest Sector 2 High Street',
    zone: 'Titan Bucharest',
    location: { latitude: 44.463800, longitude: 26.133500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Titan Bucharest.',
  },
  {
    id: 'node-buc-9-3',
    name: 'Titan Bucharest Sector 3 High Street',
    zone: 'Titan Bucharest',
    location: { latitude: 44.466800, longitude: 26.136500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Titan Bucharest.',
  },
  {
    id: 'node-buc-10-1',
    name: 'Berceni Sector 1 High Street',
    zone: 'Berceni',
    location: { latitude: 44.472800, longitude: 26.140500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Berceni.',
  },
  {
    id: 'node-buc-10-2',
    name: 'Berceni Sector 2 High Street',
    zone: 'Berceni',
    location: { latitude: 44.475800, longitude: 26.143500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Berceni.',
  },
  {
    id: 'node-buc-10-3',
    name: 'Berceni Sector 3 High Street',
    zone: 'Berceni',
    location: { latitude: 44.478800, longitude: 26.146500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Berceni.',
  },
];

export const BUCHAREST_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-buc-1',
    fromNodeId: 'node-buc-1-1',
    toNodeId: 'node-buc-1-2',
    roadName: 'Old Town Bucharest Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-2',
    fromNodeId: 'node-buc-1-2',
    toNodeId: 'node-buc-1-3',
    roadName: 'Old Town Bucharest Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-3',
    fromNodeId: 'node-buc-2-1',
    toNodeId: 'node-buc-2-2',
    roadName: 'Dorobanți Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-4',
    fromNodeId: 'node-buc-2-2',
    toNodeId: 'node-buc-2-3',
    roadName: 'Dorobanți Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-5',
    fromNodeId: 'node-buc-3-1',
    toNodeId: 'node-buc-3-2',
    roadName: 'Floreasca Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-6',
    fromNodeId: 'node-buc-3-2',
    toNodeId: 'node-buc-3-3',
    roadName: 'Floreasca Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-7',
    fromNodeId: 'node-buc-4-1',
    toNodeId: 'node-buc-4-2',
    roadName: 'Primăverii Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-8',
    fromNodeId: 'node-buc-4-2',
    toNodeId: 'node-buc-4-3',
    roadName: 'Primăverii Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-9',
    fromNodeId: 'node-buc-5-1',
    toNodeId: 'node-buc-5-2',
    roadName: 'Cotroceni Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-10',
    fromNodeId: 'node-buc-5-2',
    toNodeId: 'node-buc-5-3',
    roadName: 'Cotroceni Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-11',
    fromNodeId: 'node-buc-6-1',
    toNodeId: 'node-buc-6-2',
    roadName: 'Pipera Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-12',
    fromNodeId: 'node-buc-6-2',
    toNodeId: 'node-buc-6-3',
    roadName: 'Pipera Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-13',
    fromNodeId: 'node-buc-7-1',
    toNodeId: 'node-buc-7-2',
    roadName: 'Aviatorilor Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-14',
    fromNodeId: 'node-buc-7-2',
    toNodeId: 'node-buc-7-3',
    roadName: 'Aviatorilor Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-15',
    fromNodeId: 'node-buc-8-1',
    toNodeId: 'node-buc-8-2',
    roadName: 'Tineretului Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-16',
    fromNodeId: 'node-buc-8-2',
    toNodeId: 'node-buc-8-3',
    roadName: 'Tineretului Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-17',
    fromNodeId: 'node-buc-9-1',
    toNodeId: 'node-buc-9-2',
    roadName: 'Titan Bucharest Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-18',
    fromNodeId: 'node-buc-9-2',
    toNodeId: 'node-buc-9-3',
    roadName: 'Titan Bucharest Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-19',
    fromNodeId: 'node-buc-10-1',
    toNodeId: 'node-buc-10-2',
    roadName: 'Berceni Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-buc-20',
    fromNodeId: 'node-buc-10-2',
    toNodeId: 'node-buc-10-3',
    roadName: 'Berceni Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
