/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Budapest Danube Twin Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BUDAPEST_BASE_COORDINATE: GeoCoordinate = {
  latitude: 47.4979,
  longitude: 19.0402,
};

export const BUDAPEST_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bud-1-1',
    name: 'District V Belváros Sector 1 High Street',
    zone: 'District V Belváros',
    location: { latitude: 47.435900, longitude: 18.988200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District V Belváros.',
  },
  {
    id: 'node-bud-1-2',
    name: 'District V Belváros Sector 2 High Street',
    zone: 'District V Belváros',
    location: { latitude: 47.438900, longitude: 18.991200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District V Belváros.',
  },
  {
    id: 'node-bud-1-3',
    name: 'District V Belváros Sector 3 High Street',
    zone: 'District V Belváros',
    location: { latitude: 47.441900, longitude: 18.994200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District V Belváros.',
  },
  {
    id: 'node-bud-2-1',
    name: 'District VII Erzsébetváros Sector 1 High Street',
    zone: 'District VII Erzsébetváros',
    location: { latitude: 47.447900, longitude: 18.998200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District VII Erzsébetváros.',
  },
  {
    id: 'node-bud-2-2',
    name: 'District VII Erzsébetváros Sector 2 High Street',
    zone: 'District VII Erzsébetváros',
    location: { latitude: 47.450900, longitude: 19.001200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District VII Erzsébetváros.',
  },
  {
    id: 'node-bud-2-3',
    name: 'District VII Erzsébetváros Sector 3 High Street',
    zone: 'District VII Erzsébetváros',
    location: { latitude: 47.453900, longitude: 19.004200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District VII Erzsébetváros.',
  },
  {
    id: 'node-bud-3-1',
    name: 'District VI Terézváros Sector 1 High Street',
    zone: 'District VI Terézváros',
    location: { latitude: 47.459900, longitude: 19.008200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District VI Terézváros.',
  },
  {
    id: 'node-bud-3-2',
    name: 'District VI Terézváros Sector 2 High Street',
    zone: 'District VI Terézváros',
    location: { latitude: 47.462900, longitude: 19.011200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District VI Terézváros.',
  },
  {
    id: 'node-bud-3-3',
    name: 'District VI Terézváros Sector 3 High Street',
    zone: 'District VI Terézváros',
    location: { latitude: 47.465900, longitude: 19.014200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District VI Terézváros.',
  },
  {
    id: 'node-bud-4-1',
    name: 'District VIII Józsefváros Sector 1 High Street',
    zone: 'District VIII Józsefváros',
    location: { latitude: 47.471900, longitude: 19.018200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District VIII Józsefváros.',
  },
  {
    id: 'node-bud-4-2',
    name: 'District VIII Józsefváros Sector 2 High Street',
    zone: 'District VIII Józsefváros',
    location: { latitude: 47.474900, longitude: 19.021200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District VIII Józsefváros.',
  },
  {
    id: 'node-bud-4-3',
    name: 'District VIII Józsefváros Sector 3 High Street',
    zone: 'District VIII Józsefváros',
    location: { latitude: 47.477900, longitude: 19.024200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District VIII Józsefváros.',
  },
  {
    id: 'node-bud-5-1',
    name: 'District IX Ferencváros Sector 1 High Street',
    zone: 'District IX Ferencváros',
    location: { latitude: 47.483900, longitude: 19.028200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District IX Ferencváros.',
  },
  {
    id: 'node-bud-5-2',
    name: 'District IX Ferencváros Sector 2 High Street',
    zone: 'District IX Ferencváros',
    location: { latitude: 47.486900, longitude: 19.031200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District IX Ferencváros.',
  },
  {
    id: 'node-bud-5-3',
    name: 'District IX Ferencváros Sector 3 High Street',
    zone: 'District IX Ferencváros',
    location: { latitude: 47.489900, longitude: 19.034200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District IX Ferencváros.',
  },
  {
    id: 'node-bud-6-1',
    name: 'District XIII Újlipótváros Sector 1 High Street',
    zone: 'District XIII Újlipótváros',
    location: { latitude: 47.495900, longitude: 19.038200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District XIII Újlipótváros.',
  },
  {
    id: 'node-bud-6-2',
    name: 'District XIII Újlipótváros Sector 2 High Street',
    zone: 'District XIII Újlipótváros',
    location: { latitude: 47.498900, longitude: 19.041200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District XIII Újlipótváros.',
  },
  {
    id: 'node-bud-6-3',
    name: 'District XIII Újlipótváros Sector 3 High Street',
    zone: 'District XIII Újlipótváros',
    location: { latitude: 47.501900, longitude: 19.044200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District XIII Újlipótváros.',
  },
  {
    id: 'node-bud-7-1',
    name: 'Buda Castle District Sector 1 High Street',
    zone: 'Buda Castle District',
    location: { latitude: 47.507900, longitude: 19.048200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Buda Castle District.',
  },
  {
    id: 'node-bud-7-2',
    name: 'Buda Castle District Sector 2 High Street',
    zone: 'Buda Castle District',
    location: { latitude: 47.510900, longitude: 19.051200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Buda Castle District.',
  },
  {
    id: 'node-bud-7-3',
    name: 'Buda Castle District Sector 3 High Street',
    zone: 'Buda Castle District',
    location: { latitude: 47.513900, longitude: 19.054200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Buda Castle District.',
  },
  {
    id: 'node-bud-8-1',
    name: 'Újbuda Sector 1 High Street',
    zone: 'Újbuda',
    location: { latitude: 47.519900, longitude: 19.058200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Újbuda.',
  },
  {
    id: 'node-bud-8-2',
    name: 'Újbuda Sector 2 High Street',
    zone: 'Újbuda',
    location: { latitude: 47.522900, longitude: 19.061200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Újbuda.',
  },
  {
    id: 'node-bud-8-3',
    name: 'Újbuda Sector 3 High Street',
    zone: 'Újbuda',
    location: { latitude: 47.525900, longitude: 19.064200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Újbuda.',
  },
  {
    id: 'node-bud-9-1',
    name: 'Óbuda Sector 1 High Street',
    zone: 'Óbuda',
    location: { latitude: 47.531900, longitude: 19.068200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Óbuda.',
  },
  {
    id: 'node-bud-9-2',
    name: 'Óbuda Sector 2 High Street',
    zone: 'Óbuda',
    location: { latitude: 47.534900, longitude: 19.071200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Óbuda.',
  },
  {
    id: 'node-bud-9-3',
    name: 'Óbuda Sector 3 High Street',
    zone: 'Óbuda',
    location: { latitude: 47.537900, longitude: 19.074200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Óbuda.',
  },
  {
    id: 'node-bud-10-1',
    name: 'Zugló Sector 1 High Street',
    zone: 'Zugló',
    location: { latitude: 47.543900, longitude: 19.078200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zugló.',
  },
  {
    id: 'node-bud-10-2',
    name: 'Zugló Sector 2 High Street',
    zone: 'Zugló',
    location: { latitude: 47.546900, longitude: 19.081200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zugló.',
  },
  {
    id: 'node-bud-10-3',
    name: 'Zugló Sector 3 High Street',
    zone: 'Zugló',
    location: { latitude: 47.549900, longitude: 19.084200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zugló.',
  },
];

export const BUDAPEST_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bud-1',
    fromNodeId: 'node-bud-1-1',
    toNodeId: 'node-bud-1-2',
    roadName: 'District V Belváros Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-2',
    fromNodeId: 'node-bud-1-2',
    toNodeId: 'node-bud-1-3',
    roadName: 'District V Belváros Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-3',
    fromNodeId: 'node-bud-2-1',
    toNodeId: 'node-bud-2-2',
    roadName: 'District VII Erzsébetváros Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-4',
    fromNodeId: 'node-bud-2-2',
    toNodeId: 'node-bud-2-3',
    roadName: 'District VII Erzsébetváros Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-5',
    fromNodeId: 'node-bud-3-1',
    toNodeId: 'node-bud-3-2',
    roadName: 'District VI Terézváros Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-6',
    fromNodeId: 'node-bud-3-2',
    toNodeId: 'node-bud-3-3',
    roadName: 'District VI Terézváros Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-7',
    fromNodeId: 'node-bud-4-1',
    toNodeId: 'node-bud-4-2',
    roadName: 'District VIII Józsefváros Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-8',
    fromNodeId: 'node-bud-4-2',
    toNodeId: 'node-bud-4-3',
    roadName: 'District VIII Józsefváros Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-9',
    fromNodeId: 'node-bud-5-1',
    toNodeId: 'node-bud-5-2',
    roadName: 'District IX Ferencváros Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-10',
    fromNodeId: 'node-bud-5-2',
    toNodeId: 'node-bud-5-3',
    roadName: 'District IX Ferencváros Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-11',
    fromNodeId: 'node-bud-6-1',
    toNodeId: 'node-bud-6-2',
    roadName: 'District XIII Újlipótváros Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-12',
    fromNodeId: 'node-bud-6-2',
    toNodeId: 'node-bud-6-3',
    roadName: 'District XIII Újlipótváros Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-13',
    fromNodeId: 'node-bud-7-1',
    toNodeId: 'node-bud-7-2',
    roadName: 'Buda Castle District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-14',
    fromNodeId: 'node-bud-7-2',
    toNodeId: 'node-bud-7-3',
    roadName: 'Buda Castle District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-15',
    fromNodeId: 'node-bud-8-1',
    toNodeId: 'node-bud-8-2',
    roadName: 'Újbuda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-16',
    fromNodeId: 'node-bud-8-2',
    toNodeId: 'node-bud-8-3',
    roadName: 'Újbuda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-17',
    fromNodeId: 'node-bud-9-1',
    toNodeId: 'node-bud-9-2',
    roadName: 'Óbuda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-18',
    fromNodeId: 'node-bud-9-2',
    toNodeId: 'node-bud-9-3',
    roadName: 'Óbuda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-19',
    fromNodeId: 'node-bud-10-1',
    toNodeId: 'node-bud-10-2',
    roadName: 'Zugló Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bud-20',
    fromNodeId: 'node-bud-10-2',
    toNodeId: 'node-bud-10-3',
    roadName: 'Zugló Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
