/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Buenos Aires Palermo Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BUENOSAIRES_BASE_COORDINATE: GeoCoordinate = {
  latitude: -34.6037,
  longitude: -58.3816,
};

export const BUENOSAIRES_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bue-1-1',
    name: 'Palermo Soho Sector 1 High Street',
    zone: 'Palermo Soho',
    location: { latitude: -34.665700, longitude: -58.433600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Palermo Soho.',
  },
  {
    id: 'node-bue-1-2',
    name: 'Palermo Soho Sector 2 High Street',
    zone: 'Palermo Soho',
    location: { latitude: -34.662700, longitude: -58.430600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Palermo Soho.',
  },
  {
    id: 'node-bue-1-3',
    name: 'Palermo Soho Sector 3 High Street',
    zone: 'Palermo Soho',
    location: { latitude: -34.659700, longitude: -58.427600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Palermo Soho.',
  },
  {
    id: 'node-bue-2-1',
    name: 'Palermo Hollywood Sector 1 High Street',
    zone: 'Palermo Hollywood',
    location: { latitude: -34.653700, longitude: -58.423600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Palermo Hollywood.',
  },
  {
    id: 'node-bue-2-2',
    name: 'Palermo Hollywood Sector 2 High Street',
    zone: 'Palermo Hollywood',
    location: { latitude: -34.650700, longitude: -58.420600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Palermo Hollywood.',
  },
  {
    id: 'node-bue-2-3',
    name: 'Palermo Hollywood Sector 3 High Street',
    zone: 'Palermo Hollywood',
    location: { latitude: -34.647700, longitude: -58.417600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Palermo Hollywood.',
  },
  {
    id: 'node-bue-3-1',
    name: 'Recoleta Sector 1 High Street',
    zone: 'Recoleta',
    location: { latitude: -34.641700, longitude: -58.413600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Recoleta.',
  },
  {
    id: 'node-bue-3-2',
    name: 'Recoleta Sector 2 High Street',
    zone: 'Recoleta',
    location: { latitude: -34.638700, longitude: -58.410600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Recoleta.',
  },
  {
    id: 'node-bue-3-3',
    name: 'Recoleta Sector 3 High Street',
    zone: 'Recoleta',
    location: { latitude: -34.635700, longitude: -58.407600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Recoleta.',
  },
  {
    id: 'node-bue-4-1',
    name: 'San Telmo Sector 1 High Street',
    zone: 'San Telmo',
    location: { latitude: -34.629700, longitude: -58.403600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Telmo.',
  },
  {
    id: 'node-bue-4-2',
    name: 'San Telmo Sector 2 High Street',
    zone: 'San Telmo',
    location: { latitude: -34.626700, longitude: -58.400600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Telmo.',
  },
  {
    id: 'node-bue-4-3',
    name: 'San Telmo Sector 3 High Street',
    zone: 'San Telmo',
    location: { latitude: -34.623700, longitude: -58.397600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Telmo.',
  },
  {
    id: 'node-bue-5-1',
    name: 'Puerto Madero Sector 1 High Street',
    zone: 'Puerto Madero',
    location: { latitude: -34.617700, longitude: -58.393600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Puerto Madero.',
  },
  {
    id: 'node-bue-5-2',
    name: 'Puerto Madero Sector 2 High Street',
    zone: 'Puerto Madero',
    location: { latitude: -34.614700, longitude: -58.390600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Puerto Madero.',
  },
  {
    id: 'node-bue-5-3',
    name: 'Puerto Madero Sector 3 High Street',
    zone: 'Puerto Madero',
    location: { latitude: -34.611700, longitude: -58.387600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Puerto Madero.',
  },
  {
    id: 'node-bue-6-1',
    name: 'Belgrano Sector 1 High Street',
    zone: 'Belgrano',
    location: { latitude: -34.605700, longitude: -58.383600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Belgrano.',
  },
  {
    id: 'node-bue-6-2',
    name: 'Belgrano Sector 2 High Street',
    zone: 'Belgrano',
    location: { latitude: -34.602700, longitude: -58.380600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Belgrano.',
  },
  {
    id: 'node-bue-6-3',
    name: 'Belgrano Sector 3 High Street',
    zone: 'Belgrano',
    location: { latitude: -34.599700, longitude: -58.377600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Belgrano.',
  },
  {
    id: 'node-bue-7-1',
    name: 'Villa Crespo Sector 1 High Street',
    zone: 'Villa Crespo',
    location: { latitude: -34.593700, longitude: -58.373600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Villa Crespo.',
  },
  {
    id: 'node-bue-7-2',
    name: 'Villa Crespo Sector 2 High Street',
    zone: 'Villa Crespo',
    location: { latitude: -34.590700, longitude: -58.370600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Villa Crespo.',
  },
  {
    id: 'node-bue-7-3',
    name: 'Villa Crespo Sector 3 High Street',
    zone: 'Villa Crespo',
    location: { latitude: -34.587700, longitude: -58.367600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Villa Crespo.',
  },
  {
    id: 'node-bue-8-1',
    name: 'Colegiales Sector 1 High Street',
    zone: 'Colegiales',
    location: { latitude: -34.581700, longitude: -58.363600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Colegiales.',
  },
  {
    id: 'node-bue-8-2',
    name: 'Colegiales Sector 2 High Street',
    zone: 'Colegiales',
    location: { latitude: -34.578700, longitude: -58.360600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Colegiales.',
  },
  {
    id: 'node-bue-8-3',
    name: 'Colegiales Sector 3 High Street',
    zone: 'Colegiales',
    location: { latitude: -34.575700, longitude: -58.357600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Colegiales.',
  },
  {
    id: 'node-bue-9-1',
    name: 'Retiro Sector 1 High Street',
    zone: 'Retiro',
    location: { latitude: -34.569700, longitude: -58.353600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Retiro.',
  },
  {
    id: 'node-bue-9-2',
    name: 'Retiro Sector 2 High Street',
    zone: 'Retiro',
    location: { latitude: -34.566700, longitude: -58.350600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Retiro.',
  },
  {
    id: 'node-bue-9-3',
    name: 'Retiro Sector 3 High Street',
    zone: 'Retiro',
    location: { latitude: -34.563700, longitude: -58.347600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Retiro.',
  },
  {
    id: 'node-bue-10-1',
    name: 'Las Cañitas Sector 1 High Street',
    zone: 'Las Cañitas',
    location: { latitude: -34.557700, longitude: -58.343600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Las Cañitas.',
  },
  {
    id: 'node-bue-10-2',
    name: 'Las Cañitas Sector 2 High Street',
    zone: 'Las Cañitas',
    location: { latitude: -34.554700, longitude: -58.340600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Las Cañitas.',
  },
  {
    id: 'node-bue-10-3',
    name: 'Las Cañitas Sector 3 High Street',
    zone: 'Las Cañitas',
    location: { latitude: -34.551700, longitude: -58.337600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Las Cañitas.',
  },
];

export const BUENOSAIRES_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bue-1',
    fromNodeId: 'node-bue-1-1',
    toNodeId: 'node-bue-1-2',
    roadName: 'Palermo Soho Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-2',
    fromNodeId: 'node-bue-1-2',
    toNodeId: 'node-bue-1-3',
    roadName: 'Palermo Soho Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-3',
    fromNodeId: 'node-bue-2-1',
    toNodeId: 'node-bue-2-2',
    roadName: 'Palermo Hollywood Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-4',
    fromNodeId: 'node-bue-2-2',
    toNodeId: 'node-bue-2-3',
    roadName: 'Palermo Hollywood Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-5',
    fromNodeId: 'node-bue-3-1',
    toNodeId: 'node-bue-3-2',
    roadName: 'Recoleta Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-6',
    fromNodeId: 'node-bue-3-2',
    toNodeId: 'node-bue-3-3',
    roadName: 'Recoleta Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-7',
    fromNodeId: 'node-bue-4-1',
    toNodeId: 'node-bue-4-2',
    roadName: 'San Telmo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-8',
    fromNodeId: 'node-bue-4-2',
    toNodeId: 'node-bue-4-3',
    roadName: 'San Telmo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-9',
    fromNodeId: 'node-bue-5-1',
    toNodeId: 'node-bue-5-2',
    roadName: 'Puerto Madero Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-10',
    fromNodeId: 'node-bue-5-2',
    toNodeId: 'node-bue-5-3',
    roadName: 'Puerto Madero Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-11',
    fromNodeId: 'node-bue-6-1',
    toNodeId: 'node-bue-6-2',
    roadName: 'Belgrano Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-12',
    fromNodeId: 'node-bue-6-2',
    toNodeId: 'node-bue-6-3',
    roadName: 'Belgrano Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-13',
    fromNodeId: 'node-bue-7-1',
    toNodeId: 'node-bue-7-2',
    roadName: 'Villa Crespo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-14',
    fromNodeId: 'node-bue-7-2',
    toNodeId: 'node-bue-7-3',
    roadName: 'Villa Crespo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-15',
    fromNodeId: 'node-bue-8-1',
    toNodeId: 'node-bue-8-2',
    roadName: 'Colegiales Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-16',
    fromNodeId: 'node-bue-8-2',
    toNodeId: 'node-bue-8-3',
    roadName: 'Colegiales Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-17',
    fromNodeId: 'node-bue-9-1',
    toNodeId: 'node-bue-9-2',
    roadName: 'Retiro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-18',
    fromNodeId: 'node-bue-9-2',
    toNodeId: 'node-bue-9-3',
    roadName: 'Retiro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-19',
    fromNodeId: 'node-bue-10-1',
    toNodeId: 'node-bue-10-2',
    roadName: 'Las Cañitas Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bue-20',
    fromNodeId: 'node-bue-10-2',
    toNodeId: 'node-bue-10-3',
    roadName: 'Las Cañitas Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
