/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Busan Coastal Maritime Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const BUSAN_BASE_COORDINATE: GeoCoordinate = {
  latitude: 35.1796,
  longitude: 129.0756,
};

export const BUSAN_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-bus-1-1',
    name: 'Haeundae Sector 1 High Street',
    zone: 'Haeundae',
    location: { latitude: 35.117600, longitude: 129.023600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Haeundae.',
  },
  {
    id: 'node-bus-1-2',
    name: 'Haeundae Sector 2 High Street',
    zone: 'Haeundae',
    location: { latitude: 35.120600, longitude: 129.026600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Haeundae.',
  },
  {
    id: 'node-bus-1-3',
    name: 'Haeundae Sector 3 High Street',
    zone: 'Haeundae',
    location: { latitude: 35.123600, longitude: 129.029600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Haeundae.',
  },
  {
    id: 'node-bus-2-1',
    name: 'Seomyeon Sector 1 High Street',
    zone: 'Seomyeon',
    location: { latitude: 35.129600, longitude: 129.033600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Seomyeon.',
  },
  {
    id: 'node-bus-2-2',
    name: 'Seomyeon Sector 2 High Street',
    zone: 'Seomyeon',
    location: { latitude: 35.132600, longitude: 129.036600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Seomyeon.',
  },
  {
    id: 'node-bus-2-3',
    name: 'Seomyeon Sector 3 High Street',
    zone: 'Seomyeon',
    location: { latitude: 35.135600, longitude: 129.039600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Seomyeon.',
  },
  {
    id: 'node-bus-3-1',
    name: 'Gwangalli Sector 1 High Street',
    zone: 'Gwangalli',
    location: { latitude: 35.141600, longitude: 129.043600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gwangalli.',
  },
  {
    id: 'node-bus-3-2',
    name: 'Gwangalli Sector 2 High Street',
    zone: 'Gwangalli',
    location: { latitude: 35.144600, longitude: 129.046600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gwangalli.',
  },
  {
    id: 'node-bus-3-3',
    name: 'Gwangalli Sector 3 High Street',
    zone: 'Gwangalli',
    location: { latitude: 35.147600, longitude: 129.049600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gwangalli.',
  },
  {
    id: 'node-bus-4-1',
    name: 'Nampo-dong Sector 1 High Street',
    zone: 'Nampo-dong',
    location: { latitude: 35.153600, longitude: 129.053600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nampo-dong.',
  },
  {
    id: 'node-bus-4-2',
    name: 'Nampo-dong Sector 2 High Street',
    zone: 'Nampo-dong',
    location: { latitude: 35.156600, longitude: 129.056600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nampo-dong.',
  },
  {
    id: 'node-bus-4-3',
    name: 'Nampo-dong Sector 3 High Street',
    zone: 'Nampo-dong',
    location: { latitude: 35.159600, longitude: 129.059600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nampo-dong.',
  },
  {
    id: 'node-bus-5-1',
    name: 'Centum City Sector 1 High Street',
    zone: 'Centum City',
    location: { latitude: 35.165600, longitude: 129.063600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Centum City.',
  },
  {
    id: 'node-bus-5-2',
    name: 'Centum City Sector 2 High Street',
    zone: 'Centum City',
    location: { latitude: 35.168600, longitude: 129.066600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Centum City.',
  },
  {
    id: 'node-bus-5-3',
    name: 'Centum City Sector 3 High Street',
    zone: 'Centum City',
    location: { latitude: 35.171600, longitude: 129.069600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Centum City.',
  },
  {
    id: 'node-bus-6-1',
    name: 'Marine City Sector 1 High Street',
    zone: 'Marine City',
    location: { latitude: 35.177600, longitude: 129.073600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Marine City.',
  },
  {
    id: 'node-bus-6-2',
    name: 'Marine City Sector 2 High Street',
    zone: 'Marine City',
    location: { latitude: 35.180600, longitude: 129.076600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Marine City.',
  },
  {
    id: 'node-bus-6-3',
    name: 'Marine City Sector 3 High Street',
    zone: 'Marine City',
    location: { latitude: 35.183600, longitude: 129.079600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Marine City.',
  },
  {
    id: 'node-bus-7-1',
    name: 'Jagalchi Sector 1 High Street',
    zone: 'Jagalchi',
    location: { latitude: 35.189600, longitude: 129.083600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jagalchi.',
  },
  {
    id: 'node-bus-7-2',
    name: 'Jagalchi Sector 2 High Street',
    zone: 'Jagalchi',
    location: { latitude: 35.192600, longitude: 129.086600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jagalchi.',
  },
  {
    id: 'node-bus-7-3',
    name: 'Jagalchi Sector 3 High Street',
    zone: 'Jagalchi',
    location: { latitude: 35.195600, longitude: 129.089600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jagalchi.',
  },
  {
    id: 'node-bus-8-1',
    name: 'Busan Station Sector 1 High Street',
    zone: 'Busan Station',
    location: { latitude: 35.201600, longitude: 129.093600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Busan Station.',
  },
  {
    id: 'node-bus-8-2',
    name: 'Busan Station Sector 2 High Street',
    zone: 'Busan Station',
    location: { latitude: 35.204600, longitude: 129.096600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Busan Station.',
  },
  {
    id: 'node-bus-8-3',
    name: 'Busan Station Sector 3 High Street',
    zone: 'Busan Station',
    location: { latitude: 35.207600, longitude: 129.099600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Busan Station.',
  },
  {
    id: 'node-bus-9-1',
    name: 'Dongnae Sector 1 High Street',
    zone: 'Dongnae',
    location: { latitude: 35.213600, longitude: 129.103600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dongnae.',
  },
  {
    id: 'node-bus-9-2',
    name: 'Dongnae Sector 2 High Street',
    zone: 'Dongnae',
    location: { latitude: 35.216600, longitude: 129.106600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dongnae.',
  },
  {
    id: 'node-bus-9-3',
    name: 'Dongnae Sector 3 High Street',
    zone: 'Dongnae',
    location: { latitude: 35.219600, longitude: 129.109600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dongnae.',
  },
  {
    id: 'node-bus-10-1',
    name: 'Gwangan Sector 1 High Street',
    zone: 'Gwangan',
    location: { latitude: 35.225600, longitude: 129.113600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gwangan.',
  },
  {
    id: 'node-bus-10-2',
    name: 'Gwangan Sector 2 High Street',
    zone: 'Gwangan',
    location: { latitude: 35.228600, longitude: 129.116600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gwangan.',
  },
  {
    id: 'node-bus-10-3',
    name: 'Gwangan Sector 3 High Street',
    zone: 'Gwangan',
    location: { latitude: 35.231600, longitude: 129.119600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gwangan.',
  },
];

export const BUSAN_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-bus-1',
    fromNodeId: 'node-bus-1-1',
    toNodeId: 'node-bus-1-2',
    roadName: 'Haeundae Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-2',
    fromNodeId: 'node-bus-1-2',
    toNodeId: 'node-bus-1-3',
    roadName: 'Haeundae Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-3',
    fromNodeId: 'node-bus-2-1',
    toNodeId: 'node-bus-2-2',
    roadName: 'Seomyeon Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-4',
    fromNodeId: 'node-bus-2-2',
    toNodeId: 'node-bus-2-3',
    roadName: 'Seomyeon Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-5',
    fromNodeId: 'node-bus-3-1',
    toNodeId: 'node-bus-3-2',
    roadName: 'Gwangalli Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-6',
    fromNodeId: 'node-bus-3-2',
    toNodeId: 'node-bus-3-3',
    roadName: 'Gwangalli Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-7',
    fromNodeId: 'node-bus-4-1',
    toNodeId: 'node-bus-4-2',
    roadName: 'Nampo-dong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-8',
    fromNodeId: 'node-bus-4-2',
    toNodeId: 'node-bus-4-3',
    roadName: 'Nampo-dong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-9',
    fromNodeId: 'node-bus-5-1',
    toNodeId: 'node-bus-5-2',
    roadName: 'Centum City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-10',
    fromNodeId: 'node-bus-5-2',
    toNodeId: 'node-bus-5-3',
    roadName: 'Centum City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-11',
    fromNodeId: 'node-bus-6-1',
    toNodeId: 'node-bus-6-2',
    roadName: 'Marine City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-12',
    fromNodeId: 'node-bus-6-2',
    toNodeId: 'node-bus-6-3',
    roadName: 'Marine City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-13',
    fromNodeId: 'node-bus-7-1',
    toNodeId: 'node-bus-7-2',
    roadName: 'Jagalchi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-14',
    fromNodeId: 'node-bus-7-2',
    toNodeId: 'node-bus-7-3',
    roadName: 'Jagalchi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-15',
    fromNodeId: 'node-bus-8-1',
    toNodeId: 'node-bus-8-2',
    roadName: 'Busan Station Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-16',
    fromNodeId: 'node-bus-8-2',
    toNodeId: 'node-bus-8-3',
    roadName: 'Busan Station Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-17',
    fromNodeId: 'node-bus-9-1',
    toNodeId: 'node-bus-9-2',
    roadName: 'Dongnae Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-18',
    fromNodeId: 'node-bus-9-2',
    toNodeId: 'node-bus-9-3',
    roadName: 'Dongnae Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-19',
    fromNodeId: 'node-bus-10-1',
    toNodeId: 'node-bus-10-2',
    roadName: 'Gwangan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-bus-20',
    fromNodeId: 'node-bus-10-2',
    toNodeId: 'node-bus-10-3',
    roadName: 'Gwangan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
