/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Cairo Nile Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const CAIRO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 30.0444,
  longitude: 31.2357,
};

export const CAIRO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-cai-1-1',
    name: 'Zamalek Sector 1 High Street',
    zone: 'Zamalek',
    location: { latitude: 29.982400, longitude: 31.183700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zamalek.',
  },
  {
    id: 'node-cai-1-2',
    name: 'Zamalek Sector 2 High Street',
    zone: 'Zamalek',
    location: { latitude: 29.985400, longitude: 31.186700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zamalek.',
  },
  {
    id: 'node-cai-1-3',
    name: 'Zamalek Sector 3 High Street',
    zone: 'Zamalek',
    location: { latitude: 29.988400, longitude: 31.189700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zamalek.',
  },
  {
    id: 'node-cai-2-1',
    name: 'Maadi Sector 1 High Street',
    zone: 'Maadi',
    location: { latitude: 29.994400, longitude: 31.193700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Maadi.',
  },
  {
    id: 'node-cai-2-2',
    name: 'Maadi Sector 2 High Street',
    zone: 'Maadi',
    location: { latitude: 29.997400, longitude: 31.196700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Maadi.',
  },
  {
    id: 'node-cai-2-3',
    name: 'Maadi Sector 3 High Street',
    zone: 'Maadi',
    location: { latitude: 30.000400, longitude: 31.199700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Maadi.',
  },
  {
    id: 'node-cai-3-1',
    name: 'New Cairo Sector 1 High Street',
    zone: 'New Cairo',
    location: { latitude: 30.006400, longitude: 31.203700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in New Cairo.',
  },
  {
    id: 'node-cai-3-2',
    name: 'New Cairo Sector 2 High Street',
    zone: 'New Cairo',
    location: { latitude: 30.009400, longitude: 31.206700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in New Cairo.',
  },
  {
    id: 'node-cai-3-3',
    name: 'New Cairo Sector 3 High Street',
    zone: 'New Cairo',
    location: { latitude: 30.012400, longitude: 31.209700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in New Cairo.',
  },
  {
    id: 'node-cai-4-1',
    name: 'Heliopolis Sector 1 High Street',
    zone: 'Heliopolis',
    location: { latitude: 30.018400, longitude: 31.213700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Heliopolis.',
  },
  {
    id: 'node-cai-4-2',
    name: 'Heliopolis Sector 2 High Street',
    zone: 'Heliopolis',
    location: { latitude: 30.021400, longitude: 31.216700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Heliopolis.',
  },
  {
    id: 'node-cai-4-3',
    name: 'Heliopolis Sector 3 High Street',
    zone: 'Heliopolis',
    location: { latitude: 30.024400, longitude: 31.219700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Heliopolis.',
  },
  {
    id: 'node-cai-5-1',
    name: 'Nasr City Sector 1 High Street',
    zone: 'Nasr City',
    location: { latitude: 30.030400, longitude: 31.223700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nasr City.',
  },
  {
    id: 'node-cai-5-2',
    name: 'Nasr City Sector 2 High Street',
    zone: 'Nasr City',
    location: { latitude: 30.033400, longitude: 31.226700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nasr City.',
  },
  {
    id: 'node-cai-5-3',
    name: 'Nasr City Sector 3 High Street',
    zone: 'Nasr City',
    location: { latitude: 30.036400, longitude: 31.229700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nasr City.',
  },
  {
    id: 'node-cai-6-1',
    name: 'Dokki Sector 1 High Street',
    zone: 'Dokki',
    location: { latitude: 30.042400, longitude: 31.233700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dokki.',
  },
  {
    id: 'node-cai-6-2',
    name: 'Dokki Sector 2 High Street',
    zone: 'Dokki',
    location: { latitude: 30.045400, longitude: 31.236700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dokki.',
  },
  {
    id: 'node-cai-6-3',
    name: 'Dokki Sector 3 High Street',
    zone: 'Dokki',
    location: { latitude: 30.048400, longitude: 31.239700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dokki.',
  },
  {
    id: 'node-cai-7-1',
    name: 'Mohandessin Sector 1 High Street',
    zone: 'Mohandessin',
    location: { latitude: 30.054400, longitude: 31.243700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mohandessin.',
  },
  {
    id: 'node-cai-7-2',
    name: 'Mohandessin Sector 2 High Street',
    zone: 'Mohandessin',
    location: { latitude: 30.057400, longitude: 31.246700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mohandessin.',
  },
  {
    id: 'node-cai-7-3',
    name: 'Mohandessin Sector 3 High Street',
    zone: 'Mohandessin',
    location: { latitude: 30.060400, longitude: 31.249700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mohandessin.',
  },
  {
    id: 'node-cai-8-1',
    name: 'Downtown Cairo Sector 1 High Street',
    zone: 'Downtown Cairo',
    location: { latitude: 30.066400, longitude: 31.253700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Cairo.',
  },
  {
    id: 'node-cai-8-2',
    name: 'Downtown Cairo Sector 2 High Street',
    zone: 'Downtown Cairo',
    location: { latitude: 30.069400, longitude: 31.256700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Cairo.',
  },
  {
    id: 'node-cai-8-3',
    name: 'Downtown Cairo Sector 3 High Street',
    zone: 'Downtown Cairo',
    location: { latitude: 30.072400, longitude: 31.259700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Cairo.',
  },
  {
    id: 'node-cai-9-1',
    name: 'Sheikh Zayed City Sector 1 High Street',
    zone: 'Sheikh Zayed City',
    location: { latitude: 30.078400, longitude: 31.263700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sheikh Zayed City.',
  },
  {
    id: 'node-cai-9-2',
    name: 'Sheikh Zayed City Sector 2 High Street',
    zone: 'Sheikh Zayed City',
    location: { latitude: 30.081400, longitude: 31.266700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sheikh Zayed City.',
  },
  {
    id: 'node-cai-9-3',
    name: 'Sheikh Zayed City Sector 3 High Street',
    zone: 'Sheikh Zayed City',
    location: { latitude: 30.084400, longitude: 31.269700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sheikh Zayed City.',
  },
  {
    id: 'node-cai-10-1',
    name: 'Garden City Sector 1 High Street',
    zone: 'Garden City',
    location: { latitude: 30.090400, longitude: 31.273700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Garden City.',
  },
  {
    id: 'node-cai-10-2',
    name: 'Garden City Sector 2 High Street',
    zone: 'Garden City',
    location: { latitude: 30.093400, longitude: 31.276700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Garden City.',
  },
  {
    id: 'node-cai-10-3',
    name: 'Garden City Sector 3 High Street',
    zone: 'Garden City',
    location: { latitude: 30.096400, longitude: 31.279700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Garden City.',
  },
];

export const CAIRO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-cai-1',
    fromNodeId: 'node-cai-1-1',
    toNodeId: 'node-cai-1-2',
    roadName: 'Zamalek Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-2',
    fromNodeId: 'node-cai-1-2',
    toNodeId: 'node-cai-1-3',
    roadName: 'Zamalek Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-3',
    fromNodeId: 'node-cai-2-1',
    toNodeId: 'node-cai-2-2',
    roadName: 'Maadi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-4',
    fromNodeId: 'node-cai-2-2',
    toNodeId: 'node-cai-2-3',
    roadName: 'Maadi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-5',
    fromNodeId: 'node-cai-3-1',
    toNodeId: 'node-cai-3-2',
    roadName: 'New Cairo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-6',
    fromNodeId: 'node-cai-3-2',
    toNodeId: 'node-cai-3-3',
    roadName: 'New Cairo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-7',
    fromNodeId: 'node-cai-4-1',
    toNodeId: 'node-cai-4-2',
    roadName: 'Heliopolis Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-8',
    fromNodeId: 'node-cai-4-2',
    toNodeId: 'node-cai-4-3',
    roadName: 'Heliopolis Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-9',
    fromNodeId: 'node-cai-5-1',
    toNodeId: 'node-cai-5-2',
    roadName: 'Nasr City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-10',
    fromNodeId: 'node-cai-5-2',
    toNodeId: 'node-cai-5-3',
    roadName: 'Nasr City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-11',
    fromNodeId: 'node-cai-6-1',
    toNodeId: 'node-cai-6-2',
    roadName: 'Dokki Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-12',
    fromNodeId: 'node-cai-6-2',
    toNodeId: 'node-cai-6-3',
    roadName: 'Dokki Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-13',
    fromNodeId: 'node-cai-7-1',
    toNodeId: 'node-cai-7-2',
    roadName: 'Mohandessin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-14',
    fromNodeId: 'node-cai-7-2',
    toNodeId: 'node-cai-7-3',
    roadName: 'Mohandessin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-15',
    fromNodeId: 'node-cai-8-1',
    toNodeId: 'node-cai-8-2',
    roadName: 'Downtown Cairo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-16',
    fromNodeId: 'node-cai-8-2',
    toNodeId: 'node-cai-8-3',
    roadName: 'Downtown Cairo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-17',
    fromNodeId: 'node-cai-9-1',
    toNodeId: 'node-cai-9-2',
    roadName: 'Sheikh Zayed City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-18',
    fromNodeId: 'node-cai-9-2',
    toNodeId: 'node-cai-9-3',
    roadName: 'Sheikh Zayed City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-19',
    fromNodeId: 'node-cai-10-1',
    toNodeId: 'node-cai-10-2',
    roadName: 'Garden City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cai-20',
    fromNodeId: 'node-cai-10-2',
    toNodeId: 'node-cai-10-3',
    roadName: 'Garden City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
