/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Kozhikode Malabar Food Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const CALICUT_BASE_COORDINATE: GeoCoordinate = {
  latitude: 11.2588,
  longitude: 75.7804,
};

export const CALICUT_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-cal-1-1',
    name: 'Mavoor Road Sector 1 High Street',
    zone: 'Mavoor Road',
    location: { latitude: 11.196800, longitude: 75.728400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mavoor Road.',
  },
  {
    id: 'node-cal-1-2',
    name: 'Mavoor Road Sector 2 High Street',
    zone: 'Mavoor Road',
    location: { latitude: 11.199800, longitude: 75.731400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mavoor Road.',
  },
  {
    id: 'node-cal-1-3',
    name: 'Mavoor Road Sector 3 High Street',
    zone: 'Mavoor Road',
    location: { latitude: 11.202800, longitude: 75.734400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mavoor Road.',
  },
  {
    id: 'node-cal-2-1',
    name: 'Beach Road Sector 1 High Street',
    zone: 'Beach Road',
    location: { latitude: 11.208800, longitude: 75.738400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Beach Road.',
  },
  {
    id: 'node-cal-2-2',
    name: 'Beach Road Sector 2 High Street',
    zone: 'Beach Road',
    location: { latitude: 11.211800, longitude: 75.741400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Beach Road.',
  },
  {
    id: 'node-cal-2-3',
    name: 'Beach Road Sector 3 High Street',
    zone: 'Beach Road',
    location: { latitude: 11.214800, longitude: 75.744400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Beach Road.',
  },
  {
    id: 'node-cal-3-1',
    name: 'PT Usha Road Sector 1 High Street',
    zone: 'PT Usha Road',
    location: { latitude: 11.220800, longitude: 75.748400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in PT Usha Road.',
  },
  {
    id: 'node-cal-3-2',
    name: 'PT Usha Road Sector 2 High Street',
    zone: 'PT Usha Road',
    location: { latitude: 11.223800, longitude: 75.751400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in PT Usha Road.',
  },
  {
    id: 'node-cal-3-3',
    name: 'PT Usha Road Sector 3 High Street',
    zone: 'PT Usha Road',
    location: { latitude: 11.226800, longitude: 75.754400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in PT Usha Road.',
  },
  {
    id: 'node-cal-4-1',
    name: 'Nadakkavu Sector 1 High Street',
    zone: 'Nadakkavu',
    location: { latitude: 11.232800, longitude: 75.758400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nadakkavu.',
  },
  {
    id: 'node-cal-4-2',
    name: 'Nadakkavu Sector 2 High Street',
    zone: 'Nadakkavu',
    location: { latitude: 11.235800, longitude: 75.761400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nadakkavu.',
  },
  {
    id: 'node-cal-4-3',
    name: 'Nadakkavu Sector 3 High Street',
    zone: 'Nadakkavu',
    location: { latitude: 11.238800, longitude: 75.764400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nadakkavu.',
  },
  {
    id: 'node-cal-5-1',
    name: 'Vellayil Sector 1 High Street',
    zone: 'Vellayil',
    location: { latitude: 11.244800, longitude: 75.768400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vellayil.',
  },
  {
    id: 'node-cal-5-2',
    name: 'Vellayil Sector 2 High Street',
    zone: 'Vellayil',
    location: { latitude: 11.247800, longitude: 75.771400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vellayil.',
  },
  {
    id: 'node-cal-5-3',
    name: 'Vellayil Sector 3 High Street',
    zone: 'Vellayil',
    location: { latitude: 11.250800, longitude: 75.774400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vellayil.',
  },
  {
    id: 'node-cal-6-1',
    name: 'Thondayad Bypass Sector 1 High Street',
    zone: 'Thondayad Bypass',
    location: { latitude: 11.256800, longitude: 75.778400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Thondayad Bypass.',
  },
  {
    id: 'node-cal-6-2',
    name: 'Thondayad Bypass Sector 2 High Street',
    zone: 'Thondayad Bypass',
    location: { latitude: 11.259800, longitude: 75.781400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Thondayad Bypass.',
  },
  {
    id: 'node-cal-6-3',
    name: 'Thondayad Bypass Sector 3 High Street',
    zone: 'Thondayad Bypass',
    location: { latitude: 11.262800, longitude: 75.784400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Thondayad Bypass.',
  },
  {
    id: 'node-cal-7-1',
    name: 'Cyberpark Sector 1 High Street',
    zone: 'Cyberpark',
    location: { latitude: 11.268800, longitude: 75.788400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cyberpark.',
  },
  {
    id: 'node-cal-7-2',
    name: 'Cyberpark Sector 2 High Street',
    zone: 'Cyberpark',
    location: { latitude: 11.271800, longitude: 75.791400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cyberpark.',
  },
  {
    id: 'node-cal-7-3',
    name: 'Cyberpark Sector 3 High Street',
    zone: 'Cyberpark',
    location: { latitude: 11.274800, longitude: 75.794400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cyberpark.',
  },
  {
    id: 'node-cal-8-1',
    name: 'Kallai Sector 1 High Street',
    zone: 'Kallai',
    location: { latitude: 11.280800, longitude: 75.798400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kallai.',
  },
  {
    id: 'node-cal-8-2',
    name: 'Kallai Sector 2 High Street',
    zone: 'Kallai',
    location: { latitude: 11.283800, longitude: 75.801400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kallai.',
  },
  {
    id: 'node-cal-8-3',
    name: 'Kallai Sector 3 High Street',
    zone: 'Kallai',
    location: { latitude: 11.286800, longitude: 75.804400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kallai.',
  },
  {
    id: 'node-cal-9-1',
    name: 'West Hill Sector 1 High Street',
    zone: 'West Hill',
    location: { latitude: 11.292800, longitude: 75.808400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in West Hill.',
  },
  {
    id: 'node-cal-9-2',
    name: 'West Hill Sector 2 High Street',
    zone: 'West Hill',
    location: { latitude: 11.295800, longitude: 75.811400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in West Hill.',
  },
  {
    id: 'node-cal-9-3',
    name: 'West Hill Sector 3 High Street',
    zone: 'West Hill',
    location: { latitude: 11.298800, longitude: 75.814400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in West Hill.',
  },
  {
    id: 'node-cal-10-1',
    name: 'Eranhikkal Sector 1 High Street',
    zone: 'Eranhikkal',
    location: { latitude: 11.304800, longitude: 75.818400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Eranhikkal.',
  },
  {
    id: 'node-cal-10-2',
    name: 'Eranhikkal Sector 2 High Street',
    zone: 'Eranhikkal',
    location: { latitude: 11.307800, longitude: 75.821400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Eranhikkal.',
  },
  {
    id: 'node-cal-10-3',
    name: 'Eranhikkal Sector 3 High Street',
    zone: 'Eranhikkal',
    location: { latitude: 11.310800, longitude: 75.824400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Eranhikkal.',
  },
];

export const CALICUT_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-cal-1',
    fromNodeId: 'node-cal-1-1',
    toNodeId: 'node-cal-1-2',
    roadName: 'Mavoor Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-2',
    fromNodeId: 'node-cal-1-2',
    toNodeId: 'node-cal-1-3',
    roadName: 'Mavoor Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-3',
    fromNodeId: 'node-cal-2-1',
    toNodeId: 'node-cal-2-2',
    roadName: 'Beach Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-4',
    fromNodeId: 'node-cal-2-2',
    toNodeId: 'node-cal-2-3',
    roadName: 'Beach Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-5',
    fromNodeId: 'node-cal-3-1',
    toNodeId: 'node-cal-3-2',
    roadName: 'PT Usha Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-6',
    fromNodeId: 'node-cal-3-2',
    toNodeId: 'node-cal-3-3',
    roadName: 'PT Usha Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-7',
    fromNodeId: 'node-cal-4-1',
    toNodeId: 'node-cal-4-2',
    roadName: 'Nadakkavu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-8',
    fromNodeId: 'node-cal-4-2',
    toNodeId: 'node-cal-4-3',
    roadName: 'Nadakkavu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-9',
    fromNodeId: 'node-cal-5-1',
    toNodeId: 'node-cal-5-2',
    roadName: 'Vellayil Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-10',
    fromNodeId: 'node-cal-5-2',
    toNodeId: 'node-cal-5-3',
    roadName: 'Vellayil Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-11',
    fromNodeId: 'node-cal-6-1',
    toNodeId: 'node-cal-6-2',
    roadName: 'Thondayad Bypass Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-12',
    fromNodeId: 'node-cal-6-2',
    toNodeId: 'node-cal-6-3',
    roadName: 'Thondayad Bypass Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-13',
    fromNodeId: 'node-cal-7-1',
    toNodeId: 'node-cal-7-2',
    roadName: 'Cyberpark Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-14',
    fromNodeId: 'node-cal-7-2',
    toNodeId: 'node-cal-7-3',
    roadName: 'Cyberpark Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-15',
    fromNodeId: 'node-cal-8-1',
    toNodeId: 'node-cal-8-2',
    roadName: 'Kallai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-16',
    fromNodeId: 'node-cal-8-2',
    toNodeId: 'node-cal-8-3',
    roadName: 'Kallai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-17',
    fromNodeId: 'node-cal-9-1',
    toNodeId: 'node-cal-9-2',
    roadName: 'West Hill Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-18',
    fromNodeId: 'node-cal-9-2',
    toNodeId: 'node-cal-9-3',
    roadName: 'West Hill Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-19',
    fromNodeId: 'node-cal-10-1',
    toNodeId: 'node-cal-10-2',
    roadName: 'Eranhikkal Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cal-20',
    fromNodeId: 'node-cal-10-2',
    toNodeId: 'node-cal-10-3',
    roadName: 'Eranhikkal Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
