/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Cebu City Queen City of South
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const CEBU_BASE_COORDINATE: GeoCoordinate = {
  latitude: 10.3157,
  longitude: 123.8854,
};

export const CEBU_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ceb-1-1',
    name: 'Cebu IT Park Sector 1 High Street',
    zone: 'Cebu IT Park',
    location: { latitude: 10.253700, longitude: 123.833400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cebu IT Park.',
  },
  {
    id: 'node-ceb-1-2',
    name: 'Cebu IT Park Sector 2 High Street',
    zone: 'Cebu IT Park',
    location: { latitude: 10.256700, longitude: 123.836400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cebu IT Park.',
  },
  {
    id: 'node-ceb-1-3',
    name: 'Cebu IT Park Sector 3 High Street',
    zone: 'Cebu IT Park',
    location: { latitude: 10.259700, longitude: 123.839400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cebu IT Park.',
  },
  {
    id: 'node-ceb-2-1',
    name: 'Cebu Business Park Sector 1 High Street',
    zone: 'Cebu Business Park',
    location: { latitude: 10.265700, longitude: 123.843400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cebu Business Park.',
  },
  {
    id: 'node-ceb-2-2',
    name: 'Cebu Business Park Sector 2 High Street',
    zone: 'Cebu Business Park',
    location: { latitude: 10.268700, longitude: 123.846400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cebu Business Park.',
  },
  {
    id: 'node-ceb-2-3',
    name: 'Cebu Business Park Sector 3 High Street',
    zone: 'Cebu Business Park',
    location: { latitude: 10.271700, longitude: 123.849400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cebu Business Park.',
  },
  {
    id: 'node-ceb-3-1',
    name: 'Fuente Osmeña Sector 1 High Street',
    zone: 'Fuente Osmeña',
    location: { latitude: 10.277700, longitude: 123.853400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fuente Osmeña.',
  },
  {
    id: 'node-ceb-3-2',
    name: 'Fuente Osmeña Sector 2 High Street',
    zone: 'Fuente Osmeña',
    location: { latitude: 10.280700, longitude: 123.856400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fuente Osmeña.',
  },
  {
    id: 'node-ceb-3-3',
    name: 'Fuente Osmeña Sector 3 High Street',
    zone: 'Fuente Osmeña',
    location: { latitude: 10.283700, longitude: 123.859400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fuente Osmeña.',
  },
  {
    id: 'node-ceb-4-1',
    name: 'Lahug Sector 1 High Street',
    zone: 'Lahug',
    location: { latitude: 10.289700, longitude: 123.863400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lahug.',
  },
  {
    id: 'node-ceb-4-2',
    name: 'Lahug Sector 2 High Street',
    zone: 'Lahug',
    location: { latitude: 10.292700, longitude: 123.866400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lahug.',
  },
  {
    id: 'node-ceb-4-3',
    name: 'Lahug Sector 3 High Street',
    zone: 'Lahug',
    location: { latitude: 10.295700, longitude: 123.869400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lahug.',
  },
  {
    id: 'node-ceb-5-1',
    name: 'Banilad Sector 1 High Street',
    zone: 'Banilad',
    location: { latitude: 10.301700, longitude: 123.873400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Banilad.',
  },
  {
    id: 'node-ceb-5-2',
    name: 'Banilad Sector 2 High Street',
    zone: 'Banilad',
    location: { latitude: 10.304700, longitude: 123.876400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Banilad.',
  },
  {
    id: 'node-ceb-5-3',
    name: 'Banilad Sector 3 High Street',
    zone: 'Banilad',
    location: { latitude: 10.307700, longitude: 123.879400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Banilad.',
  },
  {
    id: 'node-ceb-6-1',
    name: 'Mabolo Sector 1 High Street',
    zone: 'Mabolo',
    location: { latitude: 10.313700, longitude: 123.883400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mabolo.',
  },
  {
    id: 'node-ceb-6-2',
    name: 'Mabolo Sector 2 High Street',
    zone: 'Mabolo',
    location: { latitude: 10.316700, longitude: 123.886400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mabolo.',
  },
  {
    id: 'node-ceb-6-3',
    name: 'Mabolo Sector 3 High Street',
    zone: 'Mabolo',
    location: { latitude: 10.319700, longitude: 123.889400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mabolo.',
  },
  {
    id: 'node-ceb-7-1',
    name: 'Capitol Site Sector 1 High Street',
    zone: 'Capitol Site',
    location: { latitude: 10.325700, longitude: 123.893400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Capitol Site.',
  },
  {
    id: 'node-ceb-7-2',
    name: 'Capitol Site Sector 2 High Street',
    zone: 'Capitol Site',
    location: { latitude: 10.328700, longitude: 123.896400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Capitol Site.',
  },
  {
    id: 'node-ceb-7-3',
    name: 'Capitol Site Sector 3 High Street',
    zone: 'Capitol Site',
    location: { latitude: 10.331700, longitude: 123.899400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Capitol Site.',
  },
  {
    id: 'node-ceb-8-1',
    name: 'Talamban Sector 1 High Street',
    zone: 'Talamban',
    location: { latitude: 10.337700, longitude: 123.903400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Talamban.',
  },
  {
    id: 'node-ceb-8-2',
    name: 'Talamban Sector 2 High Street',
    zone: 'Talamban',
    location: { latitude: 10.340700, longitude: 123.906400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Talamban.',
  },
  {
    id: 'node-ceb-8-3',
    name: 'Talamban Sector 3 High Street',
    zone: 'Talamban',
    location: { latitude: 10.343700, longitude: 123.909400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Talamban.',
  },
  {
    id: 'node-ceb-9-1',
    name: 'Guadalupe Cebu Sector 1 High Street',
    zone: 'Guadalupe Cebu',
    location: { latitude: 10.349700, longitude: 123.913400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Guadalupe Cebu.',
  },
  {
    id: 'node-ceb-9-2',
    name: 'Guadalupe Cebu Sector 2 High Street',
    zone: 'Guadalupe Cebu',
    location: { latitude: 10.352700, longitude: 123.916400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Guadalupe Cebu.',
  },
  {
    id: 'node-ceb-9-3',
    name: 'Guadalupe Cebu Sector 3 High Street',
    zone: 'Guadalupe Cebu',
    location: { latitude: 10.355700, longitude: 123.919400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Guadalupe Cebu.',
  },
  {
    id: 'node-ceb-10-1',
    name: 'Colon Sector 1 High Street',
    zone: 'Colon',
    location: { latitude: 10.361700, longitude: 123.923400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Colon.',
  },
  {
    id: 'node-ceb-10-2',
    name: 'Colon Sector 2 High Street',
    zone: 'Colon',
    location: { latitude: 10.364700, longitude: 123.926400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Colon.',
  },
  {
    id: 'node-ceb-10-3',
    name: 'Colon Sector 3 High Street',
    zone: 'Colon',
    location: { latitude: 10.367700, longitude: 123.929400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Colon.',
  },
];

export const CEBU_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ceb-1',
    fromNodeId: 'node-ceb-1-1',
    toNodeId: 'node-ceb-1-2',
    roadName: 'Cebu IT Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-2',
    fromNodeId: 'node-ceb-1-2',
    toNodeId: 'node-ceb-1-3',
    roadName: 'Cebu IT Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-3',
    fromNodeId: 'node-ceb-2-1',
    toNodeId: 'node-ceb-2-2',
    roadName: 'Cebu Business Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-4',
    fromNodeId: 'node-ceb-2-2',
    toNodeId: 'node-ceb-2-3',
    roadName: 'Cebu Business Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-5',
    fromNodeId: 'node-ceb-3-1',
    toNodeId: 'node-ceb-3-2',
    roadName: 'Fuente Osmeña Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-6',
    fromNodeId: 'node-ceb-3-2',
    toNodeId: 'node-ceb-3-3',
    roadName: 'Fuente Osmeña Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-7',
    fromNodeId: 'node-ceb-4-1',
    toNodeId: 'node-ceb-4-2',
    roadName: 'Lahug Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-8',
    fromNodeId: 'node-ceb-4-2',
    toNodeId: 'node-ceb-4-3',
    roadName: 'Lahug Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-9',
    fromNodeId: 'node-ceb-5-1',
    toNodeId: 'node-ceb-5-2',
    roadName: 'Banilad Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-10',
    fromNodeId: 'node-ceb-5-2',
    toNodeId: 'node-ceb-5-3',
    roadName: 'Banilad Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-11',
    fromNodeId: 'node-ceb-6-1',
    toNodeId: 'node-ceb-6-2',
    roadName: 'Mabolo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-12',
    fromNodeId: 'node-ceb-6-2',
    toNodeId: 'node-ceb-6-3',
    roadName: 'Mabolo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-13',
    fromNodeId: 'node-ceb-7-1',
    toNodeId: 'node-ceb-7-2',
    roadName: 'Capitol Site Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-14',
    fromNodeId: 'node-ceb-7-2',
    toNodeId: 'node-ceb-7-3',
    roadName: 'Capitol Site Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-15',
    fromNodeId: 'node-ceb-8-1',
    toNodeId: 'node-ceb-8-2',
    roadName: 'Talamban Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-16',
    fromNodeId: 'node-ceb-8-2',
    toNodeId: 'node-ceb-8-3',
    roadName: 'Talamban Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-17',
    fromNodeId: 'node-ceb-9-1',
    toNodeId: 'node-ceb-9-2',
    roadName: 'Guadalupe Cebu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-18',
    fromNodeId: 'node-ceb-9-2',
    toNodeId: 'node-ceb-9-3',
    roadName: 'Guadalupe Cebu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-19',
    fromNodeId: 'node-ceb-10-1',
    toNodeId: 'node-ceb-10-2',
    roadName: 'Colon Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ceb-20',
    fromNodeId: 'node-ceb-10-2',
    toNodeId: 'node-ceb-10-3',
    roadName: 'Colon Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
