/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Chandigarh Tricity Capital Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const CHANDIGARH_BASE_COORDINATE: GeoCoordinate = {
  latitude: 30.7333,
  longitude: 76.7794,
};

export const CHANDIGARH_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-cha-1-1',
    name: 'Sector 17 Sector 1 High Street',
    zone: 'Sector 17',
    location: { latitude: 30.671300, longitude: 76.727400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sector 17.',
  },
  {
    id: 'node-cha-1-2',
    name: 'Sector 17 Sector 2 High Street',
    zone: 'Sector 17',
    location: { latitude: 30.674300, longitude: 76.730400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sector 17.',
  },
  {
    id: 'node-cha-1-3',
    name: 'Sector 17 Sector 3 High Street',
    zone: 'Sector 17',
    location: { latitude: 30.677300, longitude: 76.733400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sector 17.',
  },
  {
    id: 'node-cha-2-1',
    name: 'Sector 35 Sector 1 High Street',
    zone: 'Sector 35',
    location: { latitude: 30.683300, longitude: 76.737400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sector 35.',
  },
  {
    id: 'node-cha-2-2',
    name: 'Sector 35 Sector 2 High Street',
    zone: 'Sector 35',
    location: { latitude: 30.686300, longitude: 76.740400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sector 35.',
  },
  {
    id: 'node-cha-2-3',
    name: 'Sector 35 Sector 3 High Street',
    zone: 'Sector 35',
    location: { latitude: 30.689300, longitude: 76.743400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sector 35.',
  },
  {
    id: 'node-cha-3-1',
    name: 'Sector 26 Sector 1 High Street',
    zone: 'Sector 26',
    location: { latitude: 30.695300, longitude: 76.747400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sector 26.',
  },
  {
    id: 'node-cha-3-2',
    name: 'Sector 26 Sector 2 High Street',
    zone: 'Sector 26',
    location: { latitude: 30.698300, longitude: 76.750400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sector 26.',
  },
  {
    id: 'node-cha-3-3',
    name: 'Sector 26 Sector 3 High Street',
    zone: 'Sector 26',
    location: { latitude: 30.701300, longitude: 76.753400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sector 26.',
  },
  {
    id: 'node-cha-4-1',
    name: 'Sector 8 Sector 1 High Street',
    zone: 'Sector 8',
    location: { latitude: 30.707300, longitude: 76.757400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sector 8.',
  },
  {
    id: 'node-cha-4-2',
    name: 'Sector 8 Sector 2 High Street',
    zone: 'Sector 8',
    location: { latitude: 30.710300, longitude: 76.760400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sector 8.',
  },
  {
    id: 'node-cha-4-3',
    name: 'Sector 8 Sector 3 High Street',
    zone: 'Sector 8',
    location: { latitude: 30.713300, longitude: 76.763400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sector 8.',
  },
  {
    id: 'node-cha-5-1',
    name: 'Sector 9 Sector 1 High Street',
    zone: 'Sector 9',
    location: { latitude: 30.719300, longitude: 76.767400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sector 9.',
  },
  {
    id: 'node-cha-5-2',
    name: 'Sector 9 Sector 2 High Street',
    zone: 'Sector 9',
    location: { latitude: 30.722300, longitude: 76.770400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sector 9.',
  },
  {
    id: 'node-cha-5-3',
    name: 'Sector 9 Sector 3 High Street',
    zone: 'Sector 9',
    location: { latitude: 30.725300, longitude: 76.773400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sector 9.',
  },
  {
    id: 'node-cha-6-1',
    name: 'Mohali Phase 7 Sector 1 High Street',
    zone: 'Mohali Phase 7',
    location: { latitude: 30.731300, longitude: 76.777400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mohali Phase 7.',
  },
  {
    id: 'node-cha-6-2',
    name: 'Mohali Phase 7 Sector 2 High Street',
    zone: 'Mohali Phase 7',
    location: { latitude: 30.734300, longitude: 76.780400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mohali Phase 7.',
  },
  {
    id: 'node-cha-6-3',
    name: 'Mohali Phase 7 Sector 3 High Street',
    zone: 'Mohali Phase 7',
    location: { latitude: 30.737300, longitude: 76.783400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mohali Phase 7.',
  },
  {
    id: 'node-cha-7-1',
    name: 'Mohali Phase 3B2 Sector 1 High Street',
    zone: 'Mohali Phase 3B2',
    location: { latitude: 30.743300, longitude: 76.787400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mohali Phase 3B2.',
  },
  {
    id: 'node-cha-7-2',
    name: 'Mohali Phase 3B2 Sector 2 High Street',
    zone: 'Mohali Phase 3B2',
    location: { latitude: 30.746300, longitude: 76.790400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mohali Phase 3B2.',
  },
  {
    id: 'node-cha-7-3',
    name: 'Mohali Phase 3B2 Sector 3 High Street',
    zone: 'Mohali Phase 3B2',
    location: { latitude: 30.749300, longitude: 76.793400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mohali Phase 3B2.',
  },
  {
    id: 'node-cha-8-1',
    name: 'Panchkula Sector 8 Sector 1 High Street',
    zone: 'Panchkula Sector 8',
    location: { latitude: 30.755300, longitude: 76.797400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Panchkula Sector 8.',
  },
  {
    id: 'node-cha-8-2',
    name: 'Panchkula Sector 8 Sector 2 High Street',
    zone: 'Panchkula Sector 8',
    location: { latitude: 30.758300, longitude: 76.800400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Panchkula Sector 8.',
  },
  {
    id: 'node-cha-8-3',
    name: 'Panchkula Sector 8 Sector 3 High Street',
    zone: 'Panchkula Sector 8',
    location: { latitude: 30.761300, longitude: 76.803400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Panchkula Sector 8.',
  },
  {
    id: 'node-cha-9-1',
    name: 'Panchkula Sector 20 Sector 1 High Street',
    zone: 'Panchkula Sector 20',
    location: { latitude: 30.767300, longitude: 76.807400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Panchkula Sector 20.',
  },
  {
    id: 'node-cha-9-2',
    name: 'Panchkula Sector 20 Sector 2 High Street',
    zone: 'Panchkula Sector 20',
    location: { latitude: 30.770300, longitude: 76.810400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Panchkula Sector 20.',
  },
  {
    id: 'node-cha-9-3',
    name: 'Panchkula Sector 20 Sector 3 High Street',
    zone: 'Panchkula Sector 20',
    location: { latitude: 30.773300, longitude: 76.813400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Panchkula Sector 20.',
  },
  {
    id: 'node-cha-10-1',
    name: 'Zirakpur Hub Sector 1 High Street',
    zone: 'Zirakpur Hub',
    location: { latitude: 30.779300, longitude: 76.817400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zirakpur Hub.',
  },
  {
    id: 'node-cha-10-2',
    name: 'Zirakpur Hub Sector 2 High Street',
    zone: 'Zirakpur Hub',
    location: { latitude: 30.782300, longitude: 76.820400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zirakpur Hub.',
  },
  {
    id: 'node-cha-10-3',
    name: 'Zirakpur Hub Sector 3 High Street',
    zone: 'Zirakpur Hub',
    location: { latitude: 30.785300, longitude: 76.823400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zirakpur Hub.',
  },
];

export const CHANDIGARH_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-cha-1',
    fromNodeId: 'node-cha-1-1',
    toNodeId: 'node-cha-1-2',
    roadName: 'Sector 17 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-2',
    fromNodeId: 'node-cha-1-2',
    toNodeId: 'node-cha-1-3',
    roadName: 'Sector 17 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-3',
    fromNodeId: 'node-cha-2-1',
    toNodeId: 'node-cha-2-2',
    roadName: 'Sector 35 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-4',
    fromNodeId: 'node-cha-2-2',
    toNodeId: 'node-cha-2-3',
    roadName: 'Sector 35 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-5',
    fromNodeId: 'node-cha-3-1',
    toNodeId: 'node-cha-3-2',
    roadName: 'Sector 26 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-6',
    fromNodeId: 'node-cha-3-2',
    toNodeId: 'node-cha-3-3',
    roadName: 'Sector 26 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-7',
    fromNodeId: 'node-cha-4-1',
    toNodeId: 'node-cha-4-2',
    roadName: 'Sector 8 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-8',
    fromNodeId: 'node-cha-4-2',
    toNodeId: 'node-cha-4-3',
    roadName: 'Sector 8 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-9',
    fromNodeId: 'node-cha-5-1',
    toNodeId: 'node-cha-5-2',
    roadName: 'Sector 9 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-10',
    fromNodeId: 'node-cha-5-2',
    toNodeId: 'node-cha-5-3',
    roadName: 'Sector 9 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-11',
    fromNodeId: 'node-cha-6-1',
    toNodeId: 'node-cha-6-2',
    roadName: 'Mohali Phase 7 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-12',
    fromNodeId: 'node-cha-6-2',
    toNodeId: 'node-cha-6-3',
    roadName: 'Mohali Phase 7 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-13',
    fromNodeId: 'node-cha-7-1',
    toNodeId: 'node-cha-7-2',
    roadName: 'Mohali Phase 3B2 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-14',
    fromNodeId: 'node-cha-7-2',
    toNodeId: 'node-cha-7-3',
    roadName: 'Mohali Phase 3B2 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-15',
    fromNodeId: 'node-cha-8-1',
    toNodeId: 'node-cha-8-2',
    roadName: 'Panchkula Sector 8 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-16',
    fromNodeId: 'node-cha-8-2',
    toNodeId: 'node-cha-8-3',
    roadName: 'Panchkula Sector 8 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-17',
    fromNodeId: 'node-cha-9-1',
    toNodeId: 'node-cha-9-2',
    roadName: 'Panchkula Sector 20 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-18',
    fromNodeId: 'node-cha-9-2',
    toNodeId: 'node-cha-9-3',
    roadName: 'Panchkula Sector 20 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-19',
    fromNodeId: 'node-cha-10-1',
    toNodeId: 'node-cha-10-2',
    roadName: 'Zirakpur Hub Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-20',
    fromNodeId: 'node-cha-10-2',
    toNodeId: 'node-cha-10-3',
    roadName: 'Zirakpur Hub Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
