/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Charlotte Queen City Uptown
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const CHARLOTTE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 35.2271,
  longitude: -80.8431,
};

export const CHARLOTTE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-cha-1-1',
    name: 'Uptown Charlotte Sector 1 High Street',
    zone: 'Uptown Charlotte',
    location: { latitude: 35.165100, longitude: -80.895100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Uptown Charlotte.',
  },
  {
    id: 'node-cha-1-2',
    name: 'Uptown Charlotte Sector 2 High Street',
    zone: 'Uptown Charlotte',
    location: { latitude: 35.168100, longitude: -80.892100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Uptown Charlotte.',
  },
  {
    id: 'node-cha-1-3',
    name: 'Uptown Charlotte Sector 3 High Street',
    zone: 'Uptown Charlotte',
    location: { latitude: 35.171100, longitude: -80.889100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Uptown Charlotte.',
  },
  {
    id: 'node-cha-2-1',
    name: 'South End Charlotte Sector 1 High Street',
    zone: 'South End Charlotte',
    location: { latitude: 35.177100, longitude: -80.885100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in South End Charlotte.',
  },
  {
    id: 'node-cha-2-2',
    name: 'South End Charlotte Sector 2 High Street',
    zone: 'South End Charlotte',
    location: { latitude: 35.180100, longitude: -80.882100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in South End Charlotte.',
  },
  {
    id: 'node-cha-2-3',
    name: 'South End Charlotte Sector 3 High Street',
    zone: 'South End Charlotte',
    location: { latitude: 35.183100, longitude: -80.879100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in South End Charlotte.',
  },
  {
    id: 'node-cha-3-1',
    name: 'NoDa Arts Sector 1 High Street',
    zone: 'NoDa Arts',
    location: { latitude: 35.189100, longitude: -80.875100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in NoDa Arts.',
  },
  {
    id: 'node-cha-3-2',
    name: 'NoDa Arts Sector 2 High Street',
    zone: 'NoDa Arts',
    location: { latitude: 35.192100, longitude: -80.872100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in NoDa Arts.',
  },
  {
    id: 'node-cha-3-3',
    name: 'NoDa Arts Sector 3 High Street',
    zone: 'NoDa Arts',
    location: { latitude: 35.195100, longitude: -80.869100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in NoDa Arts.',
  },
  {
    id: 'node-cha-4-1',
    name: 'Plaza Midwood Sector 1 High Street',
    zone: 'Plaza Midwood',
    location: { latitude: 35.201100, longitude: -80.865100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Plaza Midwood.',
  },
  {
    id: 'node-cha-4-2',
    name: 'Plaza Midwood Sector 2 High Street',
    zone: 'Plaza Midwood',
    location: { latitude: 35.204100, longitude: -80.862100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Plaza Midwood.',
  },
  {
    id: 'node-cha-4-3',
    name: 'Plaza Midwood Sector 3 High Street',
    zone: 'Plaza Midwood',
    location: { latitude: 35.207100, longitude: -80.859100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Plaza Midwood.',
  },
  {
    id: 'node-cha-5-1',
    name: 'Dilworth Sector 1 High Street',
    zone: 'Dilworth',
    location: { latitude: 35.213100, longitude: -80.855100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dilworth.',
  },
  {
    id: 'node-cha-5-2',
    name: 'Dilworth Sector 2 High Street',
    zone: 'Dilworth',
    location: { latitude: 35.216100, longitude: -80.852100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dilworth.',
  },
  {
    id: 'node-cha-5-3',
    name: 'Dilworth Sector 3 High Street',
    zone: 'Dilworth',
    location: { latitude: 35.219100, longitude: -80.849100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dilworth.',
  },
  {
    id: 'node-cha-6-1',
    name: 'Ballantyne Sector 1 High Street',
    zone: 'Ballantyne',
    location: { latitude: 35.225100, longitude: -80.845100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ballantyne.',
  },
  {
    id: 'node-cha-6-2',
    name: 'Ballantyne Sector 2 High Street',
    zone: 'Ballantyne',
    location: { latitude: 35.228100, longitude: -80.842100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ballantyne.',
  },
  {
    id: 'node-cha-6-3',
    name: 'Ballantyne Sector 3 High Street',
    zone: 'Ballantyne',
    location: { latitude: 35.231100, longitude: -80.839100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ballantyne.',
  },
  {
    id: 'node-cha-7-1',
    name: 'Myers Park Sector 1 High Street',
    zone: 'Myers Park',
    location: { latitude: 35.237100, longitude: -80.835100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Myers Park.',
  },
  {
    id: 'node-cha-7-2',
    name: 'Myers Park Sector 2 High Street',
    zone: 'Myers Park',
    location: { latitude: 35.240100, longitude: -80.832100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Myers Park.',
  },
  {
    id: 'node-cha-7-3',
    name: 'Myers Park Sector 3 High Street',
    zone: 'Myers Park',
    location: { latitude: 35.243100, longitude: -80.829100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Myers Park.',
  },
  {
    id: 'node-cha-8-1',
    name: 'Elizabeth Charlotte Sector 1 High Street',
    zone: 'Elizabeth Charlotte',
    location: { latitude: 35.249100, longitude: -80.825100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Elizabeth Charlotte.',
  },
  {
    id: 'node-cha-8-2',
    name: 'Elizabeth Charlotte Sector 2 High Street',
    zone: 'Elizabeth Charlotte',
    location: { latitude: 35.252100, longitude: -80.822100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Elizabeth Charlotte.',
  },
  {
    id: 'node-cha-8-3',
    name: 'Elizabeth Charlotte Sector 3 High Street',
    zone: 'Elizabeth Charlotte',
    location: { latitude: 35.255100, longitude: -80.819100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Elizabeth Charlotte.',
  },
  {
    id: 'node-cha-9-1',
    name: 'SouthPark Sector 1 High Street',
    zone: 'SouthPark',
    location: { latitude: 35.261100, longitude: -80.815100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in SouthPark.',
  },
  {
    id: 'node-cha-9-2',
    name: 'SouthPark Sector 2 High Street',
    zone: 'SouthPark',
    location: { latitude: 35.264100, longitude: -80.812100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in SouthPark.',
  },
  {
    id: 'node-cha-9-3',
    name: 'SouthPark Sector 3 High Street',
    zone: 'SouthPark',
    location: { latitude: 35.267100, longitude: -80.809100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in SouthPark.',
  },
  {
    id: 'node-cha-10-1',
    name: 'University City Charlotte Sector 1 High Street',
    zone: 'University City Charlotte',
    location: { latitude: 35.273100, longitude: -80.805100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in University City Charlotte.',
  },
  {
    id: 'node-cha-10-2',
    name: 'University City Charlotte Sector 2 High Street',
    zone: 'University City Charlotte',
    location: { latitude: 35.276100, longitude: -80.802100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in University City Charlotte.',
  },
  {
    id: 'node-cha-10-3',
    name: 'University City Charlotte Sector 3 High Street',
    zone: 'University City Charlotte',
    location: { latitude: 35.279100, longitude: -80.799100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in University City Charlotte.',
  },
];

export const CHARLOTTE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-cha-1',
    fromNodeId: 'node-cha-1-1',
    toNodeId: 'node-cha-1-2',
    roadName: 'Uptown Charlotte Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-2',
    fromNodeId: 'node-cha-1-2',
    toNodeId: 'node-cha-1-3',
    roadName: 'Uptown Charlotte Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-3',
    fromNodeId: 'node-cha-2-1',
    toNodeId: 'node-cha-2-2',
    roadName: 'South End Charlotte Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-4',
    fromNodeId: 'node-cha-2-2',
    toNodeId: 'node-cha-2-3',
    roadName: 'South End Charlotte Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-5',
    fromNodeId: 'node-cha-3-1',
    toNodeId: 'node-cha-3-2',
    roadName: 'NoDa Arts Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-6',
    fromNodeId: 'node-cha-3-2',
    toNodeId: 'node-cha-3-3',
    roadName: 'NoDa Arts Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-7',
    fromNodeId: 'node-cha-4-1',
    toNodeId: 'node-cha-4-2',
    roadName: 'Plaza Midwood Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-8',
    fromNodeId: 'node-cha-4-2',
    toNodeId: 'node-cha-4-3',
    roadName: 'Plaza Midwood Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-9',
    fromNodeId: 'node-cha-5-1',
    toNodeId: 'node-cha-5-2',
    roadName: 'Dilworth Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-10',
    fromNodeId: 'node-cha-5-2',
    toNodeId: 'node-cha-5-3',
    roadName: 'Dilworth Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-11',
    fromNodeId: 'node-cha-6-1',
    toNodeId: 'node-cha-6-2',
    roadName: 'Ballantyne Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-12',
    fromNodeId: 'node-cha-6-2',
    toNodeId: 'node-cha-6-3',
    roadName: 'Ballantyne Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-13',
    fromNodeId: 'node-cha-7-1',
    toNodeId: 'node-cha-7-2',
    roadName: 'Myers Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-14',
    fromNodeId: 'node-cha-7-2',
    toNodeId: 'node-cha-7-3',
    roadName: 'Myers Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-15',
    fromNodeId: 'node-cha-8-1',
    toNodeId: 'node-cha-8-2',
    roadName: 'Elizabeth Charlotte Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-16',
    fromNodeId: 'node-cha-8-2',
    toNodeId: 'node-cha-8-3',
    roadName: 'Elizabeth Charlotte Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-17',
    fromNodeId: 'node-cha-9-1',
    toNodeId: 'node-cha-9-2',
    roadName: 'SouthPark Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-18',
    fromNodeId: 'node-cha-9-2',
    toNodeId: 'node-cha-9-3',
    roadName: 'SouthPark Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-19',
    fromNodeId: 'node-cha-10-1',
    toNodeId: 'node-cha-10-2',
    roadName: 'University City Charlotte Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cha-20',
    fromNodeId: 'node-cha-10-2',
    toNodeId: 'node-cha-10-3',
    roadName: 'University City Charlotte Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
