/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Chennai Metropolitan Area
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const CHENNAI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 13.0827,
  longitude: 80.2707,
};

export const CHENNAI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-che-1-1',
    name: 'Nungambakkam Sector 1 Road',
    zone: 'Nungambakkam',
    location: { latitude: 13.010700, longitude: 80.218700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Nungambakkam commercial centers and residential communities.',
  },
  {
    id: 'node-che-1-2',
    name: 'Nungambakkam Sector 2 Road',
    zone: 'Nungambakkam',
    location: { latitude: 13.013700, longitude: 80.221700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Nungambakkam commercial centers and residential communities.',
  },
  {
    id: 'node-che-1-3',
    name: 'Nungambakkam Sector 3 Road',
    zone: 'Nungambakkam',
    location: { latitude: 13.016700, longitude: 80.224700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Nungambakkam commercial centers and residential communities.',
  },
  {
    id: 'node-che-2-1',
    name: 'Anna Nagar Sector 1 Road',
    zone: 'Anna Nagar',
    location: { latitude: 13.025700, longitude: 80.230700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Anna Nagar commercial centers and residential communities.',
  },
  {
    id: 'node-che-2-2',
    name: 'Anna Nagar Sector 2 Road',
    zone: 'Anna Nagar',
    location: { latitude: 13.028700, longitude: 80.233700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Anna Nagar commercial centers and residential communities.',
  },
  {
    id: 'node-che-2-3',
    name: 'Anna Nagar Sector 3 Road',
    zone: 'Anna Nagar',
    location: { latitude: 13.031700, longitude: 80.236700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Anna Nagar commercial centers and residential communities.',
  },
  {
    id: 'node-che-3-1',
    name: 'T Nagar Sector 1 Road',
    zone: 'T Nagar',
    location: { latitude: 13.040700, longitude: 80.242700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting T Nagar commercial centers and residential communities.',
  },
  {
    id: 'node-che-3-2',
    name: 'T Nagar Sector 2 Road',
    zone: 'T Nagar',
    location: { latitude: 13.043700, longitude: 80.245700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting T Nagar commercial centers and residential communities.',
  },
  {
    id: 'node-che-3-3',
    name: 'T Nagar Sector 3 Road',
    zone: 'T Nagar',
    location: { latitude: 13.046700, longitude: 80.248700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting T Nagar commercial centers and residential communities.',
  },
  {
    id: 'node-che-4-1',
    name: 'Adyar Sector 1 Road',
    zone: 'Adyar',
    location: { latitude: 13.055700, longitude: 80.254700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Adyar commercial centers and residential communities.',
  },
  {
    id: 'node-che-4-2',
    name: 'Adyar Sector 2 Road',
    zone: 'Adyar',
    location: { latitude: 13.058700, longitude: 80.257700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Adyar commercial centers and residential communities.',
  },
  {
    id: 'node-che-4-3',
    name: 'Adyar Sector 3 Road',
    zone: 'Adyar',
    location: { latitude: 13.061700, longitude: 80.260700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Adyar commercial centers and residential communities.',
  },
  {
    id: 'node-che-5-1',
    name: 'Besant Nagar Sector 1 Road',
    zone: 'Besant Nagar',
    location: { latitude: 13.070700, longitude: 80.266700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Besant Nagar commercial centers and residential communities.',
  },
  {
    id: 'node-che-5-2',
    name: 'Besant Nagar Sector 2 Road',
    zone: 'Besant Nagar',
    location: { latitude: 13.073700, longitude: 80.269700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Besant Nagar commercial centers and residential communities.',
  },
  {
    id: 'node-che-5-3',
    name: 'Besant Nagar Sector 3 Road',
    zone: 'Besant Nagar',
    location: { latitude: 13.076700, longitude: 80.272700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Besant Nagar commercial centers and residential communities.',
  },
  {
    id: 'node-che-6-1',
    name: 'Alwarpet Sector 1 Road',
    zone: 'Alwarpet',
    location: { latitude: 13.085700, longitude: 80.278700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Alwarpet commercial centers and residential communities.',
  },
  {
    id: 'node-che-6-2',
    name: 'Alwarpet Sector 2 Road',
    zone: 'Alwarpet',
    location: { latitude: 13.088700, longitude: 80.281700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Alwarpet commercial centers and residential communities.',
  },
  {
    id: 'node-che-6-3',
    name: 'Alwarpet Sector 3 Road',
    zone: 'Alwarpet',
    location: { latitude: 13.091700, longitude: 80.284700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Alwarpet commercial centers and residential communities.',
  },
  {
    id: 'node-che-7-1',
    name: 'OMR Tech Corridor Sector 1 Road',
    zone: 'OMR Tech Corridor',
    location: { latitude: 13.100700, longitude: 80.290700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting OMR Tech Corridor commercial centers and residential communities.',
  },
  {
    id: 'node-che-7-2',
    name: 'OMR Tech Corridor Sector 2 Road',
    zone: 'OMR Tech Corridor',
    location: { latitude: 13.103700, longitude: 80.293700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting OMR Tech Corridor commercial centers and residential communities.',
  },
  {
    id: 'node-che-7-3',
    name: 'OMR Tech Corridor Sector 3 Road',
    zone: 'OMR Tech Corridor',
    location: { latitude: 13.106700, longitude: 80.296700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting OMR Tech Corridor commercial centers and residential communities.',
  },
  {
    id: 'node-che-8-1',
    name: 'Velachery Sector 1 Road',
    zone: 'Velachery',
    location: { latitude: 13.115700, longitude: 80.302700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Velachery commercial centers and residential communities.',
  },
  {
    id: 'node-che-8-2',
    name: 'Velachery Sector 2 Road',
    zone: 'Velachery',
    location: { latitude: 13.118700, longitude: 80.305700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Velachery commercial centers and residential communities.',
  },
  {
    id: 'node-che-8-3',
    name: 'Velachery Sector 3 Road',
    zone: 'Velachery',
    location: { latitude: 13.121700, longitude: 80.308700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Velachery commercial centers and residential communities.',
  },
  {
    id: 'node-che-9-1',
    name: 'Mylapore Sector 1 Road',
    zone: 'Mylapore',
    location: { latitude: 13.130700, longitude: 80.314700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Mylapore commercial centers and residential communities.',
  },
  {
    id: 'node-che-9-2',
    name: 'Mylapore Sector 2 Road',
    zone: 'Mylapore',
    location: { latitude: 13.133700, longitude: 80.317700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Mylapore commercial centers and residential communities.',
  },
  {
    id: 'node-che-9-3',
    name: 'Mylapore Sector 3 Road',
    zone: 'Mylapore',
    location: { latitude: 13.136700, longitude: 80.320700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Mylapore commercial centers and residential communities.',
  },
  {
    id: 'node-che-10-1',
    name: 'Kilpauk Sector 1 Road',
    zone: 'Kilpauk',
    location: { latitude: 13.145700, longitude: 80.326700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Kilpauk commercial centers and residential communities.',
  },
  {
    id: 'node-che-10-2',
    name: 'Kilpauk Sector 2 Road',
    zone: 'Kilpauk',
    location: { latitude: 13.148700, longitude: 80.329700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Kilpauk commercial centers and residential communities.',
  },
  {
    id: 'node-che-10-3',
    name: 'Kilpauk Sector 3 Road',
    zone: 'Kilpauk',
    location: { latitude: 13.151700, longitude: 80.332700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Kilpauk commercial centers and residential communities.',
  },
];

export const CHENNAI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-che-1',
    fromNodeId: 'node-che-1-1',
    toNodeId: 'node-che-1-2',
    roadName: 'Nungambakkam Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-2',
    fromNodeId: 'node-che-1-2',
    toNodeId: 'node-che-1-3',
    roadName: 'Nungambakkam Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-3',
    fromNodeId: 'node-che-2-1',
    toNodeId: 'node-che-2-2',
    roadName: 'Anna Nagar Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-4',
    fromNodeId: 'node-che-2-2',
    toNodeId: 'node-che-2-3',
    roadName: 'Anna Nagar Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-5',
    fromNodeId: 'node-che-3-1',
    toNodeId: 'node-che-3-2',
    roadName: 'T Nagar Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-6',
    fromNodeId: 'node-che-3-2',
    toNodeId: 'node-che-3-3',
    roadName: 'T Nagar Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-7',
    fromNodeId: 'node-che-4-1',
    toNodeId: 'node-che-4-2',
    roadName: 'Adyar Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-8',
    fromNodeId: 'node-che-4-2',
    toNodeId: 'node-che-4-3',
    roadName: 'Adyar Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-9',
    fromNodeId: 'node-che-5-1',
    toNodeId: 'node-che-5-2',
    roadName: 'Besant Nagar Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-10',
    fromNodeId: 'node-che-5-2',
    toNodeId: 'node-che-5-3',
    roadName: 'Besant Nagar Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-11',
    fromNodeId: 'node-che-6-1',
    toNodeId: 'node-che-6-2',
    roadName: 'Alwarpet Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-12',
    fromNodeId: 'node-che-6-2',
    toNodeId: 'node-che-6-3',
    roadName: 'Alwarpet Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-13',
    fromNodeId: 'node-che-7-1',
    toNodeId: 'node-che-7-2',
    roadName: 'OMR Tech Corridor Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-14',
    fromNodeId: 'node-che-7-2',
    toNodeId: 'node-che-7-3',
    roadName: 'OMR Tech Corridor Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-15',
    fromNodeId: 'node-che-8-1',
    toNodeId: 'node-che-8-2',
    roadName: 'Velachery Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-16',
    fromNodeId: 'node-che-8-2',
    toNodeId: 'node-che-8-3',
    roadName: 'Velachery Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-17',
    fromNodeId: 'node-che-9-1',
    toNodeId: 'node-che-9-2',
    roadName: 'Mylapore Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-18',
    fromNodeId: 'node-che-9-2',
    toNodeId: 'node-che-9-3',
    roadName: 'Mylapore Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-19',
    fromNodeId: 'node-che-10-1',
    toNodeId: 'node-che-10-2',
    roadName: 'Kilpauk Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-che-20',
    fromNodeId: 'node-che-10-2',
    toNodeId: 'node-che-10-3',
    roadName: 'Kilpauk Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
