/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Chiang Mai Lanna Culinary Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const CHIANGMAI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 18.7883,
  longitude: 98.9853,
};

export const CHIANGMAI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-chi-1-1',
    name: 'Nimman Road Sector 1 High Street',
    zone: 'Nimman Road',
    location: { latitude: 18.726300, longitude: 98.933300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nimman Road.',
  },
  {
    id: 'node-chi-1-2',
    name: 'Nimman Road Sector 2 High Street',
    zone: 'Nimman Road',
    location: { latitude: 18.729300, longitude: 98.936300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nimman Road.',
  },
  {
    id: 'node-chi-1-3',
    name: 'Nimman Road Sector 3 High Street',
    zone: 'Nimman Road',
    location: { latitude: 18.732300, longitude: 98.939300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nimman Road.',
  },
  {
    id: 'node-chi-2-1',
    name: 'Old City Chiang Mai Sector 1 High Street',
    zone: 'Old City Chiang Mai',
    location: { latitude: 18.738300, longitude: 98.943300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old City Chiang Mai.',
  },
  {
    id: 'node-chi-2-2',
    name: 'Old City Chiang Mai Sector 2 High Street',
    zone: 'Old City Chiang Mai',
    location: { latitude: 18.741300, longitude: 98.946300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old City Chiang Mai.',
  },
  {
    id: 'node-chi-2-3',
    name: 'Old City Chiang Mai Sector 3 High Street',
    zone: 'Old City Chiang Mai',
    location: { latitude: 18.744300, longitude: 98.949300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old City Chiang Mai.',
  },
  {
    id: 'node-chi-3-1',
    name: 'Riverside Sector 1 High Street',
    zone: 'Riverside',
    location: { latitude: 18.750300, longitude: 98.953300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Riverside.',
  },
  {
    id: 'node-chi-3-2',
    name: 'Riverside Sector 2 High Street',
    zone: 'Riverside',
    location: { latitude: 18.753300, longitude: 98.956300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Riverside.',
  },
  {
    id: 'node-chi-3-3',
    name: 'Riverside Sector 3 High Street',
    zone: 'Riverside',
    location: { latitude: 18.756300, longitude: 98.959300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Riverside.',
  },
  {
    id: 'node-chi-4-1',
    name: 'Night Bazaar Sector 1 High Street',
    zone: 'Night Bazaar',
    location: { latitude: 18.762300, longitude: 98.963300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Night Bazaar.',
  },
  {
    id: 'node-chi-4-2',
    name: 'Night Bazaar Sector 2 High Street',
    zone: 'Night Bazaar',
    location: { latitude: 18.765300, longitude: 98.966300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Night Bazaar.',
  },
  {
    id: 'node-chi-4-3',
    name: 'Night Bazaar Sector 3 High Street',
    zone: 'Night Bazaar',
    location: { latitude: 18.768300, longitude: 98.969300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Night Bazaar.',
  },
  {
    id: 'node-chi-5-1',
    name: 'Santitham Sector 1 High Street',
    zone: 'Santitham',
    location: { latitude: 18.774300, longitude: 98.973300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Santitham.',
  },
  {
    id: 'node-chi-5-2',
    name: 'Santitham Sector 2 High Street',
    zone: 'Santitham',
    location: { latitude: 18.777300, longitude: 98.976300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Santitham.',
  },
  {
    id: 'node-chi-5-3',
    name: 'Santitham Sector 3 High Street',
    zone: 'Santitham',
    location: { latitude: 18.780300, longitude: 98.979300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Santitham.',
  },
  {
    id: 'node-chi-6-1',
    name: 'Chang Klan Sector 1 High Street',
    zone: 'Chang Klan',
    location: { latitude: 18.786300, longitude: 98.983300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chang Klan.',
  },
  {
    id: 'node-chi-6-2',
    name: 'Chang Klan Sector 2 High Street',
    zone: 'Chang Klan',
    location: { latitude: 18.789300, longitude: 98.986300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chang Klan.',
  },
  {
    id: 'node-chi-6-3',
    name: 'Chang Klan Sector 3 High Street',
    zone: 'Chang Klan',
    location: { latitude: 18.792300, longitude: 98.989300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chang Klan.',
  },
  {
    id: 'node-chi-7-1',
    name: 'Wat Ket Sector 1 High Street',
    zone: 'Wat Ket',
    location: { latitude: 18.798300, longitude: 98.993300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wat Ket.',
  },
  {
    id: 'node-chi-7-2',
    name: 'Wat Ket Sector 2 High Street',
    zone: 'Wat Ket',
    location: { latitude: 18.801300, longitude: 98.996300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wat Ket.',
  },
  {
    id: 'node-chi-7-3',
    name: 'Wat Ket Sector 3 High Street',
    zone: 'Wat Ket',
    location: { latitude: 18.804300, longitude: 98.999300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wat Ket.',
  },
  {
    id: 'node-chi-8-1',
    name: 'Mae Hia Sector 1 High Street',
    zone: 'Mae Hia',
    location: { latitude: 18.810300, longitude: 99.003300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mae Hia.',
  },
  {
    id: 'node-chi-8-2',
    name: 'Mae Hia Sector 2 High Street',
    zone: 'Mae Hia',
    location: { latitude: 18.813300, longitude: 99.006300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mae Hia.',
  },
  {
    id: 'node-chi-8-3',
    name: 'Mae Hia Sector 3 High Street',
    zone: 'Mae Hia',
    location: { latitude: 18.816300, longitude: 99.009300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mae Hia.',
  },
  {
    id: 'node-chi-9-1',
    name: 'Hang Dong Sector 1 High Street',
    zone: 'Hang Dong',
    location: { latitude: 18.822300, longitude: 99.013300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hang Dong.',
  },
  {
    id: 'node-chi-9-2',
    name: 'Hang Dong Sector 2 High Street',
    zone: 'Hang Dong',
    location: { latitude: 18.825300, longitude: 99.016300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hang Dong.',
  },
  {
    id: 'node-chi-9-3',
    name: 'Hang Dong Sector 3 High Street',
    zone: 'Hang Dong',
    location: { latitude: 18.828300, longitude: 99.019300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hang Dong.',
  },
  {
    id: 'node-chi-10-1',
    name: 'San Sai Sector 1 High Street',
    zone: 'San Sai',
    location: { latitude: 18.834300, longitude: 99.023300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Sai.',
  },
  {
    id: 'node-chi-10-2',
    name: 'San Sai Sector 2 High Street',
    zone: 'San Sai',
    location: { latitude: 18.837300, longitude: 99.026300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Sai.',
  },
  {
    id: 'node-chi-10-3',
    name: 'San Sai Sector 3 High Street',
    zone: 'San Sai',
    location: { latitude: 18.840300, longitude: 99.029300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Sai.',
  },
];

export const CHIANGMAI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-chi-1',
    fromNodeId: 'node-chi-1-1',
    toNodeId: 'node-chi-1-2',
    roadName: 'Nimman Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-2',
    fromNodeId: 'node-chi-1-2',
    toNodeId: 'node-chi-1-3',
    roadName: 'Nimman Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-3',
    fromNodeId: 'node-chi-2-1',
    toNodeId: 'node-chi-2-2',
    roadName: 'Old City Chiang Mai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-4',
    fromNodeId: 'node-chi-2-2',
    toNodeId: 'node-chi-2-3',
    roadName: 'Old City Chiang Mai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-5',
    fromNodeId: 'node-chi-3-1',
    toNodeId: 'node-chi-3-2',
    roadName: 'Riverside Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-6',
    fromNodeId: 'node-chi-3-2',
    toNodeId: 'node-chi-3-3',
    roadName: 'Riverside Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-7',
    fromNodeId: 'node-chi-4-1',
    toNodeId: 'node-chi-4-2',
    roadName: 'Night Bazaar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-8',
    fromNodeId: 'node-chi-4-2',
    toNodeId: 'node-chi-4-3',
    roadName: 'Night Bazaar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-9',
    fromNodeId: 'node-chi-5-1',
    toNodeId: 'node-chi-5-2',
    roadName: 'Santitham Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-10',
    fromNodeId: 'node-chi-5-2',
    toNodeId: 'node-chi-5-3',
    roadName: 'Santitham Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-11',
    fromNodeId: 'node-chi-6-1',
    toNodeId: 'node-chi-6-2',
    roadName: 'Chang Klan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-12',
    fromNodeId: 'node-chi-6-2',
    toNodeId: 'node-chi-6-3',
    roadName: 'Chang Klan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-13',
    fromNodeId: 'node-chi-7-1',
    toNodeId: 'node-chi-7-2',
    roadName: 'Wat Ket Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-14',
    fromNodeId: 'node-chi-7-2',
    toNodeId: 'node-chi-7-3',
    roadName: 'Wat Ket Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-15',
    fromNodeId: 'node-chi-8-1',
    toNodeId: 'node-chi-8-2',
    roadName: 'Mae Hia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-16',
    fromNodeId: 'node-chi-8-2',
    toNodeId: 'node-chi-8-3',
    roadName: 'Mae Hia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-17',
    fromNodeId: 'node-chi-9-1',
    toNodeId: 'node-chi-9-2',
    roadName: 'Hang Dong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-18',
    fromNodeId: 'node-chi-9-2',
    toNodeId: 'node-chi-9-3',
    roadName: 'Hang Dong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-19',
    fromNodeId: 'node-chi-10-1',
    toNodeId: 'node-chi-10-2',
    roadName: 'San Sai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-20',
    fromNodeId: 'node-chi-10-2',
    toNodeId: 'node-chi-10-3',
    roadName: 'San Sai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
