/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Chicago Loop & River North
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const CHICAGO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 41.8781,
  longitude: -87.6298,
};

export const CHICAGO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-chi-1-1',
    name: 'The Loop Sector 1 High Street',
    zone: 'The Loop',
    location: { latitude: 41.816100, longitude: -87.681800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in The Loop.',
  },
  {
    id: 'node-chi-1-2',
    name: 'The Loop Sector 2 High Street',
    zone: 'The Loop',
    location: { latitude: 41.819100, longitude: -87.678800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in The Loop.',
  },
  {
    id: 'node-chi-1-3',
    name: 'The Loop Sector 3 High Street',
    zone: 'The Loop',
    location: { latitude: 41.822100, longitude: -87.675800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in The Loop.',
  },
  {
    id: 'node-chi-2-1',
    name: 'River North Sector 1 High Street',
    zone: 'River North',
    location: { latitude: 41.828100, longitude: -87.671800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in River North.',
  },
  {
    id: 'node-chi-2-2',
    name: 'River North Sector 2 High Street',
    zone: 'River North',
    location: { latitude: 41.831100, longitude: -87.668800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in River North.',
  },
  {
    id: 'node-chi-2-3',
    name: 'River North Sector 3 High Street',
    zone: 'River North',
    location: { latitude: 41.834100, longitude: -87.665800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in River North.',
  },
  {
    id: 'node-chi-3-1',
    name: 'West Loop Sector 1 High Street',
    zone: 'West Loop',
    location: { latitude: 41.840100, longitude: -87.661800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in West Loop.',
  },
  {
    id: 'node-chi-3-2',
    name: 'West Loop Sector 2 High Street',
    zone: 'West Loop',
    location: { latitude: 41.843100, longitude: -87.658800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in West Loop.',
  },
  {
    id: 'node-chi-3-3',
    name: 'West Loop Sector 3 High Street',
    zone: 'West Loop',
    location: { latitude: 41.846100, longitude: -87.655800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in West Loop.',
  },
  {
    id: 'node-chi-4-1',
    name: 'Lincoln Park Sector 1 High Street',
    zone: 'Lincoln Park',
    location: { latitude: 41.852100, longitude: -87.651800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lincoln Park.',
  },
  {
    id: 'node-chi-4-2',
    name: 'Lincoln Park Sector 2 High Street',
    zone: 'Lincoln Park',
    location: { latitude: 41.855100, longitude: -87.648800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lincoln Park.',
  },
  {
    id: 'node-chi-4-3',
    name: 'Lincoln Park Sector 3 High Street',
    zone: 'Lincoln Park',
    location: { latitude: 41.858100, longitude: -87.645800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lincoln Park.',
  },
  {
    id: 'node-chi-5-1',
    name: 'Wicker Park Sector 1 High Street',
    zone: 'Wicker Park',
    location: { latitude: 41.864100, longitude: -87.641800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wicker Park.',
  },
  {
    id: 'node-chi-5-2',
    name: 'Wicker Park Sector 2 High Street',
    zone: 'Wicker Park',
    location: { latitude: 41.867100, longitude: -87.638800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wicker Park.',
  },
  {
    id: 'node-chi-5-3',
    name: 'Wicker Park Sector 3 High Street',
    zone: 'Wicker Park',
    location: { latitude: 41.870100, longitude: -87.635800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wicker Park.',
  },
  {
    id: 'node-chi-6-1',
    name: 'Lakeview Sector 1 High Street',
    zone: 'Lakeview',
    location: { latitude: 41.876100, longitude: -87.631800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lakeview.',
  },
  {
    id: 'node-chi-6-2',
    name: 'Lakeview Sector 2 High Street',
    zone: 'Lakeview',
    location: { latitude: 41.879100, longitude: -87.628800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lakeview.',
  },
  {
    id: 'node-chi-6-3',
    name: 'Lakeview Sector 3 High Street',
    zone: 'Lakeview',
    location: { latitude: 41.882100, longitude: -87.625800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lakeview.',
  },
  {
    id: 'node-chi-7-1',
    name: 'Logan Square Sector 1 High Street',
    zone: 'Logan Square',
    location: { latitude: 41.888100, longitude: -87.621800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Logan Square.',
  },
  {
    id: 'node-chi-7-2',
    name: 'Logan Square Sector 2 High Street',
    zone: 'Logan Square',
    location: { latitude: 41.891100, longitude: -87.618800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Logan Square.',
  },
  {
    id: 'node-chi-7-3',
    name: 'Logan Square Sector 3 High Street',
    zone: 'Logan Square',
    location: { latitude: 41.894100, longitude: -87.615800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Logan Square.',
  },
  {
    id: 'node-chi-8-1',
    name: 'Fulton Market Sector 1 High Street',
    zone: 'Fulton Market',
    location: { latitude: 41.900100, longitude: -87.611800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fulton Market.',
  },
  {
    id: 'node-chi-8-2',
    name: 'Fulton Market Sector 2 High Street',
    zone: 'Fulton Market',
    location: { latitude: 41.903100, longitude: -87.608800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fulton Market.',
  },
  {
    id: 'node-chi-8-3',
    name: 'Fulton Market Sector 3 High Street',
    zone: 'Fulton Market',
    location: { latitude: 41.906100, longitude: -87.605800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fulton Market.',
  },
  {
    id: 'node-chi-9-1',
    name: 'Gold Coast Sector 1 High Street',
    zone: 'Gold Coast',
    location: { latitude: 41.912100, longitude: -87.601800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gold Coast.',
  },
  {
    id: 'node-chi-9-2',
    name: 'Gold Coast Sector 2 High Street',
    zone: 'Gold Coast',
    location: { latitude: 41.915100, longitude: -87.598800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gold Coast.',
  },
  {
    id: 'node-chi-9-3',
    name: 'Gold Coast Sector 3 High Street',
    zone: 'Gold Coast',
    location: { latitude: 41.918100, longitude: -87.595800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gold Coast.',
  },
  {
    id: 'node-chi-10-1',
    name: 'Hyde Park Sector 1 High Street',
    zone: 'Hyde Park',
    location: { latitude: 41.924100, longitude: -87.591800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park.',
  },
  {
    id: 'node-chi-10-2',
    name: 'Hyde Park Sector 2 High Street',
    zone: 'Hyde Park',
    location: { latitude: 41.927100, longitude: -87.588800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park.',
  },
  {
    id: 'node-chi-10-3',
    name: 'Hyde Park Sector 3 High Street',
    zone: 'Hyde Park',
    location: { latitude: 41.930100, longitude: -87.585800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park.',
  },
];

export const CHICAGO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-chi-1',
    fromNodeId: 'node-chi-1-1',
    toNodeId: 'node-chi-1-2',
    roadName: 'The Loop Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-2',
    fromNodeId: 'node-chi-1-2',
    toNodeId: 'node-chi-1-3',
    roadName: 'The Loop Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-3',
    fromNodeId: 'node-chi-2-1',
    toNodeId: 'node-chi-2-2',
    roadName: 'River North Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-4',
    fromNodeId: 'node-chi-2-2',
    toNodeId: 'node-chi-2-3',
    roadName: 'River North Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-5',
    fromNodeId: 'node-chi-3-1',
    toNodeId: 'node-chi-3-2',
    roadName: 'West Loop Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-6',
    fromNodeId: 'node-chi-3-2',
    toNodeId: 'node-chi-3-3',
    roadName: 'West Loop Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-7',
    fromNodeId: 'node-chi-4-1',
    toNodeId: 'node-chi-4-2',
    roadName: 'Lincoln Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-8',
    fromNodeId: 'node-chi-4-2',
    toNodeId: 'node-chi-4-3',
    roadName: 'Lincoln Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-9',
    fromNodeId: 'node-chi-5-1',
    toNodeId: 'node-chi-5-2',
    roadName: 'Wicker Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-10',
    fromNodeId: 'node-chi-5-2',
    toNodeId: 'node-chi-5-3',
    roadName: 'Wicker Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-11',
    fromNodeId: 'node-chi-6-1',
    toNodeId: 'node-chi-6-2',
    roadName: 'Lakeview Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-12',
    fromNodeId: 'node-chi-6-2',
    toNodeId: 'node-chi-6-3',
    roadName: 'Lakeview Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-13',
    fromNodeId: 'node-chi-7-1',
    toNodeId: 'node-chi-7-2',
    roadName: 'Logan Square Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-14',
    fromNodeId: 'node-chi-7-2',
    toNodeId: 'node-chi-7-3',
    roadName: 'Logan Square Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-15',
    fromNodeId: 'node-chi-8-1',
    toNodeId: 'node-chi-8-2',
    roadName: 'Fulton Market Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-16',
    fromNodeId: 'node-chi-8-2',
    toNodeId: 'node-chi-8-3',
    roadName: 'Fulton Market Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-17',
    fromNodeId: 'node-chi-9-1',
    toNodeId: 'node-chi-9-2',
    roadName: 'Gold Coast Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-18',
    fromNodeId: 'node-chi-9-2',
    toNodeId: 'node-chi-9-3',
    roadName: 'Gold Coast Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-19',
    fromNodeId: 'node-chi-10-1',
    toNodeId: 'node-chi-10-2',
    roadName: 'Hyde Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-chi-20',
    fromNodeId: 'node-chi-10-2',
    toNodeId: 'node-chi-10-3',
    roadName: 'Hyde Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
