/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Coimbatore Kongu Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const COIMBATORE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 11.0168,
  longitude: 76.9558,
};

export const COIMBATORE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-coi-1-1',
    name: 'RS Puram Sector 1 High Street',
    zone: 'RS Puram',
    location: { latitude: 10.954800, longitude: 76.903800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in RS Puram.',
  },
  {
    id: 'node-coi-1-2',
    name: 'RS Puram Sector 2 High Street',
    zone: 'RS Puram',
    location: { latitude: 10.957800, longitude: 76.906800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in RS Puram.',
  },
  {
    id: 'node-coi-1-3',
    name: 'RS Puram Sector 3 High Street',
    zone: 'RS Puram',
    location: { latitude: 10.960800, longitude: 76.909800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in RS Puram.',
  },
  {
    id: 'node-coi-2-1',
    name: 'Gandhipuram Sector 1 High Street',
    zone: 'Gandhipuram',
    location: { latitude: 10.966800, longitude: 76.913800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gandhipuram.',
  },
  {
    id: 'node-coi-2-2',
    name: 'Gandhipuram Sector 2 High Street',
    zone: 'Gandhipuram',
    location: { latitude: 10.969800, longitude: 76.916800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gandhipuram.',
  },
  {
    id: 'node-coi-2-3',
    name: 'Gandhipuram Sector 3 High Street',
    zone: 'Gandhipuram',
    location: { latitude: 10.972800, longitude: 76.919800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gandhipuram.',
  },
  {
    id: 'node-coi-3-1',
    name: 'Peelamedu Sector 1 High Street',
    zone: 'Peelamedu',
    location: { latitude: 10.978800, longitude: 76.923800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Peelamedu.',
  },
  {
    id: 'node-coi-3-2',
    name: 'Peelamedu Sector 2 High Street',
    zone: 'Peelamedu',
    location: { latitude: 10.981800, longitude: 76.926800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Peelamedu.',
  },
  {
    id: 'node-coi-3-3',
    name: 'Peelamedu Sector 3 High Street',
    zone: 'Peelamedu',
    location: { latitude: 10.984800, longitude: 76.929800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Peelamedu.',
  },
  {
    id: 'node-coi-4-1',
    name: 'Saibaba Colony Sector 1 High Street',
    zone: 'Saibaba Colony',
    location: { latitude: 10.990800, longitude: 76.933800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Saibaba Colony.',
  },
  {
    id: 'node-coi-4-2',
    name: 'Saibaba Colony Sector 2 High Street',
    zone: 'Saibaba Colony',
    location: { latitude: 10.993800, longitude: 76.936800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Saibaba Colony.',
  },
  {
    id: 'node-coi-4-3',
    name: 'Saibaba Colony Sector 3 High Street',
    zone: 'Saibaba Colony',
    location: { latitude: 10.996800, longitude: 76.939800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Saibaba Colony.',
  },
  {
    id: 'node-coi-5-1',
    name: 'Race Course Sector 1 High Street',
    zone: 'Race Course',
    location: { latitude: 11.002800, longitude: 76.943800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Race Course.',
  },
  {
    id: 'node-coi-5-2',
    name: 'Race Course Sector 2 High Street',
    zone: 'Race Course',
    location: { latitude: 11.005800, longitude: 76.946800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Race Course.',
  },
  {
    id: 'node-coi-5-3',
    name: 'Race Course Sector 3 High Street',
    zone: 'Race Course',
    location: { latitude: 11.008800, longitude: 76.949800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Race Course.',
  },
  {
    id: 'node-coi-6-1',
    name: 'Saravanampatti Sector 1 High Street',
    zone: 'Saravanampatti',
    location: { latitude: 11.014800, longitude: 76.953800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Saravanampatti.',
  },
  {
    id: 'node-coi-6-2',
    name: 'Saravanampatti Sector 2 High Street',
    zone: 'Saravanampatti',
    location: { latitude: 11.017800, longitude: 76.956800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Saravanampatti.',
  },
  {
    id: 'node-coi-6-3',
    name: 'Saravanampatti Sector 3 High Street',
    zone: 'Saravanampatti',
    location: { latitude: 11.020800, longitude: 76.959800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Saravanampatti.',
  },
  {
    id: 'node-coi-7-1',
    name: 'Ramanathapuram Sector 1 High Street',
    zone: 'Ramanathapuram',
    location: { latitude: 11.026800, longitude: 76.963800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ramanathapuram.',
  },
  {
    id: 'node-coi-7-2',
    name: 'Ramanathapuram Sector 2 High Street',
    zone: 'Ramanathapuram',
    location: { latitude: 11.029800, longitude: 76.966800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ramanathapuram.',
  },
  {
    id: 'node-coi-7-3',
    name: 'Ramanathapuram Sector 3 High Street',
    zone: 'Ramanathapuram',
    location: { latitude: 11.032800, longitude: 76.969800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ramanathapuram.',
  },
  {
    id: 'node-coi-8-1',
    name: 'Singanallur Sector 1 High Street',
    zone: 'Singanallur',
    location: { latitude: 11.038800, longitude: 76.973800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Singanallur.',
  },
  {
    id: 'node-coi-8-2',
    name: 'Singanallur Sector 2 High Street',
    zone: 'Singanallur',
    location: { latitude: 11.041800, longitude: 76.976800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Singanallur.',
  },
  {
    id: 'node-coi-8-3',
    name: 'Singanallur Sector 3 High Street',
    zone: 'Singanallur',
    location: { latitude: 11.044800, longitude: 76.979800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Singanallur.',
  },
  {
    id: 'node-coi-9-1',
    name: 'Avinashi Road Sector 1 High Street',
    zone: 'Avinashi Road',
    location: { latitude: 11.050800, longitude: 76.983800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Avinashi Road.',
  },
  {
    id: 'node-coi-9-2',
    name: 'Avinashi Road Sector 2 High Street',
    zone: 'Avinashi Road',
    location: { latitude: 11.053800, longitude: 76.986800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Avinashi Road.',
  },
  {
    id: 'node-coi-9-3',
    name: 'Avinashi Road Sector 3 High Street',
    zone: 'Avinashi Road',
    location: { latitude: 11.056800, longitude: 76.989800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Avinashi Road.',
  },
  {
    id: 'node-coi-10-1',
    name: 'Vadavalli Sector 1 High Street',
    zone: 'Vadavalli',
    location: { latitude: 11.062800, longitude: 76.993800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vadavalli.',
  },
  {
    id: 'node-coi-10-2',
    name: 'Vadavalli Sector 2 High Street',
    zone: 'Vadavalli',
    location: { latitude: 11.065800, longitude: 76.996800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vadavalli.',
  },
  {
    id: 'node-coi-10-3',
    name: 'Vadavalli Sector 3 High Street',
    zone: 'Vadavalli',
    location: { latitude: 11.068800, longitude: 76.999800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vadavalli.',
  },
];

export const COIMBATORE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-coi-1',
    fromNodeId: 'node-coi-1-1',
    toNodeId: 'node-coi-1-2',
    roadName: 'RS Puram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-2',
    fromNodeId: 'node-coi-1-2',
    toNodeId: 'node-coi-1-3',
    roadName: 'RS Puram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-3',
    fromNodeId: 'node-coi-2-1',
    toNodeId: 'node-coi-2-2',
    roadName: 'Gandhipuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-4',
    fromNodeId: 'node-coi-2-2',
    toNodeId: 'node-coi-2-3',
    roadName: 'Gandhipuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-5',
    fromNodeId: 'node-coi-3-1',
    toNodeId: 'node-coi-3-2',
    roadName: 'Peelamedu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-6',
    fromNodeId: 'node-coi-3-2',
    toNodeId: 'node-coi-3-3',
    roadName: 'Peelamedu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-7',
    fromNodeId: 'node-coi-4-1',
    toNodeId: 'node-coi-4-2',
    roadName: 'Saibaba Colony Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-8',
    fromNodeId: 'node-coi-4-2',
    toNodeId: 'node-coi-4-3',
    roadName: 'Saibaba Colony Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-9',
    fromNodeId: 'node-coi-5-1',
    toNodeId: 'node-coi-5-2',
    roadName: 'Race Course Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-10',
    fromNodeId: 'node-coi-5-2',
    toNodeId: 'node-coi-5-3',
    roadName: 'Race Course Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-11',
    fromNodeId: 'node-coi-6-1',
    toNodeId: 'node-coi-6-2',
    roadName: 'Saravanampatti Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-12',
    fromNodeId: 'node-coi-6-2',
    toNodeId: 'node-coi-6-3',
    roadName: 'Saravanampatti Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-13',
    fromNodeId: 'node-coi-7-1',
    toNodeId: 'node-coi-7-2',
    roadName: 'Ramanathapuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-14',
    fromNodeId: 'node-coi-7-2',
    toNodeId: 'node-coi-7-3',
    roadName: 'Ramanathapuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-15',
    fromNodeId: 'node-coi-8-1',
    toNodeId: 'node-coi-8-2',
    roadName: 'Singanallur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-16',
    fromNodeId: 'node-coi-8-2',
    toNodeId: 'node-coi-8-3',
    roadName: 'Singanallur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-17',
    fromNodeId: 'node-coi-9-1',
    toNodeId: 'node-coi-9-2',
    roadName: 'Avinashi Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-18',
    fromNodeId: 'node-coi-9-2',
    toNodeId: 'node-coi-9-3',
    roadName: 'Avinashi Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-19',
    fromNodeId: 'node-coi-10-1',
    toNodeId: 'node-coi-10-2',
    roadName: 'Vadavalli Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-coi-20',
    fromNodeId: 'node-coi-10-2',
    toNodeId: 'node-coi-10-3',
    roadName: 'Vadavalli Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
