/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Copenhagen Øresund Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const COPENHAGEN_BASE_COORDINATE: GeoCoordinate = {
  latitude: 55.6761,
  longitude: 12.5683,
};

export const COPENHAGEN_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-cop-1-1',
    name: 'Indre By Sector 1 High Street',
    zone: 'Indre By',
    location: { latitude: 55.614100, longitude: 12.516300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Indre By.',
  },
  {
    id: 'node-cop-1-2',
    name: 'Indre By Sector 2 High Street',
    zone: 'Indre By',
    location: { latitude: 55.617100, longitude: 12.519300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Indre By.',
  },
  {
    id: 'node-cop-1-3',
    name: 'Indre By Sector 3 High Street',
    zone: 'Indre By',
    location: { latitude: 55.620100, longitude: 12.522300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Indre By.',
  },
  {
    id: 'node-cop-2-1',
    name: 'Vesterbro Sector 1 High Street',
    zone: 'Vesterbro',
    location: { latitude: 55.626100, longitude: 12.526300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vesterbro.',
  },
  {
    id: 'node-cop-2-2',
    name: 'Vesterbro Sector 2 High Street',
    zone: 'Vesterbro',
    location: { latitude: 55.629100, longitude: 12.529300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vesterbro.',
  },
  {
    id: 'node-cop-2-3',
    name: 'Vesterbro Sector 3 High Street',
    zone: 'Vesterbro',
    location: { latitude: 55.632100, longitude: 12.532300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vesterbro.',
  },
  {
    id: 'node-cop-3-1',
    name: 'Nørrebro Sector 1 High Street',
    zone: 'Nørrebro',
    location: { latitude: 55.638100, longitude: 12.536300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nørrebro.',
  },
  {
    id: 'node-cop-3-2',
    name: 'Nørrebro Sector 2 High Street',
    zone: 'Nørrebro',
    location: { latitude: 55.641100, longitude: 12.539300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nørrebro.',
  },
  {
    id: 'node-cop-3-3',
    name: 'Nørrebro Sector 3 High Street',
    zone: 'Nørrebro',
    location: { latitude: 55.644100, longitude: 12.542300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nørrebro.',
  },
  {
    id: 'node-cop-4-1',
    name: 'Østerbro Sector 1 High Street',
    zone: 'Østerbro',
    location: { latitude: 55.650100, longitude: 12.546300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Østerbro.',
  },
  {
    id: 'node-cop-4-2',
    name: 'Østerbro Sector 2 High Street',
    zone: 'Østerbro',
    location: { latitude: 55.653100, longitude: 12.549300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Østerbro.',
  },
  {
    id: 'node-cop-4-3',
    name: 'Østerbro Sector 3 High Street',
    zone: 'Østerbro',
    location: { latitude: 55.656100, longitude: 12.552300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Østerbro.',
  },
  {
    id: 'node-cop-5-1',
    name: 'Frederiksberg Sector 1 High Street',
    zone: 'Frederiksberg',
    location: { latitude: 55.662100, longitude: 12.556300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Frederiksberg.',
  },
  {
    id: 'node-cop-5-2',
    name: 'Frederiksberg Sector 2 High Street',
    zone: 'Frederiksberg',
    location: { latitude: 55.665100, longitude: 12.559300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Frederiksberg.',
  },
  {
    id: 'node-cop-5-3',
    name: 'Frederiksberg Sector 3 High Street',
    zone: 'Frederiksberg',
    location: { latitude: 55.668100, longitude: 12.562300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Frederiksberg.',
  },
  {
    id: 'node-cop-6-1',
    name: 'Christianshavn Sector 1 High Street',
    zone: 'Christianshavn',
    location: { latitude: 55.674100, longitude: 12.566300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Christianshavn.',
  },
  {
    id: 'node-cop-6-2',
    name: 'Christianshavn Sector 2 High Street',
    zone: 'Christianshavn',
    location: { latitude: 55.677100, longitude: 12.569300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Christianshavn.',
  },
  {
    id: 'node-cop-6-3',
    name: 'Christianshavn Sector 3 High Street',
    zone: 'Christianshavn',
    location: { latitude: 55.680100, longitude: 12.572300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Christianshavn.',
  },
  {
    id: 'node-cop-7-1',
    name: 'Amager Sector 1 High Street',
    zone: 'Amager',
    location: { latitude: 55.686100, longitude: 12.576300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Amager.',
  },
  {
    id: 'node-cop-7-2',
    name: 'Amager Sector 2 High Street',
    zone: 'Amager',
    location: { latitude: 55.689100, longitude: 12.579300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Amager.',
  },
  {
    id: 'node-cop-7-3',
    name: 'Amager Sector 3 High Street',
    zone: 'Amager',
    location: { latitude: 55.692100, longitude: 12.582300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Amager.',
  },
  {
    id: 'node-cop-8-1',
    name: 'Refshaleøen Sector 1 High Street',
    zone: 'Refshaleøen',
    location: { latitude: 55.698100, longitude: 12.586300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Refshaleøen.',
  },
  {
    id: 'node-cop-8-2',
    name: 'Refshaleøen Sector 2 High Street',
    zone: 'Refshaleøen',
    location: { latitude: 55.701100, longitude: 12.589300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Refshaleøen.',
  },
  {
    id: 'node-cop-8-3',
    name: 'Refshaleøen Sector 3 High Street',
    zone: 'Refshaleøen',
    location: { latitude: 55.704100, longitude: 12.592300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Refshaleøen.',
  },
  {
    id: 'node-cop-9-1',
    name: 'Nordhavn Sector 1 High Street',
    zone: 'Nordhavn',
    location: { latitude: 55.710100, longitude: 12.596300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nordhavn.',
  },
  {
    id: 'node-cop-9-2',
    name: 'Nordhavn Sector 2 High Street',
    zone: 'Nordhavn',
    location: { latitude: 55.713100, longitude: 12.599300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nordhavn.',
  },
  {
    id: 'node-cop-9-3',
    name: 'Nordhavn Sector 3 High Street',
    zone: 'Nordhavn',
    location: { latitude: 55.716100, longitude: 12.602300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nordhavn.',
  },
  {
    id: 'node-cop-10-1',
    name: 'Valby Sector 1 High Street',
    zone: 'Valby',
    location: { latitude: 55.722100, longitude: 12.606300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Valby.',
  },
  {
    id: 'node-cop-10-2',
    name: 'Valby Sector 2 High Street',
    zone: 'Valby',
    location: { latitude: 55.725100, longitude: 12.609300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Valby.',
  },
  {
    id: 'node-cop-10-3',
    name: 'Valby Sector 3 High Street',
    zone: 'Valby',
    location: { latitude: 55.728100, longitude: 12.612300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Valby.',
  },
];

export const COPENHAGEN_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-cop-1',
    fromNodeId: 'node-cop-1-1',
    toNodeId: 'node-cop-1-2',
    roadName: 'Indre By Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-2',
    fromNodeId: 'node-cop-1-2',
    toNodeId: 'node-cop-1-3',
    roadName: 'Indre By Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-3',
    fromNodeId: 'node-cop-2-1',
    toNodeId: 'node-cop-2-2',
    roadName: 'Vesterbro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-4',
    fromNodeId: 'node-cop-2-2',
    toNodeId: 'node-cop-2-3',
    roadName: 'Vesterbro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-5',
    fromNodeId: 'node-cop-3-1',
    toNodeId: 'node-cop-3-2',
    roadName: 'Nørrebro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-6',
    fromNodeId: 'node-cop-3-2',
    toNodeId: 'node-cop-3-3',
    roadName: 'Nørrebro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-7',
    fromNodeId: 'node-cop-4-1',
    toNodeId: 'node-cop-4-2',
    roadName: 'Østerbro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-8',
    fromNodeId: 'node-cop-4-2',
    toNodeId: 'node-cop-4-3',
    roadName: 'Østerbro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-9',
    fromNodeId: 'node-cop-5-1',
    toNodeId: 'node-cop-5-2',
    roadName: 'Frederiksberg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-10',
    fromNodeId: 'node-cop-5-2',
    toNodeId: 'node-cop-5-3',
    roadName: 'Frederiksberg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-11',
    fromNodeId: 'node-cop-6-1',
    toNodeId: 'node-cop-6-2',
    roadName: 'Christianshavn Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-12',
    fromNodeId: 'node-cop-6-2',
    toNodeId: 'node-cop-6-3',
    roadName: 'Christianshavn Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-13',
    fromNodeId: 'node-cop-7-1',
    toNodeId: 'node-cop-7-2',
    roadName: 'Amager Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-14',
    fromNodeId: 'node-cop-7-2',
    toNodeId: 'node-cop-7-3',
    roadName: 'Amager Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-15',
    fromNodeId: 'node-cop-8-1',
    toNodeId: 'node-cop-8-2',
    roadName: 'Refshaleøen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-16',
    fromNodeId: 'node-cop-8-2',
    toNodeId: 'node-cop-8-3',
    roadName: 'Refshaleøen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-17',
    fromNodeId: 'node-cop-9-1',
    toNodeId: 'node-cop-9-2',
    roadName: 'Nordhavn Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-18',
    fromNodeId: 'node-cop-9-2',
    toNodeId: 'node-cop-9-3',
    roadName: 'Nordhavn Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-19',
    fromNodeId: 'node-cop-10-1',
    toNodeId: 'node-cop-10-2',
    roadName: 'Valby Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-cop-20',
    fromNodeId: 'node-cop-10-2',
    toNodeId: 'node-cop-10-3',
    roadName: 'Valby Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
