/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Da Nang Coastal River Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const DANANG_BASE_COORDINATE: GeoCoordinate = {
  latitude: 16.0544,
  longitude: 108.2022,
};

export const DANANG_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-dan-1-1',
    name: 'My Khe Beach Sector 1 High Street',
    zone: 'My Khe Beach',
    location: { latitude: 15.992400, longitude: 108.150200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in My Khe Beach.',
  },
  {
    id: 'node-dan-1-2',
    name: 'My Khe Beach Sector 2 High Street',
    zone: 'My Khe Beach',
    location: { latitude: 15.995400, longitude: 108.153200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in My Khe Beach.',
  },
  {
    id: 'node-dan-1-3',
    name: 'My Khe Beach Sector 3 High Street',
    zone: 'My Khe Beach',
    location: { latitude: 15.998400, longitude: 108.156200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in My Khe Beach.',
  },
  {
    id: 'node-dan-2-1',
    name: 'Han River Waterfront Sector 1 High Street',
    zone: 'Han River Waterfront',
    location: { latitude: 16.004400, longitude: 108.160200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Han River Waterfront.',
  },
  {
    id: 'node-dan-2-2',
    name: 'Han River Waterfront Sector 2 High Street',
    zone: 'Han River Waterfront',
    location: { latitude: 16.007400, longitude: 108.163200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Han River Waterfront.',
  },
  {
    id: 'node-dan-2-3',
    name: 'Han River Waterfront Sector 3 High Street',
    zone: 'Han River Waterfront',
    location: { latitude: 16.010400, longitude: 108.166200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Han River Waterfront.',
  },
  {
    id: 'node-dan-3-1',
    name: 'Hai Chau Sector 1 High Street',
    zone: 'Hai Chau',
    location: { latitude: 16.016400, longitude: 108.170200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hai Chau.',
  },
  {
    id: 'node-dan-3-2',
    name: 'Hai Chau Sector 2 High Street',
    zone: 'Hai Chau',
    location: { latitude: 16.019400, longitude: 108.173200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hai Chau.',
  },
  {
    id: 'node-dan-3-3',
    name: 'Hai Chau Sector 3 High Street',
    zone: 'Hai Chau',
    location: { latitude: 16.022400, longitude: 108.176200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hai Chau.',
  },
  {
    id: 'node-dan-4-1',
    name: 'Son Tra Sector 1 High Street',
    zone: 'Son Tra',
    location: { latitude: 16.028400, longitude: 108.180200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Son Tra.',
  },
  {
    id: 'node-dan-4-2',
    name: 'Son Tra Sector 2 High Street',
    zone: 'Son Tra',
    location: { latitude: 16.031400, longitude: 108.183200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Son Tra.',
  },
  {
    id: 'node-dan-4-3',
    name: 'Son Tra Sector 3 High Street',
    zone: 'Son Tra',
    location: { latitude: 16.034400, longitude: 108.186200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Son Tra.',
  },
  {
    id: 'node-dan-5-1',
    name: 'An Thuong Sector 1 High Street',
    zone: 'An Thuong',
    location: { latitude: 16.040400, longitude: 108.190200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in An Thuong.',
  },
  {
    id: 'node-dan-5-2',
    name: 'An Thuong Sector 2 High Street',
    zone: 'An Thuong',
    location: { latitude: 16.043400, longitude: 108.193200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in An Thuong.',
  },
  {
    id: 'node-dan-5-3',
    name: 'An Thuong Sector 3 High Street',
    zone: 'An Thuong',
    location: { latitude: 16.046400, longitude: 108.196200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in An Thuong.',
  },
  {
    id: 'node-dan-6-1',
    name: 'Ngu Hanh Son Sector 1 High Street',
    zone: 'Ngu Hanh Son',
    location: { latitude: 16.052400, longitude: 108.200200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ngu Hanh Son.',
  },
  {
    id: 'node-dan-6-2',
    name: 'Ngu Hanh Son Sector 2 High Street',
    zone: 'Ngu Hanh Son',
    location: { latitude: 16.055400, longitude: 108.203200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ngu Hanh Son.',
  },
  {
    id: 'node-dan-6-3',
    name: 'Ngu Hanh Son Sector 3 High Street',
    zone: 'Ngu Hanh Son',
    location: { latitude: 16.058400, longitude: 108.206200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ngu Hanh Son.',
  },
  {
    id: 'node-dan-7-1',
    name: 'Thanh Khe Sector 1 High Street',
    zone: 'Thanh Khe',
    location: { latitude: 16.064400, longitude: 108.210200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Thanh Khe.',
  },
  {
    id: 'node-dan-7-2',
    name: 'Thanh Khe Sector 2 High Street',
    zone: 'Thanh Khe',
    location: { latitude: 16.067400, longitude: 108.213200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Thanh Khe.',
  },
  {
    id: 'node-dan-7-3',
    name: 'Thanh Khe Sector 3 High Street',
    zone: 'Thanh Khe',
    location: { latitude: 16.070400, longitude: 108.216200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Thanh Khe.',
  },
  {
    id: 'node-dan-8-1',
    name: 'Cam Le Sector 1 High Street',
    zone: 'Cam Le',
    location: { latitude: 16.076400, longitude: 108.220200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cam Le.',
  },
  {
    id: 'node-dan-8-2',
    name: 'Cam Le Sector 2 High Street',
    zone: 'Cam Le',
    location: { latitude: 16.079400, longitude: 108.223200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cam Le.',
  },
  {
    id: 'node-dan-8-3',
    name: 'Cam Le Sector 3 High Street',
    zone: 'Cam Le',
    location: { latitude: 16.082400, longitude: 108.226200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cam Le.',
  },
  {
    id: 'node-dan-9-1',
    name: 'Lien Chieu Sector 1 High Street',
    zone: 'Lien Chieu',
    location: { latitude: 16.088400, longitude: 108.230200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lien Chieu.',
  },
  {
    id: 'node-dan-9-2',
    name: 'Lien Chieu Sector 2 High Street',
    zone: 'Lien Chieu',
    location: { latitude: 16.091400, longitude: 108.233200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lien Chieu.',
  },
  {
    id: 'node-dan-9-3',
    name: 'Lien Chieu Sector 3 High Street',
    zone: 'Lien Chieu',
    location: { latitude: 16.094400, longitude: 108.236200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lien Chieu.',
  },
  {
    id: 'node-dan-10-1',
    name: 'Hoa Vang Sector 1 High Street',
    zone: 'Hoa Vang',
    location: { latitude: 16.100400, longitude: 108.240200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hoa Vang.',
  },
  {
    id: 'node-dan-10-2',
    name: 'Hoa Vang Sector 2 High Street',
    zone: 'Hoa Vang',
    location: { latitude: 16.103400, longitude: 108.243200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hoa Vang.',
  },
  {
    id: 'node-dan-10-3',
    name: 'Hoa Vang Sector 3 High Street',
    zone: 'Hoa Vang',
    location: { latitude: 16.106400, longitude: 108.246200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hoa Vang.',
  },
];

export const DANANG_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-dan-1',
    fromNodeId: 'node-dan-1-1',
    toNodeId: 'node-dan-1-2',
    roadName: 'My Khe Beach Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-2',
    fromNodeId: 'node-dan-1-2',
    toNodeId: 'node-dan-1-3',
    roadName: 'My Khe Beach Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-3',
    fromNodeId: 'node-dan-2-1',
    toNodeId: 'node-dan-2-2',
    roadName: 'Han River Waterfront Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-4',
    fromNodeId: 'node-dan-2-2',
    toNodeId: 'node-dan-2-3',
    roadName: 'Han River Waterfront Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-5',
    fromNodeId: 'node-dan-3-1',
    toNodeId: 'node-dan-3-2',
    roadName: 'Hai Chau Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-6',
    fromNodeId: 'node-dan-3-2',
    toNodeId: 'node-dan-3-3',
    roadName: 'Hai Chau Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-7',
    fromNodeId: 'node-dan-4-1',
    toNodeId: 'node-dan-4-2',
    roadName: 'Son Tra Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-8',
    fromNodeId: 'node-dan-4-2',
    toNodeId: 'node-dan-4-3',
    roadName: 'Son Tra Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-9',
    fromNodeId: 'node-dan-5-1',
    toNodeId: 'node-dan-5-2',
    roadName: 'An Thuong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-10',
    fromNodeId: 'node-dan-5-2',
    toNodeId: 'node-dan-5-3',
    roadName: 'An Thuong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-11',
    fromNodeId: 'node-dan-6-1',
    toNodeId: 'node-dan-6-2',
    roadName: 'Ngu Hanh Son Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-12',
    fromNodeId: 'node-dan-6-2',
    toNodeId: 'node-dan-6-3',
    roadName: 'Ngu Hanh Son Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-13',
    fromNodeId: 'node-dan-7-1',
    toNodeId: 'node-dan-7-2',
    roadName: 'Thanh Khe Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-14',
    fromNodeId: 'node-dan-7-2',
    toNodeId: 'node-dan-7-3',
    roadName: 'Thanh Khe Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-15',
    fromNodeId: 'node-dan-8-1',
    toNodeId: 'node-dan-8-2',
    roadName: 'Cam Le Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-16',
    fromNodeId: 'node-dan-8-2',
    toNodeId: 'node-dan-8-3',
    roadName: 'Cam Le Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-17',
    fromNodeId: 'node-dan-9-1',
    toNodeId: 'node-dan-9-2',
    roadName: 'Lien Chieu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-18',
    fromNodeId: 'node-dan-9-2',
    toNodeId: 'node-dan-9-3',
    roadName: 'Lien Chieu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-19',
    fromNodeId: 'node-dan-10-1',
    toNodeId: 'node-dan-10-2',
    roadName: 'Hoa Vang Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dan-20',
    fromNodeId: 'node-dan-10-2',
    toNodeId: 'node-dan-10-3',
    roadName: 'Hoa Vang Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
