/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Dehradun Doon Valley Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const DEHRADUN_BASE_COORDINATE: GeoCoordinate = {
  latitude: 30.3165,
  longitude: 78.0322,
};

export const DEHRADUN_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-deh-1-1',
    name: 'Rajpur Road Sector 1 High Street',
    zone: 'Rajpur Road',
    location: { latitude: 30.254500, longitude: 77.980200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rajpur Road.',
  },
  {
    id: 'node-deh-1-2',
    name: 'Rajpur Road Sector 2 High Street',
    zone: 'Rajpur Road',
    location: { latitude: 30.257500, longitude: 77.983200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rajpur Road.',
  },
  {
    id: 'node-deh-1-3',
    name: 'Rajpur Road Sector 3 High Street',
    zone: 'Rajpur Road',
    location: { latitude: 30.260500, longitude: 77.986200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rajpur Road.',
  },
  {
    id: 'node-deh-2-1',
    name: 'Paltan Bazaar Sector 1 High Street',
    zone: 'Paltan Bazaar',
    location: { latitude: 30.266500, longitude: 77.990200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Paltan Bazaar.',
  },
  {
    id: 'node-deh-2-2',
    name: 'Paltan Bazaar Sector 2 High Street',
    zone: 'Paltan Bazaar',
    location: { latitude: 30.269500, longitude: 77.993200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Paltan Bazaar.',
  },
  {
    id: 'node-deh-2-3',
    name: 'Paltan Bazaar Sector 3 High Street',
    zone: 'Paltan Bazaar',
    location: { latitude: 30.272500, longitude: 77.996200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Paltan Bazaar.',
  },
  {
    id: 'node-deh-3-1',
    name: 'Chakrata Road Sector 1 High Street',
    zone: 'Chakrata Road',
    location: { latitude: 30.278500, longitude: 78.000200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chakrata Road.',
  },
  {
    id: 'node-deh-3-2',
    name: 'Chakrata Road Sector 2 High Street',
    zone: 'Chakrata Road',
    location: { latitude: 30.281500, longitude: 78.003200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chakrata Road.',
  },
  {
    id: 'node-deh-3-3',
    name: 'Chakrata Road Sector 3 High Street',
    zone: 'Chakrata Road',
    location: { latitude: 30.284500, longitude: 78.006200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chakrata Road.',
  },
  {
    id: 'node-deh-4-1',
    name: 'Jakhan Sector 1 High Street',
    zone: 'Jakhan',
    location: { latitude: 30.290500, longitude: 78.010200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jakhan.',
  },
  {
    id: 'node-deh-4-2',
    name: 'Jakhan Sector 2 High Street',
    zone: 'Jakhan',
    location: { latitude: 30.293500, longitude: 78.013200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jakhan.',
  },
  {
    id: 'node-deh-4-3',
    name: 'Jakhan Sector 3 High Street',
    zone: 'Jakhan',
    location: { latitude: 30.296500, longitude: 78.016200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jakhan.',
  },
  {
    id: 'node-deh-5-1',
    name: 'Hathibarkala Sector 1 High Street',
    zone: 'Hathibarkala',
    location: { latitude: 30.302500, longitude: 78.020200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hathibarkala.',
  },
  {
    id: 'node-deh-5-2',
    name: 'Hathibarkala Sector 2 High Street',
    zone: 'Hathibarkala',
    location: { latitude: 30.305500, longitude: 78.023200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hathibarkala.',
  },
  {
    id: 'node-deh-5-3',
    name: 'Hathibarkala Sector 3 High Street',
    zone: 'Hathibarkala',
    location: { latitude: 30.308500, longitude: 78.026200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hathibarkala.',
  },
  {
    id: 'node-deh-6-1',
    name: 'Ballupur Sector 1 High Street',
    zone: 'Ballupur',
    location: { latitude: 30.314500, longitude: 78.030200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ballupur.',
  },
  {
    id: 'node-deh-6-2',
    name: 'Ballupur Sector 2 High Street',
    zone: 'Ballupur',
    location: { latitude: 30.317500, longitude: 78.033200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ballupur.',
  },
  {
    id: 'node-deh-6-3',
    name: 'Ballupur Sector 3 High Street',
    zone: 'Ballupur',
    location: { latitude: 30.320500, longitude: 78.036200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ballupur.',
  },
  {
    id: 'node-deh-7-1',
    name: 'Vasant Vihar Sector 1 High Street',
    zone: 'Vasant Vihar',
    location: { latitude: 30.326500, longitude: 78.040200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vasant Vihar.',
  },
  {
    id: 'node-deh-7-2',
    name: 'Vasant Vihar Sector 2 High Street',
    zone: 'Vasant Vihar',
    location: { latitude: 30.329500, longitude: 78.043200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vasant Vihar.',
  },
  {
    id: 'node-deh-7-3',
    name: 'Vasant Vihar Sector 3 High Street',
    zone: 'Vasant Vihar',
    location: { latitude: 30.332500, longitude: 78.046200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vasant Vihar.',
  },
  {
    id: 'node-deh-8-1',
    name: 'Dalanwala Sector 1 High Street',
    zone: 'Dalanwala',
    location: { latitude: 30.338500, longitude: 78.050200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dalanwala.',
  },
  {
    id: 'node-deh-8-2',
    name: 'Dalanwala Sector 2 High Street',
    zone: 'Dalanwala',
    location: { latitude: 30.341500, longitude: 78.053200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dalanwala.',
  },
  {
    id: 'node-deh-8-3',
    name: 'Dalanwala Sector 3 High Street',
    zone: 'Dalanwala',
    location: { latitude: 30.344500, longitude: 78.056200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dalanwala.',
  },
  {
    id: 'node-deh-9-1',
    name: 'Clement Town Sector 1 High Street',
    zone: 'Clement Town',
    location: { latitude: 30.350500, longitude: 78.060200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Clement Town.',
  },
  {
    id: 'node-deh-9-2',
    name: 'Clement Town Sector 2 High Street',
    zone: 'Clement Town',
    location: { latitude: 30.353500, longitude: 78.063200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Clement Town.',
  },
  {
    id: 'node-deh-9-3',
    name: 'Clement Town Sector 3 High Street',
    zone: 'Clement Town',
    location: { latitude: 30.356500, longitude: 78.066200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Clement Town.',
  },
  {
    id: 'node-deh-10-1',
    name: 'Sahastradhara Road Sector 1 High Street',
    zone: 'Sahastradhara Road',
    location: { latitude: 30.362500, longitude: 78.070200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sahastradhara Road.',
  },
  {
    id: 'node-deh-10-2',
    name: 'Sahastradhara Road Sector 2 High Street',
    zone: 'Sahastradhara Road',
    location: { latitude: 30.365500, longitude: 78.073200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sahastradhara Road.',
  },
  {
    id: 'node-deh-10-3',
    name: 'Sahastradhara Road Sector 3 High Street',
    zone: 'Sahastradhara Road',
    location: { latitude: 30.368500, longitude: 78.076200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sahastradhara Road.',
  },
];

export const DEHRADUN_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-deh-1',
    fromNodeId: 'node-deh-1-1',
    toNodeId: 'node-deh-1-2',
    roadName: 'Rajpur Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-2',
    fromNodeId: 'node-deh-1-2',
    toNodeId: 'node-deh-1-3',
    roadName: 'Rajpur Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-3',
    fromNodeId: 'node-deh-2-1',
    toNodeId: 'node-deh-2-2',
    roadName: 'Paltan Bazaar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-4',
    fromNodeId: 'node-deh-2-2',
    toNodeId: 'node-deh-2-3',
    roadName: 'Paltan Bazaar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-5',
    fromNodeId: 'node-deh-3-1',
    toNodeId: 'node-deh-3-2',
    roadName: 'Chakrata Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-6',
    fromNodeId: 'node-deh-3-2',
    toNodeId: 'node-deh-3-3',
    roadName: 'Chakrata Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-7',
    fromNodeId: 'node-deh-4-1',
    toNodeId: 'node-deh-4-2',
    roadName: 'Jakhan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-8',
    fromNodeId: 'node-deh-4-2',
    toNodeId: 'node-deh-4-3',
    roadName: 'Jakhan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-9',
    fromNodeId: 'node-deh-5-1',
    toNodeId: 'node-deh-5-2',
    roadName: 'Hathibarkala Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-10',
    fromNodeId: 'node-deh-5-2',
    toNodeId: 'node-deh-5-3',
    roadName: 'Hathibarkala Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-11',
    fromNodeId: 'node-deh-6-1',
    toNodeId: 'node-deh-6-2',
    roadName: 'Ballupur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-12',
    fromNodeId: 'node-deh-6-2',
    toNodeId: 'node-deh-6-3',
    roadName: 'Ballupur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-13',
    fromNodeId: 'node-deh-7-1',
    toNodeId: 'node-deh-7-2',
    roadName: 'Vasant Vihar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-14',
    fromNodeId: 'node-deh-7-2',
    toNodeId: 'node-deh-7-3',
    roadName: 'Vasant Vihar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-15',
    fromNodeId: 'node-deh-8-1',
    toNodeId: 'node-deh-8-2',
    roadName: 'Dalanwala Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-16',
    fromNodeId: 'node-deh-8-2',
    toNodeId: 'node-deh-8-3',
    roadName: 'Dalanwala Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-17',
    fromNodeId: 'node-deh-9-1',
    toNodeId: 'node-deh-9-2',
    roadName: 'Clement Town Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-18',
    fromNodeId: 'node-deh-9-2',
    toNodeId: 'node-deh-9-3',
    roadName: 'Clement Town Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-19',
    fromNodeId: 'node-deh-10-1',
    toNodeId: 'node-deh-10-2',
    roadName: 'Sahastradhara Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-deh-20',
    fromNodeId: 'node-deh-10-2',
    toNodeId: 'node-deh-10-3',
    roadName: 'Sahastradhara Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
