/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Delhi National Capital Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const DELHI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 28.6139,
  longitude: 77.209,
};

export const DELHI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-del-1-1',
    name: 'Connaught Place Sector 1 Road',
    zone: 'Connaught Place',
    location: { latitude: 28.541900, longitude: 77.157000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Connaught Place commercial centers and residential communities.',
  },
  {
    id: 'node-del-1-2',
    name: 'Connaught Place Sector 2 Road',
    zone: 'Connaught Place',
    location: { latitude: 28.544900, longitude: 77.160000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Connaught Place commercial centers and residential communities.',
  },
  {
    id: 'node-del-1-3',
    name: 'Connaught Place Sector 3 Road',
    zone: 'Connaught Place',
    location: { latitude: 28.547900, longitude: 77.163000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Connaught Place commercial centers and residential communities.',
  },
  {
    id: 'node-del-2-1',
    name: 'Hauz Khas Sector 1 Road',
    zone: 'Hauz Khas',
    location: { latitude: 28.556900, longitude: 77.169000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Hauz Khas commercial centers and residential communities.',
  },
  {
    id: 'node-del-2-2',
    name: 'Hauz Khas Sector 2 Road',
    zone: 'Hauz Khas',
    location: { latitude: 28.559900, longitude: 77.172000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Hauz Khas commercial centers and residential communities.',
  },
  {
    id: 'node-del-2-3',
    name: 'Hauz Khas Sector 3 Road',
    zone: 'Hauz Khas',
    location: { latitude: 28.562900, longitude: 77.175000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Hauz Khas commercial centers and residential communities.',
  },
  {
    id: 'node-del-3-1',
    name: 'Greater Kailash Sector 1 Road',
    zone: 'Greater Kailash',
    location: { latitude: 28.571900, longitude: 77.181000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Greater Kailash commercial centers and residential communities.',
  },
  {
    id: 'node-del-3-2',
    name: 'Greater Kailash Sector 2 Road',
    zone: 'Greater Kailash',
    location: { latitude: 28.574900, longitude: 77.184000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Greater Kailash commercial centers and residential communities.',
  },
  {
    id: 'node-del-3-3',
    name: 'Greater Kailash Sector 3 Road',
    zone: 'Greater Kailash',
    location: { latitude: 28.577900, longitude: 77.187000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Greater Kailash commercial centers and residential communities.',
  },
  {
    id: 'node-del-4-1',
    name: 'Saket Sector 1 Road',
    zone: 'Saket',
    location: { latitude: 28.586900, longitude: 77.193000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Saket commercial centers and residential communities.',
  },
  {
    id: 'node-del-4-2',
    name: 'Saket Sector 2 Road',
    zone: 'Saket',
    location: { latitude: 28.589900, longitude: 77.196000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Saket commercial centers and residential communities.',
  },
  {
    id: 'node-del-4-3',
    name: 'Saket Sector 3 Road',
    zone: 'Saket',
    location: { latitude: 28.592900, longitude: 77.199000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Saket commercial centers and residential communities.',
  },
  {
    id: 'node-del-5-1',
    name: 'Vasant Kunj Sector 1 Road',
    zone: 'Vasant Kunj',
    location: { latitude: 28.601900, longitude: 77.205000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Vasant Kunj commercial centers and residential communities.',
  },
  {
    id: 'node-del-5-2',
    name: 'Vasant Kunj Sector 2 Road',
    zone: 'Vasant Kunj',
    location: { latitude: 28.604900, longitude: 77.208000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Vasant Kunj commercial centers and residential communities.',
  },
  {
    id: 'node-del-5-3',
    name: 'Vasant Kunj Sector 3 Road',
    zone: 'Vasant Kunj',
    location: { latitude: 28.607900, longitude: 77.211000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Vasant Kunj commercial centers and residential communities.',
  },
  {
    id: 'node-del-6-1',
    name: 'Cyber City Gurgaon Sector 1 Road',
    zone: 'Cyber City Gurgaon',
    location: { latitude: 28.616900, longitude: 77.217000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Cyber City Gurgaon commercial centers and residential communities.',
  },
  {
    id: 'node-del-6-2',
    name: 'Cyber City Gurgaon Sector 2 Road',
    zone: 'Cyber City Gurgaon',
    location: { latitude: 28.619900, longitude: 77.220000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Cyber City Gurgaon commercial centers and residential communities.',
  },
  {
    id: 'node-del-6-3',
    name: 'Cyber City Gurgaon Sector 3 Road',
    zone: 'Cyber City Gurgaon',
    location: { latitude: 28.622900, longitude: 77.223000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Cyber City Gurgaon commercial centers and residential communities.',
  },
  {
    id: 'node-del-7-1',
    name: 'Sector 18 Noida Sector 1 Road',
    zone: 'Sector 18 Noida',
    location: { latitude: 28.631900, longitude: 77.229000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Sector 18 Noida commercial centers and residential communities.',
  },
  {
    id: 'node-del-7-2',
    name: 'Sector 18 Noida Sector 2 Road',
    zone: 'Sector 18 Noida',
    location: { latitude: 28.634900, longitude: 77.232000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Sector 18 Noida commercial centers and residential communities.',
  },
  {
    id: 'node-del-7-3',
    name: 'Sector 18 Noida Sector 3 Road',
    zone: 'Sector 18 Noida',
    location: { latitude: 28.637900, longitude: 77.235000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Sector 18 Noida commercial centers and residential communities.',
  },
  {
    id: 'node-del-8-1',
    name: 'Karol Bagh Sector 1 Road',
    zone: 'Karol Bagh',
    location: { latitude: 28.646900, longitude: 77.241000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Karol Bagh commercial centers and residential communities.',
  },
  {
    id: 'node-del-8-2',
    name: 'Karol Bagh Sector 2 Road',
    zone: 'Karol Bagh',
    location: { latitude: 28.649900, longitude: 77.244000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Karol Bagh commercial centers and residential communities.',
  },
  {
    id: 'node-del-8-3',
    name: 'Karol Bagh Sector 3 Road',
    zone: 'Karol Bagh',
    location: { latitude: 28.652900, longitude: 77.247000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Karol Bagh commercial centers and residential communities.',
  },
  {
    id: 'node-del-9-1',
    name: 'Rajouri Garden Sector 1 Road',
    zone: 'Rajouri Garden',
    location: { latitude: 28.661900, longitude: 77.253000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Rajouri Garden commercial centers and residential communities.',
  },
  {
    id: 'node-del-9-2',
    name: 'Rajouri Garden Sector 2 Road',
    zone: 'Rajouri Garden',
    location: { latitude: 28.664900, longitude: 77.256000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Rajouri Garden commercial centers and residential communities.',
  },
  {
    id: 'node-del-9-3',
    name: 'Rajouri Garden Sector 3 Road',
    zone: 'Rajouri Garden',
    location: { latitude: 28.667900, longitude: 77.259000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Rajouri Garden commercial centers and residential communities.',
  },
  {
    id: 'node-del-10-1',
    name: 'Dwarka Sector 1 Road',
    zone: 'Dwarka',
    location: { latitude: 28.676900, longitude: 77.265000 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Dwarka commercial centers and residential communities.',
  },
  {
    id: 'node-del-10-2',
    name: 'Dwarka Sector 2 Road',
    zone: 'Dwarka',
    location: { latitude: 28.679900, longitude: 77.268000 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Dwarka commercial centers and residential communities.',
  },
  {
    id: 'node-del-10-3',
    name: 'Dwarka Sector 3 Road',
    zone: 'Dwarka',
    location: { latitude: 28.682900, longitude: 77.271000 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Dwarka commercial centers and residential communities.',
  },
];

export const DELHI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-del-1',
    fromNodeId: 'node-del-1-1',
    toNodeId: 'node-del-1-2',
    roadName: 'Connaught Place Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-2',
    fromNodeId: 'node-del-1-2',
    toNodeId: 'node-del-1-3',
    roadName: 'Connaught Place Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-3',
    fromNodeId: 'node-del-2-1',
    toNodeId: 'node-del-2-2',
    roadName: 'Hauz Khas Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-4',
    fromNodeId: 'node-del-2-2',
    toNodeId: 'node-del-2-3',
    roadName: 'Hauz Khas Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-5',
    fromNodeId: 'node-del-3-1',
    toNodeId: 'node-del-3-2',
    roadName: 'Greater Kailash Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-6',
    fromNodeId: 'node-del-3-2',
    toNodeId: 'node-del-3-3',
    roadName: 'Greater Kailash Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-7',
    fromNodeId: 'node-del-4-1',
    toNodeId: 'node-del-4-2',
    roadName: 'Saket Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-8',
    fromNodeId: 'node-del-4-2',
    toNodeId: 'node-del-4-3',
    roadName: 'Saket Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-9',
    fromNodeId: 'node-del-5-1',
    toNodeId: 'node-del-5-2',
    roadName: 'Vasant Kunj Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-10',
    fromNodeId: 'node-del-5-2',
    toNodeId: 'node-del-5-3',
    roadName: 'Vasant Kunj Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-11',
    fromNodeId: 'node-del-6-1',
    toNodeId: 'node-del-6-2',
    roadName: 'Cyber City Gurgaon Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-12',
    fromNodeId: 'node-del-6-2',
    toNodeId: 'node-del-6-3',
    roadName: 'Cyber City Gurgaon Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-13',
    fromNodeId: 'node-del-7-1',
    toNodeId: 'node-del-7-2',
    roadName: 'Sector 18 Noida Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-14',
    fromNodeId: 'node-del-7-2',
    toNodeId: 'node-del-7-3',
    roadName: 'Sector 18 Noida Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-15',
    fromNodeId: 'node-del-8-1',
    toNodeId: 'node-del-8-2',
    roadName: 'Karol Bagh Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-16',
    fromNodeId: 'node-del-8-2',
    toNodeId: 'node-del-8-3',
    roadName: 'Karol Bagh Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-17',
    fromNodeId: 'node-del-9-1',
    toNodeId: 'node-del-9-2',
    roadName: 'Rajouri Garden Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-18',
    fromNodeId: 'node-del-9-2',
    toNodeId: 'node-del-9-3',
    roadName: 'Rajouri Garden Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-19',
    fromNodeId: 'node-del-10-1',
    toNodeId: 'node-del-10-2',
    roadName: 'Dwarka Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-del-20',
    fromNodeId: 'node-del-10-2',
    toNodeId: 'node-del-10-3',
    roadName: 'Dwarka Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
