/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Denver Mile High Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const DENVER_BASE_COORDINATE: GeoCoordinate = {
  latitude: 39.7392,
  longitude: -104.9903,
};

export const DENVER_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-den-1-1',
    name: 'LoDo Lower Downtown Sector 1 High Street',
    zone: 'LoDo Lower Downtown',
    location: { latitude: 39.677200, longitude: -105.042300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in LoDo Lower Downtown.',
  },
  {
    id: 'node-den-1-2',
    name: 'LoDo Lower Downtown Sector 2 High Street',
    zone: 'LoDo Lower Downtown',
    location: { latitude: 39.680200, longitude: -105.039300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in LoDo Lower Downtown.',
  },
  {
    id: 'node-den-1-3',
    name: 'LoDo Lower Downtown Sector 3 High Street',
    zone: 'LoDo Lower Downtown',
    location: { latitude: 39.683200, longitude: -105.036300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in LoDo Lower Downtown.',
  },
  {
    id: 'node-den-2-1',
    name: 'RiNo Art District Sector 1 High Street',
    zone: 'RiNo Art District',
    location: { latitude: 39.689200, longitude: -105.032300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in RiNo Art District.',
  },
  {
    id: 'node-den-2-2',
    name: 'RiNo Art District Sector 2 High Street',
    zone: 'RiNo Art District',
    location: { latitude: 39.692200, longitude: -105.029300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in RiNo Art District.',
  },
  {
    id: 'node-den-2-3',
    name: 'RiNo Art District Sector 3 High Street',
    zone: 'RiNo Art District',
    location: { latitude: 39.695200, longitude: -105.026300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in RiNo Art District.',
  },
  {
    id: 'node-den-3-1',
    name: 'Capitol Hill Denver Sector 1 High Street',
    zone: 'Capitol Hill Denver',
    location: { latitude: 39.701200, longitude: -105.022300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Capitol Hill Denver.',
  },
  {
    id: 'node-den-3-2',
    name: 'Capitol Hill Denver Sector 2 High Street',
    zone: 'Capitol Hill Denver',
    location: { latitude: 39.704200, longitude: -105.019300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Capitol Hill Denver.',
  },
  {
    id: 'node-den-3-3',
    name: 'Capitol Hill Denver Sector 3 High Street',
    zone: 'Capitol Hill Denver',
    location: { latitude: 39.707200, longitude: -105.016300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Capitol Hill Denver.',
  },
  {
    id: 'node-den-4-1',
    name: 'Highlands Sector 1 High Street',
    zone: 'Highlands',
    location: { latitude: 39.713200, longitude: -105.012300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Highlands.',
  },
  {
    id: 'node-den-4-2',
    name: 'Highlands Sector 2 High Street',
    zone: 'Highlands',
    location: { latitude: 39.716200, longitude: -105.009300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Highlands.',
  },
  {
    id: 'node-den-4-3',
    name: 'Highlands Sector 3 High Street',
    zone: 'Highlands',
    location: { latitude: 39.719200, longitude: -105.006300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Highlands.',
  },
  {
    id: 'node-den-5-1',
    name: 'Cherry Creek Sector 1 High Street',
    zone: 'Cherry Creek',
    location: { latitude: 39.725200, longitude: -105.002300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cherry Creek.',
  },
  {
    id: 'node-den-5-2',
    name: 'Cherry Creek Sector 2 High Street',
    zone: 'Cherry Creek',
    location: { latitude: 39.728200, longitude: -104.999300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cherry Creek.',
  },
  {
    id: 'node-den-5-3',
    name: 'Cherry Creek Sector 3 High Street',
    zone: 'Cherry Creek',
    location: { latitude: 39.731200, longitude: -104.996300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cherry Creek.',
  },
  {
    id: 'node-den-6-1',
    name: 'Baker Sector 1 High Street',
    zone: 'Baker',
    location: { latitude: 39.737200, longitude: -104.992300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Baker.',
  },
  {
    id: 'node-den-6-2',
    name: 'Baker Sector 2 High Street',
    zone: 'Baker',
    location: { latitude: 39.740200, longitude: -104.989300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Baker.',
  },
  {
    id: 'node-den-6-3',
    name: 'Baker Sector 3 High Street',
    zone: 'Baker',
    location: { latitude: 39.743200, longitude: -104.986300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Baker.',
  },
  {
    id: 'node-den-7-1',
    name: 'Five Points Sector 1 High Street',
    zone: 'Five Points',
    location: { latitude: 39.749200, longitude: -104.982300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Five Points.',
  },
  {
    id: 'node-den-7-2',
    name: 'Five Points Sector 2 High Street',
    zone: 'Five Points',
    location: { latitude: 39.752200, longitude: -104.979300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Five Points.',
  },
  {
    id: 'node-den-7-3',
    name: 'Five Points Sector 3 High Street',
    zone: 'Five Points',
    location: { latitude: 39.755200, longitude: -104.976300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Five Points.',
  },
  {
    id: 'node-den-8-1',
    name: 'Sloans Lake Sector 1 High Street',
    zone: 'Sloans Lake',
    location: { latitude: 39.761200, longitude: -104.972300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sloans Lake.',
  },
  {
    id: 'node-den-8-2',
    name: 'Sloans Lake Sector 2 High Street',
    zone: 'Sloans Lake',
    location: { latitude: 39.764200, longitude: -104.969300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sloans Lake.',
  },
  {
    id: 'node-den-8-3',
    name: 'Sloans Lake Sector 3 High Street',
    zone: 'Sloans Lake',
    location: { latitude: 39.767200, longitude: -104.966300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sloans Lake.',
  },
  {
    id: 'node-den-9-1',
    name: 'Wash Park Sector 1 High Street',
    zone: 'Wash Park',
    location: { latitude: 39.773200, longitude: -104.962300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wash Park.',
  },
  {
    id: 'node-den-9-2',
    name: 'Wash Park Sector 2 High Street',
    zone: 'Wash Park',
    location: { latitude: 39.776200, longitude: -104.959300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wash Park.',
  },
  {
    id: 'node-den-9-3',
    name: 'Wash Park Sector 3 High Street',
    zone: 'Wash Park',
    location: { latitude: 39.779200, longitude: -104.956300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wash Park.',
  },
  {
    id: 'node-den-10-1',
    name: 'Golden Triangle Sector 1 High Street',
    zone: 'Golden Triangle',
    location: { latitude: 39.785200, longitude: -104.952300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Golden Triangle.',
  },
  {
    id: 'node-den-10-2',
    name: 'Golden Triangle Sector 2 High Street',
    zone: 'Golden Triangle',
    location: { latitude: 39.788200, longitude: -104.949300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Golden Triangle.',
  },
  {
    id: 'node-den-10-3',
    name: 'Golden Triangle Sector 3 High Street',
    zone: 'Golden Triangle',
    location: { latitude: 39.791200, longitude: -104.946300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Golden Triangle.',
  },
];

export const DENVER_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-den-1',
    fromNodeId: 'node-den-1-1',
    toNodeId: 'node-den-1-2',
    roadName: 'LoDo Lower Downtown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-2',
    fromNodeId: 'node-den-1-2',
    toNodeId: 'node-den-1-3',
    roadName: 'LoDo Lower Downtown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-3',
    fromNodeId: 'node-den-2-1',
    toNodeId: 'node-den-2-2',
    roadName: 'RiNo Art District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-4',
    fromNodeId: 'node-den-2-2',
    toNodeId: 'node-den-2-3',
    roadName: 'RiNo Art District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-5',
    fromNodeId: 'node-den-3-1',
    toNodeId: 'node-den-3-2',
    roadName: 'Capitol Hill Denver Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-6',
    fromNodeId: 'node-den-3-2',
    toNodeId: 'node-den-3-3',
    roadName: 'Capitol Hill Denver Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-7',
    fromNodeId: 'node-den-4-1',
    toNodeId: 'node-den-4-2',
    roadName: 'Highlands Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-8',
    fromNodeId: 'node-den-4-2',
    toNodeId: 'node-den-4-3',
    roadName: 'Highlands Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-9',
    fromNodeId: 'node-den-5-1',
    toNodeId: 'node-den-5-2',
    roadName: 'Cherry Creek Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-10',
    fromNodeId: 'node-den-5-2',
    toNodeId: 'node-den-5-3',
    roadName: 'Cherry Creek Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-11',
    fromNodeId: 'node-den-6-1',
    toNodeId: 'node-den-6-2',
    roadName: 'Baker Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-12',
    fromNodeId: 'node-den-6-2',
    toNodeId: 'node-den-6-3',
    roadName: 'Baker Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-13',
    fromNodeId: 'node-den-7-1',
    toNodeId: 'node-den-7-2',
    roadName: 'Five Points Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-14',
    fromNodeId: 'node-den-7-2',
    toNodeId: 'node-den-7-3',
    roadName: 'Five Points Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-15',
    fromNodeId: 'node-den-8-1',
    toNodeId: 'node-den-8-2',
    roadName: 'Sloans Lake Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-16',
    fromNodeId: 'node-den-8-2',
    toNodeId: 'node-den-8-3',
    roadName: 'Sloans Lake Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-17',
    fromNodeId: 'node-den-9-1',
    toNodeId: 'node-den-9-2',
    roadName: 'Wash Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-18',
    fromNodeId: 'node-den-9-2',
    toNodeId: 'node-den-9-3',
    roadName: 'Wash Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-19',
    fromNodeId: 'node-den-10-1',
    toNodeId: 'node-den-10-2',
    roadName: 'Golden Triangle Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-den-20',
    fromNodeId: 'node-den-10-2',
    toNodeId: 'node-den-10-3',
    roadName: 'Golden Triangle Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
