/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Detroit Motor City Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const DETROIT_BASE_COORDINATE: GeoCoordinate = {
  latitude: 42.3314,
  longitude: -83.0458,
};

export const DETROIT_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-det-1-1',
    name: 'Downtown Detroit Sector 1 High Street',
    zone: 'Downtown Detroit',
    location: { latitude: 42.269400, longitude: -83.097800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Detroit.',
  },
  {
    id: 'node-det-1-2',
    name: 'Downtown Detroit Sector 2 High Street',
    zone: 'Downtown Detroit',
    location: { latitude: 42.272400, longitude: -83.094800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Detroit.',
  },
  {
    id: 'node-det-1-3',
    name: 'Downtown Detroit Sector 3 High Street',
    zone: 'Downtown Detroit',
    location: { latitude: 42.275400, longitude: -83.091800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Detroit.',
  },
  {
    id: 'node-det-2-1',
    name: 'Midtown Detroit Sector 1 High Street',
    zone: 'Midtown Detroit',
    location: { latitude: 42.281400, longitude: -83.087800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Midtown Detroit.',
  },
  {
    id: 'node-det-2-2',
    name: 'Midtown Detroit Sector 2 High Street',
    zone: 'Midtown Detroit',
    location: { latitude: 42.284400, longitude: -83.084800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Midtown Detroit.',
  },
  {
    id: 'node-det-2-3',
    name: 'Midtown Detroit Sector 3 High Street',
    zone: 'Midtown Detroit',
    location: { latitude: 42.287400, longitude: -83.081800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Midtown Detroit.',
  },
  {
    id: 'node-det-3-1',
    name: 'Corktown Sector 1 High Street',
    zone: 'Corktown',
    location: { latitude: 42.293400, longitude: -83.077800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Corktown.',
  },
  {
    id: 'node-det-3-2',
    name: 'Corktown Sector 2 High Street',
    zone: 'Corktown',
    location: { latitude: 42.296400, longitude: -83.074800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Corktown.',
  },
  {
    id: 'node-det-3-3',
    name: 'Corktown Sector 3 High Street',
    zone: 'Corktown',
    location: { latitude: 42.299400, longitude: -83.071800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Corktown.',
  },
  {
    id: 'node-det-4-1',
    name: 'Eastern Market Sector 1 High Street',
    zone: 'Eastern Market',
    location: { latitude: 42.305400, longitude: -83.067800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Eastern Market.',
  },
  {
    id: 'node-det-4-2',
    name: 'Eastern Market Sector 2 High Street',
    zone: 'Eastern Market',
    location: { latitude: 42.308400, longitude: -83.064800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Eastern Market.',
  },
  {
    id: 'node-det-4-3',
    name: 'Eastern Market Sector 3 High Street',
    zone: 'Eastern Market',
    location: { latitude: 42.311400, longitude: -83.061800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Eastern Market.',
  },
  {
    id: 'node-det-5-1',
    name: 'New Center Sector 1 High Street',
    zone: 'New Center',
    location: { latitude: 42.317400, longitude: -83.057800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in New Center.',
  },
  {
    id: 'node-det-5-2',
    name: 'New Center Sector 2 High Street',
    zone: 'New Center',
    location: { latitude: 42.320400, longitude: -83.054800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in New Center.',
  },
  {
    id: 'node-det-5-3',
    name: 'New Center Sector 3 High Street',
    zone: 'New Center',
    location: { latitude: 42.323400, longitude: -83.051800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in New Center.',
  },
  {
    id: 'node-det-6-1',
    name: 'Rivertown Sector 1 High Street',
    zone: 'Rivertown',
    location: { latitude: 42.329400, longitude: -83.047800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rivertown.',
  },
  {
    id: 'node-det-6-2',
    name: 'Rivertown Sector 2 High Street',
    zone: 'Rivertown',
    location: { latitude: 42.332400, longitude: -83.044800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rivertown.',
  },
  {
    id: 'node-det-6-3',
    name: 'Rivertown Sector 3 High Street',
    zone: 'Rivertown',
    location: { latitude: 42.335400, longitude: -83.041800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rivertown.',
  },
  {
    id: 'node-det-7-1',
    name: 'Woodbridge Sector 1 High Street',
    zone: 'Woodbridge',
    location: { latitude: 42.341400, longitude: -83.037800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Woodbridge.',
  },
  {
    id: 'node-det-7-2',
    name: 'Woodbridge Sector 2 High Street',
    zone: 'Woodbridge',
    location: { latitude: 42.344400, longitude: -83.034800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Woodbridge.',
  },
  {
    id: 'node-det-7-3',
    name: 'Woodbridge Sector 3 High Street',
    zone: 'Woodbridge',
    location: { latitude: 42.347400, longitude: -83.031800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Woodbridge.',
  },
  {
    id: 'node-det-8-1',
    name: 'West Village Detroit Sector 1 High Street',
    zone: 'West Village Detroit',
    location: { latitude: 42.353400, longitude: -83.027800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in West Village Detroit.',
  },
  {
    id: 'node-det-8-2',
    name: 'West Village Detroit Sector 2 High Street',
    zone: 'West Village Detroit',
    location: { latitude: 42.356400, longitude: -83.024800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in West Village Detroit.',
  },
  {
    id: 'node-det-8-3',
    name: 'West Village Detroit Sector 3 High Street',
    zone: 'West Village Detroit',
    location: { latitude: 42.359400, longitude: -83.021800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in West Village Detroit.',
  },
  {
    id: 'node-det-9-1',
    name: 'Indian Village Sector 1 High Street',
    zone: 'Indian Village',
    location: { latitude: 42.365400, longitude: -83.017800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Indian Village.',
  },
  {
    id: 'node-det-9-2',
    name: 'Indian Village Sector 2 High Street',
    zone: 'Indian Village',
    location: { latitude: 42.368400, longitude: -83.014800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Indian Village.',
  },
  {
    id: 'node-det-9-3',
    name: 'Indian Village Sector 3 High Street',
    zone: 'Indian Village',
    location: { latitude: 42.371400, longitude: -83.011800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Indian Village.',
  },
  {
    id: 'node-det-10-1',
    name: 'Palmer Woods Sector 1 High Street',
    zone: 'Palmer Woods',
    location: { latitude: 42.377400, longitude: -83.007800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Palmer Woods.',
  },
  {
    id: 'node-det-10-2',
    name: 'Palmer Woods Sector 2 High Street',
    zone: 'Palmer Woods',
    location: { latitude: 42.380400, longitude: -83.004800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Palmer Woods.',
  },
  {
    id: 'node-det-10-3',
    name: 'Palmer Woods Sector 3 High Street',
    zone: 'Palmer Woods',
    location: { latitude: 42.383400, longitude: -83.001800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Palmer Woods.',
  },
];

export const DETROIT_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-det-1',
    fromNodeId: 'node-det-1-1',
    toNodeId: 'node-det-1-2',
    roadName: 'Downtown Detroit Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-2',
    fromNodeId: 'node-det-1-2',
    toNodeId: 'node-det-1-3',
    roadName: 'Downtown Detroit Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-3',
    fromNodeId: 'node-det-2-1',
    toNodeId: 'node-det-2-2',
    roadName: 'Midtown Detroit Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-4',
    fromNodeId: 'node-det-2-2',
    toNodeId: 'node-det-2-3',
    roadName: 'Midtown Detroit Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-5',
    fromNodeId: 'node-det-3-1',
    toNodeId: 'node-det-3-2',
    roadName: 'Corktown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-6',
    fromNodeId: 'node-det-3-2',
    toNodeId: 'node-det-3-3',
    roadName: 'Corktown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-7',
    fromNodeId: 'node-det-4-1',
    toNodeId: 'node-det-4-2',
    roadName: 'Eastern Market Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-8',
    fromNodeId: 'node-det-4-2',
    toNodeId: 'node-det-4-3',
    roadName: 'Eastern Market Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-9',
    fromNodeId: 'node-det-5-1',
    toNodeId: 'node-det-5-2',
    roadName: 'New Center Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-10',
    fromNodeId: 'node-det-5-2',
    toNodeId: 'node-det-5-3',
    roadName: 'New Center Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-11',
    fromNodeId: 'node-det-6-1',
    toNodeId: 'node-det-6-2',
    roadName: 'Rivertown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-12',
    fromNodeId: 'node-det-6-2',
    toNodeId: 'node-det-6-3',
    roadName: 'Rivertown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-13',
    fromNodeId: 'node-det-7-1',
    toNodeId: 'node-det-7-2',
    roadName: 'Woodbridge Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-14',
    fromNodeId: 'node-det-7-2',
    toNodeId: 'node-det-7-3',
    roadName: 'Woodbridge Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-15',
    fromNodeId: 'node-det-8-1',
    toNodeId: 'node-det-8-2',
    roadName: 'West Village Detroit Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-16',
    fromNodeId: 'node-det-8-2',
    toNodeId: 'node-det-8-3',
    roadName: 'West Village Detroit Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-17',
    fromNodeId: 'node-det-9-1',
    toNodeId: 'node-det-9-2',
    roadName: 'Indian Village Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-18',
    fromNodeId: 'node-det-9-2',
    toNodeId: 'node-det-9-3',
    roadName: 'Indian Village Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-19',
    fromNodeId: 'node-det-10-1',
    toNodeId: 'node-det-10-2',
    roadName: 'Palmer Woods Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-det-20',
    fromNodeId: 'node-det-10-2',
    toNodeId: 'node-det-10-3',
    roadName: 'Palmer Woods Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
