/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Doha Corniche & Pearl
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const DOHA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 25.2854,
  longitude: 51.531,
};

export const DOHA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-doh-1-1',
    name: 'The Pearl Qatar Sector 1 High Street',
    zone: 'The Pearl Qatar',
    location: { latitude: 25.223400, longitude: 51.479000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in The Pearl Qatar.',
  },
  {
    id: 'node-doh-1-2',
    name: 'The Pearl Qatar Sector 2 High Street',
    zone: 'The Pearl Qatar',
    location: { latitude: 25.226400, longitude: 51.482000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in The Pearl Qatar.',
  },
  {
    id: 'node-doh-1-3',
    name: 'The Pearl Qatar Sector 3 High Street',
    zone: 'The Pearl Qatar',
    location: { latitude: 25.229400, longitude: 51.485000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in The Pearl Qatar.',
  },
  {
    id: 'node-doh-2-1',
    name: 'West Bay Sector 1 High Street',
    zone: 'West Bay',
    location: { latitude: 25.235400, longitude: 51.489000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in West Bay.',
  },
  {
    id: 'node-doh-2-2',
    name: 'West Bay Sector 2 High Street',
    zone: 'West Bay',
    location: { latitude: 25.238400, longitude: 51.492000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in West Bay.',
  },
  {
    id: 'node-doh-2-3',
    name: 'West Bay Sector 3 High Street',
    zone: 'West Bay',
    location: { latitude: 25.241400, longitude: 51.495000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in West Bay.',
  },
  {
    id: 'node-doh-3-1',
    name: 'Lusail City Sector 1 High Street',
    zone: 'Lusail City',
    location: { latitude: 25.247400, longitude: 51.499000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lusail City.',
  },
  {
    id: 'node-doh-3-2',
    name: 'Lusail City Sector 2 High Street',
    zone: 'Lusail City',
    location: { latitude: 25.250400, longitude: 51.502000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lusail City.',
  },
  {
    id: 'node-doh-3-3',
    name: 'Lusail City Sector 3 High Street',
    zone: 'Lusail City',
    location: { latitude: 25.253400, longitude: 51.505000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lusail City.',
  },
  {
    id: 'node-doh-4-1',
    name: 'Msheireb Downtown Sector 1 High Street',
    zone: 'Msheireb Downtown',
    location: { latitude: 25.259400, longitude: 51.509000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Msheireb Downtown.',
  },
  {
    id: 'node-doh-4-2',
    name: 'Msheireb Downtown Sector 2 High Street',
    zone: 'Msheireb Downtown',
    location: { latitude: 25.262400, longitude: 51.512000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Msheireb Downtown.',
  },
  {
    id: 'node-doh-4-3',
    name: 'Msheireb Downtown Sector 3 High Street',
    zone: 'Msheireb Downtown',
    location: { latitude: 25.265400, longitude: 51.515000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Msheireb Downtown.',
  },
  {
    id: 'node-doh-5-1',
    name: 'Souq Waqif Area Sector 1 High Street',
    zone: 'Souq Waqif Area',
    location: { latitude: 25.271400, longitude: 51.519000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Souq Waqif Area.',
  },
  {
    id: 'node-doh-5-2',
    name: 'Souq Waqif Area Sector 2 High Street',
    zone: 'Souq Waqif Area',
    location: { latitude: 25.274400, longitude: 51.522000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Souq Waqif Area.',
  },
  {
    id: 'node-doh-5-3',
    name: 'Souq Waqif Area Sector 3 High Street',
    zone: 'Souq Waqif Area',
    location: { latitude: 25.277400, longitude: 51.525000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Souq Waqif Area.',
  },
  {
    id: 'node-doh-6-1',
    name: 'Al Sadd Sector 1 High Street',
    zone: 'Al Sadd',
    location: { latitude: 25.283400, longitude: 51.529000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Sadd.',
  },
  {
    id: 'node-doh-6-2',
    name: 'Al Sadd Sector 2 High Street',
    zone: 'Al Sadd',
    location: { latitude: 25.286400, longitude: 51.532000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Sadd.',
  },
  {
    id: 'node-doh-6-3',
    name: 'Al Sadd Sector 3 High Street',
    zone: 'Al Sadd',
    location: { latitude: 25.289400, longitude: 51.535000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Sadd.',
  },
  {
    id: 'node-doh-7-1',
    name: 'Al Dafna Sector 1 High Street',
    zone: 'Al Dafna',
    location: { latitude: 25.295400, longitude: 51.539000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Dafna.',
  },
  {
    id: 'node-doh-7-2',
    name: 'Al Dafna Sector 2 High Street',
    zone: 'Al Dafna',
    location: { latitude: 25.298400, longitude: 51.542000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Dafna.',
  },
  {
    id: 'node-doh-7-3',
    name: 'Al Dafna Sector 3 High Street',
    zone: 'Al Dafna',
    location: { latitude: 25.301400, longitude: 51.545000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Dafna.',
  },
  {
    id: 'node-doh-8-1',
    name: 'Katara Cultural Village Sector 1 High Street',
    zone: 'Katara Cultural Village',
    location: { latitude: 25.307400, longitude: 51.549000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Katara Cultural Village.',
  },
  {
    id: 'node-doh-8-2',
    name: 'Katara Cultural Village Sector 2 High Street',
    zone: 'Katara Cultural Village',
    location: { latitude: 25.310400, longitude: 51.552000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Katara Cultural Village.',
  },
  {
    id: 'node-doh-8-3',
    name: 'Katara Cultural Village Sector 3 High Street',
    zone: 'Katara Cultural Village',
    location: { latitude: 25.313400, longitude: 51.555000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Katara Cultural Village.',
  },
  {
    id: 'node-doh-9-1',
    name: 'Old Airport Doha Sector 1 High Street',
    zone: 'Old Airport Doha',
    location: { latitude: 25.319400, longitude: 51.559000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old Airport Doha.',
  },
  {
    id: 'node-doh-9-2',
    name: 'Old Airport Doha Sector 2 High Street',
    zone: 'Old Airport Doha',
    location: { latitude: 25.322400, longitude: 51.562000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old Airport Doha.',
  },
  {
    id: 'node-doh-9-3',
    name: 'Old Airport Doha Sector 3 High Street',
    zone: 'Old Airport Doha',
    location: { latitude: 25.325400, longitude: 51.565000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old Airport Doha.',
  },
  {
    id: 'node-doh-10-1',
    name: 'Al Waab Sector 1 High Street',
    zone: 'Al Waab',
    location: { latitude: 25.331400, longitude: 51.569000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Waab.',
  },
  {
    id: 'node-doh-10-2',
    name: 'Al Waab Sector 2 High Street',
    zone: 'Al Waab',
    location: { latitude: 25.334400, longitude: 51.572000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Waab.',
  },
  {
    id: 'node-doh-10-3',
    name: 'Al Waab Sector 3 High Street',
    zone: 'Al Waab',
    location: { latitude: 25.337400, longitude: 51.575000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Waab.',
  },
];

export const DOHA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-doh-1',
    fromNodeId: 'node-doh-1-1',
    toNodeId: 'node-doh-1-2',
    roadName: 'The Pearl Qatar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-2',
    fromNodeId: 'node-doh-1-2',
    toNodeId: 'node-doh-1-3',
    roadName: 'The Pearl Qatar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-3',
    fromNodeId: 'node-doh-2-1',
    toNodeId: 'node-doh-2-2',
    roadName: 'West Bay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-4',
    fromNodeId: 'node-doh-2-2',
    toNodeId: 'node-doh-2-3',
    roadName: 'West Bay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-5',
    fromNodeId: 'node-doh-3-1',
    toNodeId: 'node-doh-3-2',
    roadName: 'Lusail City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-6',
    fromNodeId: 'node-doh-3-2',
    toNodeId: 'node-doh-3-3',
    roadName: 'Lusail City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-7',
    fromNodeId: 'node-doh-4-1',
    toNodeId: 'node-doh-4-2',
    roadName: 'Msheireb Downtown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-8',
    fromNodeId: 'node-doh-4-2',
    toNodeId: 'node-doh-4-3',
    roadName: 'Msheireb Downtown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-9',
    fromNodeId: 'node-doh-5-1',
    toNodeId: 'node-doh-5-2',
    roadName: 'Souq Waqif Area Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-10',
    fromNodeId: 'node-doh-5-2',
    toNodeId: 'node-doh-5-3',
    roadName: 'Souq Waqif Area Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-11',
    fromNodeId: 'node-doh-6-1',
    toNodeId: 'node-doh-6-2',
    roadName: 'Al Sadd Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-12',
    fromNodeId: 'node-doh-6-2',
    toNodeId: 'node-doh-6-3',
    roadName: 'Al Sadd Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-13',
    fromNodeId: 'node-doh-7-1',
    toNodeId: 'node-doh-7-2',
    roadName: 'Al Dafna Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-14',
    fromNodeId: 'node-doh-7-2',
    toNodeId: 'node-doh-7-3',
    roadName: 'Al Dafna Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-15',
    fromNodeId: 'node-doh-8-1',
    toNodeId: 'node-doh-8-2',
    roadName: 'Katara Cultural Village Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-16',
    fromNodeId: 'node-doh-8-2',
    toNodeId: 'node-doh-8-3',
    roadName: 'Katara Cultural Village Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-17',
    fromNodeId: 'node-doh-9-1',
    toNodeId: 'node-doh-9-2',
    roadName: 'Old Airport Doha Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-18',
    fromNodeId: 'node-doh-9-2',
    toNodeId: 'node-doh-9-3',
    roadName: 'Old Airport Doha Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-19',
    fromNodeId: 'node-doh-10-1',
    toNodeId: 'node-doh-10-2',
    roadName: 'Al Waab Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-doh-20',
    fromNodeId: 'node-doh-10-2',
    toNodeId: 'node-doh-10-3',
    roadName: 'Al Waab Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
