/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Dubai Downtown & Marina
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const DUBAI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 25.2048,
  longitude: 55.2708,
};

export const DUBAI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-dub-1-1',
    name: 'Downtown Dubai Sector 1 High Street',
    zone: 'Downtown Dubai',
    location: { latitude: 25.142800, longitude: 55.218800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Dubai.',
  },
  {
    id: 'node-dub-1-2',
    name: 'Downtown Dubai Sector 2 High Street',
    zone: 'Downtown Dubai',
    location: { latitude: 25.145800, longitude: 55.221800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Dubai.',
  },
  {
    id: 'node-dub-1-3',
    name: 'Downtown Dubai Sector 3 High Street',
    zone: 'Downtown Dubai',
    location: { latitude: 25.148800, longitude: 55.224800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Dubai.',
  },
  {
    id: 'node-dub-2-1',
    name: 'Dubai Marina Sector 1 High Street',
    zone: 'Dubai Marina',
    location: { latitude: 25.154800, longitude: 55.228800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dubai Marina.',
  },
  {
    id: 'node-dub-2-2',
    name: 'Dubai Marina Sector 2 High Street',
    zone: 'Dubai Marina',
    location: { latitude: 25.157800, longitude: 55.231800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dubai Marina.',
  },
  {
    id: 'node-dub-2-3',
    name: 'Dubai Marina Sector 3 High Street',
    zone: 'Dubai Marina',
    location: { latitude: 25.160800, longitude: 55.234800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dubai Marina.',
  },
  {
    id: 'node-dub-3-1',
    name: 'Business Bay Sector 1 High Street',
    zone: 'Business Bay',
    location: { latitude: 25.166800, longitude: 55.238800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Business Bay.',
  },
  {
    id: 'node-dub-3-2',
    name: 'Business Bay Sector 2 High Street',
    zone: 'Business Bay',
    location: { latitude: 25.169800, longitude: 55.241800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Business Bay.',
  },
  {
    id: 'node-dub-3-3',
    name: 'Business Bay Sector 3 High Street',
    zone: 'Business Bay',
    location: { latitude: 25.172800, longitude: 55.244800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Business Bay.',
  },
  {
    id: 'node-dub-4-1',
    name: 'JLT Sector 1 High Street',
    zone: 'JLT',
    location: { latitude: 25.178800, longitude: 55.248800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in JLT.',
  },
  {
    id: 'node-dub-4-2',
    name: 'JLT Sector 2 High Street',
    zone: 'JLT',
    location: { latitude: 25.181800, longitude: 55.251800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in JLT.',
  },
  {
    id: 'node-dub-4-3',
    name: 'JLT Sector 3 High Street',
    zone: 'JLT',
    location: { latitude: 25.184800, longitude: 55.254800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in JLT.',
  },
  {
    id: 'node-dub-5-1',
    name: 'Palm Jumeirah Sector 1 High Street',
    zone: 'Palm Jumeirah',
    location: { latitude: 25.190800, longitude: 55.258800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Palm Jumeirah.',
  },
  {
    id: 'node-dub-5-2',
    name: 'Palm Jumeirah Sector 2 High Street',
    zone: 'Palm Jumeirah',
    location: { latitude: 25.193800, longitude: 55.261800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Palm Jumeirah.',
  },
  {
    id: 'node-dub-5-3',
    name: 'Palm Jumeirah Sector 3 High Street',
    zone: 'Palm Jumeirah',
    location: { latitude: 25.196800, longitude: 55.264800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Palm Jumeirah.',
  },
  {
    id: 'node-dub-6-1',
    name: 'DIFC Sector 1 High Street',
    zone: 'DIFC',
    location: { latitude: 25.202800, longitude: 55.268800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in DIFC.',
  },
  {
    id: 'node-dub-6-2',
    name: 'DIFC Sector 2 High Street',
    zone: 'DIFC',
    location: { latitude: 25.205800, longitude: 55.271800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in DIFC.',
  },
  {
    id: 'node-dub-6-3',
    name: 'DIFC Sector 3 High Street',
    zone: 'DIFC',
    location: { latitude: 25.208800, longitude: 55.274800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in DIFC.',
  },
  {
    id: 'node-dub-7-1',
    name: 'Jumeirah Beach Sector 1 High Street',
    zone: 'Jumeirah Beach',
    location: { latitude: 25.214800, longitude: 55.278800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jumeirah Beach.',
  },
  {
    id: 'node-dub-7-2',
    name: 'Jumeirah Beach Sector 2 High Street',
    zone: 'Jumeirah Beach',
    location: { latitude: 25.217800, longitude: 55.281800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jumeirah Beach.',
  },
  {
    id: 'node-dub-7-3',
    name: 'Jumeirah Beach Sector 3 High Street',
    zone: 'Jumeirah Beach',
    location: { latitude: 25.220800, longitude: 55.284800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jumeirah Beach.',
  },
  {
    id: 'node-dub-8-1',
    name: 'Al Barsha Sector 1 High Street',
    zone: 'Al Barsha',
    location: { latitude: 25.226800, longitude: 55.288800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Barsha.',
  },
  {
    id: 'node-dub-8-2',
    name: 'Al Barsha Sector 2 High Street',
    zone: 'Al Barsha',
    location: { latitude: 25.229800, longitude: 55.291800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Barsha.',
  },
  {
    id: 'node-dub-8-3',
    name: 'Al Barsha Sector 3 High Street',
    zone: 'Al Barsha',
    location: { latitude: 25.232800, longitude: 55.294800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Barsha.',
  },
  {
    id: 'node-dub-9-1',
    name: 'Deira Sector 1 High Street',
    zone: 'Deira',
    location: { latitude: 25.238800, longitude: 55.298800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Deira.',
  },
  {
    id: 'node-dub-9-2',
    name: 'Deira Sector 2 High Street',
    zone: 'Deira',
    location: { latitude: 25.241800, longitude: 55.301800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Deira.',
  },
  {
    id: 'node-dub-9-3',
    name: 'Deira Sector 3 High Street',
    zone: 'Deira',
    location: { latitude: 25.244800, longitude: 55.304800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Deira.',
  },
  {
    id: 'node-dub-10-1',
    name: 'City Walk Sector 1 High Street',
    zone: 'City Walk',
    location: { latitude: 25.250800, longitude: 55.308800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in City Walk.',
  },
  {
    id: 'node-dub-10-2',
    name: 'City Walk Sector 2 High Street',
    zone: 'City Walk',
    location: { latitude: 25.253800, longitude: 55.311800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in City Walk.',
  },
  {
    id: 'node-dub-10-3',
    name: 'City Walk Sector 3 High Street',
    zone: 'City Walk',
    location: { latitude: 25.256800, longitude: 55.314800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in City Walk.',
  },
];

export const DUBAI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-dub-1',
    fromNodeId: 'node-dub-1-1',
    toNodeId: 'node-dub-1-2',
    roadName: 'Downtown Dubai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-2',
    fromNodeId: 'node-dub-1-2',
    toNodeId: 'node-dub-1-3',
    roadName: 'Downtown Dubai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-3',
    fromNodeId: 'node-dub-2-1',
    toNodeId: 'node-dub-2-2',
    roadName: 'Dubai Marina Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-4',
    fromNodeId: 'node-dub-2-2',
    toNodeId: 'node-dub-2-3',
    roadName: 'Dubai Marina Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-5',
    fromNodeId: 'node-dub-3-1',
    toNodeId: 'node-dub-3-2',
    roadName: 'Business Bay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-6',
    fromNodeId: 'node-dub-3-2',
    toNodeId: 'node-dub-3-3',
    roadName: 'Business Bay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-7',
    fromNodeId: 'node-dub-4-1',
    toNodeId: 'node-dub-4-2',
    roadName: 'JLT Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-8',
    fromNodeId: 'node-dub-4-2',
    toNodeId: 'node-dub-4-3',
    roadName: 'JLT Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-9',
    fromNodeId: 'node-dub-5-1',
    toNodeId: 'node-dub-5-2',
    roadName: 'Palm Jumeirah Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-10',
    fromNodeId: 'node-dub-5-2',
    toNodeId: 'node-dub-5-3',
    roadName: 'Palm Jumeirah Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-11',
    fromNodeId: 'node-dub-6-1',
    toNodeId: 'node-dub-6-2',
    roadName: 'DIFC Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-12',
    fromNodeId: 'node-dub-6-2',
    toNodeId: 'node-dub-6-3',
    roadName: 'DIFC Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-13',
    fromNodeId: 'node-dub-7-1',
    toNodeId: 'node-dub-7-2',
    roadName: 'Jumeirah Beach Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-14',
    fromNodeId: 'node-dub-7-2',
    toNodeId: 'node-dub-7-3',
    roadName: 'Jumeirah Beach Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-15',
    fromNodeId: 'node-dub-8-1',
    toNodeId: 'node-dub-8-2',
    roadName: 'Al Barsha Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-16',
    fromNodeId: 'node-dub-8-2',
    toNodeId: 'node-dub-8-3',
    roadName: 'Al Barsha Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-17',
    fromNodeId: 'node-dub-9-1',
    toNodeId: 'node-dub-9-2',
    roadName: 'Deira Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-18',
    fromNodeId: 'node-dub-9-2',
    toNodeId: 'node-dub-9-3',
    roadName: 'Deira Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-19',
    fromNodeId: 'node-dub-10-1',
    toNodeId: 'node-dub-10-2',
    roadName: 'City Walk Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-20',
    fromNodeId: 'node-dub-10-2',
    toNodeId: 'node-dub-10-3',
    roadName: 'City Walk Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
