/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Dublin Liffey Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const DUBLIN_BASE_COORDINATE: GeoCoordinate = {
  latitude: 53.3498,
  longitude: -6.2603,
};

export const DUBLIN_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-dub-1-1',
    name: 'Temple Bar Sector 1 High Street',
    zone: 'Temple Bar',
    location: { latitude: 53.287800, longitude: -6.312300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Temple Bar.',
  },
  {
    id: 'node-dub-1-2',
    name: 'Temple Bar Sector 2 High Street',
    zone: 'Temple Bar',
    location: { latitude: 53.290800, longitude: -6.309300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Temple Bar.',
  },
  {
    id: 'node-dub-1-3',
    name: 'Temple Bar Sector 3 High Street',
    zone: 'Temple Bar',
    location: { latitude: 53.293800, longitude: -6.306300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Temple Bar.',
  },
  {
    id: 'node-dub-2-1',
    name: 'Grafton Street Sector 1 High Street',
    zone: 'Grafton Street',
    location: { latitude: 53.299800, longitude: -6.302300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Grafton Street.',
  },
  {
    id: 'node-dub-2-2',
    name: 'Grafton Street Sector 2 High Street',
    zone: 'Grafton Street',
    location: { latitude: 53.302800, longitude: -6.299300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Grafton Street.',
  },
  {
    id: 'node-dub-2-3',
    name: 'Grafton Street Sector 3 High Street',
    zone: 'Grafton Street',
    location: { latitude: 53.305800, longitude: -6.296300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Grafton Street.',
  },
  {
    id: 'node-dub-3-1',
    name: 'Ranelagh Sector 1 High Street',
    zone: 'Ranelagh',
    location: { latitude: 53.311800, longitude: -6.292300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ranelagh.',
  },
  {
    id: 'node-dub-3-2',
    name: 'Ranelagh Sector 2 High Street',
    zone: 'Ranelagh',
    location: { latitude: 53.314800, longitude: -6.289300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ranelagh.',
  },
  {
    id: 'node-dub-3-3',
    name: 'Ranelagh Sector 3 High Street',
    zone: 'Ranelagh',
    location: { latitude: 53.317800, longitude: -6.286300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ranelagh.',
  },
  {
    id: 'node-dub-4-1',
    name: 'Rathmines Sector 1 High Street',
    zone: 'Rathmines',
    location: { latitude: 53.323800, longitude: -6.282300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rathmines.',
  },
  {
    id: 'node-dub-4-2',
    name: 'Rathmines Sector 2 High Street',
    zone: 'Rathmines',
    location: { latitude: 53.326800, longitude: -6.279300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rathmines.',
  },
  {
    id: 'node-dub-4-3',
    name: 'Rathmines Sector 3 High Street',
    zone: 'Rathmines',
    location: { latitude: 53.329800, longitude: -6.276300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rathmines.',
  },
  {
    id: 'node-dub-5-1',
    name: 'Ballsbridge Sector 1 High Street',
    zone: 'Ballsbridge',
    location: { latitude: 53.335800, longitude: -6.272300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ballsbridge.',
  },
  {
    id: 'node-dub-5-2',
    name: 'Ballsbridge Sector 2 High Street',
    zone: 'Ballsbridge',
    location: { latitude: 53.338800, longitude: -6.269300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ballsbridge.',
  },
  {
    id: 'node-dub-5-3',
    name: 'Ballsbridge Sector 3 High Street',
    zone: 'Ballsbridge',
    location: { latitude: 53.341800, longitude: -6.266300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ballsbridge.',
  },
  {
    id: 'node-dub-6-1',
    name: 'Docklands Dublin Sector 1 High Street',
    zone: 'Docklands Dublin',
    location: { latitude: 53.347800, longitude: -6.262300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Docklands Dublin.',
  },
  {
    id: 'node-dub-6-2',
    name: 'Docklands Dublin Sector 2 High Street',
    zone: 'Docklands Dublin',
    location: { latitude: 53.350800, longitude: -6.259300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Docklands Dublin.',
  },
  {
    id: 'node-dub-6-3',
    name: 'Docklands Dublin Sector 3 High Street',
    zone: 'Docklands Dublin',
    location: { latitude: 53.353800, longitude: -6.256300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Docklands Dublin.',
  },
  {
    id: 'node-dub-7-1',
    name: 'Smithfield Sector 1 High Street',
    zone: 'Smithfield',
    location: { latitude: 53.359800, longitude: -6.252300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Smithfield.',
  },
  {
    id: 'node-dub-7-2',
    name: 'Smithfield Sector 2 High Street',
    zone: 'Smithfield',
    location: { latitude: 53.362800, longitude: -6.249300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Smithfield.',
  },
  {
    id: 'node-dub-7-3',
    name: 'Smithfield Sector 3 High Street',
    zone: 'Smithfield',
    location: { latitude: 53.365800, longitude: -6.246300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Smithfield.',
  },
  {
    id: 'node-dub-8-1',
    name: 'Stoneybatter Sector 1 High Street',
    zone: 'Stoneybatter',
    location: { latitude: 53.371800, longitude: -6.242300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Stoneybatter.',
  },
  {
    id: 'node-dub-8-2',
    name: 'Stoneybatter Sector 2 High Street',
    zone: 'Stoneybatter',
    location: { latitude: 53.374800, longitude: -6.239300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Stoneybatter.',
  },
  {
    id: 'node-dub-8-3',
    name: 'Stoneybatter Sector 3 High Street',
    zone: 'Stoneybatter',
    location: { latitude: 53.377800, longitude: -6.236300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Stoneybatter.',
  },
  {
    id: 'node-dub-9-1',
    name: 'Grand Canal Dock Sector 1 High Street',
    zone: 'Grand Canal Dock',
    location: { latitude: 53.383800, longitude: -6.232300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Grand Canal Dock.',
  },
  {
    id: 'node-dub-9-2',
    name: 'Grand Canal Dock Sector 2 High Street',
    zone: 'Grand Canal Dock',
    location: { latitude: 53.386800, longitude: -6.229300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Grand Canal Dock.',
  },
  {
    id: 'node-dub-9-3',
    name: 'Grand Canal Dock Sector 3 High Street',
    zone: 'Grand Canal Dock',
    location: { latitude: 53.389800, longitude: -6.226300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Grand Canal Dock.',
  },
  {
    id: 'node-dub-10-1',
    name: 'Clontarf Sector 1 High Street',
    zone: 'Clontarf',
    location: { latitude: 53.395800, longitude: -6.222300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Clontarf.',
  },
  {
    id: 'node-dub-10-2',
    name: 'Clontarf Sector 2 High Street',
    zone: 'Clontarf',
    location: { latitude: 53.398800, longitude: -6.219300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Clontarf.',
  },
  {
    id: 'node-dub-10-3',
    name: 'Clontarf Sector 3 High Street',
    zone: 'Clontarf',
    location: { latitude: 53.401800, longitude: -6.216300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Clontarf.',
  },
];

export const DUBLIN_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-dub-1',
    fromNodeId: 'node-dub-1-1',
    toNodeId: 'node-dub-1-2',
    roadName: 'Temple Bar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-2',
    fromNodeId: 'node-dub-1-2',
    toNodeId: 'node-dub-1-3',
    roadName: 'Temple Bar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-3',
    fromNodeId: 'node-dub-2-1',
    toNodeId: 'node-dub-2-2',
    roadName: 'Grafton Street Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-4',
    fromNodeId: 'node-dub-2-2',
    toNodeId: 'node-dub-2-3',
    roadName: 'Grafton Street Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-5',
    fromNodeId: 'node-dub-3-1',
    toNodeId: 'node-dub-3-2',
    roadName: 'Ranelagh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-6',
    fromNodeId: 'node-dub-3-2',
    toNodeId: 'node-dub-3-3',
    roadName: 'Ranelagh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-7',
    fromNodeId: 'node-dub-4-1',
    toNodeId: 'node-dub-4-2',
    roadName: 'Rathmines Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-8',
    fromNodeId: 'node-dub-4-2',
    toNodeId: 'node-dub-4-3',
    roadName: 'Rathmines Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-9',
    fromNodeId: 'node-dub-5-1',
    toNodeId: 'node-dub-5-2',
    roadName: 'Ballsbridge Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-10',
    fromNodeId: 'node-dub-5-2',
    toNodeId: 'node-dub-5-3',
    roadName: 'Ballsbridge Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-11',
    fromNodeId: 'node-dub-6-1',
    toNodeId: 'node-dub-6-2',
    roadName: 'Docklands Dublin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-12',
    fromNodeId: 'node-dub-6-2',
    toNodeId: 'node-dub-6-3',
    roadName: 'Docklands Dublin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-13',
    fromNodeId: 'node-dub-7-1',
    toNodeId: 'node-dub-7-2',
    roadName: 'Smithfield Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-14',
    fromNodeId: 'node-dub-7-2',
    toNodeId: 'node-dub-7-3',
    roadName: 'Smithfield Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-15',
    fromNodeId: 'node-dub-8-1',
    toNodeId: 'node-dub-8-2',
    roadName: 'Stoneybatter Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-16',
    fromNodeId: 'node-dub-8-2',
    toNodeId: 'node-dub-8-3',
    roadName: 'Stoneybatter Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-17',
    fromNodeId: 'node-dub-9-1',
    toNodeId: 'node-dub-9-2',
    roadName: 'Grand Canal Dock Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-18',
    fromNodeId: 'node-dub-9-2',
    toNodeId: 'node-dub-9-3',
    roadName: 'Grand Canal Dock Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-19',
    fromNodeId: 'node-dub-10-1',
    toNodeId: 'node-dub-10-2',
    roadName: 'Clontarf Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dub-20',
    fromNodeId: 'node-dub-10-2',
    toNodeId: 'node-dub-10-3',
    roadName: 'Clontarf Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
