/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Durban Golden Mile Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const DURBAN_BASE_COORDINATE: GeoCoordinate = {
  latitude: -29.8587,
  longitude: 31.0218,
};

export const DURBAN_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-dur-1-1',
    name: 'Umhlanga Rocks Sector 1 High Street',
    zone: 'Umhlanga Rocks',
    location: { latitude: -29.920700, longitude: 30.969800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Umhlanga Rocks.',
  },
  {
    id: 'node-dur-1-2',
    name: 'Umhlanga Rocks Sector 2 High Street',
    zone: 'Umhlanga Rocks',
    location: { latitude: -29.917700, longitude: 30.972800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Umhlanga Rocks.',
  },
  {
    id: 'node-dur-1-3',
    name: 'Umhlanga Rocks Sector 3 High Street',
    zone: 'Umhlanga Rocks',
    location: { latitude: -29.914700, longitude: 30.975800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Umhlanga Rocks.',
  },
  {
    id: 'node-dur-2-1',
    name: 'Florida Road Sector 1 High Street',
    zone: 'Florida Road',
    location: { latitude: -29.908700, longitude: 30.979800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Florida Road.',
  },
  {
    id: 'node-dur-2-2',
    name: 'Florida Road Sector 2 High Street',
    zone: 'Florida Road',
    location: { latitude: -29.905700, longitude: 30.982800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Florida Road.',
  },
  {
    id: 'node-dur-2-3',
    name: 'Florida Road Sector 3 High Street',
    zone: 'Florida Road',
    location: { latitude: -29.902700, longitude: 30.985800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Florida Road.',
  },
  {
    id: 'node-dur-3-1',
    name: 'Durban Beachfront Sector 1 High Street',
    zone: 'Durban Beachfront',
    location: { latitude: -29.896700, longitude: 30.989800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Durban Beachfront.',
  },
  {
    id: 'node-dur-3-2',
    name: 'Durban Beachfront Sector 2 High Street',
    zone: 'Durban Beachfront',
    location: { latitude: -29.893700, longitude: 30.992800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Durban Beachfront.',
  },
  {
    id: 'node-dur-3-3',
    name: 'Durban Beachfront Sector 3 High Street',
    zone: 'Durban Beachfront',
    location: { latitude: -29.890700, longitude: 30.995800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Durban Beachfront.',
  },
  {
    id: 'node-dur-4-1',
    name: 'Morningside Durban Sector 1 High Street',
    zone: 'Morningside Durban',
    location: { latitude: -29.884700, longitude: 30.999800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Morningside Durban.',
  },
  {
    id: 'node-dur-4-2',
    name: 'Morningside Durban Sector 2 High Street',
    zone: 'Morningside Durban',
    location: { latitude: -29.881700, longitude: 31.002800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Morningside Durban.',
  },
  {
    id: 'node-dur-4-3',
    name: 'Morningside Durban Sector 3 High Street',
    zone: 'Morningside Durban',
    location: { latitude: -29.878700, longitude: 31.005800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Morningside Durban.',
  },
  {
    id: 'node-dur-5-1',
    name: 'Glenwood Sector 1 High Street',
    zone: 'Glenwood',
    location: { latitude: -29.872700, longitude: 31.009800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Glenwood.',
  },
  {
    id: 'node-dur-5-2',
    name: 'Glenwood Sector 2 High Street',
    zone: 'Glenwood',
    location: { latitude: -29.869700, longitude: 31.012800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Glenwood.',
  },
  {
    id: 'node-dur-5-3',
    name: 'Glenwood Sector 3 High Street',
    zone: 'Glenwood',
    location: { latitude: -29.866700, longitude: 31.015800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Glenwood.',
  },
  {
    id: 'node-dur-6-1',
    name: 'Durban North Sector 1 High Street',
    zone: 'Durban North',
    location: { latitude: -29.860700, longitude: 31.019800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Durban North.',
  },
  {
    id: 'node-dur-6-2',
    name: 'Durban North Sector 2 High Street',
    zone: 'Durban North',
    location: { latitude: -29.857700, longitude: 31.022800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Durban North.',
  },
  {
    id: 'node-dur-6-3',
    name: 'Durban North Sector 3 High Street',
    zone: 'Durban North',
    location: { latitude: -29.854700, longitude: 31.025800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Durban North.',
  },
  {
    id: 'node-dur-7-1',
    name: 'Westville Sector 1 High Street',
    zone: 'Westville',
    location: { latitude: -29.848700, longitude: 31.029800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Westville.',
  },
  {
    id: 'node-dur-7-2',
    name: 'Westville Sector 2 High Street',
    zone: 'Westville',
    location: { latitude: -29.845700, longitude: 31.032800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Westville.',
  },
  {
    id: 'node-dur-7-3',
    name: 'Westville Sector 3 High Street',
    zone: 'Westville',
    location: { latitude: -29.842700, longitude: 31.035800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Westville.',
  },
  {
    id: 'node-dur-8-1',
    name: 'Berea Sector 1 High Street',
    zone: 'Berea',
    location: { latitude: -29.836700, longitude: 31.039800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Berea.',
  },
  {
    id: 'node-dur-8-2',
    name: 'Berea Sector 2 High Street',
    zone: 'Berea',
    location: { latitude: -29.833700, longitude: 31.042800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Berea.',
  },
  {
    id: 'node-dur-8-3',
    name: 'Berea Sector 3 High Street',
    zone: 'Berea',
    location: { latitude: -29.830700, longitude: 31.045800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Berea.',
  },
  {
    id: 'node-dur-9-1',
    name: 'Point Waterfront Sector 1 High Street',
    zone: 'Point Waterfront',
    location: { latitude: -29.824700, longitude: 31.049800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Point Waterfront.',
  },
  {
    id: 'node-dur-9-2',
    name: 'Point Waterfront Sector 2 High Street',
    zone: 'Point Waterfront',
    location: { latitude: -29.821700, longitude: 31.052800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Point Waterfront.',
  },
  {
    id: 'node-dur-9-3',
    name: 'Point Waterfront Sector 3 High Street',
    zone: 'Point Waterfront',
    location: { latitude: -29.818700, longitude: 31.055800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Point Waterfront.',
  },
  {
    id: 'node-dur-10-1',
    name: 'Musgrave Sector 1 High Street',
    zone: 'Musgrave',
    location: { latitude: -29.812700, longitude: 31.059800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Musgrave.',
  },
  {
    id: 'node-dur-10-2',
    name: 'Musgrave Sector 2 High Street',
    zone: 'Musgrave',
    location: { latitude: -29.809700, longitude: 31.062800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Musgrave.',
  },
  {
    id: 'node-dur-10-3',
    name: 'Musgrave Sector 3 High Street',
    zone: 'Musgrave',
    location: { latitude: -29.806700, longitude: 31.065800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Musgrave.',
  },
];

export const DURBAN_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-dur-1',
    fromNodeId: 'node-dur-1-1',
    toNodeId: 'node-dur-1-2',
    roadName: 'Umhlanga Rocks Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-2',
    fromNodeId: 'node-dur-1-2',
    toNodeId: 'node-dur-1-3',
    roadName: 'Umhlanga Rocks Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-3',
    fromNodeId: 'node-dur-2-1',
    toNodeId: 'node-dur-2-2',
    roadName: 'Florida Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-4',
    fromNodeId: 'node-dur-2-2',
    toNodeId: 'node-dur-2-3',
    roadName: 'Florida Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-5',
    fromNodeId: 'node-dur-3-1',
    toNodeId: 'node-dur-3-2',
    roadName: 'Durban Beachfront Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-6',
    fromNodeId: 'node-dur-3-2',
    toNodeId: 'node-dur-3-3',
    roadName: 'Durban Beachfront Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-7',
    fromNodeId: 'node-dur-4-1',
    toNodeId: 'node-dur-4-2',
    roadName: 'Morningside Durban Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-8',
    fromNodeId: 'node-dur-4-2',
    toNodeId: 'node-dur-4-3',
    roadName: 'Morningside Durban Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-9',
    fromNodeId: 'node-dur-5-1',
    toNodeId: 'node-dur-5-2',
    roadName: 'Glenwood Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-10',
    fromNodeId: 'node-dur-5-2',
    toNodeId: 'node-dur-5-3',
    roadName: 'Glenwood Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-11',
    fromNodeId: 'node-dur-6-1',
    toNodeId: 'node-dur-6-2',
    roadName: 'Durban North Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-12',
    fromNodeId: 'node-dur-6-2',
    toNodeId: 'node-dur-6-3',
    roadName: 'Durban North Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-13',
    fromNodeId: 'node-dur-7-1',
    toNodeId: 'node-dur-7-2',
    roadName: 'Westville Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-14',
    fromNodeId: 'node-dur-7-2',
    toNodeId: 'node-dur-7-3',
    roadName: 'Westville Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-15',
    fromNodeId: 'node-dur-8-1',
    toNodeId: 'node-dur-8-2',
    roadName: 'Berea Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-16',
    fromNodeId: 'node-dur-8-2',
    toNodeId: 'node-dur-8-3',
    roadName: 'Berea Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-17',
    fromNodeId: 'node-dur-9-1',
    toNodeId: 'node-dur-9-2',
    roadName: 'Point Waterfront Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-18',
    fromNodeId: 'node-dur-9-2',
    toNodeId: 'node-dur-9-3',
    roadName: 'Point Waterfront Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-19',
    fromNodeId: 'node-dur-10-1',
    toNodeId: 'node-dur-10-2',
    roadName: 'Musgrave Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-dur-20',
    fromNodeId: 'node-dur-10-2',
    toNodeId: 'node-dur-10-3',
    roadName: 'Musgrave Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
