/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Edinburgh Royal Mile Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const EDINBURGH_BASE_COORDINATE: GeoCoordinate = {
  latitude: 55.9533,
  longitude: -3.1883,
};

export const EDINBURGH_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-edi-1-1',
    name: 'Old Town Edinburgh Sector 1 High Street',
    zone: 'Old Town Edinburgh',
    location: { latitude: 55.891300, longitude: -3.240300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old Town Edinburgh.',
  },
  {
    id: 'node-edi-1-2',
    name: 'Old Town Edinburgh Sector 2 High Street',
    zone: 'Old Town Edinburgh',
    location: { latitude: 55.894300, longitude: -3.237300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old Town Edinburgh.',
  },
  {
    id: 'node-edi-1-3',
    name: 'Old Town Edinburgh Sector 3 High Street',
    zone: 'Old Town Edinburgh',
    location: { latitude: 55.897300, longitude: -3.234300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old Town Edinburgh.',
  },
  {
    id: 'node-edi-2-1',
    name: 'New Town Edinburgh Sector 1 High Street',
    zone: 'New Town Edinburgh',
    location: { latitude: 55.903300, longitude: -3.230300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in New Town Edinburgh.',
  },
  {
    id: 'node-edi-2-2',
    name: 'New Town Edinburgh Sector 2 High Street',
    zone: 'New Town Edinburgh',
    location: { latitude: 55.906300, longitude: -3.227300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in New Town Edinburgh.',
  },
  {
    id: 'node-edi-2-3',
    name: 'New Town Edinburgh Sector 3 High Street',
    zone: 'New Town Edinburgh',
    location: { latitude: 55.909300, longitude: -3.224300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in New Town Edinburgh.',
  },
  {
    id: 'node-edi-3-1',
    name: 'Leith Sector 1 High Street',
    zone: 'Leith',
    location: { latitude: 55.915300, longitude: -3.220300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Leith.',
  },
  {
    id: 'node-edi-3-2',
    name: 'Leith Sector 2 High Street',
    zone: 'Leith',
    location: { latitude: 55.918300, longitude: -3.217300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Leith.',
  },
  {
    id: 'node-edi-3-3',
    name: 'Leith Sector 3 High Street',
    zone: 'Leith',
    location: { latitude: 55.921300, longitude: -3.214300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Leith.',
  },
  {
    id: 'node-edi-4-1',
    name: 'Stockbridge Sector 1 High Street',
    zone: 'Stockbridge',
    location: { latitude: 55.927300, longitude: -3.210300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Stockbridge.',
  },
  {
    id: 'node-edi-4-2',
    name: 'Stockbridge Sector 2 High Street',
    zone: 'Stockbridge',
    location: { latitude: 55.930300, longitude: -3.207300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Stockbridge.',
  },
  {
    id: 'node-edi-4-3',
    name: 'Stockbridge Sector 3 High Street',
    zone: 'Stockbridge',
    location: { latitude: 55.933300, longitude: -3.204300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Stockbridge.',
  },
  {
    id: 'node-edi-5-1',
    name: 'Morningside Sector 1 High Street',
    zone: 'Morningside',
    location: { latitude: 55.939300, longitude: -3.200300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Morningside.',
  },
  {
    id: 'node-edi-5-2',
    name: 'Morningside Sector 2 High Street',
    zone: 'Morningside',
    location: { latitude: 55.942300, longitude: -3.197300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Morningside.',
  },
  {
    id: 'node-edi-5-3',
    name: 'Morningside Sector 3 High Street',
    zone: 'Morningside',
    location: { latitude: 55.945300, longitude: -3.194300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Morningside.',
  },
  {
    id: 'node-edi-6-1',
    name: 'Bruntsfield Sector 1 High Street',
    zone: 'Bruntsfield',
    location: { latitude: 55.951300, longitude: -3.190300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bruntsfield.',
  },
  {
    id: 'node-edi-6-2',
    name: 'Bruntsfield Sector 2 High Street',
    zone: 'Bruntsfield',
    location: { latitude: 55.954300, longitude: -3.187300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bruntsfield.',
  },
  {
    id: 'node-edi-6-3',
    name: 'Bruntsfield Sector 3 High Street',
    zone: 'Bruntsfield',
    location: { latitude: 55.957300, longitude: -3.184300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bruntsfield.',
  },
  {
    id: 'node-edi-7-1',
    name: 'Haymarket Sector 1 High Street',
    zone: 'Haymarket',
    location: { latitude: 55.963300, longitude: -3.180300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Haymarket.',
  },
  {
    id: 'node-edi-7-2',
    name: 'Haymarket Sector 2 High Street',
    zone: 'Haymarket',
    location: { latitude: 55.966300, longitude: -3.177300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Haymarket.',
  },
  {
    id: 'node-edi-7-3',
    name: 'Haymarket Sector 3 High Street',
    zone: 'Haymarket',
    location: { latitude: 55.969300, longitude: -3.174300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Haymarket.',
  },
  {
    id: 'node-edi-8-1',
    name: 'Tollcross Sector 1 High Street',
    zone: 'Tollcross',
    location: { latitude: 55.975300, longitude: -3.170300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tollcross.',
  },
  {
    id: 'node-edi-8-2',
    name: 'Tollcross Sector 2 High Street',
    zone: 'Tollcross',
    location: { latitude: 55.978300, longitude: -3.167300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tollcross.',
  },
  {
    id: 'node-edi-8-3',
    name: 'Tollcross Sector 3 High Street',
    zone: 'Tollcross',
    location: { latitude: 55.981300, longitude: -3.164300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tollcross.',
  },
  {
    id: 'node-edi-9-1',
    name: 'Marchmont Sector 1 High Street',
    zone: 'Marchmont',
    location: { latitude: 55.987300, longitude: -3.160300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Marchmont.',
  },
  {
    id: 'node-edi-9-2',
    name: 'Marchmont Sector 2 High Street',
    zone: 'Marchmont',
    location: { latitude: 55.990300, longitude: -3.157300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Marchmont.',
  },
  {
    id: 'node-edi-9-3',
    name: 'Marchmont Sector 3 High Street',
    zone: 'Marchmont',
    location: { latitude: 55.993300, longitude: -3.154300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Marchmont.',
  },
  {
    id: 'node-edi-10-1',
    name: 'Portobello Sector 1 High Street',
    zone: 'Portobello',
    location: { latitude: 55.999300, longitude: -3.150300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Portobello.',
  },
  {
    id: 'node-edi-10-2',
    name: 'Portobello Sector 2 High Street',
    zone: 'Portobello',
    location: { latitude: 56.002300, longitude: -3.147300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Portobello.',
  },
  {
    id: 'node-edi-10-3',
    name: 'Portobello Sector 3 High Street',
    zone: 'Portobello',
    location: { latitude: 56.005300, longitude: -3.144300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Portobello.',
  },
];

export const EDINBURGH_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-edi-1',
    fromNodeId: 'node-edi-1-1',
    toNodeId: 'node-edi-1-2',
    roadName: 'Old Town Edinburgh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-2',
    fromNodeId: 'node-edi-1-2',
    toNodeId: 'node-edi-1-3',
    roadName: 'Old Town Edinburgh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-3',
    fromNodeId: 'node-edi-2-1',
    toNodeId: 'node-edi-2-2',
    roadName: 'New Town Edinburgh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-4',
    fromNodeId: 'node-edi-2-2',
    toNodeId: 'node-edi-2-3',
    roadName: 'New Town Edinburgh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-5',
    fromNodeId: 'node-edi-3-1',
    toNodeId: 'node-edi-3-2',
    roadName: 'Leith Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-6',
    fromNodeId: 'node-edi-3-2',
    toNodeId: 'node-edi-3-3',
    roadName: 'Leith Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-7',
    fromNodeId: 'node-edi-4-1',
    toNodeId: 'node-edi-4-2',
    roadName: 'Stockbridge Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-8',
    fromNodeId: 'node-edi-4-2',
    toNodeId: 'node-edi-4-3',
    roadName: 'Stockbridge Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-9',
    fromNodeId: 'node-edi-5-1',
    toNodeId: 'node-edi-5-2',
    roadName: 'Morningside Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-10',
    fromNodeId: 'node-edi-5-2',
    toNodeId: 'node-edi-5-3',
    roadName: 'Morningside Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-11',
    fromNodeId: 'node-edi-6-1',
    toNodeId: 'node-edi-6-2',
    roadName: 'Bruntsfield Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-12',
    fromNodeId: 'node-edi-6-2',
    toNodeId: 'node-edi-6-3',
    roadName: 'Bruntsfield Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-13',
    fromNodeId: 'node-edi-7-1',
    toNodeId: 'node-edi-7-2',
    roadName: 'Haymarket Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-14',
    fromNodeId: 'node-edi-7-2',
    toNodeId: 'node-edi-7-3',
    roadName: 'Haymarket Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-15',
    fromNodeId: 'node-edi-8-1',
    toNodeId: 'node-edi-8-2',
    roadName: 'Tollcross Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-16',
    fromNodeId: 'node-edi-8-2',
    toNodeId: 'node-edi-8-3',
    roadName: 'Tollcross Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-17',
    fromNodeId: 'node-edi-9-1',
    toNodeId: 'node-edi-9-2',
    roadName: 'Marchmont Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-18',
    fromNodeId: 'node-edi-9-2',
    toNodeId: 'node-edi-9-3',
    roadName: 'Marchmont Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-19',
    fromNodeId: 'node-edi-10-1',
    toNodeId: 'node-edi-10-2',
    roadName: 'Portobello Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-edi-20',
    fromNodeId: 'node-edi-10-2',
    toNodeId: 'node-edi-10-3',
    roadName: 'Portobello Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
