/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Florence Renaissance Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const FLORENCE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 43.7696,
  longitude: 11.2558,
};

export const FLORENCE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-flo-1-1',
    name: 'Duomo Florence Sector 1 High Street',
    zone: 'Duomo Florence',
    location: { latitude: 43.707600, longitude: 11.203800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Duomo Florence.',
  },
  {
    id: 'node-flo-1-2',
    name: 'Duomo Florence Sector 2 High Street',
    zone: 'Duomo Florence',
    location: { latitude: 43.710600, longitude: 11.206800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Duomo Florence.',
  },
  {
    id: 'node-flo-1-3',
    name: 'Duomo Florence Sector 3 High Street',
    zone: 'Duomo Florence',
    location: { latitude: 43.713600, longitude: 11.209800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Duomo Florence.',
  },
  {
    id: 'node-flo-2-1',
    name: 'Santa Croce Sector 1 High Street',
    zone: 'Santa Croce',
    location: { latitude: 43.719600, longitude: 11.213800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Santa Croce.',
  },
  {
    id: 'node-flo-2-2',
    name: 'Santa Croce Sector 2 High Street',
    zone: 'Santa Croce',
    location: { latitude: 43.722600, longitude: 11.216800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Santa Croce.',
  },
  {
    id: 'node-flo-2-3',
    name: 'Santa Croce Sector 3 High Street',
    zone: 'Santa Croce',
    location: { latitude: 43.725600, longitude: 11.219800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Santa Croce.',
  },
  {
    id: 'node-flo-3-1',
    name: 'San Lorenzo Sector 1 High Street',
    zone: 'San Lorenzo',
    location: { latitude: 43.731600, longitude: 11.223800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Lorenzo.',
  },
  {
    id: 'node-flo-3-2',
    name: 'San Lorenzo Sector 2 High Street',
    zone: 'San Lorenzo',
    location: { latitude: 43.734600, longitude: 11.226800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Lorenzo.',
  },
  {
    id: 'node-flo-3-3',
    name: 'San Lorenzo Sector 3 High Street',
    zone: 'San Lorenzo',
    location: { latitude: 43.737600, longitude: 11.229800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Lorenzo.',
  },
  {
    id: 'node-flo-4-1',
    name: 'Santo Spirito Sector 1 High Street',
    zone: 'Santo Spirito',
    location: { latitude: 43.743600, longitude: 11.233800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Santo Spirito.',
  },
  {
    id: 'node-flo-4-2',
    name: 'Santo Spirito Sector 2 High Street',
    zone: 'Santo Spirito',
    location: { latitude: 43.746600, longitude: 11.236800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Santo Spirito.',
  },
  {
    id: 'node-flo-4-3',
    name: 'Santo Spirito Sector 3 High Street',
    zone: 'Santo Spirito',
    location: { latitude: 43.749600, longitude: 11.239800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Santo Spirito.',
  },
  {
    id: 'node-flo-5-1',
    name: 'San Frediano Sector 1 High Street',
    zone: 'San Frediano',
    location: { latitude: 43.755600, longitude: 11.243800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Frediano.',
  },
  {
    id: 'node-flo-5-2',
    name: 'San Frediano Sector 2 High Street',
    zone: 'San Frediano',
    location: { latitude: 43.758600, longitude: 11.246800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Frediano.',
  },
  {
    id: 'node-flo-5-3',
    name: 'San Frediano Sector 3 High Street',
    zone: 'San Frediano',
    location: { latitude: 43.761600, longitude: 11.249800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Frediano.',
  },
  {
    id: 'node-flo-6-1',
    name: 'San Marco Sector 1 High Street',
    zone: 'San Marco',
    location: { latitude: 43.767600, longitude: 11.253800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Marco.',
  },
  {
    id: 'node-flo-6-2',
    name: 'San Marco Sector 2 High Street',
    zone: 'San Marco',
    location: { latitude: 43.770600, longitude: 11.256800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Marco.',
  },
  {
    id: 'node-flo-6-3',
    name: 'San Marco Sector 3 High Street',
    zone: 'San Marco',
    location: { latitude: 43.773600, longitude: 11.259800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Marco.',
  },
  {
    id: 'node-flo-7-1',
    name: 'Santa Maria Novella Sector 1 High Street',
    zone: 'Santa Maria Novella',
    location: { latitude: 43.779600, longitude: 11.263800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Santa Maria Novella.',
  },
  {
    id: 'node-flo-7-2',
    name: 'Santa Maria Novella Sector 2 High Street',
    zone: 'Santa Maria Novella',
    location: { latitude: 43.782600, longitude: 11.266800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Santa Maria Novella.',
  },
  {
    id: 'node-flo-7-3',
    name: 'Santa Maria Novella Sector 3 High Street',
    zone: 'Santa Maria Novella',
    location: { latitude: 43.785600, longitude: 11.269800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Santa Maria Novella.',
  },
  {
    id: 'node-flo-8-1',
    name: 'Campo di Marte Sector 1 High Street',
    zone: 'Campo di Marte',
    location: { latitude: 43.791600, longitude: 11.273800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Campo di Marte.',
  },
  {
    id: 'node-flo-8-2',
    name: 'Campo di Marte Sector 2 High Street',
    zone: 'Campo di Marte',
    location: { latitude: 43.794600, longitude: 11.276800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Campo di Marte.',
  },
  {
    id: 'node-flo-8-3',
    name: 'Campo di Marte Sector 3 High Street',
    zone: 'Campo di Marte',
    location: { latitude: 43.797600, longitude: 11.279800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Campo di Marte.',
  },
  {
    id: 'node-flo-9-1',
    name: 'Gavinana Sector 1 High Street',
    zone: 'Gavinana',
    location: { latitude: 43.803600, longitude: 11.283800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gavinana.',
  },
  {
    id: 'node-flo-9-2',
    name: 'Gavinana Sector 2 High Street',
    zone: 'Gavinana',
    location: { latitude: 43.806600, longitude: 11.286800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gavinana.',
  },
  {
    id: 'node-flo-9-3',
    name: 'Gavinana Sector 3 High Street',
    zone: 'Gavinana',
    location: { latitude: 43.809600, longitude: 11.289800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gavinana.',
  },
  {
    id: 'node-flo-10-1',
    name: 'Rifredi Sector 1 High Street',
    zone: 'Rifredi',
    location: { latitude: 43.815600, longitude: 11.293800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rifredi.',
  },
  {
    id: 'node-flo-10-2',
    name: 'Rifredi Sector 2 High Street',
    zone: 'Rifredi',
    location: { latitude: 43.818600, longitude: 11.296800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rifredi.',
  },
  {
    id: 'node-flo-10-3',
    name: 'Rifredi Sector 3 High Street',
    zone: 'Rifredi',
    location: { latitude: 43.821600, longitude: 11.299800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rifredi.',
  },
];

export const FLORENCE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-flo-1',
    fromNodeId: 'node-flo-1-1',
    toNodeId: 'node-flo-1-2',
    roadName: 'Duomo Florence Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-2',
    fromNodeId: 'node-flo-1-2',
    toNodeId: 'node-flo-1-3',
    roadName: 'Duomo Florence Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-3',
    fromNodeId: 'node-flo-2-1',
    toNodeId: 'node-flo-2-2',
    roadName: 'Santa Croce Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-4',
    fromNodeId: 'node-flo-2-2',
    toNodeId: 'node-flo-2-3',
    roadName: 'Santa Croce Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-5',
    fromNodeId: 'node-flo-3-1',
    toNodeId: 'node-flo-3-2',
    roadName: 'San Lorenzo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-6',
    fromNodeId: 'node-flo-3-2',
    toNodeId: 'node-flo-3-3',
    roadName: 'San Lorenzo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-7',
    fromNodeId: 'node-flo-4-1',
    toNodeId: 'node-flo-4-2',
    roadName: 'Santo Spirito Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-8',
    fromNodeId: 'node-flo-4-2',
    toNodeId: 'node-flo-4-3',
    roadName: 'Santo Spirito Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-9',
    fromNodeId: 'node-flo-5-1',
    toNodeId: 'node-flo-5-2',
    roadName: 'San Frediano Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-10',
    fromNodeId: 'node-flo-5-2',
    toNodeId: 'node-flo-5-3',
    roadName: 'San Frediano Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-11',
    fromNodeId: 'node-flo-6-1',
    toNodeId: 'node-flo-6-2',
    roadName: 'San Marco Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-12',
    fromNodeId: 'node-flo-6-2',
    toNodeId: 'node-flo-6-3',
    roadName: 'San Marco Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-13',
    fromNodeId: 'node-flo-7-1',
    toNodeId: 'node-flo-7-2',
    roadName: 'Santa Maria Novella Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-14',
    fromNodeId: 'node-flo-7-2',
    toNodeId: 'node-flo-7-3',
    roadName: 'Santa Maria Novella Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-15',
    fromNodeId: 'node-flo-8-1',
    toNodeId: 'node-flo-8-2',
    roadName: 'Campo di Marte Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-16',
    fromNodeId: 'node-flo-8-2',
    toNodeId: 'node-flo-8-3',
    roadName: 'Campo di Marte Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-17',
    fromNodeId: 'node-flo-9-1',
    toNodeId: 'node-flo-9-2',
    roadName: 'Gavinana Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-18',
    fromNodeId: 'node-flo-9-2',
    toNodeId: 'node-flo-9-3',
    roadName: 'Gavinana Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-19',
    fromNodeId: 'node-flo-10-1',
    toNodeId: 'node-flo-10-2',
    roadName: 'Rifredi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-flo-20',
    fromNodeId: 'node-flo-10-2',
    toNodeId: 'node-flo-10-3',
    roadName: 'Rifredi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
