/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Frankfurt Main Metropolis
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const FRANKFURT_BASE_COORDINATE: GeoCoordinate = {
  latitude: 50.1109,
  longitude: 8.6821,
};

export const FRANKFURT_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-fra-1-1',
    name: 'Innenstadt Sector 1 High Street',
    zone: 'Innenstadt',
    location: { latitude: 50.048900, longitude: 8.630100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Innenstadt.',
  },
  {
    id: 'node-fra-1-2',
    name: 'Innenstadt Sector 2 High Street',
    zone: 'Innenstadt',
    location: { latitude: 50.051900, longitude: 8.633100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Innenstadt.',
  },
  {
    id: 'node-fra-1-3',
    name: 'Innenstadt Sector 3 High Street',
    zone: 'Innenstadt',
    location: { latitude: 50.054900, longitude: 8.636100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Innenstadt.',
  },
  {
    id: 'node-fra-2-1',
    name: 'Sachsenhausen Sector 1 High Street',
    zone: 'Sachsenhausen',
    location: { latitude: 50.060900, longitude: 8.640100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sachsenhausen.',
  },
  {
    id: 'node-fra-2-2',
    name: 'Sachsenhausen Sector 2 High Street',
    zone: 'Sachsenhausen',
    location: { latitude: 50.063900, longitude: 8.643100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sachsenhausen.',
  },
  {
    id: 'node-fra-2-3',
    name: 'Sachsenhausen Sector 3 High Street',
    zone: 'Sachsenhausen',
    location: { latitude: 50.066900, longitude: 8.646100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sachsenhausen.',
  },
  {
    id: 'node-fra-3-1',
    name: 'Westend Sector 1 High Street',
    zone: 'Westend',
    location: { latitude: 50.072900, longitude: 8.650100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Westend.',
  },
  {
    id: 'node-fra-3-2',
    name: 'Westend Sector 2 High Street',
    zone: 'Westend',
    location: { latitude: 50.075900, longitude: 8.653100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Westend.',
  },
  {
    id: 'node-fra-3-3',
    name: 'Westend Sector 3 High Street',
    zone: 'Westend',
    location: { latitude: 50.078900, longitude: 8.656100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Westend.',
  },
  {
    id: 'node-fra-4-1',
    name: 'Nordend Sector 1 High Street',
    zone: 'Nordend',
    location: { latitude: 50.084900, longitude: 8.660100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nordend.',
  },
  {
    id: 'node-fra-4-2',
    name: 'Nordend Sector 2 High Street',
    zone: 'Nordend',
    location: { latitude: 50.087900, longitude: 8.663100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nordend.',
  },
  {
    id: 'node-fra-4-3',
    name: 'Nordend Sector 3 High Street',
    zone: 'Nordend',
    location: { latitude: 50.090900, longitude: 8.666100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nordend.',
  },
  {
    id: 'node-fra-5-1',
    name: 'Bornheim Sector 1 High Street',
    zone: 'Bornheim',
    location: { latitude: 50.096900, longitude: 8.670100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bornheim.',
  },
  {
    id: 'node-fra-5-2',
    name: 'Bornheim Sector 2 High Street',
    zone: 'Bornheim',
    location: { latitude: 50.099900, longitude: 8.673100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bornheim.',
  },
  {
    id: 'node-fra-5-3',
    name: 'Bornheim Sector 3 High Street',
    zone: 'Bornheim',
    location: { latitude: 50.102900, longitude: 8.676100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bornheim.',
  },
  {
    id: 'node-fra-6-1',
    name: 'Bahnhofsviertel Sector 1 High Street',
    zone: 'Bahnhofsviertel',
    location: { latitude: 50.108900, longitude: 8.680100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bahnhofsviertel.',
  },
  {
    id: 'node-fra-6-2',
    name: 'Bahnhofsviertel Sector 2 High Street',
    zone: 'Bahnhofsviertel',
    location: { latitude: 50.111900, longitude: 8.683100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bahnhofsviertel.',
  },
  {
    id: 'node-fra-6-3',
    name: 'Bahnhofsviertel Sector 3 High Street',
    zone: 'Bahnhofsviertel',
    location: { latitude: 50.114900, longitude: 8.686100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bahnhofsviertel.',
  },
  {
    id: 'node-fra-7-1',
    name: 'Bockenheim Sector 1 High Street',
    zone: 'Bockenheim',
    location: { latitude: 50.120900, longitude: 8.690100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bockenheim.',
  },
  {
    id: 'node-fra-7-2',
    name: 'Bockenheim Sector 2 High Street',
    zone: 'Bockenheim',
    location: { latitude: 50.123900, longitude: 8.693100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bockenheim.',
  },
  {
    id: 'node-fra-7-3',
    name: 'Bockenheim Sector 3 High Street',
    zone: 'Bockenheim',
    location: { latitude: 50.126900, longitude: 8.696100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bockenheim.',
  },
  {
    id: 'node-fra-8-1',
    name: 'Ostend Sector 1 High Street',
    zone: 'Ostend',
    location: { latitude: 50.132900, longitude: 8.700100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ostend.',
  },
  {
    id: 'node-fra-8-2',
    name: 'Ostend Sector 2 High Street',
    zone: 'Ostend',
    location: { latitude: 50.135900, longitude: 8.703100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ostend.',
  },
  {
    id: 'node-fra-8-3',
    name: 'Ostend Sector 3 High Street',
    zone: 'Ostend',
    location: { latitude: 50.138900, longitude: 8.706100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ostend.',
  },
  {
    id: 'node-fra-9-1',
    name: 'Gallus Sector 1 High Street',
    zone: 'Gallus',
    location: { latitude: 50.144900, longitude: 8.710100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gallus.',
  },
  {
    id: 'node-fra-9-2',
    name: 'Gallus Sector 2 High Street',
    zone: 'Gallus',
    location: { latitude: 50.147900, longitude: 8.713100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gallus.',
  },
  {
    id: 'node-fra-9-3',
    name: 'Gallus Sector 3 High Street',
    zone: 'Gallus',
    location: { latitude: 50.150900, longitude: 8.716100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gallus.',
  },
  {
    id: 'node-fra-10-1',
    name: 'Gutleutviertel Sector 1 High Street',
    zone: 'Gutleutviertel',
    location: { latitude: 50.156900, longitude: 8.720100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gutleutviertel.',
  },
  {
    id: 'node-fra-10-2',
    name: 'Gutleutviertel Sector 2 High Street',
    zone: 'Gutleutviertel',
    location: { latitude: 50.159900, longitude: 8.723100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gutleutviertel.',
  },
  {
    id: 'node-fra-10-3',
    name: 'Gutleutviertel Sector 3 High Street',
    zone: 'Gutleutviertel',
    location: { latitude: 50.162900, longitude: 8.726100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gutleutviertel.',
  },
];

export const FRANKFURT_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-fra-1',
    fromNodeId: 'node-fra-1-1',
    toNodeId: 'node-fra-1-2',
    roadName: 'Innenstadt Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-2',
    fromNodeId: 'node-fra-1-2',
    toNodeId: 'node-fra-1-3',
    roadName: 'Innenstadt Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-3',
    fromNodeId: 'node-fra-2-1',
    toNodeId: 'node-fra-2-2',
    roadName: 'Sachsenhausen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-4',
    fromNodeId: 'node-fra-2-2',
    toNodeId: 'node-fra-2-3',
    roadName: 'Sachsenhausen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-5',
    fromNodeId: 'node-fra-3-1',
    toNodeId: 'node-fra-3-2',
    roadName: 'Westend Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-6',
    fromNodeId: 'node-fra-3-2',
    toNodeId: 'node-fra-3-3',
    roadName: 'Westend Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-7',
    fromNodeId: 'node-fra-4-1',
    toNodeId: 'node-fra-4-2',
    roadName: 'Nordend Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-8',
    fromNodeId: 'node-fra-4-2',
    toNodeId: 'node-fra-4-3',
    roadName: 'Nordend Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-9',
    fromNodeId: 'node-fra-5-1',
    toNodeId: 'node-fra-5-2',
    roadName: 'Bornheim Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-10',
    fromNodeId: 'node-fra-5-2',
    toNodeId: 'node-fra-5-3',
    roadName: 'Bornheim Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-11',
    fromNodeId: 'node-fra-6-1',
    toNodeId: 'node-fra-6-2',
    roadName: 'Bahnhofsviertel Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-12',
    fromNodeId: 'node-fra-6-2',
    toNodeId: 'node-fra-6-3',
    roadName: 'Bahnhofsviertel Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-13',
    fromNodeId: 'node-fra-7-1',
    toNodeId: 'node-fra-7-2',
    roadName: 'Bockenheim Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-14',
    fromNodeId: 'node-fra-7-2',
    toNodeId: 'node-fra-7-3',
    roadName: 'Bockenheim Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-15',
    fromNodeId: 'node-fra-8-1',
    toNodeId: 'node-fra-8-2',
    roadName: 'Ostend Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-16',
    fromNodeId: 'node-fra-8-2',
    toNodeId: 'node-fra-8-3',
    roadName: 'Ostend Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-17',
    fromNodeId: 'node-fra-9-1',
    toNodeId: 'node-fra-9-2',
    roadName: 'Gallus Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-18',
    fromNodeId: 'node-fra-9-2',
    toNodeId: 'node-fra-9-3',
    roadName: 'Gallus Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-19',
    fromNodeId: 'node-fra-10-1',
    toNodeId: 'node-fra-10-2',
    roadName: 'Gutleutviertel Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fra-20',
    fromNodeId: 'node-fra-10-2',
    toNodeId: 'node-fra-10-3',
    roadName: 'Gutleutviertel Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
