/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Fukuoka Kyushu Food Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const FUKUOKA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 33.5904,
  longitude: 130.4017,
};

export const FUKUOKA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-fuk-1-1',
    name: 'Tenjin Sector 1 High Street',
    zone: 'Tenjin',
    location: { latitude: 33.528400, longitude: 130.349700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tenjin.',
  },
  {
    id: 'node-fuk-1-2',
    name: 'Tenjin Sector 2 High Street',
    zone: 'Tenjin',
    location: { latitude: 33.531400, longitude: 130.352700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tenjin.',
  },
  {
    id: 'node-fuk-1-3',
    name: 'Tenjin Sector 3 High Street',
    zone: 'Tenjin',
    location: { latitude: 33.534400, longitude: 130.355700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tenjin.',
  },
  {
    id: 'node-fuk-2-1',
    name: 'Hakata Sector 1 High Street',
    zone: 'Hakata',
    location: { latitude: 33.540400, longitude: 130.359700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hakata.',
  },
  {
    id: 'node-fuk-2-2',
    name: 'Hakata Sector 2 High Street',
    zone: 'Hakata',
    location: { latitude: 33.543400, longitude: 130.362700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hakata.',
  },
  {
    id: 'node-fuk-2-3',
    name: 'Hakata Sector 3 High Street',
    zone: 'Hakata',
    location: { latitude: 33.546400, longitude: 130.365700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hakata.',
  },
  {
    id: 'node-fuk-3-1',
    name: 'Nakasu Sector 1 High Street',
    zone: 'Nakasu',
    location: { latitude: 33.552400, longitude: 130.369700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nakasu.',
  },
  {
    id: 'node-fuk-3-2',
    name: 'Nakasu Sector 2 High Street',
    zone: 'Nakasu',
    location: { latitude: 33.555400, longitude: 130.372700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nakasu.',
  },
  {
    id: 'node-fuk-3-3',
    name: 'Nakasu Sector 3 High Street',
    zone: 'Nakasu',
    location: { latitude: 33.558400, longitude: 130.375700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nakasu.',
  },
  {
    id: 'node-fuk-4-1',
    name: 'Daimyo Sector 1 High Street',
    zone: 'Daimyo',
    location: { latitude: 33.564400, longitude: 130.379700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Daimyo.',
  },
  {
    id: 'node-fuk-4-2',
    name: 'Daimyo Sector 2 High Street',
    zone: 'Daimyo',
    location: { latitude: 33.567400, longitude: 130.382700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Daimyo.',
  },
  {
    id: 'node-fuk-4-3',
    name: 'Daimyo Sector 3 High Street',
    zone: 'Daimyo',
    location: { latitude: 33.570400, longitude: 130.385700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Daimyo.',
  },
  {
    id: 'node-fuk-5-1',
    name: 'Yakuin Sector 1 High Street',
    zone: 'Yakuin',
    location: { latitude: 33.576400, longitude: 130.389700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Yakuin.',
  },
  {
    id: 'node-fuk-5-2',
    name: 'Yakuin Sector 2 High Street',
    zone: 'Yakuin',
    location: { latitude: 33.579400, longitude: 130.392700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Yakuin.',
  },
  {
    id: 'node-fuk-5-3',
    name: 'Yakuin Sector 3 High Street',
    zone: 'Yakuin',
    location: { latitude: 33.582400, longitude: 130.395700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Yakuin.',
  },
  {
    id: 'node-fuk-6-1',
    name: 'Momochi Sector 1 High Street',
    zone: 'Momochi',
    location: { latitude: 33.588400, longitude: 130.399700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Momochi.',
  },
  {
    id: 'node-fuk-6-2',
    name: 'Momochi Sector 2 High Street',
    zone: 'Momochi',
    location: { latitude: 33.591400, longitude: 130.402700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Momochi.',
  },
  {
    id: 'node-fuk-6-3',
    name: 'Momochi Sector 3 High Street',
    zone: 'Momochi',
    location: { latitude: 33.594400, longitude: 130.405700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Momochi.',
  },
  {
    id: 'node-fuk-7-1',
    name: 'Nishijin Sector 1 High Street',
    zone: 'Nishijin',
    location: { latitude: 33.600400, longitude: 130.409700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nishijin.',
  },
  {
    id: 'node-fuk-7-2',
    name: 'Nishijin Sector 2 High Street',
    zone: 'Nishijin',
    location: { latitude: 33.603400, longitude: 130.412700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nishijin.',
  },
  {
    id: 'node-fuk-7-3',
    name: 'Nishijin Sector 3 High Street',
    zone: 'Nishijin',
    location: { latitude: 33.606400, longitude: 130.415700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nishijin.',
  },
  {
    id: 'node-fuk-8-1',
    name: 'Ropponmatsu Sector 1 High Street',
    zone: 'Ropponmatsu',
    location: { latitude: 33.612400, longitude: 130.419700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ropponmatsu.',
  },
  {
    id: 'node-fuk-8-2',
    name: 'Ropponmatsu Sector 2 High Street',
    zone: 'Ropponmatsu',
    location: { latitude: 33.615400, longitude: 130.422700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ropponmatsu.',
  },
  {
    id: 'node-fuk-8-3',
    name: 'Ropponmatsu Sector 3 High Street',
    zone: 'Ropponmatsu',
    location: { latitude: 33.618400, longitude: 130.425700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ropponmatsu.',
  },
  {
    id: 'node-fuk-9-1',
    name: 'Ohori Park Area Sector 1 High Street',
    zone: 'Ohori Park Area',
    location: { latitude: 33.624400, longitude: 130.429700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ohori Park Area.',
  },
  {
    id: 'node-fuk-9-2',
    name: 'Ohori Park Area Sector 2 High Street',
    zone: 'Ohori Park Area',
    location: { latitude: 33.627400, longitude: 130.432700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ohori Park Area.',
  },
  {
    id: 'node-fuk-9-3',
    name: 'Ohori Park Area Sector 3 High Street',
    zone: 'Ohori Park Area',
    location: { latitude: 33.630400, longitude: 130.435700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ohori Park Area.',
  },
  {
    id: 'node-fuk-10-1',
    name: 'Chiyo Sector 1 High Street',
    zone: 'Chiyo',
    location: { latitude: 33.636400, longitude: 130.439700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chiyo.',
  },
  {
    id: 'node-fuk-10-2',
    name: 'Chiyo Sector 2 High Street',
    zone: 'Chiyo',
    location: { latitude: 33.639400, longitude: 130.442700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chiyo.',
  },
  {
    id: 'node-fuk-10-3',
    name: 'Chiyo Sector 3 High Street',
    zone: 'Chiyo',
    location: { latitude: 33.642400, longitude: 130.445700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chiyo.',
  },
];

export const FUKUOKA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-fuk-1',
    fromNodeId: 'node-fuk-1-1',
    toNodeId: 'node-fuk-1-2',
    roadName: 'Tenjin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-2',
    fromNodeId: 'node-fuk-1-2',
    toNodeId: 'node-fuk-1-3',
    roadName: 'Tenjin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-3',
    fromNodeId: 'node-fuk-2-1',
    toNodeId: 'node-fuk-2-2',
    roadName: 'Hakata Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-4',
    fromNodeId: 'node-fuk-2-2',
    toNodeId: 'node-fuk-2-3',
    roadName: 'Hakata Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-5',
    fromNodeId: 'node-fuk-3-1',
    toNodeId: 'node-fuk-3-2',
    roadName: 'Nakasu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-6',
    fromNodeId: 'node-fuk-3-2',
    toNodeId: 'node-fuk-3-3',
    roadName: 'Nakasu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-7',
    fromNodeId: 'node-fuk-4-1',
    toNodeId: 'node-fuk-4-2',
    roadName: 'Daimyo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-8',
    fromNodeId: 'node-fuk-4-2',
    toNodeId: 'node-fuk-4-3',
    roadName: 'Daimyo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-9',
    fromNodeId: 'node-fuk-5-1',
    toNodeId: 'node-fuk-5-2',
    roadName: 'Yakuin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-10',
    fromNodeId: 'node-fuk-5-2',
    toNodeId: 'node-fuk-5-3',
    roadName: 'Yakuin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-11',
    fromNodeId: 'node-fuk-6-1',
    toNodeId: 'node-fuk-6-2',
    roadName: 'Momochi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-12',
    fromNodeId: 'node-fuk-6-2',
    toNodeId: 'node-fuk-6-3',
    roadName: 'Momochi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-13',
    fromNodeId: 'node-fuk-7-1',
    toNodeId: 'node-fuk-7-2',
    roadName: 'Nishijin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-14',
    fromNodeId: 'node-fuk-7-2',
    toNodeId: 'node-fuk-7-3',
    roadName: 'Nishijin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-15',
    fromNodeId: 'node-fuk-8-1',
    toNodeId: 'node-fuk-8-2',
    roadName: 'Ropponmatsu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-16',
    fromNodeId: 'node-fuk-8-2',
    toNodeId: 'node-fuk-8-3',
    roadName: 'Ropponmatsu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-17',
    fromNodeId: 'node-fuk-9-1',
    toNodeId: 'node-fuk-9-2',
    roadName: 'Ohori Park Area Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-18',
    fromNodeId: 'node-fuk-9-2',
    toNodeId: 'node-fuk-9-3',
    roadName: 'Ohori Park Area Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-19',
    fromNodeId: 'node-fuk-10-1',
    toNodeId: 'node-fuk-10-2',
    roadName: 'Chiyo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-fuk-20',
    fromNodeId: 'node-fuk-10-2',
    toNodeId: 'node-fuk-10-3',
    roadName: 'Chiyo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
