/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Glasgow Clyde Valley
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const GLASGOW_BASE_COORDINATE: GeoCoordinate = {
  latitude: 55.8642,
  longitude: -4.2518,
};

export const GLASGOW_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-gla-1-1',
    name: 'City Centre Glasgow Sector 1 High Street',
    zone: 'City Centre Glasgow',
    location: { latitude: 55.802200, longitude: -4.303800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in City Centre Glasgow.',
  },
  {
    id: 'node-gla-1-2',
    name: 'City Centre Glasgow Sector 2 High Street',
    zone: 'City Centre Glasgow',
    location: { latitude: 55.805200, longitude: -4.300800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in City Centre Glasgow.',
  },
  {
    id: 'node-gla-1-3',
    name: 'City Centre Glasgow Sector 3 High Street',
    zone: 'City Centre Glasgow',
    location: { latitude: 55.808200, longitude: -4.297800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in City Centre Glasgow.',
  },
  {
    id: 'node-gla-2-1',
    name: 'West End Glasgow Sector 1 High Street',
    zone: 'West End Glasgow',
    location: { latitude: 55.814200, longitude: -4.293800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in West End Glasgow.',
  },
  {
    id: 'node-gla-2-2',
    name: 'West End Glasgow Sector 2 High Street',
    zone: 'West End Glasgow',
    location: { latitude: 55.817200, longitude: -4.290800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in West End Glasgow.',
  },
  {
    id: 'node-gla-2-3',
    name: 'West End Glasgow Sector 3 High Street',
    zone: 'West End Glasgow',
    location: { latitude: 55.820200, longitude: -4.287800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in West End Glasgow.',
  },
  {
    id: 'node-gla-3-1',
    name: 'Merchant City Sector 1 High Street',
    zone: 'Merchant City',
    location: { latitude: 55.826200, longitude: -4.283800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Merchant City.',
  },
  {
    id: 'node-gla-3-2',
    name: 'Merchant City Sector 2 High Street',
    zone: 'Merchant City',
    location: { latitude: 55.829200, longitude: -4.280800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Merchant City.',
  },
  {
    id: 'node-gla-3-3',
    name: 'Merchant City Sector 3 High Street',
    zone: 'Merchant City',
    location: { latitude: 55.832200, longitude: -4.277800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Merchant City.',
  },
  {
    id: 'node-gla-4-1',
    name: 'Finnieston Sector 1 High Street',
    zone: 'Finnieston',
    location: { latitude: 55.838200, longitude: -4.273800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Finnieston.',
  },
  {
    id: 'node-gla-4-2',
    name: 'Finnieston Sector 2 High Street',
    zone: 'Finnieston',
    location: { latitude: 55.841200, longitude: -4.270800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Finnieston.',
  },
  {
    id: 'node-gla-4-3',
    name: 'Finnieston Sector 3 High Street',
    zone: 'Finnieston',
    location: { latitude: 55.844200, longitude: -4.267800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Finnieston.',
  },
  {
    id: 'node-gla-5-1',
    name: 'Shawlands Sector 1 High Street',
    zone: 'Shawlands',
    location: { latitude: 55.850200, longitude: -4.263800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shawlands.',
  },
  {
    id: 'node-gla-5-2',
    name: 'Shawlands Sector 2 High Street',
    zone: 'Shawlands',
    location: { latitude: 55.853200, longitude: -4.260800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shawlands.',
  },
  {
    id: 'node-gla-5-3',
    name: 'Shawlands Sector 3 High Street',
    zone: 'Shawlands',
    location: { latitude: 55.856200, longitude: -4.257800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shawlands.',
  },
  {
    id: 'node-gla-6-1',
    name: 'Dennistoun Sector 1 High Street',
    zone: 'Dennistoun',
    location: { latitude: 55.862200, longitude: -4.253800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dennistoun.',
  },
  {
    id: 'node-gla-6-2',
    name: 'Dennistoun Sector 2 High Street',
    zone: 'Dennistoun',
    location: { latitude: 55.865200, longitude: -4.250800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dennistoun.',
  },
  {
    id: 'node-gla-6-3',
    name: 'Dennistoun Sector 3 High Street',
    zone: 'Dennistoun',
    location: { latitude: 55.868200, longitude: -4.247800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dennistoun.',
  },
  {
    id: 'node-gla-7-1',
    name: 'Partick Sector 1 High Street',
    zone: 'Partick',
    location: { latitude: 55.874200, longitude: -4.243800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Partick.',
  },
  {
    id: 'node-gla-7-2',
    name: 'Partick Sector 2 High Street',
    zone: 'Partick',
    location: { latitude: 55.877200, longitude: -4.240800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Partick.',
  },
  {
    id: 'node-gla-7-3',
    name: 'Partick Sector 3 High Street',
    zone: 'Partick',
    location: { latitude: 55.880200, longitude: -4.237800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Partick.',
  },
  {
    id: 'node-gla-8-1',
    name: 'Southside Glasgow Sector 1 High Street',
    zone: 'Southside Glasgow',
    location: { latitude: 55.886200, longitude: -4.233800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Southside Glasgow.',
  },
  {
    id: 'node-gla-8-2',
    name: 'Southside Glasgow Sector 2 High Street',
    zone: 'Southside Glasgow',
    location: { latitude: 55.889200, longitude: -4.230800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Southside Glasgow.',
  },
  {
    id: 'node-gla-8-3',
    name: 'Southside Glasgow Sector 3 High Street',
    zone: 'Southside Glasgow',
    location: { latitude: 55.892200, longitude: -4.227800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Southside Glasgow.',
  },
  {
    id: 'node-gla-9-1',
    name: 'Hillhead Sector 1 High Street',
    zone: 'Hillhead',
    location: { latitude: 55.898200, longitude: -4.223800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hillhead.',
  },
  {
    id: 'node-gla-9-2',
    name: 'Hillhead Sector 2 High Street',
    zone: 'Hillhead',
    location: { latitude: 55.901200, longitude: -4.220800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hillhead.',
  },
  {
    id: 'node-gla-9-3',
    name: 'Hillhead Sector 3 High Street',
    zone: 'Hillhead',
    location: { latitude: 55.904200, longitude: -4.217800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hillhead.',
  },
  {
    id: 'node-gla-10-1',
    name: 'Kelvingrove Sector 1 High Street',
    zone: 'Kelvingrove',
    location: { latitude: 55.910200, longitude: -4.213800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kelvingrove.',
  },
  {
    id: 'node-gla-10-2',
    name: 'Kelvingrove Sector 2 High Street',
    zone: 'Kelvingrove',
    location: { latitude: 55.913200, longitude: -4.210800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kelvingrove.',
  },
  {
    id: 'node-gla-10-3',
    name: 'Kelvingrove Sector 3 High Street',
    zone: 'Kelvingrove',
    location: { latitude: 55.916200, longitude: -4.207800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kelvingrove.',
  },
];

export const GLASGOW_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-gla-1',
    fromNodeId: 'node-gla-1-1',
    toNodeId: 'node-gla-1-2',
    roadName: 'City Centre Glasgow Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-2',
    fromNodeId: 'node-gla-1-2',
    toNodeId: 'node-gla-1-3',
    roadName: 'City Centre Glasgow Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-3',
    fromNodeId: 'node-gla-2-1',
    toNodeId: 'node-gla-2-2',
    roadName: 'West End Glasgow Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-4',
    fromNodeId: 'node-gla-2-2',
    toNodeId: 'node-gla-2-3',
    roadName: 'West End Glasgow Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-5',
    fromNodeId: 'node-gla-3-1',
    toNodeId: 'node-gla-3-2',
    roadName: 'Merchant City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-6',
    fromNodeId: 'node-gla-3-2',
    toNodeId: 'node-gla-3-3',
    roadName: 'Merchant City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-7',
    fromNodeId: 'node-gla-4-1',
    toNodeId: 'node-gla-4-2',
    roadName: 'Finnieston Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-8',
    fromNodeId: 'node-gla-4-2',
    toNodeId: 'node-gla-4-3',
    roadName: 'Finnieston Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-9',
    fromNodeId: 'node-gla-5-1',
    toNodeId: 'node-gla-5-2',
    roadName: 'Shawlands Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-10',
    fromNodeId: 'node-gla-5-2',
    toNodeId: 'node-gla-5-3',
    roadName: 'Shawlands Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-11',
    fromNodeId: 'node-gla-6-1',
    toNodeId: 'node-gla-6-2',
    roadName: 'Dennistoun Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-12',
    fromNodeId: 'node-gla-6-2',
    toNodeId: 'node-gla-6-3',
    roadName: 'Dennistoun Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-13',
    fromNodeId: 'node-gla-7-1',
    toNodeId: 'node-gla-7-2',
    roadName: 'Partick Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-14',
    fromNodeId: 'node-gla-7-2',
    toNodeId: 'node-gla-7-3',
    roadName: 'Partick Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-15',
    fromNodeId: 'node-gla-8-1',
    toNodeId: 'node-gla-8-2',
    roadName: 'Southside Glasgow Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-16',
    fromNodeId: 'node-gla-8-2',
    toNodeId: 'node-gla-8-3',
    roadName: 'Southside Glasgow Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-17',
    fromNodeId: 'node-gla-9-1',
    toNodeId: 'node-gla-9-2',
    roadName: 'Hillhead Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-18',
    fromNodeId: 'node-gla-9-2',
    toNodeId: 'node-gla-9-3',
    roadName: 'Hillhead Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-19',
    fromNodeId: 'node-gla-10-1',
    toNodeId: 'node-gla-10-2',
    roadName: 'Kelvingrove Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gla-20',
    fromNodeId: 'node-gla-10-2',
    toNodeId: 'node-gla-10-3',
    roadName: 'Kelvingrove Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
