/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Guntur Chilli Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const GUNTUR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 16.3067,
  longitude: 80.4365,
};

export const GUNTUR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-gun-1-1',
    name: 'Brodipet Sector 1 High Street',
    zone: 'Brodipet',
    location: { latitude: 16.244700, longitude: 80.384500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Brodipet.',
  },
  {
    id: 'node-gun-1-2',
    name: 'Brodipet Sector 2 High Street',
    zone: 'Brodipet',
    location: { latitude: 16.247700, longitude: 80.387500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Brodipet.',
  },
  {
    id: 'node-gun-1-3',
    name: 'Brodipet Sector 3 High Street',
    zone: 'Brodipet',
    location: { latitude: 16.250700, longitude: 80.390500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Brodipet.',
  },
  {
    id: 'node-gun-2-1',
    name: 'Arundelpet Sector 1 High Street',
    zone: 'Arundelpet',
    location: { latitude: 16.256700, longitude: 80.394500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Arundelpet.',
  },
  {
    id: 'node-gun-2-2',
    name: 'Arundelpet Sector 2 High Street',
    zone: 'Arundelpet',
    location: { latitude: 16.259700, longitude: 80.397500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Arundelpet.',
  },
  {
    id: 'node-gun-2-3',
    name: 'Arundelpet Sector 3 High Street',
    zone: 'Arundelpet',
    location: { latitude: 16.262700, longitude: 80.400500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Arundelpet.',
  },
  {
    id: 'node-gun-3-1',
    name: 'Lakshmipuram Sector 1 High Street',
    zone: 'Lakshmipuram',
    location: { latitude: 16.268700, longitude: 80.404500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lakshmipuram.',
  },
  {
    id: 'node-gun-3-2',
    name: 'Lakshmipuram Sector 2 High Street',
    zone: 'Lakshmipuram',
    location: { latitude: 16.271700, longitude: 80.407500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lakshmipuram.',
  },
  {
    id: 'node-gun-3-3',
    name: 'Lakshmipuram Sector 3 High Street',
    zone: 'Lakshmipuram',
    location: { latitude: 16.274700, longitude: 80.410500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lakshmipuram.',
  },
  {
    id: 'node-gun-4-1',
    name: 'Kothapet Sector 1 High Street',
    zone: 'Kothapet',
    location: { latitude: 16.280700, longitude: 80.414500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kothapet.',
  },
  {
    id: 'node-gun-4-2',
    name: 'Kothapet Sector 2 High Street',
    zone: 'Kothapet',
    location: { latitude: 16.283700, longitude: 80.417500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kothapet.',
  },
  {
    id: 'node-gun-4-3',
    name: 'Kothapet Sector 3 High Street',
    zone: 'Kothapet',
    location: { latitude: 16.286700, longitude: 80.420500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kothapet.',
  },
  {
    id: 'node-gun-5-1',
    name: 'Nallapadu Sector 1 High Street',
    zone: 'Nallapadu',
    location: { latitude: 16.292700, longitude: 80.424500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nallapadu.',
  },
  {
    id: 'node-gun-5-2',
    name: 'Nallapadu Sector 2 High Street',
    zone: 'Nallapadu',
    location: { latitude: 16.295700, longitude: 80.427500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nallapadu.',
  },
  {
    id: 'node-gun-5-3',
    name: 'Nallapadu Sector 3 High Street',
    zone: 'Nallapadu',
    location: { latitude: 16.298700, longitude: 80.430500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nallapadu.',
  },
  {
    id: 'node-gun-6-1',
    name: 'Pattabhipuram Sector 1 High Street',
    zone: 'Pattabhipuram',
    location: { latitude: 16.304700, longitude: 80.434500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pattabhipuram.',
  },
  {
    id: 'node-gun-6-2',
    name: 'Pattabhipuram Sector 2 High Street',
    zone: 'Pattabhipuram',
    location: { latitude: 16.307700, longitude: 80.437500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pattabhipuram.',
  },
  {
    id: 'node-gun-6-3',
    name: 'Pattabhipuram Sector 3 High Street',
    zone: 'Pattabhipuram',
    location: { latitude: 16.310700, longitude: 80.440500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pattabhipuram.',
  },
  {
    id: 'node-gun-7-1',
    name: 'Stambalagaruvu Sector 1 High Street',
    zone: 'Stambalagaruvu',
    location: { latitude: 16.316700, longitude: 80.444500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Stambalagaruvu.',
  },
  {
    id: 'node-gun-7-2',
    name: 'Stambalagaruvu Sector 2 High Street',
    zone: 'Stambalagaruvu',
    location: { latitude: 16.319700, longitude: 80.447500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Stambalagaruvu.',
  },
  {
    id: 'node-gun-7-3',
    name: 'Stambalagaruvu Sector 3 High Street',
    zone: 'Stambalagaruvu',
    location: { latitude: 16.322700, longitude: 80.450500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Stambalagaruvu.',
  },
  {
    id: 'node-gun-8-1',
    name: 'Ring Road Guntur Sector 1 High Street',
    zone: 'Ring Road Guntur',
    location: { latitude: 16.328700, longitude: 80.454500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ring Road Guntur.',
  },
  {
    id: 'node-gun-8-2',
    name: 'Ring Road Guntur Sector 2 High Street',
    zone: 'Ring Road Guntur',
    location: { latitude: 16.331700, longitude: 80.457500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ring Road Guntur.',
  },
  {
    id: 'node-gun-8-3',
    name: 'Ring Road Guntur Sector 3 High Street',
    zone: 'Ring Road Guntur',
    location: { latitude: 16.334700, longitude: 80.460500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ring Road Guntur.',
  },
  {
    id: 'node-gun-9-1',
    name: 'Vidya Nagar Sector 1 High Street',
    zone: 'Vidya Nagar',
    location: { latitude: 16.340700, longitude: 80.464500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vidya Nagar.',
  },
  {
    id: 'node-gun-9-2',
    name: 'Vidya Nagar Sector 2 High Street',
    zone: 'Vidya Nagar',
    location: { latitude: 16.343700, longitude: 80.467500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vidya Nagar.',
  },
  {
    id: 'node-gun-9-3',
    name: 'Vidya Nagar Sector 3 High Street',
    zone: 'Vidya Nagar',
    location: { latitude: 16.346700, longitude: 80.470500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vidya Nagar.',
  },
  {
    id: 'node-gun-10-1',
    name: 'Autonagar Sector 1 High Street',
    zone: 'Autonagar',
    location: { latitude: 16.352700, longitude: 80.474500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Autonagar.',
  },
  {
    id: 'node-gun-10-2',
    name: 'Autonagar Sector 2 High Street',
    zone: 'Autonagar',
    location: { latitude: 16.355700, longitude: 80.477500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Autonagar.',
  },
  {
    id: 'node-gun-10-3',
    name: 'Autonagar Sector 3 High Street',
    zone: 'Autonagar',
    location: { latitude: 16.358700, longitude: 80.480500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Autonagar.',
  },
];

export const GUNTUR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-gun-1',
    fromNodeId: 'node-gun-1-1',
    toNodeId: 'node-gun-1-2',
    roadName: 'Brodipet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-2',
    fromNodeId: 'node-gun-1-2',
    toNodeId: 'node-gun-1-3',
    roadName: 'Brodipet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-3',
    fromNodeId: 'node-gun-2-1',
    toNodeId: 'node-gun-2-2',
    roadName: 'Arundelpet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-4',
    fromNodeId: 'node-gun-2-2',
    toNodeId: 'node-gun-2-3',
    roadName: 'Arundelpet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-5',
    fromNodeId: 'node-gun-3-1',
    toNodeId: 'node-gun-3-2',
    roadName: 'Lakshmipuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-6',
    fromNodeId: 'node-gun-3-2',
    toNodeId: 'node-gun-3-3',
    roadName: 'Lakshmipuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-7',
    fromNodeId: 'node-gun-4-1',
    toNodeId: 'node-gun-4-2',
    roadName: 'Kothapet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-8',
    fromNodeId: 'node-gun-4-2',
    toNodeId: 'node-gun-4-3',
    roadName: 'Kothapet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-9',
    fromNodeId: 'node-gun-5-1',
    toNodeId: 'node-gun-5-2',
    roadName: 'Nallapadu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-10',
    fromNodeId: 'node-gun-5-2',
    toNodeId: 'node-gun-5-3',
    roadName: 'Nallapadu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-11',
    fromNodeId: 'node-gun-6-1',
    toNodeId: 'node-gun-6-2',
    roadName: 'Pattabhipuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-12',
    fromNodeId: 'node-gun-6-2',
    toNodeId: 'node-gun-6-3',
    roadName: 'Pattabhipuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-13',
    fromNodeId: 'node-gun-7-1',
    toNodeId: 'node-gun-7-2',
    roadName: 'Stambalagaruvu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-14',
    fromNodeId: 'node-gun-7-2',
    toNodeId: 'node-gun-7-3',
    roadName: 'Stambalagaruvu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-15',
    fromNodeId: 'node-gun-8-1',
    toNodeId: 'node-gun-8-2',
    roadName: 'Ring Road Guntur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-16',
    fromNodeId: 'node-gun-8-2',
    toNodeId: 'node-gun-8-3',
    roadName: 'Ring Road Guntur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-17',
    fromNodeId: 'node-gun-9-1',
    toNodeId: 'node-gun-9-2',
    roadName: 'Vidya Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-18',
    fromNodeId: 'node-gun-9-2',
    toNodeId: 'node-gun-9-3',
    roadName: 'Vidya Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-19',
    fromNodeId: 'node-gun-10-1',
    toNodeId: 'node-gun-10-2',
    roadName: 'Autonagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-gun-20',
    fromNodeId: 'node-gun-10-2',
    toNodeId: 'node-gun-10-3',
    roadName: 'Autonagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
