/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Guwahati Brahmaputra Gateway
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const GUWAHATI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 26.1445,
  longitude: 91.7362,
};

export const GUWAHATI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-guw-1-1',
    name: 'GS Road Sector 1 High Street',
    zone: 'GS Road',
    location: { latitude: 26.082500, longitude: 91.684200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in GS Road.',
  },
  {
    id: 'node-guw-1-2',
    name: 'GS Road Sector 2 High Street',
    zone: 'GS Road',
    location: { latitude: 26.085500, longitude: 91.687200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in GS Road.',
  },
  {
    id: 'node-guw-1-3',
    name: 'GS Road Sector 3 High Street',
    zone: 'GS Road',
    location: { latitude: 26.088500, longitude: 91.690200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in GS Road.',
  },
  {
    id: 'node-guw-2-1',
    name: 'Christian Basti Sector 1 High Street',
    zone: 'Christian Basti',
    location: { latitude: 26.094500, longitude: 91.694200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Christian Basti.',
  },
  {
    id: 'node-guw-2-2',
    name: 'Christian Basti Sector 2 High Street',
    zone: 'Christian Basti',
    location: { latitude: 26.097500, longitude: 91.697200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Christian Basti.',
  },
  {
    id: 'node-guw-2-3',
    name: 'Christian Basti Sector 3 High Street',
    zone: 'Christian Basti',
    location: { latitude: 26.100500, longitude: 91.700200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Christian Basti.',
  },
  {
    id: 'node-guw-3-1',
    name: 'Ulubari Sector 1 High Street',
    zone: 'Ulubari',
    location: { latitude: 26.106500, longitude: 91.704200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ulubari.',
  },
  {
    id: 'node-guw-3-2',
    name: 'Ulubari Sector 2 High Street',
    zone: 'Ulubari',
    location: { latitude: 26.109500, longitude: 91.707200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ulubari.',
  },
  {
    id: 'node-guw-3-3',
    name: 'Ulubari Sector 3 High Street',
    zone: 'Ulubari',
    location: { latitude: 26.112500, longitude: 91.710200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ulubari.',
  },
  {
    id: 'node-guw-4-1',
    name: 'Beltola Sector 1 High Street',
    zone: 'Beltola',
    location: { latitude: 26.118500, longitude: 91.714200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Beltola.',
  },
  {
    id: 'node-guw-4-2',
    name: 'Beltola Sector 2 High Street',
    zone: 'Beltola',
    location: { latitude: 26.121500, longitude: 91.717200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Beltola.',
  },
  {
    id: 'node-guw-4-3',
    name: 'Beltola Sector 3 High Street',
    zone: 'Beltola',
    location: { latitude: 26.124500, longitude: 91.720200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Beltola.',
  },
  {
    id: 'node-guw-5-1',
    name: 'Zoo Road Sector 1 High Street',
    zone: 'Zoo Road',
    location: { latitude: 26.130500, longitude: 91.724200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zoo Road.',
  },
  {
    id: 'node-guw-5-2',
    name: 'Zoo Road Sector 2 High Street',
    zone: 'Zoo Road',
    location: { latitude: 26.133500, longitude: 91.727200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zoo Road.',
  },
  {
    id: 'node-guw-5-3',
    name: 'Zoo Road Sector 3 High Street',
    zone: 'Zoo Road',
    location: { latitude: 26.136500, longitude: 91.730200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zoo Road.',
  },
  {
    id: 'node-guw-6-1',
    name: 'Ganeshguri Sector 1 High Street',
    zone: 'Ganeshguri',
    location: { latitude: 26.142500, longitude: 91.734200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ganeshguri.',
  },
  {
    id: 'node-guw-6-2',
    name: 'Ganeshguri Sector 2 High Street',
    zone: 'Ganeshguri',
    location: { latitude: 26.145500, longitude: 91.737200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ganeshguri.',
  },
  {
    id: 'node-guw-6-3',
    name: 'Ganeshguri Sector 3 High Street',
    zone: 'Ganeshguri',
    location: { latitude: 26.148500, longitude: 91.740200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ganeshguri.',
  },
  {
    id: 'node-guw-7-1',
    name: 'Pan Bazaar Sector 1 High Street',
    zone: 'Pan Bazaar',
    location: { latitude: 26.154500, longitude: 91.744200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pan Bazaar.',
  },
  {
    id: 'node-guw-7-2',
    name: 'Pan Bazaar Sector 2 High Street',
    zone: 'Pan Bazaar',
    location: { latitude: 26.157500, longitude: 91.747200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pan Bazaar.',
  },
  {
    id: 'node-guw-7-3',
    name: 'Pan Bazaar Sector 3 High Street',
    zone: 'Pan Bazaar',
    location: { latitude: 26.160500, longitude: 91.750200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pan Bazaar.',
  },
  {
    id: 'node-guw-8-1',
    name: 'Dispur Capital Sector 1 High Street',
    zone: 'Dispur Capital',
    location: { latitude: 26.166500, longitude: 91.754200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dispur Capital.',
  },
  {
    id: 'node-guw-8-2',
    name: 'Dispur Capital Sector 2 High Street',
    zone: 'Dispur Capital',
    location: { latitude: 26.169500, longitude: 91.757200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dispur Capital.',
  },
  {
    id: 'node-guw-8-3',
    name: 'Dispur Capital Sector 3 High Street',
    zone: 'Dispur Capital',
    location: { latitude: 26.172500, longitude: 91.760200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dispur Capital.',
  },
  {
    id: 'node-guw-9-1',
    name: 'Six Mile Sector 1 High Street',
    zone: 'Six Mile',
    location: { latitude: 26.178500, longitude: 91.764200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Six Mile.',
  },
  {
    id: 'node-guw-9-2',
    name: 'Six Mile Sector 2 High Street',
    zone: 'Six Mile',
    location: { latitude: 26.181500, longitude: 91.767200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Six Mile.',
  },
  {
    id: 'node-guw-9-3',
    name: 'Six Mile Sector 3 High Street',
    zone: 'Six Mile',
    location: { latitude: 26.184500, longitude: 91.770200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Six Mile.',
  },
  {
    id: 'node-guw-10-1',
    name: 'Jalukbari Sector 1 High Street',
    zone: 'Jalukbari',
    location: { latitude: 26.190500, longitude: 91.774200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jalukbari.',
  },
  {
    id: 'node-guw-10-2',
    name: 'Jalukbari Sector 2 High Street',
    zone: 'Jalukbari',
    location: { latitude: 26.193500, longitude: 91.777200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jalukbari.',
  },
  {
    id: 'node-guw-10-3',
    name: 'Jalukbari Sector 3 High Street',
    zone: 'Jalukbari',
    location: { latitude: 26.196500, longitude: 91.780200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jalukbari.',
  },
];

export const GUWAHATI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-guw-1',
    fromNodeId: 'node-guw-1-1',
    toNodeId: 'node-guw-1-2',
    roadName: 'GS Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-2',
    fromNodeId: 'node-guw-1-2',
    toNodeId: 'node-guw-1-3',
    roadName: 'GS Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-3',
    fromNodeId: 'node-guw-2-1',
    toNodeId: 'node-guw-2-2',
    roadName: 'Christian Basti Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-4',
    fromNodeId: 'node-guw-2-2',
    toNodeId: 'node-guw-2-3',
    roadName: 'Christian Basti Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-5',
    fromNodeId: 'node-guw-3-1',
    toNodeId: 'node-guw-3-2',
    roadName: 'Ulubari Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-6',
    fromNodeId: 'node-guw-3-2',
    toNodeId: 'node-guw-3-3',
    roadName: 'Ulubari Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-7',
    fromNodeId: 'node-guw-4-1',
    toNodeId: 'node-guw-4-2',
    roadName: 'Beltola Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-8',
    fromNodeId: 'node-guw-4-2',
    toNodeId: 'node-guw-4-3',
    roadName: 'Beltola Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-9',
    fromNodeId: 'node-guw-5-1',
    toNodeId: 'node-guw-5-2',
    roadName: 'Zoo Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-10',
    fromNodeId: 'node-guw-5-2',
    toNodeId: 'node-guw-5-3',
    roadName: 'Zoo Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-11',
    fromNodeId: 'node-guw-6-1',
    toNodeId: 'node-guw-6-2',
    roadName: 'Ganeshguri Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-12',
    fromNodeId: 'node-guw-6-2',
    toNodeId: 'node-guw-6-3',
    roadName: 'Ganeshguri Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-13',
    fromNodeId: 'node-guw-7-1',
    toNodeId: 'node-guw-7-2',
    roadName: 'Pan Bazaar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-14',
    fromNodeId: 'node-guw-7-2',
    toNodeId: 'node-guw-7-3',
    roadName: 'Pan Bazaar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-15',
    fromNodeId: 'node-guw-8-1',
    toNodeId: 'node-guw-8-2',
    roadName: 'Dispur Capital Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-16',
    fromNodeId: 'node-guw-8-2',
    toNodeId: 'node-guw-8-3',
    roadName: 'Dispur Capital Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-17',
    fromNodeId: 'node-guw-9-1',
    toNodeId: 'node-guw-9-2',
    roadName: 'Six Mile Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-18',
    fromNodeId: 'node-guw-9-2',
    toNodeId: 'node-guw-9-3',
    roadName: 'Six Mile Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-19',
    fromNodeId: 'node-guw-10-1',
    toNodeId: 'node-guw-10-2',
    roadName: 'Jalukbari Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-guw-20',
    fromNodeId: 'node-guw-10-2',
    toNodeId: 'node-guw-10-3',
    roadName: 'Jalukbari Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
