/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Hanoi Old Quarter & West Lake
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const HANOI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 21.0285,
  longitude: 105.8542,
};

export const HANOI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-han-1-1',
    name: 'Old Quarter Hanoi Sector 1 High Street',
    zone: 'Old Quarter Hanoi',
    location: { latitude: 20.966500, longitude: 105.802200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old Quarter Hanoi.',
  },
  {
    id: 'node-han-1-2',
    name: 'Old Quarter Hanoi Sector 2 High Street',
    zone: 'Old Quarter Hanoi',
    location: { latitude: 20.969500, longitude: 105.805200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old Quarter Hanoi.',
  },
  {
    id: 'node-han-1-3',
    name: 'Old Quarter Hanoi Sector 3 High Street',
    zone: 'Old Quarter Hanoi',
    location: { latitude: 20.972500, longitude: 105.808200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old Quarter Hanoi.',
  },
  {
    id: 'node-han-2-1',
    name: 'Tay Ho West Lake Sector 1 High Street',
    zone: 'Tay Ho West Lake',
    location: { latitude: 20.978500, longitude: 105.812200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tay Ho West Lake.',
  },
  {
    id: 'node-han-2-2',
    name: 'Tay Ho West Lake Sector 2 High Street',
    zone: 'Tay Ho West Lake',
    location: { latitude: 20.981500, longitude: 105.815200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tay Ho West Lake.',
  },
  {
    id: 'node-han-2-3',
    name: 'Tay Ho West Lake Sector 3 High Street',
    zone: 'Tay Ho West Lake',
    location: { latitude: 20.984500, longitude: 105.818200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tay Ho West Lake.',
  },
  {
    id: 'node-han-3-1',
    name: 'Hoan Kiem Sector 1 High Street',
    zone: 'Hoan Kiem',
    location: { latitude: 20.990500, longitude: 105.822200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hoan Kiem.',
  },
  {
    id: 'node-han-3-2',
    name: 'Hoan Kiem Sector 2 High Street',
    zone: 'Hoan Kiem',
    location: { latitude: 20.993500, longitude: 105.825200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hoan Kiem.',
  },
  {
    id: 'node-han-3-3',
    name: 'Hoan Kiem Sector 3 High Street',
    zone: 'Hoan Kiem',
    location: { latitude: 20.996500, longitude: 105.828200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hoan Kiem.',
  },
  {
    id: 'node-han-4-1',
    name: 'Ba Dinh Sector 1 High Street',
    zone: 'Ba Dinh',
    location: { latitude: 21.002500, longitude: 105.832200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ba Dinh.',
  },
  {
    id: 'node-han-4-2',
    name: 'Ba Dinh Sector 2 High Street',
    zone: 'Ba Dinh',
    location: { latitude: 21.005500, longitude: 105.835200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ba Dinh.',
  },
  {
    id: 'node-han-4-3',
    name: 'Ba Dinh Sector 3 High Street',
    zone: 'Ba Dinh',
    location: { latitude: 21.008500, longitude: 105.838200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ba Dinh.',
  },
  {
    id: 'node-han-5-1',
    name: 'Cau Giay Sector 1 High Street',
    zone: 'Cau Giay',
    location: { latitude: 21.014500, longitude: 105.842200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cau Giay.',
  },
  {
    id: 'node-han-5-2',
    name: 'Cau Giay Sector 2 High Street',
    zone: 'Cau Giay',
    location: { latitude: 21.017500, longitude: 105.845200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cau Giay.',
  },
  {
    id: 'node-han-5-3',
    name: 'Cau Giay Sector 3 High Street',
    zone: 'Cau Giay',
    location: { latitude: 21.020500, longitude: 105.848200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cau Giay.',
  },
  {
    id: 'node-han-6-1',
    name: 'Hai Ba Trung Sector 1 High Street',
    zone: 'Hai Ba Trung',
    location: { latitude: 21.026500, longitude: 105.852200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hai Ba Trung.',
  },
  {
    id: 'node-han-6-2',
    name: 'Hai Ba Trung Sector 2 High Street',
    zone: 'Hai Ba Trung',
    location: { latitude: 21.029500, longitude: 105.855200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hai Ba Trung.',
  },
  {
    id: 'node-han-6-3',
    name: 'Hai Ba Trung Sector 3 High Street',
    zone: 'Hai Ba Trung',
    location: { latitude: 21.032500, longitude: 105.858200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hai Ba Trung.',
  },
  {
    id: 'node-han-7-1',
    name: 'Dong Da Sector 1 High Street',
    zone: 'Dong Da',
    location: { latitude: 21.038500, longitude: 105.862200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dong Da.',
  },
  {
    id: 'node-han-7-2',
    name: 'Dong Da Sector 2 High Street',
    zone: 'Dong Da',
    location: { latitude: 21.041500, longitude: 105.865200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dong Da.',
  },
  {
    id: 'node-han-7-3',
    name: 'Dong Da Sector 3 High Street',
    zone: 'Dong Da',
    location: { latitude: 21.044500, longitude: 105.868200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dong Da.',
  },
  {
    id: 'node-han-8-1',
    name: 'Trang Tien Sector 1 High Street',
    zone: 'Trang Tien',
    location: { latitude: 21.050500, longitude: 105.872200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Trang Tien.',
  },
  {
    id: 'node-han-8-2',
    name: 'Trang Tien Sector 2 High Street',
    zone: 'Trang Tien',
    location: { latitude: 21.053500, longitude: 105.875200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Trang Tien.',
  },
  {
    id: 'node-han-8-3',
    name: 'Trang Tien Sector 3 High Street',
    zone: 'Trang Tien',
    location: { latitude: 21.056500, longitude: 105.878200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Trang Tien.',
  },
  {
    id: 'node-han-9-1',
    name: 'My Dinh Sector 1 High Street',
    zone: 'My Dinh',
    location: { latitude: 21.062500, longitude: 105.882200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in My Dinh.',
  },
  {
    id: 'node-han-9-2',
    name: 'My Dinh Sector 2 High Street',
    zone: 'My Dinh',
    location: { latitude: 21.065500, longitude: 105.885200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in My Dinh.',
  },
  {
    id: 'node-han-9-3',
    name: 'My Dinh Sector 3 High Street',
    zone: 'My Dinh',
    location: { latitude: 21.068500, longitude: 105.888200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in My Dinh.',
  },
  {
    id: 'node-han-10-1',
    name: 'Long Bien Sector 1 High Street',
    zone: 'Long Bien',
    location: { latitude: 21.074500, longitude: 105.892200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Long Bien.',
  },
  {
    id: 'node-han-10-2',
    name: 'Long Bien Sector 2 High Street',
    zone: 'Long Bien',
    location: { latitude: 21.077500, longitude: 105.895200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Long Bien.',
  },
  {
    id: 'node-han-10-3',
    name: 'Long Bien Sector 3 High Street',
    zone: 'Long Bien',
    location: { latitude: 21.080500, longitude: 105.898200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Long Bien.',
  },
];

export const HANOI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-han-1',
    fromNodeId: 'node-han-1-1',
    toNodeId: 'node-han-1-2',
    roadName: 'Old Quarter Hanoi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-2',
    fromNodeId: 'node-han-1-2',
    toNodeId: 'node-han-1-3',
    roadName: 'Old Quarter Hanoi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-3',
    fromNodeId: 'node-han-2-1',
    toNodeId: 'node-han-2-2',
    roadName: 'Tay Ho West Lake Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-4',
    fromNodeId: 'node-han-2-2',
    toNodeId: 'node-han-2-3',
    roadName: 'Tay Ho West Lake Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-5',
    fromNodeId: 'node-han-3-1',
    toNodeId: 'node-han-3-2',
    roadName: 'Hoan Kiem Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-6',
    fromNodeId: 'node-han-3-2',
    toNodeId: 'node-han-3-3',
    roadName: 'Hoan Kiem Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-7',
    fromNodeId: 'node-han-4-1',
    toNodeId: 'node-han-4-2',
    roadName: 'Ba Dinh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-8',
    fromNodeId: 'node-han-4-2',
    toNodeId: 'node-han-4-3',
    roadName: 'Ba Dinh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-9',
    fromNodeId: 'node-han-5-1',
    toNodeId: 'node-han-5-2',
    roadName: 'Cau Giay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-10',
    fromNodeId: 'node-han-5-2',
    toNodeId: 'node-han-5-3',
    roadName: 'Cau Giay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-11',
    fromNodeId: 'node-han-6-1',
    toNodeId: 'node-han-6-2',
    roadName: 'Hai Ba Trung Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-12',
    fromNodeId: 'node-han-6-2',
    toNodeId: 'node-han-6-3',
    roadName: 'Hai Ba Trung Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-13',
    fromNodeId: 'node-han-7-1',
    toNodeId: 'node-han-7-2',
    roadName: 'Dong Da Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-14',
    fromNodeId: 'node-han-7-2',
    toNodeId: 'node-han-7-3',
    roadName: 'Dong Da Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-15',
    fromNodeId: 'node-han-8-1',
    toNodeId: 'node-han-8-2',
    roadName: 'Trang Tien Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-16',
    fromNodeId: 'node-han-8-2',
    toNodeId: 'node-han-8-3',
    roadName: 'Trang Tien Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-17',
    fromNodeId: 'node-han-9-1',
    toNodeId: 'node-han-9-2',
    roadName: 'My Dinh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-18',
    fromNodeId: 'node-han-9-2',
    toNodeId: 'node-han-9-3',
    roadName: 'My Dinh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-19',
    fromNodeId: 'node-han-10-1',
    toNodeId: 'node-han-10-2',
    roadName: 'Long Bien Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-han-20',
    fromNodeId: 'node-han-10-2',
    toNodeId: 'node-han-10-3',
    roadName: 'Long Bien Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
