/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Helsinki Baltic Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const HELSINKI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 60.1699,
  longitude: 24.9384,
};

export const HELSINKI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-hel-1-1',
    name: 'Kluuvi Sector 1 High Street',
    zone: 'Kluuvi',
    location: { latitude: 60.107900, longitude: 24.886400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kluuvi.',
  },
  {
    id: 'node-hel-1-2',
    name: 'Kluuvi Sector 2 High Street',
    zone: 'Kluuvi',
    location: { latitude: 60.110900, longitude: 24.889400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kluuvi.',
  },
  {
    id: 'node-hel-1-3',
    name: 'Kluuvi Sector 3 High Street',
    zone: 'Kluuvi',
    location: { latitude: 60.113900, longitude: 24.892400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kluuvi.',
  },
  {
    id: 'node-hel-2-1',
    name: 'Kamppi Sector 1 High Street',
    zone: 'Kamppi',
    location: { latitude: 60.119900, longitude: 24.896400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kamppi.',
  },
  {
    id: 'node-hel-2-2',
    name: 'Kamppi Sector 2 High Street',
    zone: 'Kamppi',
    location: { latitude: 60.122900, longitude: 24.899400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kamppi.',
  },
  {
    id: 'node-hel-2-3',
    name: 'Kamppi Sector 3 High Street',
    zone: 'Kamppi',
    location: { latitude: 60.125900, longitude: 24.902400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kamppi.',
  },
  {
    id: 'node-hel-3-1',
    name: 'Punavuori Sector 1 High Street',
    zone: 'Punavuori',
    location: { latitude: 60.131900, longitude: 24.906400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Punavuori.',
  },
  {
    id: 'node-hel-3-2',
    name: 'Punavuori Sector 2 High Street',
    zone: 'Punavuori',
    location: { latitude: 60.134900, longitude: 24.909400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Punavuori.',
  },
  {
    id: 'node-hel-3-3',
    name: 'Punavuori Sector 3 High Street',
    zone: 'Punavuori',
    location: { latitude: 60.137900, longitude: 24.912400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Punavuori.',
  },
  {
    id: 'node-hel-4-1',
    name: 'Kallio Sector 1 High Street',
    zone: 'Kallio',
    location: { latitude: 60.143900, longitude: 24.916400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kallio.',
  },
  {
    id: 'node-hel-4-2',
    name: 'Kallio Sector 2 High Street',
    zone: 'Kallio',
    location: { latitude: 60.146900, longitude: 24.919400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kallio.',
  },
  {
    id: 'node-hel-4-3',
    name: 'Kallio Sector 3 High Street',
    zone: 'Kallio',
    location: { latitude: 60.149900, longitude: 24.922400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kallio.',
  },
  {
    id: 'node-hel-5-1',
    name: 'Töölö Sector 1 High Street',
    zone: 'Töölö',
    location: { latitude: 60.155900, longitude: 24.926400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Töölö.',
  },
  {
    id: 'node-hel-5-2',
    name: 'Töölö Sector 2 High Street',
    zone: 'Töölö',
    location: { latitude: 60.158900, longitude: 24.929400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Töölö.',
  },
  {
    id: 'node-hel-5-3',
    name: 'Töölö Sector 3 High Street',
    zone: 'Töölö',
    location: { latitude: 60.161900, longitude: 24.932400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Töölö.',
  },
  {
    id: 'node-hel-6-1',
    name: 'Ullanlinna Sector 1 High Street',
    zone: 'Ullanlinna',
    location: { latitude: 60.167900, longitude: 24.936400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ullanlinna.',
  },
  {
    id: 'node-hel-6-2',
    name: 'Ullanlinna Sector 2 High Street',
    zone: 'Ullanlinna',
    location: { latitude: 60.170900, longitude: 24.939400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ullanlinna.',
  },
  {
    id: 'node-hel-6-3',
    name: 'Ullanlinna Sector 3 High Street',
    zone: 'Ullanlinna',
    location: { latitude: 60.173900, longitude: 24.942400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ullanlinna.',
  },
  {
    id: 'node-hel-7-1',
    name: 'Eira Sector 1 High Street',
    zone: 'Eira',
    location: { latitude: 60.179900, longitude: 24.946400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Eira.',
  },
  {
    id: 'node-hel-7-2',
    name: 'Eira Sector 2 High Street',
    zone: 'Eira',
    location: { latitude: 60.182900, longitude: 24.949400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Eira.',
  },
  {
    id: 'node-hel-7-3',
    name: 'Eira Sector 3 High Street',
    zone: 'Eira',
    location: { latitude: 60.185900, longitude: 24.952400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Eira.',
  },
  {
    id: 'node-hel-8-1',
    name: 'Ruoholahti Sector 1 High Street',
    zone: 'Ruoholahti',
    location: { latitude: 60.191900, longitude: 24.956400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ruoholahti.',
  },
  {
    id: 'node-hel-8-2',
    name: 'Ruoholahti Sector 2 High Street',
    zone: 'Ruoholahti',
    location: { latitude: 60.194900, longitude: 24.959400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ruoholahti.',
  },
  {
    id: 'node-hel-8-3',
    name: 'Ruoholahti Sector 3 High Street',
    zone: 'Ruoholahti',
    location: { latitude: 60.197900, longitude: 24.962400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ruoholahti.',
  },
  {
    id: 'node-hel-9-1',
    name: 'Vallila Sector 1 High Street',
    zone: 'Vallila',
    location: { latitude: 60.203900, longitude: 24.966400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vallila.',
  },
  {
    id: 'node-hel-9-2',
    name: 'Vallila Sector 2 High Street',
    zone: 'Vallila',
    location: { latitude: 60.206900, longitude: 24.969400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vallila.',
  },
  {
    id: 'node-hel-9-3',
    name: 'Vallila Sector 3 High Street',
    zone: 'Vallila',
    location: { latitude: 60.209900, longitude: 24.972400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vallila.',
  },
  {
    id: 'node-hel-10-1',
    name: 'Pasila Sector 1 High Street',
    zone: 'Pasila',
    location: { latitude: 60.215900, longitude: 24.976400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pasila.',
  },
  {
    id: 'node-hel-10-2',
    name: 'Pasila Sector 2 High Street',
    zone: 'Pasila',
    location: { latitude: 60.218900, longitude: 24.979400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pasila.',
  },
  {
    id: 'node-hel-10-3',
    name: 'Pasila Sector 3 High Street',
    zone: 'Pasila',
    location: { latitude: 60.221900, longitude: 24.982400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pasila.',
  },
];

export const HELSINKI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-hel-1',
    fromNodeId: 'node-hel-1-1',
    toNodeId: 'node-hel-1-2',
    roadName: 'Kluuvi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-2',
    fromNodeId: 'node-hel-1-2',
    toNodeId: 'node-hel-1-3',
    roadName: 'Kluuvi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-3',
    fromNodeId: 'node-hel-2-1',
    toNodeId: 'node-hel-2-2',
    roadName: 'Kamppi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-4',
    fromNodeId: 'node-hel-2-2',
    toNodeId: 'node-hel-2-3',
    roadName: 'Kamppi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-5',
    fromNodeId: 'node-hel-3-1',
    toNodeId: 'node-hel-3-2',
    roadName: 'Punavuori Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-6',
    fromNodeId: 'node-hel-3-2',
    toNodeId: 'node-hel-3-3',
    roadName: 'Punavuori Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-7',
    fromNodeId: 'node-hel-4-1',
    toNodeId: 'node-hel-4-2',
    roadName: 'Kallio Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-8',
    fromNodeId: 'node-hel-4-2',
    toNodeId: 'node-hel-4-3',
    roadName: 'Kallio Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-9',
    fromNodeId: 'node-hel-5-1',
    toNodeId: 'node-hel-5-2',
    roadName: 'Töölö Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-10',
    fromNodeId: 'node-hel-5-2',
    toNodeId: 'node-hel-5-3',
    roadName: 'Töölö Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-11',
    fromNodeId: 'node-hel-6-1',
    toNodeId: 'node-hel-6-2',
    roadName: 'Ullanlinna Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-12',
    fromNodeId: 'node-hel-6-2',
    toNodeId: 'node-hel-6-3',
    roadName: 'Ullanlinna Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-13',
    fromNodeId: 'node-hel-7-1',
    toNodeId: 'node-hel-7-2',
    roadName: 'Eira Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-14',
    fromNodeId: 'node-hel-7-2',
    toNodeId: 'node-hel-7-3',
    roadName: 'Eira Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-15',
    fromNodeId: 'node-hel-8-1',
    toNodeId: 'node-hel-8-2',
    roadName: 'Ruoholahti Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-16',
    fromNodeId: 'node-hel-8-2',
    toNodeId: 'node-hel-8-3',
    roadName: 'Ruoholahti Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-17',
    fromNodeId: 'node-hel-9-1',
    toNodeId: 'node-hel-9-2',
    roadName: 'Vallila Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-18',
    fromNodeId: 'node-hel-9-2',
    toNodeId: 'node-hel-9-3',
    roadName: 'Vallila Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-19',
    fromNodeId: 'node-hel-10-1',
    toNodeId: 'node-hel-10-2',
    roadName: 'Pasila Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hel-20',
    fromNodeId: 'node-hel-10-2',
    toNodeId: 'node-hel-10-3',
    roadName: 'Pasila Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
