/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Ho Chi Minh City Saigon Core
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const HOCHIMINH_BASE_COORDINATE: GeoCoordinate = {
  latitude: 10.8231,
  longitude: 106.6297,
};

export const HOCHIMINH_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-hoc-1-1',
    name: 'District 1 Central Sector 1 High Street',
    zone: 'District 1 Central',
    location: { latitude: 10.761100, longitude: 106.577700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District 1 Central.',
  },
  {
    id: 'node-hoc-1-2',
    name: 'District 1 Central Sector 2 High Street',
    zone: 'District 1 Central',
    location: { latitude: 10.764100, longitude: 106.580700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District 1 Central.',
  },
  {
    id: 'node-hoc-1-3',
    name: 'District 1 Central Sector 3 High Street',
    zone: 'District 1 Central',
    location: { latitude: 10.767100, longitude: 106.583700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District 1 Central.',
  },
  {
    id: 'node-hoc-2-1',
    name: 'District 2 Thao Dien Sector 1 High Street',
    zone: 'District 2 Thao Dien',
    location: { latitude: 10.773100, longitude: 106.587700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District 2 Thao Dien.',
  },
  {
    id: 'node-hoc-2-2',
    name: 'District 2 Thao Dien Sector 2 High Street',
    zone: 'District 2 Thao Dien',
    location: { latitude: 10.776100, longitude: 106.590700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District 2 Thao Dien.',
  },
  {
    id: 'node-hoc-2-3',
    name: 'District 2 Thao Dien Sector 3 High Street',
    zone: 'District 2 Thao Dien',
    location: { latitude: 10.779100, longitude: 106.593700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District 2 Thao Dien.',
  },
  {
    id: 'node-hoc-3-1',
    name: 'District 3 Sector 1 High Street',
    zone: 'District 3',
    location: { latitude: 10.785100, longitude: 106.597700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District 3.',
  },
  {
    id: 'node-hoc-3-2',
    name: 'District 3 Sector 2 High Street',
    zone: 'District 3',
    location: { latitude: 10.788100, longitude: 106.600700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District 3.',
  },
  {
    id: 'node-hoc-3-3',
    name: 'District 3 Sector 3 High Street',
    zone: 'District 3',
    location: { latitude: 10.791100, longitude: 106.603700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District 3.',
  },
  {
    id: 'node-hoc-4-1',
    name: 'District 7 Phu My Hung Sector 1 High Street',
    zone: 'District 7 Phu My Hung',
    location: { latitude: 10.797100, longitude: 106.607700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District 7 Phu My Hung.',
  },
  {
    id: 'node-hoc-4-2',
    name: 'District 7 Phu My Hung Sector 2 High Street',
    zone: 'District 7 Phu My Hung',
    location: { latitude: 10.800100, longitude: 106.610700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District 7 Phu My Hung.',
  },
  {
    id: 'node-hoc-4-3',
    name: 'District 7 Phu My Hung Sector 3 High Street',
    zone: 'District 7 Phu My Hung',
    location: { latitude: 10.803100, longitude: 106.613700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District 7 Phu My Hung.',
  },
  {
    id: 'node-hoc-5-1',
    name: 'Binh Thanh Sector 1 High Street',
    zone: 'Binh Thanh',
    location: { latitude: 10.809100, longitude: 106.617700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Binh Thanh.',
  },
  {
    id: 'node-hoc-5-2',
    name: 'Binh Thanh Sector 2 High Street',
    zone: 'Binh Thanh',
    location: { latitude: 10.812100, longitude: 106.620700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Binh Thanh.',
  },
  {
    id: 'node-hoc-5-3',
    name: 'Binh Thanh Sector 3 High Street',
    zone: 'Binh Thanh',
    location: { latitude: 10.815100, longitude: 106.623700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Binh Thanh.',
  },
  {
    id: 'node-hoc-6-1',
    name: 'Phu Nhuan Sector 1 High Street',
    zone: 'Phu Nhuan',
    location: { latitude: 10.821100, longitude: 106.627700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Phu Nhuan.',
  },
  {
    id: 'node-hoc-6-2',
    name: 'Phu Nhuan Sector 2 High Street',
    zone: 'Phu Nhuan',
    location: { latitude: 10.824100, longitude: 106.630700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Phu Nhuan.',
  },
  {
    id: 'node-hoc-6-3',
    name: 'Phu Nhuan Sector 3 High Street',
    zone: 'Phu Nhuan',
    location: { latitude: 10.827100, longitude: 106.633700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Phu Nhuan.',
  },
  {
    id: 'node-hoc-7-1',
    name: 'District 4 Sector 1 High Street',
    zone: 'District 4',
    location: { latitude: 10.833100, longitude: 106.637700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District 4.',
  },
  {
    id: 'node-hoc-7-2',
    name: 'District 4 Sector 2 High Street',
    zone: 'District 4',
    location: { latitude: 10.836100, longitude: 106.640700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District 4.',
  },
  {
    id: 'node-hoc-7-3',
    name: 'District 4 Sector 3 High Street',
    zone: 'District 4',
    location: { latitude: 10.839100, longitude: 106.643700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District 4.',
  },
  {
    id: 'node-hoc-8-1',
    name: 'District 5 Cho Lon Sector 1 High Street',
    zone: 'District 5 Cho Lon',
    location: { latitude: 10.845100, longitude: 106.647700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District 5 Cho Lon.',
  },
  {
    id: 'node-hoc-8-2',
    name: 'District 5 Cho Lon Sector 2 High Street',
    zone: 'District 5 Cho Lon',
    location: { latitude: 10.848100, longitude: 106.650700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District 5 Cho Lon.',
  },
  {
    id: 'node-hoc-8-3',
    name: 'District 5 Cho Lon Sector 3 High Street',
    zone: 'District 5 Cho Lon',
    location: { latitude: 10.851100, longitude: 106.653700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District 5 Cho Lon.',
  },
  {
    id: 'node-hoc-9-1',
    name: 'District 10 Sector 1 High Street',
    zone: 'District 10',
    location: { latitude: 10.857100, longitude: 106.657700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in District 10.',
  },
  {
    id: 'node-hoc-9-2',
    name: 'District 10 Sector 2 High Street',
    zone: 'District 10',
    location: { latitude: 10.860100, longitude: 106.660700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in District 10.',
  },
  {
    id: 'node-hoc-9-3',
    name: 'District 10 Sector 3 High Street',
    zone: 'District 10',
    location: { latitude: 10.863100, longitude: 106.663700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in District 10.',
  },
  {
    id: 'node-hoc-10-1',
    name: 'Tan Binh Sector 1 High Street',
    zone: 'Tan Binh',
    location: { latitude: 10.869100, longitude: 106.667700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tan Binh.',
  },
  {
    id: 'node-hoc-10-2',
    name: 'Tan Binh Sector 2 High Street',
    zone: 'Tan Binh',
    location: { latitude: 10.872100, longitude: 106.670700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tan Binh.',
  },
  {
    id: 'node-hoc-10-3',
    name: 'Tan Binh Sector 3 High Street',
    zone: 'Tan Binh',
    location: { latitude: 10.875100, longitude: 106.673700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tan Binh.',
  },
];

export const HOCHIMINH_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-hoc-1',
    fromNodeId: 'node-hoc-1-1',
    toNodeId: 'node-hoc-1-2',
    roadName: 'District 1 Central Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-2',
    fromNodeId: 'node-hoc-1-2',
    toNodeId: 'node-hoc-1-3',
    roadName: 'District 1 Central Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-3',
    fromNodeId: 'node-hoc-2-1',
    toNodeId: 'node-hoc-2-2',
    roadName: 'District 2 Thao Dien Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-4',
    fromNodeId: 'node-hoc-2-2',
    toNodeId: 'node-hoc-2-3',
    roadName: 'District 2 Thao Dien Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-5',
    fromNodeId: 'node-hoc-3-1',
    toNodeId: 'node-hoc-3-2',
    roadName: 'District 3 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-6',
    fromNodeId: 'node-hoc-3-2',
    toNodeId: 'node-hoc-3-3',
    roadName: 'District 3 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-7',
    fromNodeId: 'node-hoc-4-1',
    toNodeId: 'node-hoc-4-2',
    roadName: 'District 7 Phu My Hung Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-8',
    fromNodeId: 'node-hoc-4-2',
    toNodeId: 'node-hoc-4-3',
    roadName: 'District 7 Phu My Hung Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-9',
    fromNodeId: 'node-hoc-5-1',
    toNodeId: 'node-hoc-5-2',
    roadName: 'Binh Thanh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-10',
    fromNodeId: 'node-hoc-5-2',
    toNodeId: 'node-hoc-5-3',
    roadName: 'Binh Thanh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-11',
    fromNodeId: 'node-hoc-6-1',
    toNodeId: 'node-hoc-6-2',
    roadName: 'Phu Nhuan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-12',
    fromNodeId: 'node-hoc-6-2',
    toNodeId: 'node-hoc-6-3',
    roadName: 'Phu Nhuan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-13',
    fromNodeId: 'node-hoc-7-1',
    toNodeId: 'node-hoc-7-2',
    roadName: 'District 4 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-14',
    fromNodeId: 'node-hoc-7-2',
    toNodeId: 'node-hoc-7-3',
    roadName: 'District 4 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-15',
    fromNodeId: 'node-hoc-8-1',
    toNodeId: 'node-hoc-8-2',
    roadName: 'District 5 Cho Lon Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-16',
    fromNodeId: 'node-hoc-8-2',
    toNodeId: 'node-hoc-8-3',
    roadName: 'District 5 Cho Lon Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-17',
    fromNodeId: 'node-hoc-9-1',
    toNodeId: 'node-hoc-9-2',
    roadName: 'District 10 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-18',
    fromNodeId: 'node-hoc-9-2',
    toNodeId: 'node-hoc-9-3',
    roadName: 'District 10 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-19',
    fromNodeId: 'node-hoc-10-1',
    toNodeId: 'node-hoc-10-2',
    roadName: 'Tan Binh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hoc-20',
    fromNodeId: 'node-hoc-10-2',
    toNodeId: 'node-hoc-10-3',
    roadName: 'Tan Binh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
