/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Houston Energy Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const HOUSTON_BASE_COORDINATE: GeoCoordinate = {
  latitude: 29.7604,
  longitude: -95.3698,
};

export const HOUSTON_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-hou-1-1',
    name: 'Downtown Houston Sector 1 High Street',
    zone: 'Downtown Houston',
    location: { latitude: 29.698400, longitude: -95.421800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Houston.',
  },
  {
    id: 'node-hou-1-2',
    name: 'Downtown Houston Sector 2 High Street',
    zone: 'Downtown Houston',
    location: { latitude: 29.701400, longitude: -95.418800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Houston.',
  },
  {
    id: 'node-hou-1-3',
    name: 'Downtown Houston Sector 3 High Street',
    zone: 'Downtown Houston',
    location: { latitude: 29.704400, longitude: -95.415800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Houston.',
  },
  {
    id: 'node-hou-2-1',
    name: 'Montrose Sector 1 High Street',
    zone: 'Montrose',
    location: { latitude: 29.710400, longitude: -95.411800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Montrose.',
  },
  {
    id: 'node-hou-2-2',
    name: 'Montrose Sector 2 High Street',
    zone: 'Montrose',
    location: { latitude: 29.713400, longitude: -95.408800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Montrose.',
  },
  {
    id: 'node-hou-2-3',
    name: 'Montrose Sector 3 High Street',
    zone: 'Montrose',
    location: { latitude: 29.716400, longitude: -95.405800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Montrose.',
  },
  {
    id: 'node-hou-3-1',
    name: 'The Heights Sector 1 High Street',
    zone: 'The Heights',
    location: { latitude: 29.722400, longitude: -95.401800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in The Heights.',
  },
  {
    id: 'node-hou-3-2',
    name: 'The Heights Sector 2 High Street',
    zone: 'The Heights',
    location: { latitude: 29.725400, longitude: -95.398800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in The Heights.',
  },
  {
    id: 'node-hou-3-3',
    name: 'The Heights Sector 3 High Street',
    zone: 'The Heights',
    location: { latitude: 29.728400, longitude: -95.395800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in The Heights.',
  },
  {
    id: 'node-hou-4-1',
    name: 'Midtown Houston Sector 1 High Street',
    zone: 'Midtown Houston',
    location: { latitude: 29.734400, longitude: -95.391800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Midtown Houston.',
  },
  {
    id: 'node-hou-4-2',
    name: 'Midtown Houston Sector 2 High Street',
    zone: 'Midtown Houston',
    location: { latitude: 29.737400, longitude: -95.388800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Midtown Houston.',
  },
  {
    id: 'node-hou-4-3',
    name: 'Midtown Houston Sector 3 High Street',
    zone: 'Midtown Houston',
    location: { latitude: 29.740400, longitude: -95.385800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Midtown Houston.',
  },
  {
    id: 'node-hou-5-1',
    name: 'Galleria Sector 1 High Street',
    zone: 'Galleria',
    location: { latitude: 29.746400, longitude: -95.381800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Galleria.',
  },
  {
    id: 'node-hou-5-2',
    name: 'Galleria Sector 2 High Street',
    zone: 'Galleria',
    location: { latitude: 29.749400, longitude: -95.378800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Galleria.',
  },
  {
    id: 'node-hou-5-3',
    name: 'Galleria Sector 3 High Street',
    zone: 'Galleria',
    location: { latitude: 29.752400, longitude: -95.375800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Galleria.',
  },
  {
    id: 'node-hou-6-1',
    name: 'River Oaks Sector 1 High Street',
    zone: 'River Oaks',
    location: { latitude: 29.758400, longitude: -95.371800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in River Oaks.',
  },
  {
    id: 'node-hou-6-2',
    name: 'River Oaks Sector 2 High Street',
    zone: 'River Oaks',
    location: { latitude: 29.761400, longitude: -95.368800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in River Oaks.',
  },
  {
    id: 'node-hou-6-3',
    name: 'River Oaks Sector 3 High Street',
    zone: 'River Oaks',
    location: { latitude: 29.764400, longitude: -95.365800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in River Oaks.',
  },
  {
    id: 'node-hou-7-1',
    name: 'Rice Military Sector 1 High Street',
    zone: 'Rice Military',
    location: { latitude: 29.770400, longitude: -95.361800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rice Military.',
  },
  {
    id: 'node-hou-7-2',
    name: 'Rice Military Sector 2 High Street',
    zone: 'Rice Military',
    location: { latitude: 29.773400, longitude: -95.358800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rice Military.',
  },
  {
    id: 'node-hou-7-3',
    name: 'Rice Military Sector 3 High Street',
    zone: 'Rice Military',
    location: { latitude: 29.776400, longitude: -95.355800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rice Military.',
  },
  {
    id: 'node-hou-8-1',
    name: 'Medical Center Sector 1 High Street',
    zone: 'Medical Center',
    location: { latitude: 29.782400, longitude: -95.351800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Medical Center.',
  },
  {
    id: 'node-hou-8-2',
    name: 'Medical Center Sector 2 High Street',
    zone: 'Medical Center',
    location: { latitude: 29.785400, longitude: -95.348800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Medical Center.',
  },
  {
    id: 'node-hou-8-3',
    name: 'Medical Center Sector 3 High Street',
    zone: 'Medical Center',
    location: { latitude: 29.788400, longitude: -95.345800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Medical Center.',
  },
  {
    id: 'node-hou-9-1',
    name: 'EaDo Sector 1 High Street',
    zone: 'EaDo',
    location: { latitude: 29.794400, longitude: -95.341800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in EaDo.',
  },
  {
    id: 'node-hou-9-2',
    name: 'EaDo Sector 2 High Street',
    zone: 'EaDo',
    location: { latitude: 29.797400, longitude: -95.338800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in EaDo.',
  },
  {
    id: 'node-hou-9-3',
    name: 'EaDo Sector 3 High Street',
    zone: 'EaDo',
    location: { latitude: 29.800400, longitude: -95.335800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in EaDo.',
  },
  {
    id: 'node-hou-10-1',
    name: 'Energy Corridor Sector 1 High Street',
    zone: 'Energy Corridor',
    location: { latitude: 29.806400, longitude: -95.331800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Energy Corridor.',
  },
  {
    id: 'node-hou-10-2',
    name: 'Energy Corridor Sector 2 High Street',
    zone: 'Energy Corridor',
    location: { latitude: 29.809400, longitude: -95.328800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Energy Corridor.',
  },
  {
    id: 'node-hou-10-3',
    name: 'Energy Corridor Sector 3 High Street',
    zone: 'Energy Corridor',
    location: { latitude: 29.812400, longitude: -95.325800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Energy Corridor.',
  },
];

export const HOUSTON_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-hou-1',
    fromNodeId: 'node-hou-1-1',
    toNodeId: 'node-hou-1-2',
    roadName: 'Downtown Houston Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-2',
    fromNodeId: 'node-hou-1-2',
    toNodeId: 'node-hou-1-3',
    roadName: 'Downtown Houston Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-3',
    fromNodeId: 'node-hou-2-1',
    toNodeId: 'node-hou-2-2',
    roadName: 'Montrose Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-4',
    fromNodeId: 'node-hou-2-2',
    toNodeId: 'node-hou-2-3',
    roadName: 'Montrose Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-5',
    fromNodeId: 'node-hou-3-1',
    toNodeId: 'node-hou-3-2',
    roadName: 'The Heights Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-6',
    fromNodeId: 'node-hou-3-2',
    toNodeId: 'node-hou-3-3',
    roadName: 'The Heights Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-7',
    fromNodeId: 'node-hou-4-1',
    toNodeId: 'node-hou-4-2',
    roadName: 'Midtown Houston Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-8',
    fromNodeId: 'node-hou-4-2',
    toNodeId: 'node-hou-4-3',
    roadName: 'Midtown Houston Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-9',
    fromNodeId: 'node-hou-5-1',
    toNodeId: 'node-hou-5-2',
    roadName: 'Galleria Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-10',
    fromNodeId: 'node-hou-5-2',
    toNodeId: 'node-hou-5-3',
    roadName: 'Galleria Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-11',
    fromNodeId: 'node-hou-6-1',
    toNodeId: 'node-hou-6-2',
    roadName: 'River Oaks Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-12',
    fromNodeId: 'node-hou-6-2',
    toNodeId: 'node-hou-6-3',
    roadName: 'River Oaks Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-13',
    fromNodeId: 'node-hou-7-1',
    toNodeId: 'node-hou-7-2',
    roadName: 'Rice Military Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-14',
    fromNodeId: 'node-hou-7-2',
    toNodeId: 'node-hou-7-3',
    roadName: 'Rice Military Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-15',
    fromNodeId: 'node-hou-8-1',
    toNodeId: 'node-hou-8-2',
    roadName: 'Medical Center Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-16',
    fromNodeId: 'node-hou-8-2',
    toNodeId: 'node-hou-8-3',
    roadName: 'Medical Center Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-17',
    fromNodeId: 'node-hou-9-1',
    toNodeId: 'node-hou-9-2',
    roadName: 'EaDo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-18',
    fromNodeId: 'node-hou-9-2',
    toNodeId: 'node-hou-9-3',
    roadName: 'EaDo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-19',
    fromNodeId: 'node-hou-10-1',
    toNodeId: 'node-hou-10-2',
    roadName: 'Energy Corridor Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hou-20',
    fromNodeId: 'node-hou-10-2',
    toNodeId: 'node-hou-10-3',
    roadName: 'Energy Corridor Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
