/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Hubballi-Dharwad Twin City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const HUBLI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 15.3647,
  longitude: 75.124,
};

export const HUBLI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-hub-1-1',
    name: 'Vidyanagar Sector 1 High Street',
    zone: 'Vidyanagar',
    location: { latitude: 15.302700, longitude: 75.072000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vidyanagar.',
  },
  {
    id: 'node-hub-1-2',
    name: 'Vidyanagar Sector 2 High Street',
    zone: 'Vidyanagar',
    location: { latitude: 15.305700, longitude: 75.075000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vidyanagar.',
  },
  {
    id: 'node-hub-1-3',
    name: 'Vidyanagar Sector 3 High Street',
    zone: 'Vidyanagar',
    location: { latitude: 15.308700, longitude: 75.078000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vidyanagar.',
  },
  {
    id: 'node-hub-2-1',
    name: 'Gokul Road Sector 1 High Street',
    zone: 'Gokul Road',
    location: { latitude: 15.314700, longitude: 75.082000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gokul Road.',
  },
  {
    id: 'node-hub-2-2',
    name: 'Gokul Road Sector 2 High Street',
    zone: 'Gokul Road',
    location: { latitude: 15.317700, longitude: 75.085000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gokul Road.',
  },
  {
    id: 'node-hub-2-3',
    name: 'Gokul Road Sector 3 High Street',
    zone: 'Gokul Road',
    location: { latitude: 15.320700, longitude: 75.088000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gokul Road.',
  },
  {
    id: 'node-hub-3-1',
    name: 'Shirur Park Sector 1 High Street',
    zone: 'Shirur Park',
    location: { latitude: 15.326700, longitude: 75.092000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shirur Park.',
  },
  {
    id: 'node-hub-3-2',
    name: 'Shirur Park Sector 2 High Street',
    zone: 'Shirur Park',
    location: { latitude: 15.329700, longitude: 75.095000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shirur Park.',
  },
  {
    id: 'node-hub-3-3',
    name: 'Shirur Park Sector 3 High Street',
    zone: 'Shirur Park',
    location: { latitude: 15.332700, longitude: 75.098000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shirur Park.',
  },
  {
    id: 'node-hub-4-1',
    name: 'Keshwapur Sector 1 High Street',
    zone: 'Keshwapur',
    location: { latitude: 15.338700, longitude: 75.102000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Keshwapur.',
  },
  {
    id: 'node-hub-4-2',
    name: 'Keshwapur Sector 2 High Street',
    zone: 'Keshwapur',
    location: { latitude: 15.341700, longitude: 75.105000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Keshwapur.',
  },
  {
    id: 'node-hub-4-3',
    name: 'Keshwapur Sector 3 High Street',
    zone: 'Keshwapur',
    location: { latitude: 15.344700, longitude: 75.108000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Keshwapur.',
  },
  {
    id: 'node-hub-5-1',
    name: 'Navanagar Sector 1 High Street',
    zone: 'Navanagar',
    location: { latitude: 15.350700, longitude: 75.112000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Navanagar.',
  },
  {
    id: 'node-hub-5-2',
    name: 'Navanagar Sector 2 High Street',
    zone: 'Navanagar',
    location: { latitude: 15.353700, longitude: 75.115000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Navanagar.',
  },
  {
    id: 'node-hub-5-3',
    name: 'Navanagar Sector 3 High Street',
    zone: 'Navanagar',
    location: { latitude: 15.356700, longitude: 75.118000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Navanagar.',
  },
  {
    id: 'node-hub-6-1',
    name: 'Unkal Lake Sector 1 High Street',
    zone: 'Unkal Lake',
    location: { latitude: 15.362700, longitude: 75.122000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Unkal Lake.',
  },
  {
    id: 'node-hub-6-2',
    name: 'Unkal Lake Sector 2 High Street',
    zone: 'Unkal Lake',
    location: { latitude: 15.365700, longitude: 75.125000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Unkal Lake.',
  },
  {
    id: 'node-hub-6-3',
    name: 'Unkal Lake Sector 3 High Street',
    zone: 'Unkal Lake',
    location: { latitude: 15.368700, longitude: 75.128000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Unkal Lake.',
  },
  {
    id: 'node-hub-7-1',
    name: 'PB Road Sector 1 High Street',
    zone: 'PB Road',
    location: { latitude: 15.374700, longitude: 75.132000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in PB Road.',
  },
  {
    id: 'node-hub-7-2',
    name: 'PB Road Sector 2 High Street',
    zone: 'PB Road',
    location: { latitude: 15.377700, longitude: 75.135000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in PB Road.',
  },
  {
    id: 'node-hub-7-3',
    name: 'PB Road Sector 3 High Street',
    zone: 'PB Road',
    location: { latitude: 15.380700, longitude: 75.138000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in PB Road.',
  },
  {
    id: 'node-hub-8-1',
    name: 'Deshpande Nagar Sector 1 High Street',
    zone: 'Deshpande Nagar',
    location: { latitude: 15.386700, longitude: 75.142000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Deshpande Nagar.',
  },
  {
    id: 'node-hub-8-2',
    name: 'Deshpande Nagar Sector 2 High Street',
    zone: 'Deshpande Nagar',
    location: { latitude: 15.389700, longitude: 75.145000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Deshpande Nagar.',
  },
  {
    id: 'node-hub-8-3',
    name: 'Deshpande Nagar Sector 3 High Street',
    zone: 'Deshpande Nagar',
    location: { latitude: 15.392700, longitude: 75.148000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Deshpande Nagar.',
  },
  {
    id: 'node-hub-9-1',
    name: 'Rayapur Sector 1 High Street',
    zone: 'Rayapur',
    location: { latitude: 15.398700, longitude: 75.152000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rayapur.',
  },
  {
    id: 'node-hub-9-2',
    name: 'Rayapur Sector 2 High Street',
    zone: 'Rayapur',
    location: { latitude: 15.401700, longitude: 75.155000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rayapur.',
  },
  {
    id: 'node-hub-9-3',
    name: 'Rayapur Sector 3 High Street',
    zone: 'Rayapur',
    location: { latitude: 15.404700, longitude: 75.158000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rayapur.',
  },
  {
    id: 'node-hub-10-1',
    name: 'Koppikar Road Sector 1 High Street',
    zone: 'Koppikar Road',
    location: { latitude: 15.410700, longitude: 75.162000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Koppikar Road.',
  },
  {
    id: 'node-hub-10-2',
    name: 'Koppikar Road Sector 2 High Street',
    zone: 'Koppikar Road',
    location: { latitude: 15.413700, longitude: 75.165000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Koppikar Road.',
  },
  {
    id: 'node-hub-10-3',
    name: 'Koppikar Road Sector 3 High Street',
    zone: 'Koppikar Road',
    location: { latitude: 15.416700, longitude: 75.168000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Koppikar Road.',
  },
];

export const HUBLI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-hub-1',
    fromNodeId: 'node-hub-1-1',
    toNodeId: 'node-hub-1-2',
    roadName: 'Vidyanagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-2',
    fromNodeId: 'node-hub-1-2',
    toNodeId: 'node-hub-1-3',
    roadName: 'Vidyanagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-3',
    fromNodeId: 'node-hub-2-1',
    toNodeId: 'node-hub-2-2',
    roadName: 'Gokul Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-4',
    fromNodeId: 'node-hub-2-2',
    toNodeId: 'node-hub-2-3',
    roadName: 'Gokul Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-5',
    fromNodeId: 'node-hub-3-1',
    toNodeId: 'node-hub-3-2',
    roadName: 'Shirur Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-6',
    fromNodeId: 'node-hub-3-2',
    toNodeId: 'node-hub-3-3',
    roadName: 'Shirur Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-7',
    fromNodeId: 'node-hub-4-1',
    toNodeId: 'node-hub-4-2',
    roadName: 'Keshwapur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-8',
    fromNodeId: 'node-hub-4-2',
    toNodeId: 'node-hub-4-3',
    roadName: 'Keshwapur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-9',
    fromNodeId: 'node-hub-5-1',
    toNodeId: 'node-hub-5-2',
    roadName: 'Navanagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-10',
    fromNodeId: 'node-hub-5-2',
    toNodeId: 'node-hub-5-3',
    roadName: 'Navanagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-11',
    fromNodeId: 'node-hub-6-1',
    toNodeId: 'node-hub-6-2',
    roadName: 'Unkal Lake Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-12',
    fromNodeId: 'node-hub-6-2',
    toNodeId: 'node-hub-6-3',
    roadName: 'Unkal Lake Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-13',
    fromNodeId: 'node-hub-7-1',
    toNodeId: 'node-hub-7-2',
    roadName: 'PB Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-14',
    fromNodeId: 'node-hub-7-2',
    toNodeId: 'node-hub-7-3',
    roadName: 'PB Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-15',
    fromNodeId: 'node-hub-8-1',
    toNodeId: 'node-hub-8-2',
    roadName: 'Deshpande Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-16',
    fromNodeId: 'node-hub-8-2',
    toNodeId: 'node-hub-8-3',
    roadName: 'Deshpande Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-17',
    fromNodeId: 'node-hub-9-1',
    toNodeId: 'node-hub-9-2',
    roadName: 'Rayapur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-18',
    fromNodeId: 'node-hub-9-2',
    toNodeId: 'node-hub-9-3',
    roadName: 'Rayapur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-19',
    fromNodeId: 'node-hub-10-1',
    toNodeId: 'node-hub-10-2',
    roadName: 'Koppikar Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hub-20',
    fromNodeId: 'node-hub-10-2',
    toNodeId: 'node-hub-10-3',
    roadName: 'Koppikar Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
