/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Hyderabad Cyberabad Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const HYDERABAD_BASE_COORDINATE: GeoCoordinate = {
  latitude: 17.385,
  longitude: 78.4867,
};

export const HYDERABAD_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-hyd-1-1',
    name: 'Hitech City Sector 1 Road',
    zone: 'Hitech City',
    location: { latitude: 17.313000, longitude: 78.434700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Hitech City commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-1-2',
    name: 'Hitech City Sector 2 Road',
    zone: 'Hitech City',
    location: { latitude: 17.316000, longitude: 78.437700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Hitech City commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-1-3',
    name: 'Hitech City Sector 3 Road',
    zone: 'Hitech City',
    location: { latitude: 17.319000, longitude: 78.440700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Hitech City commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-2-1',
    name: 'Gachibowli Sector 1 Road',
    zone: 'Gachibowli',
    location: { latitude: 17.328000, longitude: 78.446700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Gachibowli commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-2-2',
    name: 'Gachibowli Sector 2 Road',
    zone: 'Gachibowli',
    location: { latitude: 17.331000, longitude: 78.449700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Gachibowli commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-2-3',
    name: 'Gachibowli Sector 3 Road',
    zone: 'Gachibowli',
    location: { latitude: 17.334000, longitude: 78.452700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Gachibowli commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-3-1',
    name: 'Jubilee Hills Sector 1 Road',
    zone: 'Jubilee Hills',
    location: { latitude: 17.343000, longitude: 78.458700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Jubilee Hills commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-3-2',
    name: 'Jubilee Hills Sector 2 Road',
    zone: 'Jubilee Hills',
    location: { latitude: 17.346000, longitude: 78.461700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Jubilee Hills commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-3-3',
    name: 'Jubilee Hills Sector 3 Road',
    zone: 'Jubilee Hills',
    location: { latitude: 17.349000, longitude: 78.464700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Jubilee Hills commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-4-1',
    name: 'Banjara Hills Sector 1 Road',
    zone: 'Banjara Hills',
    location: { latitude: 17.358000, longitude: 78.470700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Banjara Hills commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-4-2',
    name: 'Banjara Hills Sector 2 Road',
    zone: 'Banjara Hills',
    location: { latitude: 17.361000, longitude: 78.473700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Banjara Hills commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-4-3',
    name: 'Banjara Hills Sector 3 Road',
    zone: 'Banjara Hills',
    location: { latitude: 17.364000, longitude: 78.476700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Banjara Hills commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-5-1',
    name: 'Madhapur Sector 1 Road',
    zone: 'Madhapur',
    location: { latitude: 17.373000, longitude: 78.482700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Madhapur commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-5-2',
    name: 'Madhapur Sector 2 Road',
    zone: 'Madhapur',
    location: { latitude: 17.376000, longitude: 78.485700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Madhapur commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-5-3',
    name: 'Madhapur Sector 3 Road',
    zone: 'Madhapur',
    location: { latitude: 17.379000, longitude: 78.488700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Madhapur commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-6-1',
    name: 'Kondapur Sector 1 Road',
    zone: 'Kondapur',
    location: { latitude: 17.388000, longitude: 78.494700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Kondapur commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-6-2',
    name: 'Kondapur Sector 2 Road',
    zone: 'Kondapur',
    location: { latitude: 17.391000, longitude: 78.497700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Kondapur commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-6-3',
    name: 'Kondapur Sector 3 Road',
    zone: 'Kondapur',
    location: { latitude: 17.394000, longitude: 78.500700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Kondapur commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-7-1',
    name: 'Kukatpally Sector 1 Road',
    zone: 'Kukatpally',
    location: { latitude: 17.403000, longitude: 78.506700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Kukatpally commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-7-2',
    name: 'Kukatpally Sector 2 Road',
    zone: 'Kukatpally',
    location: { latitude: 17.406000, longitude: 78.509700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Kukatpally commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-7-3',
    name: 'Kukatpally Sector 3 Road',
    zone: 'Kukatpally',
    location: { latitude: 17.409000, longitude: 78.512700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Kukatpally commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-8-1',
    name: 'Begumpet Sector 1 Road',
    zone: 'Begumpet',
    location: { latitude: 17.418000, longitude: 78.518700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Begumpet commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-8-2',
    name: 'Begumpet Sector 2 Road',
    zone: 'Begumpet',
    location: { latitude: 17.421000, longitude: 78.521700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Begumpet commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-8-3',
    name: 'Begumpet Sector 3 Road',
    zone: 'Begumpet',
    location: { latitude: 17.424000, longitude: 78.524700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Begumpet commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-9-1',
    name: 'Secunderabad Sector 1 Road',
    zone: 'Secunderabad',
    location: { latitude: 17.433000, longitude: 78.530700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Secunderabad commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-9-2',
    name: 'Secunderabad Sector 2 Road',
    zone: 'Secunderabad',
    location: { latitude: 17.436000, longitude: 78.533700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Secunderabad commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-9-3',
    name: 'Secunderabad Sector 3 Road',
    zone: 'Secunderabad',
    location: { latitude: 17.439000, longitude: 78.536700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Secunderabad commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-10-1',
    name: 'Manikonda Sector 1 Road',
    zone: 'Manikonda',
    location: { latitude: 17.448000, longitude: 78.542700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Manikonda commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-10-2',
    name: 'Manikonda Sector 2 Road',
    zone: 'Manikonda',
    location: { latitude: 17.451000, longitude: 78.545700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Manikonda commercial centers and residential communities.',
  },
  {
    id: 'node-hyd-10-3',
    name: 'Manikonda Sector 3 Road',
    zone: 'Manikonda',
    location: { latitude: 17.454000, longitude: 78.548700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Manikonda commercial centers and residential communities.',
  },
];

export const HYDERABAD_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-hyd-1',
    fromNodeId: 'node-hyd-1-1',
    toNodeId: 'node-hyd-1-2',
    roadName: 'Hitech City Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-2',
    fromNodeId: 'node-hyd-1-2',
    toNodeId: 'node-hyd-1-3',
    roadName: 'Hitech City Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-3',
    fromNodeId: 'node-hyd-2-1',
    toNodeId: 'node-hyd-2-2',
    roadName: 'Gachibowli Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-4',
    fromNodeId: 'node-hyd-2-2',
    toNodeId: 'node-hyd-2-3',
    roadName: 'Gachibowli Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-5',
    fromNodeId: 'node-hyd-3-1',
    toNodeId: 'node-hyd-3-2',
    roadName: 'Jubilee Hills Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-6',
    fromNodeId: 'node-hyd-3-2',
    toNodeId: 'node-hyd-3-3',
    roadName: 'Jubilee Hills Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-7',
    fromNodeId: 'node-hyd-4-1',
    toNodeId: 'node-hyd-4-2',
    roadName: 'Banjara Hills Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-8',
    fromNodeId: 'node-hyd-4-2',
    toNodeId: 'node-hyd-4-3',
    roadName: 'Banjara Hills Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-9',
    fromNodeId: 'node-hyd-5-1',
    toNodeId: 'node-hyd-5-2',
    roadName: 'Madhapur Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-10',
    fromNodeId: 'node-hyd-5-2',
    toNodeId: 'node-hyd-5-3',
    roadName: 'Madhapur Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-11',
    fromNodeId: 'node-hyd-6-1',
    toNodeId: 'node-hyd-6-2',
    roadName: 'Kondapur Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-12',
    fromNodeId: 'node-hyd-6-2',
    toNodeId: 'node-hyd-6-3',
    roadName: 'Kondapur Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-13',
    fromNodeId: 'node-hyd-7-1',
    toNodeId: 'node-hyd-7-2',
    roadName: 'Kukatpally Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-14',
    fromNodeId: 'node-hyd-7-2',
    toNodeId: 'node-hyd-7-3',
    roadName: 'Kukatpally Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-15',
    fromNodeId: 'node-hyd-8-1',
    toNodeId: 'node-hyd-8-2',
    roadName: 'Begumpet Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-16',
    fromNodeId: 'node-hyd-8-2',
    toNodeId: 'node-hyd-8-3',
    roadName: 'Begumpet Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-17',
    fromNodeId: 'node-hyd-9-1',
    toNodeId: 'node-hyd-9-2',
    roadName: 'Secunderabad Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-18',
    fromNodeId: 'node-hyd-9-2',
    toNodeId: 'node-hyd-9-3',
    roadName: 'Secunderabad Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-19',
    fromNodeId: 'node-hyd-10-1',
    toNodeId: 'node-hyd-10-2',
    roadName: 'Manikonda Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-hyd-20',
    fromNodeId: 'node-hyd-10-2',
    toNodeId: 'node-hyd-10-3',
    roadName: 'Manikonda Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
