/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Incheon International Gateway
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const INCHEON_BASE_COORDINATE: GeoCoordinate = {
  latitude: 37.4563,
  longitude: 126.7052,
};

export const INCHEON_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-inc-1-1',
    name: 'Songdo International Sector 1 High Street',
    zone: 'Songdo International',
    location: { latitude: 37.394300, longitude: 126.653200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Songdo International.',
  },
  {
    id: 'node-inc-1-2',
    name: 'Songdo International Sector 2 High Street',
    zone: 'Songdo International',
    location: { latitude: 37.397300, longitude: 126.656200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Songdo International.',
  },
  {
    id: 'node-inc-1-3',
    name: 'Songdo International Sector 3 High Street',
    zone: 'Songdo International',
    location: { latitude: 37.400300, longitude: 126.659200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Songdo International.',
  },
  {
    id: 'node-inc-2-1',
    name: 'Bupyeong Sector 1 High Street',
    zone: 'Bupyeong',
    location: { latitude: 37.406300, longitude: 126.663200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bupyeong.',
  },
  {
    id: 'node-inc-2-2',
    name: 'Bupyeong Sector 2 High Street',
    zone: 'Bupyeong',
    location: { latitude: 37.409300, longitude: 126.666200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bupyeong.',
  },
  {
    id: 'node-inc-2-3',
    name: 'Bupyeong Sector 3 High Street',
    zone: 'Bupyeong',
    location: { latitude: 37.412300, longitude: 126.669200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bupyeong.',
  },
  {
    id: 'node-inc-3-1',
    name: 'Guwol-dong Sector 1 High Street',
    zone: 'Guwol-dong',
    location: { latitude: 37.418300, longitude: 126.673200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Guwol-dong.',
  },
  {
    id: 'node-inc-3-2',
    name: 'Guwol-dong Sector 2 High Street',
    zone: 'Guwol-dong',
    location: { latitude: 37.421300, longitude: 126.676200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Guwol-dong.',
  },
  {
    id: 'node-inc-3-3',
    name: 'Guwol-dong Sector 3 High Street',
    zone: 'Guwol-dong',
    location: { latitude: 37.424300, longitude: 126.679200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Guwol-dong.',
  },
  {
    id: 'node-inc-4-1',
    name: 'Chinatown Incheon Sector 1 High Street',
    zone: 'Chinatown Incheon',
    location: { latitude: 37.430300, longitude: 126.683200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chinatown Incheon.',
  },
  {
    id: 'node-inc-4-2',
    name: 'Chinatown Incheon Sector 2 High Street',
    zone: 'Chinatown Incheon',
    location: { latitude: 37.433300, longitude: 126.686200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chinatown Incheon.',
  },
  {
    id: 'node-inc-4-3',
    name: 'Chinatown Incheon Sector 3 High Street',
    zone: 'Chinatown Incheon',
    location: { latitude: 37.436300, longitude: 126.689200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chinatown Incheon.',
  },
  {
    id: 'node-inc-5-1',
    name: 'Cheongna Sector 1 High Street',
    zone: 'Cheongna',
    location: { latitude: 37.442300, longitude: 126.693200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cheongna.',
  },
  {
    id: 'node-inc-5-2',
    name: 'Cheongna Sector 2 High Street',
    zone: 'Cheongna',
    location: { latitude: 37.445300, longitude: 126.696200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cheongna.',
  },
  {
    id: 'node-inc-5-3',
    name: 'Cheongna Sector 3 High Street',
    zone: 'Cheongna',
    location: { latitude: 37.448300, longitude: 126.699200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cheongna.',
  },
  {
    id: 'node-inc-6-1',
    name: 'Yeonsu Sector 1 High Street',
    zone: 'Yeonsu',
    location: { latitude: 37.454300, longitude: 126.703200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Yeonsu.',
  },
  {
    id: 'node-inc-6-2',
    name: 'Yeonsu Sector 2 High Street',
    zone: 'Yeonsu',
    location: { latitude: 37.457300, longitude: 126.706200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Yeonsu.',
  },
  {
    id: 'node-inc-6-3',
    name: 'Yeonsu Sector 3 High Street',
    zone: 'Yeonsu',
    location: { latitude: 37.460300, longitude: 126.709200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Yeonsu.',
  },
  {
    id: 'node-inc-7-1',
    name: 'Incheon Free Zone Sector 1 High Street',
    zone: 'Incheon Free Zone',
    location: { latitude: 37.466300, longitude: 126.713200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Incheon Free Zone.',
  },
  {
    id: 'node-inc-7-2',
    name: 'Incheon Free Zone Sector 2 High Street',
    zone: 'Incheon Free Zone',
    location: { latitude: 37.469300, longitude: 126.716200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Incheon Free Zone.',
  },
  {
    id: 'node-inc-7-3',
    name: 'Incheon Free Zone Sector 3 High Street',
    zone: 'Incheon Free Zone',
    location: { latitude: 37.472300, longitude: 126.719200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Incheon Free Zone.',
  },
  {
    id: 'node-inc-8-1',
    name: 'Galsan Sector 1 High Street',
    zone: 'Galsan',
    location: { latitude: 37.478300, longitude: 126.723200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Galsan.',
  },
  {
    id: 'node-inc-8-2',
    name: 'Galsan Sector 2 High Street',
    zone: 'Galsan',
    location: { latitude: 37.481300, longitude: 126.726200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Galsan.',
  },
  {
    id: 'node-inc-8-3',
    name: 'Galsan Sector 3 High Street',
    zone: 'Galsan',
    location: { latitude: 37.484300, longitude: 126.729200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Galsan.',
  },
  {
    id: 'node-inc-9-1',
    name: 'Juan Sector 1 High Street',
    zone: 'Juan',
    location: { latitude: 37.490300, longitude: 126.733200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Juan.',
  },
  {
    id: 'node-inc-9-2',
    name: 'Juan Sector 2 High Street',
    zone: 'Juan',
    location: { latitude: 37.493300, longitude: 126.736200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Juan.',
  },
  {
    id: 'node-inc-9-3',
    name: 'Juan Sector 3 High Street',
    zone: 'Juan',
    location: { latitude: 37.496300, longitude: 126.739200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Juan.',
  },
  {
    id: 'node-inc-10-1',
    name: 'Dongincheon Sector 1 High Street',
    zone: 'Dongincheon',
    location: { latitude: 37.502300, longitude: 126.743200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dongincheon.',
  },
  {
    id: 'node-inc-10-2',
    name: 'Dongincheon Sector 2 High Street',
    zone: 'Dongincheon',
    location: { latitude: 37.505300, longitude: 126.746200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dongincheon.',
  },
  {
    id: 'node-inc-10-3',
    name: 'Dongincheon Sector 3 High Street',
    zone: 'Dongincheon',
    location: { latitude: 37.508300, longitude: 126.749200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dongincheon.',
  },
];

export const INCHEON_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-inc-1',
    fromNodeId: 'node-inc-1-1',
    toNodeId: 'node-inc-1-2',
    roadName: 'Songdo International Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-2',
    fromNodeId: 'node-inc-1-2',
    toNodeId: 'node-inc-1-3',
    roadName: 'Songdo International Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-3',
    fromNodeId: 'node-inc-2-1',
    toNodeId: 'node-inc-2-2',
    roadName: 'Bupyeong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-4',
    fromNodeId: 'node-inc-2-2',
    toNodeId: 'node-inc-2-3',
    roadName: 'Bupyeong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-5',
    fromNodeId: 'node-inc-3-1',
    toNodeId: 'node-inc-3-2',
    roadName: 'Guwol-dong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-6',
    fromNodeId: 'node-inc-3-2',
    toNodeId: 'node-inc-3-3',
    roadName: 'Guwol-dong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-7',
    fromNodeId: 'node-inc-4-1',
    toNodeId: 'node-inc-4-2',
    roadName: 'Chinatown Incheon Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-8',
    fromNodeId: 'node-inc-4-2',
    toNodeId: 'node-inc-4-3',
    roadName: 'Chinatown Incheon Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-9',
    fromNodeId: 'node-inc-5-1',
    toNodeId: 'node-inc-5-2',
    roadName: 'Cheongna Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-10',
    fromNodeId: 'node-inc-5-2',
    toNodeId: 'node-inc-5-3',
    roadName: 'Cheongna Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-11',
    fromNodeId: 'node-inc-6-1',
    toNodeId: 'node-inc-6-2',
    roadName: 'Yeonsu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-12',
    fromNodeId: 'node-inc-6-2',
    toNodeId: 'node-inc-6-3',
    roadName: 'Yeonsu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-13',
    fromNodeId: 'node-inc-7-1',
    toNodeId: 'node-inc-7-2',
    roadName: 'Incheon Free Zone Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-14',
    fromNodeId: 'node-inc-7-2',
    toNodeId: 'node-inc-7-3',
    roadName: 'Incheon Free Zone Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-15',
    fromNodeId: 'node-inc-8-1',
    toNodeId: 'node-inc-8-2',
    roadName: 'Galsan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-16',
    fromNodeId: 'node-inc-8-2',
    toNodeId: 'node-inc-8-3',
    roadName: 'Galsan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-17',
    fromNodeId: 'node-inc-9-1',
    toNodeId: 'node-inc-9-2',
    roadName: 'Juan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-18',
    fromNodeId: 'node-inc-9-2',
    toNodeId: 'node-inc-9-3',
    roadName: 'Juan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-19',
    fromNodeId: 'node-inc-10-1',
    toNodeId: 'node-inc-10-2',
    roadName: 'Dongincheon Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-inc-20',
    fromNodeId: 'node-inc-10-2',
    toNodeId: 'node-inc-10-3',
    roadName: 'Dongincheon Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
