/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Indore Malwa Food Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const INDORE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 22.7196,
  longitude: 75.8577,
};

export const INDORE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ind-1-1',
    name: 'Vijay Nagar Sector 1 High Street',
    zone: 'Vijay Nagar',
    location: { latitude: 22.657600, longitude: 75.805700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vijay Nagar.',
  },
  {
    id: 'node-ind-1-2',
    name: 'Vijay Nagar Sector 2 High Street',
    zone: 'Vijay Nagar',
    location: { latitude: 22.660600, longitude: 75.808700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vijay Nagar.',
  },
  {
    id: 'node-ind-1-3',
    name: 'Vijay Nagar Sector 3 High Street',
    zone: 'Vijay Nagar',
    location: { latitude: 22.663600, longitude: 75.811700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vijay Nagar.',
  },
  {
    id: 'node-ind-2-1',
    name: 'Palasia Sector 1 High Street',
    zone: 'Palasia',
    location: { latitude: 22.669600, longitude: 75.815700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Palasia.',
  },
  {
    id: 'node-ind-2-2',
    name: 'Palasia Sector 2 High Street',
    zone: 'Palasia',
    location: { latitude: 22.672600, longitude: 75.818700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Palasia.',
  },
  {
    id: 'node-ind-2-3',
    name: 'Palasia Sector 3 High Street',
    zone: 'Palasia',
    location: { latitude: 22.675600, longitude: 75.821700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Palasia.',
  },
  {
    id: 'node-ind-3-1',
    name: 'Chappan Dukan Area Sector 1 High Street',
    zone: 'Chappan Dukan Area',
    location: { latitude: 22.681600, longitude: 75.825700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chappan Dukan Area.',
  },
  {
    id: 'node-ind-3-2',
    name: 'Chappan Dukan Area Sector 2 High Street',
    zone: 'Chappan Dukan Area',
    location: { latitude: 22.684600, longitude: 75.828700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chappan Dukan Area.',
  },
  {
    id: 'node-ind-3-3',
    name: 'Chappan Dukan Area Sector 3 High Street',
    zone: 'Chappan Dukan Area',
    location: { latitude: 22.687600, longitude: 75.831700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chappan Dukan Area.',
  },
  {
    id: 'node-ind-4-1',
    name: 'Sarafa Bazaar Sector 1 High Street',
    zone: 'Sarafa Bazaar',
    location: { latitude: 22.693600, longitude: 75.835700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sarafa Bazaar.',
  },
  {
    id: 'node-ind-4-2',
    name: 'Sarafa Bazaar Sector 2 High Street',
    zone: 'Sarafa Bazaar',
    location: { latitude: 22.696600, longitude: 75.838700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sarafa Bazaar.',
  },
  {
    id: 'node-ind-4-3',
    name: 'Sarafa Bazaar Sector 3 High Street',
    zone: 'Sarafa Bazaar',
    location: { latitude: 22.699600, longitude: 75.841700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sarafa Bazaar.',
  },
  {
    id: 'node-ind-5-1',
    name: 'Bhawarkua Sector 1 High Street',
    zone: 'Bhawarkua',
    location: { latitude: 22.705600, longitude: 75.845700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bhawarkua.',
  },
  {
    id: 'node-ind-5-2',
    name: 'Bhawarkua Sector 2 High Street',
    zone: 'Bhawarkua',
    location: { latitude: 22.708600, longitude: 75.848700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bhawarkua.',
  },
  {
    id: 'node-ind-5-3',
    name: 'Bhawarkua Sector 3 High Street',
    zone: 'Bhawarkua',
    location: { latitude: 22.711600, longitude: 75.851700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bhawarkua.',
  },
  {
    id: 'node-ind-6-1',
    name: 'Rau Sector 1 High Street',
    zone: 'Rau',
    location: { latitude: 22.717600, longitude: 75.855700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rau.',
  },
  {
    id: 'node-ind-6-2',
    name: 'Rau Sector 2 High Street',
    zone: 'Rau',
    location: { latitude: 22.720600, longitude: 75.858700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rau.',
  },
  {
    id: 'node-ind-6-3',
    name: 'Rau Sector 3 High Street',
    zone: 'Rau',
    location: { latitude: 22.723600, longitude: 75.861700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rau.',
  },
  {
    id: 'node-ind-7-1',
    name: 'LIG Colony Sector 1 High Street',
    zone: 'LIG Colony',
    location: { latitude: 22.729600, longitude: 75.865700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in LIG Colony.',
  },
  {
    id: 'node-ind-7-2',
    name: 'LIG Colony Sector 2 High Street',
    zone: 'LIG Colony',
    location: { latitude: 22.732600, longitude: 75.868700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in LIG Colony.',
  },
  {
    id: 'node-ind-7-3',
    name: 'LIG Colony Sector 3 High Street',
    zone: 'LIG Colony',
    location: { latitude: 22.735600, longitude: 75.871700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in LIG Colony.',
  },
  {
    id: 'node-ind-8-1',
    name: 'Sapna Sangeeta Sector 1 High Street',
    zone: 'Sapna Sangeeta',
    location: { latitude: 22.741600, longitude: 75.875700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sapna Sangeeta.',
  },
  {
    id: 'node-ind-8-2',
    name: 'Sapna Sangeeta Sector 2 High Street',
    zone: 'Sapna Sangeeta',
    location: { latitude: 22.744600, longitude: 75.878700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sapna Sangeeta.',
  },
  {
    id: 'node-ind-8-3',
    name: 'Sapna Sangeeta Sector 3 High Street',
    zone: 'Sapna Sangeeta',
    location: { latitude: 22.747600, longitude: 75.881700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sapna Sangeeta.',
  },
  {
    id: 'node-ind-9-1',
    name: 'Annapurna Road Sector 1 High Street',
    zone: 'Annapurna Road',
    location: { latitude: 22.753600, longitude: 75.885700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Annapurna Road.',
  },
  {
    id: 'node-ind-9-2',
    name: 'Annapurna Road Sector 2 High Street',
    zone: 'Annapurna Road',
    location: { latitude: 22.756600, longitude: 75.888700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Annapurna Road.',
  },
  {
    id: 'node-ind-9-3',
    name: 'Annapurna Road Sector 3 High Street',
    zone: 'Annapurna Road',
    location: { latitude: 22.759600, longitude: 75.891700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Annapurna Road.',
  },
  {
    id: 'node-ind-10-1',
    name: 'AB Road Sector 1 High Street',
    zone: 'AB Road',
    location: { latitude: 22.765600, longitude: 75.895700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in AB Road.',
  },
  {
    id: 'node-ind-10-2',
    name: 'AB Road Sector 2 High Street',
    zone: 'AB Road',
    location: { latitude: 22.768600, longitude: 75.898700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in AB Road.',
  },
  {
    id: 'node-ind-10-3',
    name: 'AB Road Sector 3 High Street',
    zone: 'AB Road',
    location: { latitude: 22.771600, longitude: 75.901700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in AB Road.',
  },
];

export const INDORE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ind-1',
    fromNodeId: 'node-ind-1-1',
    toNodeId: 'node-ind-1-2',
    roadName: 'Vijay Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-2',
    fromNodeId: 'node-ind-1-2',
    toNodeId: 'node-ind-1-3',
    roadName: 'Vijay Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-3',
    fromNodeId: 'node-ind-2-1',
    toNodeId: 'node-ind-2-2',
    roadName: 'Palasia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-4',
    fromNodeId: 'node-ind-2-2',
    toNodeId: 'node-ind-2-3',
    roadName: 'Palasia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-5',
    fromNodeId: 'node-ind-3-1',
    toNodeId: 'node-ind-3-2',
    roadName: 'Chappan Dukan Area Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-6',
    fromNodeId: 'node-ind-3-2',
    toNodeId: 'node-ind-3-3',
    roadName: 'Chappan Dukan Area Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-7',
    fromNodeId: 'node-ind-4-1',
    toNodeId: 'node-ind-4-2',
    roadName: 'Sarafa Bazaar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-8',
    fromNodeId: 'node-ind-4-2',
    toNodeId: 'node-ind-4-3',
    roadName: 'Sarafa Bazaar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-9',
    fromNodeId: 'node-ind-5-1',
    toNodeId: 'node-ind-5-2',
    roadName: 'Bhawarkua Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-10',
    fromNodeId: 'node-ind-5-2',
    toNodeId: 'node-ind-5-3',
    roadName: 'Bhawarkua Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-11',
    fromNodeId: 'node-ind-6-1',
    toNodeId: 'node-ind-6-2',
    roadName: 'Rau Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-12',
    fromNodeId: 'node-ind-6-2',
    toNodeId: 'node-ind-6-3',
    roadName: 'Rau Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-13',
    fromNodeId: 'node-ind-7-1',
    toNodeId: 'node-ind-7-2',
    roadName: 'LIG Colony Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-14',
    fromNodeId: 'node-ind-7-2',
    toNodeId: 'node-ind-7-3',
    roadName: 'LIG Colony Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-15',
    fromNodeId: 'node-ind-8-1',
    toNodeId: 'node-ind-8-2',
    roadName: 'Sapna Sangeeta Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-16',
    fromNodeId: 'node-ind-8-2',
    toNodeId: 'node-ind-8-3',
    roadName: 'Sapna Sangeeta Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-17',
    fromNodeId: 'node-ind-9-1',
    toNodeId: 'node-ind-9-2',
    roadName: 'Annapurna Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-18',
    fromNodeId: 'node-ind-9-2',
    toNodeId: 'node-ind-9-3',
    roadName: 'Annapurna Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-19',
    fromNodeId: 'node-ind-10-1',
    toNodeId: 'node-ind-10-2',
    roadName: 'AB Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ind-20',
    fromNodeId: 'node-ind-10-2',
    toNodeId: 'node-ind-10-3',
    roadName: 'AB Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
