/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Istanbul Anatolian Kadikoy Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const ISTANBULASIA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 40.9927,
  longitude: 29.0277,
};

export const ISTANBULASIA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ist-1-1',
    name: 'Kadikoy Central Sector 1 High Street',
    zone: 'Kadikoy Central',
    location: { latitude: 40.930700, longitude: 28.975700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kadikoy Central.',
  },
  {
    id: 'node-ist-1-2',
    name: 'Kadikoy Central Sector 2 High Street',
    zone: 'Kadikoy Central',
    location: { latitude: 40.933700, longitude: 28.978700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kadikoy Central.',
  },
  {
    id: 'node-ist-1-3',
    name: 'Kadikoy Central Sector 3 High Street',
    zone: 'Kadikoy Central',
    location: { latitude: 40.936700, longitude: 28.981700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kadikoy Central.',
  },
  {
    id: 'node-ist-2-1',
    name: 'Moda Sector 1 High Street',
    zone: 'Moda',
    location: { latitude: 40.942700, longitude: 28.985700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Moda.',
  },
  {
    id: 'node-ist-2-2',
    name: 'Moda Sector 2 High Street',
    zone: 'Moda',
    location: { latitude: 40.945700, longitude: 28.988700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Moda.',
  },
  {
    id: 'node-ist-2-3',
    name: 'Moda Sector 3 High Street',
    zone: 'Moda',
    location: { latitude: 40.948700, longitude: 28.991700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Moda.',
  },
  {
    id: 'node-ist-3-1',
    name: 'Bagdat Avenue Sector 1 High Street',
    zone: 'Bagdat Avenue',
    location: { latitude: 40.954700, longitude: 28.995700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bagdat Avenue.',
  },
  {
    id: 'node-ist-3-2',
    name: 'Bagdat Avenue Sector 2 High Street',
    zone: 'Bagdat Avenue',
    location: { latitude: 40.957700, longitude: 28.998700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bagdat Avenue.',
  },
  {
    id: 'node-ist-3-3',
    name: 'Bagdat Avenue Sector 3 High Street',
    zone: 'Bagdat Avenue',
    location: { latitude: 40.960700, longitude: 29.001700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bagdat Avenue.',
  },
  {
    id: 'node-ist-4-1',
    name: 'Uskudar Sector 1 High Street',
    zone: 'Uskudar',
    location: { latitude: 40.966700, longitude: 29.005700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Uskudar.',
  },
  {
    id: 'node-ist-4-2',
    name: 'Uskudar Sector 2 High Street',
    zone: 'Uskudar',
    location: { latitude: 40.969700, longitude: 29.008700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Uskudar.',
  },
  {
    id: 'node-ist-4-3',
    name: 'Uskudar Sector 3 High Street',
    zone: 'Uskudar',
    location: { latitude: 40.972700, longitude: 29.011700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Uskudar.',
  },
  {
    id: 'node-ist-5-1',
    name: 'Atasehir Sector 1 High Street',
    zone: 'Atasehir',
    location: { latitude: 40.978700, longitude: 29.015700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Atasehir.',
  },
  {
    id: 'node-ist-5-2',
    name: 'Atasehir Sector 2 High Street',
    zone: 'Atasehir',
    location: { latitude: 40.981700, longitude: 29.018700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Atasehir.',
  },
  {
    id: 'node-ist-5-3',
    name: 'Atasehir Sector 3 High Street',
    zone: 'Atasehir',
    location: { latitude: 40.984700, longitude: 29.021700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Atasehir.',
  },
  {
    id: 'node-ist-6-1',
    name: 'Caddebostan Sector 1 High Street',
    zone: 'Caddebostan',
    location: { latitude: 40.990700, longitude: 29.025700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Caddebostan.',
  },
  {
    id: 'node-ist-6-2',
    name: 'Caddebostan Sector 2 High Street',
    zone: 'Caddebostan',
    location: { latitude: 40.993700, longitude: 29.028700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Caddebostan.',
  },
  {
    id: 'node-ist-6-3',
    name: 'Caddebostan Sector 3 High Street',
    zone: 'Caddebostan',
    location: { latitude: 40.996700, longitude: 29.031700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Caddebostan.',
  },
  {
    id: 'node-ist-7-1',
    name: 'Suadiye Sector 1 High Street',
    zone: 'Suadiye',
    location: { latitude: 41.002700, longitude: 29.035700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Suadiye.',
  },
  {
    id: 'node-ist-7-2',
    name: 'Suadiye Sector 2 High Street',
    zone: 'Suadiye',
    location: { latitude: 41.005700, longitude: 29.038700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Suadiye.',
  },
  {
    id: 'node-ist-7-3',
    name: 'Suadiye Sector 3 High Street',
    zone: 'Suadiye',
    location: { latitude: 41.008700, longitude: 29.041700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Suadiye.',
  },
  {
    id: 'node-ist-8-1',
    name: 'Fenerbahce Sector 1 High Street',
    zone: 'Fenerbahce',
    location: { latitude: 41.014700, longitude: 29.045700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fenerbahce.',
  },
  {
    id: 'node-ist-8-2',
    name: 'Fenerbahce Sector 2 High Street',
    zone: 'Fenerbahce',
    location: { latitude: 41.017700, longitude: 29.048700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fenerbahce.',
  },
  {
    id: 'node-ist-8-3',
    name: 'Fenerbahce Sector 3 High Street',
    zone: 'Fenerbahce',
    location: { latitude: 41.020700, longitude: 29.051700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fenerbahce.',
  },
  {
    id: 'node-ist-9-1',
    name: 'Kalamis Sector 1 High Street',
    zone: 'Kalamis',
    location: { latitude: 41.026700, longitude: 29.055700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kalamis.',
  },
  {
    id: 'node-ist-9-2',
    name: 'Kalamis Sector 2 High Street',
    zone: 'Kalamis',
    location: { latitude: 41.029700, longitude: 29.058700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kalamis.',
  },
  {
    id: 'node-ist-9-3',
    name: 'Kalamis Sector 3 High Street',
    zone: 'Kalamis',
    location: { latitude: 41.032700, longitude: 29.061700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kalamis.',
  },
  {
    id: 'node-ist-10-1',
    name: 'Bostanci Sector 1 High Street',
    zone: 'Bostanci',
    location: { latitude: 41.038700, longitude: 29.065700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bostanci.',
  },
  {
    id: 'node-ist-10-2',
    name: 'Bostanci Sector 2 High Street',
    zone: 'Bostanci',
    location: { latitude: 41.041700, longitude: 29.068700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bostanci.',
  },
  {
    id: 'node-ist-10-3',
    name: 'Bostanci Sector 3 High Street',
    zone: 'Bostanci',
    location: { latitude: 41.044700, longitude: 29.071700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bostanci.',
  },
];

export const ISTANBULASIA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ist-1',
    fromNodeId: 'node-ist-1-1',
    toNodeId: 'node-ist-1-2',
    roadName: 'Kadikoy Central Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-2',
    fromNodeId: 'node-ist-1-2',
    toNodeId: 'node-ist-1-3',
    roadName: 'Kadikoy Central Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-3',
    fromNodeId: 'node-ist-2-1',
    toNodeId: 'node-ist-2-2',
    roadName: 'Moda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-4',
    fromNodeId: 'node-ist-2-2',
    toNodeId: 'node-ist-2-3',
    roadName: 'Moda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-5',
    fromNodeId: 'node-ist-3-1',
    toNodeId: 'node-ist-3-2',
    roadName: 'Bagdat Avenue Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-6',
    fromNodeId: 'node-ist-3-2',
    toNodeId: 'node-ist-3-3',
    roadName: 'Bagdat Avenue Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-7',
    fromNodeId: 'node-ist-4-1',
    toNodeId: 'node-ist-4-2',
    roadName: 'Uskudar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-8',
    fromNodeId: 'node-ist-4-2',
    toNodeId: 'node-ist-4-3',
    roadName: 'Uskudar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-9',
    fromNodeId: 'node-ist-5-1',
    toNodeId: 'node-ist-5-2',
    roadName: 'Atasehir Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-10',
    fromNodeId: 'node-ist-5-2',
    toNodeId: 'node-ist-5-3',
    roadName: 'Atasehir Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-11',
    fromNodeId: 'node-ist-6-1',
    toNodeId: 'node-ist-6-2',
    roadName: 'Caddebostan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-12',
    fromNodeId: 'node-ist-6-2',
    toNodeId: 'node-ist-6-3',
    roadName: 'Caddebostan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-13',
    fromNodeId: 'node-ist-7-1',
    toNodeId: 'node-ist-7-2',
    roadName: 'Suadiye Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-14',
    fromNodeId: 'node-ist-7-2',
    toNodeId: 'node-ist-7-3',
    roadName: 'Suadiye Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-15',
    fromNodeId: 'node-ist-8-1',
    toNodeId: 'node-ist-8-2',
    roadName: 'Fenerbahce Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-16',
    fromNodeId: 'node-ist-8-2',
    toNodeId: 'node-ist-8-3',
    roadName: 'Fenerbahce Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-17',
    fromNodeId: 'node-ist-9-1',
    toNodeId: 'node-ist-9-2',
    roadName: 'Kalamis Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-18',
    fromNodeId: 'node-ist-9-2',
    toNodeId: 'node-ist-9-3',
    roadName: 'Kalamis Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-19',
    fromNodeId: 'node-ist-10-1',
    toNodeId: 'node-ist-10-2',
    roadName: 'Bostanci Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ist-20',
    fromNodeId: 'node-ist-10-2',
    toNodeId: 'node-ist-10-3',
    roadName: 'Bostanci Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
