/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Izmir Aegean Pearl
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const IZMIR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 38.4237,
  longitude: 27.1428,
};

export const IZMIR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-izm-1-1',
    name: 'Alsancak Sector 1 High Street',
    zone: 'Alsancak',
    location: { latitude: 38.361700, longitude: 27.090800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Alsancak.',
  },
  {
    id: 'node-izm-1-2',
    name: 'Alsancak Sector 2 High Street',
    zone: 'Alsancak',
    location: { latitude: 38.364700, longitude: 27.093800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Alsancak.',
  },
  {
    id: 'node-izm-1-3',
    name: 'Alsancak Sector 3 High Street',
    zone: 'Alsancak',
    location: { latitude: 38.367700, longitude: 27.096800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Alsancak.',
  },
  {
    id: 'node-izm-2-1',
    name: 'Kordon Sector 1 High Street',
    zone: 'Kordon',
    location: { latitude: 38.373700, longitude: 27.100800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kordon.',
  },
  {
    id: 'node-izm-2-2',
    name: 'Kordon Sector 2 High Street',
    zone: 'Kordon',
    location: { latitude: 38.376700, longitude: 27.103800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kordon.',
  },
  {
    id: 'node-izm-2-3',
    name: 'Kordon Sector 3 High Street',
    zone: 'Kordon',
    location: { latitude: 38.379700, longitude: 27.106800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kordon.',
  },
  {
    id: 'node-izm-3-1',
    name: 'Karşıyaka Sector 1 High Street',
    zone: 'Karşıyaka',
    location: { latitude: 38.385700, longitude: 27.110800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Karşıyaka.',
  },
  {
    id: 'node-izm-3-2',
    name: 'Karşıyaka Sector 2 High Street',
    zone: 'Karşıyaka',
    location: { latitude: 38.388700, longitude: 27.113800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Karşıyaka.',
  },
  {
    id: 'node-izm-3-3',
    name: 'Karşıyaka Sector 3 High Street',
    zone: 'Karşıyaka',
    location: { latitude: 38.391700, longitude: 27.116800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Karşıyaka.',
  },
  {
    id: 'node-izm-4-1',
    name: 'Konak Izmir Sector 1 High Street',
    zone: 'Konak Izmir',
    location: { latitude: 38.397700, longitude: 27.120800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Konak Izmir.',
  },
  {
    id: 'node-izm-4-2',
    name: 'Konak Izmir Sector 2 High Street',
    zone: 'Konak Izmir',
    location: { latitude: 38.400700, longitude: 27.123800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Konak Izmir.',
  },
  {
    id: 'node-izm-4-3',
    name: 'Konak Izmir Sector 3 High Street',
    zone: 'Konak Izmir',
    location: { latitude: 38.403700, longitude: 27.126800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Konak Izmir.',
  },
  {
    id: 'node-izm-5-1',
    name: 'Bornova Sector 1 High Street',
    zone: 'Bornova',
    location: { latitude: 38.409700, longitude: 27.130800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bornova.',
  },
  {
    id: 'node-izm-5-2',
    name: 'Bornova Sector 2 High Street',
    zone: 'Bornova',
    location: { latitude: 38.412700, longitude: 27.133800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bornova.',
  },
  {
    id: 'node-izm-5-3',
    name: 'Bornova Sector 3 High Street',
    zone: 'Bornova',
    location: { latitude: 38.415700, longitude: 27.136800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bornova.',
  },
  {
    id: 'node-izm-6-1',
    name: 'Bostanlı Sector 1 High Street',
    zone: 'Bostanlı',
    location: { latitude: 38.421700, longitude: 27.140800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bostanlı.',
  },
  {
    id: 'node-izm-6-2',
    name: 'Bostanlı Sector 2 High Street',
    zone: 'Bostanlı',
    location: { latitude: 38.424700, longitude: 27.143800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bostanlı.',
  },
  {
    id: 'node-izm-6-3',
    name: 'Bostanlı Sector 3 High Street',
    zone: 'Bostanlı',
    location: { latitude: 38.427700, longitude: 27.146800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bostanlı.',
  },
  {
    id: 'node-izm-7-1',
    name: 'Göztepe Sector 1 High Street',
    zone: 'Göztepe',
    location: { latitude: 38.433700, longitude: 27.150800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Göztepe.',
  },
  {
    id: 'node-izm-7-2',
    name: 'Göztepe Sector 2 High Street',
    zone: 'Göztepe',
    location: { latitude: 38.436700, longitude: 27.153800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Göztepe.',
  },
  {
    id: 'node-izm-7-3',
    name: 'Göztepe Sector 3 High Street',
    zone: 'Göztepe',
    location: { latitude: 38.439700, longitude: 27.156800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Göztepe.',
  },
  {
    id: 'node-izm-8-1',
    name: 'Bayraklı Sector 1 High Street',
    zone: 'Bayraklı',
    location: { latitude: 38.445700, longitude: 27.160800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bayraklı.',
  },
  {
    id: 'node-izm-8-2',
    name: 'Bayraklı Sector 2 High Street',
    zone: 'Bayraklı',
    location: { latitude: 38.448700, longitude: 27.163800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bayraklı.',
  },
  {
    id: 'node-izm-8-3',
    name: 'Bayraklı Sector 3 High Street',
    zone: 'Bayraklı',
    location: { latitude: 38.451700, longitude: 27.166800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bayraklı.',
  },
  {
    id: 'node-izm-9-1',
    name: 'Balçova Sector 1 High Street',
    zone: 'Balçova',
    location: { latitude: 38.457700, longitude: 27.170800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Balçova.',
  },
  {
    id: 'node-izm-9-2',
    name: 'Balçova Sector 2 High Street',
    zone: 'Balçova',
    location: { latitude: 38.460700, longitude: 27.173800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Balçova.',
  },
  {
    id: 'node-izm-9-3',
    name: 'Balçova Sector 3 High Street',
    zone: 'Balçova',
    location: { latitude: 38.463700, longitude: 27.176800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Balçova.',
  },
  {
    id: 'node-izm-10-1',
    name: 'Urla Coastal Sector 1 High Street',
    zone: 'Urla Coastal',
    location: { latitude: 38.469700, longitude: 27.180800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Urla Coastal.',
  },
  {
    id: 'node-izm-10-2',
    name: 'Urla Coastal Sector 2 High Street',
    zone: 'Urla Coastal',
    location: { latitude: 38.472700, longitude: 27.183800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Urla Coastal.',
  },
  {
    id: 'node-izm-10-3',
    name: 'Urla Coastal Sector 3 High Street',
    zone: 'Urla Coastal',
    location: { latitude: 38.475700, longitude: 27.186800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Urla Coastal.',
  },
];

export const IZMIR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-izm-1',
    fromNodeId: 'node-izm-1-1',
    toNodeId: 'node-izm-1-2',
    roadName: 'Alsancak Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-2',
    fromNodeId: 'node-izm-1-2',
    toNodeId: 'node-izm-1-3',
    roadName: 'Alsancak Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-3',
    fromNodeId: 'node-izm-2-1',
    toNodeId: 'node-izm-2-2',
    roadName: 'Kordon Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-4',
    fromNodeId: 'node-izm-2-2',
    toNodeId: 'node-izm-2-3',
    roadName: 'Kordon Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-5',
    fromNodeId: 'node-izm-3-1',
    toNodeId: 'node-izm-3-2',
    roadName: 'Karşıyaka Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-6',
    fromNodeId: 'node-izm-3-2',
    toNodeId: 'node-izm-3-3',
    roadName: 'Karşıyaka Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-7',
    fromNodeId: 'node-izm-4-1',
    toNodeId: 'node-izm-4-2',
    roadName: 'Konak Izmir Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-8',
    fromNodeId: 'node-izm-4-2',
    toNodeId: 'node-izm-4-3',
    roadName: 'Konak Izmir Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-9',
    fromNodeId: 'node-izm-5-1',
    toNodeId: 'node-izm-5-2',
    roadName: 'Bornova Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-10',
    fromNodeId: 'node-izm-5-2',
    toNodeId: 'node-izm-5-3',
    roadName: 'Bornova Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-11',
    fromNodeId: 'node-izm-6-1',
    toNodeId: 'node-izm-6-2',
    roadName: 'Bostanlı Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-12',
    fromNodeId: 'node-izm-6-2',
    toNodeId: 'node-izm-6-3',
    roadName: 'Bostanlı Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-13',
    fromNodeId: 'node-izm-7-1',
    toNodeId: 'node-izm-7-2',
    roadName: 'Göztepe Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-14',
    fromNodeId: 'node-izm-7-2',
    toNodeId: 'node-izm-7-3',
    roadName: 'Göztepe Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-15',
    fromNodeId: 'node-izm-8-1',
    toNodeId: 'node-izm-8-2',
    roadName: 'Bayraklı Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-16',
    fromNodeId: 'node-izm-8-2',
    toNodeId: 'node-izm-8-3',
    roadName: 'Bayraklı Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-17',
    fromNodeId: 'node-izm-9-1',
    toNodeId: 'node-izm-9-2',
    roadName: 'Balçova Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-18',
    fromNodeId: 'node-izm-9-2',
    toNodeId: 'node-izm-9-3',
    roadName: 'Balçova Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-19',
    fromNodeId: 'node-izm-10-1',
    toNodeId: 'node-izm-10-2',
    roadName: 'Urla Coastal Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-izm-20',
    fromNodeId: 'node-izm-10-2',
    toNodeId: 'node-izm-10-3',
    roadName: 'Urla Coastal Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
