/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Jaipur Pink City Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const JAIPUR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 26.9124,
  longitude: 75.7873,
};

export const JAIPUR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-jai-1-1',
    name: 'C Scheme Sector 1 High Street',
    zone: 'C Scheme',
    location: { latitude: 26.850400, longitude: 75.735300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in C Scheme.',
  },
  {
    id: 'node-jai-1-2',
    name: 'C Scheme Sector 2 High Street',
    zone: 'C Scheme',
    location: { latitude: 26.853400, longitude: 75.738300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in C Scheme.',
  },
  {
    id: 'node-jai-1-3',
    name: 'C Scheme Sector 3 High Street',
    zone: 'C Scheme',
    location: { latitude: 26.856400, longitude: 75.741300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in C Scheme.',
  },
  {
    id: 'node-jai-2-1',
    name: 'Malviya Nagar Sector 1 High Street',
    zone: 'Malviya Nagar',
    location: { latitude: 26.862400, longitude: 75.745300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Malviya Nagar.',
  },
  {
    id: 'node-jai-2-2',
    name: 'Malviya Nagar Sector 2 High Street',
    zone: 'Malviya Nagar',
    location: { latitude: 26.865400, longitude: 75.748300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Malviya Nagar.',
  },
  {
    id: 'node-jai-2-3',
    name: 'Malviya Nagar Sector 3 High Street',
    zone: 'Malviya Nagar',
    location: { latitude: 26.868400, longitude: 75.751300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Malviya Nagar.',
  },
  {
    id: 'node-jai-3-1',
    name: 'Vaishali Nagar Sector 1 High Street',
    zone: 'Vaishali Nagar',
    location: { latitude: 26.874400, longitude: 75.755300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vaishali Nagar.',
  },
  {
    id: 'node-jai-3-2',
    name: 'Vaishali Nagar Sector 2 High Street',
    zone: 'Vaishali Nagar',
    location: { latitude: 26.877400, longitude: 75.758300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vaishali Nagar.',
  },
  {
    id: 'node-jai-3-3',
    name: 'Vaishali Nagar Sector 3 High Street',
    zone: 'Vaishali Nagar',
    location: { latitude: 26.880400, longitude: 75.761300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vaishali Nagar.',
  },
  {
    id: 'node-jai-4-1',
    name: 'Raja Park Sector 1 High Street',
    zone: 'Raja Park',
    location: { latitude: 26.886400, longitude: 75.765300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Raja Park.',
  },
  {
    id: 'node-jai-4-2',
    name: 'Raja Park Sector 2 High Street',
    zone: 'Raja Park',
    location: { latitude: 26.889400, longitude: 75.768300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Raja Park.',
  },
  {
    id: 'node-jai-4-3',
    name: 'Raja Park Sector 3 High Street',
    zone: 'Raja Park',
    location: { latitude: 26.892400, longitude: 75.771300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Raja Park.',
  },
  {
    id: 'node-jai-5-1',
    name: 'Mansarovar Sector 1 High Street',
    zone: 'Mansarovar',
    location: { latitude: 26.898400, longitude: 75.775300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mansarovar.',
  },
  {
    id: 'node-jai-5-2',
    name: 'Mansarovar Sector 2 High Street',
    zone: 'Mansarovar',
    location: { latitude: 26.901400, longitude: 75.778300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mansarovar.',
  },
  {
    id: 'node-jai-5-3',
    name: 'Mansarovar Sector 3 High Street',
    zone: 'Mansarovar',
    location: { latitude: 26.904400, longitude: 75.781300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mansarovar.',
  },
  {
    id: 'node-jai-6-1',
    name: 'Tonk Road Sector 1 High Street',
    zone: 'Tonk Road',
    location: { latitude: 26.910400, longitude: 75.785300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tonk Road.',
  },
  {
    id: 'node-jai-6-2',
    name: 'Tonk Road Sector 2 High Street',
    zone: 'Tonk Road',
    location: { latitude: 26.913400, longitude: 75.788300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tonk Road.',
  },
  {
    id: 'node-jai-6-3',
    name: 'Tonk Road Sector 3 High Street',
    zone: 'Tonk Road',
    location: { latitude: 26.916400, longitude: 75.791300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tonk Road.',
  },
  {
    id: 'node-jai-7-1',
    name: 'Bani Park Sector 1 High Street',
    zone: 'Bani Park',
    location: { latitude: 26.922400, longitude: 75.795300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bani Park.',
  },
  {
    id: 'node-jai-7-2',
    name: 'Bani Park Sector 2 High Street',
    zone: 'Bani Park',
    location: { latitude: 26.925400, longitude: 75.798300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bani Park.',
  },
  {
    id: 'node-jai-7-3',
    name: 'Bani Park Sector 3 High Street',
    zone: 'Bani Park',
    location: { latitude: 26.928400, longitude: 75.801300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bani Park.',
  },
  {
    id: 'node-jai-8-1',
    name: 'Jagatpura Sector 1 High Street',
    zone: 'Jagatpura',
    location: { latitude: 26.934400, longitude: 75.805300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jagatpura.',
  },
  {
    id: 'node-jai-8-2',
    name: 'Jagatpura Sector 2 High Street',
    zone: 'Jagatpura',
    location: { latitude: 26.937400, longitude: 75.808300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jagatpura.',
  },
  {
    id: 'node-jai-8-3',
    name: 'Jagatpura Sector 3 High Street',
    zone: 'Jagatpura',
    location: { latitude: 26.940400, longitude: 75.811300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jagatpura.',
  },
  {
    id: 'node-jai-9-1',
    name: 'Civil Lines Sector 1 High Street',
    zone: 'Civil Lines',
    location: { latitude: 26.946400, longitude: 75.815300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-jai-9-2',
    name: 'Civil Lines Sector 2 High Street',
    zone: 'Civil Lines',
    location: { latitude: 26.949400, longitude: 75.818300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-jai-9-3',
    name: 'Civil Lines Sector 3 High Street',
    zone: 'Civil Lines',
    location: { latitude: 26.952400, longitude: 75.821300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-jai-10-1',
    name: 'Ajmer Road Sector 1 High Street',
    zone: 'Ajmer Road',
    location: { latitude: 26.958400, longitude: 75.825300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ajmer Road.',
  },
  {
    id: 'node-jai-10-2',
    name: 'Ajmer Road Sector 2 High Street',
    zone: 'Ajmer Road',
    location: { latitude: 26.961400, longitude: 75.828300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ajmer Road.',
  },
  {
    id: 'node-jai-10-3',
    name: 'Ajmer Road Sector 3 High Street',
    zone: 'Ajmer Road',
    location: { latitude: 26.964400, longitude: 75.831300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ajmer Road.',
  },
];

export const JAIPUR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-jai-1',
    fromNodeId: 'node-jai-1-1',
    toNodeId: 'node-jai-1-2',
    roadName: 'C Scheme Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-2',
    fromNodeId: 'node-jai-1-2',
    toNodeId: 'node-jai-1-3',
    roadName: 'C Scheme Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-3',
    fromNodeId: 'node-jai-2-1',
    toNodeId: 'node-jai-2-2',
    roadName: 'Malviya Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-4',
    fromNodeId: 'node-jai-2-2',
    toNodeId: 'node-jai-2-3',
    roadName: 'Malviya Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-5',
    fromNodeId: 'node-jai-3-1',
    toNodeId: 'node-jai-3-2',
    roadName: 'Vaishali Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-6',
    fromNodeId: 'node-jai-3-2',
    toNodeId: 'node-jai-3-3',
    roadName: 'Vaishali Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-7',
    fromNodeId: 'node-jai-4-1',
    toNodeId: 'node-jai-4-2',
    roadName: 'Raja Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-8',
    fromNodeId: 'node-jai-4-2',
    toNodeId: 'node-jai-4-3',
    roadName: 'Raja Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-9',
    fromNodeId: 'node-jai-5-1',
    toNodeId: 'node-jai-5-2',
    roadName: 'Mansarovar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-10',
    fromNodeId: 'node-jai-5-2',
    toNodeId: 'node-jai-5-3',
    roadName: 'Mansarovar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-11',
    fromNodeId: 'node-jai-6-1',
    toNodeId: 'node-jai-6-2',
    roadName: 'Tonk Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-12',
    fromNodeId: 'node-jai-6-2',
    toNodeId: 'node-jai-6-3',
    roadName: 'Tonk Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-13',
    fromNodeId: 'node-jai-7-1',
    toNodeId: 'node-jai-7-2',
    roadName: 'Bani Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-14',
    fromNodeId: 'node-jai-7-2',
    toNodeId: 'node-jai-7-3',
    roadName: 'Bani Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-15',
    fromNodeId: 'node-jai-8-1',
    toNodeId: 'node-jai-8-2',
    roadName: 'Jagatpura Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-16',
    fromNodeId: 'node-jai-8-2',
    toNodeId: 'node-jai-8-3',
    roadName: 'Jagatpura Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-17',
    fromNodeId: 'node-jai-9-1',
    toNodeId: 'node-jai-9-2',
    roadName: 'Civil Lines Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-18',
    fromNodeId: 'node-jai-9-2',
    toNodeId: 'node-jai-9-3',
    roadName: 'Civil Lines Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-19',
    fromNodeId: 'node-jai-10-1',
    toNodeId: 'node-jai-10-2',
    roadName: 'Ajmer Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jai-20',
    fromNodeId: 'node-jai-10-2',
    toNodeId: 'node-jai-10-3',
    roadName: 'Ajmer Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
