/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Jakarta Jabodetabek Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const JAKARTA_BASE_COORDINATE: GeoCoordinate = {
  latitude: -6.2088,
  longitude: 106.8456,
};

export const JAKARTA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-jak-1-1',
    name: 'SCBD Sudirman Sector 1 High Street',
    zone: 'SCBD Sudirman',
    location: { latitude: -6.270800, longitude: 106.793600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in SCBD Sudirman.',
  },
  {
    id: 'node-jak-1-2',
    name: 'SCBD Sudirman Sector 2 High Street',
    zone: 'SCBD Sudirman',
    location: { latitude: -6.267800, longitude: 106.796600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in SCBD Sudirman.',
  },
  {
    id: 'node-jak-1-3',
    name: 'SCBD Sudirman Sector 3 High Street',
    zone: 'SCBD Sudirman',
    location: { latitude: -6.264800, longitude: 106.799600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in SCBD Sudirman.',
  },
  {
    id: 'node-jak-2-1',
    name: 'Menteng Sector 1 High Street',
    zone: 'Menteng',
    location: { latitude: -6.258800, longitude: 106.803600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Menteng.',
  },
  {
    id: 'node-jak-2-2',
    name: 'Menteng Sector 2 High Street',
    zone: 'Menteng',
    location: { latitude: -6.255800, longitude: 106.806600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Menteng.',
  },
  {
    id: 'node-jak-2-3',
    name: 'Menteng Sector 3 High Street',
    zone: 'Menteng',
    location: { latitude: -6.252800, longitude: 106.809600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Menteng.',
  },
  {
    id: 'node-jak-3-1',
    name: 'Kemang Sector 1 High Street',
    zone: 'Kemang',
    location: { latitude: -6.246800, longitude: 106.813600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kemang.',
  },
  {
    id: 'node-jak-3-2',
    name: 'Kemang Sector 2 High Street',
    zone: 'Kemang',
    location: { latitude: -6.243800, longitude: 106.816600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kemang.',
  },
  {
    id: 'node-jak-3-3',
    name: 'Kemang Sector 3 High Street',
    zone: 'Kemang',
    location: { latitude: -6.240800, longitude: 106.819600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kemang.',
  },
  {
    id: 'node-jak-4-1',
    name: 'Kuningan Sector 1 High Street',
    zone: 'Kuningan',
    location: { latitude: -6.234800, longitude: 106.823600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kuningan.',
  },
  {
    id: 'node-jak-4-2',
    name: 'Kuningan Sector 2 High Street',
    zone: 'Kuningan',
    location: { latitude: -6.231800, longitude: 106.826600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kuningan.',
  },
  {
    id: 'node-jak-4-3',
    name: 'Kuningan Sector 3 High Street',
    zone: 'Kuningan',
    location: { latitude: -6.228800, longitude: 106.829600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kuningan.',
  },
  {
    id: 'node-jak-5-1',
    name: 'Senopati Sector 1 High Street',
    zone: 'Senopati',
    location: { latitude: -6.222800, longitude: 106.833600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Senopati.',
  },
  {
    id: 'node-jak-5-2',
    name: 'Senopati Sector 2 High Street',
    zone: 'Senopati',
    location: { latitude: -6.219800, longitude: 106.836600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Senopati.',
  },
  {
    id: 'node-jak-5-3',
    name: 'Senopati Sector 3 High Street',
    zone: 'Senopati',
    location: { latitude: -6.216800, longitude: 106.839600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Senopati.',
  },
  {
    id: 'node-jak-6-1',
    name: 'PIK Pantai Indah Kapuk Sector 1 High Street',
    zone: 'PIK Pantai Indah Kapuk',
    location: { latitude: -6.210800, longitude: 106.843600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in PIK Pantai Indah Kapuk.',
  },
  {
    id: 'node-jak-6-2',
    name: 'PIK Pantai Indah Kapuk Sector 2 High Street',
    zone: 'PIK Pantai Indah Kapuk',
    location: { latitude: -6.207800, longitude: 106.846600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in PIK Pantai Indah Kapuk.',
  },
  {
    id: 'node-jak-6-3',
    name: 'PIK Pantai Indah Kapuk Sector 3 High Street',
    zone: 'PIK Pantai Indah Kapuk',
    location: { latitude: -6.204800, longitude: 106.849600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in PIK Pantai Indah Kapuk.',
  },
  {
    id: 'node-jak-7-1',
    name: 'Kelapa Gading Sector 1 High Street',
    zone: 'Kelapa Gading',
    location: { latitude: -6.198800, longitude: 106.853600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kelapa Gading.',
  },
  {
    id: 'node-jak-7-2',
    name: 'Kelapa Gading Sector 2 High Street',
    zone: 'Kelapa Gading',
    location: { latitude: -6.195800, longitude: 106.856600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kelapa Gading.',
  },
  {
    id: 'node-jak-7-3',
    name: 'Kelapa Gading Sector 3 High Street',
    zone: 'Kelapa Gading',
    location: { latitude: -6.192800, longitude: 106.859600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kelapa Gading.',
  },
  {
    id: 'node-jak-8-1',
    name: 'Pondok Indah Sector 1 High Street',
    zone: 'Pondok Indah',
    location: { latitude: -6.186800, longitude: 106.863600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pondok Indah.',
  },
  {
    id: 'node-jak-8-2',
    name: 'Pondok Indah Sector 2 High Street',
    zone: 'Pondok Indah',
    location: { latitude: -6.183800, longitude: 106.866600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pondok Indah.',
  },
  {
    id: 'node-jak-8-3',
    name: 'Pondok Indah Sector 3 High Street',
    zone: 'Pondok Indah',
    location: { latitude: -6.180800, longitude: 106.869600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pondok Indah.',
  },
  {
    id: 'node-jak-9-1',
    name: 'Tebet Sector 1 High Street',
    zone: 'Tebet',
    location: { latitude: -6.174800, longitude: 106.873600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tebet.',
  },
  {
    id: 'node-jak-9-2',
    name: 'Tebet Sector 2 High Street',
    zone: 'Tebet',
    location: { latitude: -6.171800, longitude: 106.876600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tebet.',
  },
  {
    id: 'node-jak-9-3',
    name: 'Tebet Sector 3 High Street',
    zone: 'Tebet',
    location: { latitude: -6.168800, longitude: 106.879600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tebet.',
  },
  {
    id: 'node-jak-10-1',
    name: 'Pluit Sector 1 High Street',
    zone: 'Pluit',
    location: { latitude: -6.162800, longitude: 106.883600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pluit.',
  },
  {
    id: 'node-jak-10-2',
    name: 'Pluit Sector 2 High Street',
    zone: 'Pluit',
    location: { latitude: -6.159800, longitude: 106.886600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pluit.',
  },
  {
    id: 'node-jak-10-3',
    name: 'Pluit Sector 3 High Street',
    zone: 'Pluit',
    location: { latitude: -6.156800, longitude: 106.889600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pluit.',
  },
];

export const JAKARTA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-jak-1',
    fromNodeId: 'node-jak-1-1',
    toNodeId: 'node-jak-1-2',
    roadName: 'SCBD Sudirman Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-2',
    fromNodeId: 'node-jak-1-2',
    toNodeId: 'node-jak-1-3',
    roadName: 'SCBD Sudirman Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-3',
    fromNodeId: 'node-jak-2-1',
    toNodeId: 'node-jak-2-2',
    roadName: 'Menteng Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-4',
    fromNodeId: 'node-jak-2-2',
    toNodeId: 'node-jak-2-3',
    roadName: 'Menteng Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-5',
    fromNodeId: 'node-jak-3-1',
    toNodeId: 'node-jak-3-2',
    roadName: 'Kemang Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-6',
    fromNodeId: 'node-jak-3-2',
    toNodeId: 'node-jak-3-3',
    roadName: 'Kemang Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-7',
    fromNodeId: 'node-jak-4-1',
    toNodeId: 'node-jak-4-2',
    roadName: 'Kuningan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-8',
    fromNodeId: 'node-jak-4-2',
    toNodeId: 'node-jak-4-3',
    roadName: 'Kuningan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-9',
    fromNodeId: 'node-jak-5-1',
    toNodeId: 'node-jak-5-2',
    roadName: 'Senopati Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-10',
    fromNodeId: 'node-jak-5-2',
    toNodeId: 'node-jak-5-3',
    roadName: 'Senopati Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-11',
    fromNodeId: 'node-jak-6-1',
    toNodeId: 'node-jak-6-2',
    roadName: 'PIK Pantai Indah Kapuk Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-12',
    fromNodeId: 'node-jak-6-2',
    toNodeId: 'node-jak-6-3',
    roadName: 'PIK Pantai Indah Kapuk Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-13',
    fromNodeId: 'node-jak-7-1',
    toNodeId: 'node-jak-7-2',
    roadName: 'Kelapa Gading Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-14',
    fromNodeId: 'node-jak-7-2',
    toNodeId: 'node-jak-7-3',
    roadName: 'Kelapa Gading Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-15',
    fromNodeId: 'node-jak-8-1',
    toNodeId: 'node-jak-8-2',
    roadName: 'Pondok Indah Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-16',
    fromNodeId: 'node-jak-8-2',
    toNodeId: 'node-jak-8-3',
    roadName: 'Pondok Indah Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-17',
    fromNodeId: 'node-jak-9-1',
    toNodeId: 'node-jak-9-2',
    roadName: 'Tebet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-18',
    fromNodeId: 'node-jak-9-2',
    toNodeId: 'node-jak-9-3',
    roadName: 'Tebet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-19',
    fromNodeId: 'node-jak-10-1',
    toNodeId: 'node-jak-10-2',
    roadName: 'Pluit Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jak-20',
    fromNodeId: 'node-jak-10-2',
    toNodeId: 'node-jak-10-3',
    roadName: 'Pluit Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
