/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Jamshedpur Steel City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const JAMSHEDPUR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 22.8046,
  longitude: 86.2029,
};

export const JAMSHEDPUR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-jam-1-1',
    name: 'Bistupur Sector 1 High Street',
    zone: 'Bistupur',
    location: { latitude: 22.742600, longitude: 86.150900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bistupur.',
  },
  {
    id: 'node-jam-1-2',
    name: 'Bistupur Sector 2 High Street',
    zone: 'Bistupur',
    location: { latitude: 22.745600, longitude: 86.153900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bistupur.',
  },
  {
    id: 'node-jam-1-3',
    name: 'Bistupur Sector 3 High Street',
    zone: 'Bistupur',
    location: { latitude: 22.748600, longitude: 86.156900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bistupur.',
  },
  {
    id: 'node-jam-2-1',
    name: 'Sakchi Sector 1 High Street',
    zone: 'Sakchi',
    location: { latitude: 22.754600, longitude: 86.160900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sakchi.',
  },
  {
    id: 'node-jam-2-2',
    name: 'Sakchi Sector 2 High Street',
    zone: 'Sakchi',
    location: { latitude: 22.757600, longitude: 86.163900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sakchi.',
  },
  {
    id: 'node-jam-2-3',
    name: 'Sakchi Sector 3 High Street',
    zone: 'Sakchi',
    location: { latitude: 22.760600, longitude: 86.166900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sakchi.',
  },
  {
    id: 'node-jam-3-1',
    name: 'Kadma Sector 1 High Street',
    zone: 'Kadma',
    location: { latitude: 22.766600, longitude: 86.170900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kadma.',
  },
  {
    id: 'node-jam-3-2',
    name: 'Kadma Sector 2 High Street',
    zone: 'Kadma',
    location: { latitude: 22.769600, longitude: 86.173900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kadma.',
  },
  {
    id: 'node-jam-3-3',
    name: 'Kadma Sector 3 High Street',
    zone: 'Kadma',
    location: { latitude: 22.772600, longitude: 86.176900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kadma.',
  },
  {
    id: 'node-jam-4-1',
    name: 'Sonari Sector 1 High Street',
    zone: 'Sonari',
    location: { latitude: 22.778600, longitude: 86.180900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sonari.',
  },
  {
    id: 'node-jam-4-2',
    name: 'Sonari Sector 2 High Street',
    zone: 'Sonari',
    location: { latitude: 22.781600, longitude: 86.183900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sonari.',
  },
  {
    id: 'node-jam-4-3',
    name: 'Sonari Sector 3 High Street',
    zone: 'Sonari',
    location: { latitude: 22.784600, longitude: 86.186900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sonari.',
  },
  {
    id: 'node-jam-5-1',
    name: 'Telco Colony Sector 1 High Street',
    zone: 'Telco Colony',
    location: { latitude: 22.790600, longitude: 86.190900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Telco Colony.',
  },
  {
    id: 'node-jam-5-2',
    name: 'Telco Colony Sector 2 High Street',
    zone: 'Telco Colony',
    location: { latitude: 22.793600, longitude: 86.193900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Telco Colony.',
  },
  {
    id: 'node-jam-5-3',
    name: 'Telco Colony Sector 3 High Street',
    zone: 'Telco Colony',
    location: { latitude: 22.796600, longitude: 86.196900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Telco Colony.',
  },
  {
    id: 'node-jam-6-1',
    name: 'Golmuri Sector 1 High Street',
    zone: 'Golmuri',
    location: { latitude: 22.802600, longitude: 86.200900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Golmuri.',
  },
  {
    id: 'node-jam-6-2',
    name: 'Golmuri Sector 2 High Street',
    zone: 'Golmuri',
    location: { latitude: 22.805600, longitude: 86.203900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Golmuri.',
  },
  {
    id: 'node-jam-6-3',
    name: 'Golmuri Sector 3 High Street',
    zone: 'Golmuri',
    location: { latitude: 22.808600, longitude: 86.206900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Golmuri.',
  },
  {
    id: 'node-jam-7-1',
    name: 'Baridih Sector 1 High Street',
    zone: 'Baridih',
    location: { latitude: 22.814600, longitude: 86.210900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Baridih.',
  },
  {
    id: 'node-jam-7-2',
    name: 'Baridih Sector 2 High Street',
    zone: 'Baridih',
    location: { latitude: 22.817600, longitude: 86.213900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Baridih.',
  },
  {
    id: 'node-jam-7-3',
    name: 'Baridih Sector 3 High Street',
    zone: 'Baridih',
    location: { latitude: 22.820600, longitude: 86.216900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Baridih.',
  },
  {
    id: 'node-jam-8-1',
    name: 'Jugsalai Sector 1 High Street',
    zone: 'Jugsalai',
    location: { latitude: 22.826600, longitude: 86.220900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jugsalai.',
  },
  {
    id: 'node-jam-8-2',
    name: 'Jugsalai Sector 2 High Street',
    zone: 'Jugsalai',
    location: { latitude: 22.829600, longitude: 86.223900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jugsalai.',
  },
  {
    id: 'node-jam-8-3',
    name: 'Jugsalai Sector 3 High Street',
    zone: 'Jugsalai',
    location: { latitude: 22.832600, longitude: 86.226900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jugsalai.',
  },
  {
    id: 'node-jam-9-1',
    name: 'Adityapur Sector 1 High Street',
    zone: 'Adityapur',
    location: { latitude: 22.838600, longitude: 86.230900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Adityapur.',
  },
  {
    id: 'node-jam-9-2',
    name: 'Adityapur Sector 2 High Street',
    zone: 'Adityapur',
    location: { latitude: 22.841600, longitude: 86.233900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Adityapur.',
  },
  {
    id: 'node-jam-9-3',
    name: 'Adityapur Sector 3 High Street',
    zone: 'Adityapur',
    location: { latitude: 22.844600, longitude: 86.236900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Adityapur.',
  },
  {
    id: 'node-jam-10-1',
    name: 'Mango Sector 1 High Street',
    zone: 'Mango',
    location: { latitude: 22.850600, longitude: 86.240900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mango.',
  },
  {
    id: 'node-jam-10-2',
    name: 'Mango Sector 2 High Street',
    zone: 'Mango',
    location: { latitude: 22.853600, longitude: 86.243900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mango.',
  },
  {
    id: 'node-jam-10-3',
    name: 'Mango Sector 3 High Street',
    zone: 'Mango',
    location: { latitude: 22.856600, longitude: 86.246900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mango.',
  },
];

export const JAMSHEDPUR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-jam-1',
    fromNodeId: 'node-jam-1-1',
    toNodeId: 'node-jam-1-2',
    roadName: 'Bistupur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-2',
    fromNodeId: 'node-jam-1-2',
    toNodeId: 'node-jam-1-3',
    roadName: 'Bistupur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-3',
    fromNodeId: 'node-jam-2-1',
    toNodeId: 'node-jam-2-2',
    roadName: 'Sakchi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-4',
    fromNodeId: 'node-jam-2-2',
    toNodeId: 'node-jam-2-3',
    roadName: 'Sakchi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-5',
    fromNodeId: 'node-jam-3-1',
    toNodeId: 'node-jam-3-2',
    roadName: 'Kadma Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-6',
    fromNodeId: 'node-jam-3-2',
    toNodeId: 'node-jam-3-3',
    roadName: 'Kadma Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-7',
    fromNodeId: 'node-jam-4-1',
    toNodeId: 'node-jam-4-2',
    roadName: 'Sonari Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-8',
    fromNodeId: 'node-jam-4-2',
    toNodeId: 'node-jam-4-3',
    roadName: 'Sonari Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-9',
    fromNodeId: 'node-jam-5-1',
    toNodeId: 'node-jam-5-2',
    roadName: 'Telco Colony Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-10',
    fromNodeId: 'node-jam-5-2',
    toNodeId: 'node-jam-5-3',
    roadName: 'Telco Colony Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-11',
    fromNodeId: 'node-jam-6-1',
    toNodeId: 'node-jam-6-2',
    roadName: 'Golmuri Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-12',
    fromNodeId: 'node-jam-6-2',
    toNodeId: 'node-jam-6-3',
    roadName: 'Golmuri Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-13',
    fromNodeId: 'node-jam-7-1',
    toNodeId: 'node-jam-7-2',
    roadName: 'Baridih Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-14',
    fromNodeId: 'node-jam-7-2',
    toNodeId: 'node-jam-7-3',
    roadName: 'Baridih Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-15',
    fromNodeId: 'node-jam-8-1',
    toNodeId: 'node-jam-8-2',
    roadName: 'Jugsalai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-16',
    fromNodeId: 'node-jam-8-2',
    toNodeId: 'node-jam-8-3',
    roadName: 'Jugsalai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-17',
    fromNodeId: 'node-jam-9-1',
    toNodeId: 'node-jam-9-2',
    roadName: 'Adityapur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-18',
    fromNodeId: 'node-jam-9-2',
    toNodeId: 'node-jam-9-3',
    roadName: 'Adityapur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-19',
    fromNodeId: 'node-jam-10-1',
    toNodeId: 'node-jam-10-2',
    roadName: 'Mango Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jam-20',
    fromNodeId: 'node-jam-10-2',
    toNodeId: 'node-jam-10-3',
    roadName: 'Mango Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
