/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Jodhpur Blue City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const JODHPUR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 26.2389,
  longitude: 73.0243,
};

export const JODHPUR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-jod-1-1',
    name: 'Ratanada Sector 1 High Street',
    zone: 'Ratanada',
    location: { latitude: 26.176900, longitude: 72.972300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ratanada.',
  },
  {
    id: 'node-jod-1-2',
    name: 'Ratanada Sector 2 High Street',
    zone: 'Ratanada',
    location: { latitude: 26.179900, longitude: 72.975300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ratanada.',
  },
  {
    id: 'node-jod-1-3',
    name: 'Ratanada Sector 3 High Street',
    zone: 'Ratanada',
    location: { latitude: 26.182900, longitude: 72.978300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ratanada.',
  },
  {
    id: 'node-jod-2-1',
    name: 'Shastri Nagar Sector 1 High Street',
    zone: 'Shastri Nagar',
    location: { latitude: 26.188900, longitude: 72.982300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shastri Nagar.',
  },
  {
    id: 'node-jod-2-2',
    name: 'Shastri Nagar Sector 2 High Street',
    zone: 'Shastri Nagar',
    location: { latitude: 26.191900, longitude: 72.985300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shastri Nagar.',
  },
  {
    id: 'node-jod-2-3',
    name: 'Shastri Nagar Sector 3 High Street',
    zone: 'Shastri Nagar',
    location: { latitude: 26.194900, longitude: 72.988300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shastri Nagar.',
  },
  {
    id: 'node-jod-3-1',
    name: 'Sardarpura Sector 1 High Street',
    zone: 'Sardarpura',
    location: { latitude: 26.200900, longitude: 72.992300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sardarpura.',
  },
  {
    id: 'node-jod-3-2',
    name: 'Sardarpura Sector 2 High Street',
    zone: 'Sardarpura',
    location: { latitude: 26.203900, longitude: 72.995300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sardarpura.',
  },
  {
    id: 'node-jod-3-3',
    name: 'Sardarpura Sector 3 High Street',
    zone: 'Sardarpura',
    location: { latitude: 26.206900, longitude: 72.998300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sardarpura.',
  },
  {
    id: 'node-jod-4-1',
    name: 'Paota Sector 1 High Street',
    zone: 'Paota',
    location: { latitude: 26.212900, longitude: 73.002300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Paota.',
  },
  {
    id: 'node-jod-4-2',
    name: 'Paota Sector 2 High Street',
    zone: 'Paota',
    location: { latitude: 26.215900, longitude: 73.005300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Paota.',
  },
  {
    id: 'node-jod-4-3',
    name: 'Paota Sector 3 High Street',
    zone: 'Paota',
    location: { latitude: 26.218900, longitude: 73.008300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Paota.',
  },
  {
    id: 'node-jod-5-1',
    name: 'Residency Road Sector 1 High Street',
    zone: 'Residency Road',
    location: { latitude: 26.224900, longitude: 73.012300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Residency Road.',
  },
  {
    id: 'node-jod-5-2',
    name: 'Residency Road Sector 2 High Street',
    zone: 'Residency Road',
    location: { latitude: 26.227900, longitude: 73.015300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Residency Road.',
  },
  {
    id: 'node-jod-5-3',
    name: 'Residency Road Sector 3 High Street',
    zone: 'Residency Road',
    location: { latitude: 26.230900, longitude: 73.018300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Residency Road.',
  },
  {
    id: 'node-jod-6-1',
    name: 'Pal Road Sector 1 High Street',
    zone: 'Pal Road',
    location: { latitude: 26.236900, longitude: 73.022300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pal Road.',
  },
  {
    id: 'node-jod-6-2',
    name: 'Pal Road Sector 2 High Street',
    zone: 'Pal Road',
    location: { latitude: 26.239900, longitude: 73.025300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pal Road.',
  },
  {
    id: 'node-jod-6-3',
    name: 'Pal Road Sector 3 High Street',
    zone: 'Pal Road',
    location: { latitude: 26.242900, longitude: 73.028300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pal Road.',
  },
  {
    id: 'node-jod-7-1',
    name: 'Chopasni Housing Sector 1 High Street',
    zone: 'Chopasni Housing',
    location: { latitude: 26.248900, longitude: 73.032300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chopasni Housing.',
  },
  {
    id: 'node-jod-7-2',
    name: 'Chopasni Housing Sector 2 High Street',
    zone: 'Chopasni Housing',
    location: { latitude: 26.251900, longitude: 73.035300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chopasni Housing.',
  },
  {
    id: 'node-jod-7-3',
    name: 'Chopasni Housing Sector 3 High Street',
    zone: 'Chopasni Housing',
    location: { latitude: 26.254900, longitude: 73.038300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chopasni Housing.',
  },
  {
    id: 'node-jod-8-1',
    name: 'Air Force Area Sector 1 High Street',
    zone: 'Air Force Area',
    location: { latitude: 26.260900, longitude: 73.042300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Air Force Area.',
  },
  {
    id: 'node-jod-8-2',
    name: 'Air Force Area Sector 2 High Street',
    zone: 'Air Force Area',
    location: { latitude: 26.263900, longitude: 73.045300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Air Force Area.',
  },
  {
    id: 'node-jod-8-3',
    name: 'Air Force Area Sector 3 High Street',
    zone: 'Air Force Area',
    location: { latitude: 26.266900, longitude: 73.048300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Air Force Area.',
  },
  {
    id: 'node-jod-9-1',
    name: 'Mandore Sector 1 High Street',
    zone: 'Mandore',
    location: { latitude: 26.272900, longitude: 73.052300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mandore.',
  },
  {
    id: 'node-jod-9-2',
    name: 'Mandore Sector 2 High Street',
    zone: 'Mandore',
    location: { latitude: 26.275900, longitude: 73.055300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mandore.',
  },
  {
    id: 'node-jod-9-3',
    name: 'Mandore Sector 3 High Street',
    zone: 'Mandore',
    location: { latitude: 26.278900, longitude: 73.058300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mandore.',
  },
  {
    id: 'node-jod-10-1',
    name: 'Basni Sector 1 High Street',
    zone: 'Basni',
    location: { latitude: 26.284900, longitude: 73.062300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Basni.',
  },
  {
    id: 'node-jod-10-2',
    name: 'Basni Sector 2 High Street',
    zone: 'Basni',
    location: { latitude: 26.287900, longitude: 73.065300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Basni.',
  },
  {
    id: 'node-jod-10-3',
    name: 'Basni Sector 3 High Street',
    zone: 'Basni',
    location: { latitude: 26.290900, longitude: 73.068300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Basni.',
  },
];

export const JODHPUR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-jod-1',
    fromNodeId: 'node-jod-1-1',
    toNodeId: 'node-jod-1-2',
    roadName: 'Ratanada Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-2',
    fromNodeId: 'node-jod-1-2',
    toNodeId: 'node-jod-1-3',
    roadName: 'Ratanada Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-3',
    fromNodeId: 'node-jod-2-1',
    toNodeId: 'node-jod-2-2',
    roadName: 'Shastri Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-4',
    fromNodeId: 'node-jod-2-2',
    toNodeId: 'node-jod-2-3',
    roadName: 'Shastri Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-5',
    fromNodeId: 'node-jod-3-1',
    toNodeId: 'node-jod-3-2',
    roadName: 'Sardarpura Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-6',
    fromNodeId: 'node-jod-3-2',
    toNodeId: 'node-jod-3-3',
    roadName: 'Sardarpura Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-7',
    fromNodeId: 'node-jod-4-1',
    toNodeId: 'node-jod-4-2',
    roadName: 'Paota Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-8',
    fromNodeId: 'node-jod-4-2',
    toNodeId: 'node-jod-4-3',
    roadName: 'Paota Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-9',
    fromNodeId: 'node-jod-5-1',
    toNodeId: 'node-jod-5-2',
    roadName: 'Residency Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-10',
    fromNodeId: 'node-jod-5-2',
    toNodeId: 'node-jod-5-3',
    roadName: 'Residency Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-11',
    fromNodeId: 'node-jod-6-1',
    toNodeId: 'node-jod-6-2',
    roadName: 'Pal Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-12',
    fromNodeId: 'node-jod-6-2',
    toNodeId: 'node-jod-6-3',
    roadName: 'Pal Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-13',
    fromNodeId: 'node-jod-7-1',
    toNodeId: 'node-jod-7-2',
    roadName: 'Chopasni Housing Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-14',
    fromNodeId: 'node-jod-7-2',
    toNodeId: 'node-jod-7-3',
    roadName: 'Chopasni Housing Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-15',
    fromNodeId: 'node-jod-8-1',
    toNodeId: 'node-jod-8-2',
    roadName: 'Air Force Area Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-16',
    fromNodeId: 'node-jod-8-2',
    toNodeId: 'node-jod-8-3',
    roadName: 'Air Force Area Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-17',
    fromNodeId: 'node-jod-9-1',
    toNodeId: 'node-jod-9-2',
    roadName: 'Mandore Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-18',
    fromNodeId: 'node-jod-9-2',
    toNodeId: 'node-jod-9-3',
    roadName: 'Mandore Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-19',
    fromNodeId: 'node-jod-10-1',
    toNodeId: 'node-jod-10-2',
    roadName: 'Basni Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-jod-20',
    fromNodeId: 'node-jod-10-2',
    toNodeId: 'node-jod-10-3',
    roadName: 'Basni Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
