/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Johannesburg Gauteng Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const JOHANNESBURG_BASE_COORDINATE: GeoCoordinate = {
  latitude: -26.2041,
  longitude: 28.0473,
};

export const JOHANNESBURG_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-joh-1-1',
    name: 'Sandton Sector 1 High Street',
    zone: 'Sandton',
    location: { latitude: -26.266100, longitude: 27.995300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sandton.',
  },
  {
    id: 'node-joh-1-2',
    name: 'Sandton Sector 2 High Street',
    zone: 'Sandton',
    location: { latitude: -26.263100, longitude: 27.998300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sandton.',
  },
  {
    id: 'node-joh-1-3',
    name: 'Sandton Sector 3 High Street',
    zone: 'Sandton',
    location: { latitude: -26.260100, longitude: 28.001300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sandton.',
  },
  {
    id: 'node-joh-2-1',
    name: 'Rosebank Sector 1 High Street',
    zone: 'Rosebank',
    location: { latitude: -26.254100, longitude: 28.005300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rosebank.',
  },
  {
    id: 'node-joh-2-2',
    name: 'Rosebank Sector 2 High Street',
    zone: 'Rosebank',
    location: { latitude: -26.251100, longitude: 28.008300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rosebank.',
  },
  {
    id: 'node-joh-2-3',
    name: 'Rosebank Sector 3 High Street',
    zone: 'Rosebank',
    location: { latitude: -26.248100, longitude: 28.011300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rosebank.',
  },
  {
    id: 'node-joh-3-1',
    name: 'Melrose Arch Sector 1 High Street',
    zone: 'Melrose Arch',
    location: { latitude: -26.242100, longitude: 28.015300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Melrose Arch.',
  },
  {
    id: 'node-joh-3-2',
    name: 'Melrose Arch Sector 2 High Street',
    zone: 'Melrose Arch',
    location: { latitude: -26.239100, longitude: 28.018300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Melrose Arch.',
  },
  {
    id: 'node-joh-3-3',
    name: 'Melrose Arch Sector 3 High Street',
    zone: 'Melrose Arch',
    location: { latitude: -26.236100, longitude: 28.021300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Melrose Arch.',
  },
  {
    id: 'node-joh-4-1',
    name: 'Parkhurst Sector 1 High Street',
    zone: 'Parkhurst',
    location: { latitude: -26.230100, longitude: 28.025300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Parkhurst.',
  },
  {
    id: 'node-joh-4-2',
    name: 'Parkhurst Sector 2 High Street',
    zone: 'Parkhurst',
    location: { latitude: -26.227100, longitude: 28.028300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Parkhurst.',
  },
  {
    id: 'node-joh-4-3',
    name: 'Parkhurst Sector 3 High Street',
    zone: 'Parkhurst',
    location: { latitude: -26.224100, longitude: 28.031300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Parkhurst.',
  },
  {
    id: 'node-joh-5-1',
    name: 'Maboneng Sector 1 High Street',
    zone: 'Maboneng',
    location: { latitude: -26.218100, longitude: 28.035300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Maboneng.',
  },
  {
    id: 'node-joh-5-2',
    name: 'Maboneng Sector 2 High Street',
    zone: 'Maboneng',
    location: { latitude: -26.215100, longitude: 28.038300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Maboneng.',
  },
  {
    id: 'node-joh-5-3',
    name: 'Maboneng Sector 3 High Street',
    zone: 'Maboneng',
    location: { latitude: -26.212100, longitude: 28.041300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Maboneng.',
  },
  {
    id: 'node-joh-6-1',
    name: 'Fourways Sector 1 High Street',
    zone: 'Fourways',
    location: { latitude: -26.206100, longitude: 28.045300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fourways.',
  },
  {
    id: 'node-joh-6-2',
    name: 'Fourways Sector 2 High Street',
    zone: 'Fourways',
    location: { latitude: -26.203100, longitude: 28.048300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fourways.',
  },
  {
    id: 'node-joh-6-3',
    name: 'Fourways Sector 3 High Street',
    zone: 'Fourways',
    location: { latitude: -26.200100, longitude: 28.051300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fourways.',
  },
  {
    id: 'node-joh-7-1',
    name: 'Bryanston Sector 1 High Street',
    zone: 'Bryanston',
    location: { latitude: -26.194100, longitude: 28.055300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bryanston.',
  },
  {
    id: 'node-joh-7-2',
    name: 'Bryanston Sector 2 High Street',
    zone: 'Bryanston',
    location: { latitude: -26.191100, longitude: 28.058300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bryanston.',
  },
  {
    id: 'node-joh-7-3',
    name: 'Bryanston Sector 3 High Street',
    zone: 'Bryanston',
    location: { latitude: -26.188100, longitude: 28.061300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bryanston.',
  },
  {
    id: 'node-joh-8-1',
    name: 'Houghton Sector 1 High Street',
    zone: 'Houghton',
    location: { latitude: -26.182100, longitude: 28.065300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Houghton.',
  },
  {
    id: 'node-joh-8-2',
    name: 'Houghton Sector 2 High Street',
    zone: 'Houghton',
    location: { latitude: -26.179100, longitude: 28.068300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Houghton.',
  },
  {
    id: 'node-joh-8-3',
    name: 'Houghton Sector 3 High Street',
    zone: 'Houghton',
    location: { latitude: -26.176100, longitude: 28.071300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Houghton.',
  },
  {
    id: 'node-joh-9-1',
    name: 'Braamfontein Sector 1 High Street',
    zone: 'Braamfontein',
    location: { latitude: -26.170100, longitude: 28.075300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Braamfontein.',
  },
  {
    id: 'node-joh-9-2',
    name: 'Braamfontein Sector 2 High Street',
    zone: 'Braamfontein',
    location: { latitude: -26.167100, longitude: 28.078300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Braamfontein.',
  },
  {
    id: 'node-joh-9-3',
    name: 'Braamfontein Sector 3 High Street',
    zone: 'Braamfontein',
    location: { latitude: -26.164100, longitude: 28.081300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Braamfontein.',
  },
  {
    id: 'node-joh-10-1',
    name: 'Greenside Sector 1 High Street',
    zone: 'Greenside',
    location: { latitude: -26.158100, longitude: 28.085300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Greenside.',
  },
  {
    id: 'node-joh-10-2',
    name: 'Greenside Sector 2 High Street',
    zone: 'Greenside',
    location: { latitude: -26.155100, longitude: 28.088300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Greenside.',
  },
  {
    id: 'node-joh-10-3',
    name: 'Greenside Sector 3 High Street',
    zone: 'Greenside',
    location: { latitude: -26.152100, longitude: 28.091300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Greenside.',
  },
];

export const JOHANNESBURG_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-joh-1',
    fromNodeId: 'node-joh-1-1',
    toNodeId: 'node-joh-1-2',
    roadName: 'Sandton Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-2',
    fromNodeId: 'node-joh-1-2',
    toNodeId: 'node-joh-1-3',
    roadName: 'Sandton Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-3',
    fromNodeId: 'node-joh-2-1',
    toNodeId: 'node-joh-2-2',
    roadName: 'Rosebank Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-4',
    fromNodeId: 'node-joh-2-2',
    toNodeId: 'node-joh-2-3',
    roadName: 'Rosebank Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-5',
    fromNodeId: 'node-joh-3-1',
    toNodeId: 'node-joh-3-2',
    roadName: 'Melrose Arch Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-6',
    fromNodeId: 'node-joh-3-2',
    toNodeId: 'node-joh-3-3',
    roadName: 'Melrose Arch Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-7',
    fromNodeId: 'node-joh-4-1',
    toNodeId: 'node-joh-4-2',
    roadName: 'Parkhurst Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-8',
    fromNodeId: 'node-joh-4-2',
    toNodeId: 'node-joh-4-3',
    roadName: 'Parkhurst Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-9',
    fromNodeId: 'node-joh-5-1',
    toNodeId: 'node-joh-5-2',
    roadName: 'Maboneng Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-10',
    fromNodeId: 'node-joh-5-2',
    toNodeId: 'node-joh-5-3',
    roadName: 'Maboneng Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-11',
    fromNodeId: 'node-joh-6-1',
    toNodeId: 'node-joh-6-2',
    roadName: 'Fourways Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-12',
    fromNodeId: 'node-joh-6-2',
    toNodeId: 'node-joh-6-3',
    roadName: 'Fourways Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-13',
    fromNodeId: 'node-joh-7-1',
    toNodeId: 'node-joh-7-2',
    roadName: 'Bryanston Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-14',
    fromNodeId: 'node-joh-7-2',
    toNodeId: 'node-joh-7-3',
    roadName: 'Bryanston Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-15',
    fromNodeId: 'node-joh-8-1',
    toNodeId: 'node-joh-8-2',
    roadName: 'Houghton Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-16',
    fromNodeId: 'node-joh-8-2',
    toNodeId: 'node-joh-8-3',
    roadName: 'Houghton Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-17',
    fromNodeId: 'node-joh-9-1',
    toNodeId: 'node-joh-9-2',
    roadName: 'Braamfontein Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-18',
    fromNodeId: 'node-joh-9-2',
    toNodeId: 'node-joh-9-3',
    roadName: 'Braamfontein Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-19',
    fromNodeId: 'node-joh-10-1',
    toNodeId: 'node-joh-10-2',
    roadName: 'Greenside Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-joh-20',
    fromNodeId: 'node-joh-10-2',
    toNodeId: 'node-joh-10-3',
    roadName: 'Greenside Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
