/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Kanpur Industrial Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const KANPUR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 26.4499,
  longitude: 80.3319,
};

export const KANPUR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-kan-1-1',
    name: 'Swaroop Nagar Sector 1 High Street',
    zone: 'Swaroop Nagar',
    location: { latitude: 26.387900, longitude: 80.279900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Swaroop Nagar.',
  },
  {
    id: 'node-kan-1-2',
    name: 'Swaroop Nagar Sector 2 High Street',
    zone: 'Swaroop Nagar',
    location: { latitude: 26.390900, longitude: 80.282900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Swaroop Nagar.',
  },
  {
    id: 'node-kan-1-3',
    name: 'Swaroop Nagar Sector 3 High Street',
    zone: 'Swaroop Nagar',
    location: { latitude: 26.393900, longitude: 80.285900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Swaroop Nagar.',
  },
  {
    id: 'node-kan-2-1',
    name: 'Civil Lines Sector 1 High Street',
    zone: 'Civil Lines',
    location: { latitude: 26.399900, longitude: 80.289900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-kan-2-2',
    name: 'Civil Lines Sector 2 High Street',
    zone: 'Civil Lines',
    location: { latitude: 26.402900, longitude: 80.292900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-kan-2-3',
    name: 'Civil Lines Sector 3 High Street',
    zone: 'Civil Lines',
    location: { latitude: 26.405900, longitude: 80.295900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-kan-3-1',
    name: 'Kakadeo Sector 1 High Street',
    zone: 'Kakadeo',
    location: { latitude: 26.411900, longitude: 80.299900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kakadeo.',
  },
  {
    id: 'node-kan-3-2',
    name: 'Kakadeo Sector 2 High Street',
    zone: 'Kakadeo',
    location: { latitude: 26.414900, longitude: 80.302900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kakadeo.',
  },
  {
    id: 'node-kan-3-3',
    name: 'Kakadeo Sector 3 High Street',
    zone: 'Kakadeo',
    location: { latitude: 26.417900, longitude: 80.305900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kakadeo.',
  },
  {
    id: 'node-kan-4-1',
    name: 'Govind Nagar Sector 1 High Street',
    zone: 'Govind Nagar',
    location: { latitude: 26.423900, longitude: 80.309900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Govind Nagar.',
  },
  {
    id: 'node-kan-4-2',
    name: 'Govind Nagar Sector 2 High Street',
    zone: 'Govind Nagar',
    location: { latitude: 26.426900, longitude: 80.312900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Govind Nagar.',
  },
  {
    id: 'node-kan-4-3',
    name: 'Govind Nagar Sector 3 High Street',
    zone: 'Govind Nagar',
    location: { latitude: 26.429900, longitude: 80.315900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Govind Nagar.',
  },
  {
    id: 'node-kan-5-1',
    name: 'Kidwai Nagar Sector 1 High Street',
    zone: 'Kidwai Nagar',
    location: { latitude: 26.435900, longitude: 80.319900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kidwai Nagar.',
  },
  {
    id: 'node-kan-5-2',
    name: 'Kidwai Nagar Sector 2 High Street',
    zone: 'Kidwai Nagar',
    location: { latitude: 26.438900, longitude: 80.322900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kidwai Nagar.',
  },
  {
    id: 'node-kan-5-3',
    name: 'Kidwai Nagar Sector 3 High Street',
    zone: 'Kidwai Nagar',
    location: { latitude: 26.441900, longitude: 80.325900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kidwai Nagar.',
  },
  {
    id: 'node-kan-6-1',
    name: 'Gumti No 5 Sector 1 High Street',
    zone: 'Gumti No 5',
    location: { latitude: 26.447900, longitude: 80.329900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gumti No 5.',
  },
  {
    id: 'node-kan-6-2',
    name: 'Gumti No 5 Sector 2 High Street',
    zone: 'Gumti No 5',
    location: { latitude: 26.450900, longitude: 80.332900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gumti No 5.',
  },
  {
    id: 'node-kan-6-3',
    name: 'Gumti No 5 Sector 3 High Street',
    zone: 'Gumti No 5',
    location: { latitude: 26.453900, longitude: 80.335900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gumti No 5.',
  },
  {
    id: 'node-kan-7-1',
    name: 'Mall Road Sector 1 High Street',
    zone: 'Mall Road',
    location: { latitude: 26.459900, longitude: 80.339900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mall Road.',
  },
  {
    id: 'node-kan-7-2',
    name: 'Mall Road Sector 2 High Street',
    zone: 'Mall Road',
    location: { latitude: 26.462900, longitude: 80.342900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mall Road.',
  },
  {
    id: 'node-kan-7-3',
    name: 'Mall Road Sector 3 High Street',
    zone: 'Mall Road',
    location: { latitude: 26.465900, longitude: 80.345900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mall Road.',
  },
  {
    id: 'node-kan-8-1',
    name: 'Panki Sector 1 High Street',
    zone: 'Panki',
    location: { latitude: 26.471900, longitude: 80.349900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Panki.',
  },
  {
    id: 'node-kan-8-2',
    name: 'Panki Sector 2 High Street',
    zone: 'Panki',
    location: { latitude: 26.474900, longitude: 80.352900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Panki.',
  },
  {
    id: 'node-kan-8-3',
    name: 'Panki Sector 3 High Street',
    zone: 'Panki',
    location: { latitude: 26.477900, longitude: 80.355900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Panki.',
  },
  {
    id: 'node-kan-9-1',
    name: 'Kalyanpur Sector 1 High Street',
    zone: 'Kalyanpur',
    location: { latitude: 26.483900, longitude: 80.359900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kalyanpur.',
  },
  {
    id: 'node-kan-9-2',
    name: 'Kalyanpur Sector 2 High Street',
    zone: 'Kalyanpur',
    location: { latitude: 26.486900, longitude: 80.362900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kalyanpur.',
  },
  {
    id: 'node-kan-9-3',
    name: 'Kalyanpur Sector 3 High Street',
    zone: 'Kalyanpur',
    location: { latitude: 26.489900, longitude: 80.365900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kalyanpur.',
  },
  {
    id: 'node-kan-10-1',
    name: 'Shyam Nagar Sector 1 High Street',
    zone: 'Shyam Nagar',
    location: { latitude: 26.495900, longitude: 80.369900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shyam Nagar.',
  },
  {
    id: 'node-kan-10-2',
    name: 'Shyam Nagar Sector 2 High Street',
    zone: 'Shyam Nagar',
    location: { latitude: 26.498900, longitude: 80.372900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shyam Nagar.',
  },
  {
    id: 'node-kan-10-3',
    name: 'Shyam Nagar Sector 3 High Street',
    zone: 'Shyam Nagar',
    location: { latitude: 26.501900, longitude: 80.375900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shyam Nagar.',
  },
];

export const KANPUR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-kan-1',
    fromNodeId: 'node-kan-1-1',
    toNodeId: 'node-kan-1-2',
    roadName: 'Swaroop Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-2',
    fromNodeId: 'node-kan-1-2',
    toNodeId: 'node-kan-1-3',
    roadName: 'Swaroop Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-3',
    fromNodeId: 'node-kan-2-1',
    toNodeId: 'node-kan-2-2',
    roadName: 'Civil Lines Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-4',
    fromNodeId: 'node-kan-2-2',
    toNodeId: 'node-kan-2-3',
    roadName: 'Civil Lines Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-5',
    fromNodeId: 'node-kan-3-1',
    toNodeId: 'node-kan-3-2',
    roadName: 'Kakadeo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-6',
    fromNodeId: 'node-kan-3-2',
    toNodeId: 'node-kan-3-3',
    roadName: 'Kakadeo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-7',
    fromNodeId: 'node-kan-4-1',
    toNodeId: 'node-kan-4-2',
    roadName: 'Govind Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-8',
    fromNodeId: 'node-kan-4-2',
    toNodeId: 'node-kan-4-3',
    roadName: 'Govind Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-9',
    fromNodeId: 'node-kan-5-1',
    toNodeId: 'node-kan-5-2',
    roadName: 'Kidwai Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-10',
    fromNodeId: 'node-kan-5-2',
    toNodeId: 'node-kan-5-3',
    roadName: 'Kidwai Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-11',
    fromNodeId: 'node-kan-6-1',
    toNodeId: 'node-kan-6-2',
    roadName: 'Gumti No 5 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-12',
    fromNodeId: 'node-kan-6-2',
    toNodeId: 'node-kan-6-3',
    roadName: 'Gumti No 5 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-13',
    fromNodeId: 'node-kan-7-1',
    toNodeId: 'node-kan-7-2',
    roadName: 'Mall Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-14',
    fromNodeId: 'node-kan-7-2',
    toNodeId: 'node-kan-7-3',
    roadName: 'Mall Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-15',
    fromNodeId: 'node-kan-8-1',
    toNodeId: 'node-kan-8-2',
    roadName: 'Panki Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-16',
    fromNodeId: 'node-kan-8-2',
    toNodeId: 'node-kan-8-3',
    roadName: 'Panki Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-17',
    fromNodeId: 'node-kan-9-1',
    toNodeId: 'node-kan-9-2',
    roadName: 'Kalyanpur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-18',
    fromNodeId: 'node-kan-9-2',
    toNodeId: 'node-kan-9-3',
    roadName: 'Kalyanpur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-19',
    fromNodeId: 'node-kan-10-1',
    toNodeId: 'node-kan-10-2',
    roadName: 'Shyam Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kan-20',
    fromNodeId: 'node-kan-10-2',
    toNodeId: 'node-kan-10-3',
    roadName: 'Shyam Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
