/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Kochi Ernakulam Coastal Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const KOCHI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 9.9312,
  longitude: 76.2673,
};

export const KOCHI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-koc-1-1',
    name: 'Panampilly Nagar Sector 1 High Street',
    zone: 'Panampilly Nagar',
    location: { latitude: 9.869200, longitude: 76.215300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Panampilly Nagar.',
  },
  {
    id: 'node-koc-1-2',
    name: 'Panampilly Nagar Sector 2 High Street',
    zone: 'Panampilly Nagar',
    location: { latitude: 9.872200, longitude: 76.218300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Panampilly Nagar.',
  },
  {
    id: 'node-koc-1-3',
    name: 'Panampilly Nagar Sector 3 High Street',
    zone: 'Panampilly Nagar',
    location: { latitude: 9.875200, longitude: 76.221300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Panampilly Nagar.',
  },
  {
    id: 'node-koc-2-1',
    name: 'Kakkanad InfoPark Sector 1 High Street',
    zone: 'Kakkanad InfoPark',
    location: { latitude: 9.881200, longitude: 76.225300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kakkanad InfoPark.',
  },
  {
    id: 'node-koc-2-2',
    name: 'Kakkanad InfoPark Sector 2 High Street',
    zone: 'Kakkanad InfoPark',
    location: { latitude: 9.884200, longitude: 76.228300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kakkanad InfoPark.',
  },
  {
    id: 'node-koc-2-3',
    name: 'Kakkanad InfoPark Sector 3 High Street',
    zone: 'Kakkanad InfoPark',
    location: { latitude: 9.887200, longitude: 76.231300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kakkanad InfoPark.',
  },
  {
    id: 'node-koc-3-1',
    name: 'Kaloor Sector 1 High Street',
    zone: 'Kaloor',
    location: { latitude: 9.893200, longitude: 76.235300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kaloor.',
  },
  {
    id: 'node-koc-3-2',
    name: 'Kaloor Sector 2 High Street',
    zone: 'Kaloor',
    location: { latitude: 9.896200, longitude: 76.238300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kaloor.',
  },
  {
    id: 'node-koc-3-3',
    name: 'Kaloor Sector 3 High Street',
    zone: 'Kaloor',
    location: { latitude: 9.899200, longitude: 76.241300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kaloor.',
  },
  {
    id: 'node-koc-4-1',
    name: 'Marine Drive Sector 1 High Street',
    zone: 'Marine Drive',
    location: { latitude: 9.905200, longitude: 76.245300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Marine Drive.',
  },
  {
    id: 'node-koc-4-2',
    name: 'Marine Drive Sector 2 High Street',
    zone: 'Marine Drive',
    location: { latitude: 9.908200, longitude: 76.248300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Marine Drive.',
  },
  {
    id: 'node-koc-4-3',
    name: 'Marine Drive Sector 3 High Street',
    zone: 'Marine Drive',
    location: { latitude: 9.911200, longitude: 76.251300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Marine Drive.',
  },
  {
    id: 'node-koc-5-1',
    name: 'Edappally Sector 1 High Street',
    zone: 'Edappally',
    location: { latitude: 9.917200, longitude: 76.255300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Edappally.',
  },
  {
    id: 'node-koc-5-2',
    name: 'Edappally Sector 2 High Street',
    zone: 'Edappally',
    location: { latitude: 9.920200, longitude: 76.258300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Edappally.',
  },
  {
    id: 'node-koc-5-3',
    name: 'Edappally Sector 3 High Street',
    zone: 'Edappally',
    location: { latitude: 9.923200, longitude: 76.261300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Edappally.',
  },
  {
    id: 'node-koc-6-1',
    name: 'MG Road Ernakulam Sector 1 High Street',
    zone: 'MG Road Ernakulam',
    location: { latitude: 9.929200, longitude: 76.265300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in MG Road Ernakulam.',
  },
  {
    id: 'node-koc-6-2',
    name: 'MG Road Ernakulam Sector 2 High Street',
    zone: 'MG Road Ernakulam',
    location: { latitude: 9.932200, longitude: 76.268300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in MG Road Ernakulam.',
  },
  {
    id: 'node-koc-6-3',
    name: 'MG Road Ernakulam Sector 3 High Street',
    zone: 'MG Road Ernakulam',
    location: { latitude: 9.935200, longitude: 76.271300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in MG Road Ernakulam.',
  },
  {
    id: 'node-koc-7-1',
    name: 'Fort Kochi Sector 1 High Street',
    zone: 'Fort Kochi',
    location: { latitude: 9.941200, longitude: 76.275300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fort Kochi.',
  },
  {
    id: 'node-koc-7-2',
    name: 'Fort Kochi Sector 2 High Street',
    zone: 'Fort Kochi',
    location: { latitude: 9.944200, longitude: 76.278300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fort Kochi.',
  },
  {
    id: 'node-koc-7-3',
    name: 'Fort Kochi Sector 3 High Street',
    zone: 'Fort Kochi',
    location: { latitude: 9.947200, longitude: 76.281300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fort Kochi.',
  },
  {
    id: 'node-koc-8-1',
    name: 'Vyttila Sector 1 High Street',
    zone: 'Vyttila',
    location: { latitude: 9.953200, longitude: 76.285300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vyttila.',
  },
  {
    id: 'node-koc-8-2',
    name: 'Vyttila Sector 2 High Street',
    zone: 'Vyttila',
    location: { latitude: 9.956200, longitude: 76.288300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vyttila.',
  },
  {
    id: 'node-koc-8-3',
    name: 'Vyttila Sector 3 High Street',
    zone: 'Vyttila',
    location: { latitude: 9.959200, longitude: 76.291300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vyttila.',
  },
  {
    id: 'node-koc-9-1',
    name: 'Palarivattom Sector 1 High Street',
    zone: 'Palarivattom',
    location: { latitude: 9.965200, longitude: 76.295300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Palarivattom.',
  },
  {
    id: 'node-koc-9-2',
    name: 'Palarivattom Sector 2 High Street',
    zone: 'Palarivattom',
    location: { latitude: 9.968200, longitude: 76.298300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Palarivattom.',
  },
  {
    id: 'node-koc-9-3',
    name: 'Palarivattom Sector 3 High Street',
    zone: 'Palarivattom',
    location: { latitude: 9.971200, longitude: 76.301300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Palarivattom.',
  },
  {
    id: 'node-koc-10-1',
    name: 'Thrikkakara Sector 1 High Street',
    zone: 'Thrikkakara',
    location: { latitude: 9.977200, longitude: 76.305300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Thrikkakara.',
  },
  {
    id: 'node-koc-10-2',
    name: 'Thrikkakara Sector 2 High Street',
    zone: 'Thrikkakara',
    location: { latitude: 9.980200, longitude: 76.308300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Thrikkakara.',
  },
  {
    id: 'node-koc-10-3',
    name: 'Thrikkakara Sector 3 High Street',
    zone: 'Thrikkakara',
    location: { latitude: 9.983200, longitude: 76.311300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Thrikkakara.',
  },
];

export const KOCHI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-koc-1',
    fromNodeId: 'node-koc-1-1',
    toNodeId: 'node-koc-1-2',
    roadName: 'Panampilly Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-2',
    fromNodeId: 'node-koc-1-2',
    toNodeId: 'node-koc-1-3',
    roadName: 'Panampilly Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-3',
    fromNodeId: 'node-koc-2-1',
    toNodeId: 'node-koc-2-2',
    roadName: 'Kakkanad InfoPark Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-4',
    fromNodeId: 'node-koc-2-2',
    toNodeId: 'node-koc-2-3',
    roadName: 'Kakkanad InfoPark Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-5',
    fromNodeId: 'node-koc-3-1',
    toNodeId: 'node-koc-3-2',
    roadName: 'Kaloor Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-6',
    fromNodeId: 'node-koc-3-2',
    toNodeId: 'node-koc-3-3',
    roadName: 'Kaloor Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-7',
    fromNodeId: 'node-koc-4-1',
    toNodeId: 'node-koc-4-2',
    roadName: 'Marine Drive Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-8',
    fromNodeId: 'node-koc-4-2',
    toNodeId: 'node-koc-4-3',
    roadName: 'Marine Drive Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-9',
    fromNodeId: 'node-koc-5-1',
    toNodeId: 'node-koc-5-2',
    roadName: 'Edappally Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-10',
    fromNodeId: 'node-koc-5-2',
    toNodeId: 'node-koc-5-3',
    roadName: 'Edappally Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-11',
    fromNodeId: 'node-koc-6-1',
    toNodeId: 'node-koc-6-2',
    roadName: 'MG Road Ernakulam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-12',
    fromNodeId: 'node-koc-6-2',
    toNodeId: 'node-koc-6-3',
    roadName: 'MG Road Ernakulam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-13',
    fromNodeId: 'node-koc-7-1',
    toNodeId: 'node-koc-7-2',
    roadName: 'Fort Kochi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-14',
    fromNodeId: 'node-koc-7-2',
    toNodeId: 'node-koc-7-3',
    roadName: 'Fort Kochi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-15',
    fromNodeId: 'node-koc-8-1',
    toNodeId: 'node-koc-8-2',
    roadName: 'Vyttila Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-16',
    fromNodeId: 'node-koc-8-2',
    toNodeId: 'node-koc-8-3',
    roadName: 'Vyttila Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-17',
    fromNodeId: 'node-koc-9-1',
    toNodeId: 'node-koc-9-2',
    roadName: 'Palarivattom Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-18',
    fromNodeId: 'node-koc-9-2',
    toNodeId: 'node-koc-9-3',
    roadName: 'Palarivattom Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-19',
    fromNodeId: 'node-koc-10-1',
    toNodeId: 'node-koc-10-2',
    roadName: 'Thrikkakara Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-koc-20',
    fromNodeId: 'node-koc-10-2',
    toNodeId: 'node-koc-10-3',
    roadName: 'Thrikkakara Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
