/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Kolkata Metropolitan Area
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const KOLKATA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 22.5726,
  longitude: 88.3639,
};

export const KOLKATA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-kol-1-1',
    name: 'Park Street Sector 1 Road',
    zone: 'Park Street',
    location: { latitude: 22.500600, longitude: 88.311900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Park Street commercial centers and residential communities.',
  },
  {
    id: 'node-kol-1-2',
    name: 'Park Street Sector 2 Road',
    zone: 'Park Street',
    location: { latitude: 22.503600, longitude: 88.314900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Park Street commercial centers and residential communities.',
  },
  {
    id: 'node-kol-1-3',
    name: 'Park Street Sector 3 Road',
    zone: 'Park Street',
    location: { latitude: 22.506600, longitude: 88.317900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Park Street commercial centers and residential communities.',
  },
  {
    id: 'node-kol-2-1',
    name: 'Salt Lake Sector 5 Sector 1 Road',
    zone: 'Salt Lake Sector 5',
    location: { latitude: 22.515600, longitude: 88.323900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Salt Lake Sector 5 commercial centers and residential communities.',
  },
  {
    id: 'node-kol-2-2',
    name: 'Salt Lake Sector 5 Sector 2 Road',
    zone: 'Salt Lake Sector 5',
    location: { latitude: 22.518600, longitude: 88.326900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Salt Lake Sector 5 commercial centers and residential communities.',
  },
  {
    id: 'node-kol-2-3',
    name: 'Salt Lake Sector 5 Sector 3 Road',
    zone: 'Salt Lake Sector 5',
    location: { latitude: 22.521600, longitude: 88.329900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Salt Lake Sector 5 commercial centers and residential communities.',
  },
  {
    id: 'node-kol-3-1',
    name: 'New Town Sector 1 Road',
    zone: 'New Town',
    location: { latitude: 22.530600, longitude: 88.335900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting New Town commercial centers and residential communities.',
  },
  {
    id: 'node-kol-3-2',
    name: 'New Town Sector 2 Road',
    zone: 'New Town',
    location: { latitude: 22.533600, longitude: 88.338900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting New Town commercial centers and residential communities.',
  },
  {
    id: 'node-kol-3-3',
    name: 'New Town Sector 3 Road',
    zone: 'New Town',
    location: { latitude: 22.536600, longitude: 88.341900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting New Town commercial centers and residential communities.',
  },
  {
    id: 'node-kol-4-1',
    name: 'Ballygunge Sector 1 Road',
    zone: 'Ballygunge',
    location: { latitude: 22.545600, longitude: 88.347900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Ballygunge commercial centers and residential communities.',
  },
  {
    id: 'node-kol-4-2',
    name: 'Ballygunge Sector 2 Road',
    zone: 'Ballygunge',
    location: { latitude: 22.548600, longitude: 88.350900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Ballygunge commercial centers and residential communities.',
  },
  {
    id: 'node-kol-4-3',
    name: 'Ballygunge Sector 3 Road',
    zone: 'Ballygunge',
    location: { latitude: 22.551600, longitude: 88.353900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Ballygunge commercial centers and residential communities.',
  },
  {
    id: 'node-kol-5-1',
    name: 'Alipore Sector 1 Road',
    zone: 'Alipore',
    location: { latitude: 22.560600, longitude: 88.359900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Alipore commercial centers and residential communities.',
  },
  {
    id: 'node-kol-5-2',
    name: 'Alipore Sector 2 Road',
    zone: 'Alipore',
    location: { latitude: 22.563600, longitude: 88.362900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Alipore commercial centers and residential communities.',
  },
  {
    id: 'node-kol-5-3',
    name: 'Alipore Sector 3 Road',
    zone: 'Alipore',
    location: { latitude: 22.566600, longitude: 88.365900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Alipore commercial centers and residential communities.',
  },
  {
    id: 'node-kol-6-1',
    name: 'Southern Avenue Sector 1 Road',
    zone: 'Southern Avenue',
    location: { latitude: 22.575600, longitude: 88.371900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Southern Avenue commercial centers and residential communities.',
  },
  {
    id: 'node-kol-6-2',
    name: 'Southern Avenue Sector 2 Road',
    zone: 'Southern Avenue',
    location: { latitude: 22.578600, longitude: 88.374900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Southern Avenue commercial centers and residential communities.',
  },
  {
    id: 'node-kol-6-3',
    name: 'Southern Avenue Sector 3 Road',
    zone: 'Southern Avenue',
    location: { latitude: 22.581600, longitude: 88.377900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Southern Avenue commercial centers and residential communities.',
  },
  {
    id: 'node-kol-7-1',
    name: 'Gariahat Sector 1 Road',
    zone: 'Gariahat',
    location: { latitude: 22.590600, longitude: 88.383900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Gariahat commercial centers and residential communities.',
  },
  {
    id: 'node-kol-7-2',
    name: 'Gariahat Sector 2 Road',
    zone: 'Gariahat',
    location: { latitude: 22.593600, longitude: 88.386900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Gariahat commercial centers and residential communities.',
  },
  {
    id: 'node-kol-7-3',
    name: 'Gariahat Sector 3 Road',
    zone: 'Gariahat',
    location: { latitude: 22.596600, longitude: 88.389900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Gariahat commercial centers and residential communities.',
  },
  {
    id: 'node-kol-8-1',
    name: 'Behala Sector 1 Road',
    zone: 'Behala',
    location: { latitude: 22.605600, longitude: 88.395900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Behala commercial centers and residential communities.',
  },
  {
    id: 'node-kol-8-2',
    name: 'Behala Sector 2 Road',
    zone: 'Behala',
    location: { latitude: 22.608600, longitude: 88.398900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Behala commercial centers and residential communities.',
  },
  {
    id: 'node-kol-8-3',
    name: 'Behala Sector 3 Road',
    zone: 'Behala',
    location: { latitude: 22.611600, longitude: 88.401900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Behala commercial centers and residential communities.',
  },
  {
    id: 'node-kol-9-1',
    name: 'Howrah Station Hub Sector 1 Road',
    zone: 'Howrah Station Hub',
    location: { latitude: 22.620600, longitude: 88.407900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Howrah Station Hub commercial centers and residential communities.',
  },
  {
    id: 'node-kol-9-2',
    name: 'Howrah Station Hub Sector 2 Road',
    zone: 'Howrah Station Hub',
    location: { latitude: 22.623600, longitude: 88.410900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Howrah Station Hub commercial centers and residential communities.',
  },
  {
    id: 'node-kol-9-3',
    name: 'Howrah Station Hub Sector 3 Road',
    zone: 'Howrah Station Hub',
    location: { latitude: 22.626600, longitude: 88.413900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Howrah Station Hub commercial centers and residential communities.',
  },
  {
    id: 'node-kol-10-1',
    name: 'Dum Dum Sector 1 Road',
    zone: 'Dum Dum',
    location: { latitude: 22.635600, longitude: 88.419900 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Dum Dum commercial centers and residential communities.',
  },
  {
    id: 'node-kol-10-2',
    name: 'Dum Dum Sector 2 Road',
    zone: 'Dum Dum',
    location: { latitude: 22.638600, longitude: 88.422900 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Dum Dum commercial centers and residential communities.',
  },
  {
    id: 'node-kol-10-3',
    name: 'Dum Dum Sector 3 Road',
    zone: 'Dum Dum',
    location: { latitude: 22.641600, longitude: 88.425900 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Dum Dum commercial centers and residential communities.',
  },
];

export const KOLKATA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-kol-1',
    fromNodeId: 'node-kol-1-1',
    toNodeId: 'node-kol-1-2',
    roadName: 'Park Street Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-2',
    fromNodeId: 'node-kol-1-2',
    toNodeId: 'node-kol-1-3',
    roadName: 'Park Street Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-3',
    fromNodeId: 'node-kol-2-1',
    toNodeId: 'node-kol-2-2',
    roadName: 'Salt Lake Sector 5 Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-4',
    fromNodeId: 'node-kol-2-2',
    toNodeId: 'node-kol-2-3',
    roadName: 'Salt Lake Sector 5 Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-5',
    fromNodeId: 'node-kol-3-1',
    toNodeId: 'node-kol-3-2',
    roadName: 'New Town Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-6',
    fromNodeId: 'node-kol-3-2',
    toNodeId: 'node-kol-3-3',
    roadName: 'New Town Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-7',
    fromNodeId: 'node-kol-4-1',
    toNodeId: 'node-kol-4-2',
    roadName: 'Ballygunge Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-8',
    fromNodeId: 'node-kol-4-2',
    toNodeId: 'node-kol-4-3',
    roadName: 'Ballygunge Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-9',
    fromNodeId: 'node-kol-5-1',
    toNodeId: 'node-kol-5-2',
    roadName: 'Alipore Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-10',
    fromNodeId: 'node-kol-5-2',
    toNodeId: 'node-kol-5-3',
    roadName: 'Alipore Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-11',
    fromNodeId: 'node-kol-6-1',
    toNodeId: 'node-kol-6-2',
    roadName: 'Southern Avenue Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-12',
    fromNodeId: 'node-kol-6-2',
    toNodeId: 'node-kol-6-3',
    roadName: 'Southern Avenue Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-13',
    fromNodeId: 'node-kol-7-1',
    toNodeId: 'node-kol-7-2',
    roadName: 'Gariahat Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-14',
    fromNodeId: 'node-kol-7-2',
    toNodeId: 'node-kol-7-3',
    roadName: 'Gariahat Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-15',
    fromNodeId: 'node-kol-8-1',
    toNodeId: 'node-kol-8-2',
    roadName: 'Behala Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-16',
    fromNodeId: 'node-kol-8-2',
    toNodeId: 'node-kol-8-3',
    roadName: 'Behala Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-17',
    fromNodeId: 'node-kol-9-1',
    toNodeId: 'node-kol-9-2',
    roadName: 'Howrah Station Hub Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-18',
    fromNodeId: 'node-kol-9-2',
    toNodeId: 'node-kol-9-3',
    roadName: 'Howrah Station Hub Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-19',
    fromNodeId: 'node-kol-10-1',
    toNodeId: 'node-kol-10-2',
    roadName: 'Dum Dum Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kol-20',
    fromNodeId: 'node-kol-10-2',
    toNodeId: 'node-kol-10-3',
    roadName: 'Dum Dum Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
