/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Krakow Royal Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const KRAKOW_BASE_COORDINATE: GeoCoordinate = {
  latitude: 50.0647,
  longitude: 19.945,
};

export const KRAKOW_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-kra-1-1',
    name: 'Stare Miasto Krakow Sector 1 High Street',
    zone: 'Stare Miasto Krakow',
    location: { latitude: 50.002700, longitude: 19.893000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Stare Miasto Krakow.',
  },
  {
    id: 'node-kra-1-2',
    name: 'Stare Miasto Krakow Sector 2 High Street',
    zone: 'Stare Miasto Krakow',
    location: { latitude: 50.005700, longitude: 19.896000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Stare Miasto Krakow.',
  },
  {
    id: 'node-kra-1-3',
    name: 'Stare Miasto Krakow Sector 3 High Street',
    zone: 'Stare Miasto Krakow',
    location: { latitude: 50.008700, longitude: 19.899000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Stare Miasto Krakow.',
  },
  {
    id: 'node-kra-2-1',
    name: 'Kazimierz Sector 1 High Street',
    zone: 'Kazimierz',
    location: { latitude: 50.014700, longitude: 19.903000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kazimierz.',
  },
  {
    id: 'node-kra-2-2',
    name: 'Kazimierz Sector 2 High Street',
    zone: 'Kazimierz',
    location: { latitude: 50.017700, longitude: 19.906000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kazimierz.',
  },
  {
    id: 'node-kra-2-3',
    name: 'Kazimierz Sector 3 High Street',
    zone: 'Kazimierz',
    location: { latitude: 50.020700, longitude: 19.909000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kazimierz.',
  },
  {
    id: 'node-kra-3-1',
    name: 'Podgórze Sector 1 High Street',
    zone: 'Podgórze',
    location: { latitude: 50.026700, longitude: 19.913000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Podgórze.',
  },
  {
    id: 'node-kra-3-2',
    name: 'Podgórze Sector 2 High Street',
    zone: 'Podgórze',
    location: { latitude: 50.029700, longitude: 19.916000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Podgórze.',
  },
  {
    id: 'node-kra-3-3',
    name: 'Podgórze Sector 3 High Street',
    zone: 'Podgórze',
    location: { latitude: 50.032700, longitude: 19.919000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Podgórze.',
  },
  {
    id: 'node-kra-4-1',
    name: 'Kleparz Sector 1 High Street',
    zone: 'Kleparz',
    location: { latitude: 50.038700, longitude: 19.923000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kleparz.',
  },
  {
    id: 'node-kra-4-2',
    name: 'Kleparz Sector 2 High Street',
    zone: 'Kleparz',
    location: { latitude: 50.041700, longitude: 19.926000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kleparz.',
  },
  {
    id: 'node-kra-4-3',
    name: 'Kleparz Sector 3 High Street',
    zone: 'Kleparz',
    location: { latitude: 50.044700, longitude: 19.929000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kleparz.',
  },
  {
    id: 'node-kra-5-1',
    name: 'Nowy Świat Sector 1 High Street',
    zone: 'Nowy Świat',
    location: { latitude: 50.050700, longitude: 19.933000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nowy Świat.',
  },
  {
    id: 'node-kra-5-2',
    name: 'Nowy Świat Sector 2 High Street',
    zone: 'Nowy Świat',
    location: { latitude: 50.053700, longitude: 19.936000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nowy Świat.',
  },
  {
    id: 'node-kra-5-3',
    name: 'Nowy Świat Sector 3 High Street',
    zone: 'Nowy Świat',
    location: { latitude: 50.056700, longitude: 19.939000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nowy Świat.',
  },
  {
    id: 'node-kra-6-1',
    name: 'Grzegórzki Sector 1 High Street',
    zone: 'Grzegórzki',
    location: { latitude: 50.062700, longitude: 19.943000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Grzegórzki.',
  },
  {
    id: 'node-kra-6-2',
    name: 'Grzegórzki Sector 2 High Street',
    zone: 'Grzegórzki',
    location: { latitude: 50.065700, longitude: 19.946000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Grzegórzki.',
  },
  {
    id: 'node-kra-6-3',
    name: 'Grzegórzki Sector 3 High Street',
    zone: 'Grzegórzki',
    location: { latitude: 50.068700, longitude: 19.949000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Grzegórzki.',
  },
  {
    id: 'node-kra-7-1',
    name: 'Dębniki Sector 1 High Street',
    zone: 'Dębniki',
    location: { latitude: 50.074700, longitude: 19.953000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dębniki.',
  },
  {
    id: 'node-kra-7-2',
    name: 'Dębniki Sector 2 High Street',
    zone: 'Dębniki',
    location: { latitude: 50.077700, longitude: 19.956000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dębniki.',
  },
  {
    id: 'node-kra-7-3',
    name: 'Dębniki Sector 3 High Street',
    zone: 'Dębniki',
    location: { latitude: 50.080700, longitude: 19.959000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dębniki.',
  },
  {
    id: 'node-kra-8-1',
    name: 'Zwierzyniec Sector 1 High Street',
    zone: 'Zwierzyniec',
    location: { latitude: 50.086700, longitude: 19.963000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zwierzyniec.',
  },
  {
    id: 'node-kra-8-2',
    name: 'Zwierzyniec Sector 2 High Street',
    zone: 'Zwierzyniec',
    location: { latitude: 50.089700, longitude: 19.966000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zwierzyniec.',
  },
  {
    id: 'node-kra-8-3',
    name: 'Zwierzyniec Sector 3 High Street',
    zone: 'Zwierzyniec',
    location: { latitude: 50.092700, longitude: 19.969000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zwierzyniec.',
  },
  {
    id: 'node-kra-9-1',
    name: 'Krowodrza Sector 1 High Street',
    zone: 'Krowodrza',
    location: { latitude: 50.098700, longitude: 19.973000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Krowodrza.',
  },
  {
    id: 'node-kra-9-2',
    name: 'Krowodrza Sector 2 High Street',
    zone: 'Krowodrza',
    location: { latitude: 50.101700, longitude: 19.976000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Krowodrza.',
  },
  {
    id: 'node-kra-9-3',
    name: 'Krowodrza Sector 3 High Street',
    zone: 'Krowodrza',
    location: { latitude: 50.104700, longitude: 19.979000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Krowodrza.',
  },
  {
    id: 'node-kra-10-1',
    name: 'Bronowice Sector 1 High Street',
    zone: 'Bronowice',
    location: { latitude: 50.110700, longitude: 19.983000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bronowice.',
  },
  {
    id: 'node-kra-10-2',
    name: 'Bronowice Sector 2 High Street',
    zone: 'Bronowice',
    location: { latitude: 50.113700, longitude: 19.986000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bronowice.',
  },
  {
    id: 'node-kra-10-3',
    name: 'Bronowice Sector 3 High Street',
    zone: 'Bronowice',
    location: { latitude: 50.116700, longitude: 19.989000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bronowice.',
  },
];

export const KRAKOW_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-kra-1',
    fromNodeId: 'node-kra-1-1',
    toNodeId: 'node-kra-1-2',
    roadName: 'Stare Miasto Krakow Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-2',
    fromNodeId: 'node-kra-1-2',
    toNodeId: 'node-kra-1-3',
    roadName: 'Stare Miasto Krakow Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-3',
    fromNodeId: 'node-kra-2-1',
    toNodeId: 'node-kra-2-2',
    roadName: 'Kazimierz Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-4',
    fromNodeId: 'node-kra-2-2',
    toNodeId: 'node-kra-2-3',
    roadName: 'Kazimierz Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-5',
    fromNodeId: 'node-kra-3-1',
    toNodeId: 'node-kra-3-2',
    roadName: 'Podgórze Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-6',
    fromNodeId: 'node-kra-3-2',
    toNodeId: 'node-kra-3-3',
    roadName: 'Podgórze Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-7',
    fromNodeId: 'node-kra-4-1',
    toNodeId: 'node-kra-4-2',
    roadName: 'Kleparz Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-8',
    fromNodeId: 'node-kra-4-2',
    toNodeId: 'node-kra-4-3',
    roadName: 'Kleparz Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-9',
    fromNodeId: 'node-kra-5-1',
    toNodeId: 'node-kra-5-2',
    roadName: 'Nowy Świat Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-10',
    fromNodeId: 'node-kra-5-2',
    toNodeId: 'node-kra-5-3',
    roadName: 'Nowy Świat Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-11',
    fromNodeId: 'node-kra-6-1',
    toNodeId: 'node-kra-6-2',
    roadName: 'Grzegórzki Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-12',
    fromNodeId: 'node-kra-6-2',
    toNodeId: 'node-kra-6-3',
    roadName: 'Grzegórzki Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-13',
    fromNodeId: 'node-kra-7-1',
    toNodeId: 'node-kra-7-2',
    roadName: 'Dębniki Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-14',
    fromNodeId: 'node-kra-7-2',
    toNodeId: 'node-kra-7-3',
    roadName: 'Dębniki Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-15',
    fromNodeId: 'node-kra-8-1',
    toNodeId: 'node-kra-8-2',
    roadName: 'Zwierzyniec Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-16',
    fromNodeId: 'node-kra-8-2',
    toNodeId: 'node-kra-8-3',
    roadName: 'Zwierzyniec Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-17',
    fromNodeId: 'node-kra-9-1',
    toNodeId: 'node-kra-9-2',
    roadName: 'Krowodrza Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-18',
    fromNodeId: 'node-kra-9-2',
    toNodeId: 'node-kra-9-3',
    roadName: 'Krowodrza Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-19',
    fromNodeId: 'node-kra-10-1',
    toNodeId: 'node-kra-10-2',
    roadName: 'Bronowice Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kra-20',
    fromNodeId: 'node-kra-10-2',
    toNodeId: 'node-kra-10-3',
    roadName: 'Bronowice Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
