/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Kuala Lumpur Klang Valley
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const KUALALUMPUR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 3.139,
  longitude: 101.6869,
};

export const KUALALUMPUR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-kua-1-1',
    name: 'Bukit Bintang Sector 1 High Street',
    zone: 'Bukit Bintang',
    location: { latitude: 3.077000, longitude: 101.634900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bukit Bintang.',
  },
  {
    id: 'node-kua-1-2',
    name: 'Bukit Bintang Sector 2 High Street',
    zone: 'Bukit Bintang',
    location: { latitude: 3.080000, longitude: 101.637900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bukit Bintang.',
  },
  {
    id: 'node-kua-1-3',
    name: 'Bukit Bintang Sector 3 High Street',
    zone: 'Bukit Bintang',
    location: { latitude: 3.083000, longitude: 101.640900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bukit Bintang.',
  },
  {
    id: 'node-kua-2-1',
    name: 'KLCC Sector 1 High Street',
    zone: 'KLCC',
    location: { latitude: 3.089000, longitude: 101.644900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in KLCC.',
  },
  {
    id: 'node-kua-2-2',
    name: 'KLCC Sector 2 High Street',
    zone: 'KLCC',
    location: { latitude: 3.092000, longitude: 101.647900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in KLCC.',
  },
  {
    id: 'node-kua-2-3',
    name: 'KLCC Sector 3 High Street',
    zone: 'KLCC',
    location: { latitude: 3.095000, longitude: 101.650900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in KLCC.',
  },
  {
    id: 'node-kua-3-1',
    name: 'Bangsar Sector 1 High Street',
    zone: 'Bangsar',
    location: { latitude: 3.101000, longitude: 101.654900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bangsar.',
  },
  {
    id: 'node-kua-3-2',
    name: 'Bangsar Sector 2 High Street',
    zone: 'Bangsar',
    location: { latitude: 3.104000, longitude: 101.657900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bangsar.',
  },
  {
    id: 'node-kua-3-3',
    name: 'Bangsar Sector 3 High Street',
    zone: 'Bangsar',
    location: { latitude: 3.107000, longitude: 101.660900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bangsar.',
  },
  {
    id: 'node-kua-4-1',
    name: 'Mont Kiara Sector 1 High Street',
    zone: 'Mont Kiara',
    location: { latitude: 3.113000, longitude: 101.664900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mont Kiara.',
  },
  {
    id: 'node-kua-4-2',
    name: 'Mont Kiara Sector 2 High Street',
    zone: 'Mont Kiara',
    location: { latitude: 3.116000, longitude: 101.667900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mont Kiara.',
  },
  {
    id: 'node-kua-4-3',
    name: 'Mont Kiara Sector 3 High Street',
    zone: 'Mont Kiara',
    location: { latitude: 3.119000, longitude: 101.670900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mont Kiara.',
  },
  {
    id: 'node-kua-5-1',
    name: 'Damansara Sector 1 High Street',
    zone: 'Damansara',
    location: { latitude: 3.125000, longitude: 101.674900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Damansara.',
  },
  {
    id: 'node-kua-5-2',
    name: 'Damansara Sector 2 High Street',
    zone: 'Damansara',
    location: { latitude: 3.128000, longitude: 101.677900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Damansara.',
  },
  {
    id: 'node-kua-5-3',
    name: 'Damansara Sector 3 High Street',
    zone: 'Damansara',
    location: { latitude: 3.131000, longitude: 101.680900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Damansara.',
  },
  {
    id: 'node-kua-6-1',
    name: 'Cheras Sector 1 High Street',
    zone: 'Cheras',
    location: { latitude: 3.137000, longitude: 101.684900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cheras.',
  },
  {
    id: 'node-kua-6-2',
    name: 'Cheras Sector 2 High Street',
    zone: 'Cheras',
    location: { latitude: 3.140000, longitude: 101.687900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cheras.',
  },
  {
    id: 'node-kua-6-3',
    name: 'Cheras Sector 3 High Street',
    zone: 'Cheras',
    location: { latitude: 3.143000, longitude: 101.690900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cheras.',
  },
  {
    id: 'node-kua-7-1',
    name: 'Petaling Jaya Sector 1 High Street',
    zone: 'Petaling Jaya',
    location: { latitude: 3.149000, longitude: 101.694900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Petaling Jaya.',
  },
  {
    id: 'node-kua-7-2',
    name: 'Petaling Jaya Sector 2 High Street',
    zone: 'Petaling Jaya',
    location: { latitude: 3.152000, longitude: 101.697900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Petaling Jaya.',
  },
  {
    id: 'node-kua-7-3',
    name: 'Petaling Jaya Sector 3 High Street',
    zone: 'Petaling Jaya',
    location: { latitude: 3.155000, longitude: 101.700900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Petaling Jaya.',
  },
  {
    id: 'node-kua-8-1',
    name: 'Subang Jaya Sector 1 High Street',
    zone: 'Subang Jaya',
    location: { latitude: 3.161000, longitude: 101.704900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Subang Jaya.',
  },
  {
    id: 'node-kua-8-2',
    name: 'Subang Jaya Sector 2 High Street',
    zone: 'Subang Jaya',
    location: { latitude: 3.164000, longitude: 101.707900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Subang Jaya.',
  },
  {
    id: 'node-kua-8-3',
    name: 'Subang Jaya Sector 3 High Street',
    zone: 'Subang Jaya',
    location: { latitude: 3.167000, longitude: 101.710900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Subang Jaya.',
  },
  {
    id: 'node-kua-9-1',
    name: 'Shah Alam Sector 1 High Street',
    zone: 'Shah Alam',
    location: { latitude: 3.173000, longitude: 101.714900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shah Alam.',
  },
  {
    id: 'node-kua-9-2',
    name: 'Shah Alam Sector 2 High Street',
    zone: 'Shah Alam',
    location: { latitude: 3.176000, longitude: 101.717900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shah Alam.',
  },
  {
    id: 'node-kua-9-3',
    name: 'Shah Alam Sector 3 High Street',
    zone: 'Shah Alam',
    location: { latitude: 3.179000, longitude: 101.720900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shah Alam.',
  },
  {
    id: 'node-kua-10-1',
    name: 'Ampang Sector 1 High Street',
    zone: 'Ampang',
    location: { latitude: 3.185000, longitude: 101.724900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ampang.',
  },
  {
    id: 'node-kua-10-2',
    name: 'Ampang Sector 2 High Street',
    zone: 'Ampang',
    location: { latitude: 3.188000, longitude: 101.727900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ampang.',
  },
  {
    id: 'node-kua-10-3',
    name: 'Ampang Sector 3 High Street',
    zone: 'Ampang',
    location: { latitude: 3.191000, longitude: 101.730900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ampang.',
  },
];

export const KUALALUMPUR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-kua-1',
    fromNodeId: 'node-kua-1-1',
    toNodeId: 'node-kua-1-2',
    roadName: 'Bukit Bintang Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-2',
    fromNodeId: 'node-kua-1-2',
    toNodeId: 'node-kua-1-3',
    roadName: 'Bukit Bintang Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-3',
    fromNodeId: 'node-kua-2-1',
    toNodeId: 'node-kua-2-2',
    roadName: 'KLCC Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-4',
    fromNodeId: 'node-kua-2-2',
    toNodeId: 'node-kua-2-3',
    roadName: 'KLCC Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-5',
    fromNodeId: 'node-kua-3-1',
    toNodeId: 'node-kua-3-2',
    roadName: 'Bangsar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-6',
    fromNodeId: 'node-kua-3-2',
    toNodeId: 'node-kua-3-3',
    roadName: 'Bangsar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-7',
    fromNodeId: 'node-kua-4-1',
    toNodeId: 'node-kua-4-2',
    roadName: 'Mont Kiara Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-8',
    fromNodeId: 'node-kua-4-2',
    toNodeId: 'node-kua-4-3',
    roadName: 'Mont Kiara Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-9',
    fromNodeId: 'node-kua-5-1',
    toNodeId: 'node-kua-5-2',
    roadName: 'Damansara Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-10',
    fromNodeId: 'node-kua-5-2',
    toNodeId: 'node-kua-5-3',
    roadName: 'Damansara Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-11',
    fromNodeId: 'node-kua-6-1',
    toNodeId: 'node-kua-6-2',
    roadName: 'Cheras Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-12',
    fromNodeId: 'node-kua-6-2',
    toNodeId: 'node-kua-6-3',
    roadName: 'Cheras Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-13',
    fromNodeId: 'node-kua-7-1',
    toNodeId: 'node-kua-7-2',
    roadName: 'Petaling Jaya Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-14',
    fromNodeId: 'node-kua-7-2',
    toNodeId: 'node-kua-7-3',
    roadName: 'Petaling Jaya Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-15',
    fromNodeId: 'node-kua-8-1',
    toNodeId: 'node-kua-8-2',
    roadName: 'Subang Jaya Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-16',
    fromNodeId: 'node-kua-8-2',
    toNodeId: 'node-kua-8-3',
    roadName: 'Subang Jaya Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-17',
    fromNodeId: 'node-kua-9-1',
    toNodeId: 'node-kua-9-2',
    roadName: 'Shah Alam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-18',
    fromNodeId: 'node-kua-9-2',
    toNodeId: 'node-kua-9-3',
    roadName: 'Shah Alam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-19',
    fromNodeId: 'node-kua-10-1',
    toNodeId: 'node-kua-10-2',
    roadName: 'Ampang Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kua-20',
    fromNodeId: 'node-kua-10-2',
    toNodeId: 'node-kua-10-3',
    roadName: 'Ampang Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
