/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Kuwait City Arabian Gulf
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const KUWAITCITY_BASE_COORDINATE: GeoCoordinate = {
  latitude: 29.3759,
  longitude: 47.9774,
};

export const KUWAITCITY_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-kuw-1-1',
    name: 'Salmiya Sector 1 High Street',
    zone: 'Salmiya',
    location: { latitude: 29.313900, longitude: 47.925400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Salmiya.',
  },
  {
    id: 'node-kuw-1-2',
    name: 'Salmiya Sector 2 High Street',
    zone: 'Salmiya',
    location: { latitude: 29.316900, longitude: 47.928400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Salmiya.',
  },
  {
    id: 'node-kuw-1-3',
    name: 'Salmiya Sector 3 High Street',
    zone: 'Salmiya',
    location: { latitude: 29.319900, longitude: 47.931400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Salmiya.',
  },
  {
    id: 'node-kuw-2-1',
    name: 'Sharq Sector 1 High Street',
    zone: 'Sharq',
    location: { latitude: 29.325900, longitude: 47.935400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sharq.',
  },
  {
    id: 'node-kuw-2-2',
    name: 'Sharq Sector 2 High Street',
    zone: 'Sharq',
    location: { latitude: 29.328900, longitude: 47.938400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sharq.',
  },
  {
    id: 'node-kuw-2-3',
    name: 'Sharq Sector 3 High Street',
    zone: 'Sharq',
    location: { latitude: 29.331900, longitude: 47.941400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sharq.',
  },
  {
    id: 'node-kuw-3-1',
    name: 'Kuwait City Downtown Sector 1 High Street',
    zone: 'Kuwait City Downtown',
    location: { latitude: 29.337900, longitude: 47.945400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kuwait City Downtown.',
  },
  {
    id: 'node-kuw-3-2',
    name: 'Kuwait City Downtown Sector 2 High Street',
    zone: 'Kuwait City Downtown',
    location: { latitude: 29.340900, longitude: 47.948400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kuwait City Downtown.',
  },
  {
    id: 'node-kuw-3-3',
    name: 'Kuwait City Downtown Sector 3 High Street',
    zone: 'Kuwait City Downtown',
    location: { latitude: 29.343900, longitude: 47.951400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kuwait City Downtown.',
  },
  {
    id: 'node-kuw-4-1',
    name: 'Shuwaikh Sector 1 High Street',
    zone: 'Shuwaikh',
    location: { latitude: 29.349900, longitude: 47.955400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shuwaikh.',
  },
  {
    id: 'node-kuw-4-2',
    name: 'Shuwaikh Sector 2 High Street',
    zone: 'Shuwaikh',
    location: { latitude: 29.352900, longitude: 47.958400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shuwaikh.',
  },
  {
    id: 'node-kuw-4-3',
    name: 'Shuwaikh Sector 3 High Street',
    zone: 'Shuwaikh',
    location: { latitude: 29.355900, longitude: 47.961400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shuwaikh.',
  },
  {
    id: 'node-kuw-5-1',
    name: 'Jabriya Sector 1 High Street',
    zone: 'Jabriya',
    location: { latitude: 29.361900, longitude: 47.965400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jabriya.',
  },
  {
    id: 'node-kuw-5-2',
    name: 'Jabriya Sector 2 High Street',
    zone: 'Jabriya',
    location: { latitude: 29.364900, longitude: 47.968400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jabriya.',
  },
  {
    id: 'node-kuw-5-3',
    name: 'Jabriya Sector 3 High Street',
    zone: 'Jabriya',
    location: { latitude: 29.367900, longitude: 47.971400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jabriya.',
  },
  {
    id: 'node-kuw-6-1',
    name: 'Hawally Sector 1 High Street',
    zone: 'Hawally',
    location: { latitude: 29.373900, longitude: 47.975400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hawally.',
  },
  {
    id: 'node-kuw-6-2',
    name: 'Hawally Sector 2 High Street',
    zone: 'Hawally',
    location: { latitude: 29.376900, longitude: 47.978400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hawally.',
  },
  {
    id: 'node-kuw-6-3',
    name: 'Hawally Sector 3 High Street',
    zone: 'Hawally',
    location: { latitude: 29.379900, longitude: 47.981400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hawally.',
  },
  {
    id: 'node-kuw-7-1',
    name: 'Bneid Al-Gar Sector 1 High Street',
    zone: 'Bneid Al-Gar',
    location: { latitude: 29.385900, longitude: 47.985400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bneid Al-Gar.',
  },
  {
    id: 'node-kuw-7-2',
    name: 'Bneid Al-Gar Sector 2 High Street',
    zone: 'Bneid Al-Gar',
    location: { latitude: 29.388900, longitude: 47.988400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bneid Al-Gar.',
  },
  {
    id: 'node-kuw-7-3',
    name: 'Bneid Al-Gar Sector 3 High Street',
    zone: 'Bneid Al-Gar',
    location: { latitude: 29.391900, longitude: 47.991400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bneid Al-Gar.',
  },
  {
    id: 'node-kuw-8-1',
    name: 'Al Bidaa Sector 1 High Street',
    zone: 'Al Bidaa',
    location: { latitude: 29.397900, longitude: 47.995400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Bidaa.',
  },
  {
    id: 'node-kuw-8-2',
    name: 'Al Bidaa Sector 2 High Street',
    zone: 'Al Bidaa',
    location: { latitude: 29.400900, longitude: 47.998400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Bidaa.',
  },
  {
    id: 'node-kuw-8-3',
    name: 'Al Bidaa Sector 3 High Street',
    zone: 'Al Bidaa',
    location: { latitude: 29.403900, longitude: 48.001400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Bidaa.',
  },
  {
    id: 'node-kuw-9-1',
    name: 'Dasman Sector 1 High Street',
    zone: 'Dasman',
    location: { latitude: 29.409900, longitude: 48.005400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dasman.',
  },
  {
    id: 'node-kuw-9-2',
    name: 'Dasman Sector 2 High Street',
    zone: 'Dasman',
    location: { latitude: 29.412900, longitude: 48.008400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dasman.',
  },
  {
    id: 'node-kuw-9-3',
    name: 'Dasman Sector 3 High Street',
    zone: 'Dasman',
    location: { latitude: 29.415900, longitude: 48.011400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dasman.',
  },
  {
    id: 'node-kuw-10-1',
    name: 'Salwa Sector 1 High Street',
    zone: 'Salwa',
    location: { latitude: 29.421900, longitude: 48.015400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Salwa.',
  },
  {
    id: 'node-kuw-10-2',
    name: 'Salwa Sector 2 High Street',
    zone: 'Salwa',
    location: { latitude: 29.424900, longitude: 48.018400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Salwa.',
  },
  {
    id: 'node-kuw-10-3',
    name: 'Salwa Sector 3 High Street',
    zone: 'Salwa',
    location: { latitude: 29.427900, longitude: 48.021400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Salwa.',
  },
];

export const KUWAITCITY_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-kuw-1',
    fromNodeId: 'node-kuw-1-1',
    toNodeId: 'node-kuw-1-2',
    roadName: 'Salmiya Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-2',
    fromNodeId: 'node-kuw-1-2',
    toNodeId: 'node-kuw-1-3',
    roadName: 'Salmiya Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-3',
    fromNodeId: 'node-kuw-2-1',
    toNodeId: 'node-kuw-2-2',
    roadName: 'Sharq Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-4',
    fromNodeId: 'node-kuw-2-2',
    toNodeId: 'node-kuw-2-3',
    roadName: 'Sharq Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-5',
    fromNodeId: 'node-kuw-3-1',
    toNodeId: 'node-kuw-3-2',
    roadName: 'Kuwait City Downtown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-6',
    fromNodeId: 'node-kuw-3-2',
    toNodeId: 'node-kuw-3-3',
    roadName: 'Kuwait City Downtown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-7',
    fromNodeId: 'node-kuw-4-1',
    toNodeId: 'node-kuw-4-2',
    roadName: 'Shuwaikh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-8',
    fromNodeId: 'node-kuw-4-2',
    toNodeId: 'node-kuw-4-3',
    roadName: 'Shuwaikh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-9',
    fromNodeId: 'node-kuw-5-1',
    toNodeId: 'node-kuw-5-2',
    roadName: 'Jabriya Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-10',
    fromNodeId: 'node-kuw-5-2',
    toNodeId: 'node-kuw-5-3',
    roadName: 'Jabriya Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-11',
    fromNodeId: 'node-kuw-6-1',
    toNodeId: 'node-kuw-6-2',
    roadName: 'Hawally Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-12',
    fromNodeId: 'node-kuw-6-2',
    toNodeId: 'node-kuw-6-3',
    roadName: 'Hawally Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-13',
    fromNodeId: 'node-kuw-7-1',
    toNodeId: 'node-kuw-7-2',
    roadName: 'Bneid Al-Gar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-14',
    fromNodeId: 'node-kuw-7-2',
    toNodeId: 'node-kuw-7-3',
    roadName: 'Bneid Al-Gar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-15',
    fromNodeId: 'node-kuw-8-1',
    toNodeId: 'node-kuw-8-2',
    roadName: 'Al Bidaa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-16',
    fromNodeId: 'node-kuw-8-2',
    toNodeId: 'node-kuw-8-3',
    roadName: 'Al Bidaa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-17',
    fromNodeId: 'node-kuw-9-1',
    toNodeId: 'node-kuw-9-2',
    roadName: 'Dasman Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-18',
    fromNodeId: 'node-kuw-9-2',
    toNodeId: 'node-kuw-9-3',
    roadName: 'Dasman Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-19',
    fromNodeId: 'node-kuw-10-1',
    toNodeId: 'node-kuw-10-2',
    roadName: 'Salwa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kuw-20',
    fromNodeId: 'node-kuw-10-2',
    toNodeId: 'node-kuw-10-3',
    roadName: 'Salwa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
