/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Kyoto Ancient Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const KYOTO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 35.0116,
  longitude: 135.7681,
};

export const KYOTO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-kyo-1-1',
    name: 'Gion Sector 1 High Street',
    zone: 'Gion',
    location: { latitude: 34.949600, longitude: 135.716100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gion.',
  },
  {
    id: 'node-kyo-1-2',
    name: 'Gion Sector 2 High Street',
    zone: 'Gion',
    location: { latitude: 34.952600, longitude: 135.719100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gion.',
  },
  {
    id: 'node-kyo-1-3',
    name: 'Gion Sector 3 High Street',
    zone: 'Gion',
    location: { latitude: 34.955600, longitude: 135.722100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gion.',
  },
  {
    id: 'node-kyo-2-1',
    name: 'Arashiyama Sector 1 High Street',
    zone: 'Arashiyama',
    location: { latitude: 34.961600, longitude: 135.726100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Arashiyama.',
  },
  {
    id: 'node-kyo-2-2',
    name: 'Arashiyama Sector 2 High Street',
    zone: 'Arashiyama',
    location: { latitude: 34.964600, longitude: 135.729100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Arashiyama.',
  },
  {
    id: 'node-kyo-2-3',
    name: 'Arashiyama Sector 3 High Street',
    zone: 'Arashiyama',
    location: { latitude: 34.967600, longitude: 135.732100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Arashiyama.',
  },
  {
    id: 'node-kyo-3-1',
    name: 'Pontocho Sector 1 High Street',
    zone: 'Pontocho',
    location: { latitude: 34.973600, longitude: 135.736100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pontocho.',
  },
  {
    id: 'node-kyo-3-2',
    name: 'Pontocho Sector 2 High Street',
    zone: 'Pontocho',
    location: { latitude: 34.976600, longitude: 135.739100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pontocho.',
  },
  {
    id: 'node-kyo-3-3',
    name: 'Pontocho Sector 3 High Street',
    zone: 'Pontocho',
    location: { latitude: 34.979600, longitude: 135.742100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pontocho.',
  },
  {
    id: 'node-kyo-4-1',
    name: 'Kawaramachi Sector 1 High Street',
    zone: 'Kawaramachi',
    location: { latitude: 34.985600, longitude: 135.746100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kawaramachi.',
  },
  {
    id: 'node-kyo-4-2',
    name: 'Kawaramachi Sector 2 High Street',
    zone: 'Kawaramachi',
    location: { latitude: 34.988600, longitude: 135.749100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kawaramachi.',
  },
  {
    id: 'node-kyo-4-3',
    name: 'Kawaramachi Sector 3 High Street',
    zone: 'Kawaramachi',
    location: { latitude: 34.991600, longitude: 135.752100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kawaramachi.',
  },
  {
    id: 'node-kyo-5-1',
    name: 'Higashiyama Sector 1 High Street',
    zone: 'Higashiyama',
    location: { latitude: 34.997600, longitude: 135.756100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Higashiyama.',
  },
  {
    id: 'node-kyo-5-2',
    name: 'Higashiyama Sector 2 High Street',
    zone: 'Higashiyama',
    location: { latitude: 35.000600, longitude: 135.759100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Higashiyama.',
  },
  {
    id: 'node-kyo-5-3',
    name: 'Higashiyama Sector 3 High Street',
    zone: 'Higashiyama',
    location: { latitude: 35.003600, longitude: 135.762100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Higashiyama.',
  },
  {
    id: 'node-kyo-6-1',
    name: 'Fushimi Sector 1 High Street',
    zone: 'Fushimi',
    location: { latitude: 35.009600, longitude: 135.766100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fushimi.',
  },
  {
    id: 'node-kyo-6-2',
    name: 'Fushimi Sector 2 High Street',
    zone: 'Fushimi',
    location: { latitude: 35.012600, longitude: 135.769100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fushimi.',
  },
  {
    id: 'node-kyo-6-3',
    name: 'Fushimi Sector 3 High Street',
    zone: 'Fushimi',
    location: { latitude: 35.015600, longitude: 135.772100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fushimi.',
  },
  {
    id: 'node-kyo-7-1',
    name: 'Kinkaku-ji District Sector 1 High Street',
    zone: 'Kinkaku-ji District',
    location: { latitude: 35.021600, longitude: 135.776100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kinkaku-ji District.',
  },
  {
    id: 'node-kyo-7-2',
    name: 'Kinkaku-ji District Sector 2 High Street',
    zone: 'Kinkaku-ji District',
    location: { latitude: 35.024600, longitude: 135.779100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kinkaku-ji District.',
  },
  {
    id: 'node-kyo-7-3',
    name: 'Kinkaku-ji District Sector 3 High Street',
    zone: 'Kinkaku-ji District',
    location: { latitude: 35.027600, longitude: 135.782100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kinkaku-ji District.',
  },
  {
    id: 'node-kyo-8-1',
    name: 'Kitayama Sector 1 High Street',
    zone: 'Kitayama',
    location: { latitude: 35.033600, longitude: 135.786100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kitayama.',
  },
  {
    id: 'node-kyo-8-2',
    name: 'Kitayama Sector 2 High Street',
    zone: 'Kitayama',
    location: { latitude: 35.036600, longitude: 135.789100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kitayama.',
  },
  {
    id: 'node-kyo-8-3',
    name: 'Kitayama Sector 3 High Street',
    zone: 'Kitayama',
    location: { latitude: 35.039600, longitude: 135.792100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kitayama.',
  },
  {
    id: 'node-kyo-9-1',
    name: 'Nishiki Market Sector 1 High Street',
    zone: 'Nishiki Market',
    location: { latitude: 35.045600, longitude: 135.796100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nishiki Market.',
  },
  {
    id: 'node-kyo-9-2',
    name: 'Nishiki Market Sector 2 High Street',
    zone: 'Nishiki Market',
    location: { latitude: 35.048600, longitude: 135.799100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nishiki Market.',
  },
  {
    id: 'node-kyo-9-3',
    name: 'Nishiki Market Sector 3 High Street',
    zone: 'Nishiki Market',
    location: { latitude: 35.051600, longitude: 135.802100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nishiki Market.',
  },
  {
    id: 'node-kyo-10-1',
    name: 'Kamigamo Sector 1 High Street',
    zone: 'Kamigamo',
    location: { latitude: 35.057600, longitude: 135.806100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kamigamo.',
  },
  {
    id: 'node-kyo-10-2',
    name: 'Kamigamo Sector 2 High Street',
    zone: 'Kamigamo',
    location: { latitude: 35.060600, longitude: 135.809100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kamigamo.',
  },
  {
    id: 'node-kyo-10-3',
    name: 'Kamigamo Sector 3 High Street',
    zone: 'Kamigamo',
    location: { latitude: 35.063600, longitude: 135.812100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kamigamo.',
  },
];

export const KYOTO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-kyo-1',
    fromNodeId: 'node-kyo-1-1',
    toNodeId: 'node-kyo-1-2',
    roadName: 'Gion Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-2',
    fromNodeId: 'node-kyo-1-2',
    toNodeId: 'node-kyo-1-3',
    roadName: 'Gion Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-3',
    fromNodeId: 'node-kyo-2-1',
    toNodeId: 'node-kyo-2-2',
    roadName: 'Arashiyama Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-4',
    fromNodeId: 'node-kyo-2-2',
    toNodeId: 'node-kyo-2-3',
    roadName: 'Arashiyama Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-5',
    fromNodeId: 'node-kyo-3-1',
    toNodeId: 'node-kyo-3-2',
    roadName: 'Pontocho Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-6',
    fromNodeId: 'node-kyo-3-2',
    toNodeId: 'node-kyo-3-3',
    roadName: 'Pontocho Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-7',
    fromNodeId: 'node-kyo-4-1',
    toNodeId: 'node-kyo-4-2',
    roadName: 'Kawaramachi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-8',
    fromNodeId: 'node-kyo-4-2',
    toNodeId: 'node-kyo-4-3',
    roadName: 'Kawaramachi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-9',
    fromNodeId: 'node-kyo-5-1',
    toNodeId: 'node-kyo-5-2',
    roadName: 'Higashiyama Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-10',
    fromNodeId: 'node-kyo-5-2',
    toNodeId: 'node-kyo-5-3',
    roadName: 'Higashiyama Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-11',
    fromNodeId: 'node-kyo-6-1',
    toNodeId: 'node-kyo-6-2',
    roadName: 'Fushimi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-12',
    fromNodeId: 'node-kyo-6-2',
    toNodeId: 'node-kyo-6-3',
    roadName: 'Fushimi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-13',
    fromNodeId: 'node-kyo-7-1',
    toNodeId: 'node-kyo-7-2',
    roadName: 'Kinkaku-ji District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-14',
    fromNodeId: 'node-kyo-7-2',
    toNodeId: 'node-kyo-7-3',
    roadName: 'Kinkaku-ji District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-15',
    fromNodeId: 'node-kyo-8-1',
    toNodeId: 'node-kyo-8-2',
    roadName: 'Kitayama Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-16',
    fromNodeId: 'node-kyo-8-2',
    toNodeId: 'node-kyo-8-3',
    roadName: 'Kitayama Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-17',
    fromNodeId: 'node-kyo-9-1',
    toNodeId: 'node-kyo-9-2',
    roadName: 'Nishiki Market Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-18',
    fromNodeId: 'node-kyo-9-2',
    toNodeId: 'node-kyo-9-3',
    roadName: 'Nishiki Market Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-19',
    fromNodeId: 'node-kyo-10-1',
    toNodeId: 'node-kyo-10-2',
    roadName: 'Kamigamo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-kyo-20',
    fromNodeId: 'node-kyo-10-2',
    toNodeId: 'node-kyo-10-3',
    roadName: 'Kamigamo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
