/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Las Vegas Strip & Valley
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const LASVEGAS_BASE_COORDINATE: GeoCoordinate = {
  latitude: 36.1699,
  longitude: -115.1398,
};

export const LASVEGAS_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-las-1-1',
    name: 'The Strip Sector 1 High Street',
    zone: 'The Strip',
    location: { latitude: 36.107900, longitude: -115.191800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in The Strip.',
  },
  {
    id: 'node-las-1-2',
    name: 'The Strip Sector 2 High Street',
    zone: 'The Strip',
    location: { latitude: 36.110900, longitude: -115.188800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in The Strip.',
  },
  {
    id: 'node-las-1-3',
    name: 'The Strip Sector 3 High Street',
    zone: 'The Strip',
    location: { latitude: 36.113900, longitude: -115.185800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in The Strip.',
  },
  {
    id: 'node-las-2-1',
    name: 'Downtown Las Vegas Sector 1 High Street',
    zone: 'Downtown Las Vegas',
    location: { latitude: 36.119900, longitude: -115.181800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Las Vegas.',
  },
  {
    id: 'node-las-2-2',
    name: 'Downtown Las Vegas Sector 2 High Street',
    zone: 'Downtown Las Vegas',
    location: { latitude: 36.122900, longitude: -115.178800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Las Vegas.',
  },
  {
    id: 'node-las-2-3',
    name: 'Downtown Las Vegas Sector 3 High Street',
    zone: 'Downtown Las Vegas',
    location: { latitude: 36.125900, longitude: -115.175800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Las Vegas.',
  },
  {
    id: 'node-las-3-1',
    name: 'Summerlin Sector 1 High Street',
    zone: 'Summerlin',
    location: { latitude: 36.131900, longitude: -115.171800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Summerlin.',
  },
  {
    id: 'node-las-3-2',
    name: 'Summerlin Sector 2 High Street',
    zone: 'Summerlin',
    location: { latitude: 36.134900, longitude: -115.168800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Summerlin.',
  },
  {
    id: 'node-las-3-3',
    name: 'Summerlin Sector 3 High Street',
    zone: 'Summerlin',
    location: { latitude: 36.137900, longitude: -115.165800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Summerlin.',
  },
  {
    id: 'node-las-4-1',
    name: 'Arts District LV Sector 1 High Street',
    zone: 'Arts District LV',
    location: { latitude: 36.143900, longitude: -115.161800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Arts District LV.',
  },
  {
    id: 'node-las-4-2',
    name: 'Arts District LV Sector 2 High Street',
    zone: 'Arts District LV',
    location: { latitude: 36.146900, longitude: -115.158800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Arts District LV.',
  },
  {
    id: 'node-las-4-3',
    name: 'Arts District LV Sector 3 High Street',
    zone: 'Arts District LV',
    location: { latitude: 36.149900, longitude: -115.155800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Arts District LV.',
  },
  {
    id: 'node-las-5-1',
    name: 'Henderson Sector 1 High Street',
    zone: 'Henderson',
    location: { latitude: 36.155900, longitude: -115.151800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Henderson.',
  },
  {
    id: 'node-las-5-2',
    name: 'Henderson Sector 2 High Street',
    zone: 'Henderson',
    location: { latitude: 36.158900, longitude: -115.148800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Henderson.',
  },
  {
    id: 'node-las-5-3',
    name: 'Henderson Sector 3 High Street',
    zone: 'Henderson',
    location: { latitude: 36.161900, longitude: -115.145800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Henderson.',
  },
  {
    id: 'node-las-6-1',
    name: 'Spring Valley Sector 1 High Street',
    zone: 'Spring Valley',
    location: { latitude: 36.167900, longitude: -115.141800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Spring Valley.',
  },
  {
    id: 'node-las-6-2',
    name: 'Spring Valley Sector 2 High Street',
    zone: 'Spring Valley',
    location: { latitude: 36.170900, longitude: -115.138800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Spring Valley.',
  },
  {
    id: 'node-las-6-3',
    name: 'Spring Valley Sector 3 High Street',
    zone: 'Spring Valley',
    location: { latitude: 36.173900, longitude: -115.135800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Spring Valley.',
  },
  {
    id: 'node-las-7-1',
    name: 'Green Valley Sector 1 High Street',
    zone: 'Green Valley',
    location: { latitude: 36.179900, longitude: -115.131800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Green Valley.',
  },
  {
    id: 'node-las-7-2',
    name: 'Green Valley Sector 2 High Street',
    zone: 'Green Valley',
    location: { latitude: 36.182900, longitude: -115.128800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Green Valley.',
  },
  {
    id: 'node-las-7-3',
    name: 'Green Valley Sector 3 High Street',
    zone: 'Green Valley',
    location: { latitude: 36.185900, longitude: -115.125800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Green Valley.',
  },
  {
    id: 'node-las-8-1',
    name: 'Southwest Las Vegas Sector 1 High Street',
    zone: 'Southwest Las Vegas',
    location: { latitude: 36.191900, longitude: -115.121800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Southwest Las Vegas.',
  },
  {
    id: 'node-las-8-2',
    name: 'Southwest Las Vegas Sector 2 High Street',
    zone: 'Southwest Las Vegas',
    location: { latitude: 36.194900, longitude: -115.118800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Southwest Las Vegas.',
  },
  {
    id: 'node-las-8-3',
    name: 'Southwest Las Vegas Sector 3 High Street',
    zone: 'Southwest Las Vegas',
    location: { latitude: 36.197900, longitude: -115.115800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Southwest Las Vegas.',
  },
  {
    id: 'node-las-9-1',
    name: 'Centennial Hills Sector 1 High Street',
    zone: 'Centennial Hills',
    location: { latitude: 36.203900, longitude: -115.111800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Centennial Hills.',
  },
  {
    id: 'node-las-9-2',
    name: 'Centennial Hills Sector 2 High Street',
    zone: 'Centennial Hills',
    location: { latitude: 36.206900, longitude: -115.108800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Centennial Hills.',
  },
  {
    id: 'node-las-9-3',
    name: 'Centennial Hills Sector 3 High Street',
    zone: 'Centennial Hills',
    location: { latitude: 36.209900, longitude: -115.105800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Centennial Hills.',
  },
  {
    id: 'node-las-10-1',
    name: 'Paradise NV Sector 1 High Street',
    zone: 'Paradise NV',
    location: { latitude: 36.215900, longitude: -115.101800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Paradise NV.',
  },
  {
    id: 'node-las-10-2',
    name: 'Paradise NV Sector 2 High Street',
    zone: 'Paradise NV',
    location: { latitude: 36.218900, longitude: -115.098800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Paradise NV.',
  },
  {
    id: 'node-las-10-3',
    name: 'Paradise NV Sector 3 High Street',
    zone: 'Paradise NV',
    location: { latitude: 36.221900, longitude: -115.095800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Paradise NV.',
  },
];

export const LASVEGAS_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-las-1',
    fromNodeId: 'node-las-1-1',
    toNodeId: 'node-las-1-2',
    roadName: 'The Strip Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-2',
    fromNodeId: 'node-las-1-2',
    toNodeId: 'node-las-1-3',
    roadName: 'The Strip Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-3',
    fromNodeId: 'node-las-2-1',
    toNodeId: 'node-las-2-2',
    roadName: 'Downtown Las Vegas Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-4',
    fromNodeId: 'node-las-2-2',
    toNodeId: 'node-las-2-3',
    roadName: 'Downtown Las Vegas Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-5',
    fromNodeId: 'node-las-3-1',
    toNodeId: 'node-las-3-2',
    roadName: 'Summerlin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-6',
    fromNodeId: 'node-las-3-2',
    toNodeId: 'node-las-3-3',
    roadName: 'Summerlin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-7',
    fromNodeId: 'node-las-4-1',
    toNodeId: 'node-las-4-2',
    roadName: 'Arts District LV Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-8',
    fromNodeId: 'node-las-4-2',
    toNodeId: 'node-las-4-3',
    roadName: 'Arts District LV Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-9',
    fromNodeId: 'node-las-5-1',
    toNodeId: 'node-las-5-2',
    roadName: 'Henderson Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-10',
    fromNodeId: 'node-las-5-2',
    toNodeId: 'node-las-5-3',
    roadName: 'Henderson Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-11',
    fromNodeId: 'node-las-6-1',
    toNodeId: 'node-las-6-2',
    roadName: 'Spring Valley Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-12',
    fromNodeId: 'node-las-6-2',
    toNodeId: 'node-las-6-3',
    roadName: 'Spring Valley Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-13',
    fromNodeId: 'node-las-7-1',
    toNodeId: 'node-las-7-2',
    roadName: 'Green Valley Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-14',
    fromNodeId: 'node-las-7-2',
    toNodeId: 'node-las-7-3',
    roadName: 'Green Valley Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-15',
    fromNodeId: 'node-las-8-1',
    toNodeId: 'node-las-8-2',
    roadName: 'Southwest Las Vegas Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-16',
    fromNodeId: 'node-las-8-2',
    toNodeId: 'node-las-8-3',
    roadName: 'Southwest Las Vegas Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-17',
    fromNodeId: 'node-las-9-1',
    toNodeId: 'node-las-9-2',
    roadName: 'Centennial Hills Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-18',
    fromNodeId: 'node-las-9-2',
    toNodeId: 'node-las-9-3',
    roadName: 'Centennial Hills Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-19',
    fromNodeId: 'node-las-10-1',
    toNodeId: 'node-las-10-2',
    roadName: 'Paradise NV Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-las-20',
    fromNodeId: 'node-las-10-2',
    toNodeId: 'node-las-10-3',
    roadName: 'Paradise NV Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
