/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Leeds West Yorkshire Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const LEEDS_BASE_COORDINATE: GeoCoordinate = {
  latitude: 53.8008,
  longitude: -1.5491,
};

export const LEEDS_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-lee-1-1',
    name: 'City Centre Leeds Sector 1 High Street',
    zone: 'City Centre Leeds',
    location: { latitude: 53.738800, longitude: -1.601100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in City Centre Leeds.',
  },
  {
    id: 'node-lee-1-2',
    name: 'City Centre Leeds Sector 2 High Street',
    zone: 'City Centre Leeds',
    location: { latitude: 53.741800, longitude: -1.598100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in City Centre Leeds.',
  },
  {
    id: 'node-lee-1-3',
    name: 'City Centre Leeds Sector 3 High Street',
    zone: 'City Centre Leeds',
    location: { latitude: 53.744800, longitude: -1.595100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in City Centre Leeds.',
  },
  {
    id: 'node-lee-2-1',
    name: 'Headingley Sector 1 High Street',
    zone: 'Headingley',
    location: { latitude: 53.750800, longitude: -1.591100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Headingley.',
  },
  {
    id: 'node-lee-2-2',
    name: 'Headingley Sector 2 High Street',
    zone: 'Headingley',
    location: { latitude: 53.753800, longitude: -1.588100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Headingley.',
  },
  {
    id: 'node-lee-2-3',
    name: 'Headingley Sector 3 High Street',
    zone: 'Headingley',
    location: { latitude: 53.756800, longitude: -1.585100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Headingley.',
  },
  {
    id: 'node-lee-3-1',
    name: 'Chapel Allerton Sector 1 High Street',
    zone: 'Chapel Allerton',
    location: { latitude: 53.762800, longitude: -1.581100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chapel Allerton.',
  },
  {
    id: 'node-lee-3-2',
    name: 'Chapel Allerton Sector 2 High Street',
    zone: 'Chapel Allerton',
    location: { latitude: 53.765800, longitude: -1.578100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chapel Allerton.',
  },
  {
    id: 'node-lee-3-3',
    name: 'Chapel Allerton Sector 3 High Street',
    zone: 'Chapel Allerton',
    location: { latitude: 53.768800, longitude: -1.575100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chapel Allerton.',
  },
  {
    id: 'node-lee-4-1',
    name: 'Roundhay Sector 1 High Street',
    zone: 'Roundhay',
    location: { latitude: 53.774800, longitude: -1.571100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Roundhay.',
  },
  {
    id: 'node-lee-4-2',
    name: 'Roundhay Sector 2 High Street',
    zone: 'Roundhay',
    location: { latitude: 53.777800, longitude: -1.568100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Roundhay.',
  },
  {
    id: 'node-lee-4-3',
    name: 'Roundhay Sector 3 High Street',
    zone: 'Roundhay',
    location: { latitude: 53.780800, longitude: -1.565100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Roundhay.',
  },
  {
    id: 'node-lee-5-1',
    name: 'Holbeck Sector 1 High Street',
    zone: 'Holbeck',
    location: { latitude: 53.786800, longitude: -1.561100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Holbeck.',
  },
  {
    id: 'node-lee-5-2',
    name: 'Holbeck Sector 2 High Street',
    zone: 'Holbeck',
    location: { latitude: 53.789800, longitude: -1.558100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Holbeck.',
  },
  {
    id: 'node-lee-5-3',
    name: 'Holbeck Sector 3 High Street',
    zone: 'Holbeck',
    location: { latitude: 53.792800, longitude: -1.555100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Holbeck.',
  },
  {
    id: 'node-lee-6-1',
    name: 'Waterfront Leeds Sector 1 High Street',
    zone: 'Waterfront Leeds',
    location: { latitude: 53.798800, longitude: -1.551100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Waterfront Leeds.',
  },
  {
    id: 'node-lee-6-2',
    name: 'Waterfront Leeds Sector 2 High Street',
    zone: 'Waterfront Leeds',
    location: { latitude: 53.801800, longitude: -1.548100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Waterfront Leeds.',
  },
  {
    id: 'node-lee-6-3',
    name: 'Waterfront Leeds Sector 3 High Street',
    zone: 'Waterfront Leeds',
    location: { latitude: 53.804800, longitude: -1.545100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Waterfront Leeds.',
  },
  {
    id: 'node-lee-7-1',
    name: 'Horsforth Sector 1 High Street',
    zone: 'Horsforth',
    location: { latitude: 53.810800, longitude: -1.541100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Horsforth.',
  },
  {
    id: 'node-lee-7-2',
    name: 'Horsforth Sector 2 High Street',
    zone: 'Horsforth',
    location: { latitude: 53.813800, longitude: -1.538100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Horsforth.',
  },
  {
    id: 'node-lee-7-3',
    name: 'Horsforth Sector 3 High Street',
    zone: 'Horsforth',
    location: { latitude: 53.816800, longitude: -1.535100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Horsforth.',
  },
  {
    id: 'node-lee-8-1',
    name: 'Kirkstall Sector 1 High Street',
    zone: 'Kirkstall',
    location: { latitude: 53.822800, longitude: -1.531100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kirkstall.',
  },
  {
    id: 'node-lee-8-2',
    name: 'Kirkstall Sector 2 High Street',
    zone: 'Kirkstall',
    location: { latitude: 53.825800, longitude: -1.528100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kirkstall.',
  },
  {
    id: 'node-lee-8-3',
    name: 'Kirkstall Sector 3 High Street',
    zone: 'Kirkstall',
    location: { latitude: 53.828800, longitude: -1.525100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kirkstall.',
  },
  {
    id: 'node-lee-9-1',
    name: 'Meanwood Sector 1 High Street',
    zone: 'Meanwood',
    location: { latitude: 53.834800, longitude: -1.521100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Meanwood.',
  },
  {
    id: 'node-lee-9-2',
    name: 'Meanwood Sector 2 High Street',
    zone: 'Meanwood',
    location: { latitude: 53.837800, longitude: -1.518100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Meanwood.',
  },
  {
    id: 'node-lee-9-3',
    name: 'Meanwood Sector 3 High Street',
    zone: 'Meanwood',
    location: { latitude: 53.840800, longitude: -1.515100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Meanwood.',
  },
  {
    id: 'node-lee-10-1',
    name: 'Hyde Park Leeds Sector 1 High Street',
    zone: 'Hyde Park Leeds',
    location: { latitude: 53.846800, longitude: -1.511100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park Leeds.',
  },
  {
    id: 'node-lee-10-2',
    name: 'Hyde Park Leeds Sector 2 High Street',
    zone: 'Hyde Park Leeds',
    location: { latitude: 53.849800, longitude: -1.508100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park Leeds.',
  },
  {
    id: 'node-lee-10-3',
    name: 'Hyde Park Leeds Sector 3 High Street',
    zone: 'Hyde Park Leeds',
    location: { latitude: 53.852800, longitude: -1.505100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park Leeds.',
  },
];

export const LEEDS_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-lee-1',
    fromNodeId: 'node-lee-1-1',
    toNodeId: 'node-lee-1-2',
    roadName: 'City Centre Leeds Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-2',
    fromNodeId: 'node-lee-1-2',
    toNodeId: 'node-lee-1-3',
    roadName: 'City Centre Leeds Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-3',
    fromNodeId: 'node-lee-2-1',
    toNodeId: 'node-lee-2-2',
    roadName: 'Headingley Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-4',
    fromNodeId: 'node-lee-2-2',
    toNodeId: 'node-lee-2-3',
    roadName: 'Headingley Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-5',
    fromNodeId: 'node-lee-3-1',
    toNodeId: 'node-lee-3-2',
    roadName: 'Chapel Allerton Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-6',
    fromNodeId: 'node-lee-3-2',
    toNodeId: 'node-lee-3-3',
    roadName: 'Chapel Allerton Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-7',
    fromNodeId: 'node-lee-4-1',
    toNodeId: 'node-lee-4-2',
    roadName: 'Roundhay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-8',
    fromNodeId: 'node-lee-4-2',
    toNodeId: 'node-lee-4-3',
    roadName: 'Roundhay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-9',
    fromNodeId: 'node-lee-5-1',
    toNodeId: 'node-lee-5-2',
    roadName: 'Holbeck Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-10',
    fromNodeId: 'node-lee-5-2',
    toNodeId: 'node-lee-5-3',
    roadName: 'Holbeck Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-11',
    fromNodeId: 'node-lee-6-1',
    toNodeId: 'node-lee-6-2',
    roadName: 'Waterfront Leeds Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-12',
    fromNodeId: 'node-lee-6-2',
    toNodeId: 'node-lee-6-3',
    roadName: 'Waterfront Leeds Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-13',
    fromNodeId: 'node-lee-7-1',
    toNodeId: 'node-lee-7-2',
    roadName: 'Horsforth Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-14',
    fromNodeId: 'node-lee-7-2',
    toNodeId: 'node-lee-7-3',
    roadName: 'Horsforth Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-15',
    fromNodeId: 'node-lee-8-1',
    toNodeId: 'node-lee-8-2',
    roadName: 'Kirkstall Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-16',
    fromNodeId: 'node-lee-8-2',
    toNodeId: 'node-lee-8-3',
    roadName: 'Kirkstall Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-17',
    fromNodeId: 'node-lee-9-1',
    toNodeId: 'node-lee-9-2',
    roadName: 'Meanwood Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-18',
    fromNodeId: 'node-lee-9-2',
    toNodeId: 'node-lee-9-3',
    roadName: 'Meanwood Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-19',
    fromNodeId: 'node-lee-10-1',
    toNodeId: 'node-lee-10-2',
    roadName: 'Hyde Park Leeds Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lee-20',
    fromNodeId: 'node-lee-10-2',
    toNodeId: 'node-lee-10-3',
    roadName: 'Hyde Park Leeds Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
