/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Lisbon Tagus River Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const LISBON_BASE_COORDINATE: GeoCoordinate = {
  latitude: 38.7223,
  longitude: -9.1393,
};

export const LISBON_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-lis-1-1',
    name: 'Baixa Sector 1 High Street',
    zone: 'Baixa',
    location: { latitude: 38.660300, longitude: -9.191300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Baixa.',
  },
  {
    id: 'node-lis-1-2',
    name: 'Baixa Sector 2 High Street',
    zone: 'Baixa',
    location: { latitude: 38.663300, longitude: -9.188300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Baixa.',
  },
  {
    id: 'node-lis-1-3',
    name: 'Baixa Sector 3 High Street',
    zone: 'Baixa',
    location: { latitude: 38.666300, longitude: -9.185300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Baixa.',
  },
  {
    id: 'node-lis-2-1',
    name: 'Chiado Sector 1 High Street',
    zone: 'Chiado',
    location: { latitude: 38.672300, longitude: -9.181300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chiado.',
  },
  {
    id: 'node-lis-2-2',
    name: 'Chiado Sector 2 High Street',
    zone: 'Chiado',
    location: { latitude: 38.675300, longitude: -9.178300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chiado.',
  },
  {
    id: 'node-lis-2-3',
    name: 'Chiado Sector 3 High Street',
    zone: 'Chiado',
    location: { latitude: 38.678300, longitude: -9.175300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chiado.',
  },
  {
    id: 'node-lis-3-1',
    name: 'Bairro Alto Sector 1 High Street',
    zone: 'Bairro Alto',
    location: { latitude: 38.684300, longitude: -9.171300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bairro Alto.',
  },
  {
    id: 'node-lis-3-2',
    name: 'Bairro Alto Sector 2 High Street',
    zone: 'Bairro Alto',
    location: { latitude: 38.687300, longitude: -9.168300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bairro Alto.',
  },
  {
    id: 'node-lis-3-3',
    name: 'Bairro Alto Sector 3 High Street',
    zone: 'Bairro Alto',
    location: { latitude: 38.690300, longitude: -9.165300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bairro Alto.',
  },
  {
    id: 'node-lis-4-1',
    name: 'Alfama Sector 1 High Street',
    zone: 'Alfama',
    location: { latitude: 38.696300, longitude: -9.161300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Alfama.',
  },
  {
    id: 'node-lis-4-2',
    name: 'Alfama Sector 2 High Street',
    zone: 'Alfama',
    location: { latitude: 38.699300, longitude: -9.158300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Alfama.',
  },
  {
    id: 'node-lis-4-3',
    name: 'Alfama Sector 3 High Street',
    zone: 'Alfama',
    location: { latitude: 38.702300, longitude: -9.155300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Alfama.',
  },
  {
    id: 'node-lis-5-1',
    name: 'Príncipe Real Sector 1 High Street',
    zone: 'Príncipe Real',
    location: { latitude: 38.708300, longitude: -9.151300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Príncipe Real.',
  },
  {
    id: 'node-lis-5-2',
    name: 'Príncipe Real Sector 2 High Street',
    zone: 'Príncipe Real',
    location: { latitude: 38.711300, longitude: -9.148300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Príncipe Real.',
  },
  {
    id: 'node-lis-5-3',
    name: 'Príncipe Real Sector 3 High Street',
    zone: 'Príncipe Real',
    location: { latitude: 38.714300, longitude: -9.145300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Príncipe Real.',
  },
  {
    id: 'node-lis-6-1',
    name: 'Belém Sector 1 High Street',
    zone: 'Belém',
    location: { latitude: 38.720300, longitude: -9.141300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Belém.',
  },
  {
    id: 'node-lis-6-2',
    name: 'Belém Sector 2 High Street',
    zone: 'Belém',
    location: { latitude: 38.723300, longitude: -9.138300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Belém.',
  },
  {
    id: 'node-lis-6-3',
    name: 'Belém Sector 3 High Street',
    zone: 'Belém',
    location: { latitude: 38.726300, longitude: -9.135300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Belém.',
  },
  {
    id: 'node-lis-7-1',
    name: 'Parque das Nações Sector 1 High Street',
    zone: 'Parque das Nações',
    location: { latitude: 38.732300, longitude: -9.131300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Parque das Nações.',
  },
  {
    id: 'node-lis-7-2',
    name: 'Parque das Nações Sector 2 High Street',
    zone: 'Parque das Nações',
    location: { latitude: 38.735300, longitude: -9.128300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Parque das Nações.',
  },
  {
    id: 'node-lis-7-3',
    name: 'Parque das Nações Sector 3 High Street',
    zone: 'Parque das Nações',
    location: { latitude: 38.738300, longitude: -9.125300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Parque das Nações.',
  },
  {
    id: 'node-lis-8-1',
    name: 'Campo de Ourique Sector 1 High Street',
    zone: 'Campo de Ourique',
    location: { latitude: 38.744300, longitude: -9.121300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Campo de Ourique.',
  },
  {
    id: 'node-lis-8-2',
    name: 'Campo de Ourique Sector 2 High Street',
    zone: 'Campo de Ourique',
    location: { latitude: 38.747300, longitude: -9.118300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Campo de Ourique.',
  },
  {
    id: 'node-lis-8-3',
    name: 'Campo de Ourique Sector 3 High Street',
    zone: 'Campo de Ourique',
    location: { latitude: 38.750300, longitude: -9.115300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Campo de Ourique.',
  },
  {
    id: 'node-lis-9-1',
    name: 'Avenidas Novas Sector 1 High Street',
    zone: 'Avenidas Novas',
    location: { latitude: 38.756300, longitude: -9.111300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Avenidas Novas.',
  },
  {
    id: 'node-lis-9-2',
    name: 'Avenidas Novas Sector 2 High Street',
    zone: 'Avenidas Novas',
    location: { latitude: 38.759300, longitude: -9.108300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Avenidas Novas.',
  },
  {
    id: 'node-lis-9-3',
    name: 'Avenidas Novas Sector 3 High Street',
    zone: 'Avenidas Novas',
    location: { latitude: 38.762300, longitude: -9.105300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Avenidas Novas.',
  },
  {
    id: 'node-lis-10-1',
    name: 'Santos Sector 1 High Street',
    zone: 'Santos',
    location: { latitude: 38.768300, longitude: -9.101300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Santos.',
  },
  {
    id: 'node-lis-10-2',
    name: 'Santos Sector 2 High Street',
    zone: 'Santos',
    location: { latitude: 38.771300, longitude: -9.098300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Santos.',
  },
  {
    id: 'node-lis-10-3',
    name: 'Santos Sector 3 High Street',
    zone: 'Santos',
    location: { latitude: 38.774300, longitude: -9.095300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Santos.',
  },
];

export const LISBON_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-lis-1',
    fromNodeId: 'node-lis-1-1',
    toNodeId: 'node-lis-1-2',
    roadName: 'Baixa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-2',
    fromNodeId: 'node-lis-1-2',
    toNodeId: 'node-lis-1-3',
    roadName: 'Baixa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-3',
    fromNodeId: 'node-lis-2-1',
    toNodeId: 'node-lis-2-2',
    roadName: 'Chiado Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-4',
    fromNodeId: 'node-lis-2-2',
    toNodeId: 'node-lis-2-3',
    roadName: 'Chiado Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-5',
    fromNodeId: 'node-lis-3-1',
    toNodeId: 'node-lis-3-2',
    roadName: 'Bairro Alto Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-6',
    fromNodeId: 'node-lis-3-2',
    toNodeId: 'node-lis-3-3',
    roadName: 'Bairro Alto Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-7',
    fromNodeId: 'node-lis-4-1',
    toNodeId: 'node-lis-4-2',
    roadName: 'Alfama Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-8',
    fromNodeId: 'node-lis-4-2',
    toNodeId: 'node-lis-4-3',
    roadName: 'Alfama Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-9',
    fromNodeId: 'node-lis-5-1',
    toNodeId: 'node-lis-5-2',
    roadName: 'Príncipe Real Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-10',
    fromNodeId: 'node-lis-5-2',
    toNodeId: 'node-lis-5-3',
    roadName: 'Príncipe Real Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-11',
    fromNodeId: 'node-lis-6-1',
    toNodeId: 'node-lis-6-2',
    roadName: 'Belém Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-12',
    fromNodeId: 'node-lis-6-2',
    toNodeId: 'node-lis-6-3',
    roadName: 'Belém Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-13',
    fromNodeId: 'node-lis-7-1',
    toNodeId: 'node-lis-7-2',
    roadName: 'Parque das Nações Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-14',
    fromNodeId: 'node-lis-7-2',
    toNodeId: 'node-lis-7-3',
    roadName: 'Parque das Nações Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-15',
    fromNodeId: 'node-lis-8-1',
    toNodeId: 'node-lis-8-2',
    roadName: 'Campo de Ourique Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-16',
    fromNodeId: 'node-lis-8-2',
    toNodeId: 'node-lis-8-3',
    roadName: 'Campo de Ourique Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-17',
    fromNodeId: 'node-lis-9-1',
    toNodeId: 'node-lis-9-2',
    roadName: 'Avenidas Novas Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-18',
    fromNodeId: 'node-lis-9-2',
    toNodeId: 'node-lis-9-3',
    roadName: 'Avenidas Novas Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-19',
    fromNodeId: 'node-lis-10-1',
    toNodeId: 'node-lis-10-2',
    roadName: 'Santos Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lis-20',
    fromNodeId: 'node-lis-10-2',
    toNodeId: 'node-lis-10-3',
    roadName: 'Santos Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
