/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — London Central & West End
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const LONDON_BASE_COORDINATE: GeoCoordinate = {
  latitude: 51.5074,
  longitude: -0.1278,
};

export const LONDON_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-lon-1-1',
    name: 'Mayfair Sector 1 High Street',
    zone: 'Mayfair',
    location: { latitude: 51.445400, longitude: -0.179800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mayfair.',
  },
  {
    id: 'node-lon-1-2',
    name: 'Mayfair Sector 2 High Street',
    zone: 'Mayfair',
    location: { latitude: 51.448400, longitude: -0.176800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mayfair.',
  },
  {
    id: 'node-lon-1-3',
    name: 'Mayfair Sector 3 High Street',
    zone: 'Mayfair',
    location: { latitude: 51.451400, longitude: -0.173800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mayfair.',
  },
  {
    id: 'node-lon-2-1',
    name: 'Soho Sector 1 High Street',
    zone: 'Soho',
    location: { latitude: 51.457400, longitude: -0.169800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Soho.',
  },
  {
    id: 'node-lon-2-2',
    name: 'Soho Sector 2 High Street',
    zone: 'Soho',
    location: { latitude: 51.460400, longitude: -0.166800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Soho.',
  },
  {
    id: 'node-lon-2-3',
    name: 'Soho Sector 3 High Street',
    zone: 'Soho',
    location: { latitude: 51.463400, longitude: -0.163800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Soho.',
  },
  {
    id: 'node-lon-3-1',
    name: 'Covent Garden Sector 1 High Street',
    zone: 'Covent Garden',
    location: { latitude: 51.469400, longitude: -0.159800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Covent Garden.',
  },
  {
    id: 'node-lon-3-2',
    name: 'Covent Garden Sector 2 High Street',
    zone: 'Covent Garden',
    location: { latitude: 51.472400, longitude: -0.156800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Covent Garden.',
  },
  {
    id: 'node-lon-3-3',
    name: 'Covent Garden Sector 3 High Street',
    zone: 'Covent Garden',
    location: { latitude: 51.475400, longitude: -0.153800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Covent Garden.',
  },
  {
    id: 'node-lon-4-1',
    name: 'Kensington Sector 1 High Street',
    zone: 'Kensington',
    location: { latitude: 51.481400, longitude: -0.149800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kensington.',
  },
  {
    id: 'node-lon-4-2',
    name: 'Kensington Sector 2 High Street',
    zone: 'Kensington',
    location: { latitude: 51.484400, longitude: -0.146800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kensington.',
  },
  {
    id: 'node-lon-4-3',
    name: 'Kensington Sector 3 High Street',
    zone: 'Kensington',
    location: { latitude: 51.487400, longitude: -0.143800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kensington.',
  },
  {
    id: 'node-lon-5-1',
    name: 'Chelsea Sector 1 High Street',
    zone: 'Chelsea',
    location: { latitude: 51.493400, longitude: -0.139800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chelsea.',
  },
  {
    id: 'node-lon-5-2',
    name: 'Chelsea Sector 2 High Street',
    zone: 'Chelsea',
    location: { latitude: 51.496400, longitude: -0.136800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chelsea.',
  },
  {
    id: 'node-lon-5-3',
    name: 'Chelsea Sector 3 High Street',
    zone: 'Chelsea',
    location: { latitude: 51.499400, longitude: -0.133800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chelsea.',
  },
  {
    id: 'node-lon-6-1',
    name: 'Shoreditch Sector 1 High Street',
    zone: 'Shoreditch',
    location: { latitude: 51.505400, longitude: -0.129800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shoreditch.',
  },
  {
    id: 'node-lon-6-2',
    name: 'Shoreditch Sector 2 High Street',
    zone: 'Shoreditch',
    location: { latitude: 51.508400, longitude: -0.126800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shoreditch.',
  },
  {
    id: 'node-lon-6-3',
    name: 'Shoreditch Sector 3 High Street',
    zone: 'Shoreditch',
    location: { latitude: 51.511400, longitude: -0.123800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shoreditch.',
  },
  {
    id: 'node-lon-7-1',
    name: 'City of London Sector 1 High Street',
    zone: 'City of London',
    location: { latitude: 51.517400, longitude: -0.119800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in City of London.',
  },
  {
    id: 'node-lon-7-2',
    name: 'City of London Sector 2 High Street',
    zone: 'City of London',
    location: { latitude: 51.520400, longitude: -0.116800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in City of London.',
  },
  {
    id: 'node-lon-7-3',
    name: 'City of London Sector 3 High Street',
    zone: 'City of London',
    location: { latitude: 51.523400, longitude: -0.113800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in City of London.',
  },
  {
    id: 'node-lon-8-1',
    name: 'Canary Wharf Sector 1 High Street',
    zone: 'Canary Wharf',
    location: { latitude: 51.529400, longitude: -0.109800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Canary Wharf.',
  },
  {
    id: 'node-lon-8-2',
    name: 'Canary Wharf Sector 2 High Street',
    zone: 'Canary Wharf',
    location: { latitude: 51.532400, longitude: -0.106800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Canary Wharf.',
  },
  {
    id: 'node-lon-8-3',
    name: 'Canary Wharf Sector 3 High Street',
    zone: 'Canary Wharf',
    location: { latitude: 51.535400, longitude: -0.103800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Canary Wharf.',
  },
  {
    id: 'node-lon-9-1',
    name: 'Camden Town Sector 1 High Street',
    zone: 'Camden Town',
    location: { latitude: 51.541400, longitude: -0.099800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Camden Town.',
  },
  {
    id: 'node-lon-9-2',
    name: 'Camden Town Sector 2 High Street',
    zone: 'Camden Town',
    location: { latitude: 51.544400, longitude: -0.096800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Camden Town.',
  },
  {
    id: 'node-lon-9-3',
    name: 'Camden Town Sector 3 High Street',
    zone: 'Camden Town',
    location: { latitude: 51.547400, longitude: -0.093800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Camden Town.',
  },
  {
    id: 'node-lon-10-1',
    name: 'Paddington Sector 1 High Street',
    zone: 'Paddington',
    location: { latitude: 51.553400, longitude: -0.089800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Paddington.',
  },
  {
    id: 'node-lon-10-2',
    name: 'Paddington Sector 2 High Street',
    zone: 'Paddington',
    location: { latitude: 51.556400, longitude: -0.086800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Paddington.',
  },
  {
    id: 'node-lon-10-3',
    name: 'Paddington Sector 3 High Street',
    zone: 'Paddington',
    location: { latitude: 51.559400, longitude: -0.083800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Paddington.',
  },
];

export const LONDON_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-lon-1',
    fromNodeId: 'node-lon-1-1',
    toNodeId: 'node-lon-1-2',
    roadName: 'Mayfair Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-2',
    fromNodeId: 'node-lon-1-2',
    toNodeId: 'node-lon-1-3',
    roadName: 'Mayfair Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-3',
    fromNodeId: 'node-lon-2-1',
    toNodeId: 'node-lon-2-2',
    roadName: 'Soho Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-4',
    fromNodeId: 'node-lon-2-2',
    toNodeId: 'node-lon-2-3',
    roadName: 'Soho Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-5',
    fromNodeId: 'node-lon-3-1',
    toNodeId: 'node-lon-3-2',
    roadName: 'Covent Garden Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-6',
    fromNodeId: 'node-lon-3-2',
    toNodeId: 'node-lon-3-3',
    roadName: 'Covent Garden Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-7',
    fromNodeId: 'node-lon-4-1',
    toNodeId: 'node-lon-4-2',
    roadName: 'Kensington Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-8',
    fromNodeId: 'node-lon-4-2',
    toNodeId: 'node-lon-4-3',
    roadName: 'Kensington Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-9',
    fromNodeId: 'node-lon-5-1',
    toNodeId: 'node-lon-5-2',
    roadName: 'Chelsea Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-10',
    fromNodeId: 'node-lon-5-2',
    toNodeId: 'node-lon-5-3',
    roadName: 'Chelsea Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-11',
    fromNodeId: 'node-lon-6-1',
    toNodeId: 'node-lon-6-2',
    roadName: 'Shoreditch Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-12',
    fromNodeId: 'node-lon-6-2',
    toNodeId: 'node-lon-6-3',
    roadName: 'Shoreditch Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-13',
    fromNodeId: 'node-lon-7-1',
    toNodeId: 'node-lon-7-2',
    roadName: 'City of London Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-14',
    fromNodeId: 'node-lon-7-2',
    toNodeId: 'node-lon-7-3',
    roadName: 'City of London Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-15',
    fromNodeId: 'node-lon-8-1',
    toNodeId: 'node-lon-8-2',
    roadName: 'Canary Wharf Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-16',
    fromNodeId: 'node-lon-8-2',
    toNodeId: 'node-lon-8-3',
    roadName: 'Canary Wharf Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-17',
    fromNodeId: 'node-lon-9-1',
    toNodeId: 'node-lon-9-2',
    roadName: 'Camden Town Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-18',
    fromNodeId: 'node-lon-9-2',
    toNodeId: 'node-lon-9-3',
    roadName: 'Camden Town Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-19',
    fromNodeId: 'node-lon-10-1',
    toNodeId: 'node-lon-10-2',
    roadName: 'Paddington Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-lon-20',
    fromNodeId: 'node-lon-10-2',
    toNodeId: 'node-lon-10-3',
    roadName: 'Paddington Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
