/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Lucknow Nawabi Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const LUCKNOW_BASE_COORDINATE: GeoCoordinate = {
  latitude: 26.8467,
  longitude: 80.9462,
};

export const LUCKNOW_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-luc-1-1',
    name: 'Hazratganj Sector 1 High Street',
    zone: 'Hazratganj',
    location: { latitude: 26.784700, longitude: 80.894200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hazratganj.',
  },
  {
    id: 'node-luc-1-2',
    name: 'Hazratganj Sector 2 High Street',
    zone: 'Hazratganj',
    location: { latitude: 26.787700, longitude: 80.897200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hazratganj.',
  },
  {
    id: 'node-luc-1-3',
    name: 'Hazratganj Sector 3 High Street',
    zone: 'Hazratganj',
    location: { latitude: 26.790700, longitude: 80.900200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hazratganj.',
  },
  {
    id: 'node-luc-2-1',
    name: 'Gomti Nagar Sector 1 High Street',
    zone: 'Gomti Nagar',
    location: { latitude: 26.796700, longitude: 80.904200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gomti Nagar.',
  },
  {
    id: 'node-luc-2-2',
    name: 'Gomti Nagar Sector 2 High Street',
    zone: 'Gomti Nagar',
    location: { latitude: 26.799700, longitude: 80.907200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gomti Nagar.',
  },
  {
    id: 'node-luc-2-3',
    name: 'Gomti Nagar Sector 3 High Street',
    zone: 'Gomti Nagar',
    location: { latitude: 26.802700, longitude: 80.910200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gomti Nagar.',
  },
  {
    id: 'node-luc-3-1',
    name: 'Aliganj Sector 1 High Street',
    zone: 'Aliganj',
    location: { latitude: 26.808700, longitude: 80.914200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Aliganj.',
  },
  {
    id: 'node-luc-3-2',
    name: 'Aliganj Sector 2 High Street',
    zone: 'Aliganj',
    location: { latitude: 26.811700, longitude: 80.917200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Aliganj.',
  },
  {
    id: 'node-luc-3-3',
    name: 'Aliganj Sector 3 High Street',
    zone: 'Aliganj',
    location: { latitude: 26.814700, longitude: 80.920200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Aliganj.',
  },
  {
    id: 'node-luc-4-1',
    name: 'Indira Nagar Sector 1 High Street',
    zone: 'Indira Nagar',
    location: { latitude: 26.820700, longitude: 80.924200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Indira Nagar.',
  },
  {
    id: 'node-luc-4-2',
    name: 'Indira Nagar Sector 2 High Street',
    zone: 'Indira Nagar',
    location: { latitude: 26.823700, longitude: 80.927200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Indira Nagar.',
  },
  {
    id: 'node-luc-4-3',
    name: 'Indira Nagar Sector 3 High Street',
    zone: 'Indira Nagar',
    location: { latitude: 26.826700, longitude: 80.930200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Indira Nagar.',
  },
  {
    id: 'node-luc-5-1',
    name: 'Mahanagar Sector 1 High Street',
    zone: 'Mahanagar',
    location: { latitude: 26.832700, longitude: 80.934200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mahanagar.',
  },
  {
    id: 'node-luc-5-2',
    name: 'Mahanagar Sector 2 High Street',
    zone: 'Mahanagar',
    location: { latitude: 26.835700, longitude: 80.937200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mahanagar.',
  },
  {
    id: 'node-luc-5-3',
    name: 'Mahanagar Sector 3 High Street',
    zone: 'Mahanagar',
    location: { latitude: 26.838700, longitude: 80.940200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mahanagar.',
  },
  {
    id: 'node-luc-6-1',
    name: 'Jankipuram Sector 1 High Street',
    zone: 'Jankipuram',
    location: { latitude: 26.844700, longitude: 80.944200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jankipuram.',
  },
  {
    id: 'node-luc-6-2',
    name: 'Jankipuram Sector 2 High Street',
    zone: 'Jankipuram',
    location: { latitude: 26.847700, longitude: 80.947200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jankipuram.',
  },
  {
    id: 'node-luc-6-3',
    name: 'Jankipuram Sector 3 High Street',
    zone: 'Jankipuram',
    location: { latitude: 26.850700, longitude: 80.950200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jankipuram.',
  },
  {
    id: 'node-luc-7-1',
    name: 'Vikas Nagar Sector 1 High Street',
    zone: 'Vikas Nagar',
    location: { latitude: 26.856700, longitude: 80.954200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vikas Nagar.',
  },
  {
    id: 'node-luc-7-2',
    name: 'Vikas Nagar Sector 2 High Street',
    zone: 'Vikas Nagar',
    location: { latitude: 26.859700, longitude: 80.957200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vikas Nagar.',
  },
  {
    id: 'node-luc-7-3',
    name: 'Vikas Nagar Sector 3 High Street',
    zone: 'Vikas Nagar',
    location: { latitude: 26.862700, longitude: 80.960200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vikas Nagar.',
  },
  {
    id: 'node-luc-8-1',
    name: 'Aminabad Sector 1 High Street',
    zone: 'Aminabad',
    location: { latitude: 26.868700, longitude: 80.964200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Aminabad.',
  },
  {
    id: 'node-luc-8-2',
    name: 'Aminabad Sector 2 High Street',
    zone: 'Aminabad',
    location: { latitude: 26.871700, longitude: 80.967200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Aminabad.',
  },
  {
    id: 'node-luc-8-3',
    name: 'Aminabad Sector 3 High Street',
    zone: 'Aminabad',
    location: { latitude: 26.874700, longitude: 80.970200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Aminabad.',
  },
  {
    id: 'node-luc-9-1',
    name: 'Ashiyana Sector 1 High Street',
    zone: 'Ashiyana',
    location: { latitude: 26.880700, longitude: 80.974200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ashiyana.',
  },
  {
    id: 'node-luc-9-2',
    name: 'Ashiyana Sector 2 High Street',
    zone: 'Ashiyana',
    location: { latitude: 26.883700, longitude: 80.977200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ashiyana.',
  },
  {
    id: 'node-luc-9-3',
    name: 'Ashiyana Sector 3 High Street',
    zone: 'Ashiyana',
    location: { latitude: 26.886700, longitude: 80.980200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ashiyana.',
  },
  {
    id: 'node-luc-10-1',
    name: 'Sushant Golf City Sector 1 High Street',
    zone: 'Sushant Golf City',
    location: { latitude: 26.892700, longitude: 80.984200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sushant Golf City.',
  },
  {
    id: 'node-luc-10-2',
    name: 'Sushant Golf City Sector 2 High Street',
    zone: 'Sushant Golf City',
    location: { latitude: 26.895700, longitude: 80.987200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sushant Golf City.',
  },
  {
    id: 'node-luc-10-3',
    name: 'Sushant Golf City Sector 3 High Street',
    zone: 'Sushant Golf City',
    location: { latitude: 26.898700, longitude: 80.990200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sushant Golf City.',
  },
];

export const LUCKNOW_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-luc-1',
    fromNodeId: 'node-luc-1-1',
    toNodeId: 'node-luc-1-2',
    roadName: 'Hazratganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-2',
    fromNodeId: 'node-luc-1-2',
    toNodeId: 'node-luc-1-3',
    roadName: 'Hazratganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-3',
    fromNodeId: 'node-luc-2-1',
    toNodeId: 'node-luc-2-2',
    roadName: 'Gomti Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-4',
    fromNodeId: 'node-luc-2-2',
    toNodeId: 'node-luc-2-3',
    roadName: 'Gomti Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-5',
    fromNodeId: 'node-luc-3-1',
    toNodeId: 'node-luc-3-2',
    roadName: 'Aliganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-6',
    fromNodeId: 'node-luc-3-2',
    toNodeId: 'node-luc-3-3',
    roadName: 'Aliganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-7',
    fromNodeId: 'node-luc-4-1',
    toNodeId: 'node-luc-4-2',
    roadName: 'Indira Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-8',
    fromNodeId: 'node-luc-4-2',
    toNodeId: 'node-luc-4-3',
    roadName: 'Indira Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-9',
    fromNodeId: 'node-luc-5-1',
    toNodeId: 'node-luc-5-2',
    roadName: 'Mahanagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-10',
    fromNodeId: 'node-luc-5-2',
    toNodeId: 'node-luc-5-3',
    roadName: 'Mahanagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-11',
    fromNodeId: 'node-luc-6-1',
    toNodeId: 'node-luc-6-2',
    roadName: 'Jankipuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-12',
    fromNodeId: 'node-luc-6-2',
    toNodeId: 'node-luc-6-3',
    roadName: 'Jankipuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-13',
    fromNodeId: 'node-luc-7-1',
    toNodeId: 'node-luc-7-2',
    roadName: 'Vikas Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-14',
    fromNodeId: 'node-luc-7-2',
    toNodeId: 'node-luc-7-3',
    roadName: 'Vikas Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-15',
    fromNodeId: 'node-luc-8-1',
    toNodeId: 'node-luc-8-2',
    roadName: 'Aminabad Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-16',
    fromNodeId: 'node-luc-8-2',
    toNodeId: 'node-luc-8-3',
    roadName: 'Aminabad Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-17',
    fromNodeId: 'node-luc-9-1',
    toNodeId: 'node-luc-9-2',
    roadName: 'Ashiyana Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-18',
    fromNodeId: 'node-luc-9-2',
    toNodeId: 'node-luc-9-3',
    roadName: 'Ashiyana Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-19',
    fromNodeId: 'node-luc-10-1',
    toNodeId: 'node-luc-10-2',
    roadName: 'Sushant Golf City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-luc-20',
    fromNodeId: 'node-luc-10-2',
    toNodeId: 'node-luc-10-3',
    roadName: 'Sushant Golf City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
