/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Madrid Capital Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MADRID_BASE_COORDINATE: GeoCoordinate = {
  latitude: 40.4168,
  longitude: -3.7038,
};

export const MADRID_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-mad-1-1',
    name: 'Gran Vía Sector 1 High Street',
    zone: 'Gran Vía',
    location: { latitude: 40.354800, longitude: -3.755800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gran Vía.',
  },
  {
    id: 'node-mad-1-2',
    name: 'Gran Vía Sector 2 High Street',
    zone: 'Gran Vía',
    location: { latitude: 40.357800, longitude: -3.752800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gran Vía.',
  },
  {
    id: 'node-mad-1-3',
    name: 'Gran Vía Sector 3 High Street',
    zone: 'Gran Vía',
    location: { latitude: 40.360800, longitude: -3.749800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gran Vía.',
  },
  {
    id: 'node-mad-2-1',
    name: 'Salamanca Sector 1 High Street',
    zone: 'Salamanca',
    location: { latitude: 40.366800, longitude: -3.745800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Salamanca.',
  },
  {
    id: 'node-mad-2-2',
    name: 'Salamanca Sector 2 High Street',
    zone: 'Salamanca',
    location: { latitude: 40.369800, longitude: -3.742800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Salamanca.',
  },
  {
    id: 'node-mad-2-3',
    name: 'Salamanca Sector 3 High Street',
    zone: 'Salamanca',
    location: { latitude: 40.372800, longitude: -3.739800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Salamanca.',
  },
  {
    id: 'node-mad-3-1',
    name: 'Malasaña Sector 1 High Street',
    zone: 'Malasaña',
    location: { latitude: 40.378800, longitude: -3.735800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Malasaña.',
  },
  {
    id: 'node-mad-3-2',
    name: 'Malasaña Sector 2 High Street',
    zone: 'Malasaña',
    location: { latitude: 40.381800, longitude: -3.732800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Malasaña.',
  },
  {
    id: 'node-mad-3-3',
    name: 'Malasaña Sector 3 High Street',
    zone: 'Malasaña',
    location: { latitude: 40.384800, longitude: -3.729800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Malasaña.',
  },
  {
    id: 'node-mad-4-1',
    name: 'Chueca Sector 1 High Street',
    zone: 'Chueca',
    location: { latitude: 40.390800, longitude: -3.725800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chueca.',
  },
  {
    id: 'node-mad-4-2',
    name: 'Chueca Sector 2 High Street',
    zone: 'Chueca',
    location: { latitude: 40.393800, longitude: -3.722800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chueca.',
  },
  {
    id: 'node-mad-4-3',
    name: 'Chueca Sector 3 High Street',
    zone: 'Chueca',
    location: { latitude: 40.396800, longitude: -3.719800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chueca.',
  },
  {
    id: 'node-mad-5-1',
    name: 'La Latina Sector 1 High Street',
    zone: 'La Latina',
    location: { latitude: 40.402800, longitude: -3.715800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in La Latina.',
  },
  {
    id: 'node-mad-5-2',
    name: 'La Latina Sector 2 High Street',
    zone: 'La Latina',
    location: { latitude: 40.405800, longitude: -3.712800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in La Latina.',
  },
  {
    id: 'node-mad-5-3',
    name: 'La Latina Sector 3 High Street',
    zone: 'La Latina',
    location: { latitude: 40.408800, longitude: -3.709800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in La Latina.',
  },
  {
    id: 'node-mad-6-1',
    name: 'Retiro Madrid Sector 1 High Street',
    zone: 'Retiro Madrid',
    location: { latitude: 40.414800, longitude: -3.705800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Retiro Madrid.',
  },
  {
    id: 'node-mad-6-2',
    name: 'Retiro Madrid Sector 2 High Street',
    zone: 'Retiro Madrid',
    location: { latitude: 40.417800, longitude: -3.702800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Retiro Madrid.',
  },
  {
    id: 'node-mad-6-3',
    name: 'Retiro Madrid Sector 3 High Street',
    zone: 'Retiro Madrid',
    location: { latitude: 40.420800, longitude: -3.699800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Retiro Madrid.',
  },
  {
    id: 'node-mad-7-1',
    name: 'Chamberí Sector 1 High Street',
    zone: 'Chamberí',
    location: { latitude: 40.426800, longitude: -3.695800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chamberí.',
  },
  {
    id: 'node-mad-7-2',
    name: 'Chamberí Sector 2 High Street',
    zone: 'Chamberí',
    location: { latitude: 40.429800, longitude: -3.692800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chamberí.',
  },
  {
    id: 'node-mad-7-3',
    name: 'Chamberí Sector 3 High Street',
    zone: 'Chamberí',
    location: { latitude: 40.432800, longitude: -3.689800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chamberí.',
  },
  {
    id: 'node-mad-8-1',
    name: 'Moncloa Sector 1 High Street',
    zone: 'Moncloa',
    location: { latitude: 40.438800, longitude: -3.685800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Moncloa.',
  },
  {
    id: 'node-mad-8-2',
    name: 'Moncloa Sector 2 High Street',
    zone: 'Moncloa',
    location: { latitude: 40.441800, longitude: -3.682800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Moncloa.',
  },
  {
    id: 'node-mad-8-3',
    name: 'Moncloa Sector 3 High Street',
    zone: 'Moncloa',
    location: { latitude: 40.444800, longitude: -3.679800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Moncloa.',
  },
  {
    id: 'node-mad-9-1',
    name: 'Chamartín Sector 1 High Street',
    zone: 'Chamartín',
    location: { latitude: 40.450800, longitude: -3.675800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chamartín.',
  },
  {
    id: 'node-mad-9-2',
    name: 'Chamartín Sector 2 High Street',
    zone: 'Chamartín',
    location: { latitude: 40.453800, longitude: -3.672800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chamartín.',
  },
  {
    id: 'node-mad-9-3',
    name: 'Chamartín Sector 3 High Street',
    zone: 'Chamartín',
    location: { latitude: 40.456800, longitude: -3.669800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chamartín.',
  },
  {
    id: 'node-mad-10-1',
    name: 'Lavapiés Sector 1 High Street',
    zone: 'Lavapiés',
    location: { latitude: 40.462800, longitude: -3.665800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lavapiés.',
  },
  {
    id: 'node-mad-10-2',
    name: 'Lavapiés Sector 2 High Street',
    zone: 'Lavapiés',
    location: { latitude: 40.465800, longitude: -3.662800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lavapiés.',
  },
  {
    id: 'node-mad-10-3',
    name: 'Lavapiés Sector 3 High Street',
    zone: 'Lavapiés',
    location: { latitude: 40.468800, longitude: -3.659800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lavapiés.',
  },
];

export const MADRID_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-mad-1',
    fromNodeId: 'node-mad-1-1',
    toNodeId: 'node-mad-1-2',
    roadName: 'Gran Vía Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-2',
    fromNodeId: 'node-mad-1-2',
    toNodeId: 'node-mad-1-3',
    roadName: 'Gran Vía Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-3',
    fromNodeId: 'node-mad-2-1',
    toNodeId: 'node-mad-2-2',
    roadName: 'Salamanca Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-4',
    fromNodeId: 'node-mad-2-2',
    toNodeId: 'node-mad-2-3',
    roadName: 'Salamanca Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-5',
    fromNodeId: 'node-mad-3-1',
    toNodeId: 'node-mad-3-2',
    roadName: 'Malasaña Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-6',
    fromNodeId: 'node-mad-3-2',
    toNodeId: 'node-mad-3-3',
    roadName: 'Malasaña Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-7',
    fromNodeId: 'node-mad-4-1',
    toNodeId: 'node-mad-4-2',
    roadName: 'Chueca Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-8',
    fromNodeId: 'node-mad-4-2',
    toNodeId: 'node-mad-4-3',
    roadName: 'Chueca Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-9',
    fromNodeId: 'node-mad-5-1',
    toNodeId: 'node-mad-5-2',
    roadName: 'La Latina Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-10',
    fromNodeId: 'node-mad-5-2',
    toNodeId: 'node-mad-5-3',
    roadName: 'La Latina Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-11',
    fromNodeId: 'node-mad-6-1',
    toNodeId: 'node-mad-6-2',
    roadName: 'Retiro Madrid Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-12',
    fromNodeId: 'node-mad-6-2',
    toNodeId: 'node-mad-6-3',
    roadName: 'Retiro Madrid Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-13',
    fromNodeId: 'node-mad-7-1',
    toNodeId: 'node-mad-7-2',
    roadName: 'Chamberí Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-14',
    fromNodeId: 'node-mad-7-2',
    toNodeId: 'node-mad-7-3',
    roadName: 'Chamberí Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-15',
    fromNodeId: 'node-mad-8-1',
    toNodeId: 'node-mad-8-2',
    roadName: 'Moncloa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-16',
    fromNodeId: 'node-mad-8-2',
    toNodeId: 'node-mad-8-3',
    roadName: 'Moncloa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-17',
    fromNodeId: 'node-mad-9-1',
    toNodeId: 'node-mad-9-2',
    roadName: 'Chamartín Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-18',
    fromNodeId: 'node-mad-9-2',
    toNodeId: 'node-mad-9-3',
    roadName: 'Chamartín Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-19',
    fromNodeId: 'node-mad-10-1',
    toNodeId: 'node-mad-10-2',
    roadName: 'Lavapiés Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-20',
    fromNodeId: 'node-mad-10-2',
    toNodeId: 'node-mad-10-3',
    roadName: 'Lavapiés Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
