/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Madurai Temple City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MADURAI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 9.9252,
  longitude: 78.1198,
};

export const MADURAI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-mad-1-1',
    name: 'KK Nagar Sector 1 High Street',
    zone: 'KK Nagar',
    location: { latitude: 9.863200, longitude: 78.067800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in KK Nagar.',
  },
  {
    id: 'node-mad-1-2',
    name: 'KK Nagar Sector 2 High Street',
    zone: 'KK Nagar',
    location: { latitude: 9.866200, longitude: 78.070800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in KK Nagar.',
  },
  {
    id: 'node-mad-1-3',
    name: 'KK Nagar Sector 3 High Street',
    zone: 'KK Nagar',
    location: { latitude: 9.869200, longitude: 78.073800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in KK Nagar.',
  },
  {
    id: 'node-mad-2-1',
    name: 'Anna Nagar Sector 1 High Street',
    zone: 'Anna Nagar',
    location: { latitude: 9.875200, longitude: 78.077800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Anna Nagar.',
  },
  {
    id: 'node-mad-2-2',
    name: 'Anna Nagar Sector 2 High Street',
    zone: 'Anna Nagar',
    location: { latitude: 9.878200, longitude: 78.080800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Anna Nagar.',
  },
  {
    id: 'node-mad-2-3',
    name: 'Anna Nagar Sector 3 High Street',
    zone: 'Anna Nagar',
    location: { latitude: 9.881200, longitude: 78.083800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Anna Nagar.',
  },
  {
    id: 'node-mad-3-1',
    name: 'Simmakkal Sector 1 High Street',
    zone: 'Simmakkal',
    location: { latitude: 9.887200, longitude: 78.087800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Simmakkal.',
  },
  {
    id: 'node-mad-3-2',
    name: 'Simmakkal Sector 2 High Street',
    zone: 'Simmakkal',
    location: { latitude: 9.890200, longitude: 78.090800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Simmakkal.',
  },
  {
    id: 'node-mad-3-3',
    name: 'Simmakkal Sector 3 High Street',
    zone: 'Simmakkal',
    location: { latitude: 9.893200, longitude: 78.093800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Simmakkal.',
  },
  {
    id: 'node-mad-4-1',
    name: 'Goripalayam Sector 1 High Street',
    zone: 'Goripalayam',
    location: { latitude: 9.899200, longitude: 78.097800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Goripalayam.',
  },
  {
    id: 'node-mad-4-2',
    name: 'Goripalayam Sector 2 High Street',
    zone: 'Goripalayam',
    location: { latitude: 9.902200, longitude: 78.100800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Goripalayam.',
  },
  {
    id: 'node-mad-4-3',
    name: 'Goripalayam Sector 3 High Street',
    zone: 'Goripalayam',
    location: { latitude: 9.905200, longitude: 78.103800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Goripalayam.',
  },
  {
    id: 'node-mad-5-1',
    name: 'Town Hall Road Sector 1 High Street',
    zone: 'Town Hall Road',
    location: { latitude: 9.911200, longitude: 78.107800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Town Hall Road.',
  },
  {
    id: 'node-mad-5-2',
    name: 'Town Hall Road Sector 2 High Street',
    zone: 'Town Hall Road',
    location: { latitude: 9.914200, longitude: 78.110800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Town Hall Road.',
  },
  {
    id: 'node-mad-5-3',
    name: 'Town Hall Road Sector 3 High Street',
    zone: 'Town Hall Road',
    location: { latitude: 9.917200, longitude: 78.113800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Town Hall Road.',
  },
  {
    id: 'node-mad-6-1',
    name: 'Bypass Road Sector 1 High Street',
    zone: 'Bypass Road',
    location: { latitude: 9.923200, longitude: 78.117800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bypass Road.',
  },
  {
    id: 'node-mad-6-2',
    name: 'Bypass Road Sector 2 High Street',
    zone: 'Bypass Road',
    location: { latitude: 9.926200, longitude: 78.120800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bypass Road.',
  },
  {
    id: 'node-mad-6-3',
    name: 'Bypass Road Sector 3 High Street',
    zone: 'Bypass Road',
    location: { latitude: 9.929200, longitude: 78.123800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bypass Road.',
  },
  {
    id: 'node-mad-7-1',
    name: 'Mattuthavani Sector 1 High Street',
    zone: 'Mattuthavani',
    location: { latitude: 9.935200, longitude: 78.127800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mattuthavani.',
  },
  {
    id: 'node-mad-7-2',
    name: 'Mattuthavani Sector 2 High Street',
    zone: 'Mattuthavani',
    location: { latitude: 9.938200, longitude: 78.130800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mattuthavani.',
  },
  {
    id: 'node-mad-7-3',
    name: 'Mattuthavani Sector 3 High Street',
    zone: 'Mattuthavani',
    location: { latitude: 9.941200, longitude: 78.133800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mattuthavani.',
  },
  {
    id: 'node-mad-8-1',
    name: 'Tallakulam Sector 1 High Street',
    zone: 'Tallakulam',
    location: { latitude: 9.947200, longitude: 78.137800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tallakulam.',
  },
  {
    id: 'node-mad-8-2',
    name: 'Tallakulam Sector 2 High Street',
    zone: 'Tallakulam',
    location: { latitude: 9.950200, longitude: 78.140800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tallakulam.',
  },
  {
    id: 'node-mad-8-3',
    name: 'Tallakulam Sector 3 High Street',
    zone: 'Tallakulam',
    location: { latitude: 9.953200, longitude: 78.143800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tallakulam.',
  },
  {
    id: 'node-mad-9-1',
    name: 'Sellur Sector 1 High Street',
    zone: 'Sellur',
    location: { latitude: 9.959200, longitude: 78.147800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sellur.',
  },
  {
    id: 'node-mad-9-2',
    name: 'Sellur Sector 2 High Street',
    zone: 'Sellur',
    location: { latitude: 9.962200, longitude: 78.150800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sellur.',
  },
  {
    id: 'node-mad-9-3',
    name: 'Sellur Sector 3 High Street',
    zone: 'Sellur',
    location: { latitude: 9.965200, longitude: 78.153800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sellur.',
  },
  {
    id: 'node-mad-10-1',
    name: 'Villapuram Sector 1 High Street',
    zone: 'Villapuram',
    location: { latitude: 9.971200, longitude: 78.157800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Villapuram.',
  },
  {
    id: 'node-mad-10-2',
    name: 'Villapuram Sector 2 High Street',
    zone: 'Villapuram',
    location: { latitude: 9.974200, longitude: 78.160800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Villapuram.',
  },
  {
    id: 'node-mad-10-3',
    name: 'Villapuram Sector 3 High Street',
    zone: 'Villapuram',
    location: { latitude: 9.977200, longitude: 78.163800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Villapuram.',
  },
];

export const MADURAI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-mad-1',
    fromNodeId: 'node-mad-1-1',
    toNodeId: 'node-mad-1-2',
    roadName: 'KK Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-2',
    fromNodeId: 'node-mad-1-2',
    toNodeId: 'node-mad-1-3',
    roadName: 'KK Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-3',
    fromNodeId: 'node-mad-2-1',
    toNodeId: 'node-mad-2-2',
    roadName: 'Anna Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-4',
    fromNodeId: 'node-mad-2-2',
    toNodeId: 'node-mad-2-3',
    roadName: 'Anna Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-5',
    fromNodeId: 'node-mad-3-1',
    toNodeId: 'node-mad-3-2',
    roadName: 'Simmakkal Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-6',
    fromNodeId: 'node-mad-3-2',
    toNodeId: 'node-mad-3-3',
    roadName: 'Simmakkal Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-7',
    fromNodeId: 'node-mad-4-1',
    toNodeId: 'node-mad-4-2',
    roadName: 'Goripalayam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-8',
    fromNodeId: 'node-mad-4-2',
    toNodeId: 'node-mad-4-3',
    roadName: 'Goripalayam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-9',
    fromNodeId: 'node-mad-5-1',
    toNodeId: 'node-mad-5-2',
    roadName: 'Town Hall Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-10',
    fromNodeId: 'node-mad-5-2',
    toNodeId: 'node-mad-5-3',
    roadName: 'Town Hall Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-11',
    fromNodeId: 'node-mad-6-1',
    toNodeId: 'node-mad-6-2',
    roadName: 'Bypass Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-12',
    fromNodeId: 'node-mad-6-2',
    toNodeId: 'node-mad-6-3',
    roadName: 'Bypass Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-13',
    fromNodeId: 'node-mad-7-1',
    toNodeId: 'node-mad-7-2',
    roadName: 'Mattuthavani Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-14',
    fromNodeId: 'node-mad-7-2',
    toNodeId: 'node-mad-7-3',
    roadName: 'Mattuthavani Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-15',
    fromNodeId: 'node-mad-8-1',
    toNodeId: 'node-mad-8-2',
    roadName: 'Tallakulam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-16',
    fromNodeId: 'node-mad-8-2',
    toNodeId: 'node-mad-8-3',
    roadName: 'Tallakulam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-17',
    fromNodeId: 'node-mad-9-1',
    toNodeId: 'node-mad-9-2',
    roadName: 'Sellur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-18',
    fromNodeId: 'node-mad-9-2',
    toNodeId: 'node-mad-9-3',
    roadName: 'Sellur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-19',
    fromNodeId: 'node-mad-10-1',
    toNodeId: 'node-mad-10-2',
    roadName: 'Villapuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mad-20',
    fromNodeId: 'node-mad-10-2',
    toNodeId: 'node-mad-10-3',
    roadName: 'Villapuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
