/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Manama Bahrain Bay
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MANAMA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 26.2285,
  longitude: 50.586,
};

export const MANAMA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-man-1-1',
    name: 'Bahrain Bay Sector 1 High Street',
    zone: 'Bahrain Bay',
    location: { latitude: 26.166500, longitude: 50.534000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bahrain Bay.',
  },
  {
    id: 'node-man-1-2',
    name: 'Bahrain Bay Sector 2 High Street',
    zone: 'Bahrain Bay',
    location: { latitude: 26.169500, longitude: 50.537000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bahrain Bay.',
  },
  {
    id: 'node-man-1-3',
    name: 'Bahrain Bay Sector 3 High Street',
    zone: 'Bahrain Bay',
    location: { latitude: 26.172500, longitude: 50.540000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bahrain Bay.',
  },
  {
    id: 'node-man-2-1',
    name: 'Seef District Sector 1 High Street',
    zone: 'Seef District',
    location: { latitude: 26.178500, longitude: 50.544000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Seef District.',
  },
  {
    id: 'node-man-2-2',
    name: 'Seef District Sector 2 High Street',
    zone: 'Seef District',
    location: { latitude: 26.181500, longitude: 50.547000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Seef District.',
  },
  {
    id: 'node-man-2-3',
    name: 'Seef District Sector 3 High Street',
    zone: 'Seef District',
    location: { latitude: 26.184500, longitude: 50.550000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Seef District.',
  },
  {
    id: 'node-man-3-1',
    name: 'Juffair Sector 1 High Street',
    zone: 'Juffair',
    location: { latitude: 26.190500, longitude: 50.554000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Juffair.',
  },
  {
    id: 'node-man-3-2',
    name: 'Juffair Sector 2 High Street',
    zone: 'Juffair',
    location: { latitude: 26.193500, longitude: 50.557000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Juffair.',
  },
  {
    id: 'node-man-3-3',
    name: 'Juffair Sector 3 High Street',
    zone: 'Juffair',
    location: { latitude: 26.196500, longitude: 50.560000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Juffair.',
  },
  {
    id: 'node-man-4-1',
    name: 'Adliya Sector 1 High Street',
    zone: 'Adliya',
    location: { latitude: 26.202500, longitude: 50.564000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Adliya.',
  },
  {
    id: 'node-man-4-2',
    name: 'Adliya Sector 2 High Street',
    zone: 'Adliya',
    location: { latitude: 26.205500, longitude: 50.567000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Adliya.',
  },
  {
    id: 'node-man-4-3',
    name: 'Adliya Sector 3 High Street',
    zone: 'Adliya',
    location: { latitude: 26.208500, longitude: 50.570000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Adliya.',
  },
  {
    id: 'node-man-5-1',
    name: 'Diplomatic Area Manama Sector 1 High Street',
    zone: 'Diplomatic Area Manama',
    location: { latitude: 26.214500, longitude: 50.574000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Diplomatic Area Manama.',
  },
  {
    id: 'node-man-5-2',
    name: 'Diplomatic Area Manama Sector 2 High Street',
    zone: 'Diplomatic Area Manama',
    location: { latitude: 26.217500, longitude: 50.577000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Diplomatic Area Manama.',
  },
  {
    id: 'node-man-5-3',
    name: 'Diplomatic Area Manama Sector 3 High Street',
    zone: 'Diplomatic Area Manama',
    location: { latitude: 26.220500, longitude: 50.580000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Diplomatic Area Manama.',
  },
  {
    id: 'node-man-6-1',
    name: 'Amwaj Islands Sector 1 High Street',
    zone: 'Amwaj Islands',
    location: { latitude: 26.226500, longitude: 50.584000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Amwaj Islands.',
  },
  {
    id: 'node-man-6-2',
    name: 'Amwaj Islands Sector 2 High Street',
    zone: 'Amwaj Islands',
    location: { latitude: 26.229500, longitude: 50.587000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Amwaj Islands.',
  },
  {
    id: 'node-man-6-3',
    name: 'Amwaj Islands Sector 3 High Street',
    zone: 'Amwaj Islands',
    location: { latitude: 26.232500, longitude: 50.590000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Amwaj Islands.',
  },
  {
    id: 'node-man-7-1',
    name: 'Saar Sector 1 High Street',
    zone: 'Saar',
    location: { latitude: 26.238500, longitude: 50.594000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Saar.',
  },
  {
    id: 'node-man-7-2',
    name: 'Saar Sector 2 High Street',
    zone: 'Saar',
    location: { latitude: 26.241500, longitude: 50.597000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Saar.',
  },
  {
    id: 'node-man-7-3',
    name: 'Saar Sector 3 High Street',
    zone: 'Saar',
    location: { latitude: 26.244500, longitude: 50.600000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Saar.',
  },
  {
    id: 'node-man-8-1',
    name: 'Riffa Sector 1 High Street',
    zone: 'Riffa',
    location: { latitude: 26.250500, longitude: 50.604000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Riffa.',
  },
  {
    id: 'node-man-8-2',
    name: 'Riffa Sector 2 High Street',
    zone: 'Riffa',
    location: { latitude: 26.253500, longitude: 50.607000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Riffa.',
  },
  {
    id: 'node-man-8-3',
    name: 'Riffa Sector 3 High Street',
    zone: 'Riffa',
    location: { latitude: 26.256500, longitude: 50.610000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Riffa.',
  },
  {
    id: 'node-man-9-1',
    name: 'Gudaibiya Sector 1 High Street',
    zone: 'Gudaibiya',
    location: { latitude: 26.262500, longitude: 50.614000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gudaibiya.',
  },
  {
    id: 'node-man-9-2',
    name: 'Gudaibiya Sector 2 High Street',
    zone: 'Gudaibiya',
    location: { latitude: 26.265500, longitude: 50.617000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gudaibiya.',
  },
  {
    id: 'node-man-9-3',
    name: 'Gudaibiya Sector 3 High Street',
    zone: 'Gudaibiya',
    location: { latitude: 26.268500, longitude: 50.620000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gudaibiya.',
  },
  {
    id: 'node-man-10-1',
    name: 'Hoora Sector 1 High Street',
    zone: 'Hoora',
    location: { latitude: 26.274500, longitude: 50.624000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hoora.',
  },
  {
    id: 'node-man-10-2',
    name: 'Hoora Sector 2 High Street',
    zone: 'Hoora',
    location: { latitude: 26.277500, longitude: 50.627000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hoora.',
  },
  {
    id: 'node-man-10-3',
    name: 'Hoora Sector 3 High Street',
    zone: 'Hoora',
    location: { latitude: 26.280500, longitude: 50.630000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hoora.',
  },
];

export const MANAMA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-man-1',
    fromNodeId: 'node-man-1-1',
    toNodeId: 'node-man-1-2',
    roadName: 'Bahrain Bay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-2',
    fromNodeId: 'node-man-1-2',
    toNodeId: 'node-man-1-3',
    roadName: 'Bahrain Bay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-3',
    fromNodeId: 'node-man-2-1',
    toNodeId: 'node-man-2-2',
    roadName: 'Seef District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-4',
    fromNodeId: 'node-man-2-2',
    toNodeId: 'node-man-2-3',
    roadName: 'Seef District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-5',
    fromNodeId: 'node-man-3-1',
    toNodeId: 'node-man-3-2',
    roadName: 'Juffair Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-6',
    fromNodeId: 'node-man-3-2',
    toNodeId: 'node-man-3-3',
    roadName: 'Juffair Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-7',
    fromNodeId: 'node-man-4-1',
    toNodeId: 'node-man-4-2',
    roadName: 'Adliya Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-8',
    fromNodeId: 'node-man-4-2',
    toNodeId: 'node-man-4-3',
    roadName: 'Adliya Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-9',
    fromNodeId: 'node-man-5-1',
    toNodeId: 'node-man-5-2',
    roadName: 'Diplomatic Area Manama Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-10',
    fromNodeId: 'node-man-5-2',
    toNodeId: 'node-man-5-3',
    roadName: 'Diplomatic Area Manama Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-11',
    fromNodeId: 'node-man-6-1',
    toNodeId: 'node-man-6-2',
    roadName: 'Amwaj Islands Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-12',
    fromNodeId: 'node-man-6-2',
    toNodeId: 'node-man-6-3',
    roadName: 'Amwaj Islands Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-13',
    fromNodeId: 'node-man-7-1',
    toNodeId: 'node-man-7-2',
    roadName: 'Saar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-14',
    fromNodeId: 'node-man-7-2',
    toNodeId: 'node-man-7-3',
    roadName: 'Saar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-15',
    fromNodeId: 'node-man-8-1',
    toNodeId: 'node-man-8-2',
    roadName: 'Riffa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-16',
    fromNodeId: 'node-man-8-2',
    toNodeId: 'node-man-8-3',
    roadName: 'Riffa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-17',
    fromNodeId: 'node-man-9-1',
    toNodeId: 'node-man-9-2',
    roadName: 'Gudaibiya Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-18',
    fromNodeId: 'node-man-9-2',
    toNodeId: 'node-man-9-3',
    roadName: 'Gudaibiya Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-19',
    fromNodeId: 'node-man-10-1',
    toNodeId: 'node-man-10-2',
    roadName: 'Hoora Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-20',
    fromNodeId: 'node-man-10-2',
    toNodeId: 'node-man-10-3',
    roadName: 'Hoora Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
