/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Manchester Urban Core
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MANCHESTER_BASE_COORDINATE: GeoCoordinate = {
  latitude: 53.4808,
  longitude: -2.2426,
};

export const MANCHESTER_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-man-1-1',
    name: 'Northern Quarter Sector 1 High Street',
    zone: 'Northern Quarter',
    location: { latitude: 53.418800, longitude: -2.294600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Northern Quarter.',
  },
  {
    id: 'node-man-1-2',
    name: 'Northern Quarter Sector 2 High Street',
    zone: 'Northern Quarter',
    location: { latitude: 53.421800, longitude: -2.291600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Northern Quarter.',
  },
  {
    id: 'node-man-1-3',
    name: 'Northern Quarter Sector 3 High Street',
    zone: 'Northern Quarter',
    location: { latitude: 53.424800, longitude: -2.288600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Northern Quarter.',
  },
  {
    id: 'node-man-2-1',
    name: 'Deansgate Sector 1 High Street',
    zone: 'Deansgate',
    location: { latitude: 53.430800, longitude: -2.284600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Deansgate.',
  },
  {
    id: 'node-man-2-2',
    name: 'Deansgate Sector 2 High Street',
    zone: 'Deansgate',
    location: { latitude: 53.433800, longitude: -2.281600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Deansgate.',
  },
  {
    id: 'node-man-2-3',
    name: 'Deansgate Sector 3 High Street',
    zone: 'Deansgate',
    location: { latitude: 53.436800, longitude: -2.278600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Deansgate.',
  },
  {
    id: 'node-man-3-1',
    name: 'Ancoats Sector 1 High Street',
    zone: 'Ancoats',
    location: { latitude: 53.442800, longitude: -2.274600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ancoats.',
  },
  {
    id: 'node-man-3-2',
    name: 'Ancoats Sector 2 High Street',
    zone: 'Ancoats',
    location: { latitude: 53.445800, longitude: -2.271600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ancoats.',
  },
  {
    id: 'node-man-3-3',
    name: 'Ancoats Sector 3 High Street',
    zone: 'Ancoats',
    location: { latitude: 53.448800, longitude: -2.268600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ancoats.',
  },
  {
    id: 'node-man-4-1',
    name: 'Spinningfields Sector 1 High Street',
    zone: 'Spinningfields',
    location: { latitude: 53.454800, longitude: -2.264600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Spinningfields.',
  },
  {
    id: 'node-man-4-2',
    name: 'Spinningfields Sector 2 High Street',
    zone: 'Spinningfields',
    location: { latitude: 53.457800, longitude: -2.261600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Spinningfields.',
  },
  {
    id: 'node-man-4-3',
    name: 'Spinningfields Sector 3 High Street',
    zone: 'Spinningfields',
    location: { latitude: 53.460800, longitude: -2.258600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Spinningfields.',
  },
  {
    id: 'node-man-5-1',
    name: 'Castlefield Sector 1 High Street',
    zone: 'Castlefield',
    location: { latitude: 53.466800, longitude: -2.254600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Castlefield.',
  },
  {
    id: 'node-man-5-2',
    name: 'Castlefield Sector 2 High Street',
    zone: 'Castlefield',
    location: { latitude: 53.469800, longitude: -2.251600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Castlefield.',
  },
  {
    id: 'node-man-5-3',
    name: 'Castlefield Sector 3 High Street',
    zone: 'Castlefield',
    location: { latitude: 53.472800, longitude: -2.248600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Castlefield.',
  },
  {
    id: 'node-man-6-1',
    name: 'Didsbury Sector 1 High Street',
    zone: 'Didsbury',
    location: { latitude: 53.478800, longitude: -2.244600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Didsbury.',
  },
  {
    id: 'node-man-6-2',
    name: 'Didsbury Sector 2 High Street',
    zone: 'Didsbury',
    location: { latitude: 53.481800, longitude: -2.241600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Didsbury.',
  },
  {
    id: 'node-man-6-3',
    name: 'Didsbury Sector 3 High Street',
    zone: 'Didsbury',
    location: { latitude: 53.484800, longitude: -2.238600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Didsbury.',
  },
  {
    id: 'node-man-7-1',
    name: 'Chorlton Sector 1 High Street',
    zone: 'Chorlton',
    location: { latitude: 53.490800, longitude: -2.234600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chorlton.',
  },
  {
    id: 'node-man-7-2',
    name: 'Chorlton Sector 2 High Street',
    zone: 'Chorlton',
    location: { latitude: 53.493800, longitude: -2.231600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chorlton.',
  },
  {
    id: 'node-man-7-3',
    name: 'Chorlton Sector 3 High Street',
    zone: 'Chorlton',
    location: { latitude: 53.496800, longitude: -2.228600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chorlton.',
  },
  {
    id: 'node-man-8-1',
    name: 'Salford Quays Sector 1 High Street',
    zone: 'Salford Quays',
    location: { latitude: 53.502800, longitude: -2.224600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Salford Quays.',
  },
  {
    id: 'node-man-8-2',
    name: 'Salford Quays Sector 2 High Street',
    zone: 'Salford Quays',
    location: { latitude: 53.505800, longitude: -2.221600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Salford Quays.',
  },
  {
    id: 'node-man-8-3',
    name: 'Salford Quays Sector 3 High Street',
    zone: 'Salford Quays',
    location: { latitude: 53.508800, longitude: -2.218600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Salford Quays.',
  },
  {
    id: 'node-man-9-1',
    name: 'Oxford Road Sector 1 High Street',
    zone: 'Oxford Road',
    location: { latitude: 53.514800, longitude: -2.214600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Oxford Road.',
  },
  {
    id: 'node-man-9-2',
    name: 'Oxford Road Sector 2 High Street',
    zone: 'Oxford Road',
    location: { latitude: 53.517800, longitude: -2.211600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Oxford Road.',
  },
  {
    id: 'node-man-9-3',
    name: 'Oxford Road Sector 3 High Street',
    zone: 'Oxford Road',
    location: { latitude: 53.520800, longitude: -2.208600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Oxford Road.',
  },
  {
    id: 'node-man-10-1',
    name: 'Rusholme Sector 1 High Street',
    zone: 'Rusholme',
    location: { latitude: 53.526800, longitude: -2.204600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rusholme.',
  },
  {
    id: 'node-man-10-2',
    name: 'Rusholme Sector 2 High Street',
    zone: 'Rusholme',
    location: { latitude: 53.529800, longitude: -2.201600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rusholme.',
  },
  {
    id: 'node-man-10-3',
    name: 'Rusholme Sector 3 High Street',
    zone: 'Rusholme',
    location: { latitude: 53.532800, longitude: -2.198600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rusholme.',
  },
];

export const MANCHESTER_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-man-1',
    fromNodeId: 'node-man-1-1',
    toNodeId: 'node-man-1-2',
    roadName: 'Northern Quarter Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-2',
    fromNodeId: 'node-man-1-2',
    toNodeId: 'node-man-1-3',
    roadName: 'Northern Quarter Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-3',
    fromNodeId: 'node-man-2-1',
    toNodeId: 'node-man-2-2',
    roadName: 'Deansgate Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-4',
    fromNodeId: 'node-man-2-2',
    toNodeId: 'node-man-2-3',
    roadName: 'Deansgate Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-5',
    fromNodeId: 'node-man-3-1',
    toNodeId: 'node-man-3-2',
    roadName: 'Ancoats Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-6',
    fromNodeId: 'node-man-3-2',
    toNodeId: 'node-man-3-3',
    roadName: 'Ancoats Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-7',
    fromNodeId: 'node-man-4-1',
    toNodeId: 'node-man-4-2',
    roadName: 'Spinningfields Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-8',
    fromNodeId: 'node-man-4-2',
    toNodeId: 'node-man-4-3',
    roadName: 'Spinningfields Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-9',
    fromNodeId: 'node-man-5-1',
    toNodeId: 'node-man-5-2',
    roadName: 'Castlefield Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-10',
    fromNodeId: 'node-man-5-2',
    toNodeId: 'node-man-5-3',
    roadName: 'Castlefield Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-11',
    fromNodeId: 'node-man-6-1',
    toNodeId: 'node-man-6-2',
    roadName: 'Didsbury Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-12',
    fromNodeId: 'node-man-6-2',
    toNodeId: 'node-man-6-3',
    roadName: 'Didsbury Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-13',
    fromNodeId: 'node-man-7-1',
    toNodeId: 'node-man-7-2',
    roadName: 'Chorlton Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-14',
    fromNodeId: 'node-man-7-2',
    toNodeId: 'node-man-7-3',
    roadName: 'Chorlton Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-15',
    fromNodeId: 'node-man-8-1',
    toNodeId: 'node-man-8-2',
    roadName: 'Salford Quays Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-16',
    fromNodeId: 'node-man-8-2',
    toNodeId: 'node-man-8-3',
    roadName: 'Salford Quays Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-17',
    fromNodeId: 'node-man-9-1',
    toNodeId: 'node-man-9-2',
    roadName: 'Oxford Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-18',
    fromNodeId: 'node-man-9-2',
    toNodeId: 'node-man-9-3',
    roadName: 'Oxford Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-19',
    fromNodeId: 'node-man-10-1',
    toNodeId: 'node-man-10-2',
    roadName: 'Rusholme Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-20',
    fromNodeId: 'node-man-10-2',
    toNodeId: 'node-man-10-3',
    roadName: 'Rusholme Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
