/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Mangaluru Coastal Port
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MANGALORE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 12.9141,
  longitude: 74.856,
};

export const MANGALORE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-man-1-1',
    name: 'Kodialbail Sector 1 High Street',
    zone: 'Kodialbail',
    location: { latitude: 12.852100, longitude: 74.804000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kodialbail.',
  },
  {
    id: 'node-man-1-2',
    name: 'Kodialbail Sector 2 High Street',
    zone: 'Kodialbail',
    location: { latitude: 12.855100, longitude: 74.807000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kodialbail.',
  },
  {
    id: 'node-man-1-3',
    name: 'Kodialbail Sector 3 High Street',
    zone: 'Kodialbail',
    location: { latitude: 12.858100, longitude: 74.810000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kodialbail.',
  },
  {
    id: 'node-man-2-1',
    name: 'Kadri Sector 1 High Street',
    zone: 'Kadri',
    location: { latitude: 12.864100, longitude: 74.814000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kadri.',
  },
  {
    id: 'node-man-2-2',
    name: 'Kadri Sector 2 High Street',
    zone: 'Kadri',
    location: { latitude: 12.867100, longitude: 74.817000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kadri.',
  },
  {
    id: 'node-man-2-3',
    name: 'Kadri Sector 3 High Street',
    zone: 'Kadri',
    location: { latitude: 12.870100, longitude: 74.820000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kadri.',
  },
  {
    id: 'node-man-3-1',
    name: 'Bejai Sector 1 High Street',
    zone: 'Bejai',
    location: { latitude: 12.876100, longitude: 74.824000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bejai.',
  },
  {
    id: 'node-man-3-2',
    name: 'Bejai Sector 2 High Street',
    zone: 'Bejai',
    location: { latitude: 12.879100, longitude: 74.827000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bejai.',
  },
  {
    id: 'node-man-3-3',
    name: 'Bejai Sector 3 High Street',
    zone: 'Bejai',
    location: { latitude: 12.882100, longitude: 74.830000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bejai.',
  },
  {
    id: 'node-man-4-1',
    name: 'Kankanady Sector 1 High Street',
    zone: 'Kankanady',
    location: { latitude: 12.888100, longitude: 74.834000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kankanady.',
  },
  {
    id: 'node-man-4-2',
    name: 'Kankanady Sector 2 High Street',
    zone: 'Kankanady',
    location: { latitude: 12.891100, longitude: 74.837000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kankanady.',
  },
  {
    id: 'node-man-4-3',
    name: 'Kankanady Sector 3 High Street',
    zone: 'Kankanady',
    location: { latitude: 12.894100, longitude: 74.840000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kankanady.',
  },
  {
    id: 'node-man-5-1',
    name: 'Mannagudda Sector 1 High Street',
    zone: 'Mannagudda',
    location: { latitude: 12.900100, longitude: 74.844000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mannagudda.',
  },
  {
    id: 'node-man-5-2',
    name: 'Mannagudda Sector 2 High Street',
    zone: 'Mannagudda',
    location: { latitude: 12.903100, longitude: 74.847000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mannagudda.',
  },
  {
    id: 'node-man-5-3',
    name: 'Mannagudda Sector 3 High Street',
    zone: 'Mannagudda',
    location: { latitude: 12.906100, longitude: 74.850000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mannagudda.',
  },
  {
    id: 'node-man-6-1',
    name: 'Lalbagh Sector 1 High Street',
    zone: 'Lalbagh',
    location: { latitude: 12.912100, longitude: 74.854000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lalbagh.',
  },
  {
    id: 'node-man-6-2',
    name: 'Lalbagh Sector 2 High Street',
    zone: 'Lalbagh',
    location: { latitude: 12.915100, longitude: 74.857000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lalbagh.',
  },
  {
    id: 'node-man-6-3',
    name: 'Lalbagh Sector 3 High Street',
    zone: 'Lalbagh',
    location: { latitude: 12.918100, longitude: 74.860000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lalbagh.',
  },
  {
    id: 'node-man-7-1',
    name: 'Falnir Sector 1 High Street',
    zone: 'Falnir',
    location: { latitude: 12.924100, longitude: 74.864000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Falnir.',
  },
  {
    id: 'node-man-7-2',
    name: 'Falnir Sector 2 High Street',
    zone: 'Falnir',
    location: { latitude: 12.927100, longitude: 74.867000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Falnir.',
  },
  {
    id: 'node-man-7-3',
    name: 'Falnir Sector 3 High Street',
    zone: 'Falnir',
    location: { latitude: 12.930100, longitude: 74.870000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Falnir.',
  },
  {
    id: 'node-man-8-1',
    name: 'Urwa Sector 1 High Street',
    zone: 'Urwa',
    location: { latitude: 12.936100, longitude: 74.874000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Urwa.',
  },
  {
    id: 'node-man-8-2',
    name: 'Urwa Sector 2 High Street',
    zone: 'Urwa',
    location: { latitude: 12.939100, longitude: 74.877000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Urwa.',
  },
  {
    id: 'node-man-8-3',
    name: 'Urwa Sector 3 High Street',
    zone: 'Urwa',
    location: { latitude: 12.942100, longitude: 74.880000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Urwa.',
  },
  {
    id: 'node-man-9-1',
    name: 'Surathkal NITK Sector 1 High Street',
    zone: 'Surathkal NITK',
    location: { latitude: 12.948100, longitude: 74.884000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Surathkal NITK.',
  },
  {
    id: 'node-man-9-2',
    name: 'Surathkal NITK Sector 2 High Street',
    zone: 'Surathkal NITK',
    location: { latitude: 12.951100, longitude: 74.887000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Surathkal NITK.',
  },
  {
    id: 'node-man-9-3',
    name: 'Surathkal NITK Sector 3 High Street',
    zone: 'Surathkal NITK',
    location: { latitude: 12.954100, longitude: 74.890000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Surathkal NITK.',
  },
  {
    id: 'node-man-10-1',
    name: 'Pumpwell Sector 1 High Street',
    zone: 'Pumpwell',
    location: { latitude: 12.960100, longitude: 74.894000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pumpwell.',
  },
  {
    id: 'node-man-10-2',
    name: 'Pumpwell Sector 2 High Street',
    zone: 'Pumpwell',
    location: { latitude: 12.963100, longitude: 74.897000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pumpwell.',
  },
  {
    id: 'node-man-10-3',
    name: 'Pumpwell Sector 3 High Street',
    zone: 'Pumpwell',
    location: { latitude: 12.966100, longitude: 74.900000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pumpwell.',
  },
];

export const MANGALORE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-man-1',
    fromNodeId: 'node-man-1-1',
    toNodeId: 'node-man-1-2',
    roadName: 'Kodialbail Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-2',
    fromNodeId: 'node-man-1-2',
    toNodeId: 'node-man-1-3',
    roadName: 'Kodialbail Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-3',
    fromNodeId: 'node-man-2-1',
    toNodeId: 'node-man-2-2',
    roadName: 'Kadri Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-4',
    fromNodeId: 'node-man-2-2',
    toNodeId: 'node-man-2-3',
    roadName: 'Kadri Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-5',
    fromNodeId: 'node-man-3-1',
    toNodeId: 'node-man-3-2',
    roadName: 'Bejai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-6',
    fromNodeId: 'node-man-3-2',
    toNodeId: 'node-man-3-3',
    roadName: 'Bejai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-7',
    fromNodeId: 'node-man-4-1',
    toNodeId: 'node-man-4-2',
    roadName: 'Kankanady Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-8',
    fromNodeId: 'node-man-4-2',
    toNodeId: 'node-man-4-3',
    roadName: 'Kankanady Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-9',
    fromNodeId: 'node-man-5-1',
    toNodeId: 'node-man-5-2',
    roadName: 'Mannagudda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-10',
    fromNodeId: 'node-man-5-2',
    toNodeId: 'node-man-5-3',
    roadName: 'Mannagudda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-11',
    fromNodeId: 'node-man-6-1',
    toNodeId: 'node-man-6-2',
    roadName: 'Lalbagh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-12',
    fromNodeId: 'node-man-6-2',
    toNodeId: 'node-man-6-3',
    roadName: 'Lalbagh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-13',
    fromNodeId: 'node-man-7-1',
    toNodeId: 'node-man-7-2',
    roadName: 'Falnir Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-14',
    fromNodeId: 'node-man-7-2',
    toNodeId: 'node-man-7-3',
    roadName: 'Falnir Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-15',
    fromNodeId: 'node-man-8-1',
    toNodeId: 'node-man-8-2',
    roadName: 'Urwa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-16',
    fromNodeId: 'node-man-8-2',
    toNodeId: 'node-man-8-3',
    roadName: 'Urwa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-17',
    fromNodeId: 'node-man-9-1',
    toNodeId: 'node-man-9-2',
    roadName: 'Surathkal NITK Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-18',
    fromNodeId: 'node-man-9-2',
    toNodeId: 'node-man-9-3',
    roadName: 'Surathkal NITK Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-19',
    fromNodeId: 'node-man-10-1',
    toNodeId: 'node-man-10-2',
    roadName: 'Pumpwell Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-20',
    fromNodeId: 'node-man-10-2',
    toNodeId: 'node-man-10-3',
    roadName: 'Pumpwell Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
