/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Metro Manila BGC & Makati
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MANILA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 14.5995,
  longitude: 120.9842,
};

export const MANILA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-man-1-1',
    name: 'Bonifacio Global City Sector 1 High Street',
    zone: 'Bonifacio Global City',
    location: { latitude: 14.537500, longitude: 120.932200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bonifacio Global City.',
  },
  {
    id: 'node-man-1-2',
    name: 'Bonifacio Global City Sector 2 High Street',
    zone: 'Bonifacio Global City',
    location: { latitude: 14.540500, longitude: 120.935200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bonifacio Global City.',
  },
  {
    id: 'node-man-1-3',
    name: 'Bonifacio Global City Sector 3 High Street',
    zone: 'Bonifacio Global City',
    location: { latitude: 14.543500, longitude: 120.938200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bonifacio Global City.',
  },
  {
    id: 'node-man-2-1',
    name: 'Makati CBD Sector 1 High Street',
    zone: 'Makati CBD',
    location: { latitude: 14.549500, longitude: 120.942200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Makati CBD.',
  },
  {
    id: 'node-man-2-2',
    name: 'Makati CBD Sector 2 High Street',
    zone: 'Makati CBD',
    location: { latitude: 14.552500, longitude: 120.945200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Makati CBD.',
  },
  {
    id: 'node-man-2-3',
    name: 'Makati CBD Sector 3 High Street',
    zone: 'Makati CBD',
    location: { latitude: 14.555500, longitude: 120.948200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Makati CBD.',
  },
  {
    id: 'node-man-3-1',
    name: 'Ortigas Center Sector 1 High Street',
    zone: 'Ortigas Center',
    location: { latitude: 14.561500, longitude: 120.952200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ortigas Center.',
  },
  {
    id: 'node-man-3-2',
    name: 'Ortigas Center Sector 2 High Street',
    zone: 'Ortigas Center',
    location: { latitude: 14.564500, longitude: 120.955200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ortigas Center.',
  },
  {
    id: 'node-man-3-3',
    name: 'Ortigas Center Sector 3 High Street',
    zone: 'Ortigas Center',
    location: { latitude: 14.567500, longitude: 120.958200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ortigas Center.',
  },
  {
    id: 'node-man-4-1',
    name: 'Quezon City Sector 1 High Street',
    zone: 'Quezon City',
    location: { latitude: 14.573500, longitude: 120.962200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Quezon City.',
  },
  {
    id: 'node-man-4-2',
    name: 'Quezon City Sector 2 High Street',
    zone: 'Quezon City',
    location: { latitude: 14.576500, longitude: 120.965200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Quezon City.',
  },
  {
    id: 'node-man-4-3',
    name: 'Quezon City Sector 3 High Street',
    zone: 'Quezon City',
    location: { latitude: 14.579500, longitude: 120.968200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Quezon City.',
  },
  {
    id: 'node-man-5-1',
    name: 'Alabang Sector 1 High Street',
    zone: 'Alabang',
    location: { latitude: 14.585500, longitude: 120.972200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Alabang.',
  },
  {
    id: 'node-man-5-2',
    name: 'Alabang Sector 2 High Street',
    zone: 'Alabang',
    location: { latitude: 14.588500, longitude: 120.975200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Alabang.',
  },
  {
    id: 'node-man-5-3',
    name: 'Alabang Sector 3 High Street',
    zone: 'Alabang',
    location: { latitude: 14.591500, longitude: 120.978200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Alabang.',
  },
  {
    id: 'node-man-6-1',
    name: 'Greenhills Sector 1 High Street',
    zone: 'Greenhills',
    location: { latitude: 14.597500, longitude: 120.982200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Greenhills.',
  },
  {
    id: 'node-man-6-2',
    name: 'Greenhills Sector 2 High Street',
    zone: 'Greenhills',
    location: { latitude: 14.600500, longitude: 120.985200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Greenhills.',
  },
  {
    id: 'node-man-6-3',
    name: 'Greenhills Sector 3 High Street',
    zone: 'Greenhills',
    location: { latitude: 14.603500, longitude: 120.988200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Greenhills.',
  },
  {
    id: 'node-man-7-1',
    name: 'Ermita Sector 1 High Street',
    zone: 'Ermita',
    location: { latitude: 14.609500, longitude: 120.992200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ermita.',
  },
  {
    id: 'node-man-7-2',
    name: 'Ermita Sector 2 High Street',
    zone: 'Ermita',
    location: { latitude: 14.612500, longitude: 120.995200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ermita.',
  },
  {
    id: 'node-man-7-3',
    name: 'Ermita Sector 3 High Street',
    zone: 'Ermita',
    location: { latitude: 14.615500, longitude: 120.998200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ermita.',
  },
  {
    id: 'node-man-8-1',
    name: 'Taguig Sector 1 High Street',
    zone: 'Taguig',
    location: { latitude: 14.621500, longitude: 121.002200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Taguig.',
  },
  {
    id: 'node-man-8-2',
    name: 'Taguig Sector 2 High Street',
    zone: 'Taguig',
    location: { latitude: 14.624500, longitude: 121.005200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Taguig.',
  },
  {
    id: 'node-man-8-3',
    name: 'Taguig Sector 3 High Street',
    zone: 'Taguig',
    location: { latitude: 14.627500, longitude: 121.008200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Taguig.',
  },
  {
    id: 'node-man-9-1',
    name: 'Pasig Sector 1 High Street',
    zone: 'Pasig',
    location: { latitude: 14.633500, longitude: 121.012200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pasig.',
  },
  {
    id: 'node-man-9-2',
    name: 'Pasig Sector 2 High Street',
    zone: 'Pasig',
    location: { latitude: 14.636500, longitude: 121.015200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pasig.',
  },
  {
    id: 'node-man-9-3',
    name: 'Pasig Sector 3 High Street',
    zone: 'Pasig',
    location: { latitude: 14.639500, longitude: 121.018200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pasig.',
  },
  {
    id: 'node-man-10-1',
    name: 'Mandaluyong Sector 1 High Street',
    zone: 'Mandaluyong',
    location: { latitude: 14.645500, longitude: 121.022200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mandaluyong.',
  },
  {
    id: 'node-man-10-2',
    name: 'Mandaluyong Sector 2 High Street',
    zone: 'Mandaluyong',
    location: { latitude: 14.648500, longitude: 121.025200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mandaluyong.',
  },
  {
    id: 'node-man-10-3',
    name: 'Mandaluyong Sector 3 High Street',
    zone: 'Mandaluyong',
    location: { latitude: 14.651500, longitude: 121.028200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mandaluyong.',
  },
];

export const MANILA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-man-1',
    fromNodeId: 'node-man-1-1',
    toNodeId: 'node-man-1-2',
    roadName: 'Bonifacio Global City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-2',
    fromNodeId: 'node-man-1-2',
    toNodeId: 'node-man-1-3',
    roadName: 'Bonifacio Global City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-3',
    fromNodeId: 'node-man-2-1',
    toNodeId: 'node-man-2-2',
    roadName: 'Makati CBD Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-4',
    fromNodeId: 'node-man-2-2',
    toNodeId: 'node-man-2-3',
    roadName: 'Makati CBD Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-5',
    fromNodeId: 'node-man-3-1',
    toNodeId: 'node-man-3-2',
    roadName: 'Ortigas Center Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-6',
    fromNodeId: 'node-man-3-2',
    toNodeId: 'node-man-3-3',
    roadName: 'Ortigas Center Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-7',
    fromNodeId: 'node-man-4-1',
    toNodeId: 'node-man-4-2',
    roadName: 'Quezon City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-8',
    fromNodeId: 'node-man-4-2',
    toNodeId: 'node-man-4-3',
    roadName: 'Quezon City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-9',
    fromNodeId: 'node-man-5-1',
    toNodeId: 'node-man-5-2',
    roadName: 'Alabang Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-10',
    fromNodeId: 'node-man-5-2',
    toNodeId: 'node-man-5-3',
    roadName: 'Alabang Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-11',
    fromNodeId: 'node-man-6-1',
    toNodeId: 'node-man-6-2',
    roadName: 'Greenhills Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-12',
    fromNodeId: 'node-man-6-2',
    toNodeId: 'node-man-6-3',
    roadName: 'Greenhills Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-13',
    fromNodeId: 'node-man-7-1',
    toNodeId: 'node-man-7-2',
    roadName: 'Ermita Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-14',
    fromNodeId: 'node-man-7-2',
    toNodeId: 'node-man-7-3',
    roadName: 'Ermita Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-15',
    fromNodeId: 'node-man-8-1',
    toNodeId: 'node-man-8-2',
    roadName: 'Taguig Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-16',
    fromNodeId: 'node-man-8-2',
    toNodeId: 'node-man-8-3',
    roadName: 'Taguig Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-17',
    fromNodeId: 'node-man-9-1',
    toNodeId: 'node-man-9-2',
    roadName: 'Pasig Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-18',
    fromNodeId: 'node-man-9-2',
    toNodeId: 'node-man-9-3',
    roadName: 'Pasig Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-19',
    fromNodeId: 'node-man-10-1',
    toNodeId: 'node-man-10-2',
    roadName: 'Mandaluyong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-man-20',
    fromNodeId: 'node-man-10-2',
    toNodeId: 'node-man-10-3',
    roadName: 'Mandaluyong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
