/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Melbourne Yarra Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MELBOURNE_BASE_COORDINATE: GeoCoordinate = {
  latitude: -37.8136,
  longitude: 144.9631,
};

export const MELBOURNE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-mel-1-1',
    name: 'Melbourne CBD Sector 1 High Street',
    zone: 'Melbourne CBD',
    location: { latitude: -37.875600, longitude: 144.911100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Melbourne CBD.',
  },
  {
    id: 'node-mel-1-2',
    name: 'Melbourne CBD Sector 2 High Street',
    zone: 'Melbourne CBD',
    location: { latitude: -37.872600, longitude: 144.914100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Melbourne CBD.',
  },
  {
    id: 'node-mel-1-3',
    name: 'Melbourne CBD Sector 3 High Street',
    zone: 'Melbourne CBD',
    location: { latitude: -37.869600, longitude: 144.917100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Melbourne CBD.',
  },
  {
    id: 'node-mel-2-1',
    name: 'Fitzroy Sector 1 High Street',
    zone: 'Fitzroy',
    location: { latitude: -37.863600, longitude: 144.921100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fitzroy.',
  },
  {
    id: 'node-mel-2-2',
    name: 'Fitzroy Sector 2 High Street',
    zone: 'Fitzroy',
    location: { latitude: -37.860600, longitude: 144.924100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fitzroy.',
  },
  {
    id: 'node-mel-2-3',
    name: 'Fitzroy Sector 3 High Street',
    zone: 'Fitzroy',
    location: { latitude: -37.857600, longitude: 144.927100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fitzroy.',
  },
  {
    id: 'node-mel-3-1',
    name: 'South Yarra Sector 1 High Street',
    zone: 'South Yarra',
    location: { latitude: -37.851600, longitude: 144.931100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in South Yarra.',
  },
  {
    id: 'node-mel-3-2',
    name: 'South Yarra Sector 2 High Street',
    zone: 'South Yarra',
    location: { latitude: -37.848600, longitude: 144.934100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in South Yarra.',
  },
  {
    id: 'node-mel-3-3',
    name: 'South Yarra Sector 3 High Street',
    zone: 'South Yarra',
    location: { latitude: -37.845600, longitude: 144.937100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in South Yarra.',
  },
  {
    id: 'node-mel-4-1',
    name: 'St Kilda Sector 1 High Street',
    zone: 'St Kilda',
    location: { latitude: -37.839600, longitude: 144.941100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in St Kilda.',
  },
  {
    id: 'node-mel-4-2',
    name: 'St Kilda Sector 2 High Street',
    zone: 'St Kilda',
    location: { latitude: -37.836600, longitude: 144.944100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in St Kilda.',
  },
  {
    id: 'node-mel-4-3',
    name: 'St Kilda Sector 3 High Street',
    zone: 'St Kilda',
    location: { latitude: -37.833600, longitude: 144.947100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in St Kilda.',
  },
  {
    id: 'node-mel-5-1',
    name: 'Brunswick Sector 1 High Street',
    zone: 'Brunswick',
    location: { latitude: -37.827600, longitude: 144.951100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Brunswick.',
  },
  {
    id: 'node-mel-5-2',
    name: 'Brunswick Sector 2 High Street',
    zone: 'Brunswick',
    location: { latitude: -37.824600, longitude: 144.954100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Brunswick.',
  },
  {
    id: 'node-mel-5-3',
    name: 'Brunswick Sector 3 High Street',
    zone: 'Brunswick',
    location: { latitude: -37.821600, longitude: 144.957100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Brunswick.',
  },
  {
    id: 'node-mel-6-1',
    name: 'Carlton Sector 1 High Street',
    zone: 'Carlton',
    location: { latitude: -37.815600, longitude: 144.961100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Carlton.',
  },
  {
    id: 'node-mel-6-2',
    name: 'Carlton Sector 2 High Street',
    zone: 'Carlton',
    location: { latitude: -37.812600, longitude: 144.964100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Carlton.',
  },
  {
    id: 'node-mel-6-3',
    name: 'Carlton Sector 3 High Street',
    zone: 'Carlton',
    location: { latitude: -37.809600, longitude: 144.967100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Carlton.',
  },
  {
    id: 'node-mel-7-1',
    name: 'Richmond Melbourne Sector 1 High Street',
    zone: 'Richmond Melbourne',
    location: { latitude: -37.803600, longitude: 144.971100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Richmond Melbourne.',
  },
  {
    id: 'node-mel-7-2',
    name: 'Richmond Melbourne Sector 2 High Street',
    zone: 'Richmond Melbourne',
    location: { latitude: -37.800600, longitude: 144.974100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Richmond Melbourne.',
  },
  {
    id: 'node-mel-7-3',
    name: 'Richmond Melbourne Sector 3 High Street',
    zone: 'Richmond Melbourne',
    location: { latitude: -37.797600, longitude: 144.977100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Richmond Melbourne.',
  },
  {
    id: 'node-mel-8-1',
    name: 'Docklands Sector 1 High Street',
    zone: 'Docklands',
    location: { latitude: -37.791600, longitude: 144.981100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Docklands.',
  },
  {
    id: 'node-mel-8-2',
    name: 'Docklands Sector 2 High Street',
    zone: 'Docklands',
    location: { latitude: -37.788600, longitude: 144.984100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Docklands.',
  },
  {
    id: 'node-mel-8-3',
    name: 'Docklands Sector 3 High Street',
    zone: 'Docklands',
    location: { latitude: -37.785600, longitude: 144.987100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Docklands.',
  },
  {
    id: 'node-mel-9-1',
    name: 'Prahran Sector 1 High Street',
    zone: 'Prahran',
    location: { latitude: -37.779600, longitude: 144.991100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Prahran.',
  },
  {
    id: 'node-mel-9-2',
    name: 'Prahran Sector 2 High Street',
    zone: 'Prahran',
    location: { latitude: -37.776600, longitude: 144.994100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Prahran.',
  },
  {
    id: 'node-mel-9-3',
    name: 'Prahran Sector 3 High Street',
    zone: 'Prahran',
    location: { latitude: -37.773600, longitude: 144.997100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Prahran.',
  },
  {
    id: 'node-mel-10-1',
    name: 'Southbank Sector 1 High Street',
    zone: 'Southbank',
    location: { latitude: -37.767600, longitude: 145.001100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Southbank.',
  },
  {
    id: 'node-mel-10-2',
    name: 'Southbank Sector 2 High Street',
    zone: 'Southbank',
    location: { latitude: -37.764600, longitude: 145.004100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Southbank.',
  },
  {
    id: 'node-mel-10-3',
    name: 'Southbank Sector 3 High Street',
    zone: 'Southbank',
    location: { latitude: -37.761600, longitude: 145.007100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Southbank.',
  },
];

export const MELBOURNE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-mel-1',
    fromNodeId: 'node-mel-1-1',
    toNodeId: 'node-mel-1-2',
    roadName: 'Melbourne CBD Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-2',
    fromNodeId: 'node-mel-1-2',
    toNodeId: 'node-mel-1-3',
    roadName: 'Melbourne CBD Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-3',
    fromNodeId: 'node-mel-2-1',
    toNodeId: 'node-mel-2-2',
    roadName: 'Fitzroy Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-4',
    fromNodeId: 'node-mel-2-2',
    toNodeId: 'node-mel-2-3',
    roadName: 'Fitzroy Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-5',
    fromNodeId: 'node-mel-3-1',
    toNodeId: 'node-mel-3-2',
    roadName: 'South Yarra Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-6',
    fromNodeId: 'node-mel-3-2',
    toNodeId: 'node-mel-3-3',
    roadName: 'South Yarra Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-7',
    fromNodeId: 'node-mel-4-1',
    toNodeId: 'node-mel-4-2',
    roadName: 'St Kilda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-8',
    fromNodeId: 'node-mel-4-2',
    toNodeId: 'node-mel-4-3',
    roadName: 'St Kilda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-9',
    fromNodeId: 'node-mel-5-1',
    toNodeId: 'node-mel-5-2',
    roadName: 'Brunswick Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-10',
    fromNodeId: 'node-mel-5-2',
    toNodeId: 'node-mel-5-3',
    roadName: 'Brunswick Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-11',
    fromNodeId: 'node-mel-6-1',
    toNodeId: 'node-mel-6-2',
    roadName: 'Carlton Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-12',
    fromNodeId: 'node-mel-6-2',
    toNodeId: 'node-mel-6-3',
    roadName: 'Carlton Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-13',
    fromNodeId: 'node-mel-7-1',
    toNodeId: 'node-mel-7-2',
    roadName: 'Richmond Melbourne Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-14',
    fromNodeId: 'node-mel-7-2',
    toNodeId: 'node-mel-7-3',
    roadName: 'Richmond Melbourne Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-15',
    fromNodeId: 'node-mel-8-1',
    toNodeId: 'node-mel-8-2',
    roadName: 'Docklands Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-16',
    fromNodeId: 'node-mel-8-2',
    toNodeId: 'node-mel-8-3',
    roadName: 'Docklands Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-17',
    fromNodeId: 'node-mel-9-1',
    toNodeId: 'node-mel-9-2',
    roadName: 'Prahran Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-18',
    fromNodeId: 'node-mel-9-2',
    toNodeId: 'node-mel-9-3',
    roadName: 'Prahran Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-19',
    fromNodeId: 'node-mel-10-1',
    toNodeId: 'node-mel-10-2',
    roadName: 'Southbank Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mel-20',
    fromNodeId: 'node-mel-10-2',
    toNodeId: 'node-mel-10-3',
    roadName: 'Southbank Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
