/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Miami Beach & Brickell
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MIAMI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 25.7617,
  longitude: -80.1918,
};

export const MIAMI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-mia-1-1',
    name: 'Brickell Sector 1 High Street',
    zone: 'Brickell',
    location: { latitude: 25.699700, longitude: -80.243800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Brickell.',
  },
  {
    id: 'node-mia-1-2',
    name: 'Brickell Sector 2 High Street',
    zone: 'Brickell',
    location: { latitude: 25.702700, longitude: -80.240800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Brickell.',
  },
  {
    id: 'node-mia-1-3',
    name: 'Brickell Sector 3 High Street',
    zone: 'Brickell',
    location: { latitude: 25.705700, longitude: -80.237800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Brickell.',
  },
  {
    id: 'node-mia-2-1',
    name: 'South Beach Sector 1 High Street',
    zone: 'South Beach',
    location: { latitude: 25.711700, longitude: -80.233800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in South Beach.',
  },
  {
    id: 'node-mia-2-2',
    name: 'South Beach Sector 2 High Street',
    zone: 'South Beach',
    location: { latitude: 25.714700, longitude: -80.230800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in South Beach.',
  },
  {
    id: 'node-mia-2-3',
    name: 'South Beach Sector 3 High Street',
    zone: 'South Beach',
    location: { latitude: 25.717700, longitude: -80.227800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in South Beach.',
  },
  {
    id: 'node-mia-3-1',
    name: 'Wynwood Sector 1 High Street',
    zone: 'Wynwood',
    location: { latitude: 25.723700, longitude: -80.223800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wynwood.',
  },
  {
    id: 'node-mia-3-2',
    name: 'Wynwood Sector 2 High Street',
    zone: 'Wynwood',
    location: { latitude: 25.726700, longitude: -80.220800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wynwood.',
  },
  {
    id: 'node-mia-3-3',
    name: 'Wynwood Sector 3 High Street',
    zone: 'Wynwood',
    location: { latitude: 25.729700, longitude: -80.217800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wynwood.',
  },
  {
    id: 'node-mia-4-1',
    name: 'Design District Sector 1 High Street',
    zone: 'Design District',
    location: { latitude: 25.735700, longitude: -80.213800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Design District.',
  },
  {
    id: 'node-mia-4-2',
    name: 'Design District Sector 2 High Street',
    zone: 'Design District',
    location: { latitude: 25.738700, longitude: -80.210800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Design District.',
  },
  {
    id: 'node-mia-4-3',
    name: 'Design District Sector 3 High Street',
    zone: 'Design District',
    location: { latitude: 25.741700, longitude: -80.207800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Design District.',
  },
  {
    id: 'node-mia-5-1',
    name: 'Downtown Miami Sector 1 High Street',
    zone: 'Downtown Miami',
    location: { latitude: 25.747700, longitude: -80.203800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Miami.',
  },
  {
    id: 'node-mia-5-2',
    name: 'Downtown Miami Sector 2 High Street',
    zone: 'Downtown Miami',
    location: { latitude: 25.750700, longitude: -80.200800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Miami.',
  },
  {
    id: 'node-mia-5-3',
    name: 'Downtown Miami Sector 3 High Street',
    zone: 'Downtown Miami',
    location: { latitude: 25.753700, longitude: -80.197800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Miami.',
  },
  {
    id: 'node-mia-6-1',
    name: 'Coral Gables Sector 1 High Street',
    zone: 'Coral Gables',
    location: { latitude: 25.759700, longitude: -80.193800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Coral Gables.',
  },
  {
    id: 'node-mia-6-2',
    name: 'Coral Gables Sector 2 High Street',
    zone: 'Coral Gables',
    location: { latitude: 25.762700, longitude: -80.190800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Coral Gables.',
  },
  {
    id: 'node-mia-6-3',
    name: 'Coral Gables Sector 3 High Street',
    zone: 'Coral Gables',
    location: { latitude: 25.765700, longitude: -80.187800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Coral Gables.',
  },
  {
    id: 'node-mia-7-1',
    name: 'Coconut Grove Sector 1 High Street',
    zone: 'Coconut Grove',
    location: { latitude: 25.771700, longitude: -80.183800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Coconut Grove.',
  },
  {
    id: 'node-mia-7-2',
    name: 'Coconut Grove Sector 2 High Street',
    zone: 'Coconut Grove',
    location: { latitude: 25.774700, longitude: -80.180800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Coconut Grove.',
  },
  {
    id: 'node-mia-7-3',
    name: 'Coconut Grove Sector 3 High Street',
    zone: 'Coconut Grove',
    location: { latitude: 25.777700, longitude: -80.177800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Coconut Grove.',
  },
  {
    id: 'node-mia-8-1',
    name: 'Midtown Miami Sector 1 High Street',
    zone: 'Midtown Miami',
    location: { latitude: 25.783700, longitude: -80.173800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Midtown Miami.',
  },
  {
    id: 'node-mia-8-2',
    name: 'Midtown Miami Sector 2 High Street',
    zone: 'Midtown Miami',
    location: { latitude: 25.786700, longitude: -80.170800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Midtown Miami.',
  },
  {
    id: 'node-mia-8-3',
    name: 'Midtown Miami Sector 3 High Street',
    zone: 'Midtown Miami',
    location: { latitude: 25.789700, longitude: -80.167800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Midtown Miami.',
  },
  {
    id: 'node-mia-9-1',
    name: 'Little Havana Sector 1 High Street',
    zone: 'Little Havana',
    location: { latitude: 25.795700, longitude: -80.163800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Little Havana.',
  },
  {
    id: 'node-mia-9-2',
    name: 'Little Havana Sector 2 High Street',
    zone: 'Little Havana',
    location: { latitude: 25.798700, longitude: -80.160800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Little Havana.',
  },
  {
    id: 'node-mia-9-3',
    name: 'Little Havana Sector 3 High Street',
    zone: 'Little Havana',
    location: { latitude: 25.801700, longitude: -80.157800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Little Havana.',
  },
  {
    id: 'node-mia-10-1',
    name: 'Key Biscayne Sector 1 High Street',
    zone: 'Key Biscayne',
    location: { latitude: 25.807700, longitude: -80.153800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Key Biscayne.',
  },
  {
    id: 'node-mia-10-2',
    name: 'Key Biscayne Sector 2 High Street',
    zone: 'Key Biscayne',
    location: { latitude: 25.810700, longitude: -80.150800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Key Biscayne.',
  },
  {
    id: 'node-mia-10-3',
    name: 'Key Biscayne Sector 3 High Street',
    zone: 'Key Biscayne',
    location: { latitude: 25.813700, longitude: -80.147800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Key Biscayne.',
  },
];

export const MIAMI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-mia-1',
    fromNodeId: 'node-mia-1-1',
    toNodeId: 'node-mia-1-2',
    roadName: 'Brickell Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-2',
    fromNodeId: 'node-mia-1-2',
    toNodeId: 'node-mia-1-3',
    roadName: 'Brickell Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-3',
    fromNodeId: 'node-mia-2-1',
    toNodeId: 'node-mia-2-2',
    roadName: 'South Beach Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-4',
    fromNodeId: 'node-mia-2-2',
    toNodeId: 'node-mia-2-3',
    roadName: 'South Beach Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-5',
    fromNodeId: 'node-mia-3-1',
    toNodeId: 'node-mia-3-2',
    roadName: 'Wynwood Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-6',
    fromNodeId: 'node-mia-3-2',
    toNodeId: 'node-mia-3-3',
    roadName: 'Wynwood Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-7',
    fromNodeId: 'node-mia-4-1',
    toNodeId: 'node-mia-4-2',
    roadName: 'Design District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-8',
    fromNodeId: 'node-mia-4-2',
    toNodeId: 'node-mia-4-3',
    roadName: 'Design District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-9',
    fromNodeId: 'node-mia-5-1',
    toNodeId: 'node-mia-5-2',
    roadName: 'Downtown Miami Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-10',
    fromNodeId: 'node-mia-5-2',
    toNodeId: 'node-mia-5-3',
    roadName: 'Downtown Miami Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-11',
    fromNodeId: 'node-mia-6-1',
    toNodeId: 'node-mia-6-2',
    roadName: 'Coral Gables Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-12',
    fromNodeId: 'node-mia-6-2',
    toNodeId: 'node-mia-6-3',
    roadName: 'Coral Gables Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-13',
    fromNodeId: 'node-mia-7-1',
    toNodeId: 'node-mia-7-2',
    roadName: 'Coconut Grove Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-14',
    fromNodeId: 'node-mia-7-2',
    toNodeId: 'node-mia-7-3',
    roadName: 'Coconut Grove Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-15',
    fromNodeId: 'node-mia-8-1',
    toNodeId: 'node-mia-8-2',
    roadName: 'Midtown Miami Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-16',
    fromNodeId: 'node-mia-8-2',
    toNodeId: 'node-mia-8-3',
    roadName: 'Midtown Miami Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-17',
    fromNodeId: 'node-mia-9-1',
    toNodeId: 'node-mia-9-2',
    roadName: 'Little Havana Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-18',
    fromNodeId: 'node-mia-9-2',
    toNodeId: 'node-mia-9-3',
    roadName: 'Little Havana Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-19',
    fromNodeId: 'node-mia-10-1',
    toNodeId: 'node-mia-10-2',
    roadName: 'Key Biscayne Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mia-20',
    fromNodeId: 'node-mia-10-2',
    toNodeId: 'node-mia-10-3',
    roadName: 'Key Biscayne Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
