/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Milan Fashion & Financial Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MILAN_BASE_COORDINATE: GeoCoordinate = {
  latitude: 45.4642,
  longitude: 9.19,
};

export const MILAN_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-mil-1-1',
    name: 'Duomo Centro Sector 1 High Street',
    zone: 'Duomo Centro',
    location: { latitude: 45.402200, longitude: 9.138000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Duomo Centro.',
  },
  {
    id: 'node-mil-1-2',
    name: 'Duomo Centro Sector 2 High Street',
    zone: 'Duomo Centro',
    location: { latitude: 45.405200, longitude: 9.141000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Duomo Centro.',
  },
  {
    id: 'node-mil-1-3',
    name: 'Duomo Centro Sector 3 High Street',
    zone: 'Duomo Centro',
    location: { latitude: 45.408200, longitude: 9.144000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Duomo Centro.',
  },
  {
    id: 'node-mil-2-1',
    name: 'Brera Sector 1 High Street',
    zone: 'Brera',
    location: { latitude: 45.414200, longitude: 9.148000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Brera.',
  },
  {
    id: 'node-mil-2-2',
    name: 'Brera Sector 2 High Street',
    zone: 'Brera',
    location: { latitude: 45.417200, longitude: 9.151000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Brera.',
  },
  {
    id: 'node-mil-2-3',
    name: 'Brera Sector 3 High Street',
    zone: 'Brera',
    location: { latitude: 45.420200, longitude: 9.154000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Brera.',
  },
  {
    id: 'node-mil-3-1',
    name: 'Navigli Sector 1 High Street',
    zone: 'Navigli',
    location: { latitude: 45.426200, longitude: 9.158000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Navigli.',
  },
  {
    id: 'node-mil-3-2',
    name: 'Navigli Sector 2 High Street',
    zone: 'Navigli',
    location: { latitude: 45.429200, longitude: 9.161000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Navigli.',
  },
  {
    id: 'node-mil-3-3',
    name: 'Navigli Sector 3 High Street',
    zone: 'Navigli',
    location: { latitude: 45.432200, longitude: 9.164000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Navigli.',
  },
  {
    id: 'node-mil-4-1',
    name: 'Porta Nuova Sector 1 High Street',
    zone: 'Porta Nuova',
    location: { latitude: 45.438200, longitude: 9.168000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Porta Nuova.',
  },
  {
    id: 'node-mil-4-2',
    name: 'Porta Nuova Sector 2 High Street',
    zone: 'Porta Nuova',
    location: { latitude: 45.441200, longitude: 9.171000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Porta Nuova.',
  },
  {
    id: 'node-mil-4-3',
    name: 'Porta Nuova Sector 3 High Street',
    zone: 'Porta Nuova',
    location: { latitude: 45.444200, longitude: 9.174000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Porta Nuova.',
  },
  {
    id: 'node-mil-5-1',
    name: 'Isola Sector 1 High Street',
    zone: 'Isola',
    location: { latitude: 45.450200, longitude: 9.178000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Isola.',
  },
  {
    id: 'node-mil-5-2',
    name: 'Isola Sector 2 High Street',
    zone: 'Isola',
    location: { latitude: 45.453200, longitude: 9.181000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Isola.',
  },
  {
    id: 'node-mil-5-3',
    name: 'Isola Sector 3 High Street',
    zone: 'Isola',
    location: { latitude: 45.456200, longitude: 9.184000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Isola.',
  },
  {
    id: 'node-mil-6-1',
    name: 'Porta Romana Sector 1 High Street',
    zone: 'Porta Romana',
    location: { latitude: 45.462200, longitude: 9.188000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Porta Romana.',
  },
  {
    id: 'node-mil-6-2',
    name: 'Porta Romana Sector 2 High Street',
    zone: 'Porta Romana',
    location: { latitude: 45.465200, longitude: 9.191000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Porta Romana.',
  },
  {
    id: 'node-mil-6-3',
    name: 'Porta Romana Sector 3 High Street',
    zone: 'Porta Romana',
    location: { latitude: 45.468200, longitude: 9.194000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Porta Romana.',
  },
  {
    id: 'node-mil-7-1',
    name: 'San Babila Sector 1 High Street',
    zone: 'San Babila',
    location: { latitude: 45.474200, longitude: 9.198000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Babila.',
  },
  {
    id: 'node-mil-7-2',
    name: 'San Babila Sector 2 High Street',
    zone: 'San Babila',
    location: { latitude: 45.477200, longitude: 9.201000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Babila.',
  },
  {
    id: 'node-mil-7-3',
    name: 'San Babila Sector 3 High Street',
    zone: 'San Babila',
    location: { latitude: 45.480200, longitude: 9.204000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Babila.',
  },
  {
    id: 'node-mil-8-1',
    name: 'Tortona Sector 1 High Street',
    zone: 'Tortona',
    location: { latitude: 45.486200, longitude: 9.208000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tortona.',
  },
  {
    id: 'node-mil-8-2',
    name: 'Tortona Sector 2 High Street',
    zone: 'Tortona',
    location: { latitude: 45.489200, longitude: 9.211000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tortona.',
  },
  {
    id: 'node-mil-8-3',
    name: 'Tortona Sector 3 High Street',
    zone: 'Tortona',
    location: { latitude: 45.492200, longitude: 9.214000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tortona.',
  },
  {
    id: 'node-mil-9-1',
    name: 'CityLife Milan Sector 1 High Street',
    zone: 'CityLife Milan',
    location: { latitude: 45.498200, longitude: 9.218000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in CityLife Milan.',
  },
  {
    id: 'node-mil-9-2',
    name: 'CityLife Milan Sector 2 High Street',
    zone: 'CityLife Milan',
    location: { latitude: 45.501200, longitude: 9.221000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in CityLife Milan.',
  },
  {
    id: 'node-mil-9-3',
    name: 'CityLife Milan Sector 3 High Street',
    zone: 'CityLife Milan',
    location: { latitude: 45.504200, longitude: 9.224000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in CityLife Milan.',
  },
  {
    id: 'node-mil-10-1',
    name: 'Corso Sempione Sector 1 High Street',
    zone: 'Corso Sempione',
    location: { latitude: 45.510200, longitude: 9.228000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Corso Sempione.',
  },
  {
    id: 'node-mil-10-2',
    name: 'Corso Sempione Sector 2 High Street',
    zone: 'Corso Sempione',
    location: { latitude: 45.513200, longitude: 9.231000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Corso Sempione.',
  },
  {
    id: 'node-mil-10-3',
    name: 'Corso Sempione Sector 3 High Street',
    zone: 'Corso Sempione',
    location: { latitude: 45.516200, longitude: 9.234000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Corso Sempione.',
  },
];

export const MILAN_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-mil-1',
    fromNodeId: 'node-mil-1-1',
    toNodeId: 'node-mil-1-2',
    roadName: 'Duomo Centro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-2',
    fromNodeId: 'node-mil-1-2',
    toNodeId: 'node-mil-1-3',
    roadName: 'Duomo Centro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-3',
    fromNodeId: 'node-mil-2-1',
    toNodeId: 'node-mil-2-2',
    roadName: 'Brera Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-4',
    fromNodeId: 'node-mil-2-2',
    toNodeId: 'node-mil-2-3',
    roadName: 'Brera Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-5',
    fromNodeId: 'node-mil-3-1',
    toNodeId: 'node-mil-3-2',
    roadName: 'Navigli Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-6',
    fromNodeId: 'node-mil-3-2',
    toNodeId: 'node-mil-3-3',
    roadName: 'Navigli Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-7',
    fromNodeId: 'node-mil-4-1',
    toNodeId: 'node-mil-4-2',
    roadName: 'Porta Nuova Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-8',
    fromNodeId: 'node-mil-4-2',
    toNodeId: 'node-mil-4-3',
    roadName: 'Porta Nuova Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-9',
    fromNodeId: 'node-mil-5-1',
    toNodeId: 'node-mil-5-2',
    roadName: 'Isola Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-10',
    fromNodeId: 'node-mil-5-2',
    toNodeId: 'node-mil-5-3',
    roadName: 'Isola Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-11',
    fromNodeId: 'node-mil-6-1',
    toNodeId: 'node-mil-6-2',
    roadName: 'Porta Romana Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-12',
    fromNodeId: 'node-mil-6-2',
    toNodeId: 'node-mil-6-3',
    roadName: 'Porta Romana Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-13',
    fromNodeId: 'node-mil-7-1',
    toNodeId: 'node-mil-7-2',
    roadName: 'San Babila Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-14',
    fromNodeId: 'node-mil-7-2',
    toNodeId: 'node-mil-7-3',
    roadName: 'San Babila Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-15',
    fromNodeId: 'node-mil-8-1',
    toNodeId: 'node-mil-8-2',
    roadName: 'Tortona Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-16',
    fromNodeId: 'node-mil-8-2',
    toNodeId: 'node-mil-8-3',
    roadName: 'Tortona Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-17',
    fromNodeId: 'node-mil-9-1',
    toNodeId: 'node-mil-9-2',
    roadName: 'CityLife Milan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-18',
    fromNodeId: 'node-mil-9-2',
    toNodeId: 'node-mil-9-3',
    roadName: 'CityLife Milan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-19',
    fromNodeId: 'node-mil-10-1',
    toNodeId: 'node-mil-10-2',
    roadName: 'Corso Sempione Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mil-20',
    fromNodeId: 'node-mil-10-2',
    toNodeId: 'node-mil-10-3',
    roadName: 'Corso Sempione Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
