/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Minneapolis Twin Cities
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MINNEAPOLIS_BASE_COORDINATE: GeoCoordinate = {
  latitude: 44.9778,
  longitude: -93.265,
};

export const MINNEAPOLIS_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-min-1-1',
    name: 'Downtown Minneapolis Sector 1 High Street',
    zone: 'Downtown Minneapolis',
    location: { latitude: 44.915800, longitude: -93.317000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Minneapolis.',
  },
  {
    id: 'node-min-1-2',
    name: 'Downtown Minneapolis Sector 2 High Street',
    zone: 'Downtown Minneapolis',
    location: { latitude: 44.918800, longitude: -93.314000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Minneapolis.',
  },
  {
    id: 'node-min-1-3',
    name: 'Downtown Minneapolis Sector 3 High Street',
    zone: 'Downtown Minneapolis',
    location: { latitude: 44.921800, longitude: -93.311000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Minneapolis.',
  },
  {
    id: 'node-min-2-1',
    name: 'North Loop Sector 1 High Street',
    zone: 'North Loop',
    location: { latitude: 44.927800, longitude: -93.307000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in North Loop.',
  },
  {
    id: 'node-min-2-2',
    name: 'North Loop Sector 2 High Street',
    zone: 'North Loop',
    location: { latitude: 44.930800, longitude: -93.304000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in North Loop.',
  },
  {
    id: 'node-min-2-3',
    name: 'North Loop Sector 3 High Street',
    zone: 'North Loop',
    location: { latitude: 44.933800, longitude: -93.301000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in North Loop.',
  },
  {
    id: 'node-min-3-1',
    name: 'Uptown Minneapolis Sector 1 High Street',
    zone: 'Uptown Minneapolis',
    location: { latitude: 44.939800, longitude: -93.297000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Uptown Minneapolis.',
  },
  {
    id: 'node-min-3-2',
    name: 'Uptown Minneapolis Sector 2 High Street',
    zone: 'Uptown Minneapolis',
    location: { latitude: 44.942800, longitude: -93.294000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Uptown Minneapolis.',
  },
  {
    id: 'node-min-3-3',
    name: 'Uptown Minneapolis Sector 3 High Street',
    zone: 'Uptown Minneapolis',
    location: { latitude: 44.945800, longitude: -93.291000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Uptown Minneapolis.',
  },
  {
    id: 'node-min-4-1',
    name: 'Northeast Minneapolis Sector 1 High Street',
    zone: 'Northeast Minneapolis',
    location: { latitude: 44.951800, longitude: -93.287000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Northeast Minneapolis.',
  },
  {
    id: 'node-min-4-2',
    name: 'Northeast Minneapolis Sector 2 High Street',
    zone: 'Northeast Minneapolis',
    location: { latitude: 44.954800, longitude: -93.284000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Northeast Minneapolis.',
  },
  {
    id: 'node-min-4-3',
    name: 'Northeast Minneapolis Sector 3 High Street',
    zone: 'Northeast Minneapolis',
    location: { latitude: 44.957800, longitude: -93.281000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Northeast Minneapolis.',
  },
  {
    id: 'node-min-5-1',
    name: 'Dinkytown Sector 1 High Street',
    zone: 'Dinkytown',
    location: { latitude: 44.963800, longitude: -93.277000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dinkytown.',
  },
  {
    id: 'node-min-5-2',
    name: 'Dinkytown Sector 2 High Street',
    zone: 'Dinkytown',
    location: { latitude: 44.966800, longitude: -93.274000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dinkytown.',
  },
  {
    id: 'node-min-5-3',
    name: 'Dinkytown Sector 3 High Street',
    zone: 'Dinkytown',
    location: { latitude: 44.969800, longitude: -93.271000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dinkytown.',
  },
  {
    id: 'node-min-6-1',
    name: 'Loring Park Sector 1 High Street',
    zone: 'Loring Park',
    location: { latitude: 44.975800, longitude: -93.267000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Loring Park.',
  },
  {
    id: 'node-min-6-2',
    name: 'Loring Park Sector 2 High Street',
    zone: 'Loring Park',
    location: { latitude: 44.978800, longitude: -93.264000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Loring Park.',
  },
  {
    id: 'node-min-6-3',
    name: 'Loring Park Sector 3 High Street',
    zone: 'Loring Park',
    location: { latitude: 44.981800, longitude: -93.261000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Loring Park.',
  },
  {
    id: 'node-min-7-1',
    name: 'Whittier Sector 1 High Street',
    zone: 'Whittier',
    location: { latitude: 44.987800, longitude: -93.257000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Whittier.',
  },
  {
    id: 'node-min-7-2',
    name: 'Whittier Sector 2 High Street',
    zone: 'Whittier',
    location: { latitude: 44.990800, longitude: -93.254000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Whittier.',
  },
  {
    id: 'node-min-7-3',
    name: 'Whittier Sector 3 High Street',
    zone: 'Whittier',
    location: { latitude: 44.993800, longitude: -93.251000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Whittier.',
  },
  {
    id: 'node-min-8-1',
    name: 'Linden Hills Sector 1 High Street',
    zone: 'Linden Hills',
    location: { latitude: 44.999800, longitude: -93.247000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Linden Hills.',
  },
  {
    id: 'node-min-8-2',
    name: 'Linden Hills Sector 2 High Street',
    zone: 'Linden Hills',
    location: { latitude: 45.002800, longitude: -93.244000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Linden Hills.',
  },
  {
    id: 'node-min-8-3',
    name: 'Linden Hills Sector 3 High Street',
    zone: 'Linden Hills',
    location: { latitude: 45.005800, longitude: -93.241000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Linden Hills.',
  },
  {
    id: 'node-min-9-1',
    name: 'Mill District Sector 1 High Street',
    zone: 'Mill District',
    location: { latitude: 45.011800, longitude: -93.237000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mill District.',
  },
  {
    id: 'node-min-9-2',
    name: 'Mill District Sector 2 High Street',
    zone: 'Mill District',
    location: { latitude: 45.014800, longitude: -93.234000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mill District.',
  },
  {
    id: 'node-min-9-3',
    name: 'Mill District Sector 3 High Street',
    zone: 'Mill District',
    location: { latitude: 45.017800, longitude: -93.231000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mill District.',
  },
  {
    id: 'node-min-10-1',
    name: 'St. Paul Downtown Sector 1 High Street',
    zone: 'St. Paul Downtown',
    location: { latitude: 45.023800, longitude: -93.227000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in St. Paul Downtown.',
  },
  {
    id: 'node-min-10-2',
    name: 'St. Paul Downtown Sector 2 High Street',
    zone: 'St. Paul Downtown',
    location: { latitude: 45.026800, longitude: -93.224000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in St. Paul Downtown.',
  },
  {
    id: 'node-min-10-3',
    name: 'St. Paul Downtown Sector 3 High Street',
    zone: 'St. Paul Downtown',
    location: { latitude: 45.029800, longitude: -93.221000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in St. Paul Downtown.',
  },
];

export const MINNEAPOLIS_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-min-1',
    fromNodeId: 'node-min-1-1',
    toNodeId: 'node-min-1-2',
    roadName: 'Downtown Minneapolis Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-2',
    fromNodeId: 'node-min-1-2',
    toNodeId: 'node-min-1-3',
    roadName: 'Downtown Minneapolis Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-3',
    fromNodeId: 'node-min-2-1',
    toNodeId: 'node-min-2-2',
    roadName: 'North Loop Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-4',
    fromNodeId: 'node-min-2-2',
    toNodeId: 'node-min-2-3',
    roadName: 'North Loop Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-5',
    fromNodeId: 'node-min-3-1',
    toNodeId: 'node-min-3-2',
    roadName: 'Uptown Minneapolis Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-6',
    fromNodeId: 'node-min-3-2',
    toNodeId: 'node-min-3-3',
    roadName: 'Uptown Minneapolis Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-7',
    fromNodeId: 'node-min-4-1',
    toNodeId: 'node-min-4-2',
    roadName: 'Northeast Minneapolis Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-8',
    fromNodeId: 'node-min-4-2',
    toNodeId: 'node-min-4-3',
    roadName: 'Northeast Minneapolis Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-9',
    fromNodeId: 'node-min-5-1',
    toNodeId: 'node-min-5-2',
    roadName: 'Dinkytown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-10',
    fromNodeId: 'node-min-5-2',
    toNodeId: 'node-min-5-3',
    roadName: 'Dinkytown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-11',
    fromNodeId: 'node-min-6-1',
    toNodeId: 'node-min-6-2',
    roadName: 'Loring Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-12',
    fromNodeId: 'node-min-6-2',
    toNodeId: 'node-min-6-3',
    roadName: 'Loring Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-13',
    fromNodeId: 'node-min-7-1',
    toNodeId: 'node-min-7-2',
    roadName: 'Whittier Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-14',
    fromNodeId: 'node-min-7-2',
    toNodeId: 'node-min-7-3',
    roadName: 'Whittier Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-15',
    fromNodeId: 'node-min-8-1',
    toNodeId: 'node-min-8-2',
    roadName: 'Linden Hills Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-16',
    fromNodeId: 'node-min-8-2',
    toNodeId: 'node-min-8-3',
    roadName: 'Linden Hills Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-17',
    fromNodeId: 'node-min-9-1',
    toNodeId: 'node-min-9-2',
    roadName: 'Mill District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-18',
    fromNodeId: 'node-min-9-2',
    toNodeId: 'node-min-9-3',
    roadName: 'Mill District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-19',
    fromNodeId: 'node-min-10-1',
    toNodeId: 'node-min-10-2',
    roadName: 'St. Paul Downtown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-min-20',
    fromNodeId: 'node-min-10-2',
    toNodeId: 'node-min-10-3',
    roadName: 'St. Paul Downtown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
