/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Mumbai Metropolitan Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MUMBAI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 19.076,
  longitude: 72.8777,
};

export const MUMBAI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-mum-1-1',
    name: 'Bandra West Sector 1 Road',
    zone: 'Bandra West',
    location: { latitude: 19.004000, longitude: 72.825700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Bandra West commercial centers and residential communities.',
  },
  {
    id: 'node-mum-1-2',
    name: 'Bandra West Sector 2 Road',
    zone: 'Bandra West',
    location: { latitude: 19.007000, longitude: 72.828700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Bandra West commercial centers and residential communities.',
  },
  {
    id: 'node-mum-1-3',
    name: 'Bandra West Sector 3 Road',
    zone: 'Bandra West',
    location: { latitude: 19.010000, longitude: 72.831700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Bandra West commercial centers and residential communities.',
  },
  {
    id: 'node-mum-2-1',
    name: 'Juhu Sector 1 Road',
    zone: 'Juhu',
    location: { latitude: 19.019000, longitude: 72.837700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Juhu commercial centers and residential communities.',
  },
  {
    id: 'node-mum-2-2',
    name: 'Juhu Sector 2 Road',
    zone: 'Juhu',
    location: { latitude: 19.022000, longitude: 72.840700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Juhu commercial centers and residential communities.',
  },
  {
    id: 'node-mum-2-3',
    name: 'Juhu Sector 3 Road',
    zone: 'Juhu',
    location: { latitude: 19.025000, longitude: 72.843700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Juhu commercial centers and residential communities.',
  },
  {
    id: 'node-mum-3-1',
    name: 'Colaba Sector 1 Road',
    zone: 'Colaba',
    location: { latitude: 19.034000, longitude: 72.849700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Colaba commercial centers and residential communities.',
  },
  {
    id: 'node-mum-3-2',
    name: 'Colaba Sector 2 Road',
    zone: 'Colaba',
    location: { latitude: 19.037000, longitude: 72.852700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Colaba commercial centers and residential communities.',
  },
  {
    id: 'node-mum-3-3',
    name: 'Colaba Sector 3 Road',
    zone: 'Colaba',
    location: { latitude: 19.040000, longitude: 72.855700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Colaba commercial centers and residential communities.',
  },
  {
    id: 'node-mum-4-1',
    name: 'Andheri West Sector 1 Road',
    zone: 'Andheri West',
    location: { latitude: 19.049000, longitude: 72.861700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Andheri West commercial centers and residential communities.',
  },
  {
    id: 'node-mum-4-2',
    name: 'Andheri West Sector 2 Road',
    zone: 'Andheri West',
    location: { latitude: 19.052000, longitude: 72.864700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Andheri West commercial centers and residential communities.',
  },
  {
    id: 'node-mum-4-3',
    name: 'Andheri West Sector 3 Road',
    zone: 'Andheri West',
    location: { latitude: 19.055000, longitude: 72.867700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Andheri West commercial centers and residential communities.',
  },
  {
    id: 'node-mum-5-1',
    name: 'Powai Sector 1 Road',
    zone: 'Powai',
    location: { latitude: 19.064000, longitude: 72.873700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Powai commercial centers and residential communities.',
  },
  {
    id: 'node-mum-5-2',
    name: 'Powai Sector 2 Road',
    zone: 'Powai',
    location: { latitude: 19.067000, longitude: 72.876700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Powai commercial centers and residential communities.',
  },
  {
    id: 'node-mum-5-3',
    name: 'Powai Sector 3 Road',
    zone: 'Powai',
    location: { latitude: 19.070000, longitude: 72.879700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Powai commercial centers and residential communities.',
  },
  {
    id: 'node-mum-6-1',
    name: 'Lower Parel Sector 1 Road',
    zone: 'Lower Parel',
    location: { latitude: 19.079000, longitude: 72.885700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Lower Parel commercial centers and residential communities.',
  },
  {
    id: 'node-mum-6-2',
    name: 'Lower Parel Sector 2 Road',
    zone: 'Lower Parel',
    location: { latitude: 19.082000, longitude: 72.888700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Lower Parel commercial centers and residential communities.',
  },
  {
    id: 'node-mum-6-3',
    name: 'Lower Parel Sector 3 Road',
    zone: 'Lower Parel',
    location: { latitude: 19.085000, longitude: 72.891700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Lower Parel commercial centers and residential communities.',
  },
  {
    id: 'node-mum-7-1',
    name: 'Worli Sector 1 Road',
    zone: 'Worli',
    location: { latitude: 19.094000, longitude: 72.897700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Worli commercial centers and residential communities.',
  },
  {
    id: 'node-mum-7-2',
    name: 'Worli Sector 2 Road',
    zone: 'Worli',
    location: { latitude: 19.097000, longitude: 72.900700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Worli commercial centers and residential communities.',
  },
  {
    id: 'node-mum-7-3',
    name: 'Worli Sector 3 Road',
    zone: 'Worli',
    location: { latitude: 19.100000, longitude: 72.903700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Worli commercial centers and residential communities.',
  },
  {
    id: 'node-mum-8-1',
    name: 'BKC Sector 1 Road',
    zone: 'BKC',
    location: { latitude: 19.109000, longitude: 72.909700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting BKC commercial centers and residential communities.',
  },
  {
    id: 'node-mum-8-2',
    name: 'BKC Sector 2 Road',
    zone: 'BKC',
    location: { latitude: 19.112000, longitude: 72.912700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting BKC commercial centers and residential communities.',
  },
  {
    id: 'node-mum-8-3',
    name: 'BKC Sector 3 Road',
    zone: 'BKC',
    location: { latitude: 19.115000, longitude: 72.915700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting BKC commercial centers and residential communities.',
  },
  {
    id: 'node-mum-9-1',
    name: 'Goregaon East Sector 1 Road',
    zone: 'Goregaon East',
    location: { latitude: 19.124000, longitude: 72.921700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Goregaon East commercial centers and residential communities.',
  },
  {
    id: 'node-mum-9-2',
    name: 'Goregaon East Sector 2 Road',
    zone: 'Goregaon East',
    location: { latitude: 19.127000, longitude: 72.924700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Goregaon East commercial centers and residential communities.',
  },
  {
    id: 'node-mum-9-3',
    name: 'Goregaon East Sector 3 Road',
    zone: 'Goregaon East',
    location: { latitude: 19.130000, longitude: 72.927700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Goregaon East commercial centers and residential communities.',
  },
  {
    id: 'node-mum-10-1',
    name: 'Thane West Sector 1 Road',
    zone: 'Thane West',
    location: { latitude: 19.139000, longitude: 72.933700 },
    landmarkType: 'RESIDENTIAL',
    description: 'High-density transit corridor connecting Thane West commercial centers and residential communities.',
  },
  {
    id: 'node-mum-10-2',
    name: 'Thane West Sector 2 Road',
    zone: 'Thane West',
    location: { latitude: 19.142000, longitude: 72.936700 },
    landmarkType: 'TECH_PARK',
    description: 'High-density transit corridor connecting Thane West commercial centers and residential communities.',
  },
  {
    id: 'node-mum-10-3',
    name: 'Thane West Sector 3 Road',
    zone: 'Thane West',
    location: { latitude: 19.145000, longitude: 72.939700 },
    landmarkType: 'INTERSECTION',
    description: 'High-density transit corridor connecting Thane West commercial centers and residential communities.',
  },
];

export const MUMBAI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-mum-1',
    fromNodeId: 'node-mum-1-1',
    toNodeId: 'node-mum-1-2',
    roadName: 'Bandra West Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-2',
    fromNodeId: 'node-mum-1-2',
    toNodeId: 'node-mum-1-3',
    roadName: 'Bandra West Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-3',
    fromNodeId: 'node-mum-2-1',
    toNodeId: 'node-mum-2-2',
    roadName: 'Juhu Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-4',
    fromNodeId: 'node-mum-2-2',
    toNodeId: 'node-mum-2-3',
    roadName: 'Juhu Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-5',
    fromNodeId: 'node-mum-3-1',
    toNodeId: 'node-mum-3-2',
    roadName: 'Colaba Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-6',
    fromNodeId: 'node-mum-3-2',
    toNodeId: 'node-mum-3-3',
    roadName: 'Colaba Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-7',
    fromNodeId: 'node-mum-4-1',
    toNodeId: 'node-mum-4-2',
    roadName: 'Andheri West Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-8',
    fromNodeId: 'node-mum-4-2',
    toNodeId: 'node-mum-4-3',
    roadName: 'Andheri West Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-9',
    fromNodeId: 'node-mum-5-1',
    toNodeId: 'node-mum-5-2',
    roadName: 'Powai Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-10',
    fromNodeId: 'node-mum-5-2',
    toNodeId: 'node-mum-5-3',
    roadName: 'Powai Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-11',
    fromNodeId: 'node-mum-6-1',
    toNodeId: 'node-mum-6-2',
    roadName: 'Lower Parel Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-12',
    fromNodeId: 'node-mum-6-2',
    toNodeId: 'node-mum-6-3',
    roadName: 'Lower Parel Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-13',
    fromNodeId: 'node-mum-7-1',
    toNodeId: 'node-mum-7-2',
    roadName: 'Worli Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-14',
    fromNodeId: 'node-mum-7-2',
    toNodeId: 'node-mum-7-3',
    roadName: 'Worli Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-15',
    fromNodeId: 'node-mum-8-1',
    toNodeId: 'node-mum-8-2',
    roadName: 'BKC Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-16',
    fromNodeId: 'node-mum-8-2',
    toNodeId: 'node-mum-8-3',
    roadName: 'BKC Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-17',
    fromNodeId: 'node-mum-9-1',
    toNodeId: 'node-mum-9-2',
    roadName: 'Goregaon East Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-18',
    fromNodeId: 'node-mum-9-2',
    toNodeId: 'node-mum-9-3',
    roadName: 'Goregaon East Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-19',
    fromNodeId: 'node-mum-10-1',
    toNodeId: 'node-mum-10-2',
    roadName: 'Thane West Main Avenue 1',
    distanceMeters: 550,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mum-20',
    fromNodeId: 'node-mum-10-2',
    toNodeId: 'node-mum-10-3',
    roadName: 'Thane West Main Avenue 2',
    distanceMeters: 700,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.4,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
