/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Munich Bavarian Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MUNICH_BASE_COORDINATE: GeoCoordinate = {
  latitude: 48.1351,
  longitude: 11.582,
};

export const MUNICH_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-mun-1-1',
    name: 'Altstadt Munich Sector 1 High Street',
    zone: 'Altstadt Munich',
    location: { latitude: 48.073100, longitude: 11.530000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Altstadt Munich.',
  },
  {
    id: 'node-mun-1-2',
    name: 'Altstadt Munich Sector 2 High Street',
    zone: 'Altstadt Munich',
    location: { latitude: 48.076100, longitude: 11.533000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Altstadt Munich.',
  },
  {
    id: 'node-mun-1-3',
    name: 'Altstadt Munich Sector 3 High Street',
    zone: 'Altstadt Munich',
    location: { latitude: 48.079100, longitude: 11.536000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Altstadt Munich.',
  },
  {
    id: 'node-mun-2-1',
    name: 'Schwabing Sector 1 High Street',
    zone: 'Schwabing',
    location: { latitude: 48.085100, longitude: 11.540000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Schwabing.',
  },
  {
    id: 'node-mun-2-2',
    name: 'Schwabing Sector 2 High Street',
    zone: 'Schwabing',
    location: { latitude: 48.088100, longitude: 11.543000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Schwabing.',
  },
  {
    id: 'node-mun-2-3',
    name: 'Schwabing Sector 3 High Street',
    zone: 'Schwabing',
    location: { latitude: 48.091100, longitude: 11.546000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Schwabing.',
  },
  {
    id: 'node-mun-3-1',
    name: 'Maxvorstadt Sector 1 High Street',
    zone: 'Maxvorstadt',
    location: { latitude: 48.097100, longitude: 11.550000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Maxvorstadt.',
  },
  {
    id: 'node-mun-3-2',
    name: 'Maxvorstadt Sector 2 High Street',
    zone: 'Maxvorstadt',
    location: { latitude: 48.100100, longitude: 11.553000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Maxvorstadt.',
  },
  {
    id: 'node-mun-3-3',
    name: 'Maxvorstadt Sector 3 High Street',
    zone: 'Maxvorstadt',
    location: { latitude: 48.103100, longitude: 11.556000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Maxvorstadt.',
  },
  {
    id: 'node-mun-4-1',
    name: 'Ludwigsvorstadt Sector 1 High Street',
    zone: 'Ludwigsvorstadt',
    location: { latitude: 48.109100, longitude: 11.560000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ludwigsvorstadt.',
  },
  {
    id: 'node-mun-4-2',
    name: 'Ludwigsvorstadt Sector 2 High Street',
    zone: 'Ludwigsvorstadt',
    location: { latitude: 48.112100, longitude: 11.563000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ludwigsvorstadt.',
  },
  {
    id: 'node-mun-4-3',
    name: 'Ludwigsvorstadt Sector 3 High Street',
    zone: 'Ludwigsvorstadt',
    location: { latitude: 48.115100, longitude: 11.566000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ludwigsvorstadt.',
  },
  {
    id: 'node-mun-5-1',
    name: 'Glockenbachviertel Sector 1 High Street',
    zone: 'Glockenbachviertel',
    location: { latitude: 48.121100, longitude: 11.570000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Glockenbachviertel.',
  },
  {
    id: 'node-mun-5-2',
    name: 'Glockenbachviertel Sector 2 High Street',
    zone: 'Glockenbachviertel',
    location: { latitude: 48.124100, longitude: 11.573000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Glockenbachviertel.',
  },
  {
    id: 'node-mun-5-3',
    name: 'Glockenbachviertel Sector 3 High Street',
    zone: 'Glockenbachviertel',
    location: { latitude: 48.127100, longitude: 11.576000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Glockenbachviertel.',
  },
  {
    id: 'node-mun-6-1',
    name: 'Haidhausen Sector 1 High Street',
    zone: 'Haidhausen',
    location: { latitude: 48.133100, longitude: 11.580000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Haidhausen.',
  },
  {
    id: 'node-mun-6-2',
    name: 'Haidhausen Sector 2 High Street',
    zone: 'Haidhausen',
    location: { latitude: 48.136100, longitude: 11.583000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Haidhausen.',
  },
  {
    id: 'node-mun-6-3',
    name: 'Haidhausen Sector 3 High Street',
    zone: 'Haidhausen',
    location: { latitude: 48.139100, longitude: 11.586000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Haidhausen.',
  },
  {
    id: 'node-mun-7-1',
    name: 'Bogenhausen Sector 1 High Street',
    zone: 'Bogenhausen',
    location: { latitude: 48.145100, longitude: 11.590000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bogenhausen.',
  },
  {
    id: 'node-mun-7-2',
    name: 'Bogenhausen Sector 2 High Street',
    zone: 'Bogenhausen',
    location: { latitude: 48.148100, longitude: 11.593000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bogenhausen.',
  },
  {
    id: 'node-mun-7-3',
    name: 'Bogenhausen Sector 3 High Street',
    zone: 'Bogenhausen',
    location: { latitude: 48.151100, longitude: 11.596000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bogenhausen.',
  },
  {
    id: 'node-mun-8-1',
    name: 'Sendling Sector 1 High Street',
    zone: 'Sendling',
    location: { latitude: 48.157100, longitude: 11.600000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sendling.',
  },
  {
    id: 'node-mun-8-2',
    name: 'Sendling Sector 2 High Street',
    zone: 'Sendling',
    location: { latitude: 48.160100, longitude: 11.603000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sendling.',
  },
  {
    id: 'node-mun-8-3',
    name: 'Sendling Sector 3 High Street',
    zone: 'Sendling',
    location: { latitude: 48.163100, longitude: 11.606000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sendling.',
  },
  {
    id: 'node-mun-9-1',
    name: 'Neuhausen Sector 1 High Street',
    zone: 'Neuhausen',
    location: { latitude: 48.169100, longitude: 11.610000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Neuhausen.',
  },
  {
    id: 'node-mun-9-2',
    name: 'Neuhausen Sector 2 High Street',
    zone: 'Neuhausen',
    location: { latitude: 48.172100, longitude: 11.613000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Neuhausen.',
  },
  {
    id: 'node-mun-9-3',
    name: 'Neuhausen Sector 3 High Street',
    zone: 'Neuhausen',
    location: { latitude: 48.175100, longitude: 11.616000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Neuhausen.',
  },
  {
    id: 'node-mun-10-1',
    name: 'Nymphenburg Sector 1 High Street',
    zone: 'Nymphenburg',
    location: { latitude: 48.181100, longitude: 11.620000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nymphenburg.',
  },
  {
    id: 'node-mun-10-2',
    name: 'Nymphenburg Sector 2 High Street',
    zone: 'Nymphenburg',
    location: { latitude: 48.184100, longitude: 11.623000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nymphenburg.',
  },
  {
    id: 'node-mun-10-3',
    name: 'Nymphenburg Sector 3 High Street',
    zone: 'Nymphenburg',
    location: { latitude: 48.187100, longitude: 11.626000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nymphenburg.',
  },
];

export const MUNICH_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-mun-1',
    fromNodeId: 'node-mun-1-1',
    toNodeId: 'node-mun-1-2',
    roadName: 'Altstadt Munich Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-2',
    fromNodeId: 'node-mun-1-2',
    toNodeId: 'node-mun-1-3',
    roadName: 'Altstadt Munich Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-3',
    fromNodeId: 'node-mun-2-1',
    toNodeId: 'node-mun-2-2',
    roadName: 'Schwabing Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-4',
    fromNodeId: 'node-mun-2-2',
    toNodeId: 'node-mun-2-3',
    roadName: 'Schwabing Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-5',
    fromNodeId: 'node-mun-3-1',
    toNodeId: 'node-mun-3-2',
    roadName: 'Maxvorstadt Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-6',
    fromNodeId: 'node-mun-3-2',
    toNodeId: 'node-mun-3-3',
    roadName: 'Maxvorstadt Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-7',
    fromNodeId: 'node-mun-4-1',
    toNodeId: 'node-mun-4-2',
    roadName: 'Ludwigsvorstadt Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-8',
    fromNodeId: 'node-mun-4-2',
    toNodeId: 'node-mun-4-3',
    roadName: 'Ludwigsvorstadt Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-9',
    fromNodeId: 'node-mun-5-1',
    toNodeId: 'node-mun-5-2',
    roadName: 'Glockenbachviertel Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-10',
    fromNodeId: 'node-mun-5-2',
    toNodeId: 'node-mun-5-3',
    roadName: 'Glockenbachviertel Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-11',
    fromNodeId: 'node-mun-6-1',
    toNodeId: 'node-mun-6-2',
    roadName: 'Haidhausen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-12',
    fromNodeId: 'node-mun-6-2',
    toNodeId: 'node-mun-6-3',
    roadName: 'Haidhausen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-13',
    fromNodeId: 'node-mun-7-1',
    toNodeId: 'node-mun-7-2',
    roadName: 'Bogenhausen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-14',
    fromNodeId: 'node-mun-7-2',
    toNodeId: 'node-mun-7-3',
    roadName: 'Bogenhausen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-15',
    fromNodeId: 'node-mun-8-1',
    toNodeId: 'node-mun-8-2',
    roadName: 'Sendling Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-16',
    fromNodeId: 'node-mun-8-2',
    toNodeId: 'node-mun-8-3',
    roadName: 'Sendling Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-17',
    fromNodeId: 'node-mun-9-1',
    toNodeId: 'node-mun-9-2',
    roadName: 'Neuhausen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-18',
    fromNodeId: 'node-mun-9-2',
    toNodeId: 'node-mun-9-3',
    roadName: 'Neuhausen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-19',
    fromNodeId: 'node-mun-10-1',
    toNodeId: 'node-mun-10-2',
    roadName: 'Nymphenburg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mun-20',
    fromNodeId: 'node-mun-10-2',
    toNodeId: 'node-mun-10-3',
    roadName: 'Nymphenburg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
