/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Muscat Sea of Oman Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MUSCAT_BASE_COORDINATE: GeoCoordinate = {
  latitude: 23.588,
  longitude: 58.3829,
};

export const MUSCAT_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-mus-1-1',
    name: 'Al Mouj Muscat Sector 1 High Street',
    zone: 'Al Mouj Muscat',
    location: { latitude: 23.526000, longitude: 58.330900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Mouj Muscat.',
  },
  {
    id: 'node-mus-1-2',
    name: 'Al Mouj Muscat Sector 2 High Street',
    zone: 'Al Mouj Muscat',
    location: { latitude: 23.529000, longitude: 58.333900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Mouj Muscat.',
  },
  {
    id: 'node-mus-1-3',
    name: 'Al Mouj Muscat Sector 3 High Street',
    zone: 'Al Mouj Muscat',
    location: { latitude: 23.532000, longitude: 58.336900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Mouj Muscat.',
  },
  {
    id: 'node-mus-2-1',
    name: 'Madinat Sultan Qaboos Sector 1 High Street',
    zone: 'Madinat Sultan Qaboos',
    location: { latitude: 23.538000, longitude: 58.340900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Madinat Sultan Qaboos.',
  },
  {
    id: 'node-mus-2-2',
    name: 'Madinat Sultan Qaboos Sector 2 High Street',
    zone: 'Madinat Sultan Qaboos',
    location: { latitude: 23.541000, longitude: 58.343900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Madinat Sultan Qaboos.',
  },
  {
    id: 'node-mus-2-3',
    name: 'Madinat Sultan Qaboos Sector 3 High Street',
    zone: 'Madinat Sultan Qaboos',
    location: { latitude: 23.544000, longitude: 58.346900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Madinat Sultan Qaboos.',
  },
  {
    id: 'node-mus-3-1',
    name: 'Shatti Al Qurum Sector 1 High Street',
    zone: 'Shatti Al Qurum',
    location: { latitude: 23.550000, longitude: 58.350900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shatti Al Qurum.',
  },
  {
    id: 'node-mus-3-2',
    name: 'Shatti Al Qurum Sector 2 High Street',
    zone: 'Shatti Al Qurum',
    location: { latitude: 23.553000, longitude: 58.353900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shatti Al Qurum.',
  },
  {
    id: 'node-mus-3-3',
    name: 'Shatti Al Qurum Sector 3 High Street',
    zone: 'Shatti Al Qurum',
    location: { latitude: 23.556000, longitude: 58.356900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shatti Al Qurum.',
  },
  {
    id: 'node-mus-4-1',
    name: 'Qurum Sector 1 High Street',
    zone: 'Qurum',
    location: { latitude: 23.562000, longitude: 58.360900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Qurum.',
  },
  {
    id: 'node-mus-4-2',
    name: 'Qurum Sector 2 High Street',
    zone: 'Qurum',
    location: { latitude: 23.565000, longitude: 58.363900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Qurum.',
  },
  {
    id: 'node-mus-4-3',
    name: 'Qurum Sector 3 High Street',
    zone: 'Qurum',
    location: { latitude: 23.568000, longitude: 58.366900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Qurum.',
  },
  {
    id: 'node-mus-5-1',
    name: 'Muttrah Sector 1 High Street',
    zone: 'Muttrah',
    location: { latitude: 23.574000, longitude: 58.370900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Muttrah.',
  },
  {
    id: 'node-mus-5-2',
    name: 'Muttrah Sector 2 High Street',
    zone: 'Muttrah',
    location: { latitude: 23.577000, longitude: 58.373900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Muttrah.',
  },
  {
    id: 'node-mus-5-3',
    name: 'Muttrah Sector 3 High Street',
    zone: 'Muttrah',
    location: { latitude: 23.580000, longitude: 58.376900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Muttrah.',
  },
  {
    id: 'node-mus-6-1',
    name: 'Al Khuwair Sector 1 High Street',
    zone: 'Al Khuwair',
    location: { latitude: 23.586000, longitude: 58.380900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Khuwair.',
  },
  {
    id: 'node-mus-6-2',
    name: 'Al Khuwair Sector 2 High Street',
    zone: 'Al Khuwair',
    location: { latitude: 23.589000, longitude: 58.383900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Khuwair.',
  },
  {
    id: 'node-mus-6-3',
    name: 'Al Khuwair Sector 3 High Street',
    zone: 'Al Khuwair',
    location: { latitude: 23.592000, longitude: 58.386900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Khuwair.',
  },
  {
    id: 'node-mus-7-1',
    name: 'Bausher Sector 1 High Street',
    zone: 'Bausher',
    location: { latitude: 23.598000, longitude: 58.390900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bausher.',
  },
  {
    id: 'node-mus-7-2',
    name: 'Bausher Sector 2 High Street',
    zone: 'Bausher',
    location: { latitude: 23.601000, longitude: 58.393900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bausher.',
  },
  {
    id: 'node-mus-7-3',
    name: 'Bausher Sector 3 High Street',
    zone: 'Bausher',
    location: { latitude: 23.604000, longitude: 58.396900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bausher.',
  },
  {
    id: 'node-mus-8-1',
    name: 'Azaiba Sector 1 High Street',
    zone: 'Azaiba',
    location: { latitude: 23.610000, longitude: 58.400900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Azaiba.',
  },
  {
    id: 'node-mus-8-2',
    name: 'Azaiba Sector 2 High Street',
    zone: 'Azaiba',
    location: { latitude: 23.613000, longitude: 58.403900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Azaiba.',
  },
  {
    id: 'node-mus-8-3',
    name: 'Azaiba Sector 3 High Street',
    zone: 'Azaiba',
    location: { latitude: 23.616000, longitude: 58.406900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Azaiba.',
  },
  {
    id: 'node-mus-9-1',
    name: 'Ruwi Sector 1 High Street',
    zone: 'Ruwi',
    location: { latitude: 23.622000, longitude: 58.410900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ruwi.',
  },
  {
    id: 'node-mus-9-2',
    name: 'Ruwi Sector 2 High Street',
    zone: 'Ruwi',
    location: { latitude: 23.625000, longitude: 58.413900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ruwi.',
  },
  {
    id: 'node-mus-9-3',
    name: 'Ruwi Sector 3 High Street',
    zone: 'Ruwi',
    location: { latitude: 23.628000, longitude: 58.416900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ruwi.',
  },
  {
    id: 'node-mus-10-1',
    name: 'Seeb Sector 1 High Street',
    zone: 'Seeb',
    location: { latitude: 23.634000, longitude: 58.420900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Seeb.',
  },
  {
    id: 'node-mus-10-2',
    name: 'Seeb Sector 2 High Street',
    zone: 'Seeb',
    location: { latitude: 23.637000, longitude: 58.423900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Seeb.',
  },
  {
    id: 'node-mus-10-3',
    name: 'Seeb Sector 3 High Street',
    zone: 'Seeb',
    location: { latitude: 23.640000, longitude: 58.426900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Seeb.',
  },
];

export const MUSCAT_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-mus-1',
    fromNodeId: 'node-mus-1-1',
    toNodeId: 'node-mus-1-2',
    roadName: 'Al Mouj Muscat Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-2',
    fromNodeId: 'node-mus-1-2',
    toNodeId: 'node-mus-1-3',
    roadName: 'Al Mouj Muscat Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-3',
    fromNodeId: 'node-mus-2-1',
    toNodeId: 'node-mus-2-2',
    roadName: 'Madinat Sultan Qaboos Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-4',
    fromNodeId: 'node-mus-2-2',
    toNodeId: 'node-mus-2-3',
    roadName: 'Madinat Sultan Qaboos Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-5',
    fromNodeId: 'node-mus-3-1',
    toNodeId: 'node-mus-3-2',
    roadName: 'Shatti Al Qurum Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-6',
    fromNodeId: 'node-mus-3-2',
    toNodeId: 'node-mus-3-3',
    roadName: 'Shatti Al Qurum Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-7',
    fromNodeId: 'node-mus-4-1',
    toNodeId: 'node-mus-4-2',
    roadName: 'Qurum Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-8',
    fromNodeId: 'node-mus-4-2',
    toNodeId: 'node-mus-4-3',
    roadName: 'Qurum Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-9',
    fromNodeId: 'node-mus-5-1',
    toNodeId: 'node-mus-5-2',
    roadName: 'Muttrah Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-10',
    fromNodeId: 'node-mus-5-2',
    toNodeId: 'node-mus-5-3',
    roadName: 'Muttrah Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-11',
    fromNodeId: 'node-mus-6-1',
    toNodeId: 'node-mus-6-2',
    roadName: 'Al Khuwair Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-12',
    fromNodeId: 'node-mus-6-2',
    toNodeId: 'node-mus-6-3',
    roadName: 'Al Khuwair Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-13',
    fromNodeId: 'node-mus-7-1',
    toNodeId: 'node-mus-7-2',
    roadName: 'Bausher Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-14',
    fromNodeId: 'node-mus-7-2',
    toNodeId: 'node-mus-7-3',
    roadName: 'Bausher Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-15',
    fromNodeId: 'node-mus-8-1',
    toNodeId: 'node-mus-8-2',
    roadName: 'Azaiba Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-16',
    fromNodeId: 'node-mus-8-2',
    toNodeId: 'node-mus-8-3',
    roadName: 'Azaiba Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-17',
    fromNodeId: 'node-mus-9-1',
    toNodeId: 'node-mus-9-2',
    roadName: 'Ruwi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-18',
    fromNodeId: 'node-mus-9-2',
    toNodeId: 'node-mus-9-3',
    roadName: 'Ruwi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-19',
    fromNodeId: 'node-mus-10-1',
    toNodeId: 'node-mus-10-2',
    roadName: 'Seeb Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mus-20',
    fromNodeId: 'node-mus-10-2',
    toNodeId: 'node-mus-10-3',
    roadName: 'Seeb Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
