/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Mysore Royal Palace Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const MYSORE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 12.2958,
  longitude: 76.6394,
};

export const MYSORE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-mys-1-1',
    name: 'Gokulam Sector 1 High Street',
    zone: 'Gokulam',
    location: { latitude: 12.233800, longitude: 76.587400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gokulam.',
  },
  {
    id: 'node-mys-1-2',
    name: 'Gokulam Sector 2 High Street',
    zone: 'Gokulam',
    location: { latitude: 12.236800, longitude: 76.590400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gokulam.',
  },
  {
    id: 'node-mys-1-3',
    name: 'Gokulam Sector 3 High Street',
    zone: 'Gokulam',
    location: { latitude: 12.239800, longitude: 76.593400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gokulam.',
  },
  {
    id: 'node-mys-2-1',
    name: 'Jayalakshmipuram Sector 1 High Street',
    zone: 'Jayalakshmipuram',
    location: { latitude: 12.245800, longitude: 76.597400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jayalakshmipuram.',
  },
  {
    id: 'node-mys-2-2',
    name: 'Jayalakshmipuram Sector 2 High Street',
    zone: 'Jayalakshmipuram',
    location: { latitude: 12.248800, longitude: 76.600400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jayalakshmipuram.',
  },
  {
    id: 'node-mys-2-3',
    name: 'Jayalakshmipuram Sector 3 High Street',
    zone: 'Jayalakshmipuram',
    location: { latitude: 12.251800, longitude: 76.603400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jayalakshmipuram.',
  },
  {
    id: 'node-mys-3-1',
    name: 'VV Mohalla Sector 1 High Street',
    zone: 'VV Mohalla',
    location: { latitude: 12.257800, longitude: 76.607400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in VV Mohalla.',
  },
  {
    id: 'node-mys-3-2',
    name: 'VV Mohalla Sector 2 High Street',
    zone: 'VV Mohalla',
    location: { latitude: 12.260800, longitude: 76.610400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in VV Mohalla.',
  },
  {
    id: 'node-mys-3-3',
    name: 'VV Mohalla Sector 3 High Street',
    zone: 'VV Mohalla',
    location: { latitude: 12.263800, longitude: 76.613400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in VV Mohalla.',
  },
  {
    id: 'node-mys-4-1',
    name: 'Kuvempunagar Sector 1 High Street',
    zone: 'Kuvempunagar',
    location: { latitude: 12.269800, longitude: 76.617400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kuvempunagar.',
  },
  {
    id: 'node-mys-4-2',
    name: 'Kuvempunagar Sector 2 High Street',
    zone: 'Kuvempunagar',
    location: { latitude: 12.272800, longitude: 76.620400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kuvempunagar.',
  },
  {
    id: 'node-mys-4-3',
    name: 'Kuvempunagar Sector 3 High Street',
    zone: 'Kuvempunagar',
    location: { latitude: 12.275800, longitude: 76.623400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kuvempunagar.',
  },
  {
    id: 'node-mys-5-1',
    name: 'Saraswathipuram Sector 1 High Street',
    zone: 'Saraswathipuram',
    location: { latitude: 12.281800, longitude: 76.627400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Saraswathipuram.',
  },
  {
    id: 'node-mys-5-2',
    name: 'Saraswathipuram Sector 2 High Street',
    zone: 'Saraswathipuram',
    location: { latitude: 12.284800, longitude: 76.630400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Saraswathipuram.',
  },
  {
    id: 'node-mys-5-3',
    name: 'Saraswathipuram Sector 3 High Street',
    zone: 'Saraswathipuram',
    location: { latitude: 12.287800, longitude: 76.633400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Saraswathipuram.',
  },
  {
    id: 'node-mys-6-1',
    name: 'Vijayanagar Sector 1 High Street',
    zone: 'Vijayanagar',
    location: { latitude: 12.293800, longitude: 76.637400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vijayanagar.',
  },
  {
    id: 'node-mys-6-2',
    name: 'Vijayanagar Sector 2 High Street',
    zone: 'Vijayanagar',
    location: { latitude: 12.296800, longitude: 76.640400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vijayanagar.',
  },
  {
    id: 'node-mys-6-3',
    name: 'Vijayanagar Sector 3 High Street',
    zone: 'Vijayanagar',
    location: { latitude: 12.299800, longitude: 76.643400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vijayanagar.',
  },
  {
    id: 'node-mys-7-1',
    name: 'Hebbal Industrial Sector 1 High Street',
    zone: 'Hebbal Industrial',
    location: { latitude: 12.305800, longitude: 76.647400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hebbal Industrial.',
  },
  {
    id: 'node-mys-7-2',
    name: 'Hebbal Industrial Sector 2 High Street',
    zone: 'Hebbal Industrial',
    location: { latitude: 12.308800, longitude: 76.650400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hebbal Industrial.',
  },
  {
    id: 'node-mys-7-3',
    name: 'Hebbal Industrial Sector 3 High Street',
    zone: 'Hebbal Industrial',
    location: { latitude: 12.311800, longitude: 76.653400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hebbal Industrial.',
  },
  {
    id: 'node-mys-8-1',
    name: 'Yadavagiri Sector 1 High Street',
    zone: 'Yadavagiri',
    location: { latitude: 12.317800, longitude: 76.657400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Yadavagiri.',
  },
  {
    id: 'node-mys-8-2',
    name: 'Yadavagiri Sector 2 High Street',
    zone: 'Yadavagiri',
    location: { latitude: 12.320800, longitude: 76.660400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Yadavagiri.',
  },
  {
    id: 'node-mys-8-3',
    name: 'Yadavagiri Sector 3 High Street',
    zone: 'Yadavagiri',
    location: { latitude: 12.323800, longitude: 76.663400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Yadavagiri.',
  },
  {
    id: 'node-mys-9-1',
    name: 'Devaraja Market Sector 1 High Street',
    zone: 'Devaraja Market',
    location: { latitude: 12.329800, longitude: 76.667400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Devaraja Market.',
  },
  {
    id: 'node-mys-9-2',
    name: 'Devaraja Market Sector 2 High Street',
    zone: 'Devaraja Market',
    location: { latitude: 12.332800, longitude: 76.670400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Devaraja Market.',
  },
  {
    id: 'node-mys-9-3',
    name: 'Devaraja Market Sector 3 High Street',
    zone: 'Devaraja Market',
    location: { latitude: 12.335800, longitude: 76.673400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Devaraja Market.',
  },
  {
    id: 'node-mys-10-1',
    name: 'Chamundi Hill Foot Sector 1 High Street',
    zone: 'Chamundi Hill Foot',
    location: { latitude: 12.341800, longitude: 76.677400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chamundi Hill Foot.',
  },
  {
    id: 'node-mys-10-2',
    name: 'Chamundi Hill Foot Sector 2 High Street',
    zone: 'Chamundi Hill Foot',
    location: { latitude: 12.344800, longitude: 76.680400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chamundi Hill Foot.',
  },
  {
    id: 'node-mys-10-3',
    name: 'Chamundi Hill Foot Sector 3 High Street',
    zone: 'Chamundi Hill Foot',
    location: { latitude: 12.347800, longitude: 76.683400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chamundi Hill Foot.',
  },
];

export const MYSORE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-mys-1',
    fromNodeId: 'node-mys-1-1',
    toNodeId: 'node-mys-1-2',
    roadName: 'Gokulam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-2',
    fromNodeId: 'node-mys-1-2',
    toNodeId: 'node-mys-1-3',
    roadName: 'Gokulam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-3',
    fromNodeId: 'node-mys-2-1',
    toNodeId: 'node-mys-2-2',
    roadName: 'Jayalakshmipuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-4',
    fromNodeId: 'node-mys-2-2',
    toNodeId: 'node-mys-2-3',
    roadName: 'Jayalakshmipuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-5',
    fromNodeId: 'node-mys-3-1',
    toNodeId: 'node-mys-3-2',
    roadName: 'VV Mohalla Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-6',
    fromNodeId: 'node-mys-3-2',
    toNodeId: 'node-mys-3-3',
    roadName: 'VV Mohalla Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-7',
    fromNodeId: 'node-mys-4-1',
    toNodeId: 'node-mys-4-2',
    roadName: 'Kuvempunagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-8',
    fromNodeId: 'node-mys-4-2',
    toNodeId: 'node-mys-4-3',
    roadName: 'Kuvempunagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-9',
    fromNodeId: 'node-mys-5-1',
    toNodeId: 'node-mys-5-2',
    roadName: 'Saraswathipuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-10',
    fromNodeId: 'node-mys-5-2',
    toNodeId: 'node-mys-5-3',
    roadName: 'Saraswathipuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-11',
    fromNodeId: 'node-mys-6-1',
    toNodeId: 'node-mys-6-2',
    roadName: 'Vijayanagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-12',
    fromNodeId: 'node-mys-6-2',
    toNodeId: 'node-mys-6-3',
    roadName: 'Vijayanagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-13',
    fromNodeId: 'node-mys-7-1',
    toNodeId: 'node-mys-7-2',
    roadName: 'Hebbal Industrial Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-14',
    fromNodeId: 'node-mys-7-2',
    toNodeId: 'node-mys-7-3',
    roadName: 'Hebbal Industrial Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-15',
    fromNodeId: 'node-mys-8-1',
    toNodeId: 'node-mys-8-2',
    roadName: 'Yadavagiri Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-16',
    fromNodeId: 'node-mys-8-2',
    toNodeId: 'node-mys-8-3',
    roadName: 'Yadavagiri Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-17',
    fromNodeId: 'node-mys-9-1',
    toNodeId: 'node-mys-9-2',
    roadName: 'Devaraja Market Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-18',
    fromNodeId: 'node-mys-9-2',
    toNodeId: 'node-mys-9-3',
    roadName: 'Devaraja Market Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-19',
    fromNodeId: 'node-mys-10-1',
    toNodeId: 'node-mys-10-2',
    roadName: 'Chamundi Hill Foot Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-mys-20',
    fromNodeId: 'node-mys-10-2',
    toNodeId: 'node-mys-10-3',
    roadName: 'Chamundi Hill Foot Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
