/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Nagoya Chubu Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const NAGOYA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 35.1815,
  longitude: 136.9066,
};

export const NAGOYA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-nag-1-1',
    name: 'Sakae Sector 1 High Street',
    zone: 'Sakae',
    location: { latitude: 35.119500, longitude: 136.854600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sakae.',
  },
  {
    id: 'node-nag-1-2',
    name: 'Sakae Sector 2 High Street',
    zone: 'Sakae',
    location: { latitude: 35.122500, longitude: 136.857600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sakae.',
  },
  {
    id: 'node-nag-1-3',
    name: 'Sakae Sector 3 High Street',
    zone: 'Sakae',
    location: { latitude: 35.125500, longitude: 136.860600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sakae.',
  },
  {
    id: 'node-nag-2-1',
    name: 'Nagoya Station Area Sector 1 High Street',
    zone: 'Nagoya Station Area',
    location: { latitude: 35.131500, longitude: 136.864600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nagoya Station Area.',
  },
  {
    id: 'node-nag-2-2',
    name: 'Nagoya Station Area Sector 2 High Street',
    zone: 'Nagoya Station Area',
    location: { latitude: 35.134500, longitude: 136.867600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nagoya Station Area.',
  },
  {
    id: 'node-nag-2-3',
    name: 'Nagoya Station Area Sector 3 High Street',
    zone: 'Nagoya Station Area',
    location: { latitude: 35.137500, longitude: 136.870600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nagoya Station Area.',
  },
  {
    id: 'node-nag-3-1',
    name: 'Osu Sector 1 High Street',
    zone: 'Osu',
    location: { latitude: 35.143500, longitude: 136.874600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Osu.',
  },
  {
    id: 'node-nag-3-2',
    name: 'Osu Sector 2 High Street',
    zone: 'Osu',
    location: { latitude: 35.146500, longitude: 136.877600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Osu.',
  },
  {
    id: 'node-nag-3-3',
    name: 'Osu Sector 3 High Street',
    zone: 'Osu',
    location: { latitude: 35.149500, longitude: 136.880600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Osu.',
  },
  {
    id: 'node-nag-4-1',
    name: 'Kanayama Sector 1 High Street',
    zone: 'Kanayama',
    location: { latitude: 35.155500, longitude: 136.884600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kanayama.',
  },
  {
    id: 'node-nag-4-2',
    name: 'Kanayama Sector 2 High Street',
    zone: 'Kanayama',
    location: { latitude: 35.158500, longitude: 136.887600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kanayama.',
  },
  {
    id: 'node-nag-4-3',
    name: 'Kanayama Sector 3 High Street',
    zone: 'Kanayama',
    location: { latitude: 35.161500, longitude: 136.890600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kanayama.',
  },
  {
    id: 'node-nag-5-1',
    name: 'Chikusa Sector 1 High Street',
    zone: 'Chikusa',
    location: { latitude: 35.167500, longitude: 136.894600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chikusa.',
  },
  {
    id: 'node-nag-5-2',
    name: 'Chikusa Sector 2 High Street',
    zone: 'Chikusa',
    location: { latitude: 35.170500, longitude: 136.897600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chikusa.',
  },
  {
    id: 'node-nag-5-3',
    name: 'Chikusa Sector 3 High Street',
    zone: 'Chikusa',
    location: { latitude: 35.173500, longitude: 136.900600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chikusa.',
  },
  {
    id: 'node-nag-6-1',
    name: 'Meieki Sector 1 High Street',
    zone: 'Meieki',
    location: { latitude: 35.179500, longitude: 136.904600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Meieki.',
  },
  {
    id: 'node-nag-6-2',
    name: 'Meieki Sector 2 High Street',
    zone: 'Meieki',
    location: { latitude: 35.182500, longitude: 136.907600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Meieki.',
  },
  {
    id: 'node-nag-6-3',
    name: 'Meieki Sector 3 High Street',
    zone: 'Meieki',
    location: { latitude: 35.185500, longitude: 136.910600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Meieki.',
  },
  {
    id: 'node-nag-7-1',
    name: 'Fushimi Nagoya Sector 1 High Street',
    zone: 'Fushimi Nagoya',
    location: { latitude: 35.191500, longitude: 136.914600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fushimi Nagoya.',
  },
  {
    id: 'node-nag-7-2',
    name: 'Fushimi Nagoya Sector 2 High Street',
    zone: 'Fushimi Nagoya',
    location: { latitude: 35.194500, longitude: 136.917600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fushimi Nagoya.',
  },
  {
    id: 'node-nag-7-3',
    name: 'Fushimi Nagoya Sector 3 High Street',
    zone: 'Fushimi Nagoya',
    location: { latitude: 35.197500, longitude: 136.920600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fushimi Nagoya.',
  },
  {
    id: 'node-nag-8-1',
    name: 'Marunouchi Sector 1 High Street',
    zone: 'Marunouchi',
    location: { latitude: 35.203500, longitude: 136.924600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Marunouchi.',
  },
  {
    id: 'node-nag-8-2',
    name: 'Marunouchi Sector 2 High Street',
    zone: 'Marunouchi',
    location: { latitude: 35.206500, longitude: 136.927600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Marunouchi.',
  },
  {
    id: 'node-nag-8-3',
    name: 'Marunouchi Sector 3 High Street',
    zone: 'Marunouchi',
    location: { latitude: 35.209500, longitude: 136.930600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Marunouchi.',
  },
  {
    id: 'node-nag-9-1',
    name: 'Tsurumai Sector 1 High Street',
    zone: 'Tsurumai',
    location: { latitude: 35.215500, longitude: 136.934600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tsurumai.',
  },
  {
    id: 'node-nag-9-2',
    name: 'Tsurumai Sector 2 High Street',
    zone: 'Tsurumai',
    location: { latitude: 35.218500, longitude: 136.937600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tsurumai.',
  },
  {
    id: 'node-nag-9-3',
    name: 'Tsurumai Sector 3 High Street',
    zone: 'Tsurumai',
    location: { latitude: 35.221500, longitude: 136.940600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tsurumai.',
  },
  {
    id: 'node-nag-10-1',
    name: 'Hoshigaoka Sector 1 High Street',
    zone: 'Hoshigaoka',
    location: { latitude: 35.227500, longitude: 136.944600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hoshigaoka.',
  },
  {
    id: 'node-nag-10-2',
    name: 'Hoshigaoka Sector 2 High Street',
    zone: 'Hoshigaoka',
    location: { latitude: 35.230500, longitude: 136.947600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hoshigaoka.',
  },
  {
    id: 'node-nag-10-3',
    name: 'Hoshigaoka Sector 3 High Street',
    zone: 'Hoshigaoka',
    location: { latitude: 35.233500, longitude: 136.950600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hoshigaoka.',
  },
];

export const NAGOYA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-nag-1',
    fromNodeId: 'node-nag-1-1',
    toNodeId: 'node-nag-1-2',
    roadName: 'Sakae Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-2',
    fromNodeId: 'node-nag-1-2',
    toNodeId: 'node-nag-1-3',
    roadName: 'Sakae Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-3',
    fromNodeId: 'node-nag-2-1',
    toNodeId: 'node-nag-2-2',
    roadName: 'Nagoya Station Area Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-4',
    fromNodeId: 'node-nag-2-2',
    toNodeId: 'node-nag-2-3',
    roadName: 'Nagoya Station Area Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-5',
    fromNodeId: 'node-nag-3-1',
    toNodeId: 'node-nag-3-2',
    roadName: 'Osu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-6',
    fromNodeId: 'node-nag-3-2',
    toNodeId: 'node-nag-3-3',
    roadName: 'Osu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-7',
    fromNodeId: 'node-nag-4-1',
    toNodeId: 'node-nag-4-2',
    roadName: 'Kanayama Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-8',
    fromNodeId: 'node-nag-4-2',
    toNodeId: 'node-nag-4-3',
    roadName: 'Kanayama Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-9',
    fromNodeId: 'node-nag-5-1',
    toNodeId: 'node-nag-5-2',
    roadName: 'Chikusa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-10',
    fromNodeId: 'node-nag-5-2',
    toNodeId: 'node-nag-5-3',
    roadName: 'Chikusa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-11',
    fromNodeId: 'node-nag-6-1',
    toNodeId: 'node-nag-6-2',
    roadName: 'Meieki Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-12',
    fromNodeId: 'node-nag-6-2',
    toNodeId: 'node-nag-6-3',
    roadName: 'Meieki Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-13',
    fromNodeId: 'node-nag-7-1',
    toNodeId: 'node-nag-7-2',
    roadName: 'Fushimi Nagoya Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-14',
    fromNodeId: 'node-nag-7-2',
    toNodeId: 'node-nag-7-3',
    roadName: 'Fushimi Nagoya Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-15',
    fromNodeId: 'node-nag-8-1',
    toNodeId: 'node-nag-8-2',
    roadName: 'Marunouchi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-16',
    fromNodeId: 'node-nag-8-2',
    toNodeId: 'node-nag-8-3',
    roadName: 'Marunouchi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-17',
    fromNodeId: 'node-nag-9-1',
    toNodeId: 'node-nag-9-2',
    roadName: 'Tsurumai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-18',
    fromNodeId: 'node-nag-9-2',
    toNodeId: 'node-nag-9-3',
    roadName: 'Tsurumai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-19',
    fromNodeId: 'node-nag-10-1',
    toNodeId: 'node-nag-10-2',
    roadName: 'Hoshigaoka Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-20',
    fromNodeId: 'node-nag-10-2',
    toNodeId: 'node-nag-10-3',
    roadName: 'Hoshigaoka Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
