/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Nagpur Orange City Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const NAGPUR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 21.1458,
  longitude: 79.0882,
};

export const NAGPUR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-nag-1-1',
    name: 'Dharampeth Sector 1 High Street',
    zone: 'Dharampeth',
    location: { latitude: 21.083800, longitude: 79.036200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dharampeth.',
  },
  {
    id: 'node-nag-1-2',
    name: 'Dharampeth Sector 2 High Street',
    zone: 'Dharampeth',
    location: { latitude: 21.086800, longitude: 79.039200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dharampeth.',
  },
  {
    id: 'node-nag-1-3',
    name: 'Dharampeth Sector 3 High Street',
    zone: 'Dharampeth',
    location: { latitude: 21.089800, longitude: 79.042200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dharampeth.',
  },
  {
    id: 'node-nag-2-1',
    name: 'Ramdaspeth Sector 1 High Street',
    zone: 'Ramdaspeth',
    location: { latitude: 21.095800, longitude: 79.046200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ramdaspeth.',
  },
  {
    id: 'node-nag-2-2',
    name: 'Ramdaspeth Sector 2 High Street',
    zone: 'Ramdaspeth',
    location: { latitude: 21.098800, longitude: 79.049200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ramdaspeth.',
  },
  {
    id: 'node-nag-2-3',
    name: 'Ramdaspeth Sector 3 High Street',
    zone: 'Ramdaspeth',
    location: { latitude: 21.101800, longitude: 79.052200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ramdaspeth.',
  },
  {
    id: 'node-nag-3-1',
    name: 'Sadar Sector 1 High Street',
    zone: 'Sadar',
    location: { latitude: 21.107800, longitude: 79.056200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sadar.',
  },
  {
    id: 'node-nag-3-2',
    name: 'Sadar Sector 2 High Street',
    zone: 'Sadar',
    location: { latitude: 21.110800, longitude: 79.059200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sadar.',
  },
  {
    id: 'node-nag-3-3',
    name: 'Sadar Sector 3 High Street',
    zone: 'Sadar',
    location: { latitude: 21.113800, longitude: 79.062200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sadar.',
  },
  {
    id: 'node-nag-4-1',
    name: 'Wardha Road Sector 1 High Street',
    zone: 'Wardha Road',
    location: { latitude: 21.119800, longitude: 79.066200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wardha Road.',
  },
  {
    id: 'node-nag-4-2',
    name: 'Wardha Road Sector 2 High Street',
    zone: 'Wardha Road',
    location: { latitude: 21.122800, longitude: 79.069200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wardha Road.',
  },
  {
    id: 'node-nag-4-3',
    name: 'Wardha Road Sector 3 High Street',
    zone: 'Wardha Road',
    location: { latitude: 21.125800, longitude: 79.072200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wardha Road.',
  },
  {
    id: 'node-nag-5-1',
    name: 'Pratap Nagar Sector 1 High Street',
    zone: 'Pratap Nagar',
    location: { latitude: 21.131800, longitude: 79.076200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pratap Nagar.',
  },
  {
    id: 'node-nag-5-2',
    name: 'Pratap Nagar Sector 2 High Street',
    zone: 'Pratap Nagar',
    location: { latitude: 21.134800, longitude: 79.079200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pratap Nagar.',
  },
  {
    id: 'node-nag-5-3',
    name: 'Pratap Nagar Sector 3 High Street',
    zone: 'Pratap Nagar',
    location: { latitude: 21.137800, longitude: 79.082200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pratap Nagar.',
  },
  {
    id: 'node-nag-6-1',
    name: 'Manish Nagar Sector 1 High Street',
    zone: 'Manish Nagar',
    location: { latitude: 21.143800, longitude: 79.086200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Manish Nagar.',
  },
  {
    id: 'node-nag-6-2',
    name: 'Manish Nagar Sector 2 High Street',
    zone: 'Manish Nagar',
    location: { latitude: 21.146800, longitude: 79.089200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Manish Nagar.',
  },
  {
    id: 'node-nag-6-3',
    name: 'Manish Nagar Sector 3 High Street',
    zone: 'Manish Nagar',
    location: { latitude: 21.149800, longitude: 79.092200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Manish Nagar.',
  },
  {
    id: 'node-nag-7-1',
    name: 'Civil Lines Sector 1 High Street',
    zone: 'Civil Lines',
    location: { latitude: 21.155800, longitude: 79.096200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-nag-7-2',
    name: 'Civil Lines Sector 2 High Street',
    zone: 'Civil Lines',
    location: { latitude: 21.158800, longitude: 79.099200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-nag-7-3',
    name: 'Civil Lines Sector 3 High Street',
    zone: 'Civil Lines',
    location: { latitude: 21.161800, longitude: 79.102200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Civil Lines.',
  },
  {
    id: 'node-nag-8-1',
    name: 'Sitabuldi Sector 1 High Street',
    zone: 'Sitabuldi',
    location: { latitude: 21.167800, longitude: 79.106200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sitabuldi.',
  },
  {
    id: 'node-nag-8-2',
    name: 'Sitabuldi Sector 2 High Street',
    zone: 'Sitabuldi',
    location: { latitude: 21.170800, longitude: 79.109200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sitabuldi.',
  },
  {
    id: 'node-nag-8-3',
    name: 'Sitabuldi Sector 3 High Street',
    zone: 'Sitabuldi',
    location: { latitude: 21.173800, longitude: 79.112200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sitabuldi.',
  },
  {
    id: 'node-nag-9-1',
    name: 'Nandanvan Sector 1 High Street',
    zone: 'Nandanvan',
    location: { latitude: 21.179800, longitude: 79.116200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nandanvan.',
  },
  {
    id: 'node-nag-9-2',
    name: 'Nandanvan Sector 2 High Street',
    zone: 'Nandanvan',
    location: { latitude: 21.182800, longitude: 79.119200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nandanvan.',
  },
  {
    id: 'node-nag-9-3',
    name: 'Nandanvan Sector 3 High Street',
    zone: 'Nandanvan',
    location: { latitude: 21.185800, longitude: 79.122200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nandanvan.',
  },
  {
    id: 'node-nag-10-1',
    name: 'Medical Square Sector 1 High Street',
    zone: 'Medical Square',
    location: { latitude: 21.191800, longitude: 79.126200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Medical Square.',
  },
  {
    id: 'node-nag-10-2',
    name: 'Medical Square Sector 2 High Street',
    zone: 'Medical Square',
    location: { latitude: 21.194800, longitude: 79.129200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Medical Square.',
  },
  {
    id: 'node-nag-10-3',
    name: 'Medical Square Sector 3 High Street',
    zone: 'Medical Square',
    location: { latitude: 21.197800, longitude: 79.132200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Medical Square.',
  },
];

export const NAGPUR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-nag-1',
    fromNodeId: 'node-nag-1-1',
    toNodeId: 'node-nag-1-2',
    roadName: 'Dharampeth Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-2',
    fromNodeId: 'node-nag-1-2',
    toNodeId: 'node-nag-1-3',
    roadName: 'Dharampeth Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-3',
    fromNodeId: 'node-nag-2-1',
    toNodeId: 'node-nag-2-2',
    roadName: 'Ramdaspeth Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-4',
    fromNodeId: 'node-nag-2-2',
    toNodeId: 'node-nag-2-3',
    roadName: 'Ramdaspeth Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-5',
    fromNodeId: 'node-nag-3-1',
    toNodeId: 'node-nag-3-2',
    roadName: 'Sadar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-6',
    fromNodeId: 'node-nag-3-2',
    toNodeId: 'node-nag-3-3',
    roadName: 'Sadar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-7',
    fromNodeId: 'node-nag-4-1',
    toNodeId: 'node-nag-4-2',
    roadName: 'Wardha Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-8',
    fromNodeId: 'node-nag-4-2',
    toNodeId: 'node-nag-4-3',
    roadName: 'Wardha Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-9',
    fromNodeId: 'node-nag-5-1',
    toNodeId: 'node-nag-5-2',
    roadName: 'Pratap Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-10',
    fromNodeId: 'node-nag-5-2',
    toNodeId: 'node-nag-5-3',
    roadName: 'Pratap Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-11',
    fromNodeId: 'node-nag-6-1',
    toNodeId: 'node-nag-6-2',
    roadName: 'Manish Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-12',
    fromNodeId: 'node-nag-6-2',
    toNodeId: 'node-nag-6-3',
    roadName: 'Manish Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-13',
    fromNodeId: 'node-nag-7-1',
    toNodeId: 'node-nag-7-2',
    roadName: 'Civil Lines Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-14',
    fromNodeId: 'node-nag-7-2',
    toNodeId: 'node-nag-7-3',
    roadName: 'Civil Lines Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-15',
    fromNodeId: 'node-nag-8-1',
    toNodeId: 'node-nag-8-2',
    roadName: 'Sitabuldi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-16',
    fromNodeId: 'node-nag-8-2',
    toNodeId: 'node-nag-8-3',
    roadName: 'Sitabuldi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-17',
    fromNodeId: 'node-nag-9-1',
    toNodeId: 'node-nag-9-2',
    roadName: 'Nandanvan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-18',
    fromNodeId: 'node-nag-9-2',
    toNodeId: 'node-nag-9-3',
    roadName: 'Nandanvan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-19',
    fromNodeId: 'node-nag-10-1',
    toNodeId: 'node-nag-10-2',
    roadName: 'Medical Square Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nag-20',
    fromNodeId: 'node-nag-10-2',
    toNodeId: 'node-nag-10-3',
    roadName: 'Medical Square Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
