/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Naples Gulf of Pizza
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const NAPLES_BASE_COORDINATE: GeoCoordinate = {
  latitude: 40.8518,
  longitude: 14.2681,
};

export const NAPLES_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-nap-1-1',
    name: 'Spaccanapoli Sector 1 High Street',
    zone: 'Spaccanapoli',
    location: { latitude: 40.789800, longitude: 14.216100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Spaccanapoli.',
  },
  {
    id: 'node-nap-1-2',
    name: 'Spaccanapoli Sector 2 High Street',
    zone: 'Spaccanapoli',
    location: { latitude: 40.792800, longitude: 14.219100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Spaccanapoli.',
  },
  {
    id: 'node-nap-1-3',
    name: 'Spaccanapoli Sector 3 High Street',
    zone: 'Spaccanapoli',
    location: { latitude: 40.795800, longitude: 14.222100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Spaccanapoli.',
  },
  {
    id: 'node-nap-2-1',
    name: 'Chiaia Sector 1 High Street',
    zone: 'Chiaia',
    location: { latitude: 40.801800, longitude: 14.226100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chiaia.',
  },
  {
    id: 'node-nap-2-2',
    name: 'Chiaia Sector 2 High Street',
    zone: 'Chiaia',
    location: { latitude: 40.804800, longitude: 14.229100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chiaia.',
  },
  {
    id: 'node-nap-2-3',
    name: 'Chiaia Sector 3 High Street',
    zone: 'Chiaia',
    location: { latitude: 40.807800, longitude: 14.232100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chiaia.',
  },
  {
    id: 'node-nap-3-1',
    name: 'Vomero Sector 1 High Street',
    zone: 'Vomero',
    location: { latitude: 40.813800, longitude: 14.236100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vomero.',
  },
  {
    id: 'node-nap-3-2',
    name: 'Vomero Sector 2 High Street',
    zone: 'Vomero',
    location: { latitude: 40.816800, longitude: 14.239100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vomero.',
  },
  {
    id: 'node-nap-3-3',
    name: 'Vomero Sector 3 High Street',
    zone: 'Vomero',
    location: { latitude: 40.819800, longitude: 14.242100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vomero.',
  },
  {
    id: 'node-nap-4-1',
    name: 'Centro Storico Naples Sector 1 High Street',
    zone: 'Centro Storico Naples',
    location: { latitude: 40.825800, longitude: 14.246100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Centro Storico Naples.',
  },
  {
    id: 'node-nap-4-2',
    name: 'Centro Storico Naples Sector 2 High Street',
    zone: 'Centro Storico Naples',
    location: { latitude: 40.828800, longitude: 14.249100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Centro Storico Naples.',
  },
  {
    id: 'node-nap-4-3',
    name: 'Centro Storico Naples Sector 3 High Street',
    zone: 'Centro Storico Naples',
    location: { latitude: 40.831800, longitude: 14.252100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Centro Storico Naples.',
  },
  {
    id: 'node-nap-5-1',
    name: 'Posillipo Sector 1 High Street',
    zone: 'Posillipo',
    location: { latitude: 40.837800, longitude: 14.256100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Posillipo.',
  },
  {
    id: 'node-nap-5-2',
    name: 'Posillipo Sector 2 High Street',
    zone: 'Posillipo',
    location: { latitude: 40.840800, longitude: 14.259100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Posillipo.',
  },
  {
    id: 'node-nap-5-3',
    name: 'Posillipo Sector 3 High Street',
    zone: 'Posillipo',
    location: { latitude: 40.843800, longitude: 14.262100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Posillipo.',
  },
  {
    id: 'node-nap-6-1',
    name: 'Toledo Sector 1 High Street',
    zone: 'Toledo',
    location: { latitude: 40.849800, longitude: 14.266100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Toledo.',
  },
  {
    id: 'node-nap-6-2',
    name: 'Toledo Sector 2 High Street',
    zone: 'Toledo',
    location: { latitude: 40.852800, longitude: 14.269100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Toledo.',
  },
  {
    id: 'node-nap-6-3',
    name: 'Toledo Sector 3 High Street',
    zone: 'Toledo',
    location: { latitude: 40.855800, longitude: 14.272100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Toledo.',
  },
  {
    id: 'node-nap-7-1',
    name: 'San Ferdinando Sector 1 High Street',
    zone: 'San Ferdinando',
    location: { latitude: 40.861800, longitude: 14.276100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Ferdinando.',
  },
  {
    id: 'node-nap-7-2',
    name: 'San Ferdinando Sector 2 High Street',
    zone: 'San Ferdinando',
    location: { latitude: 40.864800, longitude: 14.279100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Ferdinando.',
  },
  {
    id: 'node-nap-7-3',
    name: 'San Ferdinando Sector 3 High Street',
    zone: 'San Ferdinando',
    location: { latitude: 40.867800, longitude: 14.282100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Ferdinando.',
  },
  {
    id: 'node-nap-8-1',
    name: 'Porto Naples Sector 1 High Street',
    zone: 'Porto Naples',
    location: { latitude: 40.873800, longitude: 14.286100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Porto Naples.',
  },
  {
    id: 'node-nap-8-2',
    name: 'Porto Naples Sector 2 High Street',
    zone: 'Porto Naples',
    location: { latitude: 40.876800, longitude: 14.289100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Porto Naples.',
  },
  {
    id: 'node-nap-8-3',
    name: 'Porto Naples Sector 3 High Street',
    zone: 'Porto Naples',
    location: { latitude: 40.879800, longitude: 14.292100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Porto Naples.',
  },
  {
    id: 'node-nap-9-1',
    name: 'Fuorigrotta Sector 1 High Street',
    zone: 'Fuorigrotta',
    location: { latitude: 40.885800, longitude: 14.296100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fuorigrotta.',
  },
  {
    id: 'node-nap-9-2',
    name: 'Fuorigrotta Sector 2 High Street',
    zone: 'Fuorigrotta',
    location: { latitude: 40.888800, longitude: 14.299100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fuorigrotta.',
  },
  {
    id: 'node-nap-9-3',
    name: 'Fuorigrotta Sector 3 High Street',
    zone: 'Fuorigrotta',
    location: { latitude: 40.891800, longitude: 14.302100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fuorigrotta.',
  },
  {
    id: 'node-nap-10-1',
    name: 'Mercato Sector 1 High Street',
    zone: 'Mercato',
    location: { latitude: 40.897800, longitude: 14.306100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mercato.',
  },
  {
    id: 'node-nap-10-2',
    name: 'Mercato Sector 2 High Street',
    zone: 'Mercato',
    location: { latitude: 40.900800, longitude: 14.309100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mercato.',
  },
  {
    id: 'node-nap-10-3',
    name: 'Mercato Sector 3 High Street',
    zone: 'Mercato',
    location: { latitude: 40.903800, longitude: 14.312100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mercato.',
  },
];

export const NAPLES_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-nap-1',
    fromNodeId: 'node-nap-1-1',
    toNodeId: 'node-nap-1-2',
    roadName: 'Spaccanapoli Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-2',
    fromNodeId: 'node-nap-1-2',
    toNodeId: 'node-nap-1-3',
    roadName: 'Spaccanapoli Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-3',
    fromNodeId: 'node-nap-2-1',
    toNodeId: 'node-nap-2-2',
    roadName: 'Chiaia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-4',
    fromNodeId: 'node-nap-2-2',
    toNodeId: 'node-nap-2-3',
    roadName: 'Chiaia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-5',
    fromNodeId: 'node-nap-3-1',
    toNodeId: 'node-nap-3-2',
    roadName: 'Vomero Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-6',
    fromNodeId: 'node-nap-3-2',
    toNodeId: 'node-nap-3-3',
    roadName: 'Vomero Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-7',
    fromNodeId: 'node-nap-4-1',
    toNodeId: 'node-nap-4-2',
    roadName: 'Centro Storico Naples Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-8',
    fromNodeId: 'node-nap-4-2',
    toNodeId: 'node-nap-4-3',
    roadName: 'Centro Storico Naples Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-9',
    fromNodeId: 'node-nap-5-1',
    toNodeId: 'node-nap-5-2',
    roadName: 'Posillipo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-10',
    fromNodeId: 'node-nap-5-2',
    toNodeId: 'node-nap-5-3',
    roadName: 'Posillipo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-11',
    fromNodeId: 'node-nap-6-1',
    toNodeId: 'node-nap-6-2',
    roadName: 'Toledo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-12',
    fromNodeId: 'node-nap-6-2',
    toNodeId: 'node-nap-6-3',
    roadName: 'Toledo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-13',
    fromNodeId: 'node-nap-7-1',
    toNodeId: 'node-nap-7-2',
    roadName: 'San Ferdinando Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-14',
    fromNodeId: 'node-nap-7-2',
    toNodeId: 'node-nap-7-3',
    roadName: 'San Ferdinando Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-15',
    fromNodeId: 'node-nap-8-1',
    toNodeId: 'node-nap-8-2',
    roadName: 'Porto Naples Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-16',
    fromNodeId: 'node-nap-8-2',
    toNodeId: 'node-nap-8-3',
    roadName: 'Porto Naples Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-17',
    fromNodeId: 'node-nap-9-1',
    toNodeId: 'node-nap-9-2',
    roadName: 'Fuorigrotta Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-18',
    fromNodeId: 'node-nap-9-2',
    toNodeId: 'node-nap-9-3',
    roadName: 'Fuorigrotta Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-19',
    fromNodeId: 'node-nap-10-1',
    toNodeId: 'node-nap-10-2',
    roadName: 'Mercato Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nap-20',
    fromNodeId: 'node-nap-10-2',
    toNodeId: 'node-nap-10-3',
    roadName: 'Mercato Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
