/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Nashville Music City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const NASHVILLE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 36.1627,
  longitude: -86.7816,
};

export const NASHVILLE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-nas-1-1',
    name: 'Downtown Nashville Sector 1 High Street',
    zone: 'Downtown Nashville',
    location: { latitude: 36.100700, longitude: -86.833600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Nashville.',
  },
  {
    id: 'node-nas-1-2',
    name: 'Downtown Nashville Sector 2 High Street',
    zone: 'Downtown Nashville',
    location: { latitude: 36.103700, longitude: -86.830600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Nashville.',
  },
  {
    id: 'node-nas-1-3',
    name: 'Downtown Nashville Sector 3 High Street',
    zone: 'Downtown Nashville',
    location: { latitude: 36.106700, longitude: -86.827600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Nashville.',
  },
  {
    id: 'node-nas-2-1',
    name: 'The Gulch Sector 1 High Street',
    zone: 'The Gulch',
    location: { latitude: 36.112700, longitude: -86.823600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in The Gulch.',
  },
  {
    id: 'node-nas-2-2',
    name: 'The Gulch Sector 2 High Street',
    zone: 'The Gulch',
    location: { latitude: 36.115700, longitude: -86.820600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in The Gulch.',
  },
  {
    id: 'node-nas-2-3',
    name: 'The Gulch Sector 3 High Street',
    zone: 'The Gulch',
    location: { latitude: 36.118700, longitude: -86.817600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in The Gulch.',
  },
  {
    id: 'node-nas-3-1',
    name: 'East Nashville Sector 1 High Street',
    zone: 'East Nashville',
    location: { latitude: 36.124700, longitude: -86.813600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in East Nashville.',
  },
  {
    id: 'node-nas-3-2',
    name: 'East Nashville Sector 2 High Street',
    zone: 'East Nashville',
    location: { latitude: 36.127700, longitude: -86.810600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in East Nashville.',
  },
  {
    id: 'node-nas-3-3',
    name: 'East Nashville Sector 3 High Street',
    zone: 'East Nashville',
    location: { latitude: 36.130700, longitude: -86.807600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in East Nashville.',
  },
  {
    id: 'node-nas-4-1',
    name: 'Music Row Sector 1 High Street',
    zone: 'Music Row',
    location: { latitude: 36.136700, longitude: -86.803600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Music Row.',
  },
  {
    id: 'node-nas-4-2',
    name: 'Music Row Sector 2 High Street',
    zone: 'Music Row',
    location: { latitude: 36.139700, longitude: -86.800600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Music Row.',
  },
  {
    id: 'node-nas-4-3',
    name: 'Music Row Sector 3 High Street',
    zone: 'Music Row',
    location: { latitude: 36.142700, longitude: -86.797600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Music Row.',
  },
  {
    id: 'node-nas-5-1',
    name: 'Germantown Nashville Sector 1 High Street',
    zone: 'Germantown Nashville',
    location: { latitude: 36.148700, longitude: -86.793600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Germantown Nashville.',
  },
  {
    id: 'node-nas-5-2',
    name: 'Germantown Nashville Sector 2 High Street',
    zone: 'Germantown Nashville',
    location: { latitude: 36.151700, longitude: -86.790600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Germantown Nashville.',
  },
  {
    id: 'node-nas-5-3',
    name: 'Germantown Nashville Sector 3 High Street',
    zone: 'Germantown Nashville',
    location: { latitude: 36.154700, longitude: -86.787600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Germantown Nashville.',
  },
  {
    id: 'node-nas-6-1',
    name: 'Midtown Nashville Sector 1 High Street',
    zone: 'Midtown Nashville',
    location: { latitude: 36.160700, longitude: -86.783600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Midtown Nashville.',
  },
  {
    id: 'node-nas-6-2',
    name: 'Midtown Nashville Sector 2 High Street',
    zone: 'Midtown Nashville',
    location: { latitude: 36.163700, longitude: -86.780600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Midtown Nashville.',
  },
  {
    id: 'node-nas-6-3',
    name: 'Midtown Nashville Sector 3 High Street',
    zone: 'Midtown Nashville',
    location: { latitude: 36.166700, longitude: -86.777600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Midtown Nashville.',
  },
  {
    id: 'node-nas-7-1',
    name: '12 South Sector 1 High Street',
    zone: '12 South',
    location: { latitude: 36.172700, longitude: -86.773600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in 12 South.',
  },
  {
    id: 'node-nas-7-2',
    name: '12 South Sector 2 High Street',
    zone: '12 South',
    location: { latitude: 36.175700, longitude: -86.770600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in 12 South.',
  },
  {
    id: 'node-nas-7-3',
    name: '12 South Sector 3 High Street',
    zone: '12 South',
    location: { latitude: 36.178700, longitude: -86.767600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in 12 South.',
  },
  {
    id: 'node-nas-8-1',
    name: 'Sylvan Park Sector 1 High Street',
    zone: 'Sylvan Park',
    location: { latitude: 36.184700, longitude: -86.763600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sylvan Park.',
  },
  {
    id: 'node-nas-8-2',
    name: 'Sylvan Park Sector 2 High Street',
    zone: 'Sylvan Park',
    location: { latitude: 36.187700, longitude: -86.760600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sylvan Park.',
  },
  {
    id: 'node-nas-8-3',
    name: 'Sylvan Park Sector 3 High Street',
    zone: 'Sylvan Park',
    location: { latitude: 36.190700, longitude: -86.757600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sylvan Park.',
  },
  {
    id: 'node-nas-9-1',
    name: 'Green Hills Sector 1 High Street',
    zone: 'Green Hills',
    location: { latitude: 36.196700, longitude: -86.753600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Green Hills.',
  },
  {
    id: 'node-nas-9-2',
    name: 'Green Hills Sector 2 High Street',
    zone: 'Green Hills',
    location: { latitude: 36.199700, longitude: -86.750600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Green Hills.',
  },
  {
    id: 'node-nas-9-3',
    name: 'Green Hills Sector 3 High Street',
    zone: 'Green Hills',
    location: { latitude: 36.202700, longitude: -86.747600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Green Hills.',
  },
  {
    id: 'node-nas-10-1',
    name: 'Wedgewood-Houston Sector 1 High Street',
    zone: 'Wedgewood-Houston',
    location: { latitude: 36.208700, longitude: -86.743600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wedgewood-Houston.',
  },
  {
    id: 'node-nas-10-2',
    name: 'Wedgewood-Houston Sector 2 High Street',
    zone: 'Wedgewood-Houston',
    location: { latitude: 36.211700, longitude: -86.740600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wedgewood-Houston.',
  },
  {
    id: 'node-nas-10-3',
    name: 'Wedgewood-Houston Sector 3 High Street',
    zone: 'Wedgewood-Houston',
    location: { latitude: 36.214700, longitude: -86.737600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wedgewood-Houston.',
  },
];

export const NASHVILLE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-nas-1',
    fromNodeId: 'node-nas-1-1',
    toNodeId: 'node-nas-1-2',
    roadName: 'Downtown Nashville Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-2',
    fromNodeId: 'node-nas-1-2',
    toNodeId: 'node-nas-1-3',
    roadName: 'Downtown Nashville Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-3',
    fromNodeId: 'node-nas-2-1',
    toNodeId: 'node-nas-2-2',
    roadName: 'The Gulch Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-4',
    fromNodeId: 'node-nas-2-2',
    toNodeId: 'node-nas-2-3',
    roadName: 'The Gulch Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-5',
    fromNodeId: 'node-nas-3-1',
    toNodeId: 'node-nas-3-2',
    roadName: 'East Nashville Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-6',
    fromNodeId: 'node-nas-3-2',
    toNodeId: 'node-nas-3-3',
    roadName: 'East Nashville Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-7',
    fromNodeId: 'node-nas-4-1',
    toNodeId: 'node-nas-4-2',
    roadName: 'Music Row Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-8',
    fromNodeId: 'node-nas-4-2',
    toNodeId: 'node-nas-4-3',
    roadName: 'Music Row Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-9',
    fromNodeId: 'node-nas-5-1',
    toNodeId: 'node-nas-5-2',
    roadName: 'Germantown Nashville Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-10',
    fromNodeId: 'node-nas-5-2',
    toNodeId: 'node-nas-5-3',
    roadName: 'Germantown Nashville Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-11',
    fromNodeId: 'node-nas-6-1',
    toNodeId: 'node-nas-6-2',
    roadName: 'Midtown Nashville Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-12',
    fromNodeId: 'node-nas-6-2',
    toNodeId: 'node-nas-6-3',
    roadName: 'Midtown Nashville Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-13',
    fromNodeId: 'node-nas-7-1',
    toNodeId: 'node-nas-7-2',
    roadName: '12 South Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-14',
    fromNodeId: 'node-nas-7-2',
    toNodeId: 'node-nas-7-3',
    roadName: '12 South Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-15',
    fromNodeId: 'node-nas-8-1',
    toNodeId: 'node-nas-8-2',
    roadName: 'Sylvan Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-16',
    fromNodeId: 'node-nas-8-2',
    toNodeId: 'node-nas-8-3',
    roadName: 'Sylvan Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-17',
    fromNodeId: 'node-nas-9-1',
    toNodeId: 'node-nas-9-2',
    roadName: 'Green Hills Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-18',
    fromNodeId: 'node-nas-9-2',
    toNodeId: 'node-nas-9-3',
    roadName: 'Green Hills Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-19',
    fromNodeId: 'node-nas-10-1',
    toNodeId: 'node-nas-10-2',
    roadName: 'Wedgewood-Houston Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-20',
    fromNodeId: 'node-nas-10-2',
    toNodeId: 'node-nas-10-3',
    roadName: 'Wedgewood-Houston Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
