/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Nashik Wine & Temple City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const NASHIK_BASE_COORDINATE: GeoCoordinate = {
  latitude: 19.9975,
  longitude: 73.7898,
};

export const NASHIK_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-nas-1-1',
    name: 'College Road Sector 1 High Street',
    zone: 'College Road',
    location: { latitude: 19.935500, longitude: 73.737800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in College Road.',
  },
  {
    id: 'node-nas-1-2',
    name: 'College Road Sector 2 High Street',
    zone: 'College Road',
    location: { latitude: 19.938500, longitude: 73.740800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in College Road.',
  },
  {
    id: 'node-nas-1-3',
    name: 'College Road Sector 3 High Street',
    zone: 'College Road',
    location: { latitude: 19.941500, longitude: 73.743800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in College Road.',
  },
  {
    id: 'node-nas-2-1',
    name: 'Gangapur Road Sector 1 High Street',
    zone: 'Gangapur Road',
    location: { latitude: 19.947500, longitude: 73.747800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gangapur Road.',
  },
  {
    id: 'node-nas-2-2',
    name: 'Gangapur Road Sector 2 High Street',
    zone: 'Gangapur Road',
    location: { latitude: 19.950500, longitude: 73.750800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gangapur Road.',
  },
  {
    id: 'node-nas-2-3',
    name: 'Gangapur Road Sector 3 High Street',
    zone: 'Gangapur Road',
    location: { latitude: 19.953500, longitude: 73.753800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gangapur Road.',
  },
  {
    id: 'node-nas-3-1',
    name: 'Mahatma Nagar Sector 1 High Street',
    zone: 'Mahatma Nagar',
    location: { latitude: 19.959500, longitude: 73.757800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mahatma Nagar.',
  },
  {
    id: 'node-nas-3-2',
    name: 'Mahatma Nagar Sector 2 High Street',
    zone: 'Mahatma Nagar',
    location: { latitude: 19.962500, longitude: 73.760800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mahatma Nagar.',
  },
  {
    id: 'node-nas-3-3',
    name: 'Mahatma Nagar Sector 3 High Street',
    zone: 'Mahatma Nagar',
    location: { latitude: 19.965500, longitude: 73.763800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mahatma Nagar.',
  },
  {
    id: 'node-nas-4-1',
    name: 'Indira Nagar Sector 1 High Street',
    zone: 'Indira Nagar',
    location: { latitude: 19.971500, longitude: 73.767800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Indira Nagar.',
  },
  {
    id: 'node-nas-4-2',
    name: 'Indira Nagar Sector 2 High Street',
    zone: 'Indira Nagar',
    location: { latitude: 19.974500, longitude: 73.770800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Indira Nagar.',
  },
  {
    id: 'node-nas-4-3',
    name: 'Indira Nagar Sector 3 High Street',
    zone: 'Indira Nagar',
    location: { latitude: 19.977500, longitude: 73.773800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Indira Nagar.',
  },
  {
    id: 'node-nas-5-1',
    name: 'CIDCO Sector 1 High Street',
    zone: 'CIDCO',
    location: { latitude: 19.983500, longitude: 73.777800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in CIDCO.',
  },
  {
    id: 'node-nas-5-2',
    name: 'CIDCO Sector 2 High Street',
    zone: 'CIDCO',
    location: { latitude: 19.986500, longitude: 73.780800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in CIDCO.',
  },
  {
    id: 'node-nas-5-3',
    name: 'CIDCO Sector 3 High Street',
    zone: 'CIDCO',
    location: { latitude: 19.989500, longitude: 73.783800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in CIDCO.',
  },
  {
    id: 'node-nas-6-1',
    name: 'Panchavati Sector 1 High Street',
    zone: 'Panchavati',
    location: { latitude: 19.995500, longitude: 73.787800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Panchavati.',
  },
  {
    id: 'node-nas-6-2',
    name: 'Panchavati Sector 2 High Street',
    zone: 'Panchavati',
    location: { latitude: 19.998500, longitude: 73.790800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Panchavati.',
  },
  {
    id: 'node-nas-6-3',
    name: 'Panchavati Sector 3 High Street',
    zone: 'Panchavati',
    location: { latitude: 20.001500, longitude: 73.793800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Panchavati.',
  },
  {
    id: 'node-nas-7-1',
    name: 'Satpur Sector 1 High Street',
    zone: 'Satpur',
    location: { latitude: 20.007500, longitude: 73.797800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Satpur.',
  },
  {
    id: 'node-nas-7-2',
    name: 'Satpur Sector 2 High Street',
    zone: 'Satpur',
    location: { latitude: 20.010500, longitude: 73.800800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Satpur.',
  },
  {
    id: 'node-nas-7-3',
    name: 'Satpur Sector 3 High Street',
    zone: 'Satpur',
    location: { latitude: 20.013500, longitude: 73.803800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Satpur.',
  },
  {
    id: 'node-nas-8-1',
    name: 'Ashoka Marg Sector 1 High Street',
    zone: 'Ashoka Marg',
    location: { latitude: 20.019500, longitude: 73.807800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ashoka Marg.',
  },
  {
    id: 'node-nas-8-2',
    name: 'Ashoka Marg Sector 2 High Street',
    zone: 'Ashoka Marg',
    location: { latitude: 20.022500, longitude: 73.810800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ashoka Marg.',
  },
  {
    id: 'node-nas-8-3',
    name: 'Ashoka Marg Sector 3 High Street',
    zone: 'Ashoka Marg',
    location: { latitude: 20.025500, longitude: 73.813800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ashoka Marg.',
  },
  {
    id: 'node-nas-9-1',
    name: 'Govind Nagar Sector 1 High Street',
    zone: 'Govind Nagar',
    location: { latitude: 20.031500, longitude: 73.817800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Govind Nagar.',
  },
  {
    id: 'node-nas-9-2',
    name: 'Govind Nagar Sector 2 High Street',
    zone: 'Govind Nagar',
    location: { latitude: 20.034500, longitude: 73.820800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Govind Nagar.',
  },
  {
    id: 'node-nas-9-3',
    name: 'Govind Nagar Sector 3 High Street',
    zone: 'Govind Nagar',
    location: { latitude: 20.037500, longitude: 73.823800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Govind Nagar.',
  },
  {
    id: 'node-nas-10-1',
    name: 'Pathardi Phata Sector 1 High Street',
    zone: 'Pathardi Phata',
    location: { latitude: 20.043500, longitude: 73.827800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pathardi Phata.',
  },
  {
    id: 'node-nas-10-2',
    name: 'Pathardi Phata Sector 2 High Street',
    zone: 'Pathardi Phata',
    location: { latitude: 20.046500, longitude: 73.830800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pathardi Phata.',
  },
  {
    id: 'node-nas-10-3',
    name: 'Pathardi Phata Sector 3 High Street',
    zone: 'Pathardi Phata',
    location: { latitude: 20.049500, longitude: 73.833800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pathardi Phata.',
  },
];

export const NASHIK_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-nas-1',
    fromNodeId: 'node-nas-1-1',
    toNodeId: 'node-nas-1-2',
    roadName: 'College Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-2',
    fromNodeId: 'node-nas-1-2',
    toNodeId: 'node-nas-1-3',
    roadName: 'College Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-3',
    fromNodeId: 'node-nas-2-1',
    toNodeId: 'node-nas-2-2',
    roadName: 'Gangapur Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-4',
    fromNodeId: 'node-nas-2-2',
    toNodeId: 'node-nas-2-3',
    roadName: 'Gangapur Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-5',
    fromNodeId: 'node-nas-3-1',
    toNodeId: 'node-nas-3-2',
    roadName: 'Mahatma Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-6',
    fromNodeId: 'node-nas-3-2',
    toNodeId: 'node-nas-3-3',
    roadName: 'Mahatma Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-7',
    fromNodeId: 'node-nas-4-1',
    toNodeId: 'node-nas-4-2',
    roadName: 'Indira Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-8',
    fromNodeId: 'node-nas-4-2',
    toNodeId: 'node-nas-4-3',
    roadName: 'Indira Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-9',
    fromNodeId: 'node-nas-5-1',
    toNodeId: 'node-nas-5-2',
    roadName: 'CIDCO Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-10',
    fromNodeId: 'node-nas-5-2',
    toNodeId: 'node-nas-5-3',
    roadName: 'CIDCO Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-11',
    fromNodeId: 'node-nas-6-1',
    toNodeId: 'node-nas-6-2',
    roadName: 'Panchavati Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-12',
    fromNodeId: 'node-nas-6-2',
    toNodeId: 'node-nas-6-3',
    roadName: 'Panchavati Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-13',
    fromNodeId: 'node-nas-7-1',
    toNodeId: 'node-nas-7-2',
    roadName: 'Satpur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-14',
    fromNodeId: 'node-nas-7-2',
    toNodeId: 'node-nas-7-3',
    roadName: 'Satpur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-15',
    fromNodeId: 'node-nas-8-1',
    toNodeId: 'node-nas-8-2',
    roadName: 'Ashoka Marg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-16',
    fromNodeId: 'node-nas-8-2',
    toNodeId: 'node-nas-8-3',
    roadName: 'Ashoka Marg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-17',
    fromNodeId: 'node-nas-9-1',
    toNodeId: 'node-nas-9-2',
    roadName: 'Govind Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-18',
    fromNodeId: 'node-nas-9-2',
    toNodeId: 'node-nas-9-3',
    roadName: 'Govind Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-19',
    fromNodeId: 'node-nas-10-1',
    toNodeId: 'node-nas-10-2',
    roadName: 'Pathardi Phata Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-nas-20',
    fromNodeId: 'node-nas-10-2',
    toNodeId: 'node-nas-10-3',
    roadName: 'Pathardi Phata Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
