/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — New York Manhattan & Brooklyn
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const NEWYORK_BASE_COORDINATE: GeoCoordinate = {
  latitude: 40.7128,
  longitude: -74.006,
};

export const NEWYORK_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-new-1-1',
    name: 'Midtown Manhattan Sector 1 High Street',
    zone: 'Midtown Manhattan',
    location: { latitude: 40.650800, longitude: -74.058000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Midtown Manhattan.',
  },
  {
    id: 'node-new-1-2',
    name: 'Midtown Manhattan Sector 2 High Street',
    zone: 'Midtown Manhattan',
    location: { latitude: 40.653800, longitude: -74.055000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Midtown Manhattan.',
  },
  {
    id: 'node-new-1-3',
    name: 'Midtown Manhattan Sector 3 High Street',
    zone: 'Midtown Manhattan',
    location: { latitude: 40.656800, longitude: -74.052000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Midtown Manhattan.',
  },
  {
    id: 'node-new-2-1',
    name: 'SoHo NYC Sector 1 High Street',
    zone: 'SoHo NYC',
    location: { latitude: 40.662800, longitude: -74.048000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in SoHo NYC.',
  },
  {
    id: 'node-new-2-2',
    name: 'SoHo NYC Sector 2 High Street',
    zone: 'SoHo NYC',
    location: { latitude: 40.665800, longitude: -74.045000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in SoHo NYC.',
  },
  {
    id: 'node-new-2-3',
    name: 'SoHo NYC Sector 3 High Street',
    zone: 'SoHo NYC',
    location: { latitude: 40.668800, longitude: -74.042000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in SoHo NYC.',
  },
  {
    id: 'node-new-3-1',
    name: 'Upper East Side Sector 1 High Street',
    zone: 'Upper East Side',
    location: { latitude: 40.674800, longitude: -74.038000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Upper East Side.',
  },
  {
    id: 'node-new-3-2',
    name: 'Upper East Side Sector 2 High Street',
    zone: 'Upper East Side',
    location: { latitude: 40.677800, longitude: -74.035000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Upper East Side.',
  },
  {
    id: 'node-new-3-3',
    name: 'Upper East Side Sector 3 High Street',
    zone: 'Upper East Side',
    location: { latitude: 40.680800, longitude: -74.032000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Upper East Side.',
  },
  {
    id: 'node-new-4-1',
    name: 'Williamsburg Sector 1 High Street',
    zone: 'Williamsburg',
    location: { latitude: 40.686800, longitude: -74.028000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Williamsburg.',
  },
  {
    id: 'node-new-4-2',
    name: 'Williamsburg Sector 2 High Street',
    zone: 'Williamsburg',
    location: { latitude: 40.689800, longitude: -74.025000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Williamsburg.',
  },
  {
    id: 'node-new-4-3',
    name: 'Williamsburg Sector 3 High Street',
    zone: 'Williamsburg',
    location: { latitude: 40.692800, longitude: -74.022000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Williamsburg.',
  },
  {
    id: 'node-new-5-1',
    name: 'DUMBO Brooklyn Sector 1 High Street',
    zone: 'DUMBO Brooklyn',
    location: { latitude: 40.698800, longitude: -74.018000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in DUMBO Brooklyn.',
  },
  {
    id: 'node-new-5-2',
    name: 'DUMBO Brooklyn Sector 2 High Street',
    zone: 'DUMBO Brooklyn',
    location: { latitude: 40.701800, longitude: -74.015000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in DUMBO Brooklyn.',
  },
  {
    id: 'node-new-5-3',
    name: 'DUMBO Brooklyn Sector 3 High Street',
    zone: 'DUMBO Brooklyn',
    location: { latitude: 40.704800, longitude: -74.012000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in DUMBO Brooklyn.',
  },
  {
    id: 'node-new-6-1',
    name: 'Greenwich Village Sector 1 High Street',
    zone: 'Greenwich Village',
    location: { latitude: 40.710800, longitude: -74.008000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Greenwich Village.',
  },
  {
    id: 'node-new-6-2',
    name: 'Greenwich Village Sector 2 High Street',
    zone: 'Greenwich Village',
    location: { latitude: 40.713800, longitude: -74.005000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Greenwich Village.',
  },
  {
    id: 'node-new-6-3',
    name: 'Greenwich Village Sector 3 High Street',
    zone: 'Greenwich Village',
    location: { latitude: 40.716800, longitude: -74.002000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Greenwich Village.',
  },
  {
    id: 'node-new-7-1',
    name: 'Financial District Sector 1 High Street',
    zone: 'Financial District',
    location: { latitude: 40.722800, longitude: -73.998000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Financial District.',
  },
  {
    id: 'node-new-7-2',
    name: 'Financial District Sector 2 High Street',
    zone: 'Financial District',
    location: { latitude: 40.725800, longitude: -73.995000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Financial District.',
  },
  {
    id: 'node-new-7-3',
    name: 'Financial District Sector 3 High Street',
    zone: 'Financial District',
    location: { latitude: 40.728800, longitude: -73.992000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Financial District.',
  },
  {
    id: 'node-new-8-1',
    name: 'Chelsea NYC Sector 1 High Street',
    zone: 'Chelsea NYC',
    location: { latitude: 40.734800, longitude: -73.988000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chelsea NYC.',
  },
  {
    id: 'node-new-8-2',
    name: 'Chelsea NYC Sector 2 High Street',
    zone: 'Chelsea NYC',
    location: { latitude: 40.737800, longitude: -73.985000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chelsea NYC.',
  },
  {
    id: 'node-new-8-3',
    name: 'Chelsea NYC Sector 3 High Street',
    zone: 'Chelsea NYC',
    location: { latitude: 40.740800, longitude: -73.982000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chelsea NYC.',
  },
  {
    id: 'node-new-9-1',
    name: 'Astoria Queens Sector 1 High Street',
    zone: 'Astoria Queens',
    location: { latitude: 40.746800, longitude: -73.978000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Astoria Queens.',
  },
  {
    id: 'node-new-9-2',
    name: 'Astoria Queens Sector 2 High Street',
    zone: 'Astoria Queens',
    location: { latitude: 40.749800, longitude: -73.975000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Astoria Queens.',
  },
  {
    id: 'node-new-9-3',
    name: 'Astoria Queens Sector 3 High Street',
    zone: 'Astoria Queens',
    location: { latitude: 40.752800, longitude: -73.972000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Astoria Queens.',
  },
  {
    id: 'node-new-10-1',
    name: 'Harlem Sector 1 High Street',
    zone: 'Harlem',
    location: { latitude: 40.758800, longitude: -73.968000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Harlem.',
  },
  {
    id: 'node-new-10-2',
    name: 'Harlem Sector 2 High Street',
    zone: 'Harlem',
    location: { latitude: 40.761800, longitude: -73.965000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Harlem.',
  },
  {
    id: 'node-new-10-3',
    name: 'Harlem Sector 3 High Street',
    zone: 'Harlem',
    location: { latitude: 40.764800, longitude: -73.962000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Harlem.',
  },
];

export const NEWYORK_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-new-1',
    fromNodeId: 'node-new-1-1',
    toNodeId: 'node-new-1-2',
    roadName: 'Midtown Manhattan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-2',
    fromNodeId: 'node-new-1-2',
    toNodeId: 'node-new-1-3',
    roadName: 'Midtown Manhattan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-3',
    fromNodeId: 'node-new-2-1',
    toNodeId: 'node-new-2-2',
    roadName: 'SoHo NYC Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-4',
    fromNodeId: 'node-new-2-2',
    toNodeId: 'node-new-2-3',
    roadName: 'SoHo NYC Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-5',
    fromNodeId: 'node-new-3-1',
    toNodeId: 'node-new-3-2',
    roadName: 'Upper East Side Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-6',
    fromNodeId: 'node-new-3-2',
    toNodeId: 'node-new-3-3',
    roadName: 'Upper East Side Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-7',
    fromNodeId: 'node-new-4-1',
    toNodeId: 'node-new-4-2',
    roadName: 'Williamsburg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-8',
    fromNodeId: 'node-new-4-2',
    toNodeId: 'node-new-4-3',
    roadName: 'Williamsburg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-9',
    fromNodeId: 'node-new-5-1',
    toNodeId: 'node-new-5-2',
    roadName: 'DUMBO Brooklyn Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-10',
    fromNodeId: 'node-new-5-2',
    toNodeId: 'node-new-5-3',
    roadName: 'DUMBO Brooklyn Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-11',
    fromNodeId: 'node-new-6-1',
    toNodeId: 'node-new-6-2',
    roadName: 'Greenwich Village Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-12',
    fromNodeId: 'node-new-6-2',
    toNodeId: 'node-new-6-3',
    roadName: 'Greenwich Village Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-13',
    fromNodeId: 'node-new-7-1',
    toNodeId: 'node-new-7-2',
    roadName: 'Financial District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-14',
    fromNodeId: 'node-new-7-2',
    toNodeId: 'node-new-7-3',
    roadName: 'Financial District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-15',
    fromNodeId: 'node-new-8-1',
    toNodeId: 'node-new-8-2',
    roadName: 'Chelsea NYC Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-16',
    fromNodeId: 'node-new-8-2',
    toNodeId: 'node-new-8-3',
    roadName: 'Chelsea NYC Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-17',
    fromNodeId: 'node-new-9-1',
    toNodeId: 'node-new-9-2',
    roadName: 'Astoria Queens Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-18',
    fromNodeId: 'node-new-9-2',
    toNodeId: 'node-new-9-3',
    roadName: 'Astoria Queens Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-19',
    fromNodeId: 'node-new-10-1',
    toNodeId: 'node-new-10-2',
    roadName: 'Harlem Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-new-20',
    fromNodeId: 'node-new-10-2',
    toNodeId: 'node-new-10-3',
    roadName: 'Harlem Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
