/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Orlando Theme & Tech Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const ORLANDO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 28.5383,
  longitude: -81.3792,
};

export const ORLANDO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-orl-1-1',
    name: 'Downtown Orlando Sector 1 High Street',
    zone: 'Downtown Orlando',
    location: { latitude: 28.476300, longitude: -81.431200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Orlando.',
  },
  {
    id: 'node-orl-1-2',
    name: 'Downtown Orlando Sector 2 High Street',
    zone: 'Downtown Orlando',
    location: { latitude: 28.479300, longitude: -81.428200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Orlando.',
  },
  {
    id: 'node-orl-1-3',
    name: 'Downtown Orlando Sector 3 High Street',
    zone: 'Downtown Orlando',
    location: { latitude: 28.482300, longitude: -81.425200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Orlando.',
  },
  {
    id: 'node-orl-2-1',
    name: 'Winter Park Sector 1 High Street',
    zone: 'Winter Park',
    location: { latitude: 28.488300, longitude: -81.421200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Winter Park.',
  },
  {
    id: 'node-orl-2-2',
    name: 'Winter Park Sector 2 High Street',
    zone: 'Winter Park',
    location: { latitude: 28.491300, longitude: -81.418200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Winter Park.',
  },
  {
    id: 'node-orl-2-3',
    name: 'Winter Park Sector 3 High Street',
    zone: 'Winter Park',
    location: { latitude: 28.494300, longitude: -81.415200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Winter Park.',
  },
  {
    id: 'node-orl-3-1',
    name: 'Thornton Park Sector 1 High Street',
    zone: 'Thornton Park',
    location: { latitude: 28.500300, longitude: -81.411200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Thornton Park.',
  },
  {
    id: 'node-orl-3-2',
    name: 'Thornton Park Sector 2 High Street',
    zone: 'Thornton Park',
    location: { latitude: 28.503300, longitude: -81.408200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Thornton Park.',
  },
  {
    id: 'node-orl-3-3',
    name: 'Thornton Park Sector 3 High Street',
    zone: 'Thornton Park',
    location: { latitude: 28.506300, longitude: -81.405200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Thornton Park.',
  },
  {
    id: 'node-orl-4-1',
    name: 'Lake Eola Sector 1 High Street',
    zone: 'Lake Eola',
    location: { latitude: 28.512300, longitude: -81.401200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lake Eola.',
  },
  {
    id: 'node-orl-4-2',
    name: 'Lake Eola Sector 2 High Street',
    zone: 'Lake Eola',
    location: { latitude: 28.515300, longitude: -81.398200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lake Eola.',
  },
  {
    id: 'node-orl-4-3',
    name: 'Lake Eola Sector 3 High Street',
    zone: 'Lake Eola',
    location: { latitude: 28.518300, longitude: -81.395200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lake Eola.',
  },
  {
    id: 'node-orl-5-1',
    name: 'Mills 50 Sector 1 High Street',
    zone: 'Mills 50',
    location: { latitude: 28.524300, longitude: -81.391200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mills 50.',
  },
  {
    id: 'node-orl-5-2',
    name: 'Mills 50 Sector 2 High Street',
    zone: 'Mills 50',
    location: { latitude: 28.527300, longitude: -81.388200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mills 50.',
  },
  {
    id: 'node-orl-5-3',
    name: 'Mills 50 Sector 3 High Street',
    zone: 'Mills 50',
    location: { latitude: 28.530300, longitude: -81.385200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mills 50.',
  },
  {
    id: 'node-orl-6-1',
    name: 'College Park Orlando Sector 1 High Street',
    zone: 'College Park Orlando',
    location: { latitude: 28.536300, longitude: -81.381200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in College Park Orlando.',
  },
  {
    id: 'node-orl-6-2',
    name: 'College Park Orlando Sector 2 High Street',
    zone: 'College Park Orlando',
    location: { latitude: 28.539300, longitude: -81.378200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in College Park Orlando.',
  },
  {
    id: 'node-orl-6-3',
    name: 'College Park Orlando Sector 3 High Street',
    zone: 'College Park Orlando',
    location: { latitude: 28.542300, longitude: -81.375200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in College Park Orlando.',
  },
  {
    id: 'node-orl-7-1',
    name: 'Baldwin Park Sector 1 High Street',
    zone: 'Baldwin Park',
    location: { latitude: 28.548300, longitude: -81.371200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Baldwin Park.',
  },
  {
    id: 'node-orl-7-2',
    name: 'Baldwin Park Sector 2 High Street',
    zone: 'Baldwin Park',
    location: { latitude: 28.551300, longitude: -81.368200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Baldwin Park.',
  },
  {
    id: 'node-orl-7-3',
    name: 'Baldwin Park Sector 3 High Street',
    zone: 'Baldwin Park',
    location: { latitude: 28.554300, longitude: -81.365200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Baldwin Park.',
  },
  {
    id: 'node-orl-8-1',
    name: 'International Drive Sector 1 High Street',
    zone: 'International Drive',
    location: { latitude: 28.560300, longitude: -81.361200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in International Drive.',
  },
  {
    id: 'node-orl-8-2',
    name: 'International Drive Sector 2 High Street',
    zone: 'International Drive',
    location: { latitude: 28.563300, longitude: -81.358200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in International Drive.',
  },
  {
    id: 'node-orl-8-3',
    name: 'International Drive Sector 3 High Street',
    zone: 'International Drive',
    location: { latitude: 28.566300, longitude: -81.355200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in International Drive.',
  },
  {
    id: 'node-orl-9-1',
    name: 'Doctor Phillips Sector 1 High Street',
    zone: 'Doctor Phillips',
    location: { latitude: 28.572300, longitude: -81.351200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Doctor Phillips.',
  },
  {
    id: 'node-orl-9-2',
    name: 'Doctor Phillips Sector 2 High Street',
    zone: 'Doctor Phillips',
    location: { latitude: 28.575300, longitude: -81.348200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Doctor Phillips.',
  },
  {
    id: 'node-orl-9-3',
    name: 'Doctor Phillips Sector 3 High Street',
    zone: 'Doctor Phillips',
    location: { latitude: 28.578300, longitude: -81.345200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Doctor Phillips.',
  },
  {
    id: 'node-orl-10-1',
    name: 'Lake Nona Sector 1 High Street',
    zone: 'Lake Nona',
    location: { latitude: 28.584300, longitude: -81.341200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lake Nona.',
  },
  {
    id: 'node-orl-10-2',
    name: 'Lake Nona Sector 2 High Street',
    zone: 'Lake Nona',
    location: { latitude: 28.587300, longitude: -81.338200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lake Nona.',
  },
  {
    id: 'node-orl-10-3',
    name: 'Lake Nona Sector 3 High Street',
    zone: 'Lake Nona',
    location: { latitude: 28.590300, longitude: -81.335200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lake Nona.',
  },
];

export const ORLANDO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-orl-1',
    fromNodeId: 'node-orl-1-1',
    toNodeId: 'node-orl-1-2',
    roadName: 'Downtown Orlando Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-2',
    fromNodeId: 'node-orl-1-2',
    toNodeId: 'node-orl-1-3',
    roadName: 'Downtown Orlando Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-3',
    fromNodeId: 'node-orl-2-1',
    toNodeId: 'node-orl-2-2',
    roadName: 'Winter Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-4',
    fromNodeId: 'node-orl-2-2',
    toNodeId: 'node-orl-2-3',
    roadName: 'Winter Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-5',
    fromNodeId: 'node-orl-3-1',
    toNodeId: 'node-orl-3-2',
    roadName: 'Thornton Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-6',
    fromNodeId: 'node-orl-3-2',
    toNodeId: 'node-orl-3-3',
    roadName: 'Thornton Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-7',
    fromNodeId: 'node-orl-4-1',
    toNodeId: 'node-orl-4-2',
    roadName: 'Lake Eola Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-8',
    fromNodeId: 'node-orl-4-2',
    toNodeId: 'node-orl-4-3',
    roadName: 'Lake Eola Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-9',
    fromNodeId: 'node-orl-5-1',
    toNodeId: 'node-orl-5-2',
    roadName: 'Mills 50 Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-10',
    fromNodeId: 'node-orl-5-2',
    toNodeId: 'node-orl-5-3',
    roadName: 'Mills 50 Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-11',
    fromNodeId: 'node-orl-6-1',
    toNodeId: 'node-orl-6-2',
    roadName: 'College Park Orlando Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-12',
    fromNodeId: 'node-orl-6-2',
    toNodeId: 'node-orl-6-3',
    roadName: 'College Park Orlando Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-13',
    fromNodeId: 'node-orl-7-1',
    toNodeId: 'node-orl-7-2',
    roadName: 'Baldwin Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-14',
    fromNodeId: 'node-orl-7-2',
    toNodeId: 'node-orl-7-3',
    roadName: 'Baldwin Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-15',
    fromNodeId: 'node-orl-8-1',
    toNodeId: 'node-orl-8-2',
    roadName: 'International Drive Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-16',
    fromNodeId: 'node-orl-8-2',
    toNodeId: 'node-orl-8-3',
    roadName: 'International Drive Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-17',
    fromNodeId: 'node-orl-9-1',
    toNodeId: 'node-orl-9-2',
    roadName: 'Doctor Phillips Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-18',
    fromNodeId: 'node-orl-9-2',
    toNodeId: 'node-orl-9-3',
    roadName: 'Doctor Phillips Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-19',
    fromNodeId: 'node-orl-10-1',
    toNodeId: 'node-orl-10-2',
    roadName: 'Lake Nona Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-orl-20',
    fromNodeId: 'node-orl-10-2',
    toNodeId: 'node-orl-10-3',
    roadName: 'Lake Nona Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
