/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Osaka Kansai Food Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const OSAKA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 34.6937,
  longitude: 135.5023,
};

export const OSAKA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-osa-1-1',
    name: 'Dotonbori Sector 1 High Street',
    zone: 'Dotonbori',
    location: { latitude: 34.631700, longitude: 135.450300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dotonbori.',
  },
  {
    id: 'node-osa-1-2',
    name: 'Dotonbori Sector 2 High Street',
    zone: 'Dotonbori',
    location: { latitude: 34.634700, longitude: 135.453300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dotonbori.',
  },
  {
    id: 'node-osa-1-3',
    name: 'Dotonbori Sector 3 High Street',
    zone: 'Dotonbori',
    location: { latitude: 34.637700, longitude: 135.456300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dotonbori.',
  },
  {
    id: 'node-osa-2-1',
    name: 'Umeda Sector 1 High Street',
    zone: 'Umeda',
    location: { latitude: 34.643700, longitude: 135.460300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Umeda.',
  },
  {
    id: 'node-osa-2-2',
    name: 'Umeda Sector 2 High Street',
    zone: 'Umeda',
    location: { latitude: 34.646700, longitude: 135.463300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Umeda.',
  },
  {
    id: 'node-osa-2-3',
    name: 'Umeda Sector 3 High Street',
    zone: 'Umeda',
    location: { latitude: 34.649700, longitude: 135.466300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Umeda.',
  },
  {
    id: 'node-osa-3-1',
    name: 'Shinsaibashi Sector 1 High Street',
    zone: 'Shinsaibashi',
    location: { latitude: 34.655700, longitude: 135.470300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shinsaibashi.',
  },
  {
    id: 'node-osa-3-2',
    name: 'Shinsaibashi Sector 2 High Street',
    zone: 'Shinsaibashi',
    location: { latitude: 34.658700, longitude: 135.473300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shinsaibashi.',
  },
  {
    id: 'node-osa-3-3',
    name: 'Shinsaibashi Sector 3 High Street',
    zone: 'Shinsaibashi',
    location: { latitude: 34.661700, longitude: 135.476300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shinsaibashi.',
  },
  {
    id: 'node-osa-4-1',
    name: 'Namba Sector 1 High Street',
    zone: 'Namba',
    location: { latitude: 34.667700, longitude: 135.480300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Namba.',
  },
  {
    id: 'node-osa-4-2',
    name: 'Namba Sector 2 High Street',
    zone: 'Namba',
    location: { latitude: 34.670700, longitude: 135.483300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Namba.',
  },
  {
    id: 'node-osa-4-3',
    name: 'Namba Sector 3 High Street',
    zone: 'Namba',
    location: { latitude: 34.673700, longitude: 135.486300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Namba.',
  },
  {
    id: 'node-osa-5-1',
    name: 'Tennoji Sector 1 High Street',
    zone: 'Tennoji',
    location: { latitude: 34.679700, longitude: 135.490300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tennoji.',
  },
  {
    id: 'node-osa-5-2',
    name: 'Tennoji Sector 2 High Street',
    zone: 'Tennoji',
    location: { latitude: 34.682700, longitude: 135.493300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tennoji.',
  },
  {
    id: 'node-osa-5-3',
    name: 'Tennoji Sector 3 High Street',
    zone: 'Tennoji',
    location: { latitude: 34.685700, longitude: 135.496300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tennoji.',
  },
  {
    id: 'node-osa-6-1',
    name: 'Amerikamura Sector 1 High Street',
    zone: 'Amerikamura',
    location: { latitude: 34.691700, longitude: 135.500300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Amerikamura.',
  },
  {
    id: 'node-osa-6-2',
    name: 'Amerikamura Sector 2 High Street',
    zone: 'Amerikamura',
    location: { latitude: 34.694700, longitude: 135.503300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Amerikamura.',
  },
  {
    id: 'node-osa-6-3',
    name: 'Amerikamura Sector 3 High Street',
    zone: 'Amerikamura',
    location: { latitude: 34.697700, longitude: 135.506300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Amerikamura.',
  },
  {
    id: 'node-osa-7-1',
    name: 'Kitashinchi Sector 1 High Street',
    zone: 'Kitashinchi',
    location: { latitude: 34.703700, longitude: 135.510300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kitashinchi.',
  },
  {
    id: 'node-osa-7-2',
    name: 'Kitashinchi Sector 2 High Street',
    zone: 'Kitashinchi',
    location: { latitude: 34.706700, longitude: 135.513300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kitashinchi.',
  },
  {
    id: 'node-osa-7-3',
    name: 'Kitashinchi Sector 3 High Street',
    zone: 'Kitashinchi',
    location: { latitude: 34.709700, longitude: 135.516300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kitashinchi.',
  },
  {
    id: 'node-osa-8-1',
    name: 'Tsuruhashi Sector 1 High Street',
    zone: 'Tsuruhashi',
    location: { latitude: 34.715700, longitude: 135.520300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tsuruhashi.',
  },
  {
    id: 'node-osa-8-2',
    name: 'Tsuruhashi Sector 2 High Street',
    zone: 'Tsuruhashi',
    location: { latitude: 34.718700, longitude: 135.523300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tsuruhashi.',
  },
  {
    id: 'node-osa-8-3',
    name: 'Tsuruhashi Sector 3 High Street',
    zone: 'Tsuruhashi',
    location: { latitude: 34.721700, longitude: 135.526300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tsuruhashi.',
  },
  {
    id: 'node-osa-9-1',
    name: 'Kyobashi Sector 1 High Street',
    zone: 'Kyobashi',
    location: { latitude: 34.727700, longitude: 135.530300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kyobashi.',
  },
  {
    id: 'node-osa-9-2',
    name: 'Kyobashi Sector 2 High Street',
    zone: 'Kyobashi',
    location: { latitude: 34.730700, longitude: 135.533300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kyobashi.',
  },
  {
    id: 'node-osa-9-3',
    name: 'Kyobashi Sector 3 High Street',
    zone: 'Kyobashi',
    location: { latitude: 34.733700, longitude: 135.536300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kyobashi.',
  },
  {
    id: 'node-osa-10-1',
    name: 'Shinsekai Sector 1 High Street',
    zone: 'Shinsekai',
    location: { latitude: 34.739700, longitude: 135.540300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shinsekai.',
  },
  {
    id: 'node-osa-10-2',
    name: 'Shinsekai Sector 2 High Street',
    zone: 'Shinsekai',
    location: { latitude: 34.742700, longitude: 135.543300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shinsekai.',
  },
  {
    id: 'node-osa-10-3',
    name: 'Shinsekai Sector 3 High Street',
    zone: 'Shinsekai',
    location: { latitude: 34.745700, longitude: 135.546300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shinsekai.',
  },
];

export const OSAKA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-osa-1',
    fromNodeId: 'node-osa-1-1',
    toNodeId: 'node-osa-1-2',
    roadName: 'Dotonbori Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-2',
    fromNodeId: 'node-osa-1-2',
    toNodeId: 'node-osa-1-3',
    roadName: 'Dotonbori Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-3',
    fromNodeId: 'node-osa-2-1',
    toNodeId: 'node-osa-2-2',
    roadName: 'Umeda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-4',
    fromNodeId: 'node-osa-2-2',
    toNodeId: 'node-osa-2-3',
    roadName: 'Umeda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-5',
    fromNodeId: 'node-osa-3-1',
    toNodeId: 'node-osa-3-2',
    roadName: 'Shinsaibashi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-6',
    fromNodeId: 'node-osa-3-2',
    toNodeId: 'node-osa-3-3',
    roadName: 'Shinsaibashi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-7',
    fromNodeId: 'node-osa-4-1',
    toNodeId: 'node-osa-4-2',
    roadName: 'Namba Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-8',
    fromNodeId: 'node-osa-4-2',
    toNodeId: 'node-osa-4-3',
    roadName: 'Namba Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-9',
    fromNodeId: 'node-osa-5-1',
    toNodeId: 'node-osa-5-2',
    roadName: 'Tennoji Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-10',
    fromNodeId: 'node-osa-5-2',
    toNodeId: 'node-osa-5-3',
    roadName: 'Tennoji Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-11',
    fromNodeId: 'node-osa-6-1',
    toNodeId: 'node-osa-6-2',
    roadName: 'Amerikamura Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-12',
    fromNodeId: 'node-osa-6-2',
    toNodeId: 'node-osa-6-3',
    roadName: 'Amerikamura Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-13',
    fromNodeId: 'node-osa-7-1',
    toNodeId: 'node-osa-7-2',
    roadName: 'Kitashinchi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-14',
    fromNodeId: 'node-osa-7-2',
    toNodeId: 'node-osa-7-3',
    roadName: 'Kitashinchi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-15',
    fromNodeId: 'node-osa-8-1',
    toNodeId: 'node-osa-8-2',
    roadName: 'Tsuruhashi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-16',
    fromNodeId: 'node-osa-8-2',
    toNodeId: 'node-osa-8-3',
    roadName: 'Tsuruhashi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-17',
    fromNodeId: 'node-osa-9-1',
    toNodeId: 'node-osa-9-2',
    roadName: 'Kyobashi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-18',
    fromNodeId: 'node-osa-9-2',
    toNodeId: 'node-osa-9-3',
    roadName: 'Kyobashi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-19',
    fromNodeId: 'node-osa-10-1',
    toNodeId: 'node-osa-10-2',
    roadName: 'Shinsekai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osa-20',
    fromNodeId: 'node-osa-10-2',
    toNodeId: 'node-osa-10-3',
    roadName: 'Shinsekai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
