/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Oslo Fjord Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const OSLO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 59.9139,
  longitude: 10.7522,
};

export const OSLO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-osl-1-1',
    name: 'Sentrum Oslo Sector 1 High Street',
    zone: 'Sentrum Oslo',
    location: { latitude: 59.851900, longitude: 10.700200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sentrum Oslo.',
  },
  {
    id: 'node-osl-1-2',
    name: 'Sentrum Oslo Sector 2 High Street',
    zone: 'Sentrum Oslo',
    location: { latitude: 59.854900, longitude: 10.703200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sentrum Oslo.',
  },
  {
    id: 'node-osl-1-3',
    name: 'Sentrum Oslo Sector 3 High Street',
    zone: 'Sentrum Oslo',
    location: { latitude: 59.857900, longitude: 10.706200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sentrum Oslo.',
  },
  {
    id: 'node-osl-2-1',
    name: 'Grünerløkka Sector 1 High Street',
    zone: 'Grünerløkka',
    location: { latitude: 59.863900, longitude: 10.710200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Grünerløkka.',
  },
  {
    id: 'node-osl-2-2',
    name: 'Grünerløkka Sector 2 High Street',
    zone: 'Grünerløkka',
    location: { latitude: 59.866900, longitude: 10.713200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Grünerløkka.',
  },
  {
    id: 'node-osl-2-3',
    name: 'Grünerløkka Sector 3 High Street',
    zone: 'Grünerløkka',
    location: { latitude: 59.869900, longitude: 10.716200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Grünerløkka.',
  },
  {
    id: 'node-osl-3-1',
    name: 'Frogner Sector 1 High Street',
    zone: 'Frogner',
    location: { latitude: 59.875900, longitude: 10.720200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Frogner.',
  },
  {
    id: 'node-osl-3-2',
    name: 'Frogner Sector 2 High Street',
    zone: 'Frogner',
    location: { latitude: 59.878900, longitude: 10.723200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Frogner.',
  },
  {
    id: 'node-osl-3-3',
    name: 'Frogner Sector 3 High Street',
    zone: 'Frogner',
    location: { latitude: 59.881900, longitude: 10.726200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Frogner.',
  },
  {
    id: 'node-osl-4-1',
    name: 'Majorstuen Sector 1 High Street',
    zone: 'Majorstuen',
    location: { latitude: 59.887900, longitude: 10.730200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Majorstuen.',
  },
  {
    id: 'node-osl-4-2',
    name: 'Majorstuen Sector 2 High Street',
    zone: 'Majorstuen',
    location: { latitude: 59.890900, longitude: 10.733200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Majorstuen.',
  },
  {
    id: 'node-osl-4-3',
    name: 'Majorstuen Sector 3 High Street',
    zone: 'Majorstuen',
    location: { latitude: 59.893900, longitude: 10.736200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Majorstuen.',
  },
  {
    id: 'node-osl-5-1',
    name: 'Aker Brygge Sector 1 High Street',
    zone: 'Aker Brygge',
    location: { latitude: 59.899900, longitude: 10.740200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Aker Brygge.',
  },
  {
    id: 'node-osl-5-2',
    name: 'Aker Brygge Sector 2 High Street',
    zone: 'Aker Brygge',
    location: { latitude: 59.902900, longitude: 10.743200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Aker Brygge.',
  },
  {
    id: 'node-osl-5-3',
    name: 'Aker Brygge Sector 3 High Street',
    zone: 'Aker Brygge',
    location: { latitude: 59.905900, longitude: 10.746200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Aker Brygge.',
  },
  {
    id: 'node-osl-6-1',
    name: 'St. Hanshaugen Sector 1 High Street',
    zone: 'St. Hanshaugen',
    location: { latitude: 59.911900, longitude: 10.750200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in St. Hanshaugen.',
  },
  {
    id: 'node-osl-6-2',
    name: 'St. Hanshaugen Sector 2 High Street',
    zone: 'St. Hanshaugen',
    location: { latitude: 59.914900, longitude: 10.753200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in St. Hanshaugen.',
  },
  {
    id: 'node-osl-6-3',
    name: 'St. Hanshaugen Sector 3 High Street',
    zone: 'St. Hanshaugen',
    location: { latitude: 59.917900, longitude: 10.756200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in St. Hanshaugen.',
  },
  {
    id: 'node-osl-7-1',
    name: 'Tjuvholmen Sector 1 High Street',
    zone: 'Tjuvholmen',
    location: { latitude: 59.923900, longitude: 10.760200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tjuvholmen.',
  },
  {
    id: 'node-osl-7-2',
    name: 'Tjuvholmen Sector 2 High Street',
    zone: 'Tjuvholmen',
    location: { latitude: 59.926900, longitude: 10.763200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tjuvholmen.',
  },
  {
    id: 'node-osl-7-3',
    name: 'Tjuvholmen Sector 3 High Street',
    zone: 'Tjuvholmen',
    location: { latitude: 59.929900, longitude: 10.766200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tjuvholmen.',
  },
  {
    id: 'node-osl-8-1',
    name: 'Tøyen Sector 1 High Street',
    zone: 'Tøyen',
    location: { latitude: 59.935900, longitude: 10.770200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tøyen.',
  },
  {
    id: 'node-osl-8-2',
    name: 'Tøyen Sector 2 High Street',
    zone: 'Tøyen',
    location: { latitude: 59.938900, longitude: 10.773200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tøyen.',
  },
  {
    id: 'node-osl-8-3',
    name: 'Tøyen Sector 3 High Street',
    zone: 'Tøyen',
    location: { latitude: 59.941900, longitude: 10.776200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tøyen.',
  },
  {
    id: 'node-osl-9-1',
    name: 'Bislett Sector 1 High Street',
    zone: 'Bislett',
    location: { latitude: 59.947900, longitude: 10.780200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bislett.',
  },
  {
    id: 'node-osl-9-2',
    name: 'Bislett Sector 2 High Street',
    zone: 'Bislett',
    location: { latitude: 59.950900, longitude: 10.783200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bislett.',
  },
  {
    id: 'node-osl-9-3',
    name: 'Bislett Sector 3 High Street',
    zone: 'Bislett',
    location: { latitude: 59.953900, longitude: 10.786200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bislett.',
  },
  {
    id: 'node-osl-10-1',
    name: 'Nordstrand Sector 1 High Street',
    zone: 'Nordstrand',
    location: { latitude: 59.959900, longitude: 10.790200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nordstrand.',
  },
  {
    id: 'node-osl-10-2',
    name: 'Nordstrand Sector 2 High Street',
    zone: 'Nordstrand',
    location: { latitude: 59.962900, longitude: 10.793200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nordstrand.',
  },
  {
    id: 'node-osl-10-3',
    name: 'Nordstrand Sector 3 High Street',
    zone: 'Nordstrand',
    location: { latitude: 59.965900, longitude: 10.796200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nordstrand.',
  },
];

export const OSLO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-osl-1',
    fromNodeId: 'node-osl-1-1',
    toNodeId: 'node-osl-1-2',
    roadName: 'Sentrum Oslo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-2',
    fromNodeId: 'node-osl-1-2',
    toNodeId: 'node-osl-1-3',
    roadName: 'Sentrum Oslo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-3',
    fromNodeId: 'node-osl-2-1',
    toNodeId: 'node-osl-2-2',
    roadName: 'Grünerløkka Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-4',
    fromNodeId: 'node-osl-2-2',
    toNodeId: 'node-osl-2-3',
    roadName: 'Grünerløkka Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-5',
    fromNodeId: 'node-osl-3-1',
    toNodeId: 'node-osl-3-2',
    roadName: 'Frogner Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-6',
    fromNodeId: 'node-osl-3-2',
    toNodeId: 'node-osl-3-3',
    roadName: 'Frogner Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-7',
    fromNodeId: 'node-osl-4-1',
    toNodeId: 'node-osl-4-2',
    roadName: 'Majorstuen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-8',
    fromNodeId: 'node-osl-4-2',
    toNodeId: 'node-osl-4-3',
    roadName: 'Majorstuen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-9',
    fromNodeId: 'node-osl-5-1',
    toNodeId: 'node-osl-5-2',
    roadName: 'Aker Brygge Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-10',
    fromNodeId: 'node-osl-5-2',
    toNodeId: 'node-osl-5-3',
    roadName: 'Aker Brygge Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-11',
    fromNodeId: 'node-osl-6-1',
    toNodeId: 'node-osl-6-2',
    roadName: 'St. Hanshaugen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-12',
    fromNodeId: 'node-osl-6-2',
    toNodeId: 'node-osl-6-3',
    roadName: 'St. Hanshaugen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-13',
    fromNodeId: 'node-osl-7-1',
    toNodeId: 'node-osl-7-2',
    roadName: 'Tjuvholmen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-14',
    fromNodeId: 'node-osl-7-2',
    toNodeId: 'node-osl-7-3',
    roadName: 'Tjuvholmen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-15',
    fromNodeId: 'node-osl-8-1',
    toNodeId: 'node-osl-8-2',
    roadName: 'Tøyen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-16',
    fromNodeId: 'node-osl-8-2',
    toNodeId: 'node-osl-8-3',
    roadName: 'Tøyen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-17',
    fromNodeId: 'node-osl-9-1',
    toNodeId: 'node-osl-9-2',
    roadName: 'Bislett Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-18',
    fromNodeId: 'node-osl-9-2',
    toNodeId: 'node-osl-9-3',
    roadName: 'Bislett Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-19',
    fromNodeId: 'node-osl-10-1',
    toNodeId: 'node-osl-10-2',
    roadName: 'Nordstrand Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-osl-20',
    fromNodeId: 'node-osl-10-2',
    toNodeId: 'node-osl-10-3',
    roadName: 'Nordstrand Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
