/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Patna Magadh Region
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const PATNA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 25.5941,
  longitude: 85.1376,
};

export const PATNA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-pat-1-1',
    name: 'Boring Road Sector 1 High Street',
    zone: 'Boring Road',
    location: { latitude: 25.532100, longitude: 85.085600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Boring Road.',
  },
  {
    id: 'node-pat-1-2',
    name: 'Boring Road Sector 2 High Street',
    zone: 'Boring Road',
    location: { latitude: 25.535100, longitude: 85.088600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Boring Road.',
  },
  {
    id: 'node-pat-1-3',
    name: 'Boring Road Sector 3 High Street',
    zone: 'Boring Road',
    location: { latitude: 25.538100, longitude: 85.091600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Boring Road.',
  },
  {
    id: 'node-pat-2-1',
    name: 'Kankarbagh Sector 1 High Street',
    zone: 'Kankarbagh',
    location: { latitude: 25.544100, longitude: 85.095600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kankarbagh.',
  },
  {
    id: 'node-pat-2-2',
    name: 'Kankarbagh Sector 2 High Street',
    zone: 'Kankarbagh',
    location: { latitude: 25.547100, longitude: 85.098600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kankarbagh.',
  },
  {
    id: 'node-pat-2-3',
    name: 'Kankarbagh Sector 3 High Street',
    zone: 'Kankarbagh',
    location: { latitude: 25.550100, longitude: 85.101600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kankarbagh.',
  },
  {
    id: 'node-pat-3-1',
    name: 'Bailey Road Sector 1 High Street',
    zone: 'Bailey Road',
    location: { latitude: 25.556100, longitude: 85.105600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bailey Road.',
  },
  {
    id: 'node-pat-3-2',
    name: 'Bailey Road Sector 2 High Street',
    zone: 'Bailey Road',
    location: { latitude: 25.559100, longitude: 85.108600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bailey Road.',
  },
  {
    id: 'node-pat-3-3',
    name: 'Bailey Road Sector 3 High Street',
    zone: 'Bailey Road',
    location: { latitude: 25.562100, longitude: 85.111600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bailey Road.',
  },
  {
    id: 'node-pat-4-1',
    name: 'Fraser Road Sector 1 High Street',
    zone: 'Fraser Road',
    location: { latitude: 25.568100, longitude: 85.115600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fraser Road.',
  },
  {
    id: 'node-pat-4-2',
    name: 'Fraser Road Sector 2 High Street',
    zone: 'Fraser Road',
    location: { latitude: 25.571100, longitude: 85.118600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fraser Road.',
  },
  {
    id: 'node-pat-4-3',
    name: 'Fraser Road Sector 3 High Street',
    zone: 'Fraser Road',
    location: { latitude: 25.574100, longitude: 85.121600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fraser Road.',
  },
  {
    id: 'node-pat-5-1',
    name: 'Patliputra Colony Sector 1 High Street',
    zone: 'Patliputra Colony',
    location: { latitude: 25.580100, longitude: 85.125600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Patliputra Colony.',
  },
  {
    id: 'node-pat-5-2',
    name: 'Patliputra Colony Sector 2 High Street',
    zone: 'Patliputra Colony',
    location: { latitude: 25.583100, longitude: 85.128600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Patliputra Colony.',
  },
  {
    id: 'node-pat-5-3',
    name: 'Patliputra Colony Sector 3 High Street',
    zone: 'Patliputra Colony',
    location: { latitude: 25.586100, longitude: 85.131600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Patliputra Colony.',
  },
  {
    id: 'node-pat-6-1',
    name: 'Rajendra Nagar Sector 1 High Street',
    zone: 'Rajendra Nagar',
    location: { latitude: 25.592100, longitude: 85.135600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rajendra Nagar.',
  },
  {
    id: 'node-pat-6-2',
    name: 'Rajendra Nagar Sector 2 High Street',
    zone: 'Rajendra Nagar',
    location: { latitude: 25.595100, longitude: 85.138600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rajendra Nagar.',
  },
  {
    id: 'node-pat-6-3',
    name: 'Rajendra Nagar Sector 3 High Street',
    zone: 'Rajendra Nagar',
    location: { latitude: 25.598100, longitude: 85.141600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rajendra Nagar.',
  },
  {
    id: 'node-pat-7-1',
    name: 'Danapur Sector 1 High Street',
    zone: 'Danapur',
    location: { latitude: 25.604100, longitude: 85.145600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Danapur.',
  },
  {
    id: 'node-pat-7-2',
    name: 'Danapur Sector 2 High Street',
    zone: 'Danapur',
    location: { latitude: 25.607100, longitude: 85.148600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Danapur.',
  },
  {
    id: 'node-pat-7-3',
    name: 'Danapur Sector 3 High Street',
    zone: 'Danapur',
    location: { latitude: 25.610100, longitude: 85.151600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Danapur.',
  },
  {
    id: 'node-pat-8-1',
    name: 'Ashok Rajpath Sector 1 High Street',
    zone: 'Ashok Rajpath',
    location: { latitude: 25.616100, longitude: 85.155600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ashok Rajpath.',
  },
  {
    id: 'node-pat-8-2',
    name: 'Ashok Rajpath Sector 2 High Street',
    zone: 'Ashok Rajpath',
    location: { latitude: 25.619100, longitude: 85.158600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ashok Rajpath.',
  },
  {
    id: 'node-pat-8-3',
    name: 'Ashok Rajpath Sector 3 High Street',
    zone: 'Ashok Rajpath',
    location: { latitude: 25.622100, longitude: 85.161600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ashok Rajpath.',
  },
  {
    id: 'node-pat-9-1',
    name: 'Saguna More Sector 1 High Street',
    zone: 'Saguna More',
    location: { latitude: 25.628100, longitude: 85.165600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Saguna More.',
  },
  {
    id: 'node-pat-9-2',
    name: 'Saguna More Sector 2 High Street',
    zone: 'Saguna More',
    location: { latitude: 25.631100, longitude: 85.168600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Saguna More.',
  },
  {
    id: 'node-pat-9-3',
    name: 'Saguna More Sector 3 High Street',
    zone: 'Saguna More',
    location: { latitude: 25.634100, longitude: 85.171600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Saguna More.',
  },
  {
    id: 'node-pat-10-1',
    name: 'Anisabad Sector 1 High Street',
    zone: 'Anisabad',
    location: { latitude: 25.640100, longitude: 85.175600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Anisabad.',
  },
  {
    id: 'node-pat-10-2',
    name: 'Anisabad Sector 2 High Street',
    zone: 'Anisabad',
    location: { latitude: 25.643100, longitude: 85.178600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Anisabad.',
  },
  {
    id: 'node-pat-10-3',
    name: 'Anisabad Sector 3 High Street',
    zone: 'Anisabad',
    location: { latitude: 25.646100, longitude: 85.181600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Anisabad.',
  },
];

export const PATNA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-pat-1',
    fromNodeId: 'node-pat-1-1',
    toNodeId: 'node-pat-1-2',
    roadName: 'Boring Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-2',
    fromNodeId: 'node-pat-1-2',
    toNodeId: 'node-pat-1-3',
    roadName: 'Boring Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-3',
    fromNodeId: 'node-pat-2-1',
    toNodeId: 'node-pat-2-2',
    roadName: 'Kankarbagh Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-4',
    fromNodeId: 'node-pat-2-2',
    toNodeId: 'node-pat-2-3',
    roadName: 'Kankarbagh Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-5',
    fromNodeId: 'node-pat-3-1',
    toNodeId: 'node-pat-3-2',
    roadName: 'Bailey Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-6',
    fromNodeId: 'node-pat-3-2',
    toNodeId: 'node-pat-3-3',
    roadName: 'Bailey Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-7',
    fromNodeId: 'node-pat-4-1',
    toNodeId: 'node-pat-4-2',
    roadName: 'Fraser Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-8',
    fromNodeId: 'node-pat-4-2',
    toNodeId: 'node-pat-4-3',
    roadName: 'Fraser Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-9',
    fromNodeId: 'node-pat-5-1',
    toNodeId: 'node-pat-5-2',
    roadName: 'Patliputra Colony Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-10',
    fromNodeId: 'node-pat-5-2',
    toNodeId: 'node-pat-5-3',
    roadName: 'Patliputra Colony Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-11',
    fromNodeId: 'node-pat-6-1',
    toNodeId: 'node-pat-6-2',
    roadName: 'Rajendra Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-12',
    fromNodeId: 'node-pat-6-2',
    toNodeId: 'node-pat-6-3',
    roadName: 'Rajendra Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-13',
    fromNodeId: 'node-pat-7-1',
    toNodeId: 'node-pat-7-2',
    roadName: 'Danapur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-14',
    fromNodeId: 'node-pat-7-2',
    toNodeId: 'node-pat-7-3',
    roadName: 'Danapur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-15',
    fromNodeId: 'node-pat-8-1',
    toNodeId: 'node-pat-8-2',
    roadName: 'Ashok Rajpath Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-16',
    fromNodeId: 'node-pat-8-2',
    toNodeId: 'node-pat-8-3',
    roadName: 'Ashok Rajpath Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-17',
    fromNodeId: 'node-pat-9-1',
    toNodeId: 'node-pat-9-2',
    roadName: 'Saguna More Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-18',
    fromNodeId: 'node-pat-9-2',
    toNodeId: 'node-pat-9-3',
    roadName: 'Saguna More Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-19',
    fromNodeId: 'node-pat-10-1',
    toNodeId: 'node-pat-10-2',
    roadName: 'Anisabad Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pat-20',
    fromNodeId: 'node-pat-10-2',
    toNodeId: 'node-pat-10-3',
    roadName: 'Anisabad Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
