/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Philadelphia Center City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const PHILADELPHIA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 39.9526,
  longitude: -75.1652,
};

export const PHILADELPHIA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-phi-1-1',
    name: 'Center City Philly Sector 1 High Street',
    zone: 'Center City Philly',
    location: { latitude: 39.890600, longitude: -75.217200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Center City Philly.',
  },
  {
    id: 'node-phi-1-2',
    name: 'Center City Philly Sector 2 High Street',
    zone: 'Center City Philly',
    location: { latitude: 39.893600, longitude: -75.214200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Center City Philly.',
  },
  {
    id: 'node-phi-1-3',
    name: 'Center City Philly Sector 3 High Street',
    zone: 'Center City Philly',
    location: { latitude: 39.896600, longitude: -75.211200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Center City Philly.',
  },
  {
    id: 'node-phi-2-1',
    name: 'Old City Sector 1 High Street',
    zone: 'Old City',
    location: { latitude: 39.902600, longitude: -75.207200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old City.',
  },
  {
    id: 'node-phi-2-2',
    name: 'Old City Sector 2 High Street',
    zone: 'Old City',
    location: { latitude: 39.905600, longitude: -75.204200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old City.',
  },
  {
    id: 'node-phi-2-3',
    name: 'Old City Sector 3 High Street',
    zone: 'Old City',
    location: { latitude: 39.908600, longitude: -75.201200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old City.',
  },
  {
    id: 'node-phi-3-1',
    name: 'Rittenhouse Square Sector 1 High Street',
    zone: 'Rittenhouse Square',
    location: { latitude: 39.914600, longitude: -75.197200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rittenhouse Square.',
  },
  {
    id: 'node-phi-3-2',
    name: 'Rittenhouse Square Sector 2 High Street',
    zone: 'Rittenhouse Square',
    location: { latitude: 39.917600, longitude: -75.194200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rittenhouse Square.',
  },
  {
    id: 'node-phi-3-3',
    name: 'Rittenhouse Square Sector 3 High Street',
    zone: 'Rittenhouse Square',
    location: { latitude: 39.920600, longitude: -75.191200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rittenhouse Square.',
  },
  {
    id: 'node-phi-4-1',
    name: 'Fishtown Sector 1 High Street',
    zone: 'Fishtown',
    location: { latitude: 39.926600, longitude: -75.187200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fishtown.',
  },
  {
    id: 'node-phi-4-2',
    name: 'Fishtown Sector 2 High Street',
    zone: 'Fishtown',
    location: { latitude: 39.929600, longitude: -75.184200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fishtown.',
  },
  {
    id: 'node-phi-4-3',
    name: 'Fishtown Sector 3 High Street',
    zone: 'Fishtown',
    location: { latitude: 39.932600, longitude: -75.181200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fishtown.',
  },
  {
    id: 'node-phi-5-1',
    name: 'Northern Liberties Sector 1 High Street',
    zone: 'Northern Liberties',
    location: { latitude: 39.938600, longitude: -75.177200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Northern Liberties.',
  },
  {
    id: 'node-phi-5-2',
    name: 'Northern Liberties Sector 2 High Street',
    zone: 'Northern Liberties',
    location: { latitude: 39.941600, longitude: -75.174200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Northern Liberties.',
  },
  {
    id: 'node-phi-5-3',
    name: 'Northern Liberties Sector 3 High Street',
    zone: 'Northern Liberties',
    location: { latitude: 39.944600, longitude: -75.171200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Northern Liberties.',
  },
  {
    id: 'node-phi-6-1',
    name: 'University City Sector 1 High Street',
    zone: 'University City',
    location: { latitude: 39.950600, longitude: -75.167200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in University City.',
  },
  {
    id: 'node-phi-6-2',
    name: 'University City Sector 2 High Street',
    zone: 'University City',
    location: { latitude: 39.953600, longitude: -75.164200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in University City.',
  },
  {
    id: 'node-phi-6-3',
    name: 'University City Sector 3 High Street',
    zone: 'University City',
    location: { latitude: 39.956600, longitude: -75.161200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in University City.',
  },
  {
    id: 'node-phi-7-1',
    name: 'South Philly Sector 1 High Street',
    zone: 'South Philly',
    location: { latitude: 39.962600, longitude: -75.157200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in South Philly.',
  },
  {
    id: 'node-phi-7-2',
    name: 'South Philly Sector 2 High Street',
    zone: 'South Philly',
    location: { latitude: 39.965600, longitude: -75.154200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in South Philly.',
  },
  {
    id: 'node-phi-7-3',
    name: 'South Philly Sector 3 High Street',
    zone: 'South Philly',
    location: { latitude: 39.968600, longitude: -75.151200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in South Philly.',
  },
  {
    id: 'node-phi-8-1',
    name: 'Fairmount Sector 1 High Street',
    zone: 'Fairmount',
    location: { latitude: 39.974600, longitude: -75.147200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fairmount.',
  },
  {
    id: 'node-phi-8-2',
    name: 'Fairmount Sector 2 High Street',
    zone: 'Fairmount',
    location: { latitude: 39.977600, longitude: -75.144200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fairmount.',
  },
  {
    id: 'node-phi-8-3',
    name: 'Fairmount Sector 3 High Street',
    zone: 'Fairmount',
    location: { latitude: 39.980600, longitude: -75.141200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fairmount.',
  },
  {
    id: 'node-phi-9-1',
    name: 'Passyunk Square Sector 1 High Street',
    zone: 'Passyunk Square',
    location: { latitude: 39.986600, longitude: -75.137200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Passyunk Square.',
  },
  {
    id: 'node-phi-9-2',
    name: 'Passyunk Square Sector 2 High Street',
    zone: 'Passyunk Square',
    location: { latitude: 39.989600, longitude: -75.134200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Passyunk Square.',
  },
  {
    id: 'node-phi-9-3',
    name: 'Passyunk Square Sector 3 High Street',
    zone: 'Passyunk Square',
    location: { latitude: 39.992600, longitude: -75.131200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Passyunk Square.',
  },
  {
    id: 'node-phi-10-1',
    name: 'Manayunk Sector 1 High Street',
    zone: 'Manayunk',
    location: { latitude: 39.998600, longitude: -75.127200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Manayunk.',
  },
  {
    id: 'node-phi-10-2',
    name: 'Manayunk Sector 2 High Street',
    zone: 'Manayunk',
    location: { latitude: 40.001600, longitude: -75.124200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Manayunk.',
  },
  {
    id: 'node-phi-10-3',
    name: 'Manayunk Sector 3 High Street',
    zone: 'Manayunk',
    location: { latitude: 40.004600, longitude: -75.121200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Manayunk.',
  },
];

export const PHILADELPHIA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-phi-1',
    fromNodeId: 'node-phi-1-1',
    toNodeId: 'node-phi-1-2',
    roadName: 'Center City Philly Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-2',
    fromNodeId: 'node-phi-1-2',
    toNodeId: 'node-phi-1-3',
    roadName: 'Center City Philly Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-3',
    fromNodeId: 'node-phi-2-1',
    toNodeId: 'node-phi-2-2',
    roadName: 'Old City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-4',
    fromNodeId: 'node-phi-2-2',
    toNodeId: 'node-phi-2-3',
    roadName: 'Old City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-5',
    fromNodeId: 'node-phi-3-1',
    toNodeId: 'node-phi-3-2',
    roadName: 'Rittenhouse Square Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-6',
    fromNodeId: 'node-phi-3-2',
    toNodeId: 'node-phi-3-3',
    roadName: 'Rittenhouse Square Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-7',
    fromNodeId: 'node-phi-4-1',
    toNodeId: 'node-phi-4-2',
    roadName: 'Fishtown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-8',
    fromNodeId: 'node-phi-4-2',
    toNodeId: 'node-phi-4-3',
    roadName: 'Fishtown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-9',
    fromNodeId: 'node-phi-5-1',
    toNodeId: 'node-phi-5-2',
    roadName: 'Northern Liberties Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-10',
    fromNodeId: 'node-phi-5-2',
    toNodeId: 'node-phi-5-3',
    roadName: 'Northern Liberties Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-11',
    fromNodeId: 'node-phi-6-1',
    toNodeId: 'node-phi-6-2',
    roadName: 'University City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-12',
    fromNodeId: 'node-phi-6-2',
    toNodeId: 'node-phi-6-3',
    roadName: 'University City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-13',
    fromNodeId: 'node-phi-7-1',
    toNodeId: 'node-phi-7-2',
    roadName: 'South Philly Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-14',
    fromNodeId: 'node-phi-7-2',
    toNodeId: 'node-phi-7-3',
    roadName: 'South Philly Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-15',
    fromNodeId: 'node-phi-8-1',
    toNodeId: 'node-phi-8-2',
    roadName: 'Fairmount Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-16',
    fromNodeId: 'node-phi-8-2',
    toNodeId: 'node-phi-8-3',
    roadName: 'Fairmount Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-17',
    fromNodeId: 'node-phi-9-1',
    toNodeId: 'node-phi-9-2',
    roadName: 'Passyunk Square Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-18',
    fromNodeId: 'node-phi-9-2',
    toNodeId: 'node-phi-9-3',
    roadName: 'Passyunk Square Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-19',
    fromNodeId: 'node-phi-10-1',
    toNodeId: 'node-phi-10-2',
    roadName: 'Manayunk Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-phi-20',
    fromNodeId: 'node-phi-10-2',
    toNodeId: 'node-phi-10-3',
    roadName: 'Manayunk Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
