/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Phoenix Valley of Sun
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const PHOENIX_BASE_COORDINATE: GeoCoordinate = {
  latitude: 33.4484,
  longitude: -112.074,
};

export const PHOENIX_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-pho-1-1',
    name: 'Downtown Phoenix Sector 1 High Street',
    zone: 'Downtown Phoenix',
    location: { latitude: 33.386400, longitude: -112.126000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Phoenix.',
  },
  {
    id: 'node-pho-1-2',
    name: 'Downtown Phoenix Sector 2 High Street',
    zone: 'Downtown Phoenix',
    location: { latitude: 33.389400, longitude: -112.123000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Phoenix.',
  },
  {
    id: 'node-pho-1-3',
    name: 'Downtown Phoenix Sector 3 High Street',
    zone: 'Downtown Phoenix',
    location: { latitude: 33.392400, longitude: -112.120000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Phoenix.',
  },
  {
    id: 'node-pho-2-1',
    name: 'Scottsdale Sector 1 High Street',
    zone: 'Scottsdale',
    location: { latitude: 33.398400, longitude: -112.116000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Scottsdale.',
  },
  {
    id: 'node-pho-2-2',
    name: 'Scottsdale Sector 2 High Street',
    zone: 'Scottsdale',
    location: { latitude: 33.401400, longitude: -112.113000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Scottsdale.',
  },
  {
    id: 'node-pho-2-3',
    name: 'Scottsdale Sector 3 High Street',
    zone: 'Scottsdale',
    location: { latitude: 33.404400, longitude: -112.110000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Scottsdale.',
  },
  {
    id: 'node-pho-3-1',
    name: 'Biltmore Sector 1 High Street',
    zone: 'Biltmore',
    location: { latitude: 33.410400, longitude: -112.106000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Biltmore.',
  },
  {
    id: 'node-pho-3-2',
    name: 'Biltmore Sector 2 High Street',
    zone: 'Biltmore',
    location: { latitude: 33.413400, longitude: -112.103000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Biltmore.',
  },
  {
    id: 'node-pho-3-3',
    name: 'Biltmore Sector 3 High Street',
    zone: 'Biltmore',
    location: { latitude: 33.416400, longitude: -112.100000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Biltmore.',
  },
  {
    id: 'node-pho-4-1',
    name: 'Roosevelt Row Sector 1 High Street',
    zone: 'Roosevelt Row',
    location: { latitude: 33.422400, longitude: -112.096000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Roosevelt Row.',
  },
  {
    id: 'node-pho-4-2',
    name: 'Roosevelt Row Sector 2 High Street',
    zone: 'Roosevelt Row',
    location: { latitude: 33.425400, longitude: -112.093000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Roosevelt Row.',
  },
  {
    id: 'node-pho-4-3',
    name: 'Roosevelt Row Sector 3 High Street',
    zone: 'Roosevelt Row',
    location: { latitude: 33.428400, longitude: -112.090000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Roosevelt Row.',
  },
  {
    id: 'node-pho-5-1',
    name: 'Arcadia Sector 1 High Street',
    zone: 'Arcadia',
    location: { latitude: 33.434400, longitude: -112.086000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Arcadia.',
  },
  {
    id: 'node-pho-5-2',
    name: 'Arcadia Sector 2 High Street',
    zone: 'Arcadia',
    location: { latitude: 33.437400, longitude: -112.083000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Arcadia.',
  },
  {
    id: 'node-pho-5-3',
    name: 'Arcadia Sector 3 High Street',
    zone: 'Arcadia',
    location: { latitude: 33.440400, longitude: -112.080000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Arcadia.',
  },
  {
    id: 'node-pho-6-1',
    name: 'Tempe Sector 1 High Street',
    zone: 'Tempe',
    location: { latitude: 33.446400, longitude: -112.076000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tempe.',
  },
  {
    id: 'node-pho-6-2',
    name: 'Tempe Sector 2 High Street',
    zone: 'Tempe',
    location: { latitude: 33.449400, longitude: -112.073000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tempe.',
  },
  {
    id: 'node-pho-6-3',
    name: 'Tempe Sector 3 High Street',
    zone: 'Tempe',
    location: { latitude: 33.452400, longitude: -112.070000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tempe.',
  },
  {
    id: 'node-pho-7-1',
    name: 'Paradise Valley Sector 1 High Street',
    zone: 'Paradise Valley',
    location: { latitude: 33.458400, longitude: -112.066000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Paradise Valley.',
  },
  {
    id: 'node-pho-7-2',
    name: 'Paradise Valley Sector 2 High Street',
    zone: 'Paradise Valley',
    location: { latitude: 33.461400, longitude: -112.063000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Paradise Valley.',
  },
  {
    id: 'node-pho-7-3',
    name: 'Paradise Valley Sector 3 High Street',
    zone: 'Paradise Valley',
    location: { latitude: 33.464400, longitude: -112.060000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Paradise Valley.',
  },
  {
    id: 'node-pho-8-1',
    name: 'Central Phoenix Sector 1 High Street',
    zone: 'Central Phoenix',
    location: { latitude: 33.470400, longitude: -112.056000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Central Phoenix.',
  },
  {
    id: 'node-pho-8-2',
    name: 'Central Phoenix Sector 2 High Street',
    zone: 'Central Phoenix',
    location: { latitude: 33.473400, longitude: -112.053000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Central Phoenix.',
  },
  {
    id: 'node-pho-8-3',
    name: 'Central Phoenix Sector 3 High Street',
    zone: 'Central Phoenix',
    location: { latitude: 33.476400, longitude: -112.050000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Central Phoenix.',
  },
  {
    id: 'node-pho-9-1',
    name: 'Chandler Sector 1 High Street',
    zone: 'Chandler',
    location: { latitude: 33.482400, longitude: -112.046000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chandler.',
  },
  {
    id: 'node-pho-9-2',
    name: 'Chandler Sector 2 High Street',
    zone: 'Chandler',
    location: { latitude: 33.485400, longitude: -112.043000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chandler.',
  },
  {
    id: 'node-pho-9-3',
    name: 'Chandler Sector 3 High Street',
    zone: 'Chandler',
    location: { latitude: 33.488400, longitude: -112.040000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chandler.',
  },
  {
    id: 'node-pho-10-1',
    name: 'Gilbert Sector 1 High Street',
    zone: 'Gilbert',
    location: { latitude: 33.494400, longitude: -112.036000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gilbert.',
  },
  {
    id: 'node-pho-10-2',
    name: 'Gilbert Sector 2 High Street',
    zone: 'Gilbert',
    location: { latitude: 33.497400, longitude: -112.033000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gilbert.',
  },
  {
    id: 'node-pho-10-3',
    name: 'Gilbert Sector 3 High Street',
    zone: 'Gilbert',
    location: { latitude: 33.500400, longitude: -112.030000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gilbert.',
  },
];

export const PHOENIX_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-pho-1',
    fromNodeId: 'node-pho-1-1',
    toNodeId: 'node-pho-1-2',
    roadName: 'Downtown Phoenix Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-2',
    fromNodeId: 'node-pho-1-2',
    toNodeId: 'node-pho-1-3',
    roadName: 'Downtown Phoenix Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-3',
    fromNodeId: 'node-pho-2-1',
    toNodeId: 'node-pho-2-2',
    roadName: 'Scottsdale Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-4',
    fromNodeId: 'node-pho-2-2',
    toNodeId: 'node-pho-2-3',
    roadName: 'Scottsdale Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-5',
    fromNodeId: 'node-pho-3-1',
    toNodeId: 'node-pho-3-2',
    roadName: 'Biltmore Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-6',
    fromNodeId: 'node-pho-3-2',
    toNodeId: 'node-pho-3-3',
    roadName: 'Biltmore Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-7',
    fromNodeId: 'node-pho-4-1',
    toNodeId: 'node-pho-4-2',
    roadName: 'Roosevelt Row Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-8',
    fromNodeId: 'node-pho-4-2',
    toNodeId: 'node-pho-4-3',
    roadName: 'Roosevelt Row Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-9',
    fromNodeId: 'node-pho-5-1',
    toNodeId: 'node-pho-5-2',
    roadName: 'Arcadia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-10',
    fromNodeId: 'node-pho-5-2',
    toNodeId: 'node-pho-5-3',
    roadName: 'Arcadia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-11',
    fromNodeId: 'node-pho-6-1',
    toNodeId: 'node-pho-6-2',
    roadName: 'Tempe Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-12',
    fromNodeId: 'node-pho-6-2',
    toNodeId: 'node-pho-6-3',
    roadName: 'Tempe Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-13',
    fromNodeId: 'node-pho-7-1',
    toNodeId: 'node-pho-7-2',
    roadName: 'Paradise Valley Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-14',
    fromNodeId: 'node-pho-7-2',
    toNodeId: 'node-pho-7-3',
    roadName: 'Paradise Valley Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-15',
    fromNodeId: 'node-pho-8-1',
    toNodeId: 'node-pho-8-2',
    roadName: 'Central Phoenix Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-16',
    fromNodeId: 'node-pho-8-2',
    toNodeId: 'node-pho-8-3',
    roadName: 'Central Phoenix Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-17',
    fromNodeId: 'node-pho-9-1',
    toNodeId: 'node-pho-9-2',
    roadName: 'Chandler Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-18',
    fromNodeId: 'node-pho-9-2',
    toNodeId: 'node-pho-9-3',
    roadName: 'Chandler Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-19',
    fromNodeId: 'node-pho-10-1',
    toNodeId: 'node-pho-10-2',
    roadName: 'Gilbert Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pho-20',
    fromNodeId: 'node-pho-10-2',
    toNodeId: 'node-pho-10-3',
    roadName: 'Gilbert Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
