/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Porto Douro River Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const PORTO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 41.1579,
  longitude: -8.6291,
};

export const PORTO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-por-1-1',
    name: 'Ribeira Sector 1 High Street',
    zone: 'Ribeira',
    location: { latitude: 41.095900, longitude: -8.681100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ribeira.',
  },
  {
    id: 'node-por-1-2',
    name: 'Ribeira Sector 2 High Street',
    zone: 'Ribeira',
    location: { latitude: 41.098900, longitude: -8.678100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ribeira.',
  },
  {
    id: 'node-por-1-3',
    name: 'Ribeira Sector 3 High Street',
    zone: 'Ribeira',
    location: { latitude: 41.101900, longitude: -8.675100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ribeira.',
  },
  {
    id: 'node-por-2-1',
    name: 'Baixa Porto Sector 1 High Street',
    zone: 'Baixa Porto',
    location: { latitude: 41.107900, longitude: -8.671100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Baixa Porto.',
  },
  {
    id: 'node-por-2-2',
    name: 'Baixa Porto Sector 2 High Street',
    zone: 'Baixa Porto',
    location: { latitude: 41.110900, longitude: -8.668100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Baixa Porto.',
  },
  {
    id: 'node-por-2-3',
    name: 'Baixa Porto Sector 3 High Street',
    zone: 'Baixa Porto',
    location: { latitude: 41.113900, longitude: -8.665100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Baixa Porto.',
  },
  {
    id: 'node-por-3-1',
    name: 'Cedofeita Sector 1 High Street',
    zone: 'Cedofeita',
    location: { latitude: 41.119900, longitude: -8.661100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cedofeita.',
  },
  {
    id: 'node-por-3-2',
    name: 'Cedofeita Sector 2 High Street',
    zone: 'Cedofeita',
    location: { latitude: 41.122900, longitude: -8.658100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cedofeita.',
  },
  {
    id: 'node-por-3-3',
    name: 'Cedofeita Sector 3 High Street',
    zone: 'Cedofeita',
    location: { latitude: 41.125900, longitude: -8.655100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cedofeita.',
  },
  {
    id: 'node-por-4-1',
    name: 'Foz do Douro Sector 1 High Street',
    zone: 'Foz do Douro',
    location: { latitude: 41.131900, longitude: -8.651100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Foz do Douro.',
  },
  {
    id: 'node-por-4-2',
    name: 'Foz do Douro Sector 2 High Street',
    zone: 'Foz do Douro',
    location: { latitude: 41.134900, longitude: -8.648100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Foz do Douro.',
  },
  {
    id: 'node-por-4-3',
    name: 'Foz do Douro Sector 3 High Street',
    zone: 'Foz do Douro',
    location: { latitude: 41.137900, longitude: -8.645100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Foz do Douro.',
  },
  {
    id: 'node-por-5-1',
    name: 'Boavista Sector 1 High Street',
    zone: 'Boavista',
    location: { latitude: 41.143900, longitude: -8.641100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Boavista.',
  },
  {
    id: 'node-por-5-2',
    name: 'Boavista Sector 2 High Street',
    zone: 'Boavista',
    location: { latitude: 41.146900, longitude: -8.638100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Boavista.',
  },
  {
    id: 'node-por-5-3',
    name: 'Boavista Sector 3 High Street',
    zone: 'Boavista',
    location: { latitude: 41.149900, longitude: -8.635100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Boavista.',
  },
  {
    id: 'node-por-6-1',
    name: 'Bonfim Sector 1 High Street',
    zone: 'Bonfim',
    location: { latitude: 41.155900, longitude: -8.631100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bonfim.',
  },
  {
    id: 'node-por-6-2',
    name: 'Bonfim Sector 2 High Street',
    zone: 'Bonfim',
    location: { latitude: 41.158900, longitude: -8.628100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bonfim.',
  },
  {
    id: 'node-por-6-3',
    name: 'Bonfim Sector 3 High Street',
    zone: 'Bonfim',
    location: { latitude: 41.161900, longitude: -8.625100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bonfim.',
  },
  {
    id: 'node-por-7-1',
    name: 'Miragaia Sector 1 High Street',
    zone: 'Miragaia',
    location: { latitude: 41.167900, longitude: -8.621100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Miragaia.',
  },
  {
    id: 'node-por-7-2',
    name: 'Miragaia Sector 2 High Street',
    zone: 'Miragaia',
    location: { latitude: 41.170900, longitude: -8.618100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Miragaia.',
  },
  {
    id: 'node-por-7-3',
    name: 'Miragaia Sector 3 High Street',
    zone: 'Miragaia',
    location: { latitude: 41.173900, longitude: -8.615100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Miragaia.',
  },
  {
    id: 'node-por-8-1',
    name: 'Massarelos Sector 1 High Street',
    zone: 'Massarelos',
    location: { latitude: 41.179900, longitude: -8.611100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Massarelos.',
  },
  {
    id: 'node-por-8-2',
    name: 'Massarelos Sector 2 High Street',
    zone: 'Massarelos',
    location: { latitude: 41.182900, longitude: -8.608100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Massarelos.',
  },
  {
    id: 'node-por-8-3',
    name: 'Massarelos Sector 3 High Street',
    zone: 'Massarelos',
    location: { latitude: 41.185900, longitude: -8.605100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Massarelos.',
  },
  {
    id: 'node-por-9-1',
    name: 'Campanhã Sector 1 High Street',
    zone: 'Campanhã',
    location: { latitude: 41.191900, longitude: -8.601100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Campanhã.',
  },
  {
    id: 'node-por-9-2',
    name: 'Campanhã Sector 2 High Street',
    zone: 'Campanhã',
    location: { latitude: 41.194900, longitude: -8.598100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Campanhã.',
  },
  {
    id: 'node-por-9-3',
    name: 'Campanhã Sector 3 High Street',
    zone: 'Campanhã',
    location: { latitude: 41.197900, longitude: -8.595100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Campanhã.',
  },
  {
    id: 'node-por-10-1',
    name: 'Vila Nova de Gaia Sector 1 High Street',
    zone: 'Vila Nova de Gaia',
    location: { latitude: 41.203900, longitude: -8.591100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vila Nova de Gaia.',
  },
  {
    id: 'node-por-10-2',
    name: 'Vila Nova de Gaia Sector 2 High Street',
    zone: 'Vila Nova de Gaia',
    location: { latitude: 41.206900, longitude: -8.588100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vila Nova de Gaia.',
  },
  {
    id: 'node-por-10-3',
    name: 'Vila Nova de Gaia Sector 3 High Street',
    zone: 'Vila Nova de Gaia',
    location: { latitude: 41.209900, longitude: -8.585100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vila Nova de Gaia.',
  },
];

export const PORTO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-por-1',
    fromNodeId: 'node-por-1-1',
    toNodeId: 'node-por-1-2',
    roadName: 'Ribeira Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-2',
    fromNodeId: 'node-por-1-2',
    toNodeId: 'node-por-1-3',
    roadName: 'Ribeira Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-3',
    fromNodeId: 'node-por-2-1',
    toNodeId: 'node-por-2-2',
    roadName: 'Baixa Porto Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-4',
    fromNodeId: 'node-por-2-2',
    toNodeId: 'node-por-2-3',
    roadName: 'Baixa Porto Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-5',
    fromNodeId: 'node-por-3-1',
    toNodeId: 'node-por-3-2',
    roadName: 'Cedofeita Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-6',
    fromNodeId: 'node-por-3-2',
    toNodeId: 'node-por-3-3',
    roadName: 'Cedofeita Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-7',
    fromNodeId: 'node-por-4-1',
    toNodeId: 'node-por-4-2',
    roadName: 'Foz do Douro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-8',
    fromNodeId: 'node-por-4-2',
    toNodeId: 'node-por-4-3',
    roadName: 'Foz do Douro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-9',
    fromNodeId: 'node-por-5-1',
    toNodeId: 'node-por-5-2',
    roadName: 'Boavista Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-10',
    fromNodeId: 'node-por-5-2',
    toNodeId: 'node-por-5-3',
    roadName: 'Boavista Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-11',
    fromNodeId: 'node-por-6-1',
    toNodeId: 'node-por-6-2',
    roadName: 'Bonfim Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-12',
    fromNodeId: 'node-por-6-2',
    toNodeId: 'node-por-6-3',
    roadName: 'Bonfim Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-13',
    fromNodeId: 'node-por-7-1',
    toNodeId: 'node-por-7-2',
    roadName: 'Miragaia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-14',
    fromNodeId: 'node-por-7-2',
    toNodeId: 'node-por-7-3',
    roadName: 'Miragaia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-15',
    fromNodeId: 'node-por-8-1',
    toNodeId: 'node-por-8-2',
    roadName: 'Massarelos Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-16',
    fromNodeId: 'node-por-8-2',
    toNodeId: 'node-por-8-3',
    roadName: 'Massarelos Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-17',
    fromNodeId: 'node-por-9-1',
    toNodeId: 'node-por-9-2',
    roadName: 'Campanhã Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-18',
    fromNodeId: 'node-por-9-2',
    toNodeId: 'node-por-9-3',
    roadName: 'Campanhã Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-19',
    fromNodeId: 'node-por-10-1',
    toNodeId: 'node-por-10-2',
    roadName: 'Vila Nova de Gaia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-20',
    fromNodeId: 'node-por-10-2',
    toNodeId: 'node-por-10-3',
    roadName: 'Vila Nova de Gaia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
