/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Portland Rose City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const PORTLAND_BASE_COORDINATE: GeoCoordinate = {
  latitude: 45.5152,
  longitude: -122.6784,
};

export const PORTLAND_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-por-1-1',
    name: 'Downtown Portland Sector 1 High Street',
    zone: 'Downtown Portland',
    location: { latitude: 45.453200, longitude: -122.730400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Portland.',
  },
  {
    id: 'node-por-1-2',
    name: 'Downtown Portland Sector 2 High Street',
    zone: 'Downtown Portland',
    location: { latitude: 45.456200, longitude: -122.727400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Portland.',
  },
  {
    id: 'node-por-1-3',
    name: 'Downtown Portland Sector 3 High Street',
    zone: 'Downtown Portland',
    location: { latitude: 45.459200, longitude: -122.724400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Portland.',
  },
  {
    id: 'node-por-2-1',
    name: 'Pearl District Sector 1 High Street',
    zone: 'Pearl District',
    location: { latitude: 45.465200, longitude: -122.720400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pearl District.',
  },
  {
    id: 'node-por-2-2',
    name: 'Pearl District Sector 2 High Street',
    zone: 'Pearl District',
    location: { latitude: 45.468200, longitude: -122.717400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pearl District.',
  },
  {
    id: 'node-por-2-3',
    name: 'Pearl District Sector 3 High Street',
    zone: 'Pearl District',
    location: { latitude: 45.471200, longitude: -122.714400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pearl District.',
  },
  {
    id: 'node-por-3-1',
    name: 'Hawthorne Sector 1 High Street',
    zone: 'Hawthorne',
    location: { latitude: 45.477200, longitude: -122.710400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hawthorne.',
  },
  {
    id: 'node-por-3-2',
    name: 'Hawthorne Sector 2 High Street',
    zone: 'Hawthorne',
    location: { latitude: 45.480200, longitude: -122.707400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hawthorne.',
  },
  {
    id: 'node-por-3-3',
    name: 'Hawthorne Sector 3 High Street',
    zone: 'Hawthorne',
    location: { latitude: 45.483200, longitude: -122.704400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hawthorne.',
  },
  {
    id: 'node-por-4-1',
    name: 'Alberta Arts Sector 1 High Street',
    zone: 'Alberta Arts',
    location: { latitude: 45.489200, longitude: -122.700400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Alberta Arts.',
  },
  {
    id: 'node-por-4-2',
    name: 'Alberta Arts Sector 2 High Street',
    zone: 'Alberta Arts',
    location: { latitude: 45.492200, longitude: -122.697400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Alberta Arts.',
  },
  {
    id: 'node-por-4-3',
    name: 'Alberta Arts Sector 3 High Street',
    zone: 'Alberta Arts',
    location: { latitude: 45.495200, longitude: -122.694400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Alberta Arts.',
  },
  {
    id: 'node-por-5-1',
    name: 'Division Sector 1 High Street',
    zone: 'Division',
    location: { latitude: 45.501200, longitude: -122.690400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Division.',
  },
  {
    id: 'node-por-5-2',
    name: 'Division Sector 2 High Street',
    zone: 'Division',
    location: { latitude: 45.504200, longitude: -122.687400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Division.',
  },
  {
    id: 'node-por-5-3',
    name: 'Division Sector 3 High Street',
    zone: 'Division',
    location: { latitude: 45.507200, longitude: -122.684400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Division.',
  },
  {
    id: 'node-por-6-1',
    name: 'Nob Hill Sector 1 High Street',
    zone: 'Nob Hill',
    location: { latitude: 45.513200, longitude: -122.680400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nob Hill.',
  },
  {
    id: 'node-por-6-2',
    name: 'Nob Hill Sector 2 High Street',
    zone: 'Nob Hill',
    location: { latitude: 45.516200, longitude: -122.677400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nob Hill.',
  },
  {
    id: 'node-por-6-3',
    name: 'Nob Hill Sector 3 High Street',
    zone: 'Nob Hill',
    location: { latitude: 45.519200, longitude: -122.674400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nob Hill.',
  },
  {
    id: 'node-por-7-1',
    name: 'Mississippi Ave Sector 1 High Street',
    zone: 'Mississippi Ave',
    location: { latitude: 45.525200, longitude: -122.670400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mississippi Ave.',
  },
  {
    id: 'node-por-7-2',
    name: 'Mississippi Ave Sector 2 High Street',
    zone: 'Mississippi Ave',
    location: { latitude: 45.528200, longitude: -122.667400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mississippi Ave.',
  },
  {
    id: 'node-por-7-3',
    name: 'Mississippi Ave Sector 3 High Street',
    zone: 'Mississippi Ave',
    location: { latitude: 45.531200, longitude: -122.664400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mississippi Ave.',
  },
  {
    id: 'node-por-8-1',
    name: 'Belmont Sector 1 High Street',
    zone: 'Belmont',
    location: { latitude: 45.537200, longitude: -122.660400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Belmont.',
  },
  {
    id: 'node-por-8-2',
    name: 'Belmont Sector 2 High Street',
    zone: 'Belmont',
    location: { latitude: 45.540200, longitude: -122.657400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Belmont.',
  },
  {
    id: 'node-por-8-3',
    name: 'Belmont Sector 3 High Street',
    zone: 'Belmont',
    location: { latitude: 45.543200, longitude: -122.654400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Belmont.',
  },
  {
    id: 'node-por-9-1',
    name: 'Sellwood Sector 1 High Street',
    zone: 'Sellwood',
    location: { latitude: 45.549200, longitude: -122.650400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sellwood.',
  },
  {
    id: 'node-por-9-2',
    name: 'Sellwood Sector 2 High Street',
    zone: 'Sellwood',
    location: { latitude: 45.552200, longitude: -122.647400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sellwood.',
  },
  {
    id: 'node-por-9-3',
    name: 'Sellwood Sector 3 High Street',
    zone: 'Sellwood',
    location: { latitude: 45.555200, longitude: -122.644400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sellwood.',
  },
  {
    id: 'node-por-10-1',
    name: 'Central Eastside Sector 1 High Street',
    zone: 'Central Eastside',
    location: { latitude: 45.561200, longitude: -122.640400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Central Eastside.',
  },
  {
    id: 'node-por-10-2',
    name: 'Central Eastside Sector 2 High Street',
    zone: 'Central Eastside',
    location: { latitude: 45.564200, longitude: -122.637400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Central Eastside.',
  },
  {
    id: 'node-por-10-3',
    name: 'Central Eastside Sector 3 High Street',
    zone: 'Central Eastside',
    location: { latitude: 45.567200, longitude: -122.634400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Central Eastside.',
  },
];

export const PORTLAND_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-por-1',
    fromNodeId: 'node-por-1-1',
    toNodeId: 'node-por-1-2',
    roadName: 'Downtown Portland Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-2',
    fromNodeId: 'node-por-1-2',
    toNodeId: 'node-por-1-3',
    roadName: 'Downtown Portland Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-3',
    fromNodeId: 'node-por-2-1',
    toNodeId: 'node-por-2-2',
    roadName: 'Pearl District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-4',
    fromNodeId: 'node-por-2-2',
    toNodeId: 'node-por-2-3',
    roadName: 'Pearl District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-5',
    fromNodeId: 'node-por-3-1',
    toNodeId: 'node-por-3-2',
    roadName: 'Hawthorne Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-6',
    fromNodeId: 'node-por-3-2',
    toNodeId: 'node-por-3-3',
    roadName: 'Hawthorne Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-7',
    fromNodeId: 'node-por-4-1',
    toNodeId: 'node-por-4-2',
    roadName: 'Alberta Arts Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-8',
    fromNodeId: 'node-por-4-2',
    toNodeId: 'node-por-4-3',
    roadName: 'Alberta Arts Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-9',
    fromNodeId: 'node-por-5-1',
    toNodeId: 'node-por-5-2',
    roadName: 'Division Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-10',
    fromNodeId: 'node-por-5-2',
    toNodeId: 'node-por-5-3',
    roadName: 'Division Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-11',
    fromNodeId: 'node-por-6-1',
    toNodeId: 'node-por-6-2',
    roadName: 'Nob Hill Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-12',
    fromNodeId: 'node-por-6-2',
    toNodeId: 'node-por-6-3',
    roadName: 'Nob Hill Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-13',
    fromNodeId: 'node-por-7-1',
    toNodeId: 'node-por-7-2',
    roadName: 'Mississippi Ave Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-14',
    fromNodeId: 'node-por-7-2',
    toNodeId: 'node-por-7-3',
    roadName: 'Mississippi Ave Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-15',
    fromNodeId: 'node-por-8-1',
    toNodeId: 'node-por-8-2',
    roadName: 'Belmont Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-16',
    fromNodeId: 'node-por-8-2',
    toNodeId: 'node-por-8-3',
    roadName: 'Belmont Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-17',
    fromNodeId: 'node-por-9-1',
    toNodeId: 'node-por-9-2',
    roadName: 'Sellwood Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-18',
    fromNodeId: 'node-por-9-2',
    toNodeId: 'node-por-9-3',
    roadName: 'Sellwood Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-19',
    fromNodeId: 'node-por-10-1',
    toNodeId: 'node-por-10-2',
    roadName: 'Central Eastside Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-por-20',
    fromNodeId: 'node-por-10-2',
    toNodeId: 'node-por-10-3',
    roadName: 'Central Eastside Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
