/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Prague Vltava Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const PRAGUE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 50.0755,
  longitude: 14.4378,
};

export const PRAGUE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-pra-1-1',
    name: 'Old Town Prague Sector 1 High Street',
    zone: 'Old Town Prague',
    location: { latitude: 50.013500, longitude: 14.385800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old Town Prague.',
  },
  {
    id: 'node-pra-1-2',
    name: 'Old Town Prague Sector 2 High Street',
    zone: 'Old Town Prague',
    location: { latitude: 50.016500, longitude: 14.388800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old Town Prague.',
  },
  {
    id: 'node-pra-1-3',
    name: 'Old Town Prague Sector 3 High Street',
    zone: 'Old Town Prague',
    location: { latitude: 50.019500, longitude: 14.391800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old Town Prague.',
  },
  {
    id: 'node-pra-2-1',
    name: 'Malá Strana Sector 1 High Street',
    zone: 'Malá Strana',
    location: { latitude: 50.025500, longitude: 14.395800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Malá Strana.',
  },
  {
    id: 'node-pra-2-2',
    name: 'Malá Strana Sector 2 High Street',
    zone: 'Malá Strana',
    location: { latitude: 50.028500, longitude: 14.398800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Malá Strana.',
  },
  {
    id: 'node-pra-2-3',
    name: 'Malá Strana Sector 3 High Street',
    zone: 'Malá Strana',
    location: { latitude: 50.031500, longitude: 14.401800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Malá Strana.',
  },
  {
    id: 'node-pra-3-1',
    name: 'Vinohrady Sector 1 High Street',
    zone: 'Vinohrady',
    location: { latitude: 50.037500, longitude: 14.405800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vinohrady.',
  },
  {
    id: 'node-pra-3-2',
    name: 'Vinohrady Sector 2 High Street',
    zone: 'Vinohrady',
    location: { latitude: 50.040500, longitude: 14.408800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vinohrady.',
  },
  {
    id: 'node-pra-3-3',
    name: 'Vinohrady Sector 3 High Street',
    zone: 'Vinohrady',
    location: { latitude: 50.043500, longitude: 14.411800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vinohrady.',
  },
  {
    id: 'node-pra-4-1',
    name: 'Žižkov Sector 1 High Street',
    zone: 'Žižkov',
    location: { latitude: 50.049500, longitude: 14.415800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Žižkov.',
  },
  {
    id: 'node-pra-4-2',
    name: 'Žižkov Sector 2 High Street',
    zone: 'Žižkov',
    location: { latitude: 50.052500, longitude: 14.418800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Žižkov.',
  },
  {
    id: 'node-pra-4-3',
    name: 'Žižkov Sector 3 High Street',
    zone: 'Žižkov',
    location: { latitude: 50.055500, longitude: 14.421800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Žižkov.',
  },
  {
    id: 'node-pra-5-1',
    name: 'Holešovice Sector 1 High Street',
    zone: 'Holešovice',
    location: { latitude: 50.061500, longitude: 14.425800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Holešovice.',
  },
  {
    id: 'node-pra-5-2',
    name: 'Holešovice Sector 2 High Street',
    zone: 'Holešovice',
    location: { latitude: 50.064500, longitude: 14.428800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Holešovice.',
  },
  {
    id: 'node-pra-5-3',
    name: 'Holešovice Sector 3 High Street',
    zone: 'Holešovice',
    location: { latitude: 50.067500, longitude: 14.431800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Holešovice.',
  },
  {
    id: 'node-pra-6-1',
    name: 'Karlín Sector 1 High Street',
    zone: 'Karlín',
    location: { latitude: 50.073500, longitude: 14.435800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Karlín.',
  },
  {
    id: 'node-pra-6-2',
    name: 'Karlín Sector 2 High Street',
    zone: 'Karlín',
    location: { latitude: 50.076500, longitude: 14.438800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Karlín.',
  },
  {
    id: 'node-pra-6-3',
    name: 'Karlín Sector 3 High Street',
    zone: 'Karlín',
    location: { latitude: 50.079500, longitude: 14.441800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Karlín.',
  },
  {
    id: 'node-pra-7-1',
    name: 'Smíchov Sector 1 High Street',
    zone: 'Smíchov',
    location: { latitude: 50.085500, longitude: 14.445800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Smíchov.',
  },
  {
    id: 'node-pra-7-2',
    name: 'Smíchov Sector 2 High Street',
    zone: 'Smíchov',
    location: { latitude: 50.088500, longitude: 14.448800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Smíchov.',
  },
  {
    id: 'node-pra-7-3',
    name: 'Smíchov Sector 3 High Street',
    zone: 'Smíchov',
    location: { latitude: 50.091500, longitude: 14.451800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Smíchov.',
  },
  {
    id: 'node-pra-8-1',
    name: 'Nové Město Sector 1 High Street',
    zone: 'Nové Město',
    location: { latitude: 50.097500, longitude: 14.455800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nové Město.',
  },
  {
    id: 'node-pra-8-2',
    name: 'Nové Město Sector 2 High Street',
    zone: 'Nové Město',
    location: { latitude: 50.100500, longitude: 14.458800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nové Město.',
  },
  {
    id: 'node-pra-8-3',
    name: 'Nové Město Sector 3 High Street',
    zone: 'Nové Město',
    location: { latitude: 50.103500, longitude: 14.461800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nové Město.',
  },
  {
    id: 'node-pra-9-1',
    name: 'Dejvice Sector 1 High Street',
    zone: 'Dejvice',
    location: { latitude: 50.109500, longitude: 14.465800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dejvice.',
  },
  {
    id: 'node-pra-9-2',
    name: 'Dejvice Sector 2 High Street',
    zone: 'Dejvice',
    location: { latitude: 50.112500, longitude: 14.468800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dejvice.',
  },
  {
    id: 'node-pra-9-3',
    name: 'Dejvice Sector 3 High Street',
    zone: 'Dejvice',
    location: { latitude: 50.115500, longitude: 14.471800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dejvice.',
  },
  {
    id: 'node-pra-10-1',
    name: 'Vršovice Sector 1 High Street',
    zone: 'Vršovice',
    location: { latitude: 50.121500, longitude: 14.475800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vršovice.',
  },
  {
    id: 'node-pra-10-2',
    name: 'Vršovice Sector 2 High Street',
    zone: 'Vršovice',
    location: { latitude: 50.124500, longitude: 14.478800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vršovice.',
  },
  {
    id: 'node-pra-10-3',
    name: 'Vršovice Sector 3 High Street',
    zone: 'Vršovice',
    location: { latitude: 50.127500, longitude: 14.481800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vršovice.',
  },
];

export const PRAGUE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-pra-1',
    fromNodeId: 'node-pra-1-1',
    toNodeId: 'node-pra-1-2',
    roadName: 'Old Town Prague Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-2',
    fromNodeId: 'node-pra-1-2',
    toNodeId: 'node-pra-1-3',
    roadName: 'Old Town Prague Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-3',
    fromNodeId: 'node-pra-2-1',
    toNodeId: 'node-pra-2-2',
    roadName: 'Malá Strana Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-4',
    fromNodeId: 'node-pra-2-2',
    toNodeId: 'node-pra-2-3',
    roadName: 'Malá Strana Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-5',
    fromNodeId: 'node-pra-3-1',
    toNodeId: 'node-pra-3-2',
    roadName: 'Vinohrady Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-6',
    fromNodeId: 'node-pra-3-2',
    toNodeId: 'node-pra-3-3',
    roadName: 'Vinohrady Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-7',
    fromNodeId: 'node-pra-4-1',
    toNodeId: 'node-pra-4-2',
    roadName: 'Žižkov Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-8',
    fromNodeId: 'node-pra-4-2',
    toNodeId: 'node-pra-4-3',
    roadName: 'Žižkov Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-9',
    fromNodeId: 'node-pra-5-1',
    toNodeId: 'node-pra-5-2',
    roadName: 'Holešovice Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-10',
    fromNodeId: 'node-pra-5-2',
    toNodeId: 'node-pra-5-3',
    roadName: 'Holešovice Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-11',
    fromNodeId: 'node-pra-6-1',
    toNodeId: 'node-pra-6-2',
    roadName: 'Karlín Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-12',
    fromNodeId: 'node-pra-6-2',
    toNodeId: 'node-pra-6-3',
    roadName: 'Karlín Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-13',
    fromNodeId: 'node-pra-7-1',
    toNodeId: 'node-pra-7-2',
    roadName: 'Smíchov Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-14',
    fromNodeId: 'node-pra-7-2',
    toNodeId: 'node-pra-7-3',
    roadName: 'Smíchov Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-15',
    fromNodeId: 'node-pra-8-1',
    toNodeId: 'node-pra-8-2',
    roadName: 'Nové Město Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-16',
    fromNodeId: 'node-pra-8-2',
    toNodeId: 'node-pra-8-3',
    roadName: 'Nové Město Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-17',
    fromNodeId: 'node-pra-9-1',
    toNodeId: 'node-pra-9-2',
    roadName: 'Dejvice Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-18',
    fromNodeId: 'node-pra-9-2',
    toNodeId: 'node-pra-9-3',
    roadName: 'Dejvice Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-19',
    fromNodeId: 'node-pra-10-1',
    toNodeId: 'node-pra-10-2',
    roadName: 'Vršovice Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-pra-20',
    fromNodeId: 'node-pra-10-2',
    toNodeId: 'node-pra-10-3',
    roadName: 'Vršovice Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
