/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Rajkot Saurashtra Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const RAJKOT_BASE_COORDINATE: GeoCoordinate = {
  latitude: 22.3039,
  longitude: 70.8022,
};

export const RAJKOT_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-raj-1-1',
    name: 'Yagnik Road Sector 1 High Street',
    zone: 'Yagnik Road',
    location: { latitude: 22.241900, longitude: 70.750200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Yagnik Road.',
  },
  {
    id: 'node-raj-1-2',
    name: 'Yagnik Road Sector 2 High Street',
    zone: 'Yagnik Road',
    location: { latitude: 22.244900, longitude: 70.753200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Yagnik Road.',
  },
  {
    id: 'node-raj-1-3',
    name: 'Yagnik Road Sector 3 High Street',
    zone: 'Yagnik Road',
    location: { latitude: 22.247900, longitude: 70.756200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Yagnik Road.',
  },
  {
    id: 'node-raj-2-1',
    name: 'Kalawad Road Sector 1 High Street',
    zone: 'Kalawad Road',
    location: { latitude: 22.253900, longitude: 70.760200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kalawad Road.',
  },
  {
    id: 'node-raj-2-2',
    name: 'Kalawad Road Sector 2 High Street',
    zone: 'Kalawad Road',
    location: { latitude: 22.256900, longitude: 70.763200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kalawad Road.',
  },
  {
    id: 'node-raj-2-3',
    name: 'Kalawad Road Sector 3 High Street',
    zone: 'Kalawad Road',
    location: { latitude: 22.259900, longitude: 70.766200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kalawad Road.',
  },
  {
    id: 'node-raj-3-1',
    name: 'University Road Sector 1 High Street',
    zone: 'University Road',
    location: { latitude: 22.265900, longitude: 70.770200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in University Road.',
  },
  {
    id: 'node-raj-3-2',
    name: 'University Road Sector 2 High Street',
    zone: 'University Road',
    location: { latitude: 22.268900, longitude: 70.773200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in University Road.',
  },
  {
    id: 'node-raj-3-3',
    name: 'University Road Sector 3 High Street',
    zone: 'University Road',
    location: { latitude: 22.271900, longitude: 70.776200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in University Road.',
  },
  {
    id: 'node-raj-4-1',
    name: '150 Feet Ring Road Sector 1 High Street',
    zone: '150 Feet Ring Road',
    location: { latitude: 22.277900, longitude: 70.780200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in 150 Feet Ring Road.',
  },
  {
    id: 'node-raj-4-2',
    name: '150 Feet Ring Road Sector 2 High Street',
    zone: '150 Feet Ring Road',
    location: { latitude: 22.280900, longitude: 70.783200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in 150 Feet Ring Road.',
  },
  {
    id: 'node-raj-4-3',
    name: '150 Feet Ring Road Sector 3 High Street',
    zone: '150 Feet Ring Road',
    location: { latitude: 22.283900, longitude: 70.786200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in 150 Feet Ring Road.',
  },
  {
    id: 'node-raj-5-1',
    name: 'Astron Chowk Sector 1 High Street',
    zone: 'Astron Chowk',
    location: { latitude: 22.289900, longitude: 70.790200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Astron Chowk.',
  },
  {
    id: 'node-raj-5-2',
    name: 'Astron Chowk Sector 2 High Street',
    zone: 'Astron Chowk',
    location: { latitude: 22.292900, longitude: 70.793200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Astron Chowk.',
  },
  {
    id: 'node-raj-5-3',
    name: 'Astron Chowk Sector 3 High Street',
    zone: 'Astron Chowk',
    location: { latitude: 22.295900, longitude: 70.796200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Astron Chowk.',
  },
  {
    id: 'node-raj-6-1',
    name: 'Amin Marg Sector 1 High Street',
    zone: 'Amin Marg',
    location: { latitude: 22.301900, longitude: 70.800200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Amin Marg.',
  },
  {
    id: 'node-raj-6-2',
    name: 'Amin Marg Sector 2 High Street',
    zone: 'Amin Marg',
    location: { latitude: 22.304900, longitude: 70.803200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Amin Marg.',
  },
  {
    id: 'node-raj-6-3',
    name: 'Amin Marg Sector 3 High Street',
    zone: 'Amin Marg',
    location: { latitude: 22.307900, longitude: 70.806200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Amin Marg.',
  },
  {
    id: 'node-raj-7-1',
    name: 'Nana Mava Sector 1 High Street',
    zone: 'Nana Mava',
    location: { latitude: 22.313900, longitude: 70.810200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nana Mava.',
  },
  {
    id: 'node-raj-7-2',
    name: 'Nana Mava Sector 2 High Street',
    zone: 'Nana Mava',
    location: { latitude: 22.316900, longitude: 70.813200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nana Mava.',
  },
  {
    id: 'node-raj-7-3',
    name: 'Nana Mava Sector 3 High Street',
    zone: 'Nana Mava',
    location: { latitude: 22.319900, longitude: 70.816200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nana Mava.',
  },
  {
    id: 'node-raj-8-1',
    name: 'Madhapar Sector 1 High Street',
    zone: 'Madhapar',
    location: { latitude: 22.325900, longitude: 70.820200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Madhapar.',
  },
  {
    id: 'node-raj-8-2',
    name: 'Madhapar Sector 2 High Street',
    zone: 'Madhapar',
    location: { latitude: 22.328900, longitude: 70.823200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Madhapar.',
  },
  {
    id: 'node-raj-8-3',
    name: 'Madhapar Sector 3 High Street',
    zone: 'Madhapar',
    location: { latitude: 22.331900, longitude: 70.826200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Madhapar.',
  },
  {
    id: 'node-raj-9-1',
    name: 'Kotecha Chowk Sector 1 High Street',
    zone: 'Kotecha Chowk',
    location: { latitude: 22.337900, longitude: 70.830200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kotecha Chowk.',
  },
  {
    id: 'node-raj-9-2',
    name: 'Kotecha Chowk Sector 2 High Street',
    zone: 'Kotecha Chowk',
    location: { latitude: 22.340900, longitude: 70.833200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kotecha Chowk.',
  },
  {
    id: 'node-raj-9-3',
    name: 'Kotecha Chowk Sector 3 High Street',
    zone: 'Kotecha Chowk',
    location: { latitude: 22.343900, longitude: 70.836200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kotecha Chowk.',
  },
  {
    id: 'node-raj-10-1',
    name: 'Bhaktinagar Sector 1 High Street',
    zone: 'Bhaktinagar',
    location: { latitude: 22.349900, longitude: 70.840200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bhaktinagar.',
  },
  {
    id: 'node-raj-10-2',
    name: 'Bhaktinagar Sector 2 High Street',
    zone: 'Bhaktinagar',
    location: { latitude: 22.352900, longitude: 70.843200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bhaktinagar.',
  },
  {
    id: 'node-raj-10-3',
    name: 'Bhaktinagar Sector 3 High Street',
    zone: 'Bhaktinagar',
    location: { latitude: 22.355900, longitude: 70.846200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bhaktinagar.',
  },
];

export const RAJKOT_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-raj-1',
    fromNodeId: 'node-raj-1-1',
    toNodeId: 'node-raj-1-2',
    roadName: 'Yagnik Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-2',
    fromNodeId: 'node-raj-1-2',
    toNodeId: 'node-raj-1-3',
    roadName: 'Yagnik Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-3',
    fromNodeId: 'node-raj-2-1',
    toNodeId: 'node-raj-2-2',
    roadName: 'Kalawad Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-4',
    fromNodeId: 'node-raj-2-2',
    toNodeId: 'node-raj-2-3',
    roadName: 'Kalawad Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-5',
    fromNodeId: 'node-raj-3-1',
    toNodeId: 'node-raj-3-2',
    roadName: 'University Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-6',
    fromNodeId: 'node-raj-3-2',
    toNodeId: 'node-raj-3-3',
    roadName: 'University Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-7',
    fromNodeId: 'node-raj-4-1',
    toNodeId: 'node-raj-4-2',
    roadName: '150 Feet Ring Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-8',
    fromNodeId: 'node-raj-4-2',
    toNodeId: 'node-raj-4-3',
    roadName: '150 Feet Ring Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-9',
    fromNodeId: 'node-raj-5-1',
    toNodeId: 'node-raj-5-2',
    roadName: 'Astron Chowk Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-10',
    fromNodeId: 'node-raj-5-2',
    toNodeId: 'node-raj-5-3',
    roadName: 'Astron Chowk Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-11',
    fromNodeId: 'node-raj-6-1',
    toNodeId: 'node-raj-6-2',
    roadName: 'Amin Marg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-12',
    fromNodeId: 'node-raj-6-2',
    toNodeId: 'node-raj-6-3',
    roadName: 'Amin Marg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-13',
    fromNodeId: 'node-raj-7-1',
    toNodeId: 'node-raj-7-2',
    roadName: 'Nana Mava Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-14',
    fromNodeId: 'node-raj-7-2',
    toNodeId: 'node-raj-7-3',
    roadName: 'Nana Mava Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-15',
    fromNodeId: 'node-raj-8-1',
    toNodeId: 'node-raj-8-2',
    roadName: 'Madhapar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-16',
    fromNodeId: 'node-raj-8-2',
    toNodeId: 'node-raj-8-3',
    roadName: 'Madhapar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-17',
    fromNodeId: 'node-raj-9-1',
    toNodeId: 'node-raj-9-2',
    roadName: 'Kotecha Chowk Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-18',
    fromNodeId: 'node-raj-9-2',
    toNodeId: 'node-raj-9-3',
    roadName: 'Kotecha Chowk Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-19',
    fromNodeId: 'node-raj-10-1',
    toNodeId: 'node-raj-10-2',
    roadName: 'Bhaktinagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-raj-20',
    fromNodeId: 'node-raj-10-2',
    toNodeId: 'node-raj-10-3',
    roadName: 'Bhaktinagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
