/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Ranchi Plateau Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const RANCHI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 23.3441,
  longitude: 85.3096,
};

export const RANCHI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ran-1-1',
    name: 'Main Road Sector 1 High Street',
    zone: 'Main Road',
    location: { latitude: 23.282100, longitude: 85.257600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Main Road.',
  },
  {
    id: 'node-ran-1-2',
    name: 'Main Road Sector 2 High Street',
    zone: 'Main Road',
    location: { latitude: 23.285100, longitude: 85.260600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Main Road.',
  },
  {
    id: 'node-ran-1-3',
    name: 'Main Road Sector 3 High Street',
    zone: 'Main Road',
    location: { latitude: 23.288100, longitude: 85.263600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Main Road.',
  },
  {
    id: 'node-ran-2-1',
    name: 'Harmu Housing Sector 1 High Street',
    zone: 'Harmu Housing',
    location: { latitude: 23.294100, longitude: 85.267600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Harmu Housing.',
  },
  {
    id: 'node-ran-2-2',
    name: 'Harmu Housing Sector 2 High Street',
    zone: 'Harmu Housing',
    location: { latitude: 23.297100, longitude: 85.270600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Harmu Housing.',
  },
  {
    id: 'node-ran-2-3',
    name: 'Harmu Housing Sector 3 High Street',
    zone: 'Harmu Housing',
    location: { latitude: 23.300100, longitude: 85.273600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Harmu Housing.',
  },
  {
    id: 'node-ran-3-1',
    name: 'Lalpur Sector 1 High Street',
    zone: 'Lalpur',
    location: { latitude: 23.306100, longitude: 85.277600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lalpur.',
  },
  {
    id: 'node-ran-3-2',
    name: 'Lalpur Sector 2 High Street',
    zone: 'Lalpur',
    location: { latitude: 23.309100, longitude: 85.280600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lalpur.',
  },
  {
    id: 'node-ran-3-3',
    name: 'Lalpur Sector 3 High Street',
    zone: 'Lalpur',
    location: { latitude: 23.312100, longitude: 85.283600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lalpur.',
  },
  {
    id: 'node-ran-4-1',
    name: 'Doranda Sector 1 High Street',
    zone: 'Doranda',
    location: { latitude: 23.318100, longitude: 85.287600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Doranda.',
  },
  {
    id: 'node-ran-4-2',
    name: 'Doranda Sector 2 High Street',
    zone: 'Doranda',
    location: { latitude: 23.321100, longitude: 85.290600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Doranda.',
  },
  {
    id: 'node-ran-4-3',
    name: 'Doranda Sector 3 High Street',
    zone: 'Doranda',
    location: { latitude: 23.324100, longitude: 85.293600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Doranda.',
  },
  {
    id: 'node-ran-5-1',
    name: 'Kanke Road Sector 1 High Street',
    zone: 'Kanke Road',
    location: { latitude: 23.330100, longitude: 85.297600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kanke Road.',
  },
  {
    id: 'node-ran-5-2',
    name: 'Kanke Road Sector 2 High Street',
    zone: 'Kanke Road',
    location: { latitude: 23.333100, longitude: 85.300600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kanke Road.',
  },
  {
    id: 'node-ran-5-3',
    name: 'Kanke Road Sector 3 High Street',
    zone: 'Kanke Road',
    location: { latitude: 23.336100, longitude: 85.303600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kanke Road.',
  },
  {
    id: 'node-ran-6-1',
    name: 'Bariatu Sector 1 High Street',
    zone: 'Bariatu',
    location: { latitude: 23.342100, longitude: 85.307600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bariatu.',
  },
  {
    id: 'node-ran-6-2',
    name: 'Bariatu Sector 2 High Street',
    zone: 'Bariatu',
    location: { latitude: 23.345100, longitude: 85.310600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bariatu.',
  },
  {
    id: 'node-ran-6-3',
    name: 'Bariatu Sector 3 High Street',
    zone: 'Bariatu',
    location: { latitude: 23.348100, longitude: 85.313600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bariatu.',
  },
  {
    id: 'node-ran-7-1',
    name: 'Hinoo Sector 1 High Street',
    zone: 'Hinoo',
    location: { latitude: 23.354100, longitude: 85.317600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hinoo.',
  },
  {
    id: 'node-ran-7-2',
    name: 'Hinoo Sector 2 High Street',
    zone: 'Hinoo',
    location: { latitude: 23.357100, longitude: 85.320600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hinoo.',
  },
  {
    id: 'node-ran-7-3',
    name: 'Hinoo Sector 3 High Street',
    zone: 'Hinoo',
    location: { latitude: 23.360100, longitude: 85.323600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hinoo.',
  },
  {
    id: 'node-ran-8-1',
    name: 'Morabadi Sector 1 High Street',
    zone: 'Morabadi',
    location: { latitude: 23.366100, longitude: 85.327600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Morabadi.',
  },
  {
    id: 'node-ran-8-2',
    name: 'Morabadi Sector 2 High Street',
    zone: 'Morabadi',
    location: { latitude: 23.369100, longitude: 85.330600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Morabadi.',
  },
  {
    id: 'node-ran-8-3',
    name: 'Morabadi Sector 3 High Street',
    zone: 'Morabadi',
    location: { latitude: 23.372100, longitude: 85.333600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Morabadi.',
  },
  {
    id: 'node-ran-9-1',
    name: 'Ratu Road Sector 1 High Street',
    zone: 'Ratu Road',
    location: { latitude: 23.378100, longitude: 85.337600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ratu Road.',
  },
  {
    id: 'node-ran-9-2',
    name: 'Ratu Road Sector 2 High Street',
    zone: 'Ratu Road',
    location: { latitude: 23.381100, longitude: 85.340600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ratu Road.',
  },
  {
    id: 'node-ran-9-3',
    name: 'Ratu Road Sector 3 High Street',
    zone: 'Ratu Road',
    location: { latitude: 23.384100, longitude: 85.343600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ratu Road.',
  },
  {
    id: 'node-ran-10-1',
    name: 'Namkum Sector 1 High Street',
    zone: 'Namkum',
    location: { latitude: 23.390100, longitude: 85.347600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Namkum.',
  },
  {
    id: 'node-ran-10-2',
    name: 'Namkum Sector 2 High Street',
    zone: 'Namkum',
    location: { latitude: 23.393100, longitude: 85.350600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Namkum.',
  },
  {
    id: 'node-ran-10-3',
    name: 'Namkum Sector 3 High Street',
    zone: 'Namkum',
    location: { latitude: 23.396100, longitude: 85.353600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Namkum.',
  },
];

export const RANCHI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ran-1',
    fromNodeId: 'node-ran-1-1',
    toNodeId: 'node-ran-1-2',
    roadName: 'Main Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-2',
    fromNodeId: 'node-ran-1-2',
    toNodeId: 'node-ran-1-3',
    roadName: 'Main Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-3',
    fromNodeId: 'node-ran-2-1',
    toNodeId: 'node-ran-2-2',
    roadName: 'Harmu Housing Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-4',
    fromNodeId: 'node-ran-2-2',
    toNodeId: 'node-ran-2-3',
    roadName: 'Harmu Housing Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-5',
    fromNodeId: 'node-ran-3-1',
    toNodeId: 'node-ran-3-2',
    roadName: 'Lalpur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-6',
    fromNodeId: 'node-ran-3-2',
    toNodeId: 'node-ran-3-3',
    roadName: 'Lalpur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-7',
    fromNodeId: 'node-ran-4-1',
    toNodeId: 'node-ran-4-2',
    roadName: 'Doranda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-8',
    fromNodeId: 'node-ran-4-2',
    toNodeId: 'node-ran-4-3',
    roadName: 'Doranda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-9',
    fromNodeId: 'node-ran-5-1',
    toNodeId: 'node-ran-5-2',
    roadName: 'Kanke Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-10',
    fromNodeId: 'node-ran-5-2',
    toNodeId: 'node-ran-5-3',
    roadName: 'Kanke Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-11',
    fromNodeId: 'node-ran-6-1',
    toNodeId: 'node-ran-6-2',
    roadName: 'Bariatu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-12',
    fromNodeId: 'node-ran-6-2',
    toNodeId: 'node-ran-6-3',
    roadName: 'Bariatu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-13',
    fromNodeId: 'node-ran-7-1',
    toNodeId: 'node-ran-7-2',
    roadName: 'Hinoo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-14',
    fromNodeId: 'node-ran-7-2',
    toNodeId: 'node-ran-7-3',
    roadName: 'Hinoo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-15',
    fromNodeId: 'node-ran-8-1',
    toNodeId: 'node-ran-8-2',
    roadName: 'Morabadi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-16',
    fromNodeId: 'node-ran-8-2',
    toNodeId: 'node-ran-8-3',
    roadName: 'Morabadi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-17',
    fromNodeId: 'node-ran-9-1',
    toNodeId: 'node-ran-9-2',
    roadName: 'Ratu Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-18',
    fromNodeId: 'node-ran-9-2',
    toNodeId: 'node-ran-9-3',
    roadName: 'Ratu Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-19',
    fromNodeId: 'node-ran-10-1',
    toNodeId: 'node-ran-10-2',
    roadName: 'Namkum Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ran-20',
    fromNodeId: 'node-ran-10-2',
    toNodeId: 'node-ran-10-3',
    roadName: 'Namkum Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
