/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Riyadh Olaya Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const RIYADH_BASE_COORDINATE: GeoCoordinate = {
  latitude: 24.7136,
  longitude: 46.6753,
};

export const RIYADH_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-riy-1-1',
    name: 'Al Olaya Sector 1 High Street',
    zone: 'Al Olaya',
    location: { latitude: 24.651600, longitude: 46.623300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Olaya.',
  },
  {
    id: 'node-riy-1-2',
    name: 'Al Olaya Sector 2 High Street',
    zone: 'Al Olaya',
    location: { latitude: 24.654600, longitude: 46.626300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Olaya.',
  },
  {
    id: 'node-riy-1-3',
    name: 'Al Olaya Sector 3 High Street',
    zone: 'Al Olaya',
    location: { latitude: 24.657600, longitude: 46.629300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Olaya.',
  },
  {
    id: 'node-riy-2-1',
    name: 'Al Malqa Sector 1 High Street',
    zone: 'Al Malqa',
    location: { latitude: 24.663600, longitude: 46.633300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Malqa.',
  },
  {
    id: 'node-riy-2-2',
    name: 'Al Malqa Sector 2 High Street',
    zone: 'Al Malqa',
    location: { latitude: 24.666600, longitude: 46.636300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Malqa.',
  },
  {
    id: 'node-riy-2-3',
    name: 'Al Malqa Sector 3 High Street',
    zone: 'Al Malqa',
    location: { latitude: 24.669600, longitude: 46.639300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Malqa.',
  },
  {
    id: 'node-riy-3-1',
    name: 'Al Nakheel Sector 1 High Street',
    zone: 'Al Nakheel',
    location: { latitude: 24.675600, longitude: 46.643300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Nakheel.',
  },
  {
    id: 'node-riy-3-2',
    name: 'Al Nakheel Sector 2 High Street',
    zone: 'Al Nakheel',
    location: { latitude: 24.678600, longitude: 46.646300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Nakheel.',
  },
  {
    id: 'node-riy-3-3',
    name: 'Al Nakheel Sector 3 High Street',
    zone: 'Al Nakheel',
    location: { latitude: 24.681600, longitude: 46.649300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Nakheel.',
  },
  {
    id: 'node-riy-4-1',
    name: 'Al Yasmin Sector 1 High Street',
    zone: 'Al Yasmin',
    location: { latitude: 24.687600, longitude: 46.653300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Yasmin.',
  },
  {
    id: 'node-riy-4-2',
    name: 'Al Yasmin Sector 2 High Street',
    zone: 'Al Yasmin',
    location: { latitude: 24.690600, longitude: 46.656300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Yasmin.',
  },
  {
    id: 'node-riy-4-3',
    name: 'Al Yasmin Sector 3 High Street',
    zone: 'Al Yasmin',
    location: { latitude: 24.693600, longitude: 46.659300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Yasmin.',
  },
  {
    id: 'node-riy-5-1',
    name: 'Diplomatic Quarter Sector 1 High Street',
    zone: 'Diplomatic Quarter',
    location: { latitude: 24.699600, longitude: 46.663300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Diplomatic Quarter.',
  },
  {
    id: 'node-riy-5-2',
    name: 'Diplomatic Quarter Sector 2 High Street',
    zone: 'Diplomatic Quarter',
    location: { latitude: 24.702600, longitude: 46.666300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Diplomatic Quarter.',
  },
  {
    id: 'node-riy-5-3',
    name: 'Diplomatic Quarter Sector 3 High Street',
    zone: 'Diplomatic Quarter',
    location: { latitude: 24.705600, longitude: 46.669300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Diplomatic Quarter.',
  },
  {
    id: 'node-riy-6-1',
    name: 'Al Sulaimaniyah Sector 1 High Street',
    zone: 'Al Sulaimaniyah',
    location: { latitude: 24.711600, longitude: 46.673300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Sulaimaniyah.',
  },
  {
    id: 'node-riy-6-2',
    name: 'Al Sulaimaniyah Sector 2 High Street',
    zone: 'Al Sulaimaniyah',
    location: { latitude: 24.714600, longitude: 46.676300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Sulaimaniyah.',
  },
  {
    id: 'node-riy-6-3',
    name: 'Al Sulaimaniyah Sector 3 High Street',
    zone: 'Al Sulaimaniyah',
    location: { latitude: 24.717600, longitude: 46.679300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Sulaimaniyah.',
  },
  {
    id: 'node-riy-7-1',
    name: 'Al Mohammadiyyah Sector 1 High Street',
    zone: 'Al Mohammadiyyah',
    location: { latitude: 24.723600, longitude: 46.683300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Mohammadiyyah.',
  },
  {
    id: 'node-riy-7-2',
    name: 'Al Mohammadiyyah Sector 2 High Street',
    zone: 'Al Mohammadiyyah',
    location: { latitude: 24.726600, longitude: 46.686300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Mohammadiyyah.',
  },
  {
    id: 'node-riy-7-3',
    name: 'Al Mohammadiyyah Sector 3 High Street',
    zone: 'Al Mohammadiyyah',
    location: { latitude: 24.729600, longitude: 46.689300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Mohammadiyyah.',
  },
  {
    id: 'node-riy-8-1',
    name: 'Al Murabba Sector 1 High Street',
    zone: 'Al Murabba',
    location: { latitude: 24.735600, longitude: 46.693300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Murabba.',
  },
  {
    id: 'node-riy-8-2',
    name: 'Al Murabba Sector 2 High Street',
    zone: 'Al Murabba',
    location: { latitude: 24.738600, longitude: 46.696300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Murabba.',
  },
  {
    id: 'node-riy-8-3',
    name: 'Al Murabba Sector 3 High Street',
    zone: 'Al Murabba',
    location: { latitude: 24.741600, longitude: 46.699300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Murabba.',
  },
  {
    id: 'node-riy-9-1',
    name: 'King Fahd District Sector 1 High Street',
    zone: 'King Fahd District',
    location: { latitude: 24.747600, longitude: 46.703300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in King Fahd District.',
  },
  {
    id: 'node-riy-9-2',
    name: 'King Fahd District Sector 2 High Street',
    zone: 'King Fahd District',
    location: { latitude: 24.750600, longitude: 46.706300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in King Fahd District.',
  },
  {
    id: 'node-riy-9-3',
    name: 'King Fahd District Sector 3 High Street',
    zone: 'King Fahd District',
    location: { latitude: 24.753600, longitude: 46.709300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in King Fahd District.',
  },
  {
    id: 'node-riy-10-1',
    name: 'Al Wurud Sector 1 High Street',
    zone: 'Al Wurud',
    location: { latitude: 24.759600, longitude: 46.713300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Al Wurud.',
  },
  {
    id: 'node-riy-10-2',
    name: 'Al Wurud Sector 2 High Street',
    zone: 'Al Wurud',
    location: { latitude: 24.762600, longitude: 46.716300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Al Wurud.',
  },
  {
    id: 'node-riy-10-3',
    name: 'Al Wurud Sector 3 High Street',
    zone: 'Al Wurud',
    location: { latitude: 24.765600, longitude: 46.719300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Al Wurud.',
  },
];

export const RIYADH_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-riy-1',
    fromNodeId: 'node-riy-1-1',
    toNodeId: 'node-riy-1-2',
    roadName: 'Al Olaya Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-2',
    fromNodeId: 'node-riy-1-2',
    toNodeId: 'node-riy-1-3',
    roadName: 'Al Olaya Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-3',
    fromNodeId: 'node-riy-2-1',
    toNodeId: 'node-riy-2-2',
    roadName: 'Al Malqa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-4',
    fromNodeId: 'node-riy-2-2',
    toNodeId: 'node-riy-2-3',
    roadName: 'Al Malqa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-5',
    fromNodeId: 'node-riy-3-1',
    toNodeId: 'node-riy-3-2',
    roadName: 'Al Nakheel Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-6',
    fromNodeId: 'node-riy-3-2',
    toNodeId: 'node-riy-3-3',
    roadName: 'Al Nakheel Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-7',
    fromNodeId: 'node-riy-4-1',
    toNodeId: 'node-riy-4-2',
    roadName: 'Al Yasmin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-8',
    fromNodeId: 'node-riy-4-2',
    toNodeId: 'node-riy-4-3',
    roadName: 'Al Yasmin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-9',
    fromNodeId: 'node-riy-5-1',
    toNodeId: 'node-riy-5-2',
    roadName: 'Diplomatic Quarter Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-10',
    fromNodeId: 'node-riy-5-2',
    toNodeId: 'node-riy-5-3',
    roadName: 'Diplomatic Quarter Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-11',
    fromNodeId: 'node-riy-6-1',
    toNodeId: 'node-riy-6-2',
    roadName: 'Al Sulaimaniyah Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-12',
    fromNodeId: 'node-riy-6-2',
    toNodeId: 'node-riy-6-3',
    roadName: 'Al Sulaimaniyah Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-13',
    fromNodeId: 'node-riy-7-1',
    toNodeId: 'node-riy-7-2',
    roadName: 'Al Mohammadiyyah Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-14',
    fromNodeId: 'node-riy-7-2',
    toNodeId: 'node-riy-7-3',
    roadName: 'Al Mohammadiyyah Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-15',
    fromNodeId: 'node-riy-8-1',
    toNodeId: 'node-riy-8-2',
    roadName: 'Al Murabba Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-16',
    fromNodeId: 'node-riy-8-2',
    toNodeId: 'node-riy-8-3',
    roadName: 'Al Murabba Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-17',
    fromNodeId: 'node-riy-9-1',
    toNodeId: 'node-riy-9-2',
    roadName: 'King Fahd District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-18',
    fromNodeId: 'node-riy-9-2',
    toNodeId: 'node-riy-9-3',
    roadName: 'King Fahd District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-19',
    fromNodeId: 'node-riy-10-1',
    toNodeId: 'node-riy-10-2',
    roadName: 'Al Wurud Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-riy-20',
    fromNodeId: 'node-riy-10-2',
    toNodeId: 'node-riy-10-3',
    roadName: 'Al Wurud Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
