/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Salem Mango & Steel Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SALEM_BASE_COORDINATE: GeoCoordinate = {
  latitude: 11.6643,
  longitude: 78.146,
};

export const SALEM_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sal-1-1',
    name: 'Fairlands Sector 1 High Street',
    zone: 'Fairlands',
    location: { latitude: 11.602300, longitude: 78.094000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fairlands.',
  },
  {
    id: 'node-sal-1-2',
    name: 'Fairlands Sector 2 High Street',
    zone: 'Fairlands',
    location: { latitude: 11.605300, longitude: 78.097000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fairlands.',
  },
  {
    id: 'node-sal-1-3',
    name: 'Fairlands Sector 3 High Street',
    zone: 'Fairlands',
    location: { latitude: 11.608300, longitude: 78.100000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fairlands.',
  },
  {
    id: 'node-sal-2-1',
    name: 'Hasthampatti Sector 1 High Street',
    zone: 'Hasthampatti',
    location: { latitude: 11.614300, longitude: 78.104000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hasthampatti.',
  },
  {
    id: 'node-sal-2-2',
    name: 'Hasthampatti Sector 2 High Street',
    zone: 'Hasthampatti',
    location: { latitude: 11.617300, longitude: 78.107000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hasthampatti.',
  },
  {
    id: 'node-sal-2-3',
    name: 'Hasthampatti Sector 3 High Street',
    zone: 'Hasthampatti',
    location: { latitude: 11.620300, longitude: 78.110000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hasthampatti.',
  },
  {
    id: 'node-sal-3-1',
    name: 'Alagapuram Sector 1 High Street',
    zone: 'Alagapuram',
    location: { latitude: 11.626300, longitude: 78.114000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Alagapuram.',
  },
  {
    id: 'node-sal-3-2',
    name: 'Alagapuram Sector 2 High Street',
    zone: 'Alagapuram',
    location: { latitude: 11.629300, longitude: 78.117000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Alagapuram.',
  },
  {
    id: 'node-sal-3-3',
    name: 'Alagapuram Sector 3 High Street',
    zone: 'Alagapuram',
    location: { latitude: 11.632300, longitude: 78.120000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Alagapuram.',
  },
  {
    id: 'node-sal-4-1',
    name: 'Suramangalam Sector 1 High Street',
    zone: 'Suramangalam',
    location: { latitude: 11.638300, longitude: 78.124000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Suramangalam.',
  },
  {
    id: 'node-sal-4-2',
    name: 'Suramangalam Sector 2 High Street',
    zone: 'Suramangalam',
    location: { latitude: 11.641300, longitude: 78.127000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Suramangalam.',
  },
  {
    id: 'node-sal-4-3',
    name: 'Suramangalam Sector 3 High Street',
    zone: 'Suramangalam',
    location: { latitude: 11.644300, longitude: 78.130000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Suramangalam.',
  },
  {
    id: 'node-sal-5-1',
    name: 'Four Roads Sector 1 High Street',
    zone: 'Four Roads',
    location: { latitude: 11.650300, longitude: 78.134000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Four Roads.',
  },
  {
    id: 'node-sal-5-2',
    name: 'Four Roads Sector 2 High Street',
    zone: 'Four Roads',
    location: { latitude: 11.653300, longitude: 78.137000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Four Roads.',
  },
  {
    id: 'node-sal-5-3',
    name: 'Four Roads Sector 3 High Street',
    zone: 'Four Roads',
    location: { latitude: 11.656300, longitude: 78.140000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Four Roads.',
  },
  {
    id: 'node-sal-6-1',
    name: 'Junction Sector 1 High Street',
    zone: 'Junction',
    location: { latitude: 11.662300, longitude: 78.144000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Junction.',
  },
  {
    id: 'node-sal-6-2',
    name: 'Junction Sector 2 High Street',
    zone: 'Junction',
    location: { latitude: 11.665300, longitude: 78.147000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Junction.',
  },
  {
    id: 'node-sal-6-3',
    name: 'Junction Sector 3 High Street',
    zone: 'Junction',
    location: { latitude: 11.668300, longitude: 78.150000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Junction.',
  },
  {
    id: 'node-sal-7-1',
    name: 'Gugai Sector 1 High Street',
    zone: 'Gugai',
    location: { latitude: 11.674300, longitude: 78.154000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gugai.',
  },
  {
    id: 'node-sal-7-2',
    name: 'Gugai Sector 2 High Street',
    zone: 'Gugai',
    location: { latitude: 11.677300, longitude: 78.157000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gugai.',
  },
  {
    id: 'node-sal-7-3',
    name: 'Gugai Sector 3 High Street',
    zone: 'Gugai',
    location: { latitude: 11.680300, longitude: 78.160000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gugai.',
  },
  {
    id: 'node-sal-8-1',
    name: 'Meyyanur Sector 1 High Street',
    zone: 'Meyyanur',
    location: { latitude: 11.686300, longitude: 78.164000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Meyyanur.',
  },
  {
    id: 'node-sal-8-2',
    name: 'Meyyanur Sector 2 High Street',
    zone: 'Meyyanur',
    location: { latitude: 11.689300, longitude: 78.167000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Meyyanur.',
  },
  {
    id: 'node-sal-8-3',
    name: 'Meyyanur Sector 3 High Street',
    zone: 'Meyyanur',
    location: { latitude: 11.692300, longitude: 78.170000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Meyyanur.',
  },
  {
    id: 'node-sal-9-1',
    name: 'Ammapet Sector 1 High Street',
    zone: 'Ammapet',
    location: { latitude: 11.698300, longitude: 78.174000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ammapet.',
  },
  {
    id: 'node-sal-9-2',
    name: 'Ammapet Sector 2 High Street',
    zone: 'Ammapet',
    location: { latitude: 11.701300, longitude: 78.177000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ammapet.',
  },
  {
    id: 'node-sal-9-3',
    name: 'Ammapet Sector 3 High Street',
    zone: 'Ammapet',
    location: { latitude: 11.704300, longitude: 78.180000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ammapet.',
  },
  {
    id: 'node-sal-10-1',
    name: 'Steel Plant Road Sector 1 High Street',
    zone: 'Steel Plant Road',
    location: { latitude: 11.710300, longitude: 78.184000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Steel Plant Road.',
  },
  {
    id: 'node-sal-10-2',
    name: 'Steel Plant Road Sector 2 High Street',
    zone: 'Steel Plant Road',
    location: { latitude: 11.713300, longitude: 78.187000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Steel Plant Road.',
  },
  {
    id: 'node-sal-10-3',
    name: 'Steel Plant Road Sector 3 High Street',
    zone: 'Steel Plant Road',
    location: { latitude: 11.716300, longitude: 78.190000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Steel Plant Road.',
  },
];

export const SALEM_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sal-1',
    fromNodeId: 'node-sal-1-1',
    toNodeId: 'node-sal-1-2',
    roadName: 'Fairlands Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-2',
    fromNodeId: 'node-sal-1-2',
    toNodeId: 'node-sal-1-3',
    roadName: 'Fairlands Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-3',
    fromNodeId: 'node-sal-2-1',
    toNodeId: 'node-sal-2-2',
    roadName: 'Hasthampatti Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-4',
    fromNodeId: 'node-sal-2-2',
    toNodeId: 'node-sal-2-3',
    roadName: 'Hasthampatti Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-5',
    fromNodeId: 'node-sal-3-1',
    toNodeId: 'node-sal-3-2',
    roadName: 'Alagapuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-6',
    fromNodeId: 'node-sal-3-2',
    toNodeId: 'node-sal-3-3',
    roadName: 'Alagapuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-7',
    fromNodeId: 'node-sal-4-1',
    toNodeId: 'node-sal-4-2',
    roadName: 'Suramangalam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-8',
    fromNodeId: 'node-sal-4-2',
    toNodeId: 'node-sal-4-3',
    roadName: 'Suramangalam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-9',
    fromNodeId: 'node-sal-5-1',
    toNodeId: 'node-sal-5-2',
    roadName: 'Four Roads Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-10',
    fromNodeId: 'node-sal-5-2',
    toNodeId: 'node-sal-5-3',
    roadName: 'Four Roads Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-11',
    fromNodeId: 'node-sal-6-1',
    toNodeId: 'node-sal-6-2',
    roadName: 'Junction Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-12',
    fromNodeId: 'node-sal-6-2',
    toNodeId: 'node-sal-6-3',
    roadName: 'Junction Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-13',
    fromNodeId: 'node-sal-7-1',
    toNodeId: 'node-sal-7-2',
    roadName: 'Gugai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-14',
    fromNodeId: 'node-sal-7-2',
    toNodeId: 'node-sal-7-3',
    roadName: 'Gugai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-15',
    fromNodeId: 'node-sal-8-1',
    toNodeId: 'node-sal-8-2',
    roadName: 'Meyyanur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-16',
    fromNodeId: 'node-sal-8-2',
    toNodeId: 'node-sal-8-3',
    roadName: 'Meyyanur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-17',
    fromNodeId: 'node-sal-9-1',
    toNodeId: 'node-sal-9-2',
    roadName: 'Ammapet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-18',
    fromNodeId: 'node-sal-9-2',
    toNodeId: 'node-sal-9-3',
    roadName: 'Ammapet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-19',
    fromNodeId: 'node-sal-10-1',
    toNodeId: 'node-sal-10-2',
    roadName: 'Steel Plant Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-20',
    fromNodeId: 'node-sal-10-2',
    toNodeId: 'node-sal-10-3',
    roadName: 'Steel Plant Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
