/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Salt Lake City Wasatch Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SALTLAKECITY_BASE_COORDINATE: GeoCoordinate = {
  latitude: 40.7608,
  longitude: -111.891,
};

export const SALTLAKECITY_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sal-1-1',
    name: 'Downtown SLC Sector 1 High Street',
    zone: 'Downtown SLC',
    location: { latitude: 40.698800, longitude: -111.943000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown SLC.',
  },
  {
    id: 'node-sal-1-2',
    name: 'Downtown SLC Sector 2 High Street',
    zone: 'Downtown SLC',
    location: { latitude: 40.701800, longitude: -111.940000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown SLC.',
  },
  {
    id: 'node-sal-1-3',
    name: 'Downtown SLC Sector 3 High Street',
    zone: 'Downtown SLC',
    location: { latitude: 40.704800, longitude: -111.937000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown SLC.',
  },
  {
    id: 'node-sal-2-1',
    name: 'Sugar House Sector 1 High Street',
    zone: 'Sugar House',
    location: { latitude: 40.710800, longitude: -111.933000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sugar House.',
  },
  {
    id: 'node-sal-2-2',
    name: 'Sugar House Sector 2 High Street',
    zone: 'Sugar House',
    location: { latitude: 40.713800, longitude: -111.930000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sugar House.',
  },
  {
    id: 'node-sal-2-3',
    name: 'Sugar House Sector 3 High Street',
    zone: 'Sugar House',
    location: { latitude: 40.716800, longitude: -111.927000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sugar House.',
  },
  {
    id: 'node-sal-3-1',
    name: 'The Avenues Sector 1 High Street',
    zone: 'The Avenues',
    location: { latitude: 40.722800, longitude: -111.923000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in The Avenues.',
  },
  {
    id: 'node-sal-3-2',
    name: 'The Avenues Sector 2 High Street',
    zone: 'The Avenues',
    location: { latitude: 40.725800, longitude: -111.920000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in The Avenues.',
  },
  {
    id: 'node-sal-3-3',
    name: 'The Avenues Sector 3 High Street',
    zone: 'The Avenues',
    location: { latitude: 40.728800, longitude: -111.917000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in The Avenues.',
  },
  {
    id: 'node-sal-4-1',
    name: 'Central 9th Sector 1 High Street',
    zone: 'Central 9th',
    location: { latitude: 40.734800, longitude: -111.913000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Central 9th.',
  },
  {
    id: 'node-sal-4-2',
    name: 'Central 9th Sector 2 High Street',
    zone: 'Central 9th',
    location: { latitude: 40.737800, longitude: -111.910000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Central 9th.',
  },
  {
    id: 'node-sal-4-3',
    name: 'Central 9th Sector 3 High Street',
    zone: 'Central 9th',
    location: { latitude: 40.740800, longitude: -111.907000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Central 9th.',
  },
  {
    id: 'node-sal-5-1',
    name: 'Liberty Wells Sector 1 High Street',
    zone: 'Liberty Wells',
    location: { latitude: 40.746800, longitude: -111.903000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Liberty Wells.',
  },
  {
    id: 'node-sal-5-2',
    name: 'Liberty Wells Sector 2 High Street',
    zone: 'Liberty Wells',
    location: { latitude: 40.749800, longitude: -111.900000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Liberty Wells.',
  },
  {
    id: 'node-sal-5-3',
    name: 'Liberty Wells Sector 3 High Street',
    zone: 'Liberty Wells',
    location: { latitude: 40.752800, longitude: -111.897000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Liberty Wells.',
  },
  {
    id: 'node-sal-6-1',
    name: 'Foothill Sector 1 High Street',
    zone: 'Foothill',
    location: { latitude: 40.758800, longitude: -111.893000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Foothill.',
  },
  {
    id: 'node-sal-6-2',
    name: 'Foothill Sector 2 High Street',
    zone: 'Foothill',
    location: { latitude: 40.761800, longitude: -111.890000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Foothill.',
  },
  {
    id: 'node-sal-6-3',
    name: 'Foothill Sector 3 High Street',
    zone: 'Foothill',
    location: { latitude: 40.764800, longitude: -111.887000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Foothill.',
  },
  {
    id: 'node-sal-7-1',
    name: '9th and 9th Sector 1 High Street',
    zone: '9th and 9th',
    location: { latitude: 40.770800, longitude: -111.883000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in 9th and 9th.',
  },
  {
    id: 'node-sal-7-2',
    name: '9th and 9th Sector 2 High Street',
    zone: '9th and 9th',
    location: { latitude: 40.773800, longitude: -111.880000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in 9th and 9th.',
  },
  {
    id: 'node-sal-7-3',
    name: '9th and 9th Sector 3 High Street',
    zone: '9th and 9th',
    location: { latitude: 40.776800, longitude: -111.877000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in 9th and 9th.',
  },
  {
    id: 'node-sal-8-1',
    name: 'Capitol Hill SLC Sector 1 High Street',
    zone: 'Capitol Hill SLC',
    location: { latitude: 40.782800, longitude: -111.873000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Capitol Hill SLC.',
  },
  {
    id: 'node-sal-8-2',
    name: 'Capitol Hill SLC Sector 2 High Street',
    zone: 'Capitol Hill SLC',
    location: { latitude: 40.785800, longitude: -111.870000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Capitol Hill SLC.',
  },
  {
    id: 'node-sal-8-3',
    name: 'Capitol Hill SLC Sector 3 High Street',
    zone: 'Capitol Hill SLC',
    location: { latitude: 40.788800, longitude: -111.867000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Capitol Hill SLC.',
  },
  {
    id: 'node-sal-9-1',
    name: 'Rose Park Sector 1 High Street',
    zone: 'Rose Park',
    location: { latitude: 40.794800, longitude: -111.863000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rose Park.',
  },
  {
    id: 'node-sal-9-2',
    name: 'Rose Park Sector 2 High Street',
    zone: 'Rose Park',
    location: { latitude: 40.797800, longitude: -111.860000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rose Park.',
  },
  {
    id: 'node-sal-9-3',
    name: 'Rose Park Sector 3 High Street',
    zone: 'Rose Park',
    location: { latitude: 40.800800, longitude: -111.857000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rose Park.',
  },
  {
    id: 'node-sal-10-1',
    name: 'University SLC Sector 1 High Street',
    zone: 'University SLC',
    location: { latitude: 40.806800, longitude: -111.853000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in University SLC.',
  },
  {
    id: 'node-sal-10-2',
    name: 'University SLC Sector 2 High Street',
    zone: 'University SLC',
    location: { latitude: 40.809800, longitude: -111.850000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in University SLC.',
  },
  {
    id: 'node-sal-10-3',
    name: 'University SLC Sector 3 High Street',
    zone: 'University SLC',
    location: { latitude: 40.812800, longitude: -111.847000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in University SLC.',
  },
];

export const SALTLAKECITY_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sal-1',
    fromNodeId: 'node-sal-1-1',
    toNodeId: 'node-sal-1-2',
    roadName: 'Downtown SLC Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-2',
    fromNodeId: 'node-sal-1-2',
    toNodeId: 'node-sal-1-3',
    roadName: 'Downtown SLC Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-3',
    fromNodeId: 'node-sal-2-1',
    toNodeId: 'node-sal-2-2',
    roadName: 'Sugar House Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-4',
    fromNodeId: 'node-sal-2-2',
    toNodeId: 'node-sal-2-3',
    roadName: 'Sugar House Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-5',
    fromNodeId: 'node-sal-3-1',
    toNodeId: 'node-sal-3-2',
    roadName: 'The Avenues Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-6',
    fromNodeId: 'node-sal-3-2',
    toNodeId: 'node-sal-3-3',
    roadName: 'The Avenues Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-7',
    fromNodeId: 'node-sal-4-1',
    toNodeId: 'node-sal-4-2',
    roadName: 'Central 9th Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-8',
    fromNodeId: 'node-sal-4-2',
    toNodeId: 'node-sal-4-3',
    roadName: 'Central 9th Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-9',
    fromNodeId: 'node-sal-5-1',
    toNodeId: 'node-sal-5-2',
    roadName: 'Liberty Wells Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-10',
    fromNodeId: 'node-sal-5-2',
    toNodeId: 'node-sal-5-3',
    roadName: 'Liberty Wells Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-11',
    fromNodeId: 'node-sal-6-1',
    toNodeId: 'node-sal-6-2',
    roadName: 'Foothill Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-12',
    fromNodeId: 'node-sal-6-2',
    toNodeId: 'node-sal-6-3',
    roadName: 'Foothill Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-13',
    fromNodeId: 'node-sal-7-1',
    toNodeId: 'node-sal-7-2',
    roadName: '9th and 9th Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-14',
    fromNodeId: 'node-sal-7-2',
    toNodeId: 'node-sal-7-3',
    roadName: '9th and 9th Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-15',
    fromNodeId: 'node-sal-8-1',
    toNodeId: 'node-sal-8-2',
    roadName: 'Capitol Hill SLC Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-16',
    fromNodeId: 'node-sal-8-2',
    toNodeId: 'node-sal-8-3',
    roadName: 'Capitol Hill SLC Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-17',
    fromNodeId: 'node-sal-9-1',
    toNodeId: 'node-sal-9-2',
    roadName: 'Rose Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-18',
    fromNodeId: 'node-sal-9-2',
    toNodeId: 'node-sal-9-3',
    roadName: 'Rose Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-19',
    fromNodeId: 'node-sal-10-1',
    toNodeId: 'node-sal-10-2',
    roadName: 'University SLC Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sal-20',
    fromNodeId: 'node-sal-10-2',
    toNodeId: 'node-sal-10-3',
    roadName: 'University SLC Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
