/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — San Diego Pacific Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SANDIEGO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 32.7157,
  longitude: -117.1611,
};

export const SANDIEGO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-san-1-1',
    name: 'Gaslamp Quarter Sector 1 High Street',
    zone: 'Gaslamp Quarter',
    location: { latitude: 32.653700, longitude: -117.213100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gaslamp Quarter.',
  },
  {
    id: 'node-san-1-2',
    name: 'Gaslamp Quarter Sector 2 High Street',
    zone: 'Gaslamp Quarter',
    location: { latitude: 32.656700, longitude: -117.210100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gaslamp Quarter.',
  },
  {
    id: 'node-san-1-3',
    name: 'Gaslamp Quarter Sector 3 High Street',
    zone: 'Gaslamp Quarter',
    location: { latitude: 32.659700, longitude: -117.207100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gaslamp Quarter.',
  },
  {
    id: 'node-san-2-1',
    name: 'Little Italy SD Sector 1 High Street',
    zone: 'Little Italy SD',
    location: { latitude: 32.665700, longitude: -117.203100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Little Italy SD.',
  },
  {
    id: 'node-san-2-2',
    name: 'Little Italy SD Sector 2 High Street',
    zone: 'Little Italy SD',
    location: { latitude: 32.668700, longitude: -117.200100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Little Italy SD.',
  },
  {
    id: 'node-san-2-3',
    name: 'Little Italy SD Sector 3 High Street',
    zone: 'Little Italy SD',
    location: { latitude: 32.671700, longitude: -117.197100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Little Italy SD.',
  },
  {
    id: 'node-san-3-1',
    name: 'North Park Sector 1 High Street',
    zone: 'North Park',
    location: { latitude: 32.677700, longitude: -117.193100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in North Park.',
  },
  {
    id: 'node-san-3-2',
    name: 'North Park Sector 2 High Street',
    zone: 'North Park',
    location: { latitude: 32.680700, longitude: -117.190100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in North Park.',
  },
  {
    id: 'node-san-3-3',
    name: 'North Park Sector 3 High Street',
    zone: 'North Park',
    location: { latitude: 32.683700, longitude: -117.187100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in North Park.',
  },
  {
    id: 'node-san-4-1',
    name: 'Hillcrest Sector 1 High Street',
    zone: 'Hillcrest',
    location: { latitude: 32.689700, longitude: -117.183100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hillcrest.',
  },
  {
    id: 'node-san-4-2',
    name: 'Hillcrest Sector 2 High Street',
    zone: 'Hillcrest',
    location: { latitude: 32.692700, longitude: -117.180100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hillcrest.',
  },
  {
    id: 'node-san-4-3',
    name: 'Hillcrest Sector 3 High Street',
    zone: 'Hillcrest',
    location: { latitude: 32.695700, longitude: -117.177100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hillcrest.',
  },
  {
    id: 'node-san-5-1',
    name: 'La Jolla Sector 1 High Street',
    zone: 'La Jolla',
    location: { latitude: 32.701700, longitude: -117.173100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in La Jolla.',
  },
  {
    id: 'node-san-5-2',
    name: 'La Jolla Sector 2 High Street',
    zone: 'La Jolla',
    location: { latitude: 32.704700, longitude: -117.170100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in La Jolla.',
  },
  {
    id: 'node-san-5-3',
    name: 'La Jolla Sector 3 High Street',
    zone: 'La Jolla',
    location: { latitude: 32.707700, longitude: -117.167100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in La Jolla.',
  },
  {
    id: 'node-san-6-1',
    name: 'Pacific Beach Sector 1 High Street',
    zone: 'Pacific Beach',
    location: { latitude: 32.713700, longitude: -117.163100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pacific Beach.',
  },
  {
    id: 'node-san-6-2',
    name: 'Pacific Beach Sector 2 High Street',
    zone: 'Pacific Beach',
    location: { latitude: 32.716700, longitude: -117.160100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pacific Beach.',
  },
  {
    id: 'node-san-6-3',
    name: 'Pacific Beach Sector 3 High Street',
    zone: 'Pacific Beach',
    location: { latitude: 32.719700, longitude: -117.157100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pacific Beach.',
  },
  {
    id: 'node-san-7-1',
    name: 'Ocean Beach Sector 1 High Street',
    zone: 'Ocean Beach',
    location: { latitude: 32.725700, longitude: -117.153100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ocean Beach.',
  },
  {
    id: 'node-san-7-2',
    name: 'Ocean Beach Sector 2 High Street',
    zone: 'Ocean Beach',
    location: { latitude: 32.728700, longitude: -117.150100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ocean Beach.',
  },
  {
    id: 'node-san-7-3',
    name: 'Ocean Beach Sector 3 High Street',
    zone: 'Ocean Beach',
    location: { latitude: 32.731700, longitude: -117.147100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ocean Beach.',
  },
  {
    id: 'node-san-8-1',
    name: 'Coronado Sector 1 High Street',
    zone: 'Coronado',
    location: { latitude: 32.737700, longitude: -117.143100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Coronado.',
  },
  {
    id: 'node-san-8-2',
    name: 'Coronado Sector 2 High Street',
    zone: 'Coronado',
    location: { latitude: 32.740700, longitude: -117.140100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Coronado.',
  },
  {
    id: 'node-san-8-3',
    name: 'Coronado Sector 3 High Street',
    zone: 'Coronado',
    location: { latitude: 32.743700, longitude: -117.137100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Coronado.',
  },
  {
    id: 'node-san-9-1',
    name: 'South Park SD Sector 1 High Street',
    zone: 'South Park SD',
    location: { latitude: 32.749700, longitude: -117.133100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in South Park SD.',
  },
  {
    id: 'node-san-9-2',
    name: 'South Park SD Sector 2 High Street',
    zone: 'South Park SD',
    location: { latitude: 32.752700, longitude: -117.130100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in South Park SD.',
  },
  {
    id: 'node-san-9-3',
    name: 'South Park SD Sector 3 High Street',
    zone: 'South Park SD',
    location: { latitude: 32.755700, longitude: -117.127100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in South Park SD.',
  },
  {
    id: 'node-san-10-1',
    name: 'Mission Hills Sector 1 High Street',
    zone: 'Mission Hills',
    location: { latitude: 32.761700, longitude: -117.123100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mission Hills.',
  },
  {
    id: 'node-san-10-2',
    name: 'Mission Hills Sector 2 High Street',
    zone: 'Mission Hills',
    location: { latitude: 32.764700, longitude: -117.120100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mission Hills.',
  },
  {
    id: 'node-san-10-3',
    name: 'Mission Hills Sector 3 High Street',
    zone: 'Mission Hills',
    location: { latitude: 32.767700, longitude: -117.117100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mission Hills.',
  },
];

export const SANDIEGO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-san-1',
    fromNodeId: 'node-san-1-1',
    toNodeId: 'node-san-1-2',
    roadName: 'Gaslamp Quarter Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-2',
    fromNodeId: 'node-san-1-2',
    toNodeId: 'node-san-1-3',
    roadName: 'Gaslamp Quarter Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-3',
    fromNodeId: 'node-san-2-1',
    toNodeId: 'node-san-2-2',
    roadName: 'Little Italy SD Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-4',
    fromNodeId: 'node-san-2-2',
    toNodeId: 'node-san-2-3',
    roadName: 'Little Italy SD Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-5',
    fromNodeId: 'node-san-3-1',
    toNodeId: 'node-san-3-2',
    roadName: 'North Park Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-6',
    fromNodeId: 'node-san-3-2',
    toNodeId: 'node-san-3-3',
    roadName: 'North Park Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-7',
    fromNodeId: 'node-san-4-1',
    toNodeId: 'node-san-4-2',
    roadName: 'Hillcrest Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-8',
    fromNodeId: 'node-san-4-2',
    toNodeId: 'node-san-4-3',
    roadName: 'Hillcrest Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-9',
    fromNodeId: 'node-san-5-1',
    toNodeId: 'node-san-5-2',
    roadName: 'La Jolla Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-10',
    fromNodeId: 'node-san-5-2',
    toNodeId: 'node-san-5-3',
    roadName: 'La Jolla Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-11',
    fromNodeId: 'node-san-6-1',
    toNodeId: 'node-san-6-2',
    roadName: 'Pacific Beach Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-12',
    fromNodeId: 'node-san-6-2',
    toNodeId: 'node-san-6-3',
    roadName: 'Pacific Beach Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-13',
    fromNodeId: 'node-san-7-1',
    toNodeId: 'node-san-7-2',
    roadName: 'Ocean Beach Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-14',
    fromNodeId: 'node-san-7-2',
    toNodeId: 'node-san-7-3',
    roadName: 'Ocean Beach Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-15',
    fromNodeId: 'node-san-8-1',
    toNodeId: 'node-san-8-2',
    roadName: 'Coronado Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-16',
    fromNodeId: 'node-san-8-2',
    toNodeId: 'node-san-8-3',
    roadName: 'Coronado Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-17',
    fromNodeId: 'node-san-9-1',
    toNodeId: 'node-san-9-2',
    roadName: 'South Park SD Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-18',
    fromNodeId: 'node-san-9-2',
    toNodeId: 'node-san-9-3',
    roadName: 'South Park SD Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-19',
    fromNodeId: 'node-san-10-1',
    toNodeId: 'node-san-10-2',
    roadName: 'Mission Hills Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-20',
    fromNodeId: 'node-san-10-2',
    toNodeId: 'node-san-10-3',
    roadName: 'Mission Hills Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
