/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — San Francisco Bay Area
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SANFRANCISCO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 37.7749,
  longitude: -122.4194,
};

export const SANFRANCISCO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-san-1-1',
    name: 'SoMa Sector 1 High Street',
    zone: 'SoMa',
    location: { latitude: 37.712900, longitude: -122.471400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in SoMa.',
  },
  {
    id: 'node-san-1-2',
    name: 'SoMa Sector 2 High Street',
    zone: 'SoMa',
    location: { latitude: 37.715900, longitude: -122.468400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in SoMa.',
  },
  {
    id: 'node-san-1-3',
    name: 'SoMa Sector 3 High Street',
    zone: 'SoMa',
    location: { latitude: 37.718900, longitude: -122.465400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in SoMa.',
  },
  {
    id: 'node-san-2-1',
    name: 'Mission District Sector 1 High Street',
    zone: 'Mission District',
    location: { latitude: 37.724900, longitude: -122.461400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mission District.',
  },
  {
    id: 'node-san-2-2',
    name: 'Mission District Sector 2 High Street',
    zone: 'Mission District',
    location: { latitude: 37.727900, longitude: -122.458400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mission District.',
  },
  {
    id: 'node-san-2-3',
    name: 'Mission District Sector 3 High Street',
    zone: 'Mission District',
    location: { latitude: 37.730900, longitude: -122.455400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mission District.',
  },
  {
    id: 'node-san-3-1',
    name: 'Marina Sector 1 High Street',
    zone: 'Marina',
    location: { latitude: 37.736900, longitude: -122.451400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Marina.',
  },
  {
    id: 'node-san-3-2',
    name: 'Marina Sector 2 High Street',
    zone: 'Marina',
    location: { latitude: 37.739900, longitude: -122.448400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Marina.',
  },
  {
    id: 'node-san-3-3',
    name: 'Marina Sector 3 High Street',
    zone: 'Marina',
    location: { latitude: 37.742900, longitude: -122.445400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Marina.',
  },
  {
    id: 'node-san-4-1',
    name: 'North Beach Sector 1 High Street',
    zone: 'North Beach',
    location: { latitude: 37.748900, longitude: -122.441400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in North Beach.',
  },
  {
    id: 'node-san-4-2',
    name: 'North Beach Sector 2 High Street',
    zone: 'North Beach',
    location: { latitude: 37.751900, longitude: -122.438400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in North Beach.',
  },
  {
    id: 'node-san-4-3',
    name: 'North Beach Sector 3 High Street',
    zone: 'North Beach',
    location: { latitude: 37.754900, longitude: -122.435400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in North Beach.',
  },
  {
    id: 'node-san-5-1',
    name: 'Financial District SF Sector 1 High Street',
    zone: 'Financial District SF',
    location: { latitude: 37.760900, longitude: -122.431400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Financial District SF.',
  },
  {
    id: 'node-san-5-2',
    name: 'Financial District SF Sector 2 High Street',
    zone: 'Financial District SF',
    location: { latitude: 37.763900, longitude: -122.428400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Financial District SF.',
  },
  {
    id: 'node-san-5-3',
    name: 'Financial District SF Sector 3 High Street',
    zone: 'Financial District SF',
    location: { latitude: 37.766900, longitude: -122.425400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Financial District SF.',
  },
  {
    id: 'node-san-6-1',
    name: 'Hayes Valley Sector 1 High Street',
    zone: 'Hayes Valley',
    location: { latitude: 37.772900, longitude: -122.421400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hayes Valley.',
  },
  {
    id: 'node-san-6-2',
    name: 'Hayes Valley Sector 2 High Street',
    zone: 'Hayes Valley',
    location: { latitude: 37.775900, longitude: -122.418400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hayes Valley.',
  },
  {
    id: 'node-san-6-3',
    name: 'Hayes Valley Sector 3 High Street',
    zone: 'Hayes Valley',
    location: { latitude: 37.778900, longitude: -122.415400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hayes Valley.',
  },
  {
    id: 'node-san-7-1',
    name: 'Pacific Heights Sector 1 High Street',
    zone: 'Pacific Heights',
    location: { latitude: 37.784900, longitude: -122.411400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pacific Heights.',
  },
  {
    id: 'node-san-7-2',
    name: 'Pacific Heights Sector 2 High Street',
    zone: 'Pacific Heights',
    location: { latitude: 37.787900, longitude: -122.408400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pacific Heights.',
  },
  {
    id: 'node-san-7-3',
    name: 'Pacific Heights Sector 3 High Street',
    zone: 'Pacific Heights',
    location: { latitude: 37.790900, longitude: -122.405400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pacific Heights.',
  },
  {
    id: 'node-san-8-1',
    name: 'Castro Sector 1 High Street',
    zone: 'Castro',
    location: { latitude: 37.796900, longitude: -122.401400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Castro.',
  },
  {
    id: 'node-san-8-2',
    name: 'Castro Sector 2 High Street',
    zone: 'Castro',
    location: { latitude: 37.799900, longitude: -122.398400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Castro.',
  },
  {
    id: 'node-san-8-3',
    name: 'Castro Sector 3 High Street',
    zone: 'Castro',
    location: { latitude: 37.802900, longitude: -122.395400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Castro.',
  },
  {
    id: 'node-san-9-1',
    name: 'Silicon Valley Palo Alto Sector 1 High Street',
    zone: 'Silicon Valley Palo Alto',
    location: { latitude: 37.808900, longitude: -122.391400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Silicon Valley Palo Alto.',
  },
  {
    id: 'node-san-9-2',
    name: 'Silicon Valley Palo Alto Sector 2 High Street',
    zone: 'Silicon Valley Palo Alto',
    location: { latitude: 37.811900, longitude: -122.388400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Silicon Valley Palo Alto.',
  },
  {
    id: 'node-san-9-3',
    name: 'Silicon Valley Palo Alto Sector 3 High Street',
    zone: 'Silicon Valley Palo Alto',
    location: { latitude: 37.814900, longitude: -122.385400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Silicon Valley Palo Alto.',
  },
  {
    id: 'node-san-10-1',
    name: 'Berkeley Sector 1 High Street',
    zone: 'Berkeley',
    location: { latitude: 37.820900, longitude: -122.381400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Berkeley.',
  },
  {
    id: 'node-san-10-2',
    name: 'Berkeley Sector 2 High Street',
    zone: 'Berkeley',
    location: { latitude: 37.823900, longitude: -122.378400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Berkeley.',
  },
  {
    id: 'node-san-10-3',
    name: 'Berkeley Sector 3 High Street',
    zone: 'Berkeley',
    location: { latitude: 37.826900, longitude: -122.375400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Berkeley.',
  },
];

export const SANFRANCISCO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-san-1',
    fromNodeId: 'node-san-1-1',
    toNodeId: 'node-san-1-2',
    roadName: 'SoMa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-2',
    fromNodeId: 'node-san-1-2',
    toNodeId: 'node-san-1-3',
    roadName: 'SoMa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-3',
    fromNodeId: 'node-san-2-1',
    toNodeId: 'node-san-2-2',
    roadName: 'Mission District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-4',
    fromNodeId: 'node-san-2-2',
    toNodeId: 'node-san-2-3',
    roadName: 'Mission District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-5',
    fromNodeId: 'node-san-3-1',
    toNodeId: 'node-san-3-2',
    roadName: 'Marina Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-6',
    fromNodeId: 'node-san-3-2',
    toNodeId: 'node-san-3-3',
    roadName: 'Marina Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-7',
    fromNodeId: 'node-san-4-1',
    toNodeId: 'node-san-4-2',
    roadName: 'North Beach Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-8',
    fromNodeId: 'node-san-4-2',
    toNodeId: 'node-san-4-3',
    roadName: 'North Beach Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-9',
    fromNodeId: 'node-san-5-1',
    toNodeId: 'node-san-5-2',
    roadName: 'Financial District SF Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-10',
    fromNodeId: 'node-san-5-2',
    toNodeId: 'node-san-5-3',
    roadName: 'Financial District SF Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-11',
    fromNodeId: 'node-san-6-1',
    toNodeId: 'node-san-6-2',
    roadName: 'Hayes Valley Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-12',
    fromNodeId: 'node-san-6-2',
    toNodeId: 'node-san-6-3',
    roadName: 'Hayes Valley Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-13',
    fromNodeId: 'node-san-7-1',
    toNodeId: 'node-san-7-2',
    roadName: 'Pacific Heights Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-14',
    fromNodeId: 'node-san-7-2',
    toNodeId: 'node-san-7-3',
    roadName: 'Pacific Heights Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-15',
    fromNodeId: 'node-san-8-1',
    toNodeId: 'node-san-8-2',
    roadName: 'Castro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-16',
    fromNodeId: 'node-san-8-2',
    toNodeId: 'node-san-8-3',
    roadName: 'Castro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-17',
    fromNodeId: 'node-san-9-1',
    toNodeId: 'node-san-9-2',
    roadName: 'Silicon Valley Palo Alto Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-18',
    fromNodeId: 'node-san-9-2',
    toNodeId: 'node-san-9-3',
    roadName: 'Silicon Valley Palo Alto Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-19',
    fromNodeId: 'node-san-10-1',
    toNodeId: 'node-san-10-2',
    roadName: 'Berkeley Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-san-20',
    fromNodeId: 'node-san-10-2',
    toNodeId: 'node-san-10-3',
    roadName: 'Berkeley Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
