/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Sapporo Hokkaido Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SAPPORO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 43.0618,
  longitude: 141.3545,
};

export const SAPPORO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sap-1-1',
    name: 'Susukino Sector 1 High Street',
    zone: 'Susukino',
    location: { latitude: 42.999800, longitude: 141.302500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Susukino.',
  },
  {
    id: 'node-sap-1-2',
    name: 'Susukino Sector 2 High Street',
    zone: 'Susukino',
    location: { latitude: 43.002800, longitude: 141.305500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Susukino.',
  },
  {
    id: 'node-sap-1-3',
    name: 'Susukino Sector 3 High Street',
    zone: 'Susukino',
    location: { latitude: 43.005800, longitude: 141.308500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Susukino.',
  },
  {
    id: 'node-sap-2-1',
    name: 'Odori Sector 1 High Street',
    zone: 'Odori',
    location: { latitude: 43.011800, longitude: 141.312500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Odori.',
  },
  {
    id: 'node-sap-2-2',
    name: 'Odori Sector 2 High Street',
    zone: 'Odori',
    location: { latitude: 43.014800, longitude: 141.315500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Odori.',
  },
  {
    id: 'node-sap-2-3',
    name: 'Odori Sector 3 High Street',
    zone: 'Odori',
    location: { latitude: 43.017800, longitude: 141.318500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Odori.',
  },
  {
    id: 'node-sap-3-1',
    name: 'Sapporo Station Sector 1 High Street',
    zone: 'Sapporo Station',
    location: { latitude: 43.023800, longitude: 141.322500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sapporo Station.',
  },
  {
    id: 'node-sap-3-2',
    name: 'Sapporo Station Sector 2 High Street',
    zone: 'Sapporo Station',
    location: { latitude: 43.026800, longitude: 141.325500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sapporo Station.',
  },
  {
    id: 'node-sap-3-3',
    name: 'Sapporo Station Sector 3 High Street',
    zone: 'Sapporo Station',
    location: { latitude: 43.029800, longitude: 141.328500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sapporo Station.',
  },
  {
    id: 'node-sap-4-1',
    name: 'Maruyama Sector 1 High Street',
    zone: 'Maruyama',
    location: { latitude: 43.035800, longitude: 141.332500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Maruyama.',
  },
  {
    id: 'node-sap-4-2',
    name: 'Maruyama Sector 2 High Street',
    zone: 'Maruyama',
    location: { latitude: 43.038800, longitude: 141.335500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Maruyama.',
  },
  {
    id: 'node-sap-4-3',
    name: 'Maruyama Sector 3 High Street',
    zone: 'Maruyama',
    location: { latitude: 43.041800, longitude: 141.338500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Maruyama.',
  },
  {
    id: 'node-sap-5-1',
    name: 'Kotoni Sector 1 High Street',
    zone: 'Kotoni',
    location: { latitude: 43.047800, longitude: 141.342500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kotoni.',
  },
  {
    id: 'node-sap-5-2',
    name: 'Kotoni Sector 2 High Street',
    zone: 'Kotoni',
    location: { latitude: 43.050800, longitude: 141.345500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kotoni.',
  },
  {
    id: 'node-sap-5-3',
    name: 'Kotoni Sector 3 High Street',
    zone: 'Kotoni',
    location: { latitude: 43.053800, longitude: 141.348500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kotoni.',
  },
  {
    id: 'node-sap-6-1',
    name: 'Tanukikoji Sector 1 High Street',
    zone: 'Tanukikoji',
    location: { latitude: 43.059800, longitude: 141.352500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tanukikoji.',
  },
  {
    id: 'node-sap-6-2',
    name: 'Tanukikoji Sector 2 High Street',
    zone: 'Tanukikoji',
    location: { latitude: 43.062800, longitude: 141.355500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tanukikoji.',
  },
  {
    id: 'node-sap-6-3',
    name: 'Tanukikoji Sector 3 High Street',
    zone: 'Tanukikoji',
    location: { latitude: 43.065800, longitude: 141.358500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tanukikoji.',
  },
  {
    id: 'node-sap-7-1',
    name: 'Miyanomori Sector 1 High Street',
    zone: 'Miyanomori',
    location: { latitude: 43.071800, longitude: 141.362500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Miyanomori.',
  },
  {
    id: 'node-sap-7-2',
    name: 'Miyanomori Sector 2 High Street',
    zone: 'Miyanomori',
    location: { latitude: 43.074800, longitude: 141.365500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Miyanomori.',
  },
  {
    id: 'node-sap-7-3',
    name: 'Miyanomori Sector 3 High Street',
    zone: 'Miyanomori',
    location: { latitude: 43.077800, longitude: 141.368500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Miyanomori.',
  },
  {
    id: 'node-sap-8-1',
    name: 'Toyohira Sector 1 High Street',
    zone: 'Toyohira',
    location: { latitude: 43.083800, longitude: 141.372500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Toyohira.',
  },
  {
    id: 'node-sap-8-2',
    name: 'Toyohira Sector 2 High Street',
    zone: 'Toyohira',
    location: { latitude: 43.086800, longitude: 141.375500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Toyohira.',
  },
  {
    id: 'node-sap-8-3',
    name: 'Toyohira Sector 3 High Street',
    zone: 'Toyohira',
    location: { latitude: 43.089800, longitude: 141.378500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Toyohira.',
  },
  {
    id: 'node-sap-9-1',
    name: 'Kita Ward Sector 1 High Street',
    zone: 'Kita Ward',
    location: { latitude: 43.095800, longitude: 141.382500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kita Ward.',
  },
  {
    id: 'node-sap-9-2',
    name: 'Kita Ward Sector 2 High Street',
    zone: 'Kita Ward',
    location: { latitude: 43.098800, longitude: 141.385500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kita Ward.',
  },
  {
    id: 'node-sap-9-3',
    name: 'Kita Ward Sector 3 High Street',
    zone: 'Kita Ward',
    location: { latitude: 43.101800, longitude: 141.388500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kita Ward.',
  },
  {
    id: 'node-sap-10-1',
    name: 'Shiroishi Sector 1 High Street',
    zone: 'Shiroishi',
    location: { latitude: 43.107800, longitude: 141.392500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shiroishi.',
  },
  {
    id: 'node-sap-10-2',
    name: 'Shiroishi Sector 2 High Street',
    zone: 'Shiroishi',
    location: { latitude: 43.110800, longitude: 141.395500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shiroishi.',
  },
  {
    id: 'node-sap-10-3',
    name: 'Shiroishi Sector 3 High Street',
    zone: 'Shiroishi',
    location: { latitude: 43.113800, longitude: 141.398500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shiroishi.',
  },
];

export const SAPPORO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sap-1',
    fromNodeId: 'node-sap-1-1',
    toNodeId: 'node-sap-1-2',
    roadName: 'Susukino Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-2',
    fromNodeId: 'node-sap-1-2',
    toNodeId: 'node-sap-1-3',
    roadName: 'Susukino Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-3',
    fromNodeId: 'node-sap-2-1',
    toNodeId: 'node-sap-2-2',
    roadName: 'Odori Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-4',
    fromNodeId: 'node-sap-2-2',
    toNodeId: 'node-sap-2-3',
    roadName: 'Odori Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-5',
    fromNodeId: 'node-sap-3-1',
    toNodeId: 'node-sap-3-2',
    roadName: 'Sapporo Station Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-6',
    fromNodeId: 'node-sap-3-2',
    toNodeId: 'node-sap-3-3',
    roadName: 'Sapporo Station Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-7',
    fromNodeId: 'node-sap-4-1',
    toNodeId: 'node-sap-4-2',
    roadName: 'Maruyama Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-8',
    fromNodeId: 'node-sap-4-2',
    toNodeId: 'node-sap-4-3',
    roadName: 'Maruyama Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-9',
    fromNodeId: 'node-sap-5-1',
    toNodeId: 'node-sap-5-2',
    roadName: 'Kotoni Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-10',
    fromNodeId: 'node-sap-5-2',
    toNodeId: 'node-sap-5-3',
    roadName: 'Kotoni Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-11',
    fromNodeId: 'node-sap-6-1',
    toNodeId: 'node-sap-6-2',
    roadName: 'Tanukikoji Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-12',
    fromNodeId: 'node-sap-6-2',
    toNodeId: 'node-sap-6-3',
    roadName: 'Tanukikoji Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-13',
    fromNodeId: 'node-sap-7-1',
    toNodeId: 'node-sap-7-2',
    roadName: 'Miyanomori Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-14',
    fromNodeId: 'node-sap-7-2',
    toNodeId: 'node-sap-7-3',
    roadName: 'Miyanomori Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-15',
    fromNodeId: 'node-sap-8-1',
    toNodeId: 'node-sap-8-2',
    roadName: 'Toyohira Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-16',
    fromNodeId: 'node-sap-8-2',
    toNodeId: 'node-sap-8-3',
    roadName: 'Toyohira Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-17',
    fromNodeId: 'node-sap-9-1',
    toNodeId: 'node-sap-9-2',
    roadName: 'Kita Ward Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-18',
    fromNodeId: 'node-sap-9-2',
    toNodeId: 'node-sap-9-3',
    roadName: 'Kita Ward Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-19',
    fromNodeId: 'node-sap-10-1',
    toNodeId: 'node-sap-10-2',
    roadName: 'Shiroishi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sap-20',
    fromNodeId: 'node-sap-10-2',
    toNodeId: 'node-sap-10-3',
    roadName: 'Shiroishi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
