/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Seattle Puget Sound Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SEATTLE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 47.6062,
  longitude: -122.3321,
};

export const SEATTLE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sea-1-1',
    name: 'Capitol Hill Sector 1 High Street',
    zone: 'Capitol Hill',
    location: { latitude: 47.544200, longitude: -122.384100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Capitol Hill.',
  },
  {
    id: 'node-sea-1-2',
    name: 'Capitol Hill Sector 2 High Street',
    zone: 'Capitol Hill',
    location: { latitude: 47.547200, longitude: -122.381100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Capitol Hill.',
  },
  {
    id: 'node-sea-1-3',
    name: 'Capitol Hill Sector 3 High Street',
    zone: 'Capitol Hill',
    location: { latitude: 47.550200, longitude: -122.378100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Capitol Hill.',
  },
  {
    id: 'node-sea-2-1',
    name: 'Downtown Seattle Sector 1 High Street',
    zone: 'Downtown Seattle',
    location: { latitude: 47.556200, longitude: -122.374100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Seattle.',
  },
  {
    id: 'node-sea-2-2',
    name: 'Downtown Seattle Sector 2 High Street',
    zone: 'Downtown Seattle',
    location: { latitude: 47.559200, longitude: -122.371100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Seattle.',
  },
  {
    id: 'node-sea-2-3',
    name: 'Downtown Seattle Sector 3 High Street',
    zone: 'Downtown Seattle',
    location: { latitude: 47.562200, longitude: -122.368100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Seattle.',
  },
  {
    id: 'node-sea-3-1',
    name: 'Ballard Sector 1 High Street',
    zone: 'Ballard',
    location: { latitude: 47.568200, longitude: -122.364100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ballard.',
  },
  {
    id: 'node-sea-3-2',
    name: 'Ballard Sector 2 High Street',
    zone: 'Ballard',
    location: { latitude: 47.571200, longitude: -122.361100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ballard.',
  },
  {
    id: 'node-sea-3-3',
    name: 'Ballard Sector 3 High Street',
    zone: 'Ballard',
    location: { latitude: 47.574200, longitude: -122.358100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ballard.',
  },
  {
    id: 'node-sea-4-1',
    name: 'Fremont Sector 1 High Street',
    zone: 'Fremont',
    location: { latitude: 47.580200, longitude: -122.354100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fremont.',
  },
  {
    id: 'node-sea-4-2',
    name: 'Fremont Sector 2 High Street',
    zone: 'Fremont',
    location: { latitude: 47.583200, longitude: -122.351100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fremont.',
  },
  {
    id: 'node-sea-4-3',
    name: 'Fremont Sector 3 High Street',
    zone: 'Fremont',
    location: { latitude: 47.586200, longitude: -122.348100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fremont.',
  },
  {
    id: 'node-sea-5-1',
    name: 'Belltown Sector 1 High Street',
    zone: 'Belltown',
    location: { latitude: 47.592200, longitude: -122.344100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Belltown.',
  },
  {
    id: 'node-sea-5-2',
    name: 'Belltown Sector 2 High Street',
    zone: 'Belltown',
    location: { latitude: 47.595200, longitude: -122.341100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Belltown.',
  },
  {
    id: 'node-sea-5-3',
    name: 'Belltown Sector 3 High Street',
    zone: 'Belltown',
    location: { latitude: 47.598200, longitude: -122.338100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Belltown.',
  },
  {
    id: 'node-sea-6-1',
    name: 'Queen Anne Sector 1 High Street',
    zone: 'Queen Anne',
    location: { latitude: 47.604200, longitude: -122.334100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Queen Anne.',
  },
  {
    id: 'node-sea-6-2',
    name: 'Queen Anne Sector 2 High Street',
    zone: 'Queen Anne',
    location: { latitude: 47.607200, longitude: -122.331100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Queen Anne.',
  },
  {
    id: 'node-sea-6-3',
    name: 'Queen Anne Sector 3 High Street',
    zone: 'Queen Anne',
    location: { latitude: 47.610200, longitude: -122.328100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Queen Anne.',
  },
  {
    id: 'node-sea-7-1',
    name: 'South Lake Union Sector 1 High Street',
    zone: 'South Lake Union',
    location: { latitude: 47.616200, longitude: -122.324100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in South Lake Union.',
  },
  {
    id: 'node-sea-7-2',
    name: 'South Lake Union Sector 2 High Street',
    zone: 'South Lake Union',
    location: { latitude: 47.619200, longitude: -122.321100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in South Lake Union.',
  },
  {
    id: 'node-sea-7-3',
    name: 'South Lake Union Sector 3 High Street',
    zone: 'South Lake Union',
    location: { latitude: 47.622200, longitude: -122.318100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in South Lake Union.',
  },
  {
    id: 'node-sea-8-1',
    name: 'Pioneer Square Sector 1 High Street',
    zone: 'Pioneer Square',
    location: { latitude: 47.628200, longitude: -122.314100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pioneer Square.',
  },
  {
    id: 'node-sea-8-2',
    name: 'Pioneer Square Sector 2 High Street',
    zone: 'Pioneer Square',
    location: { latitude: 47.631200, longitude: -122.311100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pioneer Square.',
  },
  {
    id: 'node-sea-8-3',
    name: 'Pioneer Square Sector 3 High Street',
    zone: 'Pioneer Square',
    location: { latitude: 47.634200, longitude: -122.308100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pioneer Square.',
  },
  {
    id: 'node-sea-9-1',
    name: 'Green Lake Sector 1 High Street',
    zone: 'Green Lake',
    location: { latitude: 47.640200, longitude: -122.304100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Green Lake.',
  },
  {
    id: 'node-sea-9-2',
    name: 'Green Lake Sector 2 High Street',
    zone: 'Green Lake',
    location: { latitude: 47.643200, longitude: -122.301100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Green Lake.',
  },
  {
    id: 'node-sea-9-3',
    name: 'Green Lake Sector 3 High Street',
    zone: 'Green Lake',
    location: { latitude: 47.646200, longitude: -122.298100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Green Lake.',
  },
  {
    id: 'node-sea-10-1',
    name: 'Bellevue WA Sector 1 High Street',
    zone: 'Bellevue WA',
    location: { latitude: 47.652200, longitude: -122.294100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bellevue WA.',
  },
  {
    id: 'node-sea-10-2',
    name: 'Bellevue WA Sector 2 High Street',
    zone: 'Bellevue WA',
    location: { latitude: 47.655200, longitude: -122.291100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bellevue WA.',
  },
  {
    id: 'node-sea-10-3',
    name: 'Bellevue WA Sector 3 High Street',
    zone: 'Bellevue WA',
    location: { latitude: 47.658200, longitude: -122.288100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bellevue WA.',
  },
];

export const SEATTLE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sea-1',
    fromNodeId: 'node-sea-1-1',
    toNodeId: 'node-sea-1-2',
    roadName: 'Capitol Hill Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-2',
    fromNodeId: 'node-sea-1-2',
    toNodeId: 'node-sea-1-3',
    roadName: 'Capitol Hill Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-3',
    fromNodeId: 'node-sea-2-1',
    toNodeId: 'node-sea-2-2',
    roadName: 'Downtown Seattle Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-4',
    fromNodeId: 'node-sea-2-2',
    toNodeId: 'node-sea-2-3',
    roadName: 'Downtown Seattle Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-5',
    fromNodeId: 'node-sea-3-1',
    toNodeId: 'node-sea-3-2',
    roadName: 'Ballard Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-6',
    fromNodeId: 'node-sea-3-2',
    toNodeId: 'node-sea-3-3',
    roadName: 'Ballard Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-7',
    fromNodeId: 'node-sea-4-1',
    toNodeId: 'node-sea-4-2',
    roadName: 'Fremont Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-8',
    fromNodeId: 'node-sea-4-2',
    toNodeId: 'node-sea-4-3',
    roadName: 'Fremont Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-9',
    fromNodeId: 'node-sea-5-1',
    toNodeId: 'node-sea-5-2',
    roadName: 'Belltown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-10',
    fromNodeId: 'node-sea-5-2',
    toNodeId: 'node-sea-5-3',
    roadName: 'Belltown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-11',
    fromNodeId: 'node-sea-6-1',
    toNodeId: 'node-sea-6-2',
    roadName: 'Queen Anne Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-12',
    fromNodeId: 'node-sea-6-2',
    toNodeId: 'node-sea-6-3',
    roadName: 'Queen Anne Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-13',
    fromNodeId: 'node-sea-7-1',
    toNodeId: 'node-sea-7-2',
    roadName: 'South Lake Union Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-14',
    fromNodeId: 'node-sea-7-2',
    toNodeId: 'node-sea-7-3',
    roadName: 'South Lake Union Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-15',
    fromNodeId: 'node-sea-8-1',
    toNodeId: 'node-sea-8-2',
    roadName: 'Pioneer Square Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-16',
    fromNodeId: 'node-sea-8-2',
    toNodeId: 'node-sea-8-3',
    roadName: 'Pioneer Square Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-17',
    fromNodeId: 'node-sea-9-1',
    toNodeId: 'node-sea-9-2',
    roadName: 'Green Lake Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-18',
    fromNodeId: 'node-sea-9-2',
    toNodeId: 'node-sea-9-3',
    roadName: 'Green Lake Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-19',
    fromNodeId: 'node-sea-10-1',
    toNodeId: 'node-sea-10-2',
    roadName: 'Bellevue WA Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sea-20',
    fromNodeId: 'node-sea-10-2',
    toNodeId: 'node-sea-10-3',
    roadName: 'Bellevue WA Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
