/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Seoul Gangnam & Hongdae Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SEOUL_BASE_COORDINATE: GeoCoordinate = {
  latitude: 37.5665,
  longitude: 126.978,
};

export const SEOUL_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-seo-1-1',
    name: 'Gangnam Sector 1 High Street',
    zone: 'Gangnam',
    location: { latitude: 37.504500, longitude: 126.926000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gangnam.',
  },
  {
    id: 'node-seo-1-2',
    name: 'Gangnam Sector 2 High Street',
    zone: 'Gangnam',
    location: { latitude: 37.507500, longitude: 126.929000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gangnam.',
  },
  {
    id: 'node-seo-1-3',
    name: 'Gangnam Sector 3 High Street',
    zone: 'Gangnam',
    location: { latitude: 37.510500, longitude: 126.932000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gangnam.',
  },
  {
    id: 'node-seo-2-1',
    name: 'Hongdae Sector 1 High Street',
    zone: 'Hongdae',
    location: { latitude: 37.516500, longitude: 126.936000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hongdae.',
  },
  {
    id: 'node-seo-2-2',
    name: 'Hongdae Sector 2 High Street',
    zone: 'Hongdae',
    location: { latitude: 37.519500, longitude: 126.939000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hongdae.',
  },
  {
    id: 'node-seo-2-3',
    name: 'Hongdae Sector 3 High Street',
    zone: 'Hongdae',
    location: { latitude: 37.522500, longitude: 126.942000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hongdae.',
  },
  {
    id: 'node-seo-3-1',
    name: 'Myeongdong Sector 1 High Street',
    zone: 'Myeongdong',
    location: { latitude: 37.528500, longitude: 126.946000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Myeongdong.',
  },
  {
    id: 'node-seo-3-2',
    name: 'Myeongdong Sector 2 High Street',
    zone: 'Myeongdong',
    location: { latitude: 37.531500, longitude: 126.949000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Myeongdong.',
  },
  {
    id: 'node-seo-3-3',
    name: 'Myeongdong Sector 3 High Street',
    zone: 'Myeongdong',
    location: { latitude: 37.534500, longitude: 126.952000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Myeongdong.',
  },
  {
    id: 'node-seo-4-1',
    name: 'Itaewon Sector 1 High Street',
    zone: 'Itaewon',
    location: { latitude: 37.540500, longitude: 126.956000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Itaewon.',
  },
  {
    id: 'node-seo-4-2',
    name: 'Itaewon Sector 2 High Street',
    zone: 'Itaewon',
    location: { latitude: 37.543500, longitude: 126.959000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Itaewon.',
  },
  {
    id: 'node-seo-4-3',
    name: 'Itaewon Sector 3 High Street',
    zone: 'Itaewon',
    location: { latitude: 37.546500, longitude: 126.962000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Itaewon.',
  },
  {
    id: 'node-seo-5-1',
    name: 'Insadong Sector 1 High Street',
    zone: 'Insadong',
    location: { latitude: 37.552500, longitude: 126.966000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Insadong.',
  },
  {
    id: 'node-seo-5-2',
    name: 'Insadong Sector 2 High Street',
    zone: 'Insadong',
    location: { latitude: 37.555500, longitude: 126.969000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Insadong.',
  },
  {
    id: 'node-seo-5-3',
    name: 'Insadong Sector 3 High Street',
    zone: 'Insadong',
    location: { latitude: 37.558500, longitude: 126.972000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Insadong.',
  },
  {
    id: 'node-seo-6-1',
    name: 'Jongno Sector 1 High Street',
    zone: 'Jongno',
    location: { latitude: 37.564500, longitude: 126.976000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jongno.',
  },
  {
    id: 'node-seo-6-2',
    name: 'Jongno Sector 2 High Street',
    zone: 'Jongno',
    location: { latitude: 37.567500, longitude: 126.979000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jongno.',
  },
  {
    id: 'node-seo-6-3',
    name: 'Jongno Sector 3 High Street',
    zone: 'Jongno',
    location: { latitude: 37.570500, longitude: 126.982000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jongno.',
  },
  {
    id: 'node-seo-7-1',
    name: 'Yeouido Sector 1 High Street',
    zone: 'Yeouido',
    location: { latitude: 37.576500, longitude: 126.986000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Yeouido.',
  },
  {
    id: 'node-seo-7-2',
    name: 'Yeouido Sector 2 High Street',
    zone: 'Yeouido',
    location: { latitude: 37.579500, longitude: 126.989000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Yeouido.',
  },
  {
    id: 'node-seo-7-3',
    name: 'Yeouido Sector 3 High Street',
    zone: 'Yeouido',
    location: { latitude: 37.582500, longitude: 126.992000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Yeouido.',
  },
  {
    id: 'node-seo-8-1',
    name: 'Apgujeong Sector 1 High Street',
    zone: 'Apgujeong',
    location: { latitude: 37.588500, longitude: 126.996000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Apgujeong.',
  },
  {
    id: 'node-seo-8-2',
    name: 'Apgujeong Sector 2 High Street',
    zone: 'Apgujeong',
    location: { latitude: 37.591500, longitude: 126.999000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Apgujeong.',
  },
  {
    id: 'node-seo-8-3',
    name: 'Apgujeong Sector 3 High Street',
    zone: 'Apgujeong',
    location: { latitude: 37.594500, longitude: 127.002000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Apgujeong.',
  },
  {
    id: 'node-seo-9-1',
    name: 'Seongsu Sector 1 High Street',
    zone: 'Seongsu',
    location: { latitude: 37.600500, longitude: 127.006000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Seongsu.',
  },
  {
    id: 'node-seo-9-2',
    name: 'Seongsu Sector 2 High Street',
    zone: 'Seongsu',
    location: { latitude: 37.603500, longitude: 127.009000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Seongsu.',
  },
  {
    id: 'node-seo-9-3',
    name: 'Seongsu Sector 3 High Street',
    zone: 'Seongsu',
    location: { latitude: 37.606500, longitude: 127.012000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Seongsu.',
  },
  {
    id: 'node-seo-10-1',
    name: 'Sinchon Sector 1 High Street',
    zone: 'Sinchon',
    location: { latitude: 37.612500, longitude: 127.016000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sinchon.',
  },
  {
    id: 'node-seo-10-2',
    name: 'Sinchon Sector 2 High Street',
    zone: 'Sinchon',
    location: { latitude: 37.615500, longitude: 127.019000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sinchon.',
  },
  {
    id: 'node-seo-10-3',
    name: 'Sinchon Sector 3 High Street',
    zone: 'Sinchon',
    location: { latitude: 37.618500, longitude: 127.022000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sinchon.',
  },
];

export const SEOUL_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-seo-1',
    fromNodeId: 'node-seo-1-1',
    toNodeId: 'node-seo-1-2',
    roadName: 'Gangnam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-2',
    fromNodeId: 'node-seo-1-2',
    toNodeId: 'node-seo-1-3',
    roadName: 'Gangnam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-3',
    fromNodeId: 'node-seo-2-1',
    toNodeId: 'node-seo-2-2',
    roadName: 'Hongdae Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-4',
    fromNodeId: 'node-seo-2-2',
    toNodeId: 'node-seo-2-3',
    roadName: 'Hongdae Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-5',
    fromNodeId: 'node-seo-3-1',
    toNodeId: 'node-seo-3-2',
    roadName: 'Myeongdong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-6',
    fromNodeId: 'node-seo-3-2',
    toNodeId: 'node-seo-3-3',
    roadName: 'Myeongdong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-7',
    fromNodeId: 'node-seo-4-1',
    toNodeId: 'node-seo-4-2',
    roadName: 'Itaewon Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-8',
    fromNodeId: 'node-seo-4-2',
    toNodeId: 'node-seo-4-3',
    roadName: 'Itaewon Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-9',
    fromNodeId: 'node-seo-5-1',
    toNodeId: 'node-seo-5-2',
    roadName: 'Insadong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-10',
    fromNodeId: 'node-seo-5-2',
    toNodeId: 'node-seo-5-3',
    roadName: 'Insadong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-11',
    fromNodeId: 'node-seo-6-1',
    toNodeId: 'node-seo-6-2',
    roadName: 'Jongno Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-12',
    fromNodeId: 'node-seo-6-2',
    toNodeId: 'node-seo-6-3',
    roadName: 'Jongno Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-13',
    fromNodeId: 'node-seo-7-1',
    toNodeId: 'node-seo-7-2',
    roadName: 'Yeouido Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-14',
    fromNodeId: 'node-seo-7-2',
    toNodeId: 'node-seo-7-3',
    roadName: 'Yeouido Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-15',
    fromNodeId: 'node-seo-8-1',
    toNodeId: 'node-seo-8-2',
    roadName: 'Apgujeong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-16',
    fromNodeId: 'node-seo-8-2',
    toNodeId: 'node-seo-8-3',
    roadName: 'Apgujeong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-17',
    fromNodeId: 'node-seo-9-1',
    toNodeId: 'node-seo-9-2',
    roadName: 'Seongsu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-18',
    fromNodeId: 'node-seo-9-2',
    toNodeId: 'node-seo-9-3',
    roadName: 'Seongsu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-19',
    fromNodeId: 'node-seo-10-1',
    toNodeId: 'node-seo-10-2',
    roadName: 'Sinchon Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-seo-20',
    fromNodeId: 'node-seo-10-2',
    toNodeId: 'node-seo-10-3',
    roadName: 'Sinchon Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
