/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Seville Andalusian Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SEVILLE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 37.3891,
  longitude: -5.9845,
};

export const SEVILLE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sev-1-1',
    name: 'Santa Cruz Sector 1 High Street',
    zone: 'Santa Cruz',
    location: { latitude: 37.327100, longitude: -6.036500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Santa Cruz.',
  },
  {
    id: 'node-sev-1-2',
    name: 'Santa Cruz Sector 2 High Street',
    zone: 'Santa Cruz',
    location: { latitude: 37.330100, longitude: -6.033500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Santa Cruz.',
  },
  {
    id: 'node-sev-1-3',
    name: 'Santa Cruz Sector 3 High Street',
    zone: 'Santa Cruz',
    location: { latitude: 37.333100, longitude: -6.030500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Santa Cruz.',
  },
  {
    id: 'node-sev-2-1',
    name: 'Triana Sector 1 High Street',
    zone: 'Triana',
    location: { latitude: 37.339100, longitude: -6.026500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Triana.',
  },
  {
    id: 'node-sev-2-2',
    name: 'Triana Sector 2 High Street',
    zone: 'Triana',
    location: { latitude: 37.342100, longitude: -6.023500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Triana.',
  },
  {
    id: 'node-sev-2-3',
    name: 'Triana Sector 3 High Street',
    zone: 'Triana',
    location: { latitude: 37.345100, longitude: -6.020500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Triana.',
  },
  {
    id: 'node-sev-3-1',
    name: 'El Arenal Sector 1 High Street',
    zone: 'El Arenal',
    location: { latitude: 37.351100, longitude: -6.016500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in El Arenal.',
  },
  {
    id: 'node-sev-3-2',
    name: 'El Arenal Sector 2 High Street',
    zone: 'El Arenal',
    location: { latitude: 37.354100, longitude: -6.013500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in El Arenal.',
  },
  {
    id: 'node-sev-3-3',
    name: 'El Arenal Sector 3 High Street',
    zone: 'El Arenal',
    location: { latitude: 37.357100, longitude: -6.010500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in El Arenal.',
  },
  {
    id: 'node-sev-4-1',
    name: 'Centro Seville Sector 1 High Street',
    zone: 'Centro Seville',
    location: { latitude: 37.363100, longitude: -6.006500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Centro Seville.',
  },
  {
    id: 'node-sev-4-2',
    name: 'Centro Seville Sector 2 High Street',
    zone: 'Centro Seville',
    location: { latitude: 37.366100, longitude: -6.003500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Centro Seville.',
  },
  {
    id: 'node-sev-4-3',
    name: 'Centro Seville Sector 3 High Street',
    zone: 'Centro Seville',
    location: { latitude: 37.369100, longitude: -6.000500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Centro Seville.',
  },
  {
    id: 'node-sev-5-1',
    name: 'Macarena Sector 1 High Street',
    zone: 'Macarena',
    location: { latitude: 37.375100, longitude: -5.996500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Macarena.',
  },
  {
    id: 'node-sev-5-2',
    name: 'Macarena Sector 2 High Street',
    zone: 'Macarena',
    location: { latitude: 37.378100, longitude: -5.993500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Macarena.',
  },
  {
    id: 'node-sev-5-3',
    name: 'Macarena Sector 3 High Street',
    zone: 'Macarena',
    location: { latitude: 37.381100, longitude: -5.990500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Macarena.',
  },
  {
    id: 'node-sev-6-1',
    name: 'Alameda de Hércules Sector 1 High Street',
    zone: 'Alameda de Hércules',
    location: { latitude: 37.387100, longitude: -5.986500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Alameda de Hércules.',
  },
  {
    id: 'node-sev-6-2',
    name: 'Alameda de Hércules Sector 2 High Street',
    zone: 'Alameda de Hércules',
    location: { latitude: 37.390100, longitude: -5.983500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Alameda de Hércules.',
  },
  {
    id: 'node-sev-6-3',
    name: 'Alameda de Hércules Sector 3 High Street',
    zone: 'Alameda de Hércules',
    location: { latitude: 37.393100, longitude: -5.980500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Alameda de Hércules.',
  },
  {
    id: 'node-sev-7-1',
    name: 'Los Remedios Sector 1 High Street',
    zone: 'Los Remedios',
    location: { latitude: 37.399100, longitude: -5.976500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Los Remedios.',
  },
  {
    id: 'node-sev-7-2',
    name: 'Los Remedios Sector 2 High Street',
    zone: 'Los Remedios',
    location: { latitude: 37.402100, longitude: -5.973500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Los Remedios.',
  },
  {
    id: 'node-sev-7-3',
    name: 'Los Remedios Sector 3 High Street',
    zone: 'Los Remedios',
    location: { latitude: 37.405100, longitude: -5.970500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Los Remedios.',
  },
  {
    id: 'node-sev-8-1',
    name: 'Nervión Sector 1 High Street',
    zone: 'Nervión',
    location: { latitude: 37.411100, longitude: -5.966500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nervión.',
  },
  {
    id: 'node-sev-8-2',
    name: 'Nervión Sector 2 High Street',
    zone: 'Nervión',
    location: { latitude: 37.414100, longitude: -5.963500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nervión.',
  },
  {
    id: 'node-sev-8-3',
    name: 'Nervión Sector 3 High Street',
    zone: 'Nervión',
    location: { latitude: 37.417100, longitude: -5.960500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nervión.',
  },
  {
    id: 'node-sev-9-1',
    name: 'San Bernardo Sector 1 High Street',
    zone: 'San Bernardo',
    location: { latitude: 37.423100, longitude: -5.956500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Bernardo.',
  },
  {
    id: 'node-sev-9-2',
    name: 'San Bernardo Sector 2 High Street',
    zone: 'San Bernardo',
    location: { latitude: 37.426100, longitude: -5.953500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Bernardo.',
  },
  {
    id: 'node-sev-9-3',
    name: 'San Bernardo Sector 3 High Street',
    zone: 'San Bernardo',
    location: { latitude: 37.429100, longitude: -5.950500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Bernardo.',
  },
  {
    id: 'node-sev-10-1',
    name: 'La Palmera Sector 1 High Street',
    zone: 'La Palmera',
    location: { latitude: 37.435100, longitude: -5.946500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in La Palmera.',
  },
  {
    id: 'node-sev-10-2',
    name: 'La Palmera Sector 2 High Street',
    zone: 'La Palmera',
    location: { latitude: 37.438100, longitude: -5.943500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in La Palmera.',
  },
  {
    id: 'node-sev-10-3',
    name: 'La Palmera Sector 3 High Street',
    zone: 'La Palmera',
    location: { latitude: 37.441100, longitude: -5.940500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in La Palmera.',
  },
];

export const SEVILLE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sev-1',
    fromNodeId: 'node-sev-1-1',
    toNodeId: 'node-sev-1-2',
    roadName: 'Santa Cruz Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-2',
    fromNodeId: 'node-sev-1-2',
    toNodeId: 'node-sev-1-3',
    roadName: 'Santa Cruz Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-3',
    fromNodeId: 'node-sev-2-1',
    toNodeId: 'node-sev-2-2',
    roadName: 'Triana Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-4',
    fromNodeId: 'node-sev-2-2',
    toNodeId: 'node-sev-2-3',
    roadName: 'Triana Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-5',
    fromNodeId: 'node-sev-3-1',
    toNodeId: 'node-sev-3-2',
    roadName: 'El Arenal Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-6',
    fromNodeId: 'node-sev-3-2',
    toNodeId: 'node-sev-3-3',
    roadName: 'El Arenal Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-7',
    fromNodeId: 'node-sev-4-1',
    toNodeId: 'node-sev-4-2',
    roadName: 'Centro Seville Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-8',
    fromNodeId: 'node-sev-4-2',
    toNodeId: 'node-sev-4-3',
    roadName: 'Centro Seville Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-9',
    fromNodeId: 'node-sev-5-1',
    toNodeId: 'node-sev-5-2',
    roadName: 'Macarena Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-10',
    fromNodeId: 'node-sev-5-2',
    toNodeId: 'node-sev-5-3',
    roadName: 'Macarena Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-11',
    fromNodeId: 'node-sev-6-1',
    toNodeId: 'node-sev-6-2',
    roadName: 'Alameda de Hércules Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-12',
    fromNodeId: 'node-sev-6-2',
    toNodeId: 'node-sev-6-3',
    roadName: 'Alameda de Hércules Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-13',
    fromNodeId: 'node-sev-7-1',
    toNodeId: 'node-sev-7-2',
    roadName: 'Los Remedios Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-14',
    fromNodeId: 'node-sev-7-2',
    toNodeId: 'node-sev-7-3',
    roadName: 'Los Remedios Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-15',
    fromNodeId: 'node-sev-8-1',
    toNodeId: 'node-sev-8-2',
    roadName: 'Nervión Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-16',
    fromNodeId: 'node-sev-8-2',
    toNodeId: 'node-sev-8-3',
    roadName: 'Nervión Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-17',
    fromNodeId: 'node-sev-9-1',
    toNodeId: 'node-sev-9-2',
    roadName: 'San Bernardo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-18',
    fromNodeId: 'node-sev-9-2',
    toNodeId: 'node-sev-9-3',
    roadName: 'San Bernardo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-19',
    fromNodeId: 'node-sev-10-1',
    toNodeId: 'node-sev-10-2',
    roadName: 'La Palmera Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sev-20',
    fromNodeId: 'node-sev-10-2',
    toNodeId: 'node-sev-10-3',
    roadName: 'La Palmera Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
