/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Shillong Scotland of East
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SHILLONG_BASE_COORDINATE: GeoCoordinate = {
  latitude: 25.5788,
  longitude: 91.8933,
};

export const SHILLONG_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-shi-1-1',
    name: 'Police Bazaar Sector 1 High Street',
    zone: 'Police Bazaar',
    location: { latitude: 25.516800, longitude: 91.841300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Police Bazaar.',
  },
  {
    id: 'node-shi-1-2',
    name: 'Police Bazaar Sector 2 High Street',
    zone: 'Police Bazaar',
    location: { latitude: 25.519800, longitude: 91.844300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Police Bazaar.',
  },
  {
    id: 'node-shi-1-3',
    name: 'Police Bazaar Sector 3 High Street',
    zone: 'Police Bazaar',
    location: { latitude: 25.522800, longitude: 91.847300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Police Bazaar.',
  },
  {
    id: 'node-shi-2-1',
    name: 'Laitumkhrah Sector 1 High Street',
    zone: 'Laitumkhrah',
    location: { latitude: 25.528800, longitude: 91.851300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Laitumkhrah.',
  },
  {
    id: 'node-shi-2-2',
    name: 'Laitumkhrah Sector 2 High Street',
    zone: 'Laitumkhrah',
    location: { latitude: 25.531800, longitude: 91.854300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Laitumkhrah.',
  },
  {
    id: 'node-shi-2-3',
    name: 'Laitumkhrah Sector 3 High Street',
    zone: 'Laitumkhrah',
    location: { latitude: 25.534800, longitude: 91.857300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Laitumkhrah.',
  },
  {
    id: 'node-shi-3-1',
    name: 'Labans Sector 1 High Street',
    zone: 'Labans',
    location: { latitude: 25.540800, longitude: 91.861300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Labans.',
  },
  {
    id: 'node-shi-3-2',
    name: 'Labans Sector 2 High Street',
    zone: 'Labans',
    location: { latitude: 25.543800, longitude: 91.864300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Labans.',
  },
  {
    id: 'node-shi-3-3',
    name: 'Labans Sector 3 High Street',
    zone: 'Labans',
    location: { latitude: 25.546800, longitude: 91.867300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Labans.',
  },
  {
    id: 'node-shi-4-1',
    name: 'Mawkhar Sector 1 High Street',
    zone: 'Mawkhar',
    location: { latitude: 25.552800, longitude: 91.871300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mawkhar.',
  },
  {
    id: 'node-shi-4-2',
    name: 'Mawkhar Sector 2 High Street',
    zone: 'Mawkhar',
    location: { latitude: 25.555800, longitude: 91.874300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mawkhar.',
  },
  {
    id: 'node-shi-4-3',
    name: 'Mawkhar Sector 3 High Street',
    zone: 'Mawkhar',
    location: { latitude: 25.558800, longitude: 91.877300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mawkhar.',
  },
  {
    id: 'node-shi-5-1',
    name: 'Malki Sector 1 High Street',
    zone: 'Malki',
    location: { latitude: 25.564800, longitude: 91.881300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Malki.',
  },
  {
    id: 'node-shi-5-2',
    name: 'Malki Sector 2 High Street',
    zone: 'Malki',
    location: { latitude: 25.567800, longitude: 91.884300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Malki.',
  },
  {
    id: 'node-shi-5-3',
    name: 'Malki Sector 3 High Street',
    zone: 'Malki',
    location: { latitude: 25.570800, longitude: 91.887300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Malki.',
  },
  {
    id: 'node-shi-6-1',
    name: 'Risa Colony Sector 1 High Street',
    zone: 'Risa Colony',
    location: { latitude: 25.576800, longitude: 91.891300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Risa Colony.',
  },
  {
    id: 'node-shi-6-2',
    name: 'Risa Colony Sector 2 High Street',
    zone: 'Risa Colony',
    location: { latitude: 25.579800, longitude: 91.894300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Risa Colony.',
  },
  {
    id: 'node-shi-6-3',
    name: 'Risa Colony Sector 3 High Street',
    zone: 'Risa Colony',
    location: { latitude: 25.582800, longitude: 91.897300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Risa Colony.',
  },
  {
    id: 'node-shi-7-1',
    name: 'Nongthymmai Sector 1 High Street',
    zone: 'Nongthymmai',
    location: { latitude: 25.588800, longitude: 91.901300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nongthymmai.',
  },
  {
    id: 'node-shi-7-2',
    name: 'Nongthymmai Sector 2 High Street',
    zone: 'Nongthymmai',
    location: { latitude: 25.591800, longitude: 91.904300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nongthymmai.',
  },
  {
    id: 'node-shi-7-3',
    name: 'Nongthymmai Sector 3 High Street',
    zone: 'Nongthymmai',
    location: { latitude: 25.594800, longitude: 91.907300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nongthymmai.',
  },
  {
    id: 'node-shi-8-1',
    name: 'Polo Grounds Sector 1 High Street',
    zone: 'Polo Grounds',
    location: { latitude: 25.600800, longitude: 91.911300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Polo Grounds.',
  },
  {
    id: 'node-shi-8-2',
    name: 'Polo Grounds Sector 2 High Street',
    zone: 'Polo Grounds',
    location: { latitude: 25.603800, longitude: 91.914300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Polo Grounds.',
  },
  {
    id: 'node-shi-8-3',
    name: 'Polo Grounds Sector 3 High Street',
    zone: 'Polo Grounds',
    location: { latitude: 25.606800, longitude: 91.917300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Polo Grounds.',
  },
  {
    id: 'node-shi-9-1',
    name: 'Cleve Colony Sector 1 High Street',
    zone: 'Cleve Colony',
    location: { latitude: 25.612800, longitude: 91.921300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cleve Colony.',
  },
  {
    id: 'node-shi-9-2',
    name: 'Cleve Colony Sector 2 High Street',
    zone: 'Cleve Colony',
    location: { latitude: 25.615800, longitude: 91.924300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cleve Colony.',
  },
  {
    id: 'node-shi-9-3',
    name: 'Cleve Colony Sector 3 High Street',
    zone: 'Cleve Colony',
    location: { latitude: 25.618800, longitude: 91.927300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cleve Colony.',
  },
  {
    id: 'node-shi-10-1',
    name: 'Barik Sector 1 High Street',
    zone: 'Barik',
    location: { latitude: 25.624800, longitude: 91.931300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Barik.',
  },
  {
    id: 'node-shi-10-2',
    name: 'Barik Sector 2 High Street',
    zone: 'Barik',
    location: { latitude: 25.627800, longitude: 91.934300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Barik.',
  },
  {
    id: 'node-shi-10-3',
    name: 'Barik Sector 3 High Street',
    zone: 'Barik',
    location: { latitude: 25.630800, longitude: 91.937300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Barik.',
  },
];

export const SHILLONG_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-shi-1',
    fromNodeId: 'node-shi-1-1',
    toNodeId: 'node-shi-1-2',
    roadName: 'Police Bazaar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-2',
    fromNodeId: 'node-shi-1-2',
    toNodeId: 'node-shi-1-3',
    roadName: 'Police Bazaar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-3',
    fromNodeId: 'node-shi-2-1',
    toNodeId: 'node-shi-2-2',
    roadName: 'Laitumkhrah Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-4',
    fromNodeId: 'node-shi-2-2',
    toNodeId: 'node-shi-2-3',
    roadName: 'Laitumkhrah Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-5',
    fromNodeId: 'node-shi-3-1',
    toNodeId: 'node-shi-3-2',
    roadName: 'Labans Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-6',
    fromNodeId: 'node-shi-3-2',
    toNodeId: 'node-shi-3-3',
    roadName: 'Labans Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-7',
    fromNodeId: 'node-shi-4-1',
    toNodeId: 'node-shi-4-2',
    roadName: 'Mawkhar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-8',
    fromNodeId: 'node-shi-4-2',
    toNodeId: 'node-shi-4-3',
    roadName: 'Mawkhar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-9',
    fromNodeId: 'node-shi-5-1',
    toNodeId: 'node-shi-5-2',
    roadName: 'Malki Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-10',
    fromNodeId: 'node-shi-5-2',
    toNodeId: 'node-shi-5-3',
    roadName: 'Malki Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-11',
    fromNodeId: 'node-shi-6-1',
    toNodeId: 'node-shi-6-2',
    roadName: 'Risa Colony Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-12',
    fromNodeId: 'node-shi-6-2',
    toNodeId: 'node-shi-6-3',
    roadName: 'Risa Colony Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-13',
    fromNodeId: 'node-shi-7-1',
    toNodeId: 'node-shi-7-2',
    roadName: 'Nongthymmai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-14',
    fromNodeId: 'node-shi-7-2',
    toNodeId: 'node-shi-7-3',
    roadName: 'Nongthymmai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-15',
    fromNodeId: 'node-shi-8-1',
    toNodeId: 'node-shi-8-2',
    roadName: 'Polo Grounds Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-16',
    fromNodeId: 'node-shi-8-2',
    toNodeId: 'node-shi-8-3',
    roadName: 'Polo Grounds Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-17',
    fromNodeId: 'node-shi-9-1',
    toNodeId: 'node-shi-9-2',
    roadName: 'Cleve Colony Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-18',
    fromNodeId: 'node-shi-9-2',
    toNodeId: 'node-shi-9-3',
    roadName: 'Cleve Colony Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-19',
    fromNodeId: 'node-shi-10-1',
    toNodeId: 'node-shi-10-2',
    roadName: 'Barik Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-shi-20',
    fromNodeId: 'node-shi-10-2',
    toNodeId: 'node-shi-10-3',
    roadName: 'Barik Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
