/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Singapore Island City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SINGAPORE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 1.3521,
  longitude: 103.8198,
};

export const SINGAPORE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sin-1-1',
    name: 'Orchard Road Sector 1 High Street',
    zone: 'Orchard Road',
    location: { latitude: 1.290100, longitude: 103.767800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Orchard Road.',
  },
  {
    id: 'node-sin-1-2',
    name: 'Orchard Road Sector 2 High Street',
    zone: 'Orchard Road',
    location: { latitude: 1.293100, longitude: 103.770800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Orchard Road.',
  },
  {
    id: 'node-sin-1-3',
    name: 'Orchard Road Sector 3 High Street',
    zone: 'Orchard Road',
    location: { latitude: 1.296100, longitude: 103.773800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Orchard Road.',
  },
  {
    id: 'node-sin-2-1',
    name: 'Marina Bay Sector 1 High Street',
    zone: 'Marina Bay',
    location: { latitude: 1.302100, longitude: 103.777800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Marina Bay.',
  },
  {
    id: 'node-sin-2-2',
    name: 'Marina Bay Sector 2 High Street',
    zone: 'Marina Bay',
    location: { latitude: 1.305100, longitude: 103.780800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Marina Bay.',
  },
  {
    id: 'node-sin-2-3',
    name: 'Marina Bay Sector 3 High Street',
    zone: 'Marina Bay',
    location: { latitude: 1.308100, longitude: 103.783800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Marina Bay.',
  },
  {
    id: 'node-sin-3-1',
    name: 'Tanjong Pagar Sector 1 High Street',
    zone: 'Tanjong Pagar',
    location: { latitude: 1.314100, longitude: 103.787800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tanjong Pagar.',
  },
  {
    id: 'node-sin-3-2',
    name: 'Tanjong Pagar Sector 2 High Street',
    zone: 'Tanjong Pagar',
    location: { latitude: 1.317100, longitude: 103.790800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tanjong Pagar.',
  },
  {
    id: 'node-sin-3-3',
    name: 'Tanjong Pagar Sector 3 High Street',
    zone: 'Tanjong Pagar',
    location: { latitude: 1.320100, longitude: 103.793800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tanjong Pagar.',
  },
  {
    id: 'node-sin-4-1',
    name: 'Clarke Quay Sector 1 High Street',
    zone: 'Clarke Quay',
    location: { latitude: 1.326100, longitude: 103.797800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Clarke Quay.',
  },
  {
    id: 'node-sin-4-2',
    name: 'Clarke Quay Sector 2 High Street',
    zone: 'Clarke Quay',
    location: { latitude: 1.329100, longitude: 103.800800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Clarke Quay.',
  },
  {
    id: 'node-sin-4-3',
    name: 'Clarke Quay Sector 3 High Street',
    zone: 'Clarke Quay',
    location: { latitude: 1.332100, longitude: 103.803800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Clarke Quay.',
  },
  {
    id: 'node-sin-5-1',
    name: 'Chinatown Sector 1 High Street',
    zone: 'Chinatown',
    location: { latitude: 1.338100, longitude: 103.807800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chinatown.',
  },
  {
    id: 'node-sin-5-2',
    name: 'Chinatown Sector 2 High Street',
    zone: 'Chinatown',
    location: { latitude: 1.341100, longitude: 103.810800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chinatown.',
  },
  {
    id: 'node-sin-5-3',
    name: 'Chinatown Sector 3 High Street',
    zone: 'Chinatown',
    location: { latitude: 1.344100, longitude: 103.813800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chinatown.',
  },
  {
    id: 'node-sin-6-1',
    name: 'Little India Sector 1 High Street',
    zone: 'Little India',
    location: { latitude: 1.350100, longitude: 103.817800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Little India.',
  },
  {
    id: 'node-sin-6-2',
    name: 'Little India Sector 2 High Street',
    zone: 'Little India',
    location: { latitude: 1.353100, longitude: 103.820800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Little India.',
  },
  {
    id: 'node-sin-6-3',
    name: 'Little India Sector 3 High Street',
    zone: 'Little India',
    location: { latitude: 1.356100, longitude: 103.823800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Little India.',
  },
  {
    id: 'node-sin-7-1',
    name: 'Katong Sector 1 High Street',
    zone: 'Katong',
    location: { latitude: 1.362100, longitude: 103.827800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Katong.',
  },
  {
    id: 'node-sin-7-2',
    name: 'Katong Sector 2 High Street',
    zone: 'Katong',
    location: { latitude: 1.365100, longitude: 103.830800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Katong.',
  },
  {
    id: 'node-sin-7-3',
    name: 'Katong Sector 3 High Street',
    zone: 'Katong',
    location: { latitude: 1.368100, longitude: 103.833800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Katong.',
  },
  {
    id: 'node-sin-8-1',
    name: 'Jurong East Sector 1 High Street',
    zone: 'Jurong East',
    location: { latitude: 1.374100, longitude: 103.837800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jurong East.',
  },
  {
    id: 'node-sin-8-2',
    name: 'Jurong East Sector 2 High Street',
    zone: 'Jurong East',
    location: { latitude: 1.377100, longitude: 103.840800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jurong East.',
  },
  {
    id: 'node-sin-8-3',
    name: 'Jurong East Sector 3 High Street',
    zone: 'Jurong East',
    location: { latitude: 1.380100, longitude: 103.843800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jurong East.',
  },
  {
    id: 'node-sin-9-1',
    name: 'Novena Sector 1 High Street',
    zone: 'Novena',
    location: { latitude: 1.386100, longitude: 103.847800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Novena.',
  },
  {
    id: 'node-sin-9-2',
    name: 'Novena Sector 2 High Street',
    zone: 'Novena',
    location: { latitude: 1.389100, longitude: 103.850800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Novena.',
  },
  {
    id: 'node-sin-9-3',
    name: 'Novena Sector 3 High Street',
    zone: 'Novena',
    location: { latitude: 1.392100, longitude: 103.853800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Novena.',
  },
  {
    id: 'node-sin-10-1',
    name: 'Bugis Sector 1 High Street',
    zone: 'Bugis',
    location: { latitude: 1.398100, longitude: 103.857800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bugis.',
  },
  {
    id: 'node-sin-10-2',
    name: 'Bugis Sector 2 High Street',
    zone: 'Bugis',
    location: { latitude: 1.401100, longitude: 103.860800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bugis.',
  },
  {
    id: 'node-sin-10-3',
    name: 'Bugis Sector 3 High Street',
    zone: 'Bugis',
    location: { latitude: 1.404100, longitude: 103.863800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bugis.',
  },
];

export const SINGAPORE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sin-1',
    fromNodeId: 'node-sin-1-1',
    toNodeId: 'node-sin-1-2',
    roadName: 'Orchard Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-2',
    fromNodeId: 'node-sin-1-2',
    toNodeId: 'node-sin-1-3',
    roadName: 'Orchard Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-3',
    fromNodeId: 'node-sin-2-1',
    toNodeId: 'node-sin-2-2',
    roadName: 'Marina Bay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-4',
    fromNodeId: 'node-sin-2-2',
    toNodeId: 'node-sin-2-3',
    roadName: 'Marina Bay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-5',
    fromNodeId: 'node-sin-3-1',
    toNodeId: 'node-sin-3-2',
    roadName: 'Tanjong Pagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-6',
    fromNodeId: 'node-sin-3-2',
    toNodeId: 'node-sin-3-3',
    roadName: 'Tanjong Pagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-7',
    fromNodeId: 'node-sin-4-1',
    toNodeId: 'node-sin-4-2',
    roadName: 'Clarke Quay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-8',
    fromNodeId: 'node-sin-4-2',
    toNodeId: 'node-sin-4-3',
    roadName: 'Clarke Quay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-9',
    fromNodeId: 'node-sin-5-1',
    toNodeId: 'node-sin-5-2',
    roadName: 'Chinatown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-10',
    fromNodeId: 'node-sin-5-2',
    toNodeId: 'node-sin-5-3',
    roadName: 'Chinatown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-11',
    fromNodeId: 'node-sin-6-1',
    toNodeId: 'node-sin-6-2',
    roadName: 'Little India Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-12',
    fromNodeId: 'node-sin-6-2',
    toNodeId: 'node-sin-6-3',
    roadName: 'Little India Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-13',
    fromNodeId: 'node-sin-7-1',
    toNodeId: 'node-sin-7-2',
    roadName: 'Katong Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-14',
    fromNodeId: 'node-sin-7-2',
    toNodeId: 'node-sin-7-3',
    roadName: 'Katong Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-15',
    fromNodeId: 'node-sin-8-1',
    toNodeId: 'node-sin-8-2',
    roadName: 'Jurong East Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-16',
    fromNodeId: 'node-sin-8-2',
    toNodeId: 'node-sin-8-3',
    roadName: 'Jurong East Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-17',
    fromNodeId: 'node-sin-9-1',
    toNodeId: 'node-sin-9-2',
    roadName: 'Novena Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-18',
    fromNodeId: 'node-sin-9-2',
    toNodeId: 'node-sin-9-3',
    roadName: 'Novena Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-19',
    fromNodeId: 'node-sin-10-1',
    toNodeId: 'node-sin-10-2',
    roadName: 'Bugis Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sin-20',
    fromNodeId: 'node-sin-10-2',
    toNodeId: 'node-sin-10-3',
    roadName: 'Bugis Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
