/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Sofia Vitosha Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SOFIA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 42.6977,
  longitude: 23.3219,
};

export const SOFIA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sof-1-1',
    name: 'Sofia Center Sector 1 High Street',
    zone: 'Sofia Center',
    location: { latitude: 42.635700, longitude: 23.269900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sofia Center.',
  },
  {
    id: 'node-sof-1-2',
    name: 'Sofia Center Sector 2 High Street',
    zone: 'Sofia Center',
    location: { latitude: 42.638700, longitude: 23.272900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sofia Center.',
  },
  {
    id: 'node-sof-1-3',
    name: 'Sofia Center Sector 3 High Street',
    zone: 'Sofia Center',
    location: { latitude: 42.641700, longitude: 23.275900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sofia Center.',
  },
  {
    id: 'node-sof-2-1',
    name: 'Lozenets Sector 1 High Street',
    zone: 'Lozenets',
    location: { latitude: 42.647700, longitude: 23.279900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lozenets.',
  },
  {
    id: 'node-sof-2-2',
    name: 'Lozenets Sector 2 High Street',
    zone: 'Lozenets',
    location: { latitude: 42.650700, longitude: 23.282900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lozenets.',
  },
  {
    id: 'node-sof-2-3',
    name: 'Lozenets Sector 3 High Street',
    zone: 'Lozenets',
    location: { latitude: 42.653700, longitude: 23.285900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lozenets.',
  },
  {
    id: 'node-sof-3-1',
    name: 'Ivan Vazov Sector 1 High Street',
    zone: 'Ivan Vazov',
    location: { latitude: 42.659700, longitude: 23.289900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ivan Vazov.',
  },
  {
    id: 'node-sof-3-2',
    name: 'Ivan Vazov Sector 2 High Street',
    zone: 'Ivan Vazov',
    location: { latitude: 42.662700, longitude: 23.292900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ivan Vazov.',
  },
  {
    id: 'node-sof-3-3',
    name: 'Ivan Vazov Sector 3 High Street',
    zone: 'Ivan Vazov',
    location: { latitude: 42.665700, longitude: 23.295900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ivan Vazov.',
  },
  {
    id: 'node-sof-4-1',
    name: 'Oborishte Sector 1 High Street',
    zone: 'Oborishte',
    location: { latitude: 42.671700, longitude: 23.299900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Oborishte.',
  },
  {
    id: 'node-sof-4-2',
    name: 'Oborishte Sector 2 High Street',
    zone: 'Oborishte',
    location: { latitude: 42.674700, longitude: 23.302900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Oborishte.',
  },
  {
    id: 'node-sof-4-3',
    name: 'Oborishte Sector 3 High Street',
    zone: 'Oborishte',
    location: { latitude: 42.677700, longitude: 23.305900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Oborishte.',
  },
  {
    id: 'node-sof-5-1',
    name: 'Vitosha District Sector 1 High Street',
    zone: 'Vitosha District',
    location: { latitude: 42.683700, longitude: 23.309900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vitosha District.',
  },
  {
    id: 'node-sof-5-2',
    name: 'Vitosha District Sector 2 High Street',
    zone: 'Vitosha District',
    location: { latitude: 42.686700, longitude: 23.312900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vitosha District.',
  },
  {
    id: 'node-sof-5-3',
    name: 'Vitosha District Sector 3 High Street',
    zone: 'Vitosha District',
    location: { latitude: 42.689700, longitude: 23.315900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vitosha District.',
  },
  {
    id: 'node-sof-6-1',
    name: 'Mladost Sector 1 High Street',
    zone: 'Mladost',
    location: { latitude: 42.695700, longitude: 23.319900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mladost.',
  },
  {
    id: 'node-sof-6-2',
    name: 'Mladost Sector 2 High Street',
    zone: 'Mladost',
    location: { latitude: 42.698700, longitude: 23.322900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mladost.',
  },
  {
    id: 'node-sof-6-3',
    name: 'Mladost Sector 3 High Street',
    zone: 'Mladost',
    location: { latitude: 42.701700, longitude: 23.325900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mladost.',
  },
  {
    id: 'node-sof-7-1',
    name: 'Studentski Grad Sector 1 High Street',
    zone: 'Studentski Grad',
    location: { latitude: 42.707700, longitude: 23.329900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Studentski Grad.',
  },
  {
    id: 'node-sof-7-2',
    name: 'Studentski Grad Sector 2 High Street',
    zone: 'Studentski Grad',
    location: { latitude: 42.710700, longitude: 23.332900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Studentski Grad.',
  },
  {
    id: 'node-sof-7-3',
    name: 'Studentski Grad Sector 3 High Street',
    zone: 'Studentski Grad',
    location: { latitude: 42.713700, longitude: 23.335900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Studentski Grad.',
  },
  {
    id: 'node-sof-8-1',
    name: 'Geo Milev Sector 1 High Street',
    zone: 'Geo Milev',
    location: { latitude: 42.719700, longitude: 23.339900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Geo Milev.',
  },
  {
    id: 'node-sof-8-2',
    name: 'Geo Milev Sector 2 High Street',
    zone: 'Geo Milev',
    location: { latitude: 42.722700, longitude: 23.342900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Geo Milev.',
  },
  {
    id: 'node-sof-8-3',
    name: 'Geo Milev Sector 3 High Street',
    zone: 'Geo Milev',
    location: { latitude: 42.725700, longitude: 23.345900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Geo Milev.',
  },
  {
    id: 'node-sof-9-1',
    name: 'Iztok Sector 1 High Street',
    zone: 'Iztok',
    location: { latitude: 42.731700, longitude: 23.349900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Iztok.',
  },
  {
    id: 'node-sof-9-2',
    name: 'Iztok Sector 2 High Street',
    zone: 'Iztok',
    location: { latitude: 42.734700, longitude: 23.352900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Iztok.',
  },
  {
    id: 'node-sof-9-3',
    name: 'Iztok Sector 3 High Street',
    zone: 'Iztok',
    location: { latitude: 42.737700, longitude: 23.355900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Iztok.',
  },
  {
    id: 'node-sof-10-1',
    name: 'Borovo Sector 1 High Street',
    zone: 'Borovo',
    location: { latitude: 42.743700, longitude: 23.359900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Borovo.',
  },
  {
    id: 'node-sof-10-2',
    name: 'Borovo Sector 2 High Street',
    zone: 'Borovo',
    location: { latitude: 42.746700, longitude: 23.362900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Borovo.',
  },
  {
    id: 'node-sof-10-3',
    name: 'Borovo Sector 3 High Street',
    zone: 'Borovo',
    location: { latitude: 42.749700, longitude: 23.365900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Borovo.',
  },
];

export const SOFIA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sof-1',
    fromNodeId: 'node-sof-1-1',
    toNodeId: 'node-sof-1-2',
    roadName: 'Sofia Center Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-2',
    fromNodeId: 'node-sof-1-2',
    toNodeId: 'node-sof-1-3',
    roadName: 'Sofia Center Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-3',
    fromNodeId: 'node-sof-2-1',
    toNodeId: 'node-sof-2-2',
    roadName: 'Lozenets Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-4',
    fromNodeId: 'node-sof-2-2',
    toNodeId: 'node-sof-2-3',
    roadName: 'Lozenets Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-5',
    fromNodeId: 'node-sof-3-1',
    toNodeId: 'node-sof-3-2',
    roadName: 'Ivan Vazov Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-6',
    fromNodeId: 'node-sof-3-2',
    toNodeId: 'node-sof-3-3',
    roadName: 'Ivan Vazov Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-7',
    fromNodeId: 'node-sof-4-1',
    toNodeId: 'node-sof-4-2',
    roadName: 'Oborishte Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-8',
    fromNodeId: 'node-sof-4-2',
    toNodeId: 'node-sof-4-3',
    roadName: 'Oborishte Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-9',
    fromNodeId: 'node-sof-5-1',
    toNodeId: 'node-sof-5-2',
    roadName: 'Vitosha District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-10',
    fromNodeId: 'node-sof-5-2',
    toNodeId: 'node-sof-5-3',
    roadName: 'Vitosha District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-11',
    fromNodeId: 'node-sof-6-1',
    toNodeId: 'node-sof-6-2',
    roadName: 'Mladost Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-12',
    fromNodeId: 'node-sof-6-2',
    toNodeId: 'node-sof-6-3',
    roadName: 'Mladost Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-13',
    fromNodeId: 'node-sof-7-1',
    toNodeId: 'node-sof-7-2',
    roadName: 'Studentski Grad Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-14',
    fromNodeId: 'node-sof-7-2',
    toNodeId: 'node-sof-7-3',
    roadName: 'Studentski Grad Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-15',
    fromNodeId: 'node-sof-8-1',
    toNodeId: 'node-sof-8-2',
    roadName: 'Geo Milev Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-16',
    fromNodeId: 'node-sof-8-2',
    toNodeId: 'node-sof-8-3',
    roadName: 'Geo Milev Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-17',
    fromNodeId: 'node-sof-9-1',
    toNodeId: 'node-sof-9-2',
    roadName: 'Iztok Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-18',
    fromNodeId: 'node-sof-9-2',
    toNodeId: 'node-sof-9-3',
    roadName: 'Iztok Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-19',
    fromNodeId: 'node-sof-10-1',
    toNodeId: 'node-sof-10-2',
    roadName: 'Borovo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sof-20',
    fromNodeId: 'node-sof-10-2',
    toNodeId: 'node-sof-10-3',
    roadName: 'Borovo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
