/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Solapur Textile Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SOLAPUR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 17.6599,
  longitude: 75.9064,
};

export const SOLAPUR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sol-1-1',
    name: 'Saat Rasta Sector 1 High Street',
    zone: 'Saat Rasta',
    location: { latitude: 17.597900, longitude: 75.854400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Saat Rasta.',
  },
  {
    id: 'node-sol-1-2',
    name: 'Saat Rasta Sector 2 High Street',
    zone: 'Saat Rasta',
    location: { latitude: 17.600900, longitude: 75.857400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Saat Rasta.',
  },
  {
    id: 'node-sol-1-3',
    name: 'Saat Rasta Sector 3 High Street',
    zone: 'Saat Rasta',
    location: { latitude: 17.603900, longitude: 75.860400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Saat Rasta.',
  },
  {
    id: 'node-sol-2-1',
    name: 'Hotgi Road Sector 1 High Street',
    zone: 'Hotgi Road',
    location: { latitude: 17.609900, longitude: 75.864400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hotgi Road.',
  },
  {
    id: 'node-sol-2-2',
    name: 'Hotgi Road Sector 2 High Street',
    zone: 'Hotgi Road',
    location: { latitude: 17.612900, longitude: 75.867400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hotgi Road.',
  },
  {
    id: 'node-sol-2-3',
    name: 'Hotgi Road Sector 3 High Street',
    zone: 'Hotgi Road',
    location: { latitude: 17.615900, longitude: 75.870400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hotgi Road.',
  },
  {
    id: 'node-sol-3-1',
    name: 'Jule Solapur Sector 1 High Street',
    zone: 'Jule Solapur',
    location: { latitude: 17.621900, longitude: 75.874400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Jule Solapur.',
  },
  {
    id: 'node-sol-3-2',
    name: 'Jule Solapur Sector 2 High Street',
    zone: 'Jule Solapur',
    location: { latitude: 17.624900, longitude: 75.877400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Jule Solapur.',
  },
  {
    id: 'node-sol-3-3',
    name: 'Jule Solapur Sector 3 High Street',
    zone: 'Jule Solapur',
    location: { latitude: 17.627900, longitude: 75.880400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Jule Solapur.',
  },
  {
    id: 'node-sol-4-1',
    name: 'Lashkar Sector 1 High Street',
    zone: 'Lashkar',
    location: { latitude: 17.633900, longitude: 75.884400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lashkar.',
  },
  {
    id: 'node-sol-4-2',
    name: 'Lashkar Sector 2 High Street',
    zone: 'Lashkar',
    location: { latitude: 17.636900, longitude: 75.887400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lashkar.',
  },
  {
    id: 'node-sol-4-3',
    name: 'Lashkar Sector 3 High Street',
    zone: 'Lashkar',
    location: { latitude: 17.639900, longitude: 75.890400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lashkar.',
  },
  {
    id: 'node-sol-5-1',
    name: 'Old Pune Naka Sector 1 High Street',
    zone: 'Old Pune Naka',
    location: { latitude: 17.645900, longitude: 75.894400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Old Pune Naka.',
  },
  {
    id: 'node-sol-5-2',
    name: 'Old Pune Naka Sector 2 High Street',
    zone: 'Old Pune Naka',
    location: { latitude: 17.648900, longitude: 75.897400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Old Pune Naka.',
  },
  {
    id: 'node-sol-5-3',
    name: 'Old Pune Naka Sector 3 High Street',
    zone: 'Old Pune Naka',
    location: { latitude: 17.651900, longitude: 75.900400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Old Pune Naka.',
  },
  {
    id: 'node-sol-6-1',
    name: 'Navi Peth Sector 1 High Street',
    zone: 'Navi Peth',
    location: { latitude: 17.657900, longitude: 75.904400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Navi Peth.',
  },
  {
    id: 'node-sol-6-2',
    name: 'Navi Peth Sector 2 High Street',
    zone: 'Navi Peth',
    location: { latitude: 17.660900, longitude: 75.907400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Navi Peth.',
  },
  {
    id: 'node-sol-6-3',
    name: 'Navi Peth Sector 3 High Street',
    zone: 'Navi Peth',
    location: { latitude: 17.663900, longitude: 75.910400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Navi Peth.',
  },
  {
    id: 'node-sol-7-1',
    name: 'MIDC Sector 1 High Street',
    zone: 'MIDC',
    location: { latitude: 17.669900, longitude: 75.914400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in MIDC.',
  },
  {
    id: 'node-sol-7-2',
    name: 'MIDC Sector 2 High Street',
    zone: 'MIDC',
    location: { latitude: 17.672900, longitude: 75.917400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in MIDC.',
  },
  {
    id: 'node-sol-7-3',
    name: 'MIDC Sector 3 High Street',
    zone: 'MIDC',
    location: { latitude: 17.675900, longitude: 75.920400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in MIDC.',
  },
  {
    id: 'node-sol-8-1',
    name: 'Bhavani Peth Sector 1 High Street',
    zone: 'Bhavani Peth',
    location: { latitude: 17.681900, longitude: 75.924400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bhavani Peth.',
  },
  {
    id: 'node-sol-8-2',
    name: 'Bhavani Peth Sector 2 High Street',
    zone: 'Bhavani Peth',
    location: { latitude: 17.684900, longitude: 75.927400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bhavani Peth.',
  },
  {
    id: 'node-sol-8-3',
    name: 'Bhavani Peth Sector 3 High Street',
    zone: 'Bhavani Peth',
    location: { latitude: 17.687900, longitude: 75.930400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bhavani Peth.',
  },
  {
    id: 'node-sol-9-1',
    name: 'Budhwar Peth Sector 1 High Street',
    zone: 'Budhwar Peth',
    location: { latitude: 17.693900, longitude: 75.934400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Budhwar Peth.',
  },
  {
    id: 'node-sol-9-2',
    name: 'Budhwar Peth Sector 2 High Street',
    zone: 'Budhwar Peth',
    location: { latitude: 17.696900, longitude: 75.937400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Budhwar Peth.',
  },
  {
    id: 'node-sol-9-3',
    name: 'Budhwar Peth Sector 3 High Street',
    zone: 'Budhwar Peth',
    location: { latitude: 17.699900, longitude: 75.940400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Budhwar Peth.',
  },
  {
    id: 'node-sol-10-1',
    name: 'Railway Lines Sector 1 High Street',
    zone: 'Railway Lines',
    location: { latitude: 17.705900, longitude: 75.944400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Railway Lines.',
  },
  {
    id: 'node-sol-10-2',
    name: 'Railway Lines Sector 2 High Street',
    zone: 'Railway Lines',
    location: { latitude: 17.708900, longitude: 75.947400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Railway Lines.',
  },
  {
    id: 'node-sol-10-3',
    name: 'Railway Lines Sector 3 High Street',
    zone: 'Railway Lines',
    location: { latitude: 17.711900, longitude: 75.950400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Railway Lines.',
  },
];

export const SOLAPUR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sol-1',
    fromNodeId: 'node-sol-1-1',
    toNodeId: 'node-sol-1-2',
    roadName: 'Saat Rasta Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-2',
    fromNodeId: 'node-sol-1-2',
    toNodeId: 'node-sol-1-3',
    roadName: 'Saat Rasta Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-3',
    fromNodeId: 'node-sol-2-1',
    toNodeId: 'node-sol-2-2',
    roadName: 'Hotgi Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-4',
    fromNodeId: 'node-sol-2-2',
    toNodeId: 'node-sol-2-3',
    roadName: 'Hotgi Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-5',
    fromNodeId: 'node-sol-3-1',
    toNodeId: 'node-sol-3-2',
    roadName: 'Jule Solapur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-6',
    fromNodeId: 'node-sol-3-2',
    toNodeId: 'node-sol-3-3',
    roadName: 'Jule Solapur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-7',
    fromNodeId: 'node-sol-4-1',
    toNodeId: 'node-sol-4-2',
    roadName: 'Lashkar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-8',
    fromNodeId: 'node-sol-4-2',
    toNodeId: 'node-sol-4-3',
    roadName: 'Lashkar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-9',
    fromNodeId: 'node-sol-5-1',
    toNodeId: 'node-sol-5-2',
    roadName: 'Old Pune Naka Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-10',
    fromNodeId: 'node-sol-5-2',
    toNodeId: 'node-sol-5-3',
    roadName: 'Old Pune Naka Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-11',
    fromNodeId: 'node-sol-6-1',
    toNodeId: 'node-sol-6-2',
    roadName: 'Navi Peth Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-12',
    fromNodeId: 'node-sol-6-2',
    toNodeId: 'node-sol-6-3',
    roadName: 'Navi Peth Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-13',
    fromNodeId: 'node-sol-7-1',
    toNodeId: 'node-sol-7-2',
    roadName: 'MIDC Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-14',
    fromNodeId: 'node-sol-7-2',
    toNodeId: 'node-sol-7-3',
    roadName: 'MIDC Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-15',
    fromNodeId: 'node-sol-8-1',
    toNodeId: 'node-sol-8-2',
    roadName: 'Bhavani Peth Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-16',
    fromNodeId: 'node-sol-8-2',
    toNodeId: 'node-sol-8-3',
    roadName: 'Bhavani Peth Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-17',
    fromNodeId: 'node-sol-9-1',
    toNodeId: 'node-sol-9-2',
    roadName: 'Budhwar Peth Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-18',
    fromNodeId: 'node-sol-9-2',
    toNodeId: 'node-sol-9-3',
    roadName: 'Budhwar Peth Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-19',
    fromNodeId: 'node-sol-10-1',
    toNodeId: 'node-sol-10-2',
    roadName: 'Railway Lines Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sol-20',
    fromNodeId: 'node-sol-10-2',
    toNodeId: 'node-sol-10-3',
    roadName: 'Railway Lines Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
