/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Stockholm Archipelago Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const STOCKHOLM_BASE_COORDINATE: GeoCoordinate = {
  latitude: 59.3293,
  longitude: 18.0686,
};

export const STOCKHOLM_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sto-1-1',
    name: 'Gamla Stan Sector 1 High Street',
    zone: 'Gamla Stan',
    location: { latitude: 59.267300, longitude: 18.016600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gamla Stan.',
  },
  {
    id: 'node-sto-1-2',
    name: 'Gamla Stan Sector 2 High Street',
    zone: 'Gamla Stan',
    location: { latitude: 59.270300, longitude: 18.019600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gamla Stan.',
  },
  {
    id: 'node-sto-1-3',
    name: 'Gamla Stan Sector 3 High Street',
    zone: 'Gamla Stan',
    location: { latitude: 59.273300, longitude: 18.022600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gamla Stan.',
  },
  {
    id: 'node-sto-2-1',
    name: 'Södermalm Sector 1 High Street',
    zone: 'Södermalm',
    location: { latitude: 59.279300, longitude: 18.026600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Södermalm.',
  },
  {
    id: 'node-sto-2-2',
    name: 'Södermalm Sector 2 High Street',
    zone: 'Södermalm',
    location: { latitude: 59.282300, longitude: 18.029600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Södermalm.',
  },
  {
    id: 'node-sto-2-3',
    name: 'Södermalm Sector 3 High Street',
    zone: 'Södermalm',
    location: { latitude: 59.285300, longitude: 18.032600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Södermalm.',
  },
  {
    id: 'node-sto-3-1',
    name: 'Östermalm Sector 1 High Street',
    zone: 'Östermalm',
    location: { latitude: 59.291300, longitude: 18.036600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Östermalm.',
  },
  {
    id: 'node-sto-3-2',
    name: 'Östermalm Sector 2 High Street',
    zone: 'Östermalm',
    location: { latitude: 59.294300, longitude: 18.039600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Östermalm.',
  },
  {
    id: 'node-sto-3-3',
    name: 'Östermalm Sector 3 High Street',
    zone: 'Östermalm',
    location: { latitude: 59.297300, longitude: 18.042600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Östermalm.',
  },
  {
    id: 'node-sto-4-1',
    name: 'Norrmalm Sector 1 High Street',
    zone: 'Norrmalm',
    location: { latitude: 59.303300, longitude: 18.046600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Norrmalm.',
  },
  {
    id: 'node-sto-4-2',
    name: 'Norrmalm Sector 2 High Street',
    zone: 'Norrmalm',
    location: { latitude: 59.306300, longitude: 18.049600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Norrmalm.',
  },
  {
    id: 'node-sto-4-3',
    name: 'Norrmalm Sector 3 High Street',
    zone: 'Norrmalm',
    location: { latitude: 59.309300, longitude: 18.052600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Norrmalm.',
  },
  {
    id: 'node-sto-5-1',
    name: 'Vasastan Sector 1 High Street',
    zone: 'Vasastan',
    location: { latitude: 59.315300, longitude: 18.056600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vasastan.',
  },
  {
    id: 'node-sto-5-2',
    name: 'Vasastan Sector 2 High Street',
    zone: 'Vasastan',
    location: { latitude: 59.318300, longitude: 18.059600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vasastan.',
  },
  {
    id: 'node-sto-5-3',
    name: 'Vasastan Sector 3 High Street',
    zone: 'Vasastan',
    location: { latitude: 59.321300, longitude: 18.062600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vasastan.',
  },
  {
    id: 'node-sto-6-1',
    name: 'Kungsholmen Sector 1 High Street',
    zone: 'Kungsholmen',
    location: { latitude: 59.327300, longitude: 18.066600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kungsholmen.',
  },
  {
    id: 'node-sto-6-2',
    name: 'Kungsholmen Sector 2 High Street',
    zone: 'Kungsholmen',
    location: { latitude: 59.330300, longitude: 18.069600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kungsholmen.',
  },
  {
    id: 'node-sto-6-3',
    name: 'Kungsholmen Sector 3 High Street',
    zone: 'Kungsholmen',
    location: { latitude: 59.333300, longitude: 18.072600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kungsholmen.',
  },
  {
    id: 'node-sto-7-1',
    name: 'Djurgården Sector 1 High Street',
    zone: 'Djurgården',
    location: { latitude: 59.339300, longitude: 18.076600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Djurgården.',
  },
  {
    id: 'node-sto-7-2',
    name: 'Djurgården Sector 2 High Street',
    zone: 'Djurgården',
    location: { latitude: 59.342300, longitude: 18.079600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Djurgården.',
  },
  {
    id: 'node-sto-7-3',
    name: 'Djurgården Sector 3 High Street',
    zone: 'Djurgården',
    location: { latitude: 59.345300, longitude: 18.082600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Djurgården.',
  },
  {
    id: 'node-sto-8-1',
    name: 'Hammarby Sjöstad Sector 1 High Street',
    zone: 'Hammarby Sjöstad',
    location: { latitude: 59.351300, longitude: 18.086600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hammarby Sjöstad.',
  },
  {
    id: 'node-sto-8-2',
    name: 'Hammarby Sjöstad Sector 2 High Street',
    zone: 'Hammarby Sjöstad',
    location: { latitude: 59.354300, longitude: 18.089600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hammarby Sjöstad.',
  },
  {
    id: 'node-sto-8-3',
    name: 'Hammarby Sjöstad Sector 3 High Street',
    zone: 'Hammarby Sjöstad',
    location: { latitude: 59.357300, longitude: 18.092600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hammarby Sjöstad.',
  },
  {
    id: 'node-sto-9-1',
    name: 'Solna Sector 1 High Street',
    zone: 'Solna',
    location: { latitude: 59.363300, longitude: 18.096600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Solna.',
  },
  {
    id: 'node-sto-9-2',
    name: 'Solna Sector 2 High Street',
    zone: 'Solna',
    location: { latitude: 59.366300, longitude: 18.099600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Solna.',
  },
  {
    id: 'node-sto-9-3',
    name: 'Solna Sector 3 High Street',
    zone: 'Solna',
    location: { latitude: 59.369300, longitude: 18.102600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Solna.',
  },
  {
    id: 'node-sto-10-1',
    name: 'Sundbyberg Sector 1 High Street',
    zone: 'Sundbyberg',
    location: { latitude: 59.375300, longitude: 18.106600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sundbyberg.',
  },
  {
    id: 'node-sto-10-2',
    name: 'Sundbyberg Sector 2 High Street',
    zone: 'Sundbyberg',
    location: { latitude: 59.378300, longitude: 18.109600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sundbyberg.',
  },
  {
    id: 'node-sto-10-3',
    name: 'Sundbyberg Sector 3 High Street',
    zone: 'Sundbyberg',
    location: { latitude: 59.381300, longitude: 18.112600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sundbyberg.',
  },
];

export const STOCKHOLM_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sto-1',
    fromNodeId: 'node-sto-1-1',
    toNodeId: 'node-sto-1-2',
    roadName: 'Gamla Stan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-2',
    fromNodeId: 'node-sto-1-2',
    toNodeId: 'node-sto-1-3',
    roadName: 'Gamla Stan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-3',
    fromNodeId: 'node-sto-2-1',
    toNodeId: 'node-sto-2-2',
    roadName: 'Södermalm Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-4',
    fromNodeId: 'node-sto-2-2',
    toNodeId: 'node-sto-2-3',
    roadName: 'Södermalm Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-5',
    fromNodeId: 'node-sto-3-1',
    toNodeId: 'node-sto-3-2',
    roadName: 'Östermalm Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-6',
    fromNodeId: 'node-sto-3-2',
    toNodeId: 'node-sto-3-3',
    roadName: 'Östermalm Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-7',
    fromNodeId: 'node-sto-4-1',
    toNodeId: 'node-sto-4-2',
    roadName: 'Norrmalm Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-8',
    fromNodeId: 'node-sto-4-2',
    toNodeId: 'node-sto-4-3',
    roadName: 'Norrmalm Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-9',
    fromNodeId: 'node-sto-5-1',
    toNodeId: 'node-sto-5-2',
    roadName: 'Vasastan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-10',
    fromNodeId: 'node-sto-5-2',
    toNodeId: 'node-sto-5-3',
    roadName: 'Vasastan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-11',
    fromNodeId: 'node-sto-6-1',
    toNodeId: 'node-sto-6-2',
    roadName: 'Kungsholmen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-12',
    fromNodeId: 'node-sto-6-2',
    toNodeId: 'node-sto-6-3',
    roadName: 'Kungsholmen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-13',
    fromNodeId: 'node-sto-7-1',
    toNodeId: 'node-sto-7-2',
    roadName: 'Djurgården Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-14',
    fromNodeId: 'node-sto-7-2',
    toNodeId: 'node-sto-7-3',
    roadName: 'Djurgården Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-15',
    fromNodeId: 'node-sto-8-1',
    toNodeId: 'node-sto-8-2',
    roadName: 'Hammarby Sjöstad Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-16',
    fromNodeId: 'node-sto-8-2',
    toNodeId: 'node-sto-8-3',
    roadName: 'Hammarby Sjöstad Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-17',
    fromNodeId: 'node-sto-9-1',
    toNodeId: 'node-sto-9-2',
    roadName: 'Solna Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-18',
    fromNodeId: 'node-sto-9-2',
    toNodeId: 'node-sto-9-3',
    roadName: 'Solna Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-19',
    fromNodeId: 'node-sto-10-1',
    toNodeId: 'node-sto-10-2',
    roadName: 'Sundbyberg Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sto-20',
    fromNodeId: 'node-sto-10-2',
    toNodeId: 'node-sto-10-3',
    roadName: 'Sundbyberg Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
