/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Surat Diamond City Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SURAT_BASE_COORDINATE: GeoCoordinate = {
  latitude: 21.1702,
  longitude: 72.8311,
};

export const SURAT_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-sur-1-1',
    name: 'Vesu Sector 1 High Street',
    zone: 'Vesu',
    location: { latitude: 21.108200, longitude: 72.779100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vesu.',
  },
  {
    id: 'node-sur-1-2',
    name: 'Vesu Sector 2 High Street',
    zone: 'Vesu',
    location: { latitude: 21.111200, longitude: 72.782100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vesu.',
  },
  {
    id: 'node-sur-1-3',
    name: 'Vesu Sector 3 High Street',
    zone: 'Vesu',
    location: { latitude: 21.114200, longitude: 72.785100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vesu.',
  },
  {
    id: 'node-sur-2-1',
    name: 'Piplod Sector 1 High Street',
    zone: 'Piplod',
    location: { latitude: 21.120200, longitude: 72.789100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Piplod.',
  },
  {
    id: 'node-sur-2-2',
    name: 'Piplod Sector 2 High Street',
    zone: 'Piplod',
    location: { latitude: 21.123200, longitude: 72.792100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Piplod.',
  },
  {
    id: 'node-sur-2-3',
    name: 'Piplod Sector 3 High Street',
    zone: 'Piplod',
    location: { latitude: 21.126200, longitude: 72.795100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Piplod.',
  },
  {
    id: 'node-sur-3-1',
    name: 'Adajan Sector 1 High Street',
    zone: 'Adajan',
    location: { latitude: 21.132200, longitude: 72.799100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Adajan.',
  },
  {
    id: 'node-sur-3-2',
    name: 'Adajan Sector 2 High Street',
    zone: 'Adajan',
    location: { latitude: 21.135200, longitude: 72.802100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Adajan.',
  },
  {
    id: 'node-sur-3-3',
    name: 'Adajan Sector 3 High Street',
    zone: 'Adajan',
    location: { latitude: 21.138200, longitude: 72.805100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Adajan.',
  },
  {
    id: 'node-sur-4-1',
    name: 'Ghod Dod Road Sector 1 High Street',
    zone: 'Ghod Dod Road',
    location: { latitude: 21.144200, longitude: 72.809100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ghod Dod Road.',
  },
  {
    id: 'node-sur-4-2',
    name: 'Ghod Dod Road Sector 2 High Street',
    zone: 'Ghod Dod Road',
    location: { latitude: 21.147200, longitude: 72.812100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ghod Dod Road.',
  },
  {
    id: 'node-sur-4-3',
    name: 'Ghod Dod Road Sector 3 High Street',
    zone: 'Ghod Dod Road',
    location: { latitude: 21.150200, longitude: 72.815100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ghod Dod Road.',
  },
  {
    id: 'node-sur-5-1',
    name: 'City Light Sector 1 High Street',
    zone: 'City Light',
    location: { latitude: 21.156200, longitude: 72.819100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in City Light.',
  },
  {
    id: 'node-sur-5-2',
    name: 'City Light Sector 2 High Street',
    zone: 'City Light',
    location: { latitude: 21.159200, longitude: 72.822100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in City Light.',
  },
  {
    id: 'node-sur-5-3',
    name: 'City Light Sector 3 High Street',
    zone: 'City Light',
    location: { latitude: 21.162200, longitude: 72.825100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in City Light.',
  },
  {
    id: 'node-sur-6-1',
    name: 'Athwa Sector 1 High Street',
    zone: 'Athwa',
    location: { latitude: 21.168200, longitude: 72.829100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Athwa.',
  },
  {
    id: 'node-sur-6-2',
    name: 'Athwa Sector 2 High Street',
    zone: 'Athwa',
    location: { latitude: 21.171200, longitude: 72.832100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Athwa.',
  },
  {
    id: 'node-sur-6-3',
    name: 'Athwa Sector 3 High Street',
    zone: 'Athwa',
    location: { latitude: 21.174200, longitude: 72.835100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Athwa.',
  },
  {
    id: 'node-sur-7-1',
    name: 'Varachha Sector 1 High Street',
    zone: 'Varachha',
    location: { latitude: 21.180200, longitude: 72.839100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Varachha.',
  },
  {
    id: 'node-sur-7-2',
    name: 'Varachha Sector 2 High Street',
    zone: 'Varachha',
    location: { latitude: 21.183200, longitude: 72.842100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Varachha.',
  },
  {
    id: 'node-sur-7-3',
    name: 'Varachha Sector 3 High Street',
    zone: 'Varachha',
    location: { latitude: 21.186200, longitude: 72.845100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Varachha.',
  },
  {
    id: 'node-sur-8-1',
    name: 'Katargam Sector 1 High Street',
    zone: 'Katargam',
    location: { latitude: 21.192200, longitude: 72.849100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Katargam.',
  },
  {
    id: 'node-sur-8-2',
    name: 'Katargam Sector 2 High Street',
    zone: 'Katargam',
    location: { latitude: 21.195200, longitude: 72.852100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Katargam.',
  },
  {
    id: 'node-sur-8-3',
    name: 'Katargam Sector 3 High Street',
    zone: 'Katargam',
    location: { latitude: 21.198200, longitude: 72.855100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Katargam.',
  },
  {
    id: 'node-sur-9-1',
    name: 'Rander Road Sector 1 High Street',
    zone: 'Rander Road',
    location: { latitude: 21.204200, longitude: 72.859100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rander Road.',
  },
  {
    id: 'node-sur-9-2',
    name: 'Rander Road Sector 2 High Street',
    zone: 'Rander Road',
    location: { latitude: 21.207200, longitude: 72.862100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rander Road.',
  },
  {
    id: 'node-sur-9-3',
    name: 'Rander Road Sector 3 High Street',
    zone: 'Rander Road',
    location: { latitude: 21.210200, longitude: 72.865100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rander Road.',
  },
  {
    id: 'node-sur-10-1',
    name: 'Dumas Road Sector 1 High Street',
    zone: 'Dumas Road',
    location: { latitude: 21.216200, longitude: 72.869100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dumas Road.',
  },
  {
    id: 'node-sur-10-2',
    name: 'Dumas Road Sector 2 High Street',
    zone: 'Dumas Road',
    location: { latitude: 21.219200, longitude: 72.872100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dumas Road.',
  },
  {
    id: 'node-sur-10-3',
    name: 'Dumas Road Sector 3 High Street',
    zone: 'Dumas Road',
    location: { latitude: 21.222200, longitude: 72.875100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dumas Road.',
  },
];

export const SURAT_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-sur-1',
    fromNodeId: 'node-sur-1-1',
    toNodeId: 'node-sur-1-2',
    roadName: 'Vesu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-2',
    fromNodeId: 'node-sur-1-2',
    toNodeId: 'node-sur-1-3',
    roadName: 'Vesu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-3',
    fromNodeId: 'node-sur-2-1',
    toNodeId: 'node-sur-2-2',
    roadName: 'Piplod Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-4',
    fromNodeId: 'node-sur-2-2',
    toNodeId: 'node-sur-2-3',
    roadName: 'Piplod Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-5',
    fromNodeId: 'node-sur-3-1',
    toNodeId: 'node-sur-3-2',
    roadName: 'Adajan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-6',
    fromNodeId: 'node-sur-3-2',
    toNodeId: 'node-sur-3-3',
    roadName: 'Adajan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-7',
    fromNodeId: 'node-sur-4-1',
    toNodeId: 'node-sur-4-2',
    roadName: 'Ghod Dod Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-8',
    fromNodeId: 'node-sur-4-2',
    toNodeId: 'node-sur-4-3',
    roadName: 'Ghod Dod Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-9',
    fromNodeId: 'node-sur-5-1',
    toNodeId: 'node-sur-5-2',
    roadName: 'City Light Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-10',
    fromNodeId: 'node-sur-5-2',
    toNodeId: 'node-sur-5-3',
    roadName: 'City Light Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-11',
    fromNodeId: 'node-sur-6-1',
    toNodeId: 'node-sur-6-2',
    roadName: 'Athwa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-12',
    fromNodeId: 'node-sur-6-2',
    toNodeId: 'node-sur-6-3',
    roadName: 'Athwa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-13',
    fromNodeId: 'node-sur-7-1',
    toNodeId: 'node-sur-7-2',
    roadName: 'Varachha Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-14',
    fromNodeId: 'node-sur-7-2',
    toNodeId: 'node-sur-7-3',
    roadName: 'Varachha Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-15',
    fromNodeId: 'node-sur-8-1',
    toNodeId: 'node-sur-8-2',
    roadName: 'Katargam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-16',
    fromNodeId: 'node-sur-8-2',
    toNodeId: 'node-sur-8-3',
    roadName: 'Katargam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-17',
    fromNodeId: 'node-sur-9-1',
    toNodeId: 'node-sur-9-2',
    roadName: 'Rander Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-18',
    fromNodeId: 'node-sur-9-2',
    toNodeId: 'node-sur-9-3',
    roadName: 'Rander Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-19',
    fromNodeId: 'node-sur-10-1',
    toNodeId: 'node-sur-10-2',
    roadName: 'Dumas Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-sur-20',
    fromNodeId: 'node-sur-10-2',
    toNodeId: 'node-sur-10-3',
    roadName: 'Dumas Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
