/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Sydney Harbour & CBD
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const SYDNEY_BASE_COORDINATE: GeoCoordinate = {
  latitude: -33.8688,
  longitude: 151.2093,
};

export const SYDNEY_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-syd-1-1',
    name: 'Sydney CBD Sector 1 High Street',
    zone: 'Sydney CBD',
    location: { latitude: -33.930800, longitude: 151.157300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sydney CBD.',
  },
  {
    id: 'node-syd-1-2',
    name: 'Sydney CBD Sector 2 High Street',
    zone: 'Sydney CBD',
    location: { latitude: -33.927800, longitude: 151.160300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sydney CBD.',
  },
  {
    id: 'node-syd-1-3',
    name: 'Sydney CBD Sector 3 High Street',
    zone: 'Sydney CBD',
    location: { latitude: -33.924800, longitude: 151.163300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sydney CBD.',
  },
  {
    id: 'node-syd-2-1',
    name: 'Surry Hills Sector 1 High Street',
    zone: 'Surry Hills',
    location: { latitude: -33.918800, longitude: 151.167300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Surry Hills.',
  },
  {
    id: 'node-syd-2-2',
    name: 'Surry Hills Sector 2 High Street',
    zone: 'Surry Hills',
    location: { latitude: -33.915800, longitude: 151.170300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Surry Hills.',
  },
  {
    id: 'node-syd-2-3',
    name: 'Surry Hills Sector 3 High Street',
    zone: 'Surry Hills',
    location: { latitude: -33.912800, longitude: 151.173300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Surry Hills.',
  },
  {
    id: 'node-syd-3-1',
    name: 'Bondi Beach Sector 1 High Street',
    zone: 'Bondi Beach',
    location: { latitude: -33.906800, longitude: 151.177300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bondi Beach.',
  },
  {
    id: 'node-syd-3-2',
    name: 'Bondi Beach Sector 2 High Street',
    zone: 'Bondi Beach',
    location: { latitude: -33.903800, longitude: 151.180300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bondi Beach.',
  },
  {
    id: 'node-syd-3-3',
    name: 'Bondi Beach Sector 3 High Street',
    zone: 'Bondi Beach',
    location: { latitude: -33.900800, longitude: 151.183300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bondi Beach.',
  },
  {
    id: 'node-syd-4-1',
    name: 'Paddington Sydney Sector 1 High Street',
    zone: 'Paddington Sydney',
    location: { latitude: -33.894800, longitude: 151.187300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Paddington Sydney.',
  },
  {
    id: 'node-syd-4-2',
    name: 'Paddington Sydney Sector 2 High Street',
    zone: 'Paddington Sydney',
    location: { latitude: -33.891800, longitude: 151.190300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Paddington Sydney.',
  },
  {
    id: 'node-syd-4-3',
    name: 'Paddington Sydney Sector 3 High Street',
    zone: 'Paddington Sydney',
    location: { latitude: -33.888800, longitude: 151.193300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Paddington Sydney.',
  },
  {
    id: 'node-syd-5-1',
    name: 'Newtown Sector 1 High Street',
    zone: 'Newtown',
    location: { latitude: -33.882800, longitude: 151.197300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Newtown.',
  },
  {
    id: 'node-syd-5-2',
    name: 'Newtown Sector 2 High Street',
    zone: 'Newtown',
    location: { latitude: -33.879800, longitude: 151.200300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Newtown.',
  },
  {
    id: 'node-syd-5-3',
    name: 'Newtown Sector 3 High Street',
    zone: 'Newtown',
    location: { latitude: -33.876800, longitude: 151.203300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Newtown.',
  },
  {
    id: 'node-syd-6-1',
    name: 'Darlinghurst Sector 1 High Street',
    zone: 'Darlinghurst',
    location: { latitude: -33.870800, longitude: 151.207300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Darlinghurst.',
  },
  {
    id: 'node-syd-6-2',
    name: 'Darlinghurst Sector 2 High Street',
    zone: 'Darlinghurst',
    location: { latitude: -33.867800, longitude: 151.210300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Darlinghurst.',
  },
  {
    id: 'node-syd-6-3',
    name: 'Darlinghurst Sector 3 High Street',
    zone: 'Darlinghurst',
    location: { latitude: -33.864800, longitude: 151.213300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Darlinghurst.',
  },
  {
    id: 'node-syd-7-1',
    name: 'North Sydney Sector 1 High Street',
    zone: 'North Sydney',
    location: { latitude: -33.858800, longitude: 151.217300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in North Sydney.',
  },
  {
    id: 'node-syd-7-2',
    name: 'North Sydney Sector 2 High Street',
    zone: 'North Sydney',
    location: { latitude: -33.855800, longitude: 151.220300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in North Sydney.',
  },
  {
    id: 'node-syd-7-3',
    name: 'North Sydney Sector 3 High Street',
    zone: 'North Sydney',
    location: { latitude: -33.852800, longitude: 151.223300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in North Sydney.',
  },
  {
    id: 'node-syd-8-1',
    name: 'Manly Sector 1 High Street',
    zone: 'Manly',
    location: { latitude: -33.846800, longitude: 151.227300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Manly.',
  },
  {
    id: 'node-syd-8-2',
    name: 'Manly Sector 2 High Street',
    zone: 'Manly',
    location: { latitude: -33.843800, longitude: 151.230300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Manly.',
  },
  {
    id: 'node-syd-8-3',
    name: 'Manly Sector 3 High Street',
    zone: 'Manly',
    location: { latitude: -33.840800, longitude: 151.233300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Manly.',
  },
  {
    id: 'node-syd-9-1',
    name: 'Parramatta Sector 1 High Street',
    zone: 'Parramatta',
    location: { latitude: -33.834800, longitude: 151.237300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Parramatta.',
  },
  {
    id: 'node-syd-9-2',
    name: 'Parramatta Sector 2 High Street',
    zone: 'Parramatta',
    location: { latitude: -33.831800, longitude: 151.240300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Parramatta.',
  },
  {
    id: 'node-syd-9-3',
    name: 'Parramatta Sector 3 High Street',
    zone: 'Parramatta',
    location: { latitude: -33.828800, longitude: 151.243300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Parramatta.',
  },
  {
    id: 'node-syd-10-1',
    name: 'Chatswood Sector 1 High Street',
    zone: 'Chatswood',
    location: { latitude: -33.822800, longitude: 151.247300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Chatswood.',
  },
  {
    id: 'node-syd-10-2',
    name: 'Chatswood Sector 2 High Street',
    zone: 'Chatswood',
    location: { latitude: -33.819800, longitude: 151.250300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Chatswood.',
  },
  {
    id: 'node-syd-10-3',
    name: 'Chatswood Sector 3 High Street',
    zone: 'Chatswood',
    location: { latitude: -33.816800, longitude: 151.253300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Chatswood.',
  },
];

export const SYDNEY_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-syd-1',
    fromNodeId: 'node-syd-1-1',
    toNodeId: 'node-syd-1-2',
    roadName: 'Sydney CBD Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-2',
    fromNodeId: 'node-syd-1-2',
    toNodeId: 'node-syd-1-3',
    roadName: 'Sydney CBD Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-3',
    fromNodeId: 'node-syd-2-1',
    toNodeId: 'node-syd-2-2',
    roadName: 'Surry Hills Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-4',
    fromNodeId: 'node-syd-2-2',
    toNodeId: 'node-syd-2-3',
    roadName: 'Surry Hills Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-5',
    fromNodeId: 'node-syd-3-1',
    toNodeId: 'node-syd-3-2',
    roadName: 'Bondi Beach Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-6',
    fromNodeId: 'node-syd-3-2',
    toNodeId: 'node-syd-3-3',
    roadName: 'Bondi Beach Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-7',
    fromNodeId: 'node-syd-4-1',
    toNodeId: 'node-syd-4-2',
    roadName: 'Paddington Sydney Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-8',
    fromNodeId: 'node-syd-4-2',
    toNodeId: 'node-syd-4-3',
    roadName: 'Paddington Sydney Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-9',
    fromNodeId: 'node-syd-5-1',
    toNodeId: 'node-syd-5-2',
    roadName: 'Newtown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-10',
    fromNodeId: 'node-syd-5-2',
    toNodeId: 'node-syd-5-3',
    roadName: 'Newtown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-11',
    fromNodeId: 'node-syd-6-1',
    toNodeId: 'node-syd-6-2',
    roadName: 'Darlinghurst Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-12',
    fromNodeId: 'node-syd-6-2',
    toNodeId: 'node-syd-6-3',
    roadName: 'Darlinghurst Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-13',
    fromNodeId: 'node-syd-7-1',
    toNodeId: 'node-syd-7-2',
    roadName: 'North Sydney Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-14',
    fromNodeId: 'node-syd-7-2',
    toNodeId: 'node-syd-7-3',
    roadName: 'North Sydney Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-15',
    fromNodeId: 'node-syd-8-1',
    toNodeId: 'node-syd-8-2',
    roadName: 'Manly Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-16',
    fromNodeId: 'node-syd-8-2',
    toNodeId: 'node-syd-8-3',
    roadName: 'Manly Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-17',
    fromNodeId: 'node-syd-9-1',
    toNodeId: 'node-syd-9-2',
    roadName: 'Parramatta Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-18',
    fromNodeId: 'node-syd-9-2',
    toNodeId: 'node-syd-9-3',
    roadName: 'Parramatta Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-19',
    fromNodeId: 'node-syd-10-1',
    toNodeId: 'node-syd-10-2',
    roadName: 'Chatswood Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-syd-20',
    fromNodeId: 'node-syd-10-2',
    toNodeId: 'node-syd-10-3',
    roadName: 'Chatswood Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
