/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Taipei Ximending Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const TAIPEI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 25.033,
  longitude: 121.5654,
};

export const TAIPEI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-tai-1-1',
    name: 'Ximending Sector 1 High Street',
    zone: 'Ximending',
    location: { latitude: 24.971000, longitude: 121.513400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ximending.',
  },
  {
    id: 'node-tai-1-2',
    name: 'Ximending Sector 2 High Street',
    zone: 'Ximending',
    location: { latitude: 24.974000, longitude: 121.516400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ximending.',
  },
  {
    id: 'node-tai-1-3',
    name: 'Ximending Sector 3 High Street',
    zone: 'Ximending',
    location: { latitude: 24.977000, longitude: 121.519400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ximending.',
  },
  {
    id: 'node-tai-2-1',
    name: 'Daan Sector 1 High Street',
    zone: 'Daan',
    location: { latitude: 24.983000, longitude: 121.523400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Daan.',
  },
  {
    id: 'node-tai-2-2',
    name: 'Daan Sector 2 High Street',
    zone: 'Daan',
    location: { latitude: 24.986000, longitude: 121.526400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Daan.',
  },
  {
    id: 'node-tai-2-3',
    name: 'Daan Sector 3 High Street',
    zone: 'Daan',
    location: { latitude: 24.989000, longitude: 121.529400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Daan.',
  },
  {
    id: 'node-tai-3-1',
    name: 'Xinyi Sector 1 High Street',
    zone: 'Xinyi',
    location: { latitude: 24.995000, longitude: 121.533400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Xinyi.',
  },
  {
    id: 'node-tai-3-2',
    name: 'Xinyi Sector 2 High Street',
    zone: 'Xinyi',
    location: { latitude: 24.998000, longitude: 121.536400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Xinyi.',
  },
  {
    id: 'node-tai-3-3',
    name: 'Xinyi Sector 3 High Street',
    zone: 'Xinyi',
    location: { latitude: 25.001000, longitude: 121.539400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Xinyi.',
  },
  {
    id: 'node-tai-4-1',
    name: 'Zhongshan Sector 1 High Street',
    zone: 'Zhongshan',
    location: { latitude: 25.007000, longitude: 121.543400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Zhongshan.',
  },
  {
    id: 'node-tai-4-2',
    name: 'Zhongshan Sector 2 High Street',
    zone: 'Zhongshan',
    location: { latitude: 25.010000, longitude: 121.546400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Zhongshan.',
  },
  {
    id: 'node-tai-4-3',
    name: 'Zhongshan Sector 3 High Street',
    zone: 'Zhongshan',
    location: { latitude: 25.013000, longitude: 121.549400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Zhongshan.',
  },
  {
    id: 'node-tai-5-1',
    name: 'Songshan Sector 1 High Street',
    zone: 'Songshan',
    location: { latitude: 25.019000, longitude: 121.553400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Songshan.',
  },
  {
    id: 'node-tai-5-2',
    name: 'Songshan Sector 2 High Street',
    zone: 'Songshan',
    location: { latitude: 25.022000, longitude: 121.556400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Songshan.',
  },
  {
    id: 'node-tai-5-3',
    name: 'Songshan Sector 3 High Street',
    zone: 'Songshan',
    location: { latitude: 25.025000, longitude: 121.559400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Songshan.',
  },
  {
    id: 'node-tai-6-1',
    name: 'Shilin Sector 1 High Street',
    zone: 'Shilin',
    location: { latitude: 25.031000, longitude: 121.563400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shilin.',
  },
  {
    id: 'node-tai-6-2',
    name: 'Shilin Sector 2 High Street',
    zone: 'Shilin',
    location: { latitude: 25.034000, longitude: 121.566400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shilin.',
  },
  {
    id: 'node-tai-6-3',
    name: 'Shilin Sector 3 High Street',
    zone: 'Shilin',
    location: { latitude: 25.037000, longitude: 121.569400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shilin.',
  },
  {
    id: 'node-tai-7-1',
    name: 'Beitou Sector 1 High Street',
    zone: 'Beitou',
    location: { latitude: 25.043000, longitude: 121.573400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Beitou.',
  },
  {
    id: 'node-tai-7-2',
    name: 'Beitou Sector 2 High Street',
    zone: 'Beitou',
    location: { latitude: 25.046000, longitude: 121.576400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Beitou.',
  },
  {
    id: 'node-tai-7-3',
    name: 'Beitou Sector 3 High Street',
    zone: 'Beitou',
    location: { latitude: 25.049000, longitude: 121.579400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Beitou.',
  },
  {
    id: 'node-tai-8-1',
    name: 'Wanhua Sector 1 High Street',
    zone: 'Wanhua',
    location: { latitude: 25.055000, longitude: 121.583400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wanhua.',
  },
  {
    id: 'node-tai-8-2',
    name: 'Wanhua Sector 2 High Street',
    zone: 'Wanhua',
    location: { latitude: 25.058000, longitude: 121.586400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wanhua.',
  },
  {
    id: 'node-tai-8-3',
    name: 'Wanhua Sector 3 High Street',
    zone: 'Wanhua',
    location: { latitude: 25.061000, longitude: 121.589400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wanhua.',
  },
  {
    id: 'node-tai-9-1',
    name: 'Neihu Sector 1 High Street',
    zone: 'Neihu',
    location: { latitude: 25.067000, longitude: 121.593400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Neihu.',
  },
  {
    id: 'node-tai-9-2',
    name: 'Neihu Sector 2 High Street',
    zone: 'Neihu',
    location: { latitude: 25.070000, longitude: 121.596400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Neihu.',
  },
  {
    id: 'node-tai-9-3',
    name: 'Neihu Sector 3 High Street',
    zone: 'Neihu',
    location: { latitude: 25.073000, longitude: 121.599400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Neihu.',
  },
  {
    id: 'node-tai-10-1',
    name: 'Nangang Sector 1 High Street',
    zone: 'Nangang',
    location: { latitude: 25.079000, longitude: 121.603400 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nangang.',
  },
  {
    id: 'node-tai-10-2',
    name: 'Nangang Sector 2 High Street',
    zone: 'Nangang',
    location: { latitude: 25.082000, longitude: 121.606400 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nangang.',
  },
  {
    id: 'node-tai-10-3',
    name: 'Nangang Sector 3 High Street',
    zone: 'Nangang',
    location: { latitude: 25.085000, longitude: 121.609400 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nangang.',
  },
];

export const TAIPEI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-tai-1',
    fromNodeId: 'node-tai-1-1',
    toNodeId: 'node-tai-1-2',
    roadName: 'Ximending Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-2',
    fromNodeId: 'node-tai-1-2',
    toNodeId: 'node-tai-1-3',
    roadName: 'Ximending Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-3',
    fromNodeId: 'node-tai-2-1',
    toNodeId: 'node-tai-2-2',
    roadName: 'Daan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-4',
    fromNodeId: 'node-tai-2-2',
    toNodeId: 'node-tai-2-3',
    roadName: 'Daan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-5',
    fromNodeId: 'node-tai-3-1',
    toNodeId: 'node-tai-3-2',
    roadName: 'Xinyi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-6',
    fromNodeId: 'node-tai-3-2',
    toNodeId: 'node-tai-3-3',
    roadName: 'Xinyi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-7',
    fromNodeId: 'node-tai-4-1',
    toNodeId: 'node-tai-4-2',
    roadName: 'Zhongshan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-8',
    fromNodeId: 'node-tai-4-2',
    toNodeId: 'node-tai-4-3',
    roadName: 'Zhongshan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-9',
    fromNodeId: 'node-tai-5-1',
    toNodeId: 'node-tai-5-2',
    roadName: 'Songshan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-10',
    fromNodeId: 'node-tai-5-2',
    toNodeId: 'node-tai-5-3',
    roadName: 'Songshan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-11',
    fromNodeId: 'node-tai-6-1',
    toNodeId: 'node-tai-6-2',
    roadName: 'Shilin Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-12',
    fromNodeId: 'node-tai-6-2',
    toNodeId: 'node-tai-6-3',
    roadName: 'Shilin Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-13',
    fromNodeId: 'node-tai-7-1',
    toNodeId: 'node-tai-7-2',
    roadName: 'Beitou Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-14',
    fromNodeId: 'node-tai-7-2',
    toNodeId: 'node-tai-7-3',
    roadName: 'Beitou Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-15',
    fromNodeId: 'node-tai-8-1',
    toNodeId: 'node-tai-8-2',
    roadName: 'Wanhua Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-16',
    fromNodeId: 'node-tai-8-2',
    toNodeId: 'node-tai-8-3',
    roadName: 'Wanhua Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-17',
    fromNodeId: 'node-tai-9-1',
    toNodeId: 'node-tai-9-2',
    roadName: 'Neihu Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-18',
    fromNodeId: 'node-tai-9-2',
    toNodeId: 'node-tai-9-3',
    roadName: 'Neihu Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-19',
    fromNodeId: 'node-tai-10-1',
    toNodeId: 'node-tai-10-2',
    roadName: 'Nangang Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tai-20',
    fromNodeId: 'node-tai-10-2',
    toNodeId: 'node-tai-10-3',
    roadName: 'Nangang Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
