/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Tampa Bay Sunshine Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const TAMPA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 27.9506,
  longitude: -82.4572,
};

export const TAMPA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-tam-1-1',
    name: 'Downtown Tampa Sector 1 High Street',
    zone: 'Downtown Tampa',
    location: { latitude: 27.888600, longitude: -82.509200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Tampa.',
  },
  {
    id: 'node-tam-1-2',
    name: 'Downtown Tampa Sector 2 High Street',
    zone: 'Downtown Tampa',
    location: { latitude: 27.891600, longitude: -82.506200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Tampa.',
  },
  {
    id: 'node-tam-1-3',
    name: 'Downtown Tampa Sector 3 High Street',
    zone: 'Downtown Tampa',
    location: { latitude: 27.894600, longitude: -82.503200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Tampa.',
  },
  {
    id: 'node-tam-2-1',
    name: 'Ybor City Sector 1 High Street',
    zone: 'Ybor City',
    location: { latitude: 27.900600, longitude: -82.499200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ybor City.',
  },
  {
    id: 'node-tam-2-2',
    name: 'Ybor City Sector 2 High Street',
    zone: 'Ybor City',
    location: { latitude: 27.903600, longitude: -82.496200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ybor City.',
  },
  {
    id: 'node-tam-2-3',
    name: 'Ybor City Sector 3 High Street',
    zone: 'Ybor City',
    location: { latitude: 27.906600, longitude: -82.493200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ybor City.',
  },
  {
    id: 'node-tam-3-1',
    name: 'Hyde Park Tampa Sector 1 High Street',
    zone: 'Hyde Park Tampa',
    location: { latitude: 27.912600, longitude: -82.489200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park Tampa.',
  },
  {
    id: 'node-tam-3-2',
    name: 'Hyde Park Tampa Sector 2 High Street',
    zone: 'Hyde Park Tampa',
    location: { latitude: 27.915600, longitude: -82.486200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park Tampa.',
  },
  {
    id: 'node-tam-3-3',
    name: 'Hyde Park Tampa Sector 3 High Street',
    zone: 'Hyde Park Tampa',
    location: { latitude: 27.918600, longitude: -82.483200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hyde Park Tampa.',
  },
  {
    id: 'node-tam-4-1',
    name: 'Channelside Sector 1 High Street',
    zone: 'Channelside',
    location: { latitude: 27.924600, longitude: -82.479200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Channelside.',
  },
  {
    id: 'node-tam-4-2',
    name: 'Channelside Sector 2 High Street',
    zone: 'Channelside',
    location: { latitude: 27.927600, longitude: -82.476200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Channelside.',
  },
  {
    id: 'node-tam-4-3',
    name: 'Channelside Sector 3 High Street',
    zone: 'Channelside',
    location: { latitude: 27.930600, longitude: -82.473200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Channelside.',
  },
  {
    id: 'node-tam-5-1',
    name: 'South Tampa Sector 1 High Street',
    zone: 'South Tampa',
    location: { latitude: 27.936600, longitude: -82.469200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in South Tampa.',
  },
  {
    id: 'node-tam-5-2',
    name: 'South Tampa Sector 2 High Street',
    zone: 'South Tampa',
    location: { latitude: 27.939600, longitude: -82.466200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in South Tampa.',
  },
  {
    id: 'node-tam-5-3',
    name: 'South Tampa Sector 3 High Street',
    zone: 'South Tampa',
    location: { latitude: 27.942600, longitude: -82.463200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in South Tampa.',
  },
  {
    id: 'node-tam-6-1',
    name: 'Tampa Heights Sector 1 High Street',
    zone: 'Tampa Heights',
    location: { latitude: 27.948600, longitude: -82.459200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Tampa Heights.',
  },
  {
    id: 'node-tam-6-2',
    name: 'Tampa Heights Sector 2 High Street',
    zone: 'Tampa Heights',
    location: { latitude: 27.951600, longitude: -82.456200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Tampa Heights.',
  },
  {
    id: 'node-tam-6-3',
    name: 'Tampa Heights Sector 3 High Street',
    zone: 'Tampa Heights',
    location: { latitude: 27.954600, longitude: -82.453200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Tampa Heights.',
  },
  {
    id: 'node-tam-7-1',
    name: 'Westshore Sector 1 High Street',
    zone: 'Westshore',
    location: { latitude: 27.960600, longitude: -82.449200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Westshore.',
  },
  {
    id: 'node-tam-7-2',
    name: 'Westshore Sector 2 High Street',
    zone: 'Westshore',
    location: { latitude: 27.963600, longitude: -82.446200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Westshore.',
  },
  {
    id: 'node-tam-7-3',
    name: 'Westshore Sector 3 High Street',
    zone: 'Westshore',
    location: { latitude: 27.966600, longitude: -82.443200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Westshore.',
  },
  {
    id: 'node-tam-8-1',
    name: 'Davis Islands Sector 1 High Street',
    zone: 'Davis Islands',
    location: { latitude: 27.972600, longitude: -82.439200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Davis Islands.',
  },
  {
    id: 'node-tam-8-2',
    name: 'Davis Islands Sector 2 High Street',
    zone: 'Davis Islands',
    location: { latitude: 27.975600, longitude: -82.436200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Davis Islands.',
  },
  {
    id: 'node-tam-8-3',
    name: 'Davis Islands Sector 3 High Street',
    zone: 'Davis Islands',
    location: { latitude: 27.978600, longitude: -82.433200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Davis Islands.',
  },
  {
    id: 'node-tam-9-1',
    name: 'Carrollwood Sector 1 High Street',
    zone: 'Carrollwood',
    location: { latitude: 27.984600, longitude: -82.429200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Carrollwood.',
  },
  {
    id: 'node-tam-9-2',
    name: 'Carrollwood Sector 2 High Street',
    zone: 'Carrollwood',
    location: { latitude: 27.987600, longitude: -82.426200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Carrollwood.',
  },
  {
    id: 'node-tam-9-3',
    name: 'Carrollwood Sector 3 High Street',
    zone: 'Carrollwood',
    location: { latitude: 27.990600, longitude: -82.423200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Carrollwood.',
  },
  {
    id: 'node-tam-10-1',
    name: 'Seminole Heights Sector 1 High Street',
    zone: 'Seminole Heights',
    location: { latitude: 27.996600, longitude: -82.419200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Seminole Heights.',
  },
  {
    id: 'node-tam-10-2',
    name: 'Seminole Heights Sector 2 High Street',
    zone: 'Seminole Heights',
    location: { latitude: 27.999600, longitude: -82.416200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Seminole Heights.',
  },
  {
    id: 'node-tam-10-3',
    name: 'Seminole Heights Sector 3 High Street',
    zone: 'Seminole Heights',
    location: { latitude: 28.002600, longitude: -82.413200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Seminole Heights.',
  },
];

export const TAMPA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-tam-1',
    fromNodeId: 'node-tam-1-1',
    toNodeId: 'node-tam-1-2',
    roadName: 'Downtown Tampa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-2',
    fromNodeId: 'node-tam-1-2',
    toNodeId: 'node-tam-1-3',
    roadName: 'Downtown Tampa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-3',
    fromNodeId: 'node-tam-2-1',
    toNodeId: 'node-tam-2-2',
    roadName: 'Ybor City Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-4',
    fromNodeId: 'node-tam-2-2',
    toNodeId: 'node-tam-2-3',
    roadName: 'Ybor City Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-5',
    fromNodeId: 'node-tam-3-1',
    toNodeId: 'node-tam-3-2',
    roadName: 'Hyde Park Tampa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-6',
    fromNodeId: 'node-tam-3-2',
    toNodeId: 'node-tam-3-3',
    roadName: 'Hyde Park Tampa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-7',
    fromNodeId: 'node-tam-4-1',
    toNodeId: 'node-tam-4-2',
    roadName: 'Channelside Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-8',
    fromNodeId: 'node-tam-4-2',
    toNodeId: 'node-tam-4-3',
    roadName: 'Channelside Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-9',
    fromNodeId: 'node-tam-5-1',
    toNodeId: 'node-tam-5-2',
    roadName: 'South Tampa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-10',
    fromNodeId: 'node-tam-5-2',
    toNodeId: 'node-tam-5-3',
    roadName: 'South Tampa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-11',
    fromNodeId: 'node-tam-6-1',
    toNodeId: 'node-tam-6-2',
    roadName: 'Tampa Heights Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-12',
    fromNodeId: 'node-tam-6-2',
    toNodeId: 'node-tam-6-3',
    roadName: 'Tampa Heights Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-13',
    fromNodeId: 'node-tam-7-1',
    toNodeId: 'node-tam-7-2',
    roadName: 'Westshore Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-14',
    fromNodeId: 'node-tam-7-2',
    toNodeId: 'node-tam-7-3',
    roadName: 'Westshore Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-15',
    fromNodeId: 'node-tam-8-1',
    toNodeId: 'node-tam-8-2',
    roadName: 'Davis Islands Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-16',
    fromNodeId: 'node-tam-8-2',
    toNodeId: 'node-tam-8-3',
    roadName: 'Davis Islands Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-17',
    fromNodeId: 'node-tam-9-1',
    toNodeId: 'node-tam-9-2',
    roadName: 'Carrollwood Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-18',
    fromNodeId: 'node-tam-9-2',
    toNodeId: 'node-tam-9-3',
    roadName: 'Carrollwood Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-19',
    fromNodeId: 'node-tam-10-1',
    toNodeId: 'node-tam-10-2',
    roadName: 'Seminole Heights Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tam-20',
    fromNodeId: 'node-tam-10-2',
    toNodeId: 'node-tam-10-3',
    roadName: 'Seminole Heights Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
