/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Toronto GTA Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const TORONTO_BASE_COORDINATE: GeoCoordinate = {
  latitude: 43.6532,
  longitude: -79.3832,
};

export const TORONTO_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-tor-1-1',
    name: 'Downtown Toronto Sector 1 High Street',
    zone: 'Downtown Toronto',
    location: { latitude: 43.591200, longitude: -79.435200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Toronto.',
  },
  {
    id: 'node-tor-1-2',
    name: 'Downtown Toronto Sector 2 High Street',
    zone: 'Downtown Toronto',
    location: { latitude: 43.594200, longitude: -79.432200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Toronto.',
  },
  {
    id: 'node-tor-1-3',
    name: 'Downtown Toronto Sector 3 High Street',
    zone: 'Downtown Toronto',
    location: { latitude: 43.597200, longitude: -79.429200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Toronto.',
  },
  {
    id: 'node-tor-2-1',
    name: 'Yorkville Sector 1 High Street',
    zone: 'Yorkville',
    location: { latitude: 43.603200, longitude: -79.425200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Yorkville.',
  },
  {
    id: 'node-tor-2-2',
    name: 'Yorkville Sector 2 High Street',
    zone: 'Yorkville',
    location: { latitude: 43.606200, longitude: -79.422200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Yorkville.',
  },
  {
    id: 'node-tor-2-3',
    name: 'Yorkville Sector 3 High Street',
    zone: 'Yorkville',
    location: { latitude: 43.609200, longitude: -79.419200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Yorkville.',
  },
  {
    id: 'node-tor-3-1',
    name: 'Queen West Sector 1 High Street',
    zone: 'Queen West',
    location: { latitude: 43.615200, longitude: -79.415200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Queen West.',
  },
  {
    id: 'node-tor-3-2',
    name: 'Queen West Sector 2 High Street',
    zone: 'Queen West',
    location: { latitude: 43.618200, longitude: -79.412200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Queen West.',
  },
  {
    id: 'node-tor-3-3',
    name: 'Queen West Sector 3 High Street',
    zone: 'Queen West',
    location: { latitude: 43.621200, longitude: -79.409200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Queen West.',
  },
  {
    id: 'node-tor-4-1',
    name: 'Kensington Market Sector 1 High Street',
    zone: 'Kensington Market',
    location: { latitude: 43.627200, longitude: -79.405200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kensington Market.',
  },
  {
    id: 'node-tor-4-2',
    name: 'Kensington Market Sector 2 High Street',
    zone: 'Kensington Market',
    location: { latitude: 43.630200, longitude: -79.402200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kensington Market.',
  },
  {
    id: 'node-tor-4-3',
    name: 'Kensington Market Sector 3 High Street',
    zone: 'Kensington Market',
    location: { latitude: 43.633200, longitude: -79.399200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kensington Market.',
  },
  {
    id: 'node-tor-5-1',
    name: 'The Annex Sector 1 High Street',
    zone: 'The Annex',
    location: { latitude: 43.639200, longitude: -79.395200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in The Annex.',
  },
  {
    id: 'node-tor-5-2',
    name: 'The Annex Sector 2 High Street',
    zone: 'The Annex',
    location: { latitude: 43.642200, longitude: -79.392200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in The Annex.',
  },
  {
    id: 'node-tor-5-3',
    name: 'The Annex Sector 3 High Street',
    zone: 'The Annex',
    location: { latitude: 43.645200, longitude: -79.389200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in The Annex.',
  },
  {
    id: 'node-tor-6-1',
    name: 'Distillery District Sector 1 High Street',
    zone: 'Distillery District',
    location: { latitude: 43.651200, longitude: -79.385200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Distillery District.',
  },
  {
    id: 'node-tor-6-2',
    name: 'Distillery District Sector 2 High Street',
    zone: 'Distillery District',
    location: { latitude: 43.654200, longitude: -79.382200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Distillery District.',
  },
  {
    id: 'node-tor-6-3',
    name: 'Distillery District Sector 3 High Street',
    zone: 'Distillery District',
    location: { latitude: 43.657200, longitude: -79.379200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Distillery District.',
  },
  {
    id: 'node-tor-7-1',
    name: 'Liberty Village Sector 1 High Street',
    zone: 'Liberty Village',
    location: { latitude: 43.663200, longitude: -79.375200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Liberty Village.',
  },
  {
    id: 'node-tor-7-2',
    name: 'Liberty Village Sector 2 High Street',
    zone: 'Liberty Village',
    location: { latitude: 43.666200, longitude: -79.372200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Liberty Village.',
  },
  {
    id: 'node-tor-7-3',
    name: 'Liberty Village Sector 3 High Street',
    zone: 'Liberty Village',
    location: { latitude: 43.669200, longitude: -79.369200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Liberty Village.',
  },
  {
    id: 'node-tor-8-1',
    name: 'Scarborough Sector 1 High Street',
    zone: 'Scarborough',
    location: { latitude: 43.675200, longitude: -79.365200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Scarborough.',
  },
  {
    id: 'node-tor-8-2',
    name: 'Scarborough Sector 2 High Street',
    zone: 'Scarborough',
    location: { latitude: 43.678200, longitude: -79.362200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Scarborough.',
  },
  {
    id: 'node-tor-8-3',
    name: 'Scarborough Sector 3 High Street',
    zone: 'Scarborough',
    location: { latitude: 43.681200, longitude: -79.359200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Scarborough.',
  },
  {
    id: 'node-tor-9-1',
    name: 'North York Sector 1 High Street',
    zone: 'North York',
    location: { latitude: 43.687200, longitude: -79.355200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in North York.',
  },
  {
    id: 'node-tor-9-2',
    name: 'North York Sector 2 High Street',
    zone: 'North York',
    location: { latitude: 43.690200, longitude: -79.352200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in North York.',
  },
  {
    id: 'node-tor-9-3',
    name: 'North York Sector 3 High Street',
    zone: 'North York',
    location: { latitude: 43.693200, longitude: -79.349200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in North York.',
  },
  {
    id: 'node-tor-10-1',
    name: 'Mississauga Hub Sector 1 High Street',
    zone: 'Mississauga Hub',
    location: { latitude: 43.699200, longitude: -79.345200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mississauga Hub.',
  },
  {
    id: 'node-tor-10-2',
    name: 'Mississauga Hub Sector 2 High Street',
    zone: 'Mississauga Hub',
    location: { latitude: 43.702200, longitude: -79.342200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mississauga Hub.',
  },
  {
    id: 'node-tor-10-3',
    name: 'Mississauga Hub Sector 3 High Street',
    zone: 'Mississauga Hub',
    location: { latitude: 43.705200, longitude: -79.339200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mississauga Hub.',
  },
];

export const TORONTO_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-tor-1',
    fromNodeId: 'node-tor-1-1',
    toNodeId: 'node-tor-1-2',
    roadName: 'Downtown Toronto Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-2',
    fromNodeId: 'node-tor-1-2',
    toNodeId: 'node-tor-1-3',
    roadName: 'Downtown Toronto Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-3',
    fromNodeId: 'node-tor-2-1',
    toNodeId: 'node-tor-2-2',
    roadName: 'Yorkville Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-4',
    fromNodeId: 'node-tor-2-2',
    toNodeId: 'node-tor-2-3',
    roadName: 'Yorkville Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-5',
    fromNodeId: 'node-tor-3-1',
    toNodeId: 'node-tor-3-2',
    roadName: 'Queen West Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-6',
    fromNodeId: 'node-tor-3-2',
    toNodeId: 'node-tor-3-3',
    roadName: 'Queen West Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-7',
    fromNodeId: 'node-tor-4-1',
    toNodeId: 'node-tor-4-2',
    roadName: 'Kensington Market Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-8',
    fromNodeId: 'node-tor-4-2',
    toNodeId: 'node-tor-4-3',
    roadName: 'Kensington Market Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-9',
    fromNodeId: 'node-tor-5-1',
    toNodeId: 'node-tor-5-2',
    roadName: 'The Annex Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-10',
    fromNodeId: 'node-tor-5-2',
    toNodeId: 'node-tor-5-3',
    roadName: 'The Annex Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-11',
    fromNodeId: 'node-tor-6-1',
    toNodeId: 'node-tor-6-2',
    roadName: 'Distillery District Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-12',
    fromNodeId: 'node-tor-6-2',
    toNodeId: 'node-tor-6-3',
    roadName: 'Distillery District Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-13',
    fromNodeId: 'node-tor-7-1',
    toNodeId: 'node-tor-7-2',
    roadName: 'Liberty Village Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-14',
    fromNodeId: 'node-tor-7-2',
    toNodeId: 'node-tor-7-3',
    roadName: 'Liberty Village Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-15',
    fromNodeId: 'node-tor-8-1',
    toNodeId: 'node-tor-8-2',
    roadName: 'Scarborough Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-16',
    fromNodeId: 'node-tor-8-2',
    toNodeId: 'node-tor-8-3',
    roadName: 'Scarborough Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-17',
    fromNodeId: 'node-tor-9-1',
    toNodeId: 'node-tor-9-2',
    roadName: 'North York Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-18',
    fromNodeId: 'node-tor-9-2',
    toNodeId: 'node-tor-9-3',
    roadName: 'North York Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-19',
    fromNodeId: 'node-tor-10-1',
    toNodeId: 'node-tor-10-2',
    roadName: 'Mississauga Hub Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tor-20',
    fromNodeId: 'node-tor-10-2',
    toNodeId: 'node-tor-10-3',
    roadName: 'Mississauga Hub Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
