/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Tiruchirappalli Rockfort Zone
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const TRICHY_BASE_COORDINATE: GeoCoordinate = {
  latitude: 10.7905,
  longitude: 78.7047,
};

export const TRICHY_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-tri-1-1',
    name: 'Thillai Nagar Sector 1 High Street',
    zone: 'Thillai Nagar',
    location: { latitude: 10.728500, longitude: 78.652700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Thillai Nagar.',
  },
  {
    id: 'node-tri-1-2',
    name: 'Thillai Nagar Sector 2 High Street',
    zone: 'Thillai Nagar',
    location: { latitude: 10.731500, longitude: 78.655700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Thillai Nagar.',
  },
  {
    id: 'node-tri-1-3',
    name: 'Thillai Nagar Sector 3 High Street',
    zone: 'Thillai Nagar',
    location: { latitude: 10.734500, longitude: 78.658700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Thillai Nagar.',
  },
  {
    id: 'node-tri-2-1',
    name: 'Cantonment Sector 1 High Street',
    zone: 'Cantonment',
    location: { latitude: 10.740500, longitude: 78.662700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cantonment.',
  },
  {
    id: 'node-tri-2-2',
    name: 'Cantonment Sector 2 High Street',
    zone: 'Cantonment',
    location: { latitude: 10.743500, longitude: 78.665700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cantonment.',
  },
  {
    id: 'node-tri-2-3',
    name: 'Cantonment Sector 3 High Street',
    zone: 'Cantonment',
    location: { latitude: 10.746500, longitude: 78.668700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cantonment.',
  },
  {
    id: 'node-tri-3-1',
    name: 'Srirangam Sector 1 High Street',
    zone: 'Srirangam',
    location: { latitude: 10.752500, longitude: 78.672700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Srirangam.',
  },
  {
    id: 'node-tri-3-2',
    name: 'Srirangam Sector 2 High Street',
    zone: 'Srirangam',
    location: { latitude: 10.755500, longitude: 78.675700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Srirangam.',
  },
  {
    id: 'node-tri-3-3',
    name: 'Srirangam Sector 3 High Street',
    zone: 'Srirangam',
    location: { latitude: 10.758500, longitude: 78.678700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Srirangam.',
  },
  {
    id: 'node-tri-4-1',
    name: 'K宣传KK Nagar Sector 1 High Street',
    zone: 'K宣传KK Nagar',
    location: { latitude: 10.764500, longitude: 78.682700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in K宣传KK Nagar.',
  },
  {
    id: 'node-tri-4-2',
    name: 'K宣传KK Nagar Sector 2 High Street',
    zone: 'K宣传KK Nagar',
    location: { latitude: 10.767500, longitude: 78.685700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in K宣传KK Nagar.',
  },
  {
    id: 'node-tri-4-3',
    name: 'K宣传KK Nagar Sector 3 High Street',
    zone: 'K宣传KK Nagar',
    location: { latitude: 10.770500, longitude: 78.688700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in K宣传KK Nagar.',
  },
  {
    id: 'node-tri-5-1',
    name: 'Main Guard Gate Sector 1 High Street',
    zone: 'Main Guard Gate',
    location: { latitude: 10.776500, longitude: 78.692700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Main Guard Gate.',
  },
  {
    id: 'node-tri-5-2',
    name: 'Main Guard Gate Sector 2 High Street',
    zone: 'Main Guard Gate',
    location: { latitude: 10.779500, longitude: 78.695700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Main Guard Gate.',
  },
  {
    id: 'node-tri-5-3',
    name: 'Main Guard Gate Sector 3 High Street',
    zone: 'Main Guard Gate',
    location: { latitude: 10.782500, longitude: 78.698700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Main Guard Gate.',
  },
  {
    id: 'node-tri-6-1',
    name: 'Shastri Road Sector 1 High Street',
    zone: 'Shastri Road',
    location: { latitude: 10.788500, longitude: 78.702700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shastri Road.',
  },
  {
    id: 'node-tri-6-2',
    name: 'Shastri Road Sector 2 High Street',
    zone: 'Shastri Road',
    location: { latitude: 10.791500, longitude: 78.705700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shastri Road.',
  },
  {
    id: 'node-tri-6-3',
    name: 'Shastri Road Sector 3 High Street',
    zone: 'Shastri Road',
    location: { latitude: 10.794500, longitude: 78.708700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shastri Road.',
  },
  {
    id: 'node-tri-7-1',
    name: 'Central Bus Stand Sector 1 High Street',
    zone: 'Central Bus Stand',
    location: { latitude: 10.800500, longitude: 78.712700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Central Bus Stand.',
  },
  {
    id: 'node-tri-7-2',
    name: 'Central Bus Stand Sector 2 High Street',
    zone: 'Central Bus Stand',
    location: { latitude: 10.803500, longitude: 78.715700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Central Bus Stand.',
  },
  {
    id: 'node-tri-7-3',
    name: 'Central Bus Stand Sector 3 High Street',
    zone: 'Central Bus Stand',
    location: { latitude: 10.806500, longitude: 78.718700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Central Bus Stand.',
  },
  {
    id: 'node-tri-8-1',
    name: 'KK Nagar Trichy Sector 1 High Street',
    zone: 'KK Nagar Trichy',
    location: { latitude: 10.812500, longitude: 78.722700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in KK Nagar Trichy.',
  },
  {
    id: 'node-tri-8-2',
    name: 'KK Nagar Trichy Sector 2 High Street',
    zone: 'KK Nagar Trichy',
    location: { latitude: 10.815500, longitude: 78.725700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in KK Nagar Trichy.',
  },
  {
    id: 'node-tri-8-3',
    name: 'KK Nagar Trichy Sector 3 High Street',
    zone: 'KK Nagar Trichy',
    location: { latitude: 10.818500, longitude: 78.728700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in KK Nagar Trichy.',
  },
  {
    id: 'node-tri-9-1',
    name: 'Airport Road Sector 1 High Street',
    zone: 'Airport Road',
    location: { latitude: 10.824500, longitude: 78.732700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Airport Road.',
  },
  {
    id: 'node-tri-9-2',
    name: 'Airport Road Sector 2 High Street',
    zone: 'Airport Road',
    location: { latitude: 10.827500, longitude: 78.735700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Airport Road.',
  },
  {
    id: 'node-tri-9-3',
    name: 'Airport Road Sector 3 High Street',
    zone: 'Airport Road',
    location: { latitude: 10.830500, longitude: 78.738700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Airport Road.',
  },
  {
    id: 'node-tri-10-1',
    name: 'Ponmalai Sector 1 High Street',
    zone: 'Ponmalai',
    location: { latitude: 10.836500, longitude: 78.742700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ponmalai.',
  },
  {
    id: 'node-tri-10-2',
    name: 'Ponmalai Sector 2 High Street',
    zone: 'Ponmalai',
    location: { latitude: 10.839500, longitude: 78.745700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ponmalai.',
  },
  {
    id: 'node-tri-10-3',
    name: 'Ponmalai Sector 3 High Street',
    zone: 'Ponmalai',
    location: { latitude: 10.842500, longitude: 78.748700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ponmalai.',
  },
];

export const TRICHY_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-tri-1',
    fromNodeId: 'node-tri-1-1',
    toNodeId: 'node-tri-1-2',
    roadName: 'Thillai Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-2',
    fromNodeId: 'node-tri-1-2',
    toNodeId: 'node-tri-1-3',
    roadName: 'Thillai Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-3',
    fromNodeId: 'node-tri-2-1',
    toNodeId: 'node-tri-2-2',
    roadName: 'Cantonment Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-4',
    fromNodeId: 'node-tri-2-2',
    toNodeId: 'node-tri-2-3',
    roadName: 'Cantonment Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-5',
    fromNodeId: 'node-tri-3-1',
    toNodeId: 'node-tri-3-2',
    roadName: 'Srirangam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-6',
    fromNodeId: 'node-tri-3-2',
    toNodeId: 'node-tri-3-3',
    roadName: 'Srirangam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-7',
    fromNodeId: 'node-tri-4-1',
    toNodeId: 'node-tri-4-2',
    roadName: 'K宣传KK Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-8',
    fromNodeId: 'node-tri-4-2',
    toNodeId: 'node-tri-4-3',
    roadName: 'K宣传KK Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-9',
    fromNodeId: 'node-tri-5-1',
    toNodeId: 'node-tri-5-2',
    roadName: 'Main Guard Gate Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-10',
    fromNodeId: 'node-tri-5-2',
    toNodeId: 'node-tri-5-3',
    roadName: 'Main Guard Gate Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-11',
    fromNodeId: 'node-tri-6-1',
    toNodeId: 'node-tri-6-2',
    roadName: 'Shastri Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-12',
    fromNodeId: 'node-tri-6-2',
    toNodeId: 'node-tri-6-3',
    roadName: 'Shastri Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-13',
    fromNodeId: 'node-tri-7-1',
    toNodeId: 'node-tri-7-2',
    roadName: 'Central Bus Stand Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-14',
    fromNodeId: 'node-tri-7-2',
    toNodeId: 'node-tri-7-3',
    roadName: 'Central Bus Stand Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-15',
    fromNodeId: 'node-tri-8-1',
    toNodeId: 'node-tri-8-2',
    roadName: 'KK Nagar Trichy Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-16',
    fromNodeId: 'node-tri-8-2',
    toNodeId: 'node-tri-8-3',
    roadName: 'KK Nagar Trichy Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-17',
    fromNodeId: 'node-tri-9-1',
    toNodeId: 'node-tri-9-2',
    roadName: 'Airport Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-18',
    fromNodeId: 'node-tri-9-2',
    toNodeId: 'node-tri-9-3',
    roadName: 'Airport Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-19',
    fromNodeId: 'node-tri-10-1',
    toNodeId: 'node-tri-10-2',
    roadName: 'Ponmalai Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-20',
    fromNodeId: 'node-tri-10-2',
    toNodeId: 'node-tri-10-3',
    roadName: 'Ponmalai Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
