/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Thiruvananthapuram Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const TRIVANDRUM_BASE_COORDINATE: GeoCoordinate = {
  latitude: 8.5241,
  longitude: 76.9366,
};

export const TRIVANDRUM_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-tri-1-1',
    name: 'Kowdiar Sector 1 High Street',
    zone: 'Kowdiar',
    location: { latitude: 8.462100, longitude: 76.884600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kowdiar.',
  },
  {
    id: 'node-tri-1-2',
    name: 'Kowdiar Sector 2 High Street',
    zone: 'Kowdiar',
    location: { latitude: 8.465100, longitude: 76.887600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kowdiar.',
  },
  {
    id: 'node-tri-1-3',
    name: 'Kowdiar Sector 3 High Street',
    zone: 'Kowdiar',
    location: { latitude: 8.468100, longitude: 76.890600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kowdiar.',
  },
  {
    id: 'node-tri-2-1',
    name: 'Vellayambalam Sector 1 High Street',
    zone: 'Vellayambalam',
    location: { latitude: 8.474100, longitude: 76.894600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vellayambalam.',
  },
  {
    id: 'node-tri-2-2',
    name: 'Vellayambalam Sector 2 High Street',
    zone: 'Vellayambalam',
    location: { latitude: 8.477100, longitude: 76.897600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vellayambalam.',
  },
  {
    id: 'node-tri-2-3',
    name: 'Vellayambalam Sector 3 High Street',
    zone: 'Vellayambalam',
    location: { latitude: 8.480100, longitude: 76.900600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vellayambalam.',
  },
  {
    id: 'node-tri-3-1',
    name: 'Technopark Kazhakkoottam Sector 1 High Street',
    zone: 'Technopark Kazhakkoottam',
    location: { latitude: 8.486100, longitude: 76.904600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Technopark Kazhakkoottam.',
  },
  {
    id: 'node-tri-3-2',
    name: 'Technopark Kazhakkoottam Sector 2 High Street',
    zone: 'Technopark Kazhakkoottam',
    location: { latitude: 8.489100, longitude: 76.907600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Technopark Kazhakkoottam.',
  },
  {
    id: 'node-tri-3-3',
    name: 'Technopark Kazhakkoottam Sector 3 High Street',
    zone: 'Technopark Kazhakkoottam',
    location: { latitude: 8.492100, longitude: 76.910600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Technopark Kazhakkoottam.',
  },
  {
    id: 'node-tri-4-1',
    name: 'Palayam Sector 1 High Street',
    zone: 'Palayam',
    location: { latitude: 8.498100, longitude: 76.914600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Palayam.',
  },
  {
    id: 'node-tri-4-2',
    name: 'Palayam Sector 2 High Street',
    zone: 'Palayam',
    location: { latitude: 8.501100, longitude: 76.917600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Palayam.',
  },
  {
    id: 'node-tri-4-3',
    name: 'Palayam Sector 3 High Street',
    zone: 'Palayam',
    location: { latitude: 8.504100, longitude: 76.920600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Palayam.',
  },
  {
    id: 'node-tri-5-1',
    name: 'Pattom Sector 1 High Street',
    zone: 'Pattom',
    location: { latitude: 8.510100, longitude: 76.924600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pattom.',
  },
  {
    id: 'node-tri-5-2',
    name: 'Pattom Sector 2 High Street',
    zone: 'Pattom',
    location: { latitude: 8.513100, longitude: 76.927600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pattom.',
  },
  {
    id: 'node-tri-5-3',
    name: 'Pattom Sector 3 High Street',
    zone: 'Pattom',
    location: { latitude: 8.516100, longitude: 76.930600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pattom.',
  },
  {
    id: 'node-tri-6-1',
    name: 'Sasthamangalam Sector 1 High Street',
    zone: 'Sasthamangalam',
    location: { latitude: 8.522100, longitude: 76.934600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sasthamangalam.',
  },
  {
    id: 'node-tri-6-2',
    name: 'Sasthamangalam Sector 2 High Street',
    zone: 'Sasthamangalam',
    location: { latitude: 8.525100, longitude: 76.937600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sasthamangalam.',
  },
  {
    id: 'node-tri-6-3',
    name: 'Sasthamangalam Sector 3 High Street',
    zone: 'Sasthamangalam',
    location: { latitude: 8.528100, longitude: 76.940600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sasthamangalam.',
  },
  {
    id: 'node-tri-7-1',
    name: 'Vazhuthacaud Sector 1 High Street',
    zone: 'Vazhuthacaud',
    location: { latitude: 8.534100, longitude: 76.944600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vazhuthacaud.',
  },
  {
    id: 'node-tri-7-2',
    name: 'Vazhuthacaud Sector 2 High Street',
    zone: 'Vazhuthacaud',
    location: { latitude: 8.537100, longitude: 76.947600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vazhuthacaud.',
  },
  {
    id: 'node-tri-7-3',
    name: 'Vazhuthacaud Sector 3 High Street',
    zone: 'Vazhuthacaud',
    location: { latitude: 8.540100, longitude: 76.950600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vazhuthacaud.',
  },
  {
    id: 'node-tri-8-1',
    name: 'Thampanoor Sector 1 High Street',
    zone: 'Thampanoor',
    location: { latitude: 8.546100, longitude: 76.954600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Thampanoor.',
  },
  {
    id: 'node-tri-8-2',
    name: 'Thampanoor Sector 2 High Street',
    zone: 'Thampanoor',
    location: { latitude: 8.549100, longitude: 76.957600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Thampanoor.',
  },
  {
    id: 'node-tri-8-3',
    name: 'Thampanoor Sector 3 High Street',
    zone: 'Thampanoor',
    location: { latitude: 8.552100, longitude: 76.960600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Thampanoor.',
  },
  {
    id: 'node-tri-9-1',
    name: 'Sreekariyam Sector 1 High Street',
    zone: 'Sreekariyam',
    location: { latitude: 8.558100, longitude: 76.964600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sreekariyam.',
  },
  {
    id: 'node-tri-9-2',
    name: 'Sreekariyam Sector 2 High Street',
    zone: 'Sreekariyam',
    location: { latitude: 8.561100, longitude: 76.967600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sreekariyam.',
  },
  {
    id: 'node-tri-9-3',
    name: 'Sreekariyam Sector 3 High Street',
    zone: 'Sreekariyam',
    location: { latitude: 8.564100, longitude: 76.970600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sreekariyam.',
  },
  {
    id: 'node-tri-10-1',
    name: 'Poojappura Sector 1 High Street',
    zone: 'Poojappura',
    location: { latitude: 8.570100, longitude: 76.974600 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Poojappura.',
  },
  {
    id: 'node-tri-10-2',
    name: 'Poojappura Sector 2 High Street',
    zone: 'Poojappura',
    location: { latitude: 8.573100, longitude: 76.977600 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Poojappura.',
  },
  {
    id: 'node-tri-10-3',
    name: 'Poojappura Sector 3 High Street',
    zone: 'Poojappura',
    location: { latitude: 8.576100, longitude: 76.980600 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Poojappura.',
  },
];

export const TRIVANDRUM_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-tri-1',
    fromNodeId: 'node-tri-1-1',
    toNodeId: 'node-tri-1-2',
    roadName: 'Kowdiar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-2',
    fromNodeId: 'node-tri-1-2',
    toNodeId: 'node-tri-1-3',
    roadName: 'Kowdiar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-3',
    fromNodeId: 'node-tri-2-1',
    toNodeId: 'node-tri-2-2',
    roadName: 'Vellayambalam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-4',
    fromNodeId: 'node-tri-2-2',
    toNodeId: 'node-tri-2-3',
    roadName: 'Vellayambalam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-5',
    fromNodeId: 'node-tri-3-1',
    toNodeId: 'node-tri-3-2',
    roadName: 'Technopark Kazhakkoottam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-6',
    fromNodeId: 'node-tri-3-2',
    toNodeId: 'node-tri-3-3',
    roadName: 'Technopark Kazhakkoottam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-7',
    fromNodeId: 'node-tri-4-1',
    toNodeId: 'node-tri-4-2',
    roadName: 'Palayam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-8',
    fromNodeId: 'node-tri-4-2',
    toNodeId: 'node-tri-4-3',
    roadName: 'Palayam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-9',
    fromNodeId: 'node-tri-5-1',
    toNodeId: 'node-tri-5-2',
    roadName: 'Pattom Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-10',
    fromNodeId: 'node-tri-5-2',
    toNodeId: 'node-tri-5-3',
    roadName: 'Pattom Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-11',
    fromNodeId: 'node-tri-6-1',
    toNodeId: 'node-tri-6-2',
    roadName: 'Sasthamangalam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-12',
    fromNodeId: 'node-tri-6-2',
    toNodeId: 'node-tri-6-3',
    roadName: 'Sasthamangalam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-13',
    fromNodeId: 'node-tri-7-1',
    toNodeId: 'node-tri-7-2',
    roadName: 'Vazhuthacaud Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-14',
    fromNodeId: 'node-tri-7-2',
    toNodeId: 'node-tri-7-3',
    roadName: 'Vazhuthacaud Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-15',
    fromNodeId: 'node-tri-8-1',
    toNodeId: 'node-tri-8-2',
    roadName: 'Thampanoor Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-16',
    fromNodeId: 'node-tri-8-2',
    toNodeId: 'node-tri-8-3',
    roadName: 'Thampanoor Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-17',
    fromNodeId: 'node-tri-9-1',
    toNodeId: 'node-tri-9-2',
    roadName: 'Sreekariyam Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-18',
    fromNodeId: 'node-tri-9-2',
    toNodeId: 'node-tri-9-3',
    roadName: 'Sreekariyam Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-19',
    fromNodeId: 'node-tri-10-1',
    toNodeId: 'node-tri-10-2',
    roadName: 'Poojappura Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-tri-20',
    fromNodeId: 'node-tri-10-2',
    toNodeId: 'node-tri-10-3',
    roadName: 'Poojappura Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
