/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Udaipur Lake City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const UDAIPUR_BASE_COORDINATE: GeoCoordinate = {
  latitude: 24.5854,
  longitude: 73.7125,
};

export const UDAIPUR_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-uda-1-1',
    name: 'Fateh Sagar Sector 1 High Street',
    zone: 'Fateh Sagar',
    location: { latitude: 24.523400, longitude: 73.660500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fateh Sagar.',
  },
  {
    id: 'node-uda-1-2',
    name: 'Fateh Sagar Sector 2 High Street',
    zone: 'Fateh Sagar',
    location: { latitude: 24.526400, longitude: 73.663500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fateh Sagar.',
  },
  {
    id: 'node-uda-1-3',
    name: 'Fateh Sagar Sector 3 High Street',
    zone: 'Fateh Sagar',
    location: { latitude: 24.529400, longitude: 73.666500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fateh Sagar.',
  },
  {
    id: 'node-uda-2-1',
    name: 'Panchwati Sector 1 High Street',
    zone: 'Panchwati',
    location: { latitude: 24.535400, longitude: 73.670500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Panchwati.',
  },
  {
    id: 'node-uda-2-2',
    name: 'Panchwati Sector 2 High Street',
    zone: 'Panchwati',
    location: { latitude: 24.538400, longitude: 73.673500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Panchwati.',
  },
  {
    id: 'node-uda-2-3',
    name: 'Panchwati Sector 3 High Street',
    zone: 'Panchwati',
    location: { latitude: 24.541400, longitude: 73.676500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Panchwati.',
  },
  {
    id: 'node-uda-3-1',
    name: 'Saheli Nagar Sector 1 High Street',
    zone: 'Saheli Nagar',
    location: { latitude: 24.547400, longitude: 73.680500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Saheli Nagar.',
  },
  {
    id: 'node-uda-3-2',
    name: 'Saheli Nagar Sector 2 High Street',
    zone: 'Saheli Nagar',
    location: { latitude: 24.550400, longitude: 73.683500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Saheli Nagar.',
  },
  {
    id: 'node-uda-3-3',
    name: 'Saheli Nagar Sector 3 High Street',
    zone: 'Saheli Nagar',
    location: { latitude: 24.553400, longitude: 73.686500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Saheli Nagar.',
  },
  {
    id: 'node-uda-4-1',
    name: 'Hiran Magri Sector 1 High Street',
    zone: 'Hiran Magri',
    location: { latitude: 24.559400, longitude: 73.690500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hiran Magri.',
  },
  {
    id: 'node-uda-4-2',
    name: 'Hiran Magri Sector 2 High Street',
    zone: 'Hiran Magri',
    location: { latitude: 24.562400, longitude: 73.693500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hiran Magri.',
  },
  {
    id: 'node-uda-4-3',
    name: 'Hiran Magri Sector 3 High Street',
    zone: 'Hiran Magri',
    location: { latitude: 24.565400, longitude: 73.696500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hiran Magri.',
  },
  {
    id: 'node-uda-5-1',
    name: 'Shobhagpura Sector 1 High Street',
    zone: 'Shobhagpura',
    location: { latitude: 24.571400, longitude: 73.700500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shobhagpura.',
  },
  {
    id: 'node-uda-5-2',
    name: 'Shobhagpura Sector 2 High Street',
    zone: 'Shobhagpura',
    location: { latitude: 24.574400, longitude: 73.703500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shobhagpura.',
  },
  {
    id: 'node-uda-5-3',
    name: 'Shobhagpura Sector 3 High Street',
    zone: 'Shobhagpura',
    location: { latitude: 24.577400, longitude: 73.706500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shobhagpura.',
  },
  {
    id: 'node-uda-6-1',
    name: 'Sukher Sector 1 High Street',
    zone: 'Sukher',
    location: { latitude: 24.583400, longitude: 73.710500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sukher.',
  },
  {
    id: 'node-uda-6-2',
    name: 'Sukher Sector 2 High Street',
    zone: 'Sukher',
    location: { latitude: 24.586400, longitude: 73.713500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sukher.',
  },
  {
    id: 'node-uda-6-3',
    name: 'Sukher Sector 3 High Street',
    zone: 'Sukher',
    location: { latitude: 24.589400, longitude: 73.716500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sukher.',
  },
  {
    id: 'node-uda-7-1',
    name: 'Madhuban Sector 1 High Street',
    zone: 'Madhuban',
    location: { latitude: 24.595400, longitude: 73.720500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Madhuban.',
  },
  {
    id: 'node-uda-7-2',
    name: 'Madhuban Sector 2 High Street',
    zone: 'Madhuban',
    location: { latitude: 24.598400, longitude: 73.723500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Madhuban.',
  },
  {
    id: 'node-uda-7-3',
    name: 'Madhuban Sector 3 High Street',
    zone: 'Madhuban',
    location: { latitude: 24.601400, longitude: 73.726500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Madhuban.',
  },
  {
    id: 'node-uda-8-1',
    name: 'City Palace Road Sector 1 High Street',
    zone: 'City Palace Road',
    location: { latitude: 24.607400, longitude: 73.730500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in City Palace Road.',
  },
  {
    id: 'node-uda-8-2',
    name: 'City Palace Road Sector 2 High Street',
    zone: 'City Palace Road',
    location: { latitude: 24.610400, longitude: 73.733500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in City Palace Road.',
  },
  {
    id: 'node-uda-8-3',
    name: 'City Palace Road Sector 3 High Street',
    zone: 'City Palace Road',
    location: { latitude: 24.613400, longitude: 73.736500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in City Palace Road.',
  },
  {
    id: 'node-uda-9-1',
    name: 'Goverdhan Vilas Sector 1 High Street',
    zone: 'Goverdhan Vilas',
    location: { latitude: 24.619400, longitude: 73.740500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Goverdhan Vilas.',
  },
  {
    id: 'node-uda-9-2',
    name: 'Goverdhan Vilas Sector 2 High Street',
    zone: 'Goverdhan Vilas',
    location: { latitude: 24.622400, longitude: 73.743500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Goverdhan Vilas.',
  },
  {
    id: 'node-uda-9-3',
    name: 'Goverdhan Vilas Sector 3 High Street',
    zone: 'Goverdhan Vilas',
    location: { latitude: 24.625400, longitude: 73.746500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Goverdhan Vilas.',
  },
  {
    id: 'node-uda-10-1',
    name: 'Bhuwana Sector 1 High Street',
    zone: 'Bhuwana',
    location: { latitude: 24.631400, longitude: 73.750500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bhuwana.',
  },
  {
    id: 'node-uda-10-2',
    name: 'Bhuwana Sector 2 High Street',
    zone: 'Bhuwana',
    location: { latitude: 24.634400, longitude: 73.753500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bhuwana.',
  },
  {
    id: 'node-uda-10-3',
    name: 'Bhuwana Sector 3 High Street',
    zone: 'Bhuwana',
    location: { latitude: 24.637400, longitude: 73.756500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bhuwana.',
  },
];

export const UDAIPUR_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-uda-1',
    fromNodeId: 'node-uda-1-1',
    toNodeId: 'node-uda-1-2',
    roadName: 'Fateh Sagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-2',
    fromNodeId: 'node-uda-1-2',
    toNodeId: 'node-uda-1-3',
    roadName: 'Fateh Sagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-3',
    fromNodeId: 'node-uda-2-1',
    toNodeId: 'node-uda-2-2',
    roadName: 'Panchwati Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-4',
    fromNodeId: 'node-uda-2-2',
    toNodeId: 'node-uda-2-3',
    roadName: 'Panchwati Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-5',
    fromNodeId: 'node-uda-3-1',
    toNodeId: 'node-uda-3-2',
    roadName: 'Saheli Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-6',
    fromNodeId: 'node-uda-3-2',
    toNodeId: 'node-uda-3-3',
    roadName: 'Saheli Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-7',
    fromNodeId: 'node-uda-4-1',
    toNodeId: 'node-uda-4-2',
    roadName: 'Hiran Magri Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-8',
    fromNodeId: 'node-uda-4-2',
    toNodeId: 'node-uda-4-3',
    roadName: 'Hiran Magri Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-9',
    fromNodeId: 'node-uda-5-1',
    toNodeId: 'node-uda-5-2',
    roadName: 'Shobhagpura Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-10',
    fromNodeId: 'node-uda-5-2',
    toNodeId: 'node-uda-5-3',
    roadName: 'Shobhagpura Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-11',
    fromNodeId: 'node-uda-6-1',
    toNodeId: 'node-uda-6-2',
    roadName: 'Sukher Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-12',
    fromNodeId: 'node-uda-6-2',
    toNodeId: 'node-uda-6-3',
    roadName: 'Sukher Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-13',
    fromNodeId: 'node-uda-7-1',
    toNodeId: 'node-uda-7-2',
    roadName: 'Madhuban Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-14',
    fromNodeId: 'node-uda-7-2',
    toNodeId: 'node-uda-7-3',
    roadName: 'Madhuban Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-15',
    fromNodeId: 'node-uda-8-1',
    toNodeId: 'node-uda-8-2',
    roadName: 'City Palace Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-16',
    fromNodeId: 'node-uda-8-2',
    toNodeId: 'node-uda-8-3',
    roadName: 'City Palace Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-17',
    fromNodeId: 'node-uda-9-1',
    toNodeId: 'node-uda-9-2',
    roadName: 'Goverdhan Vilas Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-18',
    fromNodeId: 'node-uda-9-2',
    toNodeId: 'node-uda-9-3',
    roadName: 'Goverdhan Vilas Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-19',
    fromNodeId: 'node-uda-10-1',
    toNodeId: 'node-uda-10-2',
    roadName: 'Bhuwana Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-uda-20',
    fromNodeId: 'node-uda-10-2',
    toNodeId: 'node-uda-10-3',
    roadName: 'Bhuwana Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
