/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Vadodara Cultural Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const VADODARA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 22.3072,
  longitude: 73.1812,
};

export const VADODARA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-vad-1-1',
    name: 'Alkapuri Sector 1 High Street',
    zone: 'Alkapuri',
    location: { latitude: 22.245200, longitude: 73.129200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Alkapuri.',
  },
  {
    id: 'node-vad-1-2',
    name: 'Alkapuri Sector 2 High Street',
    zone: 'Alkapuri',
    location: { latitude: 22.248200, longitude: 73.132200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Alkapuri.',
  },
  {
    id: 'node-vad-1-3',
    name: 'Alkapuri Sector 3 High Street',
    zone: 'Alkapuri',
    location: { latitude: 22.251200, longitude: 73.135200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Alkapuri.',
  },
  {
    id: 'node-vad-2-1',
    name: 'Fatehgunj Sector 1 High Street',
    zone: 'Fatehgunj',
    location: { latitude: 22.257200, longitude: 73.139200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Fatehgunj.',
  },
  {
    id: 'node-vad-2-2',
    name: 'Fatehgunj Sector 2 High Street',
    zone: 'Fatehgunj',
    location: { latitude: 22.260200, longitude: 73.142200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Fatehgunj.',
  },
  {
    id: 'node-vad-2-3',
    name: 'Fatehgunj Sector 3 High Street',
    zone: 'Fatehgunj',
    location: { latitude: 22.263200, longitude: 73.145200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Fatehgunj.',
  },
  {
    id: 'node-vad-3-1',
    name: 'Akota Sector 1 High Street',
    zone: 'Akota',
    location: { latitude: 22.269200, longitude: 73.149200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Akota.',
  },
  {
    id: 'node-vad-3-2',
    name: 'Akota Sector 2 High Street',
    zone: 'Akota',
    location: { latitude: 22.272200, longitude: 73.152200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Akota.',
  },
  {
    id: 'node-vad-3-3',
    name: 'Akota Sector 3 High Street',
    zone: 'Akota',
    location: { latitude: 22.275200, longitude: 73.155200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Akota.',
  },
  {
    id: 'node-vad-4-1',
    name: 'Gotri Sector 1 High Street',
    zone: 'Gotri',
    location: { latitude: 22.281200, longitude: 73.159200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gotri.',
  },
  {
    id: 'node-vad-4-2',
    name: 'Gotri Sector 2 High Street',
    zone: 'Gotri',
    location: { latitude: 22.284200, longitude: 73.162200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gotri.',
  },
  {
    id: 'node-vad-4-3',
    name: 'Gotri Sector 3 High Street',
    zone: 'Gotri',
    location: { latitude: 22.287200, longitude: 73.165200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gotri.',
  },
  {
    id: 'node-vad-5-1',
    name: 'Vasna Road Sector 1 High Street',
    zone: 'Vasna Road',
    location: { latitude: 22.293200, longitude: 73.169200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Vasna Road.',
  },
  {
    id: 'node-vad-5-2',
    name: 'Vasna Road Sector 2 High Street',
    zone: 'Vasna Road',
    location: { latitude: 22.296200, longitude: 73.172200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Vasna Road.',
  },
  {
    id: 'node-vad-5-3',
    name: 'Vasna Road Sector 3 High Street',
    zone: 'Vasna Road',
    location: { latitude: 22.299200, longitude: 73.175200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Vasna Road.',
  },
  {
    id: 'node-vad-6-1',
    name: 'Manjalpur Sector 1 High Street',
    zone: 'Manjalpur',
    location: { latitude: 22.305200, longitude: 73.179200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Manjalpur.',
  },
  {
    id: 'node-vad-6-2',
    name: 'Manjalpur Sector 2 High Street',
    zone: 'Manjalpur',
    location: { latitude: 22.308200, longitude: 73.182200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Manjalpur.',
  },
  {
    id: 'node-vad-6-3',
    name: 'Manjalpur Sector 3 High Street',
    zone: 'Manjalpur',
    location: { latitude: 22.311200, longitude: 73.185200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Manjalpur.',
  },
  {
    id: 'node-vad-7-1',
    name: 'Karelibaug Sector 1 High Street',
    zone: 'Karelibaug',
    location: { latitude: 22.317200, longitude: 73.189200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Karelibaug.',
  },
  {
    id: 'node-vad-7-2',
    name: 'Karelibaug Sector 2 High Street',
    zone: 'Karelibaug',
    location: { latitude: 22.320200, longitude: 73.192200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Karelibaug.',
  },
  {
    id: 'node-vad-7-3',
    name: 'Karelibaug Sector 3 High Street',
    zone: 'Karelibaug',
    location: { latitude: 22.323200, longitude: 73.195200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Karelibaug.',
  },
  {
    id: 'node-vad-8-1',
    name: 'Subhanpura Sector 1 High Street',
    zone: 'Subhanpura',
    location: { latitude: 22.329200, longitude: 73.199200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Subhanpura.',
  },
  {
    id: 'node-vad-8-2',
    name: 'Subhanpura Sector 2 High Street',
    zone: 'Subhanpura',
    location: { latitude: 22.332200, longitude: 73.202200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Subhanpura.',
  },
  {
    id: 'node-vad-8-3',
    name: 'Subhanpura Sector 3 High Street',
    zone: 'Subhanpura',
    location: { latitude: 22.335200, longitude: 73.205200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Subhanpura.',
  },
  {
    id: 'node-vad-9-1',
    name: 'Sayajigunj Sector 1 High Street',
    zone: 'Sayajigunj',
    location: { latitude: 22.341200, longitude: 73.209200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sayajigunj.',
  },
  {
    id: 'node-vad-9-2',
    name: 'Sayajigunj Sector 2 High Street',
    zone: 'Sayajigunj',
    location: { latitude: 22.344200, longitude: 73.212200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sayajigunj.',
  },
  {
    id: 'node-vad-9-3',
    name: 'Sayajigunj Sector 3 High Street',
    zone: 'Sayajigunj',
    location: { latitude: 22.347200, longitude: 73.215200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sayajigunj.',
  },
  {
    id: 'node-vad-10-1',
    name: 'Waghodia Road Sector 1 High Street',
    zone: 'Waghodia Road',
    location: { latitude: 22.353200, longitude: 73.219200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Waghodia Road.',
  },
  {
    id: 'node-vad-10-2',
    name: 'Waghodia Road Sector 2 High Street',
    zone: 'Waghodia Road',
    location: { latitude: 22.356200, longitude: 73.222200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Waghodia Road.',
  },
  {
    id: 'node-vad-10-3',
    name: 'Waghodia Road Sector 3 High Street',
    zone: 'Waghodia Road',
    location: { latitude: 22.359200, longitude: 73.225200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Waghodia Road.',
  },
];

export const VADODARA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-vad-1',
    fromNodeId: 'node-vad-1-1',
    toNodeId: 'node-vad-1-2',
    roadName: 'Alkapuri Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-2',
    fromNodeId: 'node-vad-1-2',
    toNodeId: 'node-vad-1-3',
    roadName: 'Alkapuri Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-3',
    fromNodeId: 'node-vad-2-1',
    toNodeId: 'node-vad-2-2',
    roadName: 'Fatehgunj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-4',
    fromNodeId: 'node-vad-2-2',
    toNodeId: 'node-vad-2-3',
    roadName: 'Fatehgunj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-5',
    fromNodeId: 'node-vad-3-1',
    toNodeId: 'node-vad-3-2',
    roadName: 'Akota Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-6',
    fromNodeId: 'node-vad-3-2',
    toNodeId: 'node-vad-3-3',
    roadName: 'Akota Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-7',
    fromNodeId: 'node-vad-4-1',
    toNodeId: 'node-vad-4-2',
    roadName: 'Gotri Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-8',
    fromNodeId: 'node-vad-4-2',
    toNodeId: 'node-vad-4-3',
    roadName: 'Gotri Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-9',
    fromNodeId: 'node-vad-5-1',
    toNodeId: 'node-vad-5-2',
    roadName: 'Vasna Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-10',
    fromNodeId: 'node-vad-5-2',
    toNodeId: 'node-vad-5-3',
    roadName: 'Vasna Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-11',
    fromNodeId: 'node-vad-6-1',
    toNodeId: 'node-vad-6-2',
    roadName: 'Manjalpur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-12',
    fromNodeId: 'node-vad-6-2',
    toNodeId: 'node-vad-6-3',
    roadName: 'Manjalpur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-13',
    fromNodeId: 'node-vad-7-1',
    toNodeId: 'node-vad-7-2',
    roadName: 'Karelibaug Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-14',
    fromNodeId: 'node-vad-7-2',
    toNodeId: 'node-vad-7-3',
    roadName: 'Karelibaug Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-15',
    fromNodeId: 'node-vad-8-1',
    toNodeId: 'node-vad-8-2',
    roadName: 'Subhanpura Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-16',
    fromNodeId: 'node-vad-8-2',
    toNodeId: 'node-vad-8-3',
    roadName: 'Subhanpura Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-17',
    fromNodeId: 'node-vad-9-1',
    toNodeId: 'node-vad-9-2',
    roadName: 'Sayajigunj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-18',
    fromNodeId: 'node-vad-9-2',
    toNodeId: 'node-vad-9-3',
    roadName: 'Sayajigunj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-19',
    fromNodeId: 'node-vad-10-1',
    toNodeId: 'node-vad-10-2',
    roadName: 'Waghodia Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vad-20',
    fromNodeId: 'node-vad-10-2',
    toNodeId: 'node-vad-10-3',
    roadName: 'Waghodia Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
