/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Valencia Turia River Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const VALENCIA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 39.4699,
  longitude: -0.3763,
};

export const VALENCIA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-val-1-1',
    name: 'Ciutat Vella Sector 1 High Street',
    zone: 'Ciutat Vella',
    location: { latitude: 39.407900, longitude: -0.428300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ciutat Vella.',
  },
  {
    id: 'node-val-1-2',
    name: 'Ciutat Vella Sector 2 High Street',
    zone: 'Ciutat Vella',
    location: { latitude: 39.410900, longitude: -0.425300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ciutat Vella.',
  },
  {
    id: 'node-val-1-3',
    name: 'Ciutat Vella Sector 3 High Street',
    zone: 'Ciutat Vella',
    location: { latitude: 39.413900, longitude: -0.422300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ciutat Vella.',
  },
  {
    id: 'node-val-2-1',
    name: 'Ruzafa Sector 1 High Street',
    zone: 'Ruzafa',
    location: { latitude: 39.419900, longitude: -0.418300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ruzafa.',
  },
  {
    id: 'node-val-2-2',
    name: 'Ruzafa Sector 2 High Street',
    zone: 'Ruzafa',
    location: { latitude: 39.422900, longitude: -0.415300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ruzafa.',
  },
  {
    id: 'node-val-2-3',
    name: 'Ruzafa Sector 3 High Street',
    zone: 'Ruzafa',
    location: { latitude: 39.425900, longitude: -0.412300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ruzafa.',
  },
  {
    id: 'node-val-3-1',
    name: 'El Carmen Sector 1 High Street',
    zone: 'El Carmen',
    location: { latitude: 39.431900, longitude: -0.408300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in El Carmen.',
  },
  {
    id: 'node-val-3-2',
    name: 'El Carmen Sector 2 High Street',
    zone: 'El Carmen',
    location: { latitude: 39.434900, longitude: -0.405300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in El Carmen.',
  },
  {
    id: 'node-val-3-3',
    name: 'El Carmen Sector 3 High Street',
    zone: 'El Carmen',
    location: { latitude: 39.437900, longitude: -0.402300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in El Carmen.',
  },
  {
    id: 'node-val-4-1',
    name: 'El Cabanyal Sector 1 High Street',
    zone: 'El Cabanyal',
    location: { latitude: 39.443900, longitude: -0.398300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in El Cabanyal.',
  },
  {
    id: 'node-val-4-2',
    name: 'El Cabanyal Sector 2 High Street',
    zone: 'El Cabanyal',
    location: { latitude: 39.446900, longitude: -0.395300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in El Cabanyal.',
  },
  {
    id: 'node-val-4-3',
    name: 'El Cabanyal Sector 3 High Street',
    zone: 'El Cabanyal',
    location: { latitude: 39.449900, longitude: -0.392300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in El Cabanyal.',
  },
  {
    id: 'node-val-5-1',
    name: 'Extramurs Sector 1 High Street',
    zone: 'Extramurs',
    location: { latitude: 39.455900, longitude: -0.388300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Extramurs.',
  },
  {
    id: 'node-val-5-2',
    name: 'Extramurs Sector 2 High Street',
    zone: 'Extramurs',
    location: { latitude: 39.458900, longitude: -0.385300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Extramurs.',
  },
  {
    id: 'node-val-5-3',
    name: 'Extramurs Sector 3 High Street',
    zone: 'Extramurs',
    location: { latitude: 39.461900, longitude: -0.382300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Extramurs.',
  },
  {
    id: 'node-val-6-1',
    name: 'Eixample Valencia Sector 1 High Street',
    zone: 'Eixample Valencia',
    location: { latitude: 39.467900, longitude: -0.378300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Eixample Valencia.',
  },
  {
    id: 'node-val-6-2',
    name: 'Eixample Valencia Sector 2 High Street',
    zone: 'Eixample Valencia',
    location: { latitude: 39.470900, longitude: -0.375300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Eixample Valencia.',
  },
  {
    id: 'node-val-6-3',
    name: 'Eixample Valencia Sector 3 High Street',
    zone: 'Eixample Valencia',
    location: { latitude: 39.473900, longitude: -0.372300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Eixample Valencia.',
  },
  {
    id: 'node-val-7-1',
    name: 'Mestalla Sector 1 High Street',
    zone: 'Mestalla',
    location: { latitude: 39.479900, longitude: -0.368300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mestalla.',
  },
  {
    id: 'node-val-7-2',
    name: 'Mestalla Sector 2 High Street',
    zone: 'Mestalla',
    location: { latitude: 39.482900, longitude: -0.365300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mestalla.',
  },
  {
    id: 'node-val-7-3',
    name: 'Mestalla Sector 3 High Street',
    zone: 'Mestalla',
    location: { latitude: 39.485900, longitude: -0.362300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mestalla.',
  },
  {
    id: 'node-val-8-1',
    name: 'Campanar Sector 1 High Street',
    zone: 'Campanar',
    location: { latitude: 39.491900, longitude: -0.358300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Campanar.',
  },
  {
    id: 'node-val-8-2',
    name: 'Campanar Sector 2 High Street',
    zone: 'Campanar',
    location: { latitude: 39.494900, longitude: -0.355300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Campanar.',
  },
  {
    id: 'node-val-8-3',
    name: 'Campanar Sector 3 High Street',
    zone: 'Campanar',
    location: { latitude: 39.497900, longitude: -0.352300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Campanar.',
  },
  {
    id: 'node-val-9-1',
    name: 'Benimaclet Sector 1 High Street',
    zone: 'Benimaclet',
    location: { latitude: 39.503900, longitude: -0.348300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Benimaclet.',
  },
  {
    id: 'node-val-9-2',
    name: 'Benimaclet Sector 2 High Street',
    zone: 'Benimaclet',
    location: { latitude: 39.506900, longitude: -0.345300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Benimaclet.',
  },
  {
    id: 'node-val-9-3',
    name: 'Benimaclet Sector 3 High Street',
    zone: 'Benimaclet',
    location: { latitude: 39.509900, longitude: -0.342300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Benimaclet.',
  },
  {
    id: 'node-val-10-1',
    name: 'Poblats Maritims Sector 1 High Street',
    zone: 'Poblats Maritims',
    location: { latitude: 39.515900, longitude: -0.338300 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Poblats Maritims.',
  },
  {
    id: 'node-val-10-2',
    name: 'Poblats Maritims Sector 2 High Street',
    zone: 'Poblats Maritims',
    location: { latitude: 39.518900, longitude: -0.335300 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Poblats Maritims.',
  },
  {
    id: 'node-val-10-3',
    name: 'Poblats Maritims Sector 3 High Street',
    zone: 'Poblats Maritims',
    location: { latitude: 39.521900, longitude: -0.332300 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Poblats Maritims.',
  },
];

export const VALENCIA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-val-1',
    fromNodeId: 'node-val-1-1',
    toNodeId: 'node-val-1-2',
    roadName: 'Ciutat Vella Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-2',
    fromNodeId: 'node-val-1-2',
    toNodeId: 'node-val-1-3',
    roadName: 'Ciutat Vella Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-3',
    fromNodeId: 'node-val-2-1',
    toNodeId: 'node-val-2-2',
    roadName: 'Ruzafa Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-4',
    fromNodeId: 'node-val-2-2',
    toNodeId: 'node-val-2-3',
    roadName: 'Ruzafa Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-5',
    fromNodeId: 'node-val-3-1',
    toNodeId: 'node-val-3-2',
    roadName: 'El Carmen Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-6',
    fromNodeId: 'node-val-3-2',
    toNodeId: 'node-val-3-3',
    roadName: 'El Carmen Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-7',
    fromNodeId: 'node-val-4-1',
    toNodeId: 'node-val-4-2',
    roadName: 'El Cabanyal Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-8',
    fromNodeId: 'node-val-4-2',
    toNodeId: 'node-val-4-3',
    roadName: 'El Cabanyal Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-9',
    fromNodeId: 'node-val-5-1',
    toNodeId: 'node-val-5-2',
    roadName: 'Extramurs Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-10',
    fromNodeId: 'node-val-5-2',
    toNodeId: 'node-val-5-3',
    roadName: 'Extramurs Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-11',
    fromNodeId: 'node-val-6-1',
    toNodeId: 'node-val-6-2',
    roadName: 'Eixample Valencia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-12',
    fromNodeId: 'node-val-6-2',
    toNodeId: 'node-val-6-3',
    roadName: 'Eixample Valencia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-13',
    fromNodeId: 'node-val-7-1',
    toNodeId: 'node-val-7-2',
    roadName: 'Mestalla Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-14',
    fromNodeId: 'node-val-7-2',
    toNodeId: 'node-val-7-3',
    roadName: 'Mestalla Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-15',
    fromNodeId: 'node-val-8-1',
    toNodeId: 'node-val-8-2',
    roadName: 'Campanar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-16',
    fromNodeId: 'node-val-8-2',
    toNodeId: 'node-val-8-3',
    roadName: 'Campanar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-17',
    fromNodeId: 'node-val-9-1',
    toNodeId: 'node-val-9-2',
    roadName: 'Benimaclet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-18',
    fromNodeId: 'node-val-9-2',
    toNodeId: 'node-val-9-3',
    roadName: 'Benimaclet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-19',
    fromNodeId: 'node-val-10-1',
    toNodeId: 'node-val-10-2',
    roadName: 'Poblats Maritims Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-val-20',
    fromNodeId: 'node-val-10-2',
    toNodeId: 'node-val-10-3',
    roadName: 'Poblats Maritims Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
