/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Vancouver Coastal Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const VANCOUVER_BASE_COORDINATE: GeoCoordinate = {
  latitude: 49.2827,
  longitude: -123.1207,
};

export const VANCOUVER_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-van-1-1',
    name: 'Downtown Vancouver Sector 1 High Street',
    zone: 'Downtown Vancouver',
    location: { latitude: 49.220700, longitude: -123.172700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Downtown Vancouver.',
  },
  {
    id: 'node-van-1-2',
    name: 'Downtown Vancouver Sector 2 High Street',
    zone: 'Downtown Vancouver',
    location: { latitude: 49.223700, longitude: -123.169700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Downtown Vancouver.',
  },
  {
    id: 'node-van-1-3',
    name: 'Downtown Vancouver Sector 3 High Street',
    zone: 'Downtown Vancouver',
    location: { latitude: 49.226700, longitude: -123.166700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Downtown Vancouver.',
  },
  {
    id: 'node-van-2-1',
    name: 'Yaletown Sector 1 High Street',
    zone: 'Yaletown',
    location: { latitude: 49.232700, longitude: -123.162700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Yaletown.',
  },
  {
    id: 'node-van-2-2',
    name: 'Yaletown Sector 2 High Street',
    zone: 'Yaletown',
    location: { latitude: 49.235700, longitude: -123.159700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Yaletown.',
  },
  {
    id: 'node-van-2-3',
    name: 'Yaletown Sector 3 High Street',
    zone: 'Yaletown',
    location: { latitude: 49.238700, longitude: -123.156700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Yaletown.',
  },
  {
    id: 'node-van-3-1',
    name: 'Gastown Sector 1 High Street',
    zone: 'Gastown',
    location: { latitude: 49.244700, longitude: -123.152700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gastown.',
  },
  {
    id: 'node-van-3-2',
    name: 'Gastown Sector 2 High Street',
    zone: 'Gastown',
    location: { latitude: 49.247700, longitude: -123.149700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gastown.',
  },
  {
    id: 'node-van-3-3',
    name: 'Gastown Sector 3 High Street',
    zone: 'Gastown',
    location: { latitude: 49.250700, longitude: -123.146700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gastown.',
  },
  {
    id: 'node-van-4-1',
    name: 'Kitsilano Sector 1 High Street',
    zone: 'Kitsilano',
    location: { latitude: 49.256700, longitude: -123.142700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kitsilano.',
  },
  {
    id: 'node-van-4-2',
    name: 'Kitsilano Sector 2 High Street',
    zone: 'Kitsilano',
    location: { latitude: 49.259700, longitude: -123.139700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kitsilano.',
  },
  {
    id: 'node-van-4-3',
    name: 'Kitsilano Sector 3 High Street',
    zone: 'Kitsilano',
    location: { latitude: 49.262700, longitude: -123.136700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kitsilano.',
  },
  {
    id: 'node-van-5-1',
    name: 'West End Sector 1 High Street',
    zone: 'West End',
    location: { latitude: 49.268700, longitude: -123.132700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in West End.',
  },
  {
    id: 'node-van-5-2',
    name: 'West End Sector 2 High Street',
    zone: 'West End',
    location: { latitude: 49.271700, longitude: -123.129700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in West End.',
  },
  {
    id: 'node-van-5-3',
    name: 'West End Sector 3 High Street',
    zone: 'West End',
    location: { latitude: 49.274700, longitude: -123.126700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in West End.',
  },
  {
    id: 'node-van-6-1',
    name: 'Mount Pleasant Sector 1 High Street',
    zone: 'Mount Pleasant',
    location: { latitude: 49.280700, longitude: -123.122700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mount Pleasant.',
  },
  {
    id: 'node-van-6-2',
    name: 'Mount Pleasant Sector 2 High Street',
    zone: 'Mount Pleasant',
    location: { latitude: 49.283700, longitude: -123.119700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mount Pleasant.',
  },
  {
    id: 'node-van-6-3',
    name: 'Mount Pleasant Sector 3 High Street',
    zone: 'Mount Pleasant',
    location: { latitude: 49.286700, longitude: -123.116700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mount Pleasant.',
  },
  {
    id: 'node-van-7-1',
    name: 'Commercial Drive Sector 1 High Street',
    zone: 'Commercial Drive',
    location: { latitude: 49.292700, longitude: -123.112700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Commercial Drive.',
  },
  {
    id: 'node-van-7-2',
    name: 'Commercial Drive Sector 2 High Street',
    zone: 'Commercial Drive',
    location: { latitude: 49.295700, longitude: -123.109700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Commercial Drive.',
  },
  {
    id: 'node-van-7-3',
    name: 'Commercial Drive Sector 3 High Street',
    zone: 'Commercial Drive',
    location: { latitude: 49.298700, longitude: -123.106700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Commercial Drive.',
  },
  {
    id: 'node-van-8-1',
    name: 'Coal Harbour Sector 1 High Street',
    zone: 'Coal Harbour',
    location: { latitude: 49.304700, longitude: -123.102700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Coal Harbour.',
  },
  {
    id: 'node-van-8-2',
    name: 'Coal Harbour Sector 2 High Street',
    zone: 'Coal Harbour',
    location: { latitude: 49.307700, longitude: -123.099700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Coal Harbour.',
  },
  {
    id: 'node-van-8-3',
    name: 'Coal Harbour Sector 3 High Street',
    zone: 'Coal Harbour',
    location: { latitude: 49.310700, longitude: -123.096700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Coal Harbour.',
  },
  {
    id: 'node-van-9-1',
    name: 'Richmond BC Sector 1 High Street',
    zone: 'Richmond BC',
    location: { latitude: 49.316700, longitude: -123.092700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Richmond BC.',
  },
  {
    id: 'node-van-9-2',
    name: 'Richmond BC Sector 2 High Street',
    zone: 'Richmond BC',
    location: { latitude: 49.319700, longitude: -123.089700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Richmond BC.',
  },
  {
    id: 'node-van-9-3',
    name: 'Richmond BC Sector 3 High Street',
    zone: 'Richmond BC',
    location: { latitude: 49.322700, longitude: -123.086700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Richmond BC.',
  },
  {
    id: 'node-van-10-1',
    name: 'Burnaby Sector 1 High Street',
    zone: 'Burnaby',
    location: { latitude: 49.328700, longitude: -123.082700 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Burnaby.',
  },
  {
    id: 'node-van-10-2',
    name: 'Burnaby Sector 2 High Street',
    zone: 'Burnaby',
    location: { latitude: 49.331700, longitude: -123.079700 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Burnaby.',
  },
  {
    id: 'node-van-10-3',
    name: 'Burnaby Sector 3 High Street',
    zone: 'Burnaby',
    location: { latitude: 49.334700, longitude: -123.076700 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Burnaby.',
  },
];

export const VANCOUVER_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-van-1',
    fromNodeId: 'node-van-1-1',
    toNodeId: 'node-van-1-2',
    roadName: 'Downtown Vancouver Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-2',
    fromNodeId: 'node-van-1-2',
    toNodeId: 'node-van-1-3',
    roadName: 'Downtown Vancouver Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-3',
    fromNodeId: 'node-van-2-1',
    toNodeId: 'node-van-2-2',
    roadName: 'Yaletown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-4',
    fromNodeId: 'node-van-2-2',
    toNodeId: 'node-van-2-3',
    roadName: 'Yaletown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-5',
    fromNodeId: 'node-van-3-1',
    toNodeId: 'node-van-3-2',
    roadName: 'Gastown Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-6',
    fromNodeId: 'node-van-3-2',
    toNodeId: 'node-van-3-3',
    roadName: 'Gastown Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-7',
    fromNodeId: 'node-van-4-1',
    toNodeId: 'node-van-4-2',
    roadName: 'Kitsilano Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-8',
    fromNodeId: 'node-van-4-2',
    toNodeId: 'node-van-4-3',
    roadName: 'Kitsilano Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-9',
    fromNodeId: 'node-van-5-1',
    toNodeId: 'node-van-5-2',
    roadName: 'West End Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-10',
    fromNodeId: 'node-van-5-2',
    toNodeId: 'node-van-5-3',
    roadName: 'West End Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-11',
    fromNodeId: 'node-van-6-1',
    toNodeId: 'node-van-6-2',
    roadName: 'Mount Pleasant Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-12',
    fromNodeId: 'node-van-6-2',
    toNodeId: 'node-van-6-3',
    roadName: 'Mount Pleasant Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-13',
    fromNodeId: 'node-van-7-1',
    toNodeId: 'node-van-7-2',
    roadName: 'Commercial Drive Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-14',
    fromNodeId: 'node-van-7-2',
    toNodeId: 'node-van-7-3',
    roadName: 'Commercial Drive Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-15',
    fromNodeId: 'node-van-8-1',
    toNodeId: 'node-van-8-2',
    roadName: 'Coal Harbour Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-16',
    fromNodeId: 'node-van-8-2',
    toNodeId: 'node-van-8-3',
    roadName: 'Coal Harbour Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-17',
    fromNodeId: 'node-van-9-1',
    toNodeId: 'node-van-9-2',
    roadName: 'Richmond BC Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-18',
    fromNodeId: 'node-van-9-2',
    toNodeId: 'node-van-9-3',
    roadName: 'Richmond BC Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-19',
    fromNodeId: 'node-van-10-1',
    toNodeId: 'node-van-10-2',
    roadName: 'Burnaby Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-van-20',
    fromNodeId: 'node-van-10-2',
    toNodeId: 'node-van-10-3',
    roadName: 'Burnaby Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
