/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Varanasi Kashi Ghats & City
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const VARANASI_BASE_COORDINATE: GeoCoordinate = {
  latitude: 25.3176,
  longitude: 82.9739,
};

export const VARANASI_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-var-1-1',
    name: 'Assi Ghat Sector 1 High Street',
    zone: 'Assi Ghat',
    location: { latitude: 25.255600, longitude: 82.921900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Assi Ghat.',
  },
  {
    id: 'node-var-1-2',
    name: 'Assi Ghat Sector 2 High Street',
    zone: 'Assi Ghat',
    location: { latitude: 25.258600, longitude: 82.924900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Assi Ghat.',
  },
  {
    id: 'node-var-1-3',
    name: 'Assi Ghat Sector 3 High Street',
    zone: 'Assi Ghat',
    location: { latitude: 25.261600, longitude: 82.927900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Assi Ghat.',
  },
  {
    id: 'node-var-2-1',
    name: 'Lanka Sector 1 High Street',
    zone: 'Lanka',
    location: { latitude: 25.267600, longitude: 82.931900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lanka.',
  },
  {
    id: 'node-var-2-2',
    name: 'Lanka Sector 2 High Street',
    zone: 'Lanka',
    location: { latitude: 25.270600, longitude: 82.934900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lanka.',
  },
  {
    id: 'node-var-2-3',
    name: 'Lanka Sector 3 High Street',
    zone: 'Lanka',
    location: { latitude: 25.273600, longitude: 82.937900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lanka.',
  },
  {
    id: 'node-var-3-1',
    name: 'Godowlia Sector 1 High Street',
    zone: 'Godowlia',
    location: { latitude: 25.279600, longitude: 82.941900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Godowlia.',
  },
  {
    id: 'node-var-3-2',
    name: 'Godowlia Sector 2 High Street',
    zone: 'Godowlia',
    location: { latitude: 25.282600, longitude: 82.944900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Godowlia.',
  },
  {
    id: 'node-var-3-3',
    name: 'Godowlia Sector 3 High Street',
    zone: 'Godowlia',
    location: { latitude: 25.285600, longitude: 82.947900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Godowlia.',
  },
  {
    id: 'node-var-4-1',
    name: 'Cantonment Sector 1 High Street',
    zone: 'Cantonment',
    location: { latitude: 25.291600, longitude: 82.951900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cantonment.',
  },
  {
    id: 'node-var-4-2',
    name: 'Cantonment Sector 2 High Street',
    zone: 'Cantonment',
    location: { latitude: 25.294600, longitude: 82.954900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cantonment.',
  },
  {
    id: 'node-var-4-3',
    name: 'Cantonment Sector 3 High Street',
    zone: 'Cantonment',
    location: { latitude: 25.297600, longitude: 82.957900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cantonment.',
  },
  {
    id: 'node-var-5-1',
    name: 'Sigra Sector 1 High Street',
    zone: 'Sigra',
    location: { latitude: 25.303600, longitude: 82.961900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sigra.',
  },
  {
    id: 'node-var-5-2',
    name: 'Sigra Sector 2 High Street',
    zone: 'Sigra',
    location: { latitude: 25.306600, longitude: 82.964900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sigra.',
  },
  {
    id: 'node-var-5-3',
    name: 'Sigra Sector 3 High Street',
    zone: 'Sigra',
    location: { latitude: 25.309600, longitude: 82.967900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sigra.',
  },
  {
    id: 'node-var-6-1',
    name: 'Bhelupur Sector 1 High Street',
    zone: 'Bhelupur',
    location: { latitude: 25.315600, longitude: 82.971900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bhelupur.',
  },
  {
    id: 'node-var-6-2',
    name: 'Bhelupur Sector 2 High Street',
    zone: 'Bhelupur',
    location: { latitude: 25.318600, longitude: 82.974900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bhelupur.',
  },
  {
    id: 'node-var-6-3',
    name: 'Bhelupur Sector 3 High Street',
    zone: 'Bhelupur',
    location: { latitude: 25.321600, longitude: 82.977900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bhelupur.',
  },
  {
    id: 'node-var-7-1',
    name: 'Mahmoorganj Sector 1 High Street',
    zone: 'Mahmoorganj',
    location: { latitude: 25.327600, longitude: 82.981900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mahmoorganj.',
  },
  {
    id: 'node-var-7-2',
    name: 'Mahmoorganj Sector 2 High Street',
    zone: 'Mahmoorganj',
    location: { latitude: 25.330600, longitude: 82.984900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mahmoorganj.',
  },
  {
    id: 'node-var-7-3',
    name: 'Mahmoorganj Sector 3 High Street',
    zone: 'Mahmoorganj',
    location: { latitude: 25.333600, longitude: 82.987900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mahmoorganj.',
  },
  {
    id: 'node-var-8-1',
    name: 'Shivpur Sector 1 High Street',
    zone: 'Shivpur',
    location: { latitude: 25.339600, longitude: 82.991900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Shivpur.',
  },
  {
    id: 'node-var-8-2',
    name: 'Shivpur Sector 2 High Street',
    zone: 'Shivpur',
    location: { latitude: 25.342600, longitude: 82.994900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Shivpur.',
  },
  {
    id: 'node-var-8-3',
    name: 'Shivpur Sector 3 High Street',
    zone: 'Shivpur',
    location: { latitude: 25.345600, longitude: 82.997900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Shivpur.',
  },
  {
    id: 'node-var-9-1',
    name: 'Pandeypur Sector 1 High Street',
    zone: 'Pandeypur',
    location: { latitude: 25.351600, longitude: 83.001900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pandeypur.',
  },
  {
    id: 'node-var-9-2',
    name: 'Pandeypur Sector 2 High Street',
    zone: 'Pandeypur',
    location: { latitude: 25.354600, longitude: 83.004900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pandeypur.',
  },
  {
    id: 'node-var-9-3',
    name: 'Pandeypur Sector 3 High Street',
    zone: 'Pandeypur',
    location: { latitude: 25.357600, longitude: 83.007900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pandeypur.',
  },
  {
    id: 'node-var-10-1',
    name: 'Sarnath Gateway Sector 1 High Street',
    zone: 'Sarnath Gateway',
    location: { latitude: 25.363600, longitude: 83.011900 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Sarnath Gateway.',
  },
  {
    id: 'node-var-10-2',
    name: 'Sarnath Gateway Sector 2 High Street',
    zone: 'Sarnath Gateway',
    location: { latitude: 25.366600, longitude: 83.014900 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Sarnath Gateway.',
  },
  {
    id: 'node-var-10-3',
    name: 'Sarnath Gateway Sector 3 High Street',
    zone: 'Sarnath Gateway',
    location: { latitude: 25.369600, longitude: 83.017900 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Sarnath Gateway.',
  },
];

export const VARANASI_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-var-1',
    fromNodeId: 'node-var-1-1',
    toNodeId: 'node-var-1-2',
    roadName: 'Assi Ghat Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-2',
    fromNodeId: 'node-var-1-2',
    toNodeId: 'node-var-1-3',
    roadName: 'Assi Ghat Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-3',
    fromNodeId: 'node-var-2-1',
    toNodeId: 'node-var-2-2',
    roadName: 'Lanka Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-4',
    fromNodeId: 'node-var-2-2',
    toNodeId: 'node-var-2-3',
    roadName: 'Lanka Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-5',
    fromNodeId: 'node-var-3-1',
    toNodeId: 'node-var-3-2',
    roadName: 'Godowlia Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-6',
    fromNodeId: 'node-var-3-2',
    toNodeId: 'node-var-3-3',
    roadName: 'Godowlia Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-7',
    fromNodeId: 'node-var-4-1',
    toNodeId: 'node-var-4-2',
    roadName: 'Cantonment Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-8',
    fromNodeId: 'node-var-4-2',
    toNodeId: 'node-var-4-3',
    roadName: 'Cantonment Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-9',
    fromNodeId: 'node-var-5-1',
    toNodeId: 'node-var-5-2',
    roadName: 'Sigra Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-10',
    fromNodeId: 'node-var-5-2',
    toNodeId: 'node-var-5-3',
    roadName: 'Sigra Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-11',
    fromNodeId: 'node-var-6-1',
    toNodeId: 'node-var-6-2',
    roadName: 'Bhelupur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-12',
    fromNodeId: 'node-var-6-2',
    toNodeId: 'node-var-6-3',
    roadName: 'Bhelupur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-13',
    fromNodeId: 'node-var-7-1',
    toNodeId: 'node-var-7-2',
    roadName: 'Mahmoorganj Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-14',
    fromNodeId: 'node-var-7-2',
    toNodeId: 'node-var-7-3',
    roadName: 'Mahmoorganj Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-15',
    fromNodeId: 'node-var-8-1',
    toNodeId: 'node-var-8-2',
    roadName: 'Shivpur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-16',
    fromNodeId: 'node-var-8-2',
    toNodeId: 'node-var-8-3',
    roadName: 'Shivpur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-17',
    fromNodeId: 'node-var-9-1',
    toNodeId: 'node-var-9-2',
    roadName: 'Pandeypur Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-18',
    fromNodeId: 'node-var-9-2',
    toNodeId: 'node-var-9-3',
    roadName: 'Pandeypur Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-19',
    fromNodeId: 'node-var-10-1',
    toNodeId: 'node-var-10-2',
    roadName: 'Sarnath Gateway Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-var-20',
    fromNodeId: 'node-var-10-2',
    toNodeId: 'node-var-10-3',
    roadName: 'Sarnath Gateway Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
