/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Venice Lagoon & Mestre
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const VENICE_BASE_COORDINATE: GeoCoordinate = {
  latitude: 45.4408,
  longitude: 12.3155,
};

export const VENICE_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-ven-1-1',
    name: 'San Marco Venice Sector 1 High Street',
    zone: 'San Marco Venice',
    location: { latitude: 45.378800, longitude: 12.263500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Marco Venice.',
  },
  {
    id: 'node-ven-1-2',
    name: 'San Marco Venice Sector 2 High Street',
    zone: 'San Marco Venice',
    location: { latitude: 45.381800, longitude: 12.266500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Marco Venice.',
  },
  {
    id: 'node-ven-1-3',
    name: 'San Marco Venice Sector 3 High Street',
    zone: 'San Marco Venice',
    location: { latitude: 45.384800, longitude: 12.269500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Marco Venice.',
  },
  {
    id: 'node-ven-2-1',
    name: 'Cannaregio Sector 1 High Street',
    zone: 'Cannaregio',
    location: { latitude: 45.390800, longitude: 12.273500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Cannaregio.',
  },
  {
    id: 'node-ven-2-2',
    name: 'Cannaregio Sector 2 High Street',
    zone: 'Cannaregio',
    location: { latitude: 45.393800, longitude: 12.276500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Cannaregio.',
  },
  {
    id: 'node-ven-2-3',
    name: 'Cannaregio Sector 3 High Street',
    zone: 'Cannaregio',
    location: { latitude: 45.396800, longitude: 12.279500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Cannaregio.',
  },
  {
    id: 'node-ven-3-1',
    name: 'Dorsoduro Sector 1 High Street',
    zone: 'Dorsoduro',
    location: { latitude: 45.402800, longitude: 12.283500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dorsoduro.',
  },
  {
    id: 'node-ven-3-2',
    name: 'Dorsoduro Sector 2 High Street',
    zone: 'Dorsoduro',
    location: { latitude: 45.405800, longitude: 12.286500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dorsoduro.',
  },
  {
    id: 'node-ven-3-3',
    name: 'Dorsoduro Sector 3 High Street',
    zone: 'Dorsoduro',
    location: { latitude: 45.408800, longitude: 12.289500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dorsoduro.',
  },
  {
    id: 'node-ven-4-1',
    name: 'San Polo Sector 1 High Street',
    zone: 'San Polo',
    location: { latitude: 45.414800, longitude: 12.293500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in San Polo.',
  },
  {
    id: 'node-ven-4-2',
    name: 'San Polo Sector 2 High Street',
    zone: 'San Polo',
    location: { latitude: 45.417800, longitude: 12.296500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in San Polo.',
  },
  {
    id: 'node-ven-4-3',
    name: 'San Polo Sector 3 High Street',
    zone: 'San Polo',
    location: { latitude: 45.420800, longitude: 12.299500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in San Polo.',
  },
  {
    id: 'node-ven-5-1',
    name: 'Castello Sector 1 High Street',
    zone: 'Castello',
    location: { latitude: 45.426800, longitude: 12.303500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Castello.',
  },
  {
    id: 'node-ven-5-2',
    name: 'Castello Sector 2 High Street',
    zone: 'Castello',
    location: { latitude: 45.429800, longitude: 12.306500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Castello.',
  },
  {
    id: 'node-ven-5-3',
    name: 'Castello Sector 3 High Street',
    zone: 'Castello',
    location: { latitude: 45.432800, longitude: 12.309500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Castello.',
  },
  {
    id: 'node-ven-6-1',
    name: 'Santa Croce Venice Sector 1 High Street',
    zone: 'Santa Croce Venice',
    location: { latitude: 45.438800, longitude: 12.313500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Santa Croce Venice.',
  },
  {
    id: 'node-ven-6-2',
    name: 'Santa Croce Venice Sector 2 High Street',
    zone: 'Santa Croce Venice',
    location: { latitude: 45.441800, longitude: 12.316500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Santa Croce Venice.',
  },
  {
    id: 'node-ven-6-3',
    name: 'Santa Croce Venice Sector 3 High Street',
    zone: 'Santa Croce Venice',
    location: { latitude: 45.444800, longitude: 12.319500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Santa Croce Venice.',
  },
  {
    id: 'node-ven-7-1',
    name: 'Giudecca Sector 1 High Street',
    zone: 'Giudecca',
    location: { latitude: 45.450800, longitude: 12.323500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Giudecca.',
  },
  {
    id: 'node-ven-7-2',
    name: 'Giudecca Sector 2 High Street',
    zone: 'Giudecca',
    location: { latitude: 45.453800, longitude: 12.326500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Giudecca.',
  },
  {
    id: 'node-ven-7-3',
    name: 'Giudecca Sector 3 High Street',
    zone: 'Giudecca',
    location: { latitude: 45.456800, longitude: 12.329500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Giudecca.',
  },
  {
    id: 'node-ven-8-1',
    name: 'Mestre Central Sector 1 High Street',
    zone: 'Mestre Central',
    location: { latitude: 45.462800, longitude: 12.333500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mestre Central.',
  },
  {
    id: 'node-ven-8-2',
    name: 'Mestre Central Sector 2 High Street',
    zone: 'Mestre Central',
    location: { latitude: 45.465800, longitude: 12.336500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mestre Central.',
  },
  {
    id: 'node-ven-8-3',
    name: 'Mestre Central Sector 3 High Street',
    zone: 'Mestre Central',
    location: { latitude: 45.468800, longitude: 12.339500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mestre Central.',
  },
  {
    id: 'node-ven-9-1',
    name: 'Marghera Sector 1 High Street',
    zone: 'Marghera',
    location: { latitude: 45.474800, longitude: 12.343500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Marghera.',
  },
  {
    id: 'node-ven-9-2',
    name: 'Marghera Sector 2 High Street',
    zone: 'Marghera',
    location: { latitude: 45.477800, longitude: 12.346500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Marghera.',
  },
  {
    id: 'node-ven-9-3',
    name: 'Marghera Sector 3 High Street',
    zone: 'Marghera',
    location: { latitude: 45.480800, longitude: 12.349500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Marghera.',
  },
  {
    id: 'node-ven-10-1',
    name: 'Lido Venice Sector 1 High Street',
    zone: 'Lido Venice',
    location: { latitude: 45.486800, longitude: 12.353500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Lido Venice.',
  },
  {
    id: 'node-ven-10-2',
    name: 'Lido Venice Sector 2 High Street',
    zone: 'Lido Venice',
    location: { latitude: 45.489800, longitude: 12.356500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Lido Venice.',
  },
  {
    id: 'node-ven-10-3',
    name: 'Lido Venice Sector 3 High Street',
    zone: 'Lido Venice',
    location: { latitude: 45.492800, longitude: 12.359500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Lido Venice.',
  },
];

export const VENICE_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-ven-1',
    fromNodeId: 'node-ven-1-1',
    toNodeId: 'node-ven-1-2',
    roadName: 'San Marco Venice Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-2',
    fromNodeId: 'node-ven-1-2',
    toNodeId: 'node-ven-1-3',
    roadName: 'San Marco Venice Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-3',
    fromNodeId: 'node-ven-2-1',
    toNodeId: 'node-ven-2-2',
    roadName: 'Cannaregio Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-4',
    fromNodeId: 'node-ven-2-2',
    toNodeId: 'node-ven-2-3',
    roadName: 'Cannaregio Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-5',
    fromNodeId: 'node-ven-3-1',
    toNodeId: 'node-ven-3-2',
    roadName: 'Dorsoduro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-6',
    fromNodeId: 'node-ven-3-2',
    toNodeId: 'node-ven-3-3',
    roadName: 'Dorsoduro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-7',
    fromNodeId: 'node-ven-4-1',
    toNodeId: 'node-ven-4-2',
    roadName: 'San Polo Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-8',
    fromNodeId: 'node-ven-4-2',
    toNodeId: 'node-ven-4-3',
    roadName: 'San Polo Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-9',
    fromNodeId: 'node-ven-5-1',
    toNodeId: 'node-ven-5-2',
    roadName: 'Castello Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-10',
    fromNodeId: 'node-ven-5-2',
    toNodeId: 'node-ven-5-3',
    roadName: 'Castello Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-11',
    fromNodeId: 'node-ven-6-1',
    toNodeId: 'node-ven-6-2',
    roadName: 'Santa Croce Venice Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-12',
    fromNodeId: 'node-ven-6-2',
    toNodeId: 'node-ven-6-3',
    roadName: 'Santa Croce Venice Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-13',
    fromNodeId: 'node-ven-7-1',
    toNodeId: 'node-ven-7-2',
    roadName: 'Giudecca Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-14',
    fromNodeId: 'node-ven-7-2',
    toNodeId: 'node-ven-7-3',
    roadName: 'Giudecca Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-15',
    fromNodeId: 'node-ven-8-1',
    toNodeId: 'node-ven-8-2',
    roadName: 'Mestre Central Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-16',
    fromNodeId: 'node-ven-8-2',
    toNodeId: 'node-ven-8-3',
    roadName: 'Mestre Central Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-17',
    fromNodeId: 'node-ven-9-1',
    toNodeId: 'node-ven-9-2',
    roadName: 'Marghera Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-18',
    fromNodeId: 'node-ven-9-2',
    toNodeId: 'node-ven-9-3',
    roadName: 'Marghera Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-19',
    fromNodeId: 'node-ven-10-1',
    toNodeId: 'node-ven-10-2',
    roadName: 'Lido Venice Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-ven-20',
    fromNodeId: 'node-ven-10-2',
    toNodeId: 'node-ven-10-3',
    roadName: 'Lido Venice Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
