/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Vienna Danube Capital
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const VIENNA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 48.2082,
  longitude: 16.3738,
};

export const VIENNA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-vie-1-1',
    name: 'Innere Stadt Sector 1 High Street',
    zone: 'Innere Stadt',
    location: { latitude: 48.146200, longitude: 16.321800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Innere Stadt.',
  },
  {
    id: 'node-vie-1-2',
    name: 'Innere Stadt Sector 2 High Street',
    zone: 'Innere Stadt',
    location: { latitude: 48.149200, longitude: 16.324800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Innere Stadt.',
  },
  {
    id: 'node-vie-1-3',
    name: 'Innere Stadt Sector 3 High Street',
    zone: 'Innere Stadt',
    location: { latitude: 48.152200, longitude: 16.327800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Innere Stadt.',
  },
  {
    id: 'node-vie-2-1',
    name: 'Leopoldstadt Sector 1 High Street',
    zone: 'Leopoldstadt',
    location: { latitude: 48.158200, longitude: 16.331800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Leopoldstadt.',
  },
  {
    id: 'node-vie-2-2',
    name: 'Leopoldstadt Sector 2 High Street',
    zone: 'Leopoldstadt',
    location: { latitude: 48.161200, longitude: 16.334800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Leopoldstadt.',
  },
  {
    id: 'node-vie-2-3',
    name: 'Leopoldstadt Sector 3 High Street',
    zone: 'Leopoldstadt',
    location: { latitude: 48.164200, longitude: 16.337800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Leopoldstadt.',
  },
  {
    id: 'node-vie-3-1',
    name: 'Neubau Sector 1 High Street',
    zone: 'Neubau',
    location: { latitude: 48.170200, longitude: 16.341800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Neubau.',
  },
  {
    id: 'node-vie-3-2',
    name: 'Neubau Sector 2 High Street',
    zone: 'Neubau',
    location: { latitude: 48.173200, longitude: 16.344800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Neubau.',
  },
  {
    id: 'node-vie-3-3',
    name: 'Neubau Sector 3 High Street',
    zone: 'Neubau',
    location: { latitude: 48.176200, longitude: 16.347800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Neubau.',
  },
  {
    id: 'node-vie-4-1',
    name: 'Mariahilf Sector 1 High Street',
    zone: 'Mariahilf',
    location: { latitude: 48.182200, longitude: 16.351800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mariahilf.',
  },
  {
    id: 'node-vie-4-2',
    name: 'Mariahilf Sector 2 High Street',
    zone: 'Mariahilf',
    location: { latitude: 48.185200, longitude: 16.354800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mariahilf.',
  },
  {
    id: 'node-vie-4-3',
    name: 'Mariahilf Sector 3 High Street',
    zone: 'Mariahilf',
    location: { latitude: 48.188200, longitude: 16.357800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mariahilf.',
  },
  {
    id: 'node-vie-5-1',
    name: 'Josefstadt Sector 1 High Street',
    zone: 'Josefstadt',
    location: { latitude: 48.194200, longitude: 16.361800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Josefstadt.',
  },
  {
    id: 'node-vie-5-2',
    name: 'Josefstadt Sector 2 High Street',
    zone: 'Josefstadt',
    location: { latitude: 48.197200, longitude: 16.364800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Josefstadt.',
  },
  {
    id: 'node-vie-5-3',
    name: 'Josefstadt Sector 3 High Street',
    zone: 'Josefstadt',
    location: { latitude: 48.200200, longitude: 16.367800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Josefstadt.',
  },
  {
    id: 'node-vie-6-1',
    name: 'Alsergrund Sector 1 High Street',
    zone: 'Alsergrund',
    location: { latitude: 48.206200, longitude: 16.371800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Alsergrund.',
  },
  {
    id: 'node-vie-6-2',
    name: 'Alsergrund Sector 2 High Street',
    zone: 'Alsergrund',
    location: { latitude: 48.209200, longitude: 16.374800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Alsergrund.',
  },
  {
    id: 'node-vie-6-3',
    name: 'Alsergrund Sector 3 High Street',
    zone: 'Alsergrund',
    location: { latitude: 48.212200, longitude: 16.377800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Alsergrund.',
  },
  {
    id: 'node-vie-7-1',
    name: 'Favoriten Sector 1 High Street',
    zone: 'Favoriten',
    location: { latitude: 48.218200, longitude: 16.381800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Favoriten.',
  },
  {
    id: 'node-vie-7-2',
    name: 'Favoriten Sector 2 High Street',
    zone: 'Favoriten',
    location: { latitude: 48.221200, longitude: 16.384800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Favoriten.',
  },
  {
    id: 'node-vie-7-3',
    name: 'Favoriten Sector 3 High Street',
    zone: 'Favoriten',
    location: { latitude: 48.224200, longitude: 16.387800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Favoriten.',
  },
  {
    id: 'node-vie-8-1',
    name: 'Döbling Sector 1 High Street',
    zone: 'Döbling',
    location: { latitude: 48.230200, longitude: 16.391800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Döbling.',
  },
  {
    id: 'node-vie-8-2',
    name: 'Döbling Sector 2 High Street',
    zone: 'Döbling',
    location: { latitude: 48.233200, longitude: 16.394800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Döbling.',
  },
  {
    id: 'node-vie-8-3',
    name: 'Döbling Sector 3 High Street',
    zone: 'Döbling',
    location: { latitude: 48.236200, longitude: 16.397800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Döbling.',
  },
  {
    id: 'node-vie-9-1',
    name: 'Hietzing Sector 1 High Street',
    zone: 'Hietzing',
    location: { latitude: 48.242200, longitude: 16.401800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hietzing.',
  },
  {
    id: 'node-vie-9-2',
    name: 'Hietzing Sector 2 High Street',
    zone: 'Hietzing',
    location: { latitude: 48.245200, longitude: 16.404800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hietzing.',
  },
  {
    id: 'node-vie-9-3',
    name: 'Hietzing Sector 3 High Street',
    zone: 'Hietzing',
    location: { latitude: 48.248200, longitude: 16.407800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hietzing.',
  },
  {
    id: 'node-vie-10-1',
    name: 'Wieden Sector 1 High Street',
    zone: 'Wieden',
    location: { latitude: 48.254200, longitude: 16.411800 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wieden.',
  },
  {
    id: 'node-vie-10-2',
    name: 'Wieden Sector 2 High Street',
    zone: 'Wieden',
    location: { latitude: 48.257200, longitude: 16.414800 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wieden.',
  },
  {
    id: 'node-vie-10-3',
    name: 'Wieden Sector 3 High Street',
    zone: 'Wieden',
    location: { latitude: 48.260200, longitude: 16.417800 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wieden.',
  },
];

export const VIENNA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-vie-1',
    fromNodeId: 'node-vie-1-1',
    toNodeId: 'node-vie-1-2',
    roadName: 'Innere Stadt Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-2',
    fromNodeId: 'node-vie-1-2',
    toNodeId: 'node-vie-1-3',
    roadName: 'Innere Stadt Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-3',
    fromNodeId: 'node-vie-2-1',
    toNodeId: 'node-vie-2-2',
    roadName: 'Leopoldstadt Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-4',
    fromNodeId: 'node-vie-2-2',
    toNodeId: 'node-vie-2-3',
    roadName: 'Leopoldstadt Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-5',
    fromNodeId: 'node-vie-3-1',
    toNodeId: 'node-vie-3-2',
    roadName: 'Neubau Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-6',
    fromNodeId: 'node-vie-3-2',
    toNodeId: 'node-vie-3-3',
    roadName: 'Neubau Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-7',
    fromNodeId: 'node-vie-4-1',
    toNodeId: 'node-vie-4-2',
    roadName: 'Mariahilf Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-8',
    fromNodeId: 'node-vie-4-2',
    toNodeId: 'node-vie-4-3',
    roadName: 'Mariahilf Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-9',
    fromNodeId: 'node-vie-5-1',
    toNodeId: 'node-vie-5-2',
    roadName: 'Josefstadt Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-10',
    fromNodeId: 'node-vie-5-2',
    toNodeId: 'node-vie-5-3',
    roadName: 'Josefstadt Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-11',
    fromNodeId: 'node-vie-6-1',
    toNodeId: 'node-vie-6-2',
    roadName: 'Alsergrund Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-12',
    fromNodeId: 'node-vie-6-2',
    toNodeId: 'node-vie-6-3',
    roadName: 'Alsergrund Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-13',
    fromNodeId: 'node-vie-7-1',
    toNodeId: 'node-vie-7-2',
    roadName: 'Favoriten Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-14',
    fromNodeId: 'node-vie-7-2',
    toNodeId: 'node-vie-7-3',
    roadName: 'Favoriten Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-15',
    fromNodeId: 'node-vie-8-1',
    toNodeId: 'node-vie-8-2',
    roadName: 'Döbling Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-16',
    fromNodeId: 'node-vie-8-2',
    toNodeId: 'node-vie-8-3',
    roadName: 'Döbling Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-17',
    fromNodeId: 'node-vie-9-1',
    toNodeId: 'node-vie-9-2',
    roadName: 'Hietzing Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-18',
    fromNodeId: 'node-vie-9-2',
    toNodeId: 'node-vie-9-3',
    roadName: 'Hietzing Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-19',
    fromNodeId: 'node-vie-10-1',
    toNodeId: 'node-vie-10-2',
    roadName: 'Wieden Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vie-20',
    fromNodeId: 'node-vie-10-2',
    toNodeId: 'node-vie-10-3',
    roadName: 'Wieden Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
