/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Vijayawada Amaravati Hub
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const VIJAYAWADA_BASE_COORDINATE: GeoCoordinate = {
  latitude: 16.5062,
  longitude: 80.648,
};

export const VIJAYAWADA_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-vij-1-1',
    name: 'MG Road Sector 1 High Street',
    zone: 'MG Road',
    location: { latitude: 16.444200, longitude: 80.596000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in MG Road.',
  },
  {
    id: 'node-vij-1-2',
    name: 'MG Road Sector 2 High Street',
    zone: 'MG Road',
    location: { latitude: 16.447200, longitude: 80.599000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in MG Road.',
  },
  {
    id: 'node-vij-1-3',
    name: 'MG Road Sector 3 High Street',
    zone: 'MG Road',
    location: { latitude: 16.450200, longitude: 80.602000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in MG Road.',
  },
  {
    id: 'node-vij-2-1',
    name: 'Benz Circle Sector 1 High Street',
    zone: 'Benz Circle',
    location: { latitude: 16.456200, longitude: 80.606000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Benz Circle.',
  },
  {
    id: 'node-vij-2-2',
    name: 'Benz Circle Sector 2 High Street',
    zone: 'Benz Circle',
    location: { latitude: 16.459200, longitude: 80.609000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Benz Circle.',
  },
  {
    id: 'node-vij-2-3',
    name: 'Benz Circle Sector 3 High Street',
    zone: 'Benz Circle',
    location: { latitude: 16.462200, longitude: 80.612000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Benz Circle.',
  },
  {
    id: 'node-vij-3-1',
    name: 'Governorpet Sector 1 High Street',
    zone: 'Governorpet',
    location: { latitude: 16.468200, longitude: 80.616000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Governorpet.',
  },
  {
    id: 'node-vij-3-2',
    name: 'Governorpet Sector 2 High Street',
    zone: 'Governorpet',
    location: { latitude: 16.471200, longitude: 80.619000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Governorpet.',
  },
  {
    id: 'node-vij-3-3',
    name: 'Governorpet Sector 3 High Street',
    zone: 'Governorpet',
    location: { latitude: 16.474200, longitude: 80.622000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Governorpet.',
  },
  {
    id: 'node-vij-4-1',
    name: 'Suryaraopet Sector 1 High Street',
    zone: 'Suryaraopet',
    location: { latitude: 16.480200, longitude: 80.626000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Suryaraopet.',
  },
  {
    id: 'node-vij-4-2',
    name: 'Suryaraopet Sector 2 High Street',
    zone: 'Suryaraopet',
    location: { latitude: 16.483200, longitude: 80.629000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Suryaraopet.',
  },
  {
    id: 'node-vij-4-3',
    name: 'Suryaraopet Sector 3 High Street',
    zone: 'Suryaraopet',
    location: { latitude: 16.486200, longitude: 80.632000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Suryaraopet.',
  },
  {
    id: 'node-vij-5-1',
    name: 'Auto Nagar Sector 1 High Street',
    zone: 'Auto Nagar',
    location: { latitude: 16.492200, longitude: 80.636000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Auto Nagar.',
  },
  {
    id: 'node-vij-5-2',
    name: 'Auto Nagar Sector 2 High Street',
    zone: 'Auto Nagar',
    location: { latitude: 16.495200, longitude: 80.639000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Auto Nagar.',
  },
  {
    id: 'node-vij-5-3',
    name: 'Auto Nagar Sector 3 High Street',
    zone: 'Auto Nagar',
    location: { latitude: 16.498200, longitude: 80.642000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Auto Nagar.',
  },
  {
    id: 'node-vij-6-1',
    name: 'Bhavanipuram Sector 1 High Street',
    zone: 'Bhavanipuram',
    location: { latitude: 16.504200, longitude: 80.646000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bhavanipuram.',
  },
  {
    id: 'node-vij-6-2',
    name: 'Bhavanipuram Sector 2 High Street',
    zone: 'Bhavanipuram',
    location: { latitude: 16.507200, longitude: 80.649000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bhavanipuram.',
  },
  {
    id: 'node-vij-6-3',
    name: 'Bhavanipuram Sector 3 High Street',
    zone: 'Bhavanipuram',
    location: { latitude: 16.510200, longitude: 80.652000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bhavanipuram.',
  },
  {
    id: 'node-vij-7-1',
    name: 'Labbipet Sector 1 High Street',
    zone: 'Labbipet',
    location: { latitude: 16.516200, longitude: 80.656000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Labbipet.',
  },
  {
    id: 'node-vij-7-2',
    name: 'Labbipet Sector 2 High Street',
    zone: 'Labbipet',
    location: { latitude: 16.519200, longitude: 80.659000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Labbipet.',
  },
  {
    id: 'node-vij-7-3',
    name: 'Labbipet Sector 3 High Street',
    zone: 'Labbipet',
    location: { latitude: 16.522200, longitude: 80.662000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Labbipet.',
  },
  {
    id: 'node-vij-8-1',
    name: 'Gollapudi Sector 1 High Street',
    zone: 'Gollapudi',
    location: { latitude: 16.528200, longitude: 80.666000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gollapudi.',
  },
  {
    id: 'node-vij-8-2',
    name: 'Gollapudi Sector 2 High Street',
    zone: 'Gollapudi',
    location: { latitude: 16.531200, longitude: 80.669000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gollapudi.',
  },
  {
    id: 'node-vij-8-3',
    name: 'Gollapudi Sector 3 High Street',
    zone: 'Gollapudi',
    location: { latitude: 16.534200, longitude: 80.672000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gollapudi.',
  },
  {
    id: 'node-vij-9-1',
    name: 'Patamata Sector 1 High Street',
    zone: 'Patamata',
    location: { latitude: 16.540200, longitude: 80.676000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Patamata.',
  },
  {
    id: 'node-vij-9-2',
    name: 'Patamata Sector 2 High Street',
    zone: 'Patamata',
    location: { latitude: 16.543200, longitude: 80.679000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Patamata.',
  },
  {
    id: 'node-vij-9-3',
    name: 'Patamata Sector 3 High Street',
    zone: 'Patamata',
    location: { latitude: 16.546200, longitude: 80.682000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Patamata.',
  },
  {
    id: 'node-vij-10-1',
    name: 'Moghalrajpuram Sector 1 High Street',
    zone: 'Moghalrajpuram',
    location: { latitude: 16.552200, longitude: 80.686000 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Moghalrajpuram.',
  },
  {
    id: 'node-vij-10-2',
    name: 'Moghalrajpuram Sector 2 High Street',
    zone: 'Moghalrajpuram',
    location: { latitude: 16.555200, longitude: 80.689000 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Moghalrajpuram.',
  },
  {
    id: 'node-vij-10-3',
    name: 'Moghalrajpuram Sector 3 High Street',
    zone: 'Moghalrajpuram',
    location: { latitude: 16.558200, longitude: 80.692000 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Moghalrajpuram.',
  },
];

export const VIJAYAWADA_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-vij-1',
    fromNodeId: 'node-vij-1-1',
    toNodeId: 'node-vij-1-2',
    roadName: 'MG Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-2',
    fromNodeId: 'node-vij-1-2',
    toNodeId: 'node-vij-1-3',
    roadName: 'MG Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-3',
    fromNodeId: 'node-vij-2-1',
    toNodeId: 'node-vij-2-2',
    roadName: 'Benz Circle Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-4',
    fromNodeId: 'node-vij-2-2',
    toNodeId: 'node-vij-2-3',
    roadName: 'Benz Circle Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-5',
    fromNodeId: 'node-vij-3-1',
    toNodeId: 'node-vij-3-2',
    roadName: 'Governorpet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-6',
    fromNodeId: 'node-vij-3-2',
    toNodeId: 'node-vij-3-3',
    roadName: 'Governorpet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-7',
    fromNodeId: 'node-vij-4-1',
    toNodeId: 'node-vij-4-2',
    roadName: 'Suryaraopet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-8',
    fromNodeId: 'node-vij-4-2',
    toNodeId: 'node-vij-4-3',
    roadName: 'Suryaraopet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-9',
    fromNodeId: 'node-vij-5-1',
    toNodeId: 'node-vij-5-2',
    roadName: 'Auto Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-10',
    fromNodeId: 'node-vij-5-2',
    toNodeId: 'node-vij-5-3',
    roadName: 'Auto Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-11',
    fromNodeId: 'node-vij-6-1',
    toNodeId: 'node-vij-6-2',
    roadName: 'Bhavanipuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-12',
    fromNodeId: 'node-vij-6-2',
    toNodeId: 'node-vij-6-3',
    roadName: 'Bhavanipuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-13',
    fromNodeId: 'node-vij-7-1',
    toNodeId: 'node-vij-7-2',
    roadName: 'Labbipet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-14',
    fromNodeId: 'node-vij-7-2',
    toNodeId: 'node-vij-7-3',
    roadName: 'Labbipet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-15',
    fromNodeId: 'node-vij-8-1',
    toNodeId: 'node-vij-8-2',
    roadName: 'Gollapudi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-16',
    fromNodeId: 'node-vij-8-2',
    toNodeId: 'node-vij-8-3',
    roadName: 'Gollapudi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-17',
    fromNodeId: 'node-vij-9-1',
    toNodeId: 'node-vij-9-2',
    roadName: 'Patamata Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-18',
    fromNodeId: 'node-vij-9-2',
    toNodeId: 'node-vij-9-3',
    roadName: 'Patamata Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-19',
    fromNodeId: 'node-vij-10-1',
    toNodeId: 'node-vij-10-2',
    roadName: 'Moghalrajpuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vij-20',
    fromNodeId: 'node-vij-10-2',
    toNodeId: 'node-vij-10-3',
    roadName: 'Moghalrajpuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
