/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Visakhapatnam Steel & Port Zone
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const VISAKHAPATNAM_BASE_COORDINATE: GeoCoordinate = {
  latitude: 17.6868,
  longitude: 83.2185,
};

export const VISAKHAPATNAM_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-vis-1-1',
    name: 'Siripuram Sector 1 High Street',
    zone: 'Siripuram',
    location: { latitude: 17.624800, longitude: 83.166500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Siripuram.',
  },
  {
    id: 'node-vis-1-2',
    name: 'Siripuram Sector 2 High Street',
    zone: 'Siripuram',
    location: { latitude: 17.627800, longitude: 83.169500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Siripuram.',
  },
  {
    id: 'node-vis-1-3',
    name: 'Siripuram Sector 3 High Street',
    zone: 'Siripuram',
    location: { latitude: 17.630800, longitude: 83.172500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Siripuram.',
  },
  {
    id: 'node-vis-2-1',
    name: 'MVP Colony Sector 1 High Street',
    zone: 'MVP Colony',
    location: { latitude: 17.636800, longitude: 83.176500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in MVP Colony.',
  },
  {
    id: 'node-vis-2-2',
    name: 'MVP Colony Sector 2 High Street',
    zone: 'MVP Colony',
    location: { latitude: 17.639800, longitude: 83.179500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in MVP Colony.',
  },
  {
    id: 'node-vis-2-3',
    name: 'MVP Colony Sector 3 High Street',
    zone: 'MVP Colony',
    location: { latitude: 17.642800, longitude: 83.182500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in MVP Colony.',
  },
  {
    id: 'node-vis-3-1',
    name: 'Dwaraka Nagar Sector 1 High Street',
    zone: 'Dwaraka Nagar',
    location: { latitude: 17.648800, longitude: 83.186500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Dwaraka Nagar.',
  },
  {
    id: 'node-vis-3-2',
    name: 'Dwaraka Nagar Sector 2 High Street',
    zone: 'Dwaraka Nagar',
    location: { latitude: 17.651800, longitude: 83.189500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Dwaraka Nagar.',
  },
  {
    id: 'node-vis-3-3',
    name: 'Dwaraka Nagar Sector 3 High Street',
    zone: 'Dwaraka Nagar',
    location: { latitude: 17.654800, longitude: 83.192500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Dwaraka Nagar.',
  },
  {
    id: 'node-vis-4-1',
    name: 'Gajuwaka Sector 1 High Street',
    zone: 'Gajuwaka',
    location: { latitude: 17.660800, longitude: 83.196500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Gajuwaka.',
  },
  {
    id: 'node-vis-4-2',
    name: 'Gajuwaka Sector 2 High Street',
    zone: 'Gajuwaka',
    location: { latitude: 17.663800, longitude: 83.199500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Gajuwaka.',
  },
  {
    id: 'node-vis-4-3',
    name: 'Gajuwaka Sector 3 High Street',
    zone: 'Gajuwaka',
    location: { latitude: 17.666800, longitude: 83.202500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Gajuwaka.',
  },
  {
    id: 'node-vis-5-1',
    name: 'Beach Road Sector 1 High Street',
    zone: 'Beach Road',
    location: { latitude: 17.672800, longitude: 83.206500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Beach Road.',
  },
  {
    id: 'node-vis-5-2',
    name: 'Beach Road Sector 2 High Street',
    zone: 'Beach Road',
    location: { latitude: 17.675800, longitude: 83.209500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Beach Road.',
  },
  {
    id: 'node-vis-5-3',
    name: 'Beach Road Sector 3 High Street',
    zone: 'Beach Road',
    location: { latitude: 17.678800, longitude: 83.212500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Beach Road.',
  },
  {
    id: 'node-vis-6-1',
    name: 'Madhurawada Sector 1 High Street',
    zone: 'Madhurawada',
    location: { latitude: 17.684800, longitude: 83.216500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Madhurawada.',
  },
  {
    id: 'node-vis-6-2',
    name: 'Madhurawada Sector 2 High Street',
    zone: 'Madhurawada',
    location: { latitude: 17.687800, longitude: 83.219500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Madhurawada.',
  },
  {
    id: 'node-vis-6-3',
    name: 'Madhurawada Sector 3 High Street',
    zone: 'Madhurawada',
    location: { latitude: 17.690800, longitude: 83.222500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Madhurawada.',
  },
  {
    id: 'node-vis-7-1',
    name: 'Seethammadhara Sector 1 High Street',
    zone: 'Seethammadhara',
    location: { latitude: 17.696800, longitude: 83.226500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Seethammadhara.',
  },
  {
    id: 'node-vis-7-2',
    name: 'Seethammadhara Sector 2 High Street',
    zone: 'Seethammadhara',
    location: { latitude: 17.699800, longitude: 83.229500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Seethammadhara.',
  },
  {
    id: 'node-vis-7-3',
    name: 'Seethammadhara Sector 3 High Street',
    zone: 'Seethammadhara',
    location: { latitude: 17.702800, longitude: 83.232500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Seethammadhara.',
  },
  {
    id: 'node-vis-8-1',
    name: 'Rushikonda Sector 1 High Street',
    zone: 'Rushikonda',
    location: { latitude: 17.708800, longitude: 83.236500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Rushikonda.',
  },
  {
    id: 'node-vis-8-2',
    name: 'Rushikonda Sector 2 High Street',
    zone: 'Rushikonda',
    location: { latitude: 17.711800, longitude: 83.239500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Rushikonda.',
  },
  {
    id: 'node-vis-8-3',
    name: 'Rushikonda Sector 3 High Street',
    zone: 'Rushikonda',
    location: { latitude: 17.714800, longitude: 83.242500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Rushikonda.',
  },
  {
    id: 'node-vis-9-1',
    name: 'Waltair Uplands Sector 1 High Street',
    zone: 'Waltair Uplands',
    location: { latitude: 17.720800, longitude: 83.246500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Waltair Uplands.',
  },
  {
    id: 'node-vis-9-2',
    name: 'Waltair Uplands Sector 2 High Street',
    zone: 'Waltair Uplands',
    location: { latitude: 17.723800, longitude: 83.249500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Waltair Uplands.',
  },
  {
    id: 'node-vis-9-3',
    name: 'Waltair Uplands Sector 3 High Street',
    zone: 'Waltair Uplands',
    location: { latitude: 17.726800, longitude: 83.252500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Waltair Uplands.',
  },
  {
    id: 'node-vis-10-1',
    name: 'Pendurthi Sector 1 High Street',
    zone: 'Pendurthi',
    location: { latitude: 17.732800, longitude: 83.256500 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pendurthi.',
  },
  {
    id: 'node-vis-10-2',
    name: 'Pendurthi Sector 2 High Street',
    zone: 'Pendurthi',
    location: { latitude: 17.735800, longitude: 83.259500 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pendurthi.',
  },
  {
    id: 'node-vis-10-3',
    name: 'Pendurthi Sector 3 High Street',
    zone: 'Pendurthi',
    location: { latitude: 17.738800, longitude: 83.262500 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pendurthi.',
  },
];

export const VISAKHAPATNAM_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-vis-1',
    fromNodeId: 'node-vis-1-1',
    toNodeId: 'node-vis-1-2',
    roadName: 'Siripuram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-2',
    fromNodeId: 'node-vis-1-2',
    toNodeId: 'node-vis-1-3',
    roadName: 'Siripuram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-3',
    fromNodeId: 'node-vis-2-1',
    toNodeId: 'node-vis-2-2',
    roadName: 'MVP Colony Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-4',
    fromNodeId: 'node-vis-2-2',
    toNodeId: 'node-vis-2-3',
    roadName: 'MVP Colony Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-5',
    fromNodeId: 'node-vis-3-1',
    toNodeId: 'node-vis-3-2',
    roadName: 'Dwaraka Nagar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-6',
    fromNodeId: 'node-vis-3-2',
    toNodeId: 'node-vis-3-3',
    roadName: 'Dwaraka Nagar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-7',
    fromNodeId: 'node-vis-4-1',
    toNodeId: 'node-vis-4-2',
    roadName: 'Gajuwaka Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-8',
    fromNodeId: 'node-vis-4-2',
    toNodeId: 'node-vis-4-3',
    roadName: 'Gajuwaka Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-9',
    fromNodeId: 'node-vis-5-1',
    toNodeId: 'node-vis-5-2',
    roadName: 'Beach Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-10',
    fromNodeId: 'node-vis-5-2',
    toNodeId: 'node-vis-5-3',
    roadName: 'Beach Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-11',
    fromNodeId: 'node-vis-6-1',
    toNodeId: 'node-vis-6-2',
    roadName: 'Madhurawada Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-12',
    fromNodeId: 'node-vis-6-2',
    toNodeId: 'node-vis-6-3',
    roadName: 'Madhurawada Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-13',
    fromNodeId: 'node-vis-7-1',
    toNodeId: 'node-vis-7-2',
    roadName: 'Seethammadhara Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-14',
    fromNodeId: 'node-vis-7-2',
    toNodeId: 'node-vis-7-3',
    roadName: 'Seethammadhara Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-15',
    fromNodeId: 'node-vis-8-1',
    toNodeId: 'node-vis-8-2',
    roadName: 'Rushikonda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-16',
    fromNodeId: 'node-vis-8-2',
    toNodeId: 'node-vis-8-3',
    roadName: 'Rushikonda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-17',
    fromNodeId: 'node-vis-9-1',
    toNodeId: 'node-vis-9-2',
    roadName: 'Waltair Uplands Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-18',
    fromNodeId: 'node-vis-9-2',
    toNodeId: 'node-vis-9-3',
    roadName: 'Waltair Uplands Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-19',
    fromNodeId: 'node-vis-10-1',
    toNodeId: 'node-vis-10-2',
    roadName: 'Pendurthi Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-vis-20',
    fromNodeId: 'node-vis-10-2',
    toNodeId: 'node-vis-10-3',
    roadName: 'Pendurthi Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
