/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Warangal Kakatiya Heritage
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const WARANGAL_BASE_COORDINATE: GeoCoordinate = {
  latitude: 17.9689,
  longitude: 79.5941,
};

export const WARANGAL_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-war-1-1',
    name: 'Hanamkonda Sector 1 High Street',
    zone: 'Hanamkonda',
    location: { latitude: 17.906900, longitude: 79.542100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hanamkonda.',
  },
  {
    id: 'node-war-1-2',
    name: 'Hanamkonda Sector 2 High Street',
    zone: 'Hanamkonda',
    location: { latitude: 17.909900, longitude: 79.545100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hanamkonda.',
  },
  {
    id: 'node-war-1-3',
    name: 'Hanamkonda Sector 3 High Street',
    zone: 'Hanamkonda',
    location: { latitude: 17.912900, longitude: 79.548100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hanamkonda.',
  },
  {
    id: 'node-war-2-1',
    name: 'Kazipet Sector 1 High Street',
    zone: 'Kazipet',
    location: { latitude: 17.918900, longitude: 79.552100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kazipet.',
  },
  {
    id: 'node-war-2-2',
    name: 'Kazipet Sector 2 High Street',
    zone: 'Kazipet',
    location: { latitude: 17.921900, longitude: 79.555100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kazipet.',
  },
  {
    id: 'node-war-2-3',
    name: 'Kazipet Sector 3 High Street',
    zone: 'Kazipet',
    location: { latitude: 17.924900, longitude: 79.558100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kazipet.',
  },
  {
    id: 'node-war-3-1',
    name: 'Subedari Sector 1 High Street',
    zone: 'Subedari',
    location: { latitude: 17.930900, longitude: 79.562100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Subedari.',
  },
  {
    id: 'node-war-3-2',
    name: 'Subedari Sector 2 High Street',
    zone: 'Subedari',
    location: { latitude: 17.933900, longitude: 79.565100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Subedari.',
  },
  {
    id: 'node-war-3-3',
    name: 'Subedari Sector 3 High Street',
    zone: 'Subedari',
    location: { latitude: 17.936900, longitude: 79.568100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Subedari.',
  },
  {
    id: 'node-war-4-1',
    name: 'Nakkalagutta Sector 1 High Street',
    zone: 'Nakkalagutta',
    location: { latitude: 17.942900, longitude: 79.572100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Nakkalagutta.',
  },
  {
    id: 'node-war-4-2',
    name: 'Nakkalagutta Sector 2 High Street',
    zone: 'Nakkalagutta',
    location: { latitude: 17.945900, longitude: 79.575100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Nakkalagutta.',
  },
  {
    id: 'node-war-4-3',
    name: 'Nakkalagutta Sector 3 High Street',
    zone: 'Nakkalagutta',
    location: { latitude: 17.948900, longitude: 79.578100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Nakkalagutta.',
  },
  {
    id: 'node-war-5-1',
    name: 'Kakatiya Colony Sector 1 High Street',
    zone: 'Kakatiya Colony',
    location: { latitude: 17.954900, longitude: 79.582100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kakatiya Colony.',
  },
  {
    id: 'node-war-5-2',
    name: 'Kakatiya Colony Sector 2 High Street',
    zone: 'Kakatiya Colony',
    location: { latitude: 17.957900, longitude: 79.585100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kakatiya Colony.',
  },
  {
    id: 'node-war-5-3',
    name: 'Kakatiya Colony Sector 3 High Street',
    zone: 'Kakatiya Colony',
    location: { latitude: 17.960900, longitude: 79.588100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kakatiya Colony.',
  },
  {
    id: 'node-war-6-1',
    name: 'Mandi Bazaar Sector 1 High Street',
    zone: 'Mandi Bazaar',
    location: { latitude: 17.966900, longitude: 79.592100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mandi Bazaar.',
  },
  {
    id: 'node-war-6-2',
    name: 'Mandi Bazaar Sector 2 High Street',
    zone: 'Mandi Bazaar',
    location: { latitude: 17.969900, longitude: 79.595100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mandi Bazaar.',
  },
  {
    id: 'node-war-6-3',
    name: 'Mandi Bazaar Sector 3 High Street',
    zone: 'Mandi Bazaar',
    location: { latitude: 17.972900, longitude: 79.598100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mandi Bazaar.',
  },
  {
    id: 'node-war-7-1',
    name: 'Pochamma Maidan Sector 1 High Street',
    zone: 'Pochamma Maidan',
    location: { latitude: 17.978900, longitude: 79.602100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Pochamma Maidan.',
  },
  {
    id: 'node-war-7-2',
    name: 'Pochamma Maidan Sector 2 High Street',
    zone: 'Pochamma Maidan',
    location: { latitude: 17.981900, longitude: 79.605100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Pochamma Maidan.',
  },
  {
    id: 'node-war-7-3',
    name: 'Pochamma Maidan Sector 3 High Street',
    zone: 'Pochamma Maidan',
    location: { latitude: 17.984900, longitude: 79.608100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Pochamma Maidan.',
  },
  {
    id: 'node-war-8-1',
    name: 'Balasamudram Sector 1 High Street',
    zone: 'Balasamudram',
    location: { latitude: 17.990900, longitude: 79.612100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Balasamudram.',
  },
  {
    id: 'node-war-8-2',
    name: 'Balasamudram Sector 2 High Street',
    zone: 'Balasamudram',
    location: { latitude: 17.993900, longitude: 79.615100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Balasamudram.',
  },
  {
    id: 'node-war-8-3',
    name: 'Balasamudram Sector 3 High Street',
    zone: 'Balasamudram',
    location: { latitude: 17.996900, longitude: 79.618100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Balasamudram.',
  },
  {
    id: 'node-war-9-1',
    name: 'Bhimaram Sector 1 High Street',
    zone: 'Bhimaram',
    location: { latitude: 18.002900, longitude: 79.622100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bhimaram.',
  },
  {
    id: 'node-war-9-2',
    name: 'Bhimaram Sector 2 High Street',
    zone: 'Bhimaram',
    location: { latitude: 18.005900, longitude: 79.625100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bhimaram.',
  },
  {
    id: 'node-war-9-3',
    name: 'Bhimaram Sector 3 High Street',
    zone: 'Bhimaram',
    location: { latitude: 18.008900, longitude: 79.628100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bhimaram.',
  },
  {
    id: 'node-war-10-1',
    name: 'Hunter Road Sector 1 High Street',
    zone: 'Hunter Road',
    location: { latitude: 18.014900, longitude: 79.632100 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Hunter Road.',
  },
  {
    id: 'node-war-10-2',
    name: 'Hunter Road Sector 2 High Street',
    zone: 'Hunter Road',
    location: { latitude: 18.017900, longitude: 79.635100 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Hunter Road.',
  },
  {
    id: 'node-war-10-3',
    name: 'Hunter Road Sector 3 High Street',
    zone: 'Hunter Road',
    location: { latitude: 18.020900, longitude: 79.638100 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Hunter Road.',
  },
];

export const WARANGAL_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-war-1',
    fromNodeId: 'node-war-1-1',
    toNodeId: 'node-war-1-2',
    roadName: 'Hanamkonda Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-2',
    fromNodeId: 'node-war-1-2',
    toNodeId: 'node-war-1-3',
    roadName: 'Hanamkonda Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-3',
    fromNodeId: 'node-war-2-1',
    toNodeId: 'node-war-2-2',
    roadName: 'Kazipet Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-4',
    fromNodeId: 'node-war-2-2',
    toNodeId: 'node-war-2-3',
    roadName: 'Kazipet Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-5',
    fromNodeId: 'node-war-3-1',
    toNodeId: 'node-war-3-2',
    roadName: 'Subedari Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-6',
    fromNodeId: 'node-war-3-2',
    toNodeId: 'node-war-3-3',
    roadName: 'Subedari Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-7',
    fromNodeId: 'node-war-4-1',
    toNodeId: 'node-war-4-2',
    roadName: 'Nakkalagutta Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-8',
    fromNodeId: 'node-war-4-2',
    toNodeId: 'node-war-4-3',
    roadName: 'Nakkalagutta Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-9',
    fromNodeId: 'node-war-5-1',
    toNodeId: 'node-war-5-2',
    roadName: 'Kakatiya Colony Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-10',
    fromNodeId: 'node-war-5-2',
    toNodeId: 'node-war-5-3',
    roadName: 'Kakatiya Colony Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-11',
    fromNodeId: 'node-war-6-1',
    toNodeId: 'node-war-6-2',
    roadName: 'Mandi Bazaar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-12',
    fromNodeId: 'node-war-6-2',
    toNodeId: 'node-war-6-3',
    roadName: 'Mandi Bazaar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-13',
    fromNodeId: 'node-war-7-1',
    toNodeId: 'node-war-7-2',
    roadName: 'Pochamma Maidan Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-14',
    fromNodeId: 'node-war-7-2',
    toNodeId: 'node-war-7-3',
    roadName: 'Pochamma Maidan Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-15',
    fromNodeId: 'node-war-8-1',
    toNodeId: 'node-war-8-2',
    roadName: 'Balasamudram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-16',
    fromNodeId: 'node-war-8-2',
    toNodeId: 'node-war-8-3',
    roadName: 'Balasamudram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-17',
    fromNodeId: 'node-war-9-1',
    toNodeId: 'node-war-9-2',
    roadName: 'Bhimaram Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-18',
    fromNodeId: 'node-war-9-2',
    toNodeId: 'node-war-9-3',
    roadName: 'Bhimaram Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-19',
    fromNodeId: 'node-war-10-1',
    toNodeId: 'node-war-10-2',
    roadName: 'Hunter Road Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-20',
    fromNodeId: 'node-war-10-2',
    toNodeId: 'node-war-10-3',
    roadName: 'Hunter Road Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
