/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Warsaw Vistula Corridor
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const WARSAW_BASE_COORDINATE: GeoCoordinate = {
  latitude: 52.2297,
  longitude: 21.0122,
};

export const WARSAW_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-war-1-1',
    name: 'Śródmieście Sector 1 High Street',
    zone: 'Śródmieście',
    location: { latitude: 52.167700, longitude: 20.960200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Śródmieście.',
  },
  {
    id: 'node-war-1-2',
    name: 'Śródmieście Sector 2 High Street',
    zone: 'Śródmieście',
    location: { latitude: 52.170700, longitude: 20.963200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Śródmieście.',
  },
  {
    id: 'node-war-1-3',
    name: 'Śródmieście Sector 3 High Street',
    zone: 'Śródmieście',
    location: { latitude: 52.173700, longitude: 20.966200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Śródmieście.',
  },
  {
    id: 'node-war-2-1',
    name: 'Mokotów Sector 1 High Street',
    zone: 'Mokotów',
    location: { latitude: 52.179700, longitude: 20.970200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mokotów.',
  },
  {
    id: 'node-war-2-2',
    name: 'Mokotów Sector 2 High Street',
    zone: 'Mokotów',
    location: { latitude: 52.182700, longitude: 20.973200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mokotów.',
  },
  {
    id: 'node-war-2-3',
    name: 'Mokotów Sector 3 High Street',
    zone: 'Mokotów',
    location: { latitude: 52.185700, longitude: 20.976200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mokotów.',
  },
  {
    id: 'node-war-3-1',
    name: 'Wola Sector 1 High Street',
    zone: 'Wola',
    location: { latitude: 52.191700, longitude: 20.980200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wola.',
  },
  {
    id: 'node-war-3-2',
    name: 'Wola Sector 2 High Street',
    zone: 'Wola',
    location: { latitude: 52.194700, longitude: 20.983200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wola.',
  },
  {
    id: 'node-war-3-3',
    name: 'Wola Sector 3 High Street',
    zone: 'Wola',
    location: { latitude: 52.197700, longitude: 20.986200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wola.',
  },
  {
    id: 'node-war-4-1',
    name: 'Praga-Północ Sector 1 High Street',
    zone: 'Praga-Północ',
    location: { latitude: 52.203700, longitude: 20.990200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Praga-Północ.',
  },
  {
    id: 'node-war-4-2',
    name: 'Praga-Północ Sector 2 High Street',
    zone: 'Praga-Północ',
    location: { latitude: 52.206700, longitude: 20.993200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Praga-Północ.',
  },
  {
    id: 'node-war-4-3',
    name: 'Praga-Północ Sector 3 High Street',
    zone: 'Praga-Północ',
    location: { latitude: 52.209700, longitude: 20.996200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Praga-Północ.',
  },
  {
    id: 'node-war-5-1',
    name: 'Ursynów Sector 1 High Street',
    zone: 'Ursynów',
    location: { latitude: 52.215700, longitude: 21.000200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ursynów.',
  },
  {
    id: 'node-war-5-2',
    name: 'Ursynów Sector 2 High Street',
    zone: 'Ursynów',
    location: { latitude: 52.218700, longitude: 21.003200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ursynów.',
  },
  {
    id: 'node-war-5-3',
    name: 'Ursynów Sector 3 High Street',
    zone: 'Ursynów',
    location: { latitude: 52.221700, longitude: 21.006200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ursynów.',
  },
  {
    id: 'node-war-6-1',
    name: 'Żoliborz Sector 1 High Street',
    zone: 'Żoliborz',
    location: { latitude: 52.227700, longitude: 21.010200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Żoliborz.',
  },
  {
    id: 'node-war-6-2',
    name: 'Żoliborz Sector 2 High Street',
    zone: 'Żoliborz',
    location: { latitude: 52.230700, longitude: 21.013200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Żoliborz.',
  },
  {
    id: 'node-war-6-3',
    name: 'Żoliborz Sector 3 High Street',
    zone: 'Żoliborz',
    location: { latitude: 52.233700, longitude: 21.016200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Żoliborz.',
  },
  {
    id: 'node-war-7-1',
    name: 'Ochota Sector 1 High Street',
    zone: 'Ochota',
    location: { latitude: 52.239700, longitude: 21.020200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Ochota.',
  },
  {
    id: 'node-war-7-2',
    name: 'Ochota Sector 2 High Street',
    zone: 'Ochota',
    location: { latitude: 52.242700, longitude: 21.023200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Ochota.',
  },
  {
    id: 'node-war-7-3',
    name: 'Ochota Sector 3 High Street',
    zone: 'Ochota',
    location: { latitude: 52.245700, longitude: 21.026200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Ochota.',
  },
  {
    id: 'node-war-8-1',
    name: 'Wilanów Sector 1 High Street',
    zone: 'Wilanów',
    location: { latitude: 52.251700, longitude: 21.030200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wilanów.',
  },
  {
    id: 'node-war-8-2',
    name: 'Wilanów Sector 2 High Street',
    zone: 'Wilanów',
    location: { latitude: 52.254700, longitude: 21.033200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wilanów.',
  },
  {
    id: 'node-war-8-3',
    name: 'Wilanów Sector 3 High Street',
    zone: 'Wilanów',
    location: { latitude: 52.257700, longitude: 21.036200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wilanów.',
  },
  {
    id: 'node-war-9-1',
    name: 'Bielany Sector 1 High Street',
    zone: 'Bielany',
    location: { latitude: 52.263700, longitude: 21.040200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Bielany.',
  },
  {
    id: 'node-war-9-2',
    name: 'Bielany Sector 2 High Street',
    zone: 'Bielany',
    location: { latitude: 52.266700, longitude: 21.043200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Bielany.',
  },
  {
    id: 'node-war-9-3',
    name: 'Bielany Sector 3 High Street',
    zone: 'Bielany',
    location: { latitude: 52.269700, longitude: 21.046200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Bielany.',
  },
  {
    id: 'node-war-10-1',
    name: 'Targówek Sector 1 High Street',
    zone: 'Targówek',
    location: { latitude: 52.275700, longitude: 21.050200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Targówek.',
  },
  {
    id: 'node-war-10-2',
    name: 'Targówek Sector 2 High Street',
    zone: 'Targówek',
    location: { latitude: 52.278700, longitude: 21.053200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Targówek.',
  },
  {
    id: 'node-war-10-3',
    name: 'Targówek Sector 3 High Street',
    zone: 'Targówek',
    location: { latitude: 52.281700, longitude: 21.056200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Targówek.',
  },
];

export const WARSAW_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-war-1',
    fromNodeId: 'node-war-1-1',
    toNodeId: 'node-war-1-2',
    roadName: 'Śródmieście Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-2',
    fromNodeId: 'node-war-1-2',
    toNodeId: 'node-war-1-3',
    roadName: 'Śródmieście Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-3',
    fromNodeId: 'node-war-2-1',
    toNodeId: 'node-war-2-2',
    roadName: 'Mokotów Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-4',
    fromNodeId: 'node-war-2-2',
    toNodeId: 'node-war-2-3',
    roadName: 'Mokotów Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-5',
    fromNodeId: 'node-war-3-1',
    toNodeId: 'node-war-3-2',
    roadName: 'Wola Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-6',
    fromNodeId: 'node-war-3-2',
    toNodeId: 'node-war-3-3',
    roadName: 'Wola Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-7',
    fromNodeId: 'node-war-4-1',
    toNodeId: 'node-war-4-2',
    roadName: 'Praga-Północ Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-8',
    fromNodeId: 'node-war-4-2',
    toNodeId: 'node-war-4-3',
    roadName: 'Praga-Północ Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-9',
    fromNodeId: 'node-war-5-1',
    toNodeId: 'node-war-5-2',
    roadName: 'Ursynów Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-10',
    fromNodeId: 'node-war-5-2',
    toNodeId: 'node-war-5-3',
    roadName: 'Ursynów Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-11',
    fromNodeId: 'node-war-6-1',
    toNodeId: 'node-war-6-2',
    roadName: 'Żoliborz Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-12',
    fromNodeId: 'node-war-6-2',
    toNodeId: 'node-war-6-3',
    roadName: 'Żoliborz Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-13',
    fromNodeId: 'node-war-7-1',
    toNodeId: 'node-war-7-2',
    roadName: 'Ochota Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-14',
    fromNodeId: 'node-war-7-2',
    toNodeId: 'node-war-7-3',
    roadName: 'Ochota Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-15',
    fromNodeId: 'node-war-8-1',
    toNodeId: 'node-war-8-2',
    roadName: 'Wilanów Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-16',
    fromNodeId: 'node-war-8-2',
    toNodeId: 'node-war-8-3',
    roadName: 'Wilanów Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-17',
    fromNodeId: 'node-war-9-1',
    toNodeId: 'node-war-9-2',
    roadName: 'Bielany Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-18',
    fromNodeId: 'node-war-9-2',
    toNodeId: 'node-war-9-3',
    roadName: 'Bielany Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-19',
    fromNodeId: 'node-war-10-1',
    toNodeId: 'node-war-10-2',
    roadName: 'Targówek Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-war-20',
    fromNodeId: 'node-war-10-2',
    toNodeId: 'node-war-10-3',
    roadName: 'Targówek Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
