/**
 * QuickBite Metropolitan Road Graph & Spatial Topology — Wellington Capital Harbour
 * High-precision topological coordinates, street nodes, speed regulations, and landmark hubs.
 */

import { GeoCoordinate, RoadNode, RoadSegment } from '../metroGraph.js';

export const WELLINGTON_BASE_COORDINATE: GeoCoordinate = {
  latitude: -41.2865,
  longitude: 174.7762,
};

export const WELLINGTON_LOCALITY_NODES: RoadNode[] = [
  {
    id: 'node-wel-1-1',
    name: 'Te Aro Sector 1 High Street',
    zone: 'Te Aro',
    location: { latitude: -41.348500, longitude: 174.724200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Te Aro.',
  },
  {
    id: 'node-wel-1-2',
    name: 'Te Aro Sector 2 High Street',
    zone: 'Te Aro',
    location: { latitude: -41.345500, longitude: 174.727200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Te Aro.',
  },
  {
    id: 'node-wel-1-3',
    name: 'Te Aro Sector 3 High Street',
    zone: 'Te Aro',
    location: { latitude: -41.342500, longitude: 174.730200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Te Aro.',
  },
  {
    id: 'node-wel-2-1',
    name: 'Wellington Waterfront Sector 1 High Street',
    zone: 'Wellington Waterfront',
    location: { latitude: -41.336500, longitude: 174.734200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Wellington Waterfront.',
  },
  {
    id: 'node-wel-2-2',
    name: 'Wellington Waterfront Sector 2 High Street',
    zone: 'Wellington Waterfront',
    location: { latitude: -41.333500, longitude: 174.737200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Wellington Waterfront.',
  },
  {
    id: 'node-wel-2-3',
    name: 'Wellington Waterfront Sector 3 High Street',
    zone: 'Wellington Waterfront',
    location: { latitude: -41.330500, longitude: 174.740200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Wellington Waterfront.',
  },
  {
    id: 'node-wel-3-1',
    name: 'Thorndon Sector 1 High Street',
    zone: 'Thorndon',
    location: { latitude: -41.324500, longitude: 174.744200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Thorndon.',
  },
  {
    id: 'node-wel-3-2',
    name: 'Thorndon Sector 2 High Street',
    zone: 'Thorndon',
    location: { latitude: -41.321500, longitude: 174.747200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Thorndon.',
  },
  {
    id: 'node-wel-3-3',
    name: 'Thorndon Sector 3 High Street',
    zone: 'Thorndon',
    location: { latitude: -41.318500, longitude: 174.750200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Thorndon.',
  },
  {
    id: 'node-wel-4-1',
    name: 'Mount Victoria Sector 1 High Street',
    zone: 'Mount Victoria',
    location: { latitude: -41.312500, longitude: 174.754200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Mount Victoria.',
  },
  {
    id: 'node-wel-4-2',
    name: 'Mount Victoria Sector 2 High Street',
    zone: 'Mount Victoria',
    location: { latitude: -41.309500, longitude: 174.757200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Mount Victoria.',
  },
  {
    id: 'node-wel-4-3',
    name: 'Mount Victoria Sector 3 High Street',
    zone: 'Mount Victoria',
    location: { latitude: -41.306500, longitude: 174.760200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Mount Victoria.',
  },
  {
    id: 'node-wel-5-1',
    name: 'Newtown Wellington Sector 1 High Street',
    zone: 'Newtown Wellington',
    location: { latitude: -41.300500, longitude: 174.764200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Newtown Wellington.',
  },
  {
    id: 'node-wel-5-2',
    name: 'Newtown Wellington Sector 2 High Street',
    zone: 'Newtown Wellington',
    location: { latitude: -41.297500, longitude: 174.767200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Newtown Wellington.',
  },
  {
    id: 'node-wel-5-3',
    name: 'Newtown Wellington Sector 3 High Street',
    zone: 'Newtown Wellington',
    location: { latitude: -41.294500, longitude: 174.770200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Newtown Wellington.',
  },
  {
    id: 'node-wel-6-1',
    name: 'Kelburn Sector 1 High Street',
    zone: 'Kelburn',
    location: { latitude: -41.288500, longitude: 174.774200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Kelburn.',
  },
  {
    id: 'node-wel-6-2',
    name: 'Kelburn Sector 2 High Street',
    zone: 'Kelburn',
    location: { latitude: -41.285500, longitude: 174.777200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Kelburn.',
  },
  {
    id: 'node-wel-6-3',
    name: 'Kelburn Sector 3 High Street',
    zone: 'Kelburn',
    location: { latitude: -41.282500, longitude: 174.780200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Kelburn.',
  },
  {
    id: 'node-wel-7-1',
    name: 'Courtenay Place Sector 1 High Street',
    zone: 'Courtenay Place',
    location: { latitude: -41.276500, longitude: 174.784200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Courtenay Place.',
  },
  {
    id: 'node-wel-7-2',
    name: 'Courtenay Place Sector 2 High Street',
    zone: 'Courtenay Place',
    location: { latitude: -41.273500, longitude: 174.787200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Courtenay Place.',
  },
  {
    id: 'node-wel-7-3',
    name: 'Courtenay Place Sector 3 High Street',
    zone: 'Courtenay Place',
    location: { latitude: -41.270500, longitude: 174.790200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Courtenay Place.',
  },
  {
    id: 'node-wel-8-1',
    name: 'Oriental Bay Sector 1 High Street',
    zone: 'Oriental Bay',
    location: { latitude: -41.264500, longitude: 174.794200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Oriental Bay.',
  },
  {
    id: 'node-wel-8-2',
    name: 'Oriental Bay Sector 2 High Street',
    zone: 'Oriental Bay',
    location: { latitude: -41.261500, longitude: 174.797200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Oriental Bay.',
  },
  {
    id: 'node-wel-8-3',
    name: 'Oriental Bay Sector 3 High Street',
    zone: 'Oriental Bay',
    location: { latitude: -41.258500, longitude: 174.800200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Oriental Bay.',
  },
  {
    id: 'node-wel-9-1',
    name: 'Island Bay Sector 1 High Street',
    zone: 'Island Bay',
    location: { latitude: -41.252500, longitude: 174.804200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Island Bay.',
  },
  {
    id: 'node-wel-9-2',
    name: 'Island Bay Sector 2 High Street',
    zone: 'Island Bay',
    location: { latitude: -41.249500, longitude: 174.807200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Island Bay.',
  },
  {
    id: 'node-wel-9-3',
    name: 'Island Bay Sector 3 High Street',
    zone: 'Island Bay',
    location: { latitude: -41.246500, longitude: 174.810200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Island Bay.',
  },
  {
    id: 'node-wel-10-1',
    name: 'Miramar Sector 1 High Street',
    zone: 'Miramar',
    location: { latitude: -41.240500, longitude: 174.814200 },
    landmarkType: 'RESIDENTIAL',
    description: 'Vibrant commercial & residential delivery sector in Miramar.',
  },
  {
    id: 'node-wel-10-2',
    name: 'Miramar Sector 2 High Street',
    zone: 'Miramar',
    location: { latitude: -41.237500, longitude: 174.817200 },
    landmarkType: 'TECH_PARK',
    description: 'Vibrant commercial & residential delivery sector in Miramar.',
  },
  {
    id: 'node-wel-10-3',
    name: 'Miramar Sector 3 High Street',
    zone: 'Miramar',
    location: { latitude: -41.234500, longitude: 174.820200 },
    landmarkType: 'INTERSECTION',
    description: 'Vibrant commercial & residential delivery sector in Miramar.',
  },
];

export const WELLINGTON_ROAD_SEGMENTS: RoadSegment[] = [
  {
    id: 'seg-wel-1',
    fromNodeId: 'node-wel-1-1',
    toNodeId: 'node-wel-1-2',
    roadName: 'Te Aro Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-2',
    fromNodeId: 'node-wel-1-2',
    toNodeId: 'node-wel-1-3',
    roadName: 'Te Aro Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-3',
    fromNodeId: 'node-wel-2-1',
    toNodeId: 'node-wel-2-2',
    roadName: 'Wellington Waterfront Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-4',
    fromNodeId: 'node-wel-2-2',
    toNodeId: 'node-wel-2-3',
    roadName: 'Wellington Waterfront Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-5',
    fromNodeId: 'node-wel-3-1',
    toNodeId: 'node-wel-3-2',
    roadName: 'Thorndon Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-6',
    fromNodeId: 'node-wel-3-2',
    toNodeId: 'node-wel-3-3',
    roadName: 'Thorndon Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-7',
    fromNodeId: 'node-wel-4-1',
    toNodeId: 'node-wel-4-2',
    roadName: 'Mount Victoria Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-8',
    fromNodeId: 'node-wel-4-2',
    toNodeId: 'node-wel-4-3',
    roadName: 'Mount Victoria Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-9',
    fromNodeId: 'node-wel-5-1',
    toNodeId: 'node-wel-5-2',
    roadName: 'Newtown Wellington Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-10',
    fromNodeId: 'node-wel-5-2',
    toNodeId: 'node-wel-5-3',
    roadName: 'Newtown Wellington Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-11',
    fromNodeId: 'node-wel-6-1',
    toNodeId: 'node-wel-6-2',
    roadName: 'Kelburn Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-12',
    fromNodeId: 'node-wel-6-2',
    toNodeId: 'node-wel-6-3',
    roadName: 'Kelburn Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-13',
    fromNodeId: 'node-wel-7-1',
    toNodeId: 'node-wel-7-2',
    roadName: 'Courtenay Place Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-14',
    fromNodeId: 'node-wel-7-2',
    toNodeId: 'node-wel-7-3',
    roadName: 'Courtenay Place Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-15',
    fromNodeId: 'node-wel-8-1',
    toNodeId: 'node-wel-8-2',
    roadName: 'Oriental Bay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-16',
    fromNodeId: 'node-wel-8-2',
    toNodeId: 'node-wel-8-3',
    roadName: 'Oriental Bay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-17',
    fromNodeId: 'node-wel-9-1',
    toNodeId: 'node-wel-9-2',
    roadName: 'Island Bay Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-18',
    fromNodeId: 'node-wel-9-2',
    toNodeId: 'node-wel-9-3',
    roadName: 'Island Bay Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-19',
    fromNodeId: 'node-wel-10-1',
    toNodeId: 'node-wel-10-2',
    roadName: 'Miramar Sector 1 Arterial Road',
    distanceMeters: 570,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.2,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
  {
    id: 'seg-wel-20',
    fromNodeId: 'node-wel-10-2',
    toNodeId: 'node-wel-10-3',
    roadName: 'Miramar Sector 2 Arterial Road',
    distanceMeters: 690,
    speedLimitKmh: 40,
    baseCongestionFactor: 1.3,
    isOneWay: false,
    surfaceType: 'ASPHALT',
  },
];
