export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  RESTAURANT: 'RESTAURANT',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
  ADMIN: 'ADMIN',
} as const;

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  RESTAURANT_ACCEPTED: 'RESTAURANT_ACCEPTED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  DELIVERY_ACCEPTED: 'DELIVERY_ACCEPTED',
  ARRIVED_AT_RESTAURANT: 'ARRIVED_AT_RESTAURANT',
  PICKED_UP: 'PICKED_UP',
  ON_THE_WAY: 'ON_THE_WAY',
  DELIVERED: 'DELIVERED',
  RESTAURANT_REJECTED: 'RESTAURANT_REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const PAYMENT_METHODS = {
  CASH_ON_DELIVERY: 'CASH_ON_DELIVERY',
  ONLINE_DEMO_PAY: 'ONLINE_DEMO_PAY',
} as const;

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export const NOTIFICATION_TYPES = {
  ORDER_STATUS: 'ORDER_STATUS',
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  DELIVERY_UPDATE: 'DELIVERY_UPDATE',
  PAYMENT: 'PAYMENT',
  SYSTEM: 'SYSTEM',
  PROMO: 'PROMO',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const DEFAULT_COORDINATES = {
  // Center of Bangalore (tech hub / demo metropolis)
  LATITUDE: 12.9716,
  LONGITUDE: 77.5946,
  CITY: 'Bengaluru',
  STATE: 'Karnataka',
};
