/**
 * QuickBite Recipe & Culinary Catalog — Italian Gelateria & Frozen Desserts
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const ARTISANALGELATO_RECIPES: RecipeItem[] = [
  {
    id: 'dish-art-1',
    name: 'Bronte Sicilian Pistachio Gelato Tub (350ml)',
    cuisine: 'Desserts',
    category: 'Artisanal Specialty',
    price: 380.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Ultra-creamy churned gelato made with 100% pure stone-ground Sicilian Bronte PDO pistachio paste.',
    caloriesKcal: 348,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: ["Dairy"],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-art-2',
    name: 'Piedmont Roasted Hazelnut (Nocciola) Gelato',
    cuisine: 'Desserts',
    category: 'Signature Drinks',
    price: 360.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Slow-churned velvety gelato loaded with caramelized IGP Piedmont hazelnuts.',
    caloriesKcal: 336,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: ["Dairy"],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-art-3',
    name: 'Amalfi Coast Zesty Lemon Sorbetto (Dairy-Free)',
    cuisine: 'Desserts',
    category: 'Chilled Treats',
    price: 290.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Refreshing vegan sorbet crafted from sun-ripened organic Amalfi lemons and pure spring water.',
    caloriesKcal: 294,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-art-4',
    name: 'Madagascan Vanilla & Salted Caramel Swirl',
    cuisine: 'Desserts',
    category: 'Infusions',
    price: 320.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Bourbon vanilla bean gelato swirled with fleur de sel Brittany sea salt caramel ribbon.',
    caloriesKcal: 312,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-art-5',
    name: 'Belgian 70% Dark Chocolate Stracciatella',
    cuisine: 'Desserts',
    category: 'Artisanal Specialty',
    price: 340.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Fior di latte sweet cream gelato studded with crunchy shavings of 70% bittersweet Belgian chocolate.',
    caloriesKcal: 324,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-art-6',
    name: 'Wild Forest Blackberry & Raspberry Sorbet',
    cuisine: 'Desserts',
    category: 'Signature Drinks',
    price: 310.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Vibrant ruby-red sorbet packed with antioxidant-rich mountain berries.',
    caloriesKcal: 306,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
];
