/**
 * QuickBite Recipe & Culinary Catalog — Artisan French Boulangerie & Patisserie
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const ARTISANALBAKERY_RECIPES: RecipeItem[] = [
  {
    id: 'dish-art-1',
    name: 'Flaky Almond Frangipane Croissant',
    cuisine: 'Bakery & Desserts',
    category: 'Signature Item',
    price: 180.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Twice-baked French butter croissant filled with almond frangipane cream and topped with toasted flaked almonds.',
    caloriesKcal: 518,
    proteinGrams: 21.2,
    carbsGrams: 50.6,
    fatsGrams: 19.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-art-2',
    name: 'Classic Pain au Chocolat',
    cuisine: 'Bakery & Desserts',
    category: 'Appetizers',
    price: 160.0,
    prepTimeMinutes: 10,
    isVegetarian: false,
    description: 'Laminated butter pastry dough folded with twin batons of 65% Valrhona dark chocolate.',
    caloriesKcal: 496,
    proteinGrams: 34.0,
    carbsGrams: 49.2,
    fatsGrams: 18.4,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-art-3',
    name: 'Belgian Dark Chocolate Hazelnut Cruffin',
    cuisine: 'Bakery & Desserts',
    category: 'Entrees',
    price: 220.0,
    prepTimeMinutes: 12,
    isVegetarian: false,
    description: 'Hybrid croissant-muffin filled with roasted hazelnut praline and liquid dark chocolate core.',
    caloriesKcal: 562,
    proteinGrams: 37.0,
    carbsGrams: 53.4,
    fatsGrams: 20.8,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-art-4',
    name: 'Artisanal Sourdough Country Loaf (500g)',
    cuisine: 'Bakery & Desserts',
    category: 'Desserts',
    price: 210.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Naturally fermented 36-hour slow proofed rustic loaf with crisp blistered crust and open airy crumb.',
    caloriesKcal: 551,
    proteinGrams: 22.4,
    carbsGrams: 52.7,
    fatsGrams: 20.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-art-5',
    name: 'Madagascan Vanilla Bean Creme Brulee',
    cuisine: 'Bakery & Desserts',
    category: 'Signature Item',
    price: 260.0,
    prepTimeMinutes: 10,
    isVegetarian: false,
    description: 'Rich baked egg custard infused with real vanilla bean pods finished with a crisp caramelized sugar shell.',
    caloriesKcal: 606,
    proteinGrams: 39.0,
    carbsGrams: 56.2,
    fatsGrams: 22.4,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-art-6',
    name: 'French Macaron Gift Box (6 Assorted)',
    cuisine: 'Bakery & Desserts',
    category: 'Appetizers',
    price: 380.0,
    prepTimeMinutes: 5,
    isVegetarian: false,
    description: 'Delicate almond meringue cookies filled with salted caramel, raspberry, pistachio, and dark chocolate ganache.',
    caloriesKcal: 738,
    proteinGrams: 45.0,
    carbsGrams: 64.6,
    fatsGrams: 27.2,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
];
