/**
 * QuickBite Recipe & Culinary Catalog — Lucknowi Awadhi Dum & Galouti Kebabs
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const AWADHINAWABI_RECIPES: RecipeItem[] = [
  {
    id: 'dish-awa-1',
    name: 'Galouti Kebab Melt-in-Mouth Minced Lamb with Sheermal',
    cuisine: 'Awadhi',
    category: 'Signature Specialties',
    price: 490.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Finely tenderized minced lamb patties smoked with cloves and 48 aromatic spices served with saffron bread.',
    caloriesKcal: 879,
    proteinGrams: 52.5,
    carbsGrams: 69.4,
    fatsGrams: 33.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-awa-2',
    name: 'Lucknowi Murgh Awadhi Dum Biryani',
    cuisine: 'Awadhi',
    category: 'Appetizers & Tapas',
    price: 440.0,
    prepTimeMinutes: 30,
    isVegetarian: false,
    description: 'Fragrant long-grain basmati rice cooked on slow dum with marinated chicken, saffron milk, and kewra water.',
    caloriesKcal: 824,
    proteinGrams: 50.0,
    carbsGrams: 66.4,
    fatsGrams: 31.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-awa-3',
    name: 'Kakori Kebab Royal Skewers (4 Pcs)',
    cuisine: 'Awadhi',
    category: 'Main Course',
    price: 520.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Tender minced mutton skewers enriched with khoya, raw papaya, and rose petal paste grilled over coals.',
    caloriesKcal: 912,
    proteinGrams: 54.0,
    carbsGrams: 71.2,
    fatsGrams: 34.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-awa-4',
    name: 'Paneer Pasanda in Rich Cashew Cardamom Gravy',
    cuisine: 'Awadhi',
    category: 'Desserts & Beverages',
    price: 360.0,
    prepTimeMinutes: 20,
    isVegetarian: true,
    description: 'Shallow-fried cottage cheese sandwiches stuffed with khoya and dry fruits cooked in silky cashew reduction.',
    caloriesKcal: 736,
    proteinGrams: 29.4,
    carbsGrams: 61.6,
    fatsGrams: 28.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-awa-5',
    name: 'Ulte Tawe Ka Paratha Saffron Flatbread (2 Pcs)',
    cuisine: 'Awadhi',
    category: 'Signature Specialties',
    price: 160.0,
    prepTimeMinutes: 10,
    isVegetarian: false,
    description: 'Mughlai style paper-thin roomali paratha cooked on inverted iron griddle.',
    caloriesKcal: 516,
    proteinGrams: 36.0,
    carbsGrams: 49.6,
    fatsGrams: 20.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-awa-6',
    name: 'Shahi Tukda Royal Bread Pudding with Rabdi',
    cuisine: 'Awadhi',
    category: 'Appetizers & Tapas',
    price: 240.0,
    prepTimeMinutes: 8,
    isVegetarian: true,
    description: 'Crispy ghee-fried bread slices soaked in saffron sugar syrup smothered in thick clotted cream rabdi.',
    caloriesKcal: 604,
    proteinGrams: 24.6,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
