/**
 * QuickBite Recipe & Culinary Catalog — Brazilian Churrasco & Feijoada
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const BRAZILIANCHURRASCO_RECIPES: RecipeItem[] = [
  {
    id: 'dish-bra-1',
    name: 'Picanha Prime Rump Steak (300g)',
    cuisine: 'Brazilian',
    category: 'Signature Specialties',
    price: 590.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Charcoal grilled prime cut of beef seasoned solely with coarse sea salt served with farofa and chimichurri.',
    caloriesKcal: 989,
    proteinGrams: 57.5,
    carbsGrams: 75.4,
    fatsGrams: 37.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-bra-2',
    name: 'Traditional Brazilian Feijoada Black Bean Stew',
    cuisine: 'Brazilian',
    category: 'Appetizers & Tapas',
    price: 480.0,
    prepTimeMinutes: 28,
    isVegetarian: false,
    description: 'Rich slow-cooked black bean stew with smoked pork ribs, linguiça sausage, collard greens, and orange slices.',
    caloriesKcal: 868,
    proteinGrams: 52.0,
    carbsGrams: 68.8,
    fatsGrams: 33.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-bra-3',
    name: 'Pão de Queijo Baked Cheese Bread (8 Pcs)',
    cuisine: 'Brazilian',
    category: 'Main Course',
    price: 240.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Warm chewy gluten-free cassava rolls baked with Brazilian Minas cured cheese.',
    caloriesKcal: 604,
    proteinGrams: 24.6,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-bra-4',
    name: 'Coxinha Crispy Shredded Chicken Croquettes',
    cuisine: 'Brazilian',
    category: 'Desserts & Beverages',
    price: 280.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Teardrop-shaped fried dough fritters stuffed with seasoned shredded chicken and catupiry cream cheese.',
    caloriesKcal: 648,
    proteinGrams: 42.0,
    carbsGrams: 56.8,
    fatsGrams: 25.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-bra-5',
    name: 'Moqueca Baiana Seafood Coconut Stew',
    cuisine: 'Brazilian',
    category: 'Signature Specialties',
    price: 540.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Fresh sea bass and tiger prawns simmered in dende palm oil, coconut milk, bell peppers, and fresh cilantro.',
    caloriesKcal: 934,
    proteinGrams: 55.0,
    carbsGrams: 72.4,
    fatsGrams: 35.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-bra-6',
    name: 'Brigadeiros Artisanal Chocolate Truffles (6 Pcs)',
    cuisine: 'Brazilian',
    category: 'Appetizers & Tapas',
    price: 190.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Rich condensed milk and Dutch cocoa fudge balls rolled in Belgian dark chocolate sprinkles.',
    caloriesKcal: 549,
    proteinGrams: 22.6,
    carbsGrams: 51.4,
    fatsGrams: 21.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
