/**
 * QuickBite Recipe & Culinary Catalog — Jamaican Jerk Pit BBQ & Stews
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const CARIBBEANJERK_RECIPES: RecipeItem[] = [
  {
    id: 'dish-car-1',
    name: 'Authentic Smokehouse Jamaican Jerk Chicken',
    cuisine: 'Caribbean',
    category: 'Signature Specialties',
    price: 440.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Chicken quarters marinated in Scotch bonnet peppers, allspice pimento berries, and thyme, smoked over allspice wood.',
    caloriesKcal: 824,
    proteinGrams: 50.0,
    carbsGrams: 66.4,
    fatsGrams: 31.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-car-2',
    name: 'Curry Goat with Rice and Gunjgu Peas',
    cuisine: 'Caribbean',
    category: 'Appetizers & Tapas',
    price: 490.0,
    prepTimeMinutes: 30,
    isVegetarian: false,
    description: 'Tender bone-in goat meat slow-braised in Jamaican yellow curry powder, thyme, and Scotch bonnet peppers.',
    caloriesKcal: 879,
    proteinGrams: 52.5,
    carbsGrams: 69.4,
    fatsGrams: 33.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-car-3',
    name: 'Jamaican Beef Patty Deluxe (2 Pcs)',
    cuisine: 'Caribbean',
    category: 'Main Course',
    price: 220.0,
    prepTimeMinutes: 10,
    isVegetarian: false,
    description: 'Flaky golden turmeric pastry turnover filled with spicy seasoned ground beef.',
    caloriesKcal: 582,
    proteinGrams: 39.0,
    carbsGrams: 53.2,
    fatsGrams: 22.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-car-4',
    name: 'Sweet Fried Plantains (Maduros)',
    cuisine: 'Caribbean',
    category: 'Desserts & Beverages',
    price: 180.0,
    prepTimeMinutes: 8,
    isVegetarian: false,
    description: 'Ripe sweet yellow plantains pan-fried in coconut oil until caramelized and golden brown.',
    caloriesKcal: 538,
    proteinGrams: 37.0,
    carbsGrams: 50.8,
    fatsGrams: 21.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-car-5',
    name: 'Brown Stew Red Snapper Fish',
    cuisine: 'Caribbean',
    category: 'Signature Specialties',
    price: 520.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Fried whole red snapper braised in a savory sweet tomato and bell pepper reduction.',
    caloriesKcal: 912,
    proteinGrams: 54.0,
    carbsGrams: 71.2,
    fatsGrams: 34.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-car-6',
    name: 'Caribbean Rum Cake with Vanilla Bean Glaze',
    cuisine: 'Caribbean',
    category: 'Appetizers & Tapas',
    price: 240.0,
    prepTimeMinutes: 8,
    isVegetarian: false,
    description: 'Rich dark fruit cake infused with aged dark rum and molasses.',
    caloriesKcal: 604,
    proteinGrams: 40.0,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
