/**
 * QuickBite Recipe & Culinary Catalog — Authentic Chettinad Karaikudi Spices
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const CHETTINADROYAL_RECIPES: RecipeItem[] = [
  {
    id: 'dish-che-1',
    name: 'Chettinad Pepper Chicken Dry',
    cuisine: 'Chettinad',
    category: 'Signature Specialties',
    price: 390.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Country chicken tossed with crushed black tellicherry peppercorns, curry leaves, and freshly ground Chettinad masala.',
    caloriesKcal: 769,
    proteinGrams: 47.5,
    carbsGrams: 63.4,
    fatsGrams: 29.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-che-2',
    name: 'Karaikudi Erappa Prawn Masala',
    cuisine: 'Chettinad',
    category: 'Appetizers & Tapas',
    price: 460.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Tiger prawns simmered in shallot, garlic, fennel, and coconut paste with stone flower and star anise.',
    caloriesKcal: 846,
    proteinGrams: 51.0,
    carbsGrams: 67.6,
    fatsGrams: 32.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-che-3',
    name: 'Ennai Kathirikai Stuffed Baby Brinjal',
    cuisine: 'Chettinad',
    category: 'Main Course',
    price: 290.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Small purple brinjals stuffed with roasted peanut, sesame, and coriander paste cooked in tangy tamarind gravy.',
    caloriesKcal: 659,
    proteinGrams: 42.5,
    carbsGrams: 57.4,
    fatsGrams: 25.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-che-4',
    name: 'Chettinad Kozhi Biryani with Seeraga Samba',
    cuisine: 'Chettinad',
    category: 'Desserts & Beverages',
    price: 420.0,
    prepTimeMinutes: 28,
    isVegetarian: false,
    description: 'Aromatic short-grain seeraga samba rice cooked with country chicken, curd, and hand-ground spices.',
    caloriesKcal: 802,
    proteinGrams: 49.0,
    carbsGrams: 65.2,
    fatsGrams: 30.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-che-5',
    name: 'Vazhaipoo Banana Flower Vadai (6 Pcs)',
    cuisine: 'Chettinad',
    category: 'Signature Specialties',
    price: 220.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Crispy spiced lentil fritters studded with finely chopped banana blossom petals and fennel.',
    caloriesKcal: 582,
    proteinGrams: 39.0,
    carbsGrams: 53.2,
    fatsGrams: 22.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-che-6',
    name: 'Kavanarisi Black Rice Sweet Pudding',
    cuisine: 'Chettinad',
    category: 'Appetizers & Tapas',
    price: 240.0,
    prepTimeMinutes: 12,
    isVegetarian: true,
    description: 'Traditional Chettinad black sticky rice cooked in rich milk, jaggery, cardamom, and roasted cashews.',
    caloriesKcal: 604,
    proteinGrams: 24.6,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
