/**
 * QuickBite Recipe & Culinary Catalog — Zero-Proof Botanical Craft Mocktails
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const CRAFTMOCKTAILS_RECIPES: RecipeItem[] = [
  {
    id: 'dish-cra-1',
    name: 'Smoked Rosemary Grapefruit Paloma Spritz',
    cuisine: 'Beverages',
    category: 'Artisanal Specialty',
    price: 240.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Fresh ruby red grapefruit juice, smoked organic rosemary sprig, lime, and sparkling alkaline soda water.',
    caloriesKcal: 264,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-cra-2',
    name: 'Kaffir Lime & Lemongrass Thai Cooler',
    cuisine: 'Beverages',
    category: 'Signature Drinks',
    price: 210.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Bruised kaffir lime leaves, fresh lemongrass syrup, coconut water, and crushed ice.',
    caloriesKcal: 246,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-cra-3',
    name: 'Wild Hibiscus Rose & Cardamom Fizz',
    cuisine: 'Beverages',
    category: 'Chilled Treats',
    price: 220.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Brewed Egyptian hibiscus calyces, edible rose petals, crushed green cardamom, and tonic.',
    caloriesKcal: 252,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-cra-4',
    name: 'Cucumber Basil Jalapeño Smash',
    cuisine: 'Beverages',
    category: 'Infusions',
    price: 230.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Muddled English cucumber, Genovese sweet basil, jalapeño slice, and cold-pressed apple cider.',
    caloriesKcal: 258,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-cra-5',
    name: 'Yuzu Ginger Matcha Sparkling Tonic',
    cuisine: 'Beverages',
    category: 'Artisanal Specialty',
    price: 260.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Japanese ceremonial grade Uji matcha whisked over fresh yuzu juice and spicy ginger beer.',
    caloriesKcal: 276,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-cra-6',
    name: 'Midnight Passionfruit & Butterfly Pea Tea',
    cuisine: 'Beverages',
    category: 'Signature Drinks',
    price: 240.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Color-shifting blue butterfly pea flower tea layered with golden passionfruit nectar and mint.',
    caloriesKcal: 264,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
];
