/**
 * QuickBite Recipe & Culinary Catalog — Ethiopian Injera & Spicy Wot
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const ETHIOPIANKITCHEN_RECIPES: RecipeItem[] = [
  {
    id: 'dish-eth-1',
    name: 'Doro Wot Spicy Chicken Drumstick Stew',
    cuisine: 'Ethiopian',
    category: 'Signature Specialties',
    price: 460.0,
    prepTimeMinutes: 28,
    isVegetarian: false,
    description: 'Slow-simmered chicken drumsticks in fiery berbere spice paste, niter kibbeh spiced butter, and hard-boiled egg.',
    caloriesKcal: 846,
    proteinGrams: 51.0,
    carbsGrams: 67.6,
    fatsGrams: 32.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-eth-2',
    name: 'Misir Wot Red Lentil Puree with Injera',
    cuisine: 'Ethiopian',
    category: 'Appetizers & Tapas',
    price: 320.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Silky red lentils cooked with garlic, ginger, and berbere served atop warm fermented sourdough teff injera.',
    caloriesKcal: 692,
    proteinGrams: 44.0,
    carbsGrams: 59.2,
    fatsGrams: 26.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-eth-3',
    name: 'Tibs Sautéed Beef Strips with Rosemary',
    cuisine: 'Ethiopian',
    category: 'Main Course',
    price: 440.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Tender beef cubes flash-fried with fresh rosemary, jalapeños, onions, and clarified Ethiopian spiced butter.',
    caloriesKcal: 824,
    proteinGrams: 50.0,
    carbsGrams: 66.4,
    fatsGrams: 31.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-eth-4',
    name: 'Atkilt Wot Cabbage, Potato & Carrot Medley',
    cuisine: 'Ethiopian',
    category: 'Desserts & Beverages',
    price: 280.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Mild turmeric, ginger, and garlic braised vegetables served on injera flatbread.',
    caloriesKcal: 648,
    proteinGrams: 42.0,
    carbsGrams: 56.8,
    fatsGrams: 25.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-eth-5',
    name: 'Gomen Braised Collard Greens with Spices',
    cuisine: 'Ethiopian',
    category: 'Signature Specialties',
    price: 240.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Tender slow-braised collard greens sautéed with onions, garlic, and cardamom.',
    caloriesKcal: 604,
    proteinGrams: 40.0,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-eth-6',
    name: 'Traditional Ethiopian Spiced Tea with Cloves',
    cuisine: 'Ethiopian',
    category: 'Appetizers & Tapas',
    price: 140.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Black tea brewed with cinnamon bark, crushed green cardamom pods, and whole cloves.',
    caloriesKcal: 494,
    proteinGrams: 20.6,
    carbsGrams: 48.4,
    fatsGrams: 19.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
