/**
 * QuickBite Recipe & Culinary Catalog — Bavarian Schnitzel & Artisan Sausages
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const GERMANBIERGARTEN_RECIPES: RecipeItem[] = [
  {
    id: 'dish-ger-1',
    name: 'Crispy Veal Wiener Schnitzel with Potato Salad',
    cuisine: 'German',
    category: 'Signature Specialties',
    price: 540.0,
    prepTimeMinutes: 20,
    isVegetarian: true,
    description: 'Pounded thin milk-fed veal cutlet breaded in fine crumbs fried golden served with warm Bavarian potato salad.',
    caloriesKcal: 934,
    proteinGrams: 36.6,
    carbsGrams: 72.4,
    fatsGrams: 35.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-ger-2',
    name: 'Bratwurst & Thuringer Sausage Platter (2 Pcs)',
    cuisine: 'German',
    category: 'Appetizers & Tapas',
    price: 420.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Grilled artisan German pork sausages served with tangy sauerkraut, sweet mustard, and fresh pretzel.',
    caloriesKcal: 802,
    proteinGrams: 49.0,
    carbsGrams: 65.2,
    fatsGrams: 30.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-ger-3',
    name: 'Crispy Bavarian Pork Knuckle (Schweinshaxe)',
    cuisine: 'German',
    category: 'Main Course',
    price: 640.0,
    prepTimeMinutes: 35,
    isVegetarian: false,
    description: 'Slow-roasted pork shank with shatteringly crisp skin served with dark beer gravy and bread dumplings.',
    caloriesKcal: 1044,
    proteinGrams: 60.0,
    carbsGrams: 78.4,
    fatsGrams: 39.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-ger-4',
    name: 'Handmade Spätzle Noodles with Melted Emmental Cheese',
    cuisine: 'German',
    category: 'Desserts & Beverages',
    price: 340.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Soft egg noodles pan-sautéed with sweet caramelized onions and bubbly Alpine Emmental cheese.',
    caloriesKcal: 714,
    proteinGrams: 45.0,
    carbsGrams: 60.4,
    fatsGrams: 27.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-ger-5',
    name: 'Warm Bavarian Pretzel with Obatzda Cheese Dip',
    cuisine: 'German',
    category: 'Signature Specialties',
    price: 220.0,
    prepTimeMinutes: 8,
    isVegetarian: true,
    description: 'Freshly baked lye pretzel sprinkled with rock salt served with Camembert butter dip.',
    caloriesKcal: 582,
    proteinGrams: 23.8,
    carbsGrams: 53.2,
    fatsGrams: 22.8,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-ger-6',
    name: 'Traditional Black Forest Kirsch Cherry Torte',
    cuisine: 'German',
    category: 'Appetizers & Tapas',
    price: 260.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Layers of chocolate sponge soaked in Kirschwasser cherry brandy with whipped cream and sour cherries.',
    caloriesKcal: 626,
    proteinGrams: 25.4,
    carbsGrams: 55.6,
    fatsGrams: 24.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
