/**
 * QuickBite Recipe & Culinary Catalog — Goan Portuguese Coastal Seafood & Curries
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const GOANCOASTAL_RECIPES: RecipeItem[] = [
  {
    id: 'dish-goa-1',
    name: 'Traditional Goan Fish Curry with Coconut & Raw Mango',
    cuisine: 'Goan',
    category: 'Signature Specialties',
    price: 440.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Fresh kingfish steaks simmered in freshly ground coconut, red Byadgi chillies, coriander, and kokum petals.',
    caloriesKcal: 824,
    proteinGrams: 50.0,
    carbsGrams: 66.4,
    fatsGrams: 31.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-goa-2',
    name: 'Goan Pork Vindaloo with Toddy Vinegar',
    cuisine: 'Goan',
    category: 'Appetizers & Tapas',
    price: 460.0,
    prepTimeMinutes: 28,
    isVegetarian: false,
    description: 'Pork shoulder slow-cooked in fiery garlic, Kashmiri red chilli paste, cinnamon, and aged palm vinegar.',
    caloriesKcal: 846,
    proteinGrams: 51.0,
    carbsGrams: 67.6,
    fatsGrams: 32.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-goa-3',
    name: 'Prawn Balchão Spicy Pickled Relish with Pao',
    cuisine: 'Goan',
    category: 'Main Course',
    price: 420.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Pan-seared prawns cooked in a rich sweet, sour, and spicy tomato-vinegar reduction with crusty local poee bread.',
    caloriesKcal: 802,
    proteinGrams: 49.0,
    carbsGrams: 65.2,
    fatsGrams: 30.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-goa-4',
    name: 'Goan Crab Xec Xec with Roasted Coconut',
    cuisine: 'Goan',
    category: 'Desserts & Beverages',
    price: 520.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Whole mud crabs braised in heavily roasted coconut, star anise, nutmeg, and clove infused gravy.',
    caloriesKcal: 912,
    proteinGrams: 54.0,
    carbsGrams: 71.2,
    fatsGrams: 34.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-goa-5',
    name: 'Kismur Dried Prawn & Fresh Coconut Salad',
    cuisine: 'Goan',
    category: 'Signature Specialties',
    price: 210.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Crispy fried dried baby prawns tossed with grated fresh coconut, finely chopped onions, and lemon juice.',
    caloriesKcal: 571,
    proteinGrams: 23.4,
    carbsGrams: 52.6,
    fatsGrams: 22.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-goa-6',
    name: 'Authentic Goan Bebinca Layered Pudding',
    cuisine: 'Goan',
    category: 'Appetizers & Tapas',
    price: 280.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Seven-layered baked dessert made with rich coconut milk, egg yolks, flour, sugar, and pure ghee.',
    caloriesKcal: 648,
    proteinGrams: 26.2,
    carbsGrams: 56.8,
    fatsGrams: 25.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
