/**
 * QuickBite Recipe & Culinary Catalog — Aegean Greek Souvlaki & Coastal Seafood
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const GREEKMEDITERRANEAN_RECIPES: RecipeItem[] = [
  {
    id: 'dish-gre-1',
    name: 'Greek Souvlaki Lamb Skewers with Tzatziki',
    cuisine: 'Greek',
    category: 'Signature Item',
    price: 490.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Oregano and lemon marinated lamb skewers served with cucumber garlic tzatziki and warm pita.',
    caloriesKcal: 859,
    proteinGrams: 50.5,
    carbsGrams: 72.3,
    fatsGrams: 31.6,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-gre-2',
    name: 'Authentic Baked Greek Moussaka',
    cuisine: 'Greek',
    category: 'Appetizers',
    price: 440.0,
    prepTimeMinutes: 30,
    isVegetarian: false,
    description: 'Layered baked casserole of spiced minced beef, roasted aubergines, potatoes, and velvety béchamel crust.',
    caloriesKcal: 804,
    proteinGrams: 48.0,
    carbsGrams: 68.8,
    fatsGrams: 29.6,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-gre-3',
    name: 'Traditional Horiatiki Greek Village Salad',
    cuisine: 'Greek',
    category: 'Entrees',
    price: 320.0,
    prepTimeMinutes: 12,
    isVegetarian: true,
    description: 'Heirloom tomatoes, crisp cucumbers, kalamata olives, capers, and a block of aged Greek feta drizzled in olive oil.',
    caloriesKcal: 672,
    proteinGrams: 26.8,
    carbsGrams: 60.4,
    fatsGrams: 24.8,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-gre-4',
    name: 'Spanakopita Spinach & Feta Filo Pie',
    cuisine: 'Greek',
    category: 'Desserts',
    price: 310.0,
    prepTimeMinutes: 20,
    isVegetarian: true,
    description: 'Crispy layered filo pastry stuffed with sautéed wild spinach, spring onions, dill, and barrel-aged feta.',
    caloriesKcal: 661,
    proteinGrams: 26.4,
    carbsGrams: 59.7,
    fatsGrams: 24.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-gre-5',
    name: 'Crispy Calamari Rings with Lemon Caper Aioli',
    cuisine: 'Greek',
    category: 'Signature Item',
    price: 390.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Tender squid rings dusted in seasoned flour fried golden served with house lemon garlic dip.',
    caloriesKcal: 749,
    proteinGrams: 45.5,
    carbsGrams: 65.3,
    fatsGrams: 27.6,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-gre-6',
    name: 'Greek Orange Honey Semolina Cake (Portokalopita)',
    cuisine: 'Greek',
    category: 'Appetizers',
    price: 240.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Moist baked filo cake soaked in sweet orange syrup and Greek wild thyme honey.',
    caloriesKcal: 584,
    proteinGrams: 23.6,
    carbsGrams: 54.8,
    fatsGrams: 21.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
];
