/**
 * QuickBite Recipe & Culinary Catalog — Hawaiian Fresh Poke & Grill
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const HAWAIIANPOKE_RECIPES: RecipeItem[] = [
  {
    id: 'dish-haw-1',
    name: 'Ahi Tuna Classic Shoyu Poke Bowl',
    cuisine: 'Hawaiian',
    category: 'Signature Specialties',
    price: 540.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Fresh raw yellowfin ahi tuna cubes tossed in sesame shoyu, green scallions, sweet onions, and seaweed over warm sushi rice.',
    caloriesKcal: 934,
    proteinGrams: 55.0,
    carbsGrams: 72.4,
    fatsGrams: 35.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-haw-2',
    name: 'Spicy Salmon Crunch Poke Bowl',
    cuisine: 'Hawaiian',
    category: 'Appetizers & Tapas',
    price: 490.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Atlantic salmon, spicy sriracha mayo, tobiko flying fish roe, cucumber, and crispy fried shallots.',
    caloriesKcal: 879,
    proteinGrams: 52.5,
    carbsGrams: 69.4,
    fatsGrams: 33.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-haw-3',
    name: 'Hawaiian Kalua Slow-Smoked Pulled Pork',
    cuisine: 'Hawaiian',
    category: 'Main Course',
    price: 420.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Tender shredded pork smoked with kiawe wood and sea salt served with steamed jasmine rice and macaroni salad.',
    caloriesKcal: 802,
    proteinGrams: 49.0,
    carbsGrams: 65.2,
    fatsGrams: 30.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-haw-4',
    name: 'Loco Moco Comfort Burger & Gravy Bowl',
    cuisine: 'Hawaiian',
    category: 'Desserts & Beverages',
    price: 390.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Grilled beef burger patty over white rice smothered in rich brown mushroom gravy and topped with sunny egg.',
    caloriesKcal: 769,
    proteinGrams: 47.5,
    carbsGrams: 63.4,
    fatsGrams: 29.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-haw-5',
    name: 'Furikake Chicken Katsu Rice Bowl',
    cuisine: 'Hawaiian',
    category: 'Signature Specialties',
    price: 380.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Crispy panko-breaded fried chicken tossed in sweet teriyaki glaze and toasted seaweed sesame furikake.',
    caloriesKcal: 758,
    proteinGrams: 47.0,
    carbsGrams: 62.8,
    fatsGrams: 29.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-haw-6',
    name: 'Haupia Hawaiian Coconut Milk Pudding',
    cuisine: 'Hawaiian',
    category: 'Appetizers & Tapas',
    price: 190.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Traditional gelatin-free chilled pudding made from pure rich coconut milk and raw cane sugar.',
    caloriesKcal: 549,
    proteinGrams: 22.6,
    carbsGrams: 51.4,
    fatsGrams: 21.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
