/**
 * QuickBite Recipe & Culinary Catalog — Artisanal Tokyo Sushi & Traditional Ramen
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const JAPANESESUSHIRAMEN_RECIPES: RecipeItem[] = [
  {
    id: 'dish-jap-1',
    name: 'Spicy Bluefin Tuna Crunch Roll',
    cuisine: 'Japanese',
    category: 'Signature Item',
    price: 620.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Sashimi-grade tuna, spicy sriracha aioli, cucumber, tempura flakes, and sweet unagi drizzle.',
    caloriesKcal: 1002,
    proteinGrams: 57.0,
    carbsGrams: 81.4,
    fatsGrams: 36.8,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-jap-2',
    name: 'Hokkaido Scallop Nigiri (4 Pcs)',
    cuisine: 'Japanese',
    category: 'Appetizers',
    price: 580.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Sweet wild Hokkaido sea scallops lightly torched with yuzu truffle soy and sea salt.',
    caloriesKcal: 958,
    proteinGrams: 55.0,
    carbsGrams: 78.6,
    fatsGrams: 35.2,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-jap-3',
    name: 'Tokyo Shoyu Ramen with Chashu Pork',
    cuisine: 'Japanese',
    category: 'Entrees',
    price: 480.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Clear dashi and chicken broth seasoned with aged shoyu soy, springy noodles, soft-boiled egg, and bamboo shoots.',
    caloriesKcal: 848,
    proteinGrams: 50.0,
    carbsGrams: 71.6,
    fatsGrams: 31.2,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-jap-4',
    name: 'Crispy Chicken Katsu Curry with Steamed Rice',
    cuisine: 'Japanese',
    category: 'Desserts',
    price: 420.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Panko breaded fried chicken cutlet smothered in rich Japanese aromatic curry sauce.',
    caloriesKcal: 782,
    proteinGrams: 47.0,
    carbsGrams: 67.4,
    fatsGrams: 28.8,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-jap-5',
    name: 'Charred Edamame with Togarashi Sea Salt',
    cuisine: 'Japanese',
    category: 'Signature Item',
    price: 240.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Steamed young soybean pods pan-charred in sesame oil with Japanese seven-spice blend.',
    caloriesKcal: 584,
    proteinGrams: 23.6,
    carbsGrams: 54.8,
    fatsGrams: 21.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-jap-6',
    name: 'Matcha Green Tea Crepe Cake',
    cuisine: 'Japanese',
    category: 'Appetizers',
    price: 290.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Twenty delicate layers of handmade matcha crepes layered with light whipped green tea cream.',
    caloriesKcal: 639,
    proteinGrams: 25.6,
    carbsGrams: 58.3,
    fatsGrams: 23.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
];
