/**
 * QuickBite Recipe & Culinary Catalog — Royal Kashmiri Wazwan Feasts
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const KASHMIRIWAZWAN_RECIPES: RecipeItem[] = [
  {
    id: 'dish-kas-1',
    name: 'Wazwan Rista Hand-Pounded Meatballs in Red Gravy',
    cuisine: 'Kashmiri',
    category: 'Signature Specialties',
    price: 520.0,
    prepTimeMinutes: 30,
    isVegetarian: false,
    description: 'Silky hand-pounded mutton meatballs simmered in royal saffron, fennel, and Kashmiri deggi mirch reduction.',
    caloriesKcal: 912,
    proteinGrams: 54.0,
    carbsGrams: 71.2,
    fatsGrams: 34.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kas-2',
    name: 'Wazwan Goshtaba Meatballs in Velvety Yogurt Gravy',
    cuisine: 'Kashmiri',
    category: 'Appetizers & Tapas',
    price: 540.0,
    prepTimeMinutes: 32,
    isVegetarian: false,
    description: 'Delicate mutton meatballs poached in fragrant cardamom, dried mint, and whipped yogurt broth.',
    caloriesKcal: 934,
    proteinGrams: 55.0,
    carbsGrams: 72.4,
    fatsGrams: 35.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kas-3',
    name: 'Tabak Maaz Crisp Fried Lamb Ribs',
    cuisine: 'Kashmiri',
    category: 'Main Course',
    price: 490.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Tender lamb ribs simmered in spiced milk and shallow-fried in clarified desi ghee until golden crisp.',
    caloriesKcal: 879,
    proteinGrams: 52.5,
    carbsGrams: 69.4,
    fatsGrams: 33.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kas-4',
    name: 'Kashmiri Dum Aloo with Hing & Saunf',
    cuisine: 'Kashmiri',
    category: 'Desserts & Beverages',
    price: 290.0,
    prepTimeMinutes: 20,
    isVegetarian: true,
    description: 'Baby potatoes deep-fried and slow-cooked in rich curd gravy flavored with asafoetida and dry ginger powder.',
    caloriesKcal: 659,
    proteinGrams: 26.6,
    carbsGrams: 57.4,
    fatsGrams: 25.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kas-5',
    name: 'Nadru Yakhni Lotus Root in Yogurt Curry',
    cuisine: 'Kashmiri',
    category: 'Signature Specialties',
    price: 320.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Crunchy lotus stem rounds cooked in delicate yogurt gravy tempered with black cumin and cloves.',
    caloriesKcal: 692,
    proteinGrams: 44.0,
    carbsGrams: 59.2,
    fatsGrams: 26.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kas-6',
    name: 'Kashmiri Shahi Kahwa with Almonds & Saffron',
    cuisine: 'Kashmiri',
    category: 'Appetizers & Tapas',
    price: 160.0,
    prepTimeMinutes: 5,
    isVegetarian: false,
    description: 'Green tea brewed with whole green cardamom, cinnamon, saffron strands, and crushed blanched almonds.',
    caloriesKcal: 516,
    proteinGrams: 36.0,
    carbsGrams: 49.6,
    fatsGrams: 20.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
