/**
 * QuickBite Recipe & Culinary Catalog — Korean BBQ & Bibimbap Kitchen
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const KOREANBBQ_RECIPES: RecipeItem[] = [
  {
    id: 'dish-kor-1',
    name: 'Bulgogi Marinated Beef Rice Bowl',
    cuisine: 'Korean',
    category: 'Signature Specialties',
    price: 480.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Thinly sliced prime beef ribeye marinated in sweet soy, Asian pear, sesame oil, and garlic served over rice.',
    caloriesKcal: 868,
    proteinGrams: 52.0,
    carbsGrams: 68.8,
    fatsGrams: 33.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kor-2',
    name: 'Crispy Korean Fried Chicken with Yangnyeom Glaze',
    cuisine: 'Korean',
    category: 'Appetizers & Tapas',
    price: 420.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Double-fried crunchy chicken wings tossed in sticky sweet and spicy gochujang chilli glaze.',
    caloriesKcal: 802,
    proteinGrams: 49.0,
    carbsGrams: 65.2,
    fatsGrams: 30.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kor-3',
    name: 'Dolsot Sizzling Bibimbap with Fried Egg',
    cuisine: 'Korean',
    category: 'Main Course',
    price: 390.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Warm rice topped with seasoned namul vegetables, gochujang paste, sliced beef, and sunny egg.',
    caloriesKcal: 769,
    proteinGrams: 47.5,
    carbsGrams: 63.4,
    fatsGrams: 29.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kor-4',
    name: 'Kimchi Jjigae Spicy Pork Stew',
    cuisine: 'Korean',
    category: 'Desserts & Beverages',
    price: 360.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Rich fermented aged kimchi stew simmered with pork belly, tofu cubes, scallions, and anchovy stock.',
    caloriesKcal: 736,
    proteinGrams: 46.0,
    carbsGrams: 61.6,
    fatsGrams: 28.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kor-5',
    name: 'Seafood Scallion Pancake (Haemul Pajeon)',
    cuisine: 'Korean',
    category: 'Signature Specialties',
    price: 320.0,
    prepTimeMinutes: 15,
    isVegetarian: true,
    description: 'Crispy pan-fried savoury pancake studded with calamari, prawns, and long spring scallions.',
    caloriesKcal: 692,
    proteinGrams: 27.8,
    carbsGrams: 59.2,
    fatsGrams: 26.8,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-kor-6',
    name: 'Sweet Honey Hotteok Korean Street Pancakes',
    cuisine: 'Korean',
    category: 'Appetizers & Tapas',
    price: 210.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Warm golden griddle cakes filled with melted brown sugar, roasted peanuts, and cinnamon syrup.',
    caloriesKcal: 571,
    proteinGrams: 23.4,
    carbsGrams: 52.6,
    fatsGrams: 22.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
