/**
 * QuickBite Recipe & Culinary Catalog — Middle Eastern Mezze & Charcoal Grill
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const LEBANESEMEZZE_RECIPES: RecipeItem[] = [
  {
    id: 'dish-leb-1',
    name: 'Charcoal Chicken Shish Tawook Platter',
    cuisine: 'Lebanese',
    category: 'Signature Item',
    price: 460.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Tender yogurt, lemon, and garlic marinated chicken breast skewers grilled over natural charcoal with toum dip.',
    caloriesKcal: 826,
    proteinGrams: 49.0,
    carbsGrams: 70.2,
    fatsGrams: 30.4,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-leb-2',
    name: 'Traditional Silk Hummus with Spiced Lamb',
    cuisine: 'Lebanese',
    category: 'Appetizers',
    price: 360.0,
    prepTimeMinutes: 15,
    isVegetarian: true,
    description: 'Ultra-smooth chickpea tahini dip topped with warm minced lamb, toasted pine nuts, and sumac virgin olive oil.',
    caloriesKcal: 716,
    proteinGrams: 28.4,
    carbsGrams: 63.2,
    fatsGrams: 26.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-leb-3',
    name: 'Crispy Falafel Pita Wrap Deluxe',
    cuisine: 'Lebanese',
    category: 'Entrees',
    price: 280.0,
    prepTimeMinutes: 15,
    isVegetarian: true,
    description: 'Golden herbed chickpea falafels with pickled turnips, tahini sauce, fresh mint, and tomatoes in fresh flatbread.',
    caloriesKcal: 628,
    proteinGrams: 25.2,
    carbsGrams: 57.6,
    fatsGrams: 23.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-leb-4',
    name: 'Smoky Moutabal Eggplant Dip with Warm Pita',
    cuisine: 'Lebanese',
    category: 'Desserts',
    price: 290.0,
    prepTimeMinutes: 12,
    isVegetarian: false,
    description: 'Fire-roasted smoky aubergines whipped with garlic, lemon, tahini, and pomegranate seeds.',
    caloriesKcal: 639,
    proteinGrams: 40.5,
    carbsGrams: 58.3,
    fatsGrams: 23.6,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-leb-5',
    name: 'Grilled Halloumi Cheese & Watermelon Salad',
    cuisine: 'Lebanese',
    category: 'Signature Item',
    price: 340.0,
    prepTimeMinutes: 12,
    isVegetarian: true,
    description: 'Seared Cypriot sheep milk halloumi with fresh mint, wild arugula, and pomegranate reduction.',
    caloriesKcal: 694,
    proteinGrams: 27.6,
    carbsGrams: 61.8,
    fatsGrams: 25.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-leb-6',
    name: 'Baklava Assortment with Pistachio & Honey',
    cuisine: 'Lebanese',
    category: 'Appetizers',
    price: 260.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Flaky filo pastry sheets layered with crushed emerald pistachios and infused with orange blossom syrup.',
    caloriesKcal: 606,
    proteinGrams: 24.4,
    carbsGrams: 56.2,
    fatsGrams: 22.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
];
