/**
 * QuickBite Recipe & Culinary Catalog — Malvani Konkan Seafood & Saoji Curries
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const MAHARASHTRIANMALVANI_RECIPES: RecipeItem[] = [
  {
    id: 'dish-mah-1',
    name: 'Malvani Surmai Fish Fry with Rava Crust',
    cuisine: 'Maharashtrian',
    category: 'Signature Specialties',
    price: 460.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Kingfish steak marinated in fiery Malvani red masala, coated in semolina and shallow fried crisp.',
    caloriesKcal: 846,
    proteinGrams: 51.0,
    carbsGrams: 67.6,
    fatsGrams: 32.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mah-2',
    name: 'Kolhapuri Tambda Rassa & Pandhra Rassa Set',
    cuisine: 'Maharashtrian',
    category: 'Appetizers & Tapas',
    price: 480.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Fiery red mutton broth and delicate aromatic coconut white broth served with tender mutton sukka.',
    caloriesKcal: 868,
    proteinGrams: 52.0,
    carbsGrams: 68.8,
    fatsGrams: 33.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mah-3',
    name: 'Kanda Batata Poha with Roasted Peanuts',
    cuisine: 'Maharashtrian',
    category: 'Main Course',
    price: 160.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Flattened rice flakes tempered with mustard seeds, turmeric, onions, potatoes, and crunchy peanuts.',
    caloriesKcal: 516,
    proteinGrams: 21.4,
    carbsGrams: 49.6,
    fatsGrams: 20.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mah-4',
    name: 'Misal Pav Spicy Sprouted Bean Curry with Farsan',
    cuisine: 'Maharashtrian',
    category: 'Desserts & Beverages',
    price: 210.0,
    prepTimeMinutes: 12,
    isVegetarian: true,
    description: 'Fiery sprouted moth bean gravy topped with spicy farsan, onions, lemon, and butter-toasted pav bread.',
    caloriesKcal: 571,
    proteinGrams: 23.4,
    carbsGrams: 52.6,
    fatsGrams: 22.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mah-5',
    name: 'Puran Poli with Ghee & Katachi Amti',
    cuisine: 'Maharashtrian',
    category: 'Signature Specialties',
    price: 240.0,
    prepTimeMinutes: 15,
    isVegetarian: true,
    description: 'Sweet whole wheat flatbread stuffed with cooked chana dal and jaggery, served with spicy lentil broth.',
    caloriesKcal: 604,
    proteinGrams: 24.6,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mah-6',
    name: 'Ukdiche Modak Steamed Jaggery Coconut Dumplings (4 Pcs)',
    cuisine: 'Maharashtrian',
    category: 'Appetizers & Tapas',
    price: 260.0,
    prepTimeMinutes: 12,
    isVegetarian: true,
    description: 'Steamed rice flour dumplings stuffed with fresh grated coconut, jaggery, and nutmeg, served with warm ghee.',
    caloriesKcal: 626,
    proteinGrams: 25.4,
    carbsGrams: 55.6,
    fatsGrams: 24.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
