/**
 * QuickBite Recipe & Culinary Catalog — Authentic Mexican Street Tacos & Burritos
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const MEXICANTAQUERIA_RECIPES: RecipeItem[] = [
  {
    id: 'dish-mex-1',
    name: 'Birria Beef Quesatacos with Consome',
    cuisine: 'Mexican',
    category: 'Signature Item',
    price: 420.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Slow-braised shredded beef brisket in dried guajillo chillies folded in dipped corn tortillas with melted oaxaca cheese and dipping broth.',
    caloriesKcal: 782,
    proteinGrams: 47.0,
    carbsGrams: 67.4,
    fatsGrams: 28.8,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-mex-2',
    name: 'Baja Crispy Fish Tacos (3 Pcs)',
    cuisine: 'Mexican',
    category: 'Appetizers',
    price: 380.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Beer-battered sea bass fillets topped with chipotle crema, shredded red cabbage slaw, and fresh pico de gallo.',
    caloriesKcal: 738,
    proteinGrams: 45.0,
    carbsGrams: 64.6,
    fatsGrams: 27.2,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-mex-3',
    name: 'Loaded Carne Asada Burrito Bowl',
    cuisine: 'Mexican',
    category: 'Entrees',
    price: 440.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Flame-grilled flank steak over cilantro lime rice, black beans, roasted corn salsa, guacamole, and sour cream.',
    caloriesKcal: 804,
    proteinGrams: 48.0,
    carbsGrams: 68.8,
    fatsGrams: 29.6,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-mex-4',
    name: 'Smoky Chicken Tinga Enchiladas',
    cuisine: 'Mexican',
    category: 'Desserts',
    price: 360.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Shredded chicken simmered in chipotle adobo sauce rolled in corn tortillas baked under salsa roja and melted jack cheese.',
    caloriesKcal: 716,
    proteinGrams: 44.0,
    carbsGrams: 63.2,
    fatsGrams: 26.4,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-mex-5',
    name: 'Artisanal Guacamole & House Tortilla Chips',
    cuisine: 'Mexican',
    category: 'Signature Item',
    price: 260.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Fresh hand-mashed Hass avocados with diced jalapeños, red onions, fresh lime juice, and sea salt.',
    caloriesKcal: 606,
    proteinGrams: 24.4,
    carbsGrams: 56.2,
    fatsGrams: 22.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-mex-6',
    name: 'Churros with Warm Dulce de Leche Dip',
    cuisine: 'Mexican',
    category: 'Appetizers',
    price: 220.0,
    prepTimeMinutes: 12,
    isVegetarian: true,
    description: 'Crispy golden fried choux pastry dusted in cinnamon sugar served with rich Mexican caramel dip.',
    caloriesKcal: 562,
    proteinGrams: 22.8,
    carbsGrams: 53.4,
    fatsGrams: 20.8,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
];
