/**
 * QuickBite Recipe & Culinary Catalog — Moroccan Clay Tagines & Couscous
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const MOROCCANTAGINE_RECIPES: RecipeItem[] = [
  {
    id: 'dish-mor-1',
    name: 'Slow-Cooked Lamb Shank Tagine with Prunes',
    cuisine: 'Moroccan',
    category: 'Signature Specialties',
    price: 560.0,
    prepTimeMinutes: 35,
    isVegetarian: false,
    description: 'Tender lamb shank braised in clay tagine with ras el hanout spices, caramelized prunes, and toasted almonds.',
    caloriesKcal: 956,
    proteinGrams: 56.0,
    carbsGrams: 73.6,
    fatsGrams: 36.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mor-2',
    name: 'Lemon & Green Olive Chicken Tagine',
    cuisine: 'Moroccan',
    category: 'Appetizers & Tapas',
    price: 460.0,
    prepTimeMinutes: 28,
    isVegetarian: false,
    description: 'Farm chicken stewed with salt-cured Moroccan preserved lemons, cracked green olives, and saffron broth.',
    caloriesKcal: 846,
    proteinGrams: 51.0,
    carbsGrams: 67.6,
    fatsGrams: 32.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mor-3',
    name: 'Steamed Seven Vegetable Couscous Royale',
    cuisine: 'Moroccan',
    category: 'Main Course',
    price: 380.0,
    prepTimeMinutes: 20,
    isVegetarian: true,
    description: 'Hand-rolled fluffy semolina grain steamed over broth topped with zucchini, pumpkin, turnips, and chickpeas.',
    caloriesKcal: 758,
    proteinGrams: 30.2,
    carbsGrams: 62.8,
    fatsGrams: 29.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mor-4',
    name: 'Crispy Chicken Pastilla Filo Pie with Almonds',
    cuisine: 'Moroccan',
    category: 'Desserts & Beverages',
    price: 420.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Flaky layered pastry stuffed with spiced shredded chicken and almonds, dusted with powdered sugar and cinnamon.',
    caloriesKcal: 802,
    proteinGrams: 49.0,
    carbsGrams: 65.2,
    fatsGrams: 30.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mor-5',
    name: 'Moroccan Harira Tomato & Lentil Soup',
    cuisine: 'Moroccan',
    category: 'Signature Specialties',
    price: 240.0,
    prepTimeMinutes: 15,
    isVegetarian: true,
    description: 'Hearty comforting soup of ripe tomatoes, chickpeas, lentils, fresh coriander, and ginger.',
    caloriesKcal: 604,
    proteinGrams: 24.6,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-mor-6',
    name: 'Moroccan Sweet Mint Green Tea (Pot)',
    cuisine: 'Moroccan',
    category: 'Appetizers & Tapas',
    price: 180.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Gunpowder green tea brewed with fresh spearmint leaves and pure cane sugar.',
    caloriesKcal: 538,
    proteinGrams: 22.2,
    carbsGrams: 50.8,
    fatsGrams: 21.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
