/**
 * QuickBite Recipe & Culinary Catalog — Nepalese Kathmandu Thali & Sekuwa
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const NEPALESEHERITAGE_RECIPES: RecipeItem[] = [
  {
    id: 'dish-nep-1',
    name: 'Authentic Nepali Thakali Khasa Thali',
    cuisine: 'Nepalese',
    category: 'Signature Specialties',
    price: 420.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Traditional set with steamed basmati rice, black dal, rayo ko saag (mustard greens), gundruk achar, and chicken curry.',
    caloriesKcal: 802,
    proteinGrams: 49.0,
    carbsGrams: 65.2,
    fatsGrams: 30.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-nep-2',
    name: 'Charcoal Grilled Pork Sekuwa Skewers',
    cuisine: 'Nepalese',
    category: 'Appetizers & Tapas',
    price: 380.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Pork belly strips marinated in roasted cumin, timur pepper, mustard oil, and garlic grilled over charcoal.',
    caloriesKcal: 758,
    proteinGrams: 47.0,
    carbsGrams: 62.8,
    fatsGrams: 29.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-nep-3',
    name: 'Chatamari Nepali Rice Flour Pizza',
    cuisine: 'Nepalese',
    category: 'Main Course',
    price: 240.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Crispy thin rice crepe topped with minced meat, whisked egg, chopped tomatoes, and fresh coriander.',
    caloriesKcal: 604,
    proteinGrams: 40.0,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-nep-4',
    name: 'Choila Spicy Chargrilled Chicken Salad',
    cuisine: 'Nepalese',
    category: 'Desserts & Beverages',
    price: 320.0,
    prepTimeMinutes: 15,
    isVegetarian: true,
    description: 'Flame-grilled chicken tossed with raw mustard oil, roasted fenugreek seeds, green chillies, and garlic.',
    caloriesKcal: 692,
    proteinGrams: 27.8,
    carbsGrams: 59.2,
    fatsGrams: 26.8,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-nep-5',
    name: 'Gundruk Fermented Leaf Soup with Soya Beans',
    cuisine: 'Nepalese',
    category: 'Signature Specialties',
    price: 190.0,
    prepTimeMinutes: 12,
    isVegetarian: true,
    description: 'Tangy warming soup made from dried fermented mustard leaves and roasted soybeans.',
    caloriesKcal: 549,
    proteinGrams: 22.6,
    carbsGrams: 51.4,
    fatsGrams: 21.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-nep-6',
    name: 'Sel Roti Traditional Ring Rice Doughnuts (3 Pcs)',
    cuisine: 'Nepalese',
    category: 'Appetizers & Tapas',
    price: 160.0,
    prepTimeMinutes: 8,
    isVegetarian: true,
    description: 'Crispy sweet golden fried rice flour rings spiced with green cardamom and ghee.',
    caloriesKcal: 516,
    proteinGrams: 21.4,
    carbsGrams: 49.6,
    fatsGrams: 20.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
