/**
 * QuickBite Recipe & Culinary Catalog — Persian Saffron Chelo Kebabs
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const PERSIANGRILL_RECIPES: RecipeItem[] = [
  {
    id: 'dish-per-1',
    name: 'Chelo Kebab Koobideh with Saffron Rice',
    cuisine: 'Persian',
    category: 'Signature Specialties',
    price: 520.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Two skewers of hand-ground minced lamb seasoned with grated onions and sumac over buttered saffron basmati.',
    caloriesKcal: 912,
    proteinGrams: 54.0,
    carbsGrams: 71.2,
    fatsGrams: 34.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-2',
    name: 'Joojeh Saffron Lemon Chicken Kebab',
    cuisine: 'Persian',
    category: 'Appetizers & Tapas',
    price: 460.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Tender boneless chicken breast cubes marinated in Greek yogurt, bloomed saffron water, and fresh lime juice.',
    caloriesKcal: 846,
    proteinGrams: 51.0,
    carbsGrams: 67.6,
    fatsGrams: 32.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-3',
    name: 'Ghormeh Sabzi Persian Herb & Kidney Bean Stew',
    cuisine: 'Persian',
    category: 'Main Course',
    price: 440.0,
    prepTimeMinutes: 30,
    isVegetarian: false,
    description: 'Slow-simmered dark green stew with sautéed fenugreek, parsley, dried Omani limes, and tender braised beef.',
    caloriesKcal: 824,
    proteinGrams: 50.0,
    carbsGrams: 66.4,
    fatsGrams: 31.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-4',
    name: 'Kashk-e Bademjan Fried Eggplant Dip',
    cuisine: 'Persian',
    category: 'Desserts & Beverages',
    price: 290.0,
    prepTimeMinutes: 15,
    isVegetarian: true,
    description: 'Sautéed smoked aubergine whipped with fermented whey cream (kashk), crispy fried garlic, and dried mint.',
    caloriesKcal: 659,
    proteinGrams: 26.6,
    carbsGrams: 57.4,
    fatsGrams: 25.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-5',
    name: 'Shirazi Fresh Cucumber & Tomato Salad',
    cuisine: 'Persian',
    category: 'Signature Specialties',
    price: 210.0,
    prepTimeMinutes: 10,
    isVegetarian: true,
    description: 'Finely diced Persian cucumbers, firm ripe tomatoes, and red onions with verjuice and dried spearmint.',
    caloriesKcal: 571,
    proteinGrams: 23.4,
    carbsGrams: 52.6,
    fatsGrams: 22.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-6',
    name: 'Saffron Rosewater Pistachio Ice Cream (Bastani)',
    cuisine: 'Persian',
    category: 'Appetizers & Tapas',
    price: 260.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Traditional Persian ice cream churned with saffron, rosewater, salep, and frozen clotted cream chips.',
    caloriesKcal: 626,
    proteinGrams: 25.4,
    carbsGrams: 55.6,
    fatsGrams: 24.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
