/**
 * QuickBite Recipe & Culinary Catalog — Peruvian Nikkei & Fresh Ceviche
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const PERUVIANCEVICHE_RECIPES: RecipeItem[] = [
  {
    id: 'dish-per-1',
    name: 'Classic Sea Bass Ceviche with Leche de Tigre',
    cuisine: 'Peruvian',
    category: 'Signature Specialties',
    price: 520.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Fresh wild sea bass cured in zesty lime juice with red onions, aji amarillo chillies, choclo corn, and sweet potato.',
    caloriesKcal: 912,
    proteinGrams: 54.0,
    carbsGrams: 71.2,
    fatsGrams: 34.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-2',
    name: 'Lomo Saltado Wok-Seared Beef Strips',
    cuisine: 'Peruvian',
    category: 'Appetizers & Tapas',
    price: 490.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Flank steak sautéed with red onions, tomatoes, soy sauce, and pisco served over hand-cut fries and white rice.',
    caloriesKcal: 879,
    proteinGrams: 52.5,
    carbsGrams: 69.4,
    fatsGrams: 33.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-3',
    name: 'Causa Rellena Layered Potato Terrine with Crab',
    cuisine: 'Peruvian',
    category: 'Main Course',
    price: 380.0,
    prepTimeMinutes: 12,
    isVegetarian: false,
    description: 'Chilled yellow potato mash infused with lime and aji amarillo layered with jumbo lump crab salad and avocado.',
    caloriesKcal: 758,
    proteinGrams: 47.0,
    carbsGrams: 62.8,
    fatsGrams: 29.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-4',
    name: 'Anticuchos Charcoal Beef Heart Skewers',
    cuisine: 'Peruvian',
    category: 'Desserts & Beverages',
    price: 360.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Traditional grilled skewers marinated in aji panca chilli paste, red wine vinegar, and cumin.',
    caloriesKcal: 736,
    proteinGrams: 46.0,
    carbsGrams: 61.6,
    fatsGrams: 28.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-5',
    name: 'Arroz con Mariscos Saffron Seafood Rice',
    cuisine: 'Peruvian',
    category: 'Signature Specialties',
    price: 540.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Peruvian style paella loaded with calamari, prawns, and mussels cooked in white wine and aji paste.',
    caloriesKcal: 934,
    proteinGrams: 55.0,
    carbsGrams: 72.4,
    fatsGrams: 35.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-per-6',
    name: 'Tres Leches Cake with Cinnamon Whipped Cream',
    cuisine: 'Peruvian',
    category: 'Appetizers & Tapas',
    price: 260.0,
    prepTimeMinutes: 8,
    isVegetarian: false,
    description: 'Sponge cake soaked in three kinds of milk: evaporated, condensed, and heavy cream.',
    caloriesKcal: 626,
    proteinGrams: 41.0,
    carbsGrams: 55.6,
    fatsGrams: 24.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
