/**
 * QuickBite Recipe & Culinary Catalog — Royal Rajasthani Marwari Kitchen
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const RAJASTHANIMARWARI_RECIPES: RecipeItem[] = [
  {
    id: 'dish-raj-1',
    name: 'Dal Baati Churma Royal Thali Set',
    cuisine: 'Rajasthani',
    category: 'Signature Specialties',
    price: 420.0,
    prepTimeMinutes: 25,
    isVegetarian: true,
    description: 'Clay-oven baked whole wheat baatis dipped in desi ghee, served with panchmel dal and sweet powdered churma.',
    caloriesKcal: 802,
    proteinGrams: 31.8,
    carbsGrams: 65.2,
    fatsGrams: 30.8,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-raj-2',
    name: 'Laal Maas Fiery Mathania Chilli Mutton',
    cuisine: 'Rajasthani',
    category: 'Appetizers & Tapas',
    price: 540.0,
    prepTimeMinutes: 32,
    isVegetarian: false,
    description: 'Tender goat meat slow-cooked in traditional Mathania red chillies, mustard oil, garlic, and clove smoke.',
    caloriesKcal: 934,
    proteinGrams: 55.0,
    carbsGrams: 72.4,
    fatsGrams: 35.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-raj-3',
    name: 'Gatte Ki Sabzi Gram Flour Dumplings in Curd',
    cuisine: 'Rajasthani',
    category: 'Main Course',
    price: 280.0,
    prepTimeMinutes: 18,
    isVegetarian: true,
    description: 'Steamed spiced gram flour dumplings simmered in tangy spiced yogurt gravy.',
    caloriesKcal: 648,
    proteinGrams: 26.2,
    carbsGrams: 56.8,
    fatsGrams: 25.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-raj-4',
    name: 'Ker Sangri Desert Bean & Berry Masala',
    cuisine: 'Rajasthani',
    category: 'Desserts & Beverages',
    price: 340.0,
    prepTimeMinutes: 15,
    isVegetarian: true,
    description: 'Authentic wild desert berries and dried beans cooked with whole red chillies, amchur, and mustard oil.',
    caloriesKcal: 714,
    proteinGrams: 28.6,
    carbsGrams: 60.4,
    fatsGrams: 27.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-raj-5',
    name: 'Pyaaz Kachori with Mint & Tamarind Chutney (2 Pcs)',
    cuisine: 'Rajasthani',
    category: 'Signature Specialties',
    price: 180.0,
    prepTimeMinutes: 10,
    isVegetarian: false,
    description: 'Flaky deep-fried puffed pastries stuffed with spicy caramelized onion filling.',
    caloriesKcal: 538,
    proteinGrams: 37.0,
    carbsGrams: 50.8,
    fatsGrams: 21.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-raj-6',
    name: 'Traditional Ghevar with Rabdi & Pistachio',
    cuisine: 'Rajasthani',
    category: 'Appetizers & Tapas',
    price: 260.0,
    prepTimeMinutes: 8,
    isVegetarian: true,
    description: 'Honeycomb filigree sweet cake fried in pure ghee, soaked in sugar syrup, and topped with thick rabdi.',
    caloriesKcal: 626,
    proteinGrams: 25.4,
    carbsGrams: 55.6,
    fatsGrams: 24.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
