/**
 * QuickBite Recipe & Culinary Catalog — Nordic Smørrebrød & Arctic Seafood
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const SCANDINAVIANKITCHEN_RECIPES: RecipeItem[] = [
  {
    id: 'dish-sca-1',
    name: 'Gravlax Cured Salmon Smørrebrød on Rye',
    cuisine: 'Scandinavian',
    category: 'Signature Specialties',
    price: 460.0,
    prepTimeMinutes: 12,
    isVegetarian: false,
    description: 'Dill and aquavit cured salmon on dense seeded Danish rugbrød bread with sweet mustard dill sauce.',
    caloriesKcal: 846,
    proteinGrams: 51.0,
    carbsGrams: 67.6,
    fatsGrams: 32.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-sca-2',
    name: 'Swedish Meatballs with Lingonberry Jam & Mash',
    cuisine: 'Scandinavian',
    category: 'Appetizers & Tapas',
    price: 440.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Tender pork and beef meatballs in rich creamy gravy served with buttery potato mash and wild lingonberries.',
    caloriesKcal: 824,
    proteinGrams: 50.0,
    carbsGrams: 66.4,
    fatsGrams: 31.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-sca-3',
    name: 'Pickled Baltic Herring Duo with Sour Cream',
    cuisine: 'Scandinavian',
    category: 'Main Course',
    price: 320.0,
    prepTimeMinutes: 10,
    isVegetarian: false,
    description: 'Cured herring fillets in mustard dill and sweet onion marinades served with boiled baby new potatoes.',
    caloriesKcal: 692,
    proteinGrams: 44.0,
    carbsGrams: 59.2,
    fatsGrams: 26.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-sca-4',
    name: 'Arctic Cold-Water Prawn Open Sandwich',
    cuisine: 'Scandinavian',
    category: 'Desserts & Beverages',
    price: 480.0,
    prepTimeMinutes: 12,
    isVegetarian: false,
    description: 'Hand-peeled Greenland prawns piled high on buttered brioche with mayonnaise, boiled egg, and fresh dill.',
    caloriesKcal: 868,
    proteinGrams: 52.0,
    carbsGrams: 68.8,
    fatsGrams: 33.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-sca-5',
    name: 'Slow-Roasted Pork Belly with Crackling (Flæskesteg)',
    cuisine: 'Scandinavian',
    category: 'Signature Specialties',
    price: 520.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Danish style pork roast with extra crispy blistered crackling, braised red cabbage, and caramelized potatoes.',
    caloriesKcal: 912,
    proteinGrams: 54.0,
    carbsGrams: 71.2,
    fatsGrams: 34.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-sca-6',
    name: 'Cinnamon Cardamom Kanelbulle Swirl (2 Pcs)',
    cuisine: 'Scandinavian',
    category: 'Appetizers & Tapas',
    price: 210.0,
    prepTimeMinutes: 8,
    isVegetarian: false,
    description: 'Traditional Swedish braided yeast bun rich in ground green cardamom and pearl sugar.',
    caloriesKcal: 571,
    proteinGrams: 38.5,
    carbsGrams: 52.6,
    fatsGrams: 22.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
