/**
 * QuickBite Recipe & Culinary Catalog — Third-Wave Specialty Coffees & Roasts
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const SPECIALTYCOFFEE_RECIPES: RecipeItem[] = [
  {
    id: 'dish-spe-1',
    name: 'Geisha Pour-Over Filter Coffee (Ethiopian Single Origin)',
    cuisine: 'Beverages',
    category: 'Artisanal Specialty',
    price: 280.0,
    prepTimeMinutes: 6,
    isVegetarian: true,
    description: 'Rare Geisha varietal coffee beans hand-brewed via V60 dripper with floral jasmine and bergamot notes.',
    caloriesKcal: 288,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-spe-2',
    name: 'Spanish Iced Cortado with Condensed Milk',
    cuisine: 'Beverages',
    category: 'Signature Drinks',
    price: 220.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Double ristretto espresso shaken over ice with equal parts whole milk and sweet condensed milk.',
    caloriesKcal: 252,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: ["Dairy"],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-spe-3',
    name: 'Kyoto Slow Cold Drip Coffee (12-Hour Extraction)',
    cuisine: 'Beverages',
    category: 'Chilled Treats',
    price: 260.0,
    prepTimeMinutes: 4,
    isVegetarian: true,
    description: 'Slow Dutch water-drip cold brew presenting ultra-smooth dark chocolate and winey cherry notes.',
    caloriesKcal: 276,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-spe-4',
    name: 'Artisanal Flat White with Oat Milk & Latte Art',
    cuisine: 'Beverages',
    category: 'Infusions',
    price: 210.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Velvety microfoam steamed with organic oat milk poured over double espresso extraction.',
    caloriesKcal: 246,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: ["Dairy"],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-spe-5',
    name: 'Madagascan Vanilla Iced Cold Brew Latte',
    cuisine: 'Beverages',
    category: 'Artisanal Specialty',
    price: 240.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Steeped cold brew poured over chilled milk sweetened with real Madagascan bourbon vanilla bean syrup.',
    caloriesKcal: 264,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
  {
    id: 'dish-spe-6',
    name: 'Cascara Coffee Cherry Herbal Infusion',
    cuisine: 'Beverages',
    category: 'Signature Drinks',
    price: 180.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Brewed dried coffee cherry husks delivering sweet rosehip, hibiscus, and honey flavor profile.',
    caloriesKcal: 228,
    proteinGrams: 4.0,
    carbsGrams: 25.0,
    fatsGrams: 6.0,
    allergens: [],
    cookingInstructions: [
      'Step 1: Measure fresh botanical ingredients or extract espresso pull.',
      'Step 2: Blend, churn, or brew under precise temperature control.',
      'Step 3: Serve in insulated cold container with biodegradable straw / spoon.',
    ],
  },
];
