/**
 * QuickBite Recipe & Culinary Catalog — Alpine Swiss Fondue & Raclette
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const SWISSFONDUE_RECIPES: RecipeItem[] = [
  {
    id: 'dish-swi-1',
    name: 'Artisanal Gruyère & Vacherin Cheese Fondue (Serves 2)',
    cuisine: 'Swiss',
    category: 'Signature Specialties',
    price: 680.0,
    prepTimeMinutes: 20,
    isVegetarian: true,
    description: 'Melted blend of AOP Gruyère and Vacherin Fribourgeois with dry white wine, garlic, and kirsch served with bread cubes.',
    caloriesKcal: 1088,
    proteinGrams: 42.2,
    carbsGrams: 80.8,
    fatsGrams: 41.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-swi-2',
    name: 'Crispy Potato Rösti with Smoked Bacon & Fried Egg',
    cuisine: 'Swiss',
    category: 'Appetizers & Tapas',
    price: 360.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Golden grated pan-fried potato cake topped with melted Raclette cheese and sunny-side egg.',
    caloriesKcal: 736,
    proteinGrams: 46.0,
    carbsGrams: 61.6,
    fatsGrams: 28.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-swi-3',
    name: 'Zürcher Geschnetzeltes Sliced Veal in Mushroom Cream',
    cuisine: 'Swiss',
    category: 'Main Course',
    price: 560.0,
    prepTimeMinutes: 22,
    isVegetarian: false,
    description: 'Tender sliced veal tenderloin cooked in white wine, button mushrooms, and heavy double cream.',
    caloriesKcal: 956,
    proteinGrams: 56.0,
    carbsGrams: 73.6,
    fatsGrams: 36.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-swi-4',
    name: 'Traditional Swiss Raclette Plate with Baby Potatoes',
    cuisine: 'Swiss',
    category: 'Desserts & Beverages',
    price: 480.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Molten wheel-scraped Raclette cheese poured over boiled new potatoes, cornichons, and pickled pearl onions.',
    caloriesKcal: 868,
    proteinGrams: 52.0,
    carbsGrams: 68.8,
    fatsGrams: 33.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-swi-5',
    name: 'Bündnerfleisch Air-Dried Beef Carpaccio',
    cuisine: 'Swiss',
    category: 'Signature Specialties',
    price: 420.0,
    prepTimeMinutes: 10,
    isVegetarian: false,
    description: 'Paper-thin slices of dry-cured Grisons beef served with freshly cracked black pepper and olive oil.',
    caloriesKcal: 802,
    proteinGrams: 49.0,
    carbsGrams: 65.2,
    fatsGrams: 30.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-swi-6',
    name: 'Engadiner Nusstorte Walnut Caramel Tart',
    cuisine: 'Swiss',
    category: 'Appetizers & Tapas',
    price: 240.0,
    prepTimeMinutes: 8,
    isVegetarian: true,
    description: 'Traditional Swiss shortcrust pastry filled with roasted caramelized chopped walnuts and honey.',
    caloriesKcal: 604,
    proteinGrams: 24.6,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
