/**
 * QuickBite Recipe & Culinary Catalog — Royal Thai Lemongrass Curries & Street Wok
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const THAIWOKCURRY_RECIPES: RecipeItem[] = [
  {
    id: 'dish-tha-1',
    name: 'Thai Red Duck Curry with Lychee',
    cuisine: 'Thai',
    category: 'Signature Item',
    price: 520.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Roasted duck breast simmered in fragrant red coconut curry with sweet lychees, cherry tomatoes, and Thai basil.',
    caloriesKcal: 892,
    proteinGrams: 52.0,
    carbsGrams: 74.4,
    fatsGrams: 32.8,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-tha-2',
    name: 'Bangkok Street Style Crab Fried Rice',
    cuisine: 'Thai',
    category: 'Appetizers',
    price: 460.0,
    prepTimeMinutes: 20,
    isVegetarian: false,
    description: 'Jasmine rice wok-tossed with jumbo lump crab meat, eggs, scallions, and prik nam pla chilli fish sauce.',
    caloriesKcal: 826,
    proteinGrams: 49.0,
    carbsGrams: 70.2,
    fatsGrams: 30.4,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-tha-3',
    name: 'Som Tum Green Papaya Salad',
    cuisine: 'Thai',
    category: 'Entrees',
    price: 280.0,
    prepTimeMinutes: 12,
    isVegetarian: true,
    description: 'Pounded crunchy green papaya with garlic, birds eye chillies, dried shrimp, peanuts, and tamarind palm sugar dressing.',
    caloriesKcal: 628,
    proteinGrams: 25.2,
    carbsGrams: 57.6,
    fatsGrams: 23.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-tha-4',
    name: 'Tom Yum Goong Spicy Prawn Soup',
    cuisine: 'Thai',
    category: 'Desserts',
    price: 380.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Hot and sour aromatic broth infused with lemongrass, kaffir lime leaves, galangal, and fresh tiger prawns.',
    caloriesKcal: 738,
    proteinGrams: 45.0,
    carbsGrams: 64.6,
    fatsGrams: 27.2,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-tha-5',
    name: 'Crispy Thai Spring Rolls with Sweet Plum Dip',
    cuisine: 'Thai',
    category: 'Signature Item',
    price: 240.0,
    prepTimeMinutes: 12,
    isVegetarian: false,
    description: 'Glass noodles, shredded cabbage, and wood ear mushrooms fried in thin wrappers with dipping sauce.',
    caloriesKcal: 584,
    proteinGrams: 38.0,
    carbsGrams: 54.8,
    fatsGrams: 21.6,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
  {
    id: 'dish-tha-6',
    name: 'Warm Mango Sticky Rice with Sweet Coconut Cream',
    cuisine: 'Thai',
    category: 'Appetizers',
    price: 280.0,
    prepTimeMinutes: 10,
    isVegetarian: false,
    description: 'Sweetened glutinous rice steamed in coconut milk served with ripe Alphonso mango slices.',
    caloriesKcal: 628,
    proteinGrams: 40.0,
    carbsGrams: 57.6,
    fatsGrams: 23.2,
    allergens: ["Gluten", "Seafood/Meat"],
    cookingInstructions: [
      'Step 1: Inspect ingredient quality and preheat specialized culinary cooking station.',
      'Step 2: Execute authentic regional cooking technique with precise temperature control.',
      'Step 3: Garnish with fresh herbs and package into insulated eco-friendly containers.',
    ],
  },
];
