/**
 * QuickBite Recipe & Culinary Catalog — Tibetan Himalayan Momos & Thukpa
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const TIBETANHIMALAYAN_RECIPES: RecipeItem[] = [
  {
    id: 'dish-tib-1',
    name: 'Steamed Juicy Chicken Momos (8 Pcs)',
    cuisine: 'Tibetan',
    category: 'Signature Specialties',
    price: 240.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Hand-pinched thin flour dumplings filled with minced spiced chicken, spring onions, and garlic served with spicy tomato sesame chutney.',
    caloriesKcal: 604,
    proteinGrams: 40.0,
    carbsGrams: 54.4,
    fatsGrams: 23.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-tib-2',
    name: 'Crispy Pan-Fried Buff Kothey Momos (8 Pcs)',
    cuisine: 'Tibetan',
    category: 'Appetizers & Tapas',
    price: 260.0,
    prepTimeMinutes: 18,
    isVegetarian: false,
    description: 'Half-steamed, half-crispy pan-fried dumplings with tender savory filling and hot chilli dip.',
    caloriesKcal: 626,
    proteinGrams: 41.0,
    carbsGrams: 55.6,
    fatsGrams: 24.4,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-tib-3',
    name: 'Traditional Himalayan Thukpa Noodle Soup',
    cuisine: 'Tibetan',
    category: 'Main Course',
    price: 280.0,
    prepTimeMinutes: 20,
    isVegetarian: true,
    description: 'Hearty clear spiced broth with hand-pulled noodles, shredded vegetables, chicken, and fresh coriander.',
    caloriesKcal: 648,
    proteinGrams: 26.2,
    carbsGrams: 56.8,
    fatsGrams: 25.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-tib-4',
    name: 'Shabalay Tibetan Deep-Fried Meat Pies (2 Pcs)',
    cuisine: 'Tibetan',
    category: 'Desserts & Beverages',
    price: 220.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Crispy semi-circular pastries stuffed with seasoned minced meat and ginger.',
    caloriesKcal: 582,
    proteinGrams: 39.0,
    carbsGrams: 53.2,
    fatsGrams: 22.8,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-tib-5',
    name: 'Tingmo Steamed Lotus Bread with Spicy Veg Curry',
    cuisine: 'Tibetan',
    category: 'Signature Specialties',
    price: 220.0,
    prepTimeMinutes: 15,
    isVegetarian: true,
    description: 'Soft twisted steamed buns served with rich vegetable and cottage cheese curry.',
    caloriesKcal: 582,
    proteinGrams: 23.8,
    carbsGrams: 53.2,
    fatsGrams: 22.8,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-tib-6',
    name: 'Sweet Tibetan Butter Tea (Po Cha)',
    cuisine: 'Tibetan',
    category: 'Appetizers & Tapas',
    price: 120.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Churned black tea with yak butter, milk, and Himalayan pink rock salt.',
    caloriesKcal: 472,
    proteinGrams: 19.8,
    carbsGrams: 47.2,
    fatsGrams: 18.8,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
