/**
 * QuickBite Recipe & Culinary Catalog — Vietnamese Saigon Pho & Banh Mi
 * Complete dish specifications, ingredients, allergens, preparation steps, and pricing.
 */

import { RecipeItem } from './northIndianCatalog.js';

export const VIETNAMESEPHO_RECIPES: RecipeItem[] = [
  {
    id: 'dish-vie-1',
    name: 'Traditional Beef Flank Pho Noodle Soup',
    cuisine: 'Vietnamese',
    category: 'Signature Specialties',
    price: 460.0,
    prepTimeMinutes: 25,
    isVegetarian: true,
    description: '16-hour simmered star anise beef marrow broth, flat rice noodles, sliced flank steak, and fresh Thai basil.',
    caloriesKcal: 846,
    proteinGrams: 33.4,
    carbsGrams: 67.6,
    fatsGrams: 32.4,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-vie-2',
    name: 'Crispy Pork Belly Banh Mi Baguette',
    cuisine: 'Vietnamese',
    category: 'Appetizers & Tapas',
    price: 340.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Crusty French baguette stuffed with five-spice roasted pork belly, chicken pate, pickled daikon, and cilantro.',
    caloriesKcal: 714,
    proteinGrams: 45.0,
    carbsGrams: 60.4,
    fatsGrams: 27.6,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-vie-3',
    name: 'Fresh Summer Rice Paper Rolls with Peanut Dip (4 Pcs)',
    cuisine: 'Vietnamese',
    category: 'Main Course',
    price: 290.0,
    prepTimeMinutes: 12,
    isVegetarian: true,
    description: 'Translucent rice wrappers filled with tiger prawns, vermicelli noodles, mint, and crushed peanut hoisin dip.',
    caloriesKcal: 659,
    proteinGrams: 26.6,
    carbsGrams: 57.4,
    fatsGrams: 25.6,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-vie-4',
    name: 'Caramelized Claypot Fish (Ca Kho To)',
    cuisine: 'Vietnamese',
    category: 'Desserts & Beverages',
    price: 480.0,
    prepTimeMinutes: 25,
    isVegetarian: false,
    description: 'Fish steaks braised in dark palm sugar caramel, fish sauce, and cracked black tellicherry peppercorns.',
    caloriesKcal: 868,
    proteinGrams: 52.0,
    carbsGrams: 68.8,
    fatsGrams: 33.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-vie-5',
    name: 'Saigon Crispy Spring Rolls (Cha Gio)',
    cuisine: 'Vietnamese',
    category: 'Signature Specialties',
    price: 280.0,
    prepTimeMinutes: 15,
    isVegetarian: false,
    description: 'Minced pork, wood ear mushrooms, and glass noodles wrapped in rice paper and fried extra crispy.',
    caloriesKcal: 648,
    proteinGrams: 42.0,
    carbsGrams: 56.8,
    fatsGrams: 25.2,
    allergens: ["Gluten", "Poultry/Meat/Seafood"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
  {
    id: 'dish-vie-6',
    name: 'Vietnamese Iced Drip Coffee with Sweet Condensed Milk',
    cuisine: 'Vietnamese',
    category: 'Appetizers & Tapas',
    price: 180.0,
    prepTimeMinutes: 5,
    isVegetarian: true,
    description: 'Dark roasted Robusta coffee brewed via traditional Phin metal filter poured over ice and condensed milk.',
    caloriesKcal: 538,
    proteinGrams: 22.2,
    carbsGrams: 50.8,
    fatsGrams: 21.2,
    allergens: ["Dairy", "Gluten"],
    cookingInstructions: [
      'Step 1: Prep fresh raw ingredients and preheat specialized culinary station.',
      'Step 2: Sauté aromatics and blend reduction simmer for optimal flavor integration.',
      'Step 3: Plate freshly cooked portion into food-grade tamper-evident thermal container.',
    ],
  },
];
